# -*- coding: utf-8 -*-
"""Bereich AL · Alkohole — AL-03 bis AL-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "AL-03",
    "title": "Struktur und Eigenschaften der Alkohole",
    "leitidee": "B2",
    "standards": ["K1", "K2.4", "K3.3"],
    "klasse": 10,
    "wortspeicher": ["die Wasserstoffbrücke", "die Löslichkeit", "die Siedetemperatur",
                     "der hydrophile Teil", "der hydrophobe Teil"],
    "worterklaerungen": {
        "hydrophil": "Wasserfreundlich. Der polare Teil eines Moleküls.",
        "hydrophob": "Wasserabweisend. Der unpolare Teil eines Moleküls."
    },
    "can_do": {
        "A": "Ich weiß, dass kurze Alkohole wasserlöslich sind und lange nicht.",
        "B": "Ich erkläre Löslichkeit und Siedetemperatur mit den Wasserstoffbrücken.",
        "C": "Ich sage anhand der Struktur Eigenschaften voraus und begründe die Vorhersage."
    },
    "lernkarten": {
        "A": karte("Zwei Teile im Molekül",
                   "Ein Alkoholmolekül hat zwei Teile.",
                   ["Die OH-Gruppe mag Wasser.", "Die Kohlenstoffkette mag Wasser nicht."],
                   "Kurze Kette: löslich. Lange Kette: unlöslich.",
                   visual={"type": "struktur", "kette": 4, "gruppe": "oh", "name": "Butan-1-ol",
                           "alt": "Strukturformel von Butanol mit langer Kette und OH-Gruppe."},
                   beispiel={"titel": "Was sich löst", "aufgabe": "Methanol oder Hexanol?",
                             "schritte": ["Methanol hat eine kurze Kette.",
                                          "Es löst sich vollständig.",
                                          "Hexanol hat eine lange Kette."],
                             "ergebnis": "Hexanol löst sich kaum."}),
        "B": karte("Zwei Kräfte im Wettstreit",
                   "In jedem Alkoholmolekül konkurrieren zwei Bereiche: der hydrophile Kopf und der hydrophobe Schwanz. Welcher überwiegt, entscheidet über die Eigenschaften.",
                   ["Die OH-Gruppe bildet Wasserstoffbrücken — zu anderen Alkoholmolekülen und zu Wasser.",
                    "Deshalb sieden Alkohole deutlich höher als Alkane vergleichbarer Masse: Ethanol 78 °C, Propan −42 °C.",
                    "Deshalb sind Methanol, Ethanol und Propanol mit Wasser in jedem Verhältnis mischbar.",
                    "Ab Butanol nimmt die Löslichkeit deutlich ab, ab Hexanol ist sie gering. Die unpolare Kette überwiegt.",
                    "Innerhalb der Reihe steigen die Siedetemperaturen weiter — dort addieren sich Wasserstoffbrücken und van-der-Waals-Kräfte."],
                   "Kopf und Schwanz konkurrieren — das Verhältnis entscheidet über die Löslichkeit.",
                   visual={"type": "diagramm", "titel": "Siedetemperaturen der Alkanole",
                           "xtitel": "Zahl der C-Atome", "ytitel": "Siedetemperatur in °C",
                           "punkte": [[1, 65, "Methanol"], [2, 78], [3, 97], [4, 118], [5, 138]],
                           "ymin": 0, "ymax": 160,
                           "alt": "Siedetemperaturen der Alkanole steigen mit der Kettenlänge."}),
        "C": karte("Eigenschaften vorhersagen",
                   "Aus der Struktur lassen sich Eigenschaften ableiten — das ist der eigentliche Zweck des Struktur-Eigenschafts-Konzepts.",
                   ["Frage 1: Wie lang ist die unpolare Kette? Je länger, desto geringer die Wasserlöslichkeit und desto höher der Siedepunkt.",
                    "Frage 2: Wie viele OH-Gruppen gibt es? Mehr OH-Gruppen bedeuten mehr Wasserstoffbrücken, höhere Siedetemperatur und bessere Löslichkeit — Glycerin mit drei OH-Gruppen siedet bei 290 °C.",
                    "Frage 3: Wo sitzt die OH-Gruppe? Endständig ist sie besser zugänglich als in der Kettenmitte.",
                    "Die Vorhersage gilt für Trends, nicht für exakte Werte. Sie erlaubt aber, zwei Stoffe zuverlässig zu ordnen."],
                   "Kettenlänge, Zahl der OH-Gruppen, Position — drei Fragen genügen für eine Vorhersage.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "oh", "name": "Propan-1-ol",
                           "alt": "Strukturformel von Propanol."})
    },
    "formelkarte": {"formeln": ["Siedetemperaturen: Methanol 65 · Ethanol 78 · Propanol 97 · Butanol 118 °C"],
                    "saetze": ["Die OH-Gruppe ist hydrophil, die Kette hydrophob.",
                               "Kurzkettige Alkohole sind mit Wasser mischbar, ab Butanol nimmt es ab.",
                               "Mehr OH-Gruppen: höherer Siedepunkt, bessere Löslichkeit.",
                               "Alkohole sieden höher als Alkane vergleichbarer Masse."]},
    "tasks": [
        aufgabe("AL03-A1-001", "A", 1, "choice",
                "Welcher Alkohol löst sich vollständig in Wasser?",
                options=["Ethanol", "Hexanol", "Octanol"], answer=0,
                hints=["Kurze Ketten lösen sich besser.", "Ethanol hat zwei C-Atome.", "Ethanol."],
                solution="Ethanol hat eine kurze Kette und ist mit Wasser in jedem Verhältnis mischbar.",
                tags=["alkohole"], spiral=["W-LOES"]),
        aufgabe("AL03-A2-002", "A", 2, "choice",
                "Welcher Teil des Alkoholmoleküls mag Wasser?",
                options=["die OH-Gruppe", "die Kohlenstoffkette", "beide gleich"], answer=0,
                hints=["Wasser ist polar.", "Welcher Teil ist auch polar?", "Die OH-Gruppe."],
                solution="Die polare OH-Gruppe bildet Wasserstoffbrücken zum Wasser — sie ist hydrophil.",
                misconceptions=[fv("polar_unpolar_vertauscht", 1,
                                   "Die Kohlenstoffkette ist unpolar und wasserabweisend.",
                                   "polar_unpolar_vertauscht")],
                tags=["alkohole"], spiral=["W-LOES"]),
        aufgabe("AL03-A3-003", "A", 3, "numeric",
                "Ethanol siedet bei 78 °C, Propanol bei 97 °C. Wie groß ist der Unterschied?",
                answer=19, unit_label="°C", tolerance=1,
                hints=["97 − 78.", "Die Differenz.", "19 °C."],
                solution="97 °C − 78 °C = 19 °C",
                tags=["alkohole", "rechnen"], spiral=["W-EINH"]),
        aufgabe("AL03-A4-004", "A", 4, "choice",
                "Was passiert mit der Siedetemperatur, wenn die Kette länger wird?",
                options=["Sie steigt.", "Sie sinkt.", "Sie bleibt gleich."], answer=0,
                hints=["Wie bei den Alkanen.", "Mehr Kontaktfläche.", "Sie steigt."],
                solution="Mit wachsender Kettenlänge nehmen die van-der-Waals-Kräfte zu — die Siedetemperatur steigt.",
                tags=["alkohole"], spiral=["W-ORG"]),
        aufgabe("AL03-B1-005", "B", 1, "choice",
                "Warum siedet Ethanol (78 °C) höher als Propan (−42 °C)?",
                options=["Zwischen Ethanolmolekülen wirken Wasserstoffbrücken.",
                         "Ethanol ist schwerer.",
                         "Propan ist verzweigt."],
                answer=0,
                hints=["Beide haben ähnliche Masse.",
                       "Verschieden ist die funktionelle Gruppe.",
                       "Die OH-Gruppe bildet Brücken."],
                solution="Trotz ähnlicher Masse siedet Ethanol 120 °C höher. Die Wasserstoffbrücken zwischen den OH-Gruppen sind viel stärker als die van-der-Waals-Kräfte im Propan.",
                tags=["alkohole", "bbr"], spiral=["W-ORG"]),
        aufgabe("AL03-B2-006", "B", 2, "choice",
                "Ab welchem Alkanol nimmt die Wasserlöslichkeit deutlich ab?",
                options=["ab Butanol", "ab Ethanol", "ab Octanol"], answer=0,
                hints=["Methanol, Ethanol und Propanol mischen sich vollständig.",
                       "Beim nächsten Glied kippt es.",
                       "Butanol."],
                solution="Bis Propanol sind die Alkohole mit Wasser vollständig mischbar. Ab Butanol überwiegt die unpolare Kette und die Löslichkeit nimmt deutlich ab.",
                tags=["alkohole", "bbr"], spiral=["W-LOES"]),
        aufgabe("AL03-B2-007", "B", 2, "choice",
                "Warum löst sich Ethanol sowohl in Wasser als auch in Benzin?",
                options=["Es hat einen polaren und einen unpolaren Teil.",
                         "Es ist besonders leicht.",
                         "Es ist ein Gemisch."],
                answer=0,
                hints=["Das Molekül hat zwei Bereiche.",
                       "Einen polaren und einen unpolaren.",
                       "Deshalb vermittelt es zwischen beiden."],
                solution="Die OH-Gruppe passt zum polaren Wasser, die kurze Kohlenstoffkette zum unpolaren Benzin. Deshalb ist Ethanol ein vielseitiges Lösungsmittel.",
                tags=["alkohole", "bbr"], spiral=["W-LOES"]),
        aufgabe("AL03-B3-008", "B", 3, "choice",
                "Warum siedet Glycerin mit drei OH-Gruppen bei 290 °C?",
                options=["Drei OH-Gruppen bilden sehr viele Wasserstoffbrücken.",
                         "Glycerin ist sehr schwer.",
                         "Glycerin ist unpolar."],
                answer=0,
                hints=["Wie viele Brücken kann ein Molekül bilden?",
                       "Je OH-Gruppe mehrere.",
                       "Drei Gruppen bedeuten viele Brücken."],
                solution="Jede OH-Gruppe bildet Wasserstoffbrücken. Mit drei davon ist die Anziehung zwischen den Molekülen so stark, dass Glycerin erst bei 290 °C siedet und zähflüssig ist.",
                tags=["alkohole", "msa"], spiral=["W-ORG"]),
        aufgabe("AL03-B3-009", "B", 3, "multi",
                "Vergleiche Ethanol (M = 46 g/mol, Sdp. 78 °C) und Propan (M = 44 g/mol, Sdp. −42 °C).",
                fields=[
                    {"label": "Massenunterschied", "answer": 2, "unit_label": "g/mol", "tolerance": 0.5},
                    {"label": "Siedepunktunterschied", "answer": 120, "unit_label": "°C", "tolerance": 2}
                ],
                hints=["46 − 44.",
                       "78 − (−42).",
                       "Auf das Vorzeichen achten."],
                solution="Masse: 2 g/mol Unterschied\nSiedepunkt: 78 − (−42) = 120 °C Unterschied\nDie Masse erklärt das nicht — es sind die Wasserstoffbrücken.",
                tags=["alkohole", "rechnen", "bbr"], spiral=["W-EINH"]),
        aufgabe("AL03-B4-010", "B", 4, "choice",
                "Warum wird Ethanol als Lösungsmittel für Duftstoffe verwendet?",
                options=["Es löst polare und unpolare Stoffe und verdunstet rückstandsfrei.",
                         "Es riecht besonders gut.",
                         "Es ist besonders billig."],
                answer=0,
                hints=["Welche zwei Eigenschaften braucht ein Parfümlösungsmittel?",
                       "Gute Lösefähigkeit und Verdunsten.",
                       "Ethanol hat beides."],
                solution="Ethanol löst durch seinen Doppelcharakter viele Duftstoffe und verdunstet bei 78 °C rückstandsfrei. Beides zusammen macht es zum Standardlösungsmittel in der Kosmetik.",
                tags=["alkohole", "anwenden", "msa"], spiral=["W-LOES"]),
        aufgabe("AL03-C2-011", "C", 2, "choice",
                "Ordne nach steigender Wasserlöslichkeit: Butanol, Methanol, Hexanol.",
                options=["Hexanol < Butanol < Methanol", "Methanol < Butanol < Hexanol", "alle gleich"],
                answer=0,
                hints=["Kurze Kette heißt bessere Löslichkeit.",
                       "Methanol hat die kürzeste.",
                       "Hexanol die längste."],
                solution="Je länger die unpolare Kette, desto schlechter die Löslichkeit: Hexanol < Butanol < Methanol.",
                misconceptions=[fv("polar_unpolar_vertauscht", 1,
                                   "Die Reihenfolge ist umgekehrt: Lange Ketten lösen sich schlechter.",
                                   "polar_unpolar_vertauscht")],
                tags=["alkohole", "msa"], spiral=["W-LOES"]),
        aufgabe("AL03-C3-012", "C", 3, "choice",
                "Warum ist Glycerin in Kosmetika als Feuchthaltemittel geeignet?",
                options=["Seine drei OH-Gruppen binden Wassermoleküle über Wasserstoffbrücken.",
                         "Es ist ölig und dichtet ab.",
                         "Es tötet Bakterien ab."],
                answer=0,
                hints=["Was macht Glycerin mit Wasser?",
                       "Es bindet es.",
                       "Über die OH-Gruppen."],
                solution="Die drei OH-Gruppen bilden Wasserstoffbrücken zu Wassermolekülen und halten sie fest. Deshalb bleibt die Haut länger feucht — Glycerin wirkt hygroskopisch.",
                tags=["alkohole", "anwenden", "msa"], spiral=["W-LOES"]),
        aufgabe("AL03-C3-013", "C", 3, "choice",
                "Ein unbekannter Alkohol hat 7 C-Atome. Welche Vorhersage triffst du?",
                options=["Er ist in Wasser kaum löslich und siedet über 170 °C.",
                         "Er ist gut wasserlöslich und siedet unter 100 °C.",
                         "Er ist gasförmig."],
                answer=0,
                hints=["Sieben C-Atome sind eine lange Kette.",
                       "Der Trend geht Richtung schlecht löslich.",
                       "Und der Siedepunkt steigt mit jeder CH₂-Gruppe."],
                solution="Bei sieben C-Atomen überwiegt die unpolare Kette deutlich — die Löslichkeit ist gering. Der Trend der Siedetemperaturen (65, 78, 97, 118, 138 …) führt für C₇ auf über 170 °C.",
                tags=["alkohole", "vorhersage", "msa"], spiral=["W-ORG"]),
        aufgabe("AL03-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Alkohole lösen sich in Wasser, weil sie flüssig sind.“ Wie bewertest du das?",
                options=["Falsch — auch Benzin und Öl sind flüssig und lösen sich nicht; entscheidend ist die polare OH-Gruppe.",
                         "Richtig.",
                         "Falsch — Alkohole lösen sich gar nicht."],
                answer=0,
                hints=["Ist jede Flüssigkeit mit Wasser mischbar?",
                       "Nein — Öl zum Beispiel nicht.",
                       "Also liegt es nicht am Aggregatzustand."],
                solution="Der Aggregatzustand sagt nichts über die Löslichkeit: Benzin und Öl sind flüssig und mischen sich nicht mit Wasser. Entscheidend ist die polare OH-Gruppe und ihr Verhältnis zur unpolaren Kette.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 1,
                                   "Flüssig zu sein genügt nicht — Öl ist ebenfalls flüssig.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["alkohole", "bewerten", "msa"], spiral=["W-LOES"])
    ]
})

E.append({
    "unit": "AL-04",
    "title": "Mehrwertige Alkohole: Glycol und Glycerin",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["mehrwertig", "das Glycol", "das Glycerin", "das Frostschutzmittel",
                     "hygroskopisch", "der Zuckeraustauschstoff"],
    "worterklaerungen": {
        "mehrwertig": "Ein Alkohol mit mehr als einer OH-Gruppe.",
        "hygroskopisch": "Zieht Wasser aus der Luft an und bindet es."
    },
    "can_do": {
        "A": "Ich weiß, dass Glycerin drei OH-Gruppen hat, und nenne eine Verwendung.",
        "B": "Ich erkläre die Eigenschaften mehrwertiger Alkohole mit der Zahl der OH-Gruppen.",
        "C": "Ich bewerte die Verwendung von Glycol und Glycerin unter Sicherheitsaspekten."
    },
    "lernkarten": {
        "A": karte("Mehr als eine OH-Gruppe",
                   "Manche Alkohole haben mehrere OH-Gruppen.",
                   ["Glycol hat zwei.", "Glycerin hat drei."],
                   "Mehr OH-Gruppen: dickflüssiger und besser wasserlöslich.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "oh", "name": "Glycerin (dreiwertig)",
                           "alt": "Strukturformel eines dreiwertigen Alkohols."},
                   beispiel={"titel": "Glycerin", "aufgabe": "Wozu wird Glycerin verwendet?",
                             "schritte": ["In Handcreme.", "In Zahnpasta.",
                                          "Es hält Feuchtigkeit."],
                             "ergebnis": "Als Feuchthaltemittel."}),
        "B": karte("Was mehrere OH-Gruppen bewirken",
                   "Jede zusätzliche OH-Gruppe verstärkt alle Effekte, die schon bei den einwertigen Alkoholen zu sehen waren.",
                   ["Mehr Wasserstoffbrücken bedeuten höhere Siedetemperatur: Ethanol 78 °C, Glycol 197 °C, Glycerin 290 °C.",
                    "Sie bedeuten auch höhere Zähigkeit — Glycerin ist sirupartig.",
                    "Und bessere Wasserlöslichkeit, weil mehr polare Gruppen zur Verfügung stehen.",
                    "Glycol wird als Frostschutzmittel eingesetzt: Es senkt den Gefrierpunkt des Kühlwassers deutlich.",
                    "Glycerin ist hygroskopisch und wird als Feuchthaltemittel in Kosmetik und Lebensmitteln verwendet."],
                   "Jede OH-Gruppe mehr: höherer Siedepunkt, zäher, besser löslich.",
                   visual={"type": "diagramm", "titel": "Siedetemperatur und Zahl der OH-Gruppen",
                           "xtitel": "Zahl der OH-Gruppen", "ytitel": "Siedetemperatur in °C",
                           "punkte": [[1, 78, "Ethanol"], [2, 197, "Glycol"], [3, 290, "Glycerin"]],
                           "ymin": 0, "ymax": 320,
                           "alt": "Die Siedetemperatur steigt mit der Zahl der OH-Gruppen."}),
        "C": karte("Zwei ähnliche Stoffe, zwei Bewertungen",
                   "Glycol und Glycerin sind chemisch verwandt und in der Wirkung auf den Körper völlig verschieden — ein weiteres Beispiel für die Bedeutung kleiner Bauunterschiede.",
                   ["Glycerin ist unbedenklich und in Lebensmitteln als Zusatzstoff zugelassen.",
                    "Glycol ist giftig: Es wird im Körper zu Oxalsäure abgebaut, die in den Nieren Kristalle bildet.",
                    "Gefährlich wird das durch den süßlichen Geschmack — Kinder und Haustiere sind besonders gefährdet.",
                    "Deshalb wird Frostschutzmittel bitter vergällt und farbig eingefärbt.",
                    "Fachlich lehrreich: Verwandtschaft im Bau erlaubt keine Rückschlüsse auf die Wirkung. Das gilt auch für Methanol und Ethanol."],
                   "Ähnlicher Bau bedeutet nicht ähnliche Wirkung.",
                   visual={"type": "struktur", "kette": 2, "gruppe": "oh", "name": "Glycol (zweiwertig)",
                           "alt": "Strukturformel eines zweiwertigen Alkohols."})
    },
    "formelkarte": {"formeln": ["Glycol C₂H₄(OH)₂ · Glycerin C₃H₅(OH)₃"],
                    "saetze": ["Mehrwertig: mehr als eine OH-Gruppe.",
                               "Siedetemperaturen: Ethanol 78 · Glycol 197 · Glycerin 290 °C.",
                               "Glycerin ist unbedenklich, Glycol giftig.",
                               "Frostschutzmittel wird bitter vergällt und eingefärbt."]},
    "tasks": [
        aufgabe("AL04-A1-001", "A", 1, "numeric",
                "Wie viele OH-Gruppen hat Glycerin?",
                answer=3, tolerance=0,
                hints=["Es ist ein dreiwertiger Alkohol.", "Drei OH-Gruppen.", "3."],
                solution="Glycerin hat drei OH-Gruppen — es ist ein dreiwertiger Alkohol.",
                tags=["mehrwertig"], spiral=["W-ORG"]),
        aufgabe("AL04-A2-002", "A", 2, "choice",
                "Wozu wird Glycerin in Handcreme verwendet?",
                options=["Es hält Feuchtigkeit in der Haut.", "Es desinfiziert.", "Es färbt die Creme."],
                answer=0,
                hints=["Glycerin bindet Wasser.", "Deshalb bleibt die Haut feucht.", "Als Feuchthaltemittel."],
                solution="Glycerin bindet Wassermoleküle über seine OH-Gruppen und hält so die Haut feucht.",
                tags=["mehrwertig"], spiral=["W-LOES"]),
        aufgabe("AL04-A3-003", "A", 3, "choice",
                "Warum ist Glycerin dickflüssig?",
                options=["Die vielen OH-Gruppen bilden viele Wasserstoffbrücken.",
                         "Es enthält Zucker.", "Es ist kalt."],
                answer=0,
                hints=["Drei OH-Gruppen je Molekül.",
                       "Jede bildet Brücken.",
                       "Die Moleküle halten stark zusammen."],
                solution="Drei OH-Gruppen je Molekül bilden sehr viele Wasserstoffbrücken. Die Moleküle gleiten schwer aneinander vorbei — Glycerin ist sirupartig.",
                tags=["mehrwertig"], spiral=["W-ORG"]),
        aufgabe("AL04-A4-004", "A", 4, "choice",
                "Wofür wird Glycol verwendet?",
                options=["als Frostschutzmittel", "als Süßstoff", "als Duftstoff"], answer=0,
                hints=["Es kommt ins Kühlwasser.", "Es senkt den Gefrierpunkt.", "Frostschutzmittel."],
                solution="Glycol senkt den Gefrierpunkt von Wasser deutlich und wird deshalb als Frostschutzmittel eingesetzt.",
                tags=["mehrwertig"], spiral=["W-LOES"]),
        aufgabe("AL04-B1-005", "B", 1, "choice",
                "Warum siedet Glycerin (290 °C) so viel höher als Ethanol (78 °C)?",
                options=["Drei OH-Gruppen bilden weit mehr Wasserstoffbrücken als eine.",
                         "Glycerin ist viel schwerer.",
                         "Glycerin ist unpolar."],
                answer=0,
                hints=["Wie viele OH-Gruppen hat jedes Molekül?",
                       "Drei gegen eine.",
                       "Mehr Brücken heißt höherer Siedepunkt."],
                solution="Jede OH-Gruppe bildet Wasserstoffbrücken. Mit drei davon ist die Anziehung zwischen den Molekülen so stark, dass Glycerin erst bei 290 °C siedet.",
                tags=["mehrwertig", "bbr"], spiral=["W-ORG"]),
        aufgabe("AL04-B2-006", "B", 2, "choice",
                "Warum senkt Glycol den Gefrierpunkt von Wasser?",
                options=["Die gelösten Moleküle stören den Aufbau des Eisgitters.",
                         "Glycol erwärmt das Wasser.",
                         "Glycol verdampft."],
                answer=0,
                hints=["Was passiert beim Gefrieren?",
                       "Ein regelmäßiges Gitter entsteht.",
                       "Fremde Moleküle stören dabei."],
                solution="Gelöste Teilchen stören den regelmäßigen Aufbau des Eisgitters. Es muss stärker abgekühlt werden, bis das Gitter trotzdem entsteht — der Gefrierpunkt sinkt.",
                tags=["mehrwertig", "bbr"], spiral=["W-LOES"]),
        aufgabe("AL04-B2-007", "B", 2, "choice",
                "Warum ist Glycol trotz seiner Ähnlichkeit zu Glycerin giftig?",
                options=["Im Körper entsteht daraus Oxalsäure, die in den Nieren Kristalle bildet.",
                         "Es ist ätzend.",
                         "Es ist brennbar."],
                answer=0,
                hints=["Beide werden im Körper abgebaut.",
                       "Verschieden ist das Abbauprodukt.",
                       "Aus Glycol entsteht Oxalsäure."],
                solution="Der Körper baut Glycol zu Oxalsäure ab. Diese bildet mit Calcium schwerlösliche Kristalle, die die Nieren schädigen. Glycerin wird dagegen unbedenklich abgebaut.",
                tags=["mehrwertig", "sicherheit", "bbr"]),
        aufgabe("AL04-B3-008", "B", 3, "choice",
                "Warum wird Frostschutzmittel bitter vergällt und eingefärbt?",
                options=["Glycol schmeckt süßlich; Bitterstoff und Farbe verhindern versehentliches Trinken.",
                         "Damit man es besser sieht.",
                         "Damit es länger haltbar ist."],
                answer=0,
                hints=["Wie schmeckt Glycol?",
                       "Süßlich.",
                       "Das ist gefährlich, besonders für Kinder und Tiere."],
                solution="Der süßliche Geschmack macht Glycol besonders gefährlich für Kinder und Haustiere. Bitterstoff und Farbe sind eine Sicherheitsmaßnahme, keine Kosmetik.",
                tags=["mehrwertig", "sicherheit", "bbr"]),
        aufgabe("AL04-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Glycerin C₃H₈O₃? (C = 12, H = 1, O = 16 g/mol)",
                answer=92, unit_label="g/mol", tolerance=1,
                hints=["3 C, 8 H, 3 O.",
                       "36 + 8 + 48.",
                       "92 g/mol."],
                solution="M = 3 · 12 + 8 · 1 + 3 · 16 = 36 + 8 + 48 = 92 g/mol",
                tags=["mehrwertig", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("AL04-B4-010", "B", 4, "choice",
                "Warum ist Glycerin gut wasserlöslich, obwohl es drei C-Atome hat?",
                options=["Drei OH-Gruppen überwiegen die kurze Kohlenstoffkette deutlich.",
                         "Weil es dickflüssig ist.",
                         "Weil es süß schmeckt."],
                answer=0,
                hints=["Zähle die polaren Gruppen.",
                       "Drei OH auf drei C-Atome.",
                       "Der polare Anteil überwiegt."],
                solution="Bei Propanol steht eine OH-Gruppe drei C-Atomen gegenüber. Bei Glycerin sind es drei OH-Gruppen auf drei C-Atome — der polare Anteil überwiegt klar, die Löslichkeit ist entsprechend gut.",
                tags=["mehrwertig", "msa"], spiral=["W-LOES"]),
        aufgabe("AL04-C2-011", "C", 2, "choice",
                "Warum wird Glycerin auch Lebensmitteln zugesetzt?",
                options=["Es hält sie feucht und ist gesundheitlich unbedenklich.",
                         "Es tötet Keime ab.",
                         "Es färbt sie."],
                answer=0,
                hints=["Was bewirkt Glycerin mit Wasser?",
                       "Es bindet es.",
                       "Und es ist unbedenklich."],
                solution="Glycerin ist hygroskopisch und hält Backwaren und Süßwaren länger feucht. Anders als Glycol ist es gesundheitlich unbedenklich und als Zusatzstoff zugelassen.",
                tags=["mehrwertig", "bewerten", "msa"]),
        aufgabe("AL04-C3-012", "C", 3, "choice",
                "Welche Lehre lässt sich aus dem Vergleich Glycol/Glycerin und Methanol/Ethanol ziehen?",
                options=["Ähnlicher Bau erlaubt keine Rückschlüsse auf die Wirkung im Körper.",
                         "Alle Alkohole sind giftig.",
                         "Alle Alkohole sind unbedenklich."],
                answer=0,
                hints=["Beide Paare sind chemisch eng verwandt.",
                       "Trotzdem wirken sie völlig verschieden.",
                       "Der Abbauweg entscheidet."],
                solution="Beide Paare unterscheiden sich nur geringfügig im Bau und völlig in der Wirkung — weil die Abbauprodukte verschieden sind. Von der Struktur auf die physiologische Wirkung zu schließen, ist unzulässig.",
                tags=["mehrwertig", "bewerten", "msa"]),
        aufgabe("AL04-C3-013", "C", 3, "multi",
                "Ein Kühlsystem fasst 6 L und wird mit 40 % Glycol befüllt. (Dichte Glycol 1,11 g/mL)",
                fields=[
                    {"label": "Volumen des Glycols", "answer": 2.4, "unit_label": "L", "tolerance": 0.1},
                    {"label": "Masse des Glycols", "answer": 2664, "unit_label": "g", "tolerance": 30}
                ],
                hints=["40 % von 6 L.",
                       "2,4 L = 2400 mL.",
                       "m = 2400 · 1,11."],
                solution="V = 6 L · 0,40 = 2,4 L = 2400 mL\nm = 2400 mL · 1,11 g/mL = 2664 g",
                tags=["mehrwertig", "rechnen", "msa"], spiral=["W-LOES", "W-STOF"]),
        aufgabe("AL04-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Glycerin steht in der Zutatenliste, also ist es ein künstlicher Zusatzstoff und bedenklich.“ Wie bewertest du das?",
                options=["Der Schluss ist unzulässig — Glycerin kommt auch natürlich in Fetten vor und ist unbedenklich.",
                         "Richtig, Zusatzstoffe sind bedenklich.",
                         "Falsch, Glycerin ist giftig."],
                answer=0,
                hints=["Wo kommt Glycerin natürlich vor?",
                       "In jedem Fett.",
                       "Und natürlich heißt nicht automatisch unbedenklich, künstlich nicht automatisch bedenklich."],
                solution="Glycerin ist Bestandteil aller natürlichen Fette. Ob ein Stoff bedenklich ist, entscheidet seine Wirkung und die Menge — nicht, ob er auf einer Zutatenliste steht oder synthetisch hergestellt wurde.",
                tags=["mehrwertig", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("al", E, "Bereich AL · Einheiten 3 und 4")
