# -*- coding: utf-8 -*-
"""Bereich QB · Quantitative Betrachtungen — QB-04 und QB-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "QB-04",
    "title": "Molares Volumen und Gasvolumina",
    "leitidee": "B1",
    "standards": ["K1", "K2.4", "K3.3"],
    "klasse": 9,
    "wortspeicher": ["das molare Volumen", "die Normbedingungen", "das Gasvolumen",
                     "der Satz von Avogadro", "die Gasdichte"],
    "worterklaerungen": {
        "molares Volumen": "Das Volumen von einem Mol Gas. Bei Normbedingungen 22,4 L/mol.",
        "Normbedingungen": "0 °C und 1013 hPa.",
        "Satz von Avogadro": "Gleiche Gasvolumina enthalten bei gleichen Bedingungen gleich viele Teilchen."
    },
    "can_do": {
        "A": "Ich berechne das Volumen einer Gasportion aus der Stoffmenge.",
        "B": "Ich rechne zwischen Masse, Stoffmenge und Gasvolumen um.",
        "C": "Ich begründe, warum das molare Volumen für alle Gase gleich ist."
    },
    "lernkarten": {
        "A": karte("Ein Mol Gas ist immer gleich groß",
                   "Jedes Gas nimmt bei einem Mol dasselbe Volumen ein.",
                   ["Es sind 22,4 Liter.", "Das gilt bei 0 °C und normalem Druck."],
                   "1 mol Gas = 22,4 L bei Normbedingungen.",
                   visual={"type": "apparatur", "aufbau": "pneumatisch",
                           "alt": "Über Wasser aufgefangenes Gasvolumen."},
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "Welches Volumen haben 2 mol Gas?",
                             "schritte": ["V = n · 22,4 L/mol", "V = 2 · 22,4", "V = 44,8 L"],
                             "ergebnis": "44,8 L",
                             "luecke": {"schritt": 2, "wert": 44.8, "einheit": "L"}}),
        "B": karte("Zwischen Masse, Stoffmenge und Volumen",
                   "Bei Gasen gibt es einen zusätzlichen Weg: Neben der Waage lässt sich auch das Volumen messen — oft einfacher.",
                   ["V = n · V_m mit V_m = 22,4 L/mol bei Normbedingungen.",
                    "Umgekehrt: n = V : V_m.",
                    "Damit ist der ganze Weg möglich: Masse → Stoffmenge → Volumen und zurück.",
                    "Die Dichte eines Gases folgt daraus unmittelbar: ρ = M : V_m. Kohlenstoffdioxid mit 44 g/mol hat 1,96 g/L, Luft rund 1,29 g/L — deshalb sammelt sich CO₂ am Boden."],
                   "V = n · 22,4 L/mol. Für Gase ist das Messen des Volumens oft praktischer als das Wiegen.",
                   visual=anim("mol", "B")),
        "C": karte("Warum 22,4 L für jedes Gas",
                   "Dass ein Mol Wasserstoff und ein Mol Kohlenstoffdioxid dasselbe Volumen einnehmen, obwohl die Moleküle so verschieden sind, hat einen klaren Grund.",
                   ["In einem Gas sind die Abstände zwischen den Teilchen viel größer als die Teilchen selbst. Das Eigenvolumen der Teilchen fällt kaum ins Gewicht.",
                    "Deshalb hängt das Volumen fast nur von der Teilchenzahl ab, nicht von der Teilchengröße — das ist der Satz von Avogadro.",
                    "Bei Feststoffen und Flüssigkeiten gilt das nicht: Dort liegen die Teilchen dicht beieinander, und ihre Größe bestimmt das Volumen mit.",
                    "Das molare Volumen gilt nur bei den angegebenen Bedingungen. Bei 20 °C sind es rund 24 L/mol — die Temperatur muss immer mitgenannt werden."],
                   "Im Gas ist fast nur Zwischenraum. Deshalb zählt die Teilchenzahl, nicht die Teilchengröße.",
                   visual={"type": "teilchen", "zustand": "gas", "art": "element",
                           "alt": "Teilchenmodell eines Gases mit großen Abständen."})
    },
    "formelkarte": {"formeln": ["V = n · V_m", "n = V : V_m", "V_m = 22,4 L/mol (Normbedingungen)",
                               "ρ(Gas) = M : V_m"],
                    "saetze": ["Normbedingungen: 0 °C und 1013 hPa.",
                               "Gleiche Gasvolumina enthalten gleich viele Teilchen.",
                               "Das molare Volumen gilt nur für Gase.",
                               "Bei 20 °C sind es rund 24 L/mol."]},
    "tasks": [
        aufgabe("QB04-A1-001", "A", 1, "numeric",
                "Welches Volumen hat 1 mol eines Gases bei Normbedingungen?",
                answer=22.4, unit_label="L", tolerance=0.1,
                hints=["Der Wert gilt für jedes Gas.", "Er steht auf der Formelkarte.", "22,4 L."],
                solution="1 mol eines Gases nimmt bei Normbedingungen 22,4 L ein.",
                tags=["gasvolumen"], spiral=["K-QUANT"]),
        aufgabe("QB04-A2-002", "A", 2, "numeric",
                "Welches Volumen haben 2 mol Gas?",
                answer=44.8, unit_label="L", tolerance=0.2,
                hints=["V = n · 22,4.", "2 · 22,4.", "44,8 L."],
                solution="V = 2 mol · 22,4 L/mol = 44,8 L",
                tags=["gasvolumen"], spiral=["K-QUANT"]),
        aufgabe("QB04-A3-003", "A", 3, "numeric",
                "Welches Volumen hat 0,5 mol Sauerstoff?",
                answer=11.2, unit_label="L", tolerance=0.1,
                hints=["V = n · 22,4.", "0,5 · 22,4.", "11,2 L."],
                solution="V = 0,5 mol · 22,4 L/mol = 11,2 L",
                misconceptions=[fv("mol_geteilt_statt_mal", 44.8,
                                   "V = n · V_m — hier wird multipliziert.")],
                tags=["gasvolumen"], spiral=["K-QUANT"]),
        aufgabe("QB04-A4-004", "A", 4, "choice",
                "1 mol Wasserstoff und 1 mol Kohlenstoffdioxid — welches Gas nimmt mehr Volumen ein?",
                options=["beide gleich viel", "Wasserstoff", "Kohlenstoffdioxid"], answer=0,
                hints=["Wie groß ist das molare Volumen bei Gasen?",
                       "Für jedes Gas gleich.",
                       "22,4 L."],
                solution="Beide nehmen 22,4 L ein. Das molare Volumen ist für alle Gase gleich — verschieden ist nur die Masse.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 2,
                                   "Die Teilchengröße spielt im Gas fast keine Rolle. Beide nehmen 22,4 L ein.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["gasvolumen"], spiral=["K-QUANT"]),
        aufgabe("QB04-B1-005", "B", 1, "numeric",
                "Wie viel mol sind 44,8 L eines Gases bei Normbedingungen?",
                answer=2, unit_label="mol", tolerance=0.05,
                hints=["n = V : V_m.", "44,8 : 22,4.", "2 mol."],
                solution="n = 44,8 L : 22,4 L/mol = 2 mol",
                tags=["gasvolumen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("QB04-B2-006", "B", 2, "numeric",
                "Welche Masse hat 11,2 L Kohlenstoffdioxid bei Normbedingungen? (M = 44 g/mol)",
                answer=22, unit_label="g", tolerance=0.3,
                hints=["Erst n = 11,2 : 22,4 = 0,5 mol.",
                       "Dann m = n · M.",
                       "0,5 · 44."],
                solution="n = 11,2 L : 22,4 L/mol = 0,5 mol\nm = 0,5 mol · 44 g/mol = 22 g",
                tags=["gasvolumen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("QB04-B2-007", "B", 2, "numeric",
                "Welches Volumen nehmen 8 g Sauerstoff O₂ ein? (M = 32 g/mol)",
                answer=5.6, unit_label="L", tolerance=0.2,
                hints=["n = 8 : 32 = 0,25 mol.",
                       "V = n · 22,4.",
                       "0,25 · 22,4."],
                solution="n = 8 g : 32 g/mol = 0,25 mol\nV = 0,25 · 22,4 L/mol = 5,6 L",
                tags=["gasvolumen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("QB04-B3-008", "B", 3, "numeric",
                "Wie groß ist die Dichte von Kohlenstoffdioxid bei Normbedingungen? (M = 44 g/mol)",
                answer=1.96, unit_label="g/L", tolerance=0.05,
                hints=["ρ = M : V_m.", "44 : 22,4.", "1,96 g/L."],
                solution="ρ = 44 g/mol : 22,4 L/mol = 1,96 g/L. Luft hat rund 1,29 g/L — deshalb sammelt sich CO₂ am Boden.",
                misconceptions=[fv("dichte_umgedreht", 0.51,
                                   "ρ = M : V_m — molare Masse durch molares Volumen.")],
                tags=["gasvolumen", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("QB04-B3-009", "B", 3, "choice",
                "Warum sammelt sich Kohlenstoffdioxid in Kellern und Gärkellern am Boden?",
                options=["Seine Dichte ist größer als die der Luft.",
                         "Es ist kälter als Luft.",
                         "Es löst sich im Boden."],
                answer=0,
                hints=["Vergleiche die Dichten.",
                       "1,96 g/L gegen 1,29 g/L.",
                       "Das schwerere Gas sinkt."],
                solution="Mit 1,96 g/L ist Kohlenstoffdioxid deutlich dichter als Luft (1,29 g/L) und sammelt sich am Boden. In Gärkellern kann das lebensgefährlich werden.",
                tags=["gasvolumen", "sicherheit", "bbr"], spiral=["K-STOF"]),
        aufgabe("QB04-B4-010", "B", 4, "multi",
                "Bei einer Reaktion entstehen 3,36 L Wasserstoff bei Normbedingungen. (M = 2 g/mol)",
                fields=[
                    {"label": "Stoffmenge", "answer": 0.15, "unit_label": "mol", "tolerance": 0.01},
                    {"label": "Masse", "answer": 0.3, "unit_label": "g", "tolerance": 0.02}
                ],
                hints=["n = 3,36 : 22,4.",
                       "0,15 mol.",
                       "m = 0,15 · 2."],
                solution="n = 3,36 L : 22,4 L/mol = 0,15 mol\nm = 0,15 mol · 2 g/mol = 0,3 g",
                tags=["gasvolumen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("QB04-C2-011", "C", 2, "choice",
                "Warum ist das molare Volumen für alle Gase gleich, für Feststoffe aber nicht?",
                options=["Im Gas ist der Zwischenraum viel größer als die Teilchen; bei Feststoffen bestimmt die Teilchengröße das Volumen mit.",
                         "Feststoffe haben kein molares Volumen.",
                         "Gase sind alle gleich schwer."],
                answer=0,
                visual={"type": "teilchen", "zustand": "gas", "art": "gemisch",
                        "alt": "Teilchenmodell eines Gases mit großen Abständen."},
                hints=["Wie groß sind die Abstände im Gas?",
                       "Viel größer als die Teilchen selbst.",
                       "Im Feststoff berühren sie sich."],
                solution="Im Gas fällt das Eigenvolumen der Teilchen kaum ins Gewicht — das Volumen hängt fast nur von der Teilchenzahl ab. Im Feststoff liegen die Teilchen dicht beieinander, dort bestimmt ihre Größe das Volumen mit.",
                tags=["gasvolumen", "msa"], spiral=["K-STOF"]),
        aufgabe("QB04-C3-012", "C", 3, "multi",
                "Bei der Elektrolyse von Wasser entstehen 2 H₂ und 1 O₂. Es werden 6,72 L Wasserstoff aufgefangen.",
                fields=[
                    {"label": "Stoffmenge des Wasserstoffs", "answer": 0.3, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "Stoffmenge des Sauerstoffs", "answer": 0.15, "unit_label": "mol", "tolerance": 0.01},
                    {"label": "Volumen des Sauerstoffs", "answer": 3.36, "unit_label": "L", "tolerance": 0.1}
                ],
                hints=["n(H₂) = 6,72 : 22,4.",
                       "Sauerstoff: die halbe Stoffmenge.",
                       "V = 0,15 · 22,4."],
                solution="n(H₂) = 0,3 mol\nn(O₂) = 0,15 mol\nV(O₂) = 0,15 · 22,4 = 3,36 L — genau die Hälfte, wie das Verhältnis 2 : 1 erwarten lässt.",
                tags=["gasvolumen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB04-C3-013", "C", 3, "choice",
                "Warum muss bei Volumenangaben von Gasen immer die Temperatur mitgenannt werden?",
                options=["Das molare Volumen hängt von Temperatur und Druck ab — bei 20 °C sind es rund 24 L/mol.",
                         "Die Teilchenzahl ändert sich mit der Temperatur.",
                         "Das ist nur eine Formalität."],
                answer=0,
                hints=["Was passiert mit einem Gas beim Erwärmen?",
                       "Es dehnt sich aus.",
                       "Also ändert sich das Volumen je Mol."],
                solution="Beim Erwärmen dehnt sich ein Gas aus — dieselbe Stoffmenge nimmt mehr Raum ein. Die Teilchenzahl bleibt gleich. Ohne Angabe der Bedingungen ist ein Gasvolumen deshalb nicht auswertbar.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Die Teilchenzahl ändert sich nicht. Nur der Raum je Teilchen wird größer.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["gasvolumen", "msa"], spiral=["K-QUANT"]),
        aufgabe("QB04-C4-014", "C", 4, "numeric",
                "2,4 g Magnesium (M = 24 g/mol) reagieren mit Säure: Mg + 2 HCl → MgCl₂ + H₂. Welches Wasserstoffvolumen entsteht bei Normbedingungen?",
                answer=2.24, unit_label="L", tolerance=0.1,
                hints=["n(Mg) = 2,4 : 24 = 0,1 mol.",
                       "Auf 1 Mg kommt 1 H₂, also 0,1 mol.",
                       "V = 0,1 · 22,4."],
                solution="n(Mg) = 2,4 g : 24 g/mol = 0,1 mol\nn(H₂) = 0,1 mol\nV = 0,1 · 22,4 L/mol = 2,24 L",
                misconceptions=[fv("masse_direkt_uebertragen", 2.4,
                                   "2,4 ist die Masse des Magnesiums. Rechne über die Stoffmenge zum Gasvolumen.")],
                tags=["gasvolumen", "msa"], spiral=["K-QUANT", "K-REAK"])
    ]
})

E.append({
    "unit": "QB-05",
    "title": "Anwenden & Prüfungstraining Stöchiometrie",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3"],
    "klasse": 9,
    "wortspeicher": ["die Stöchiometrie", "das Stoffmengenverhältnis", "die Ausbeute",
                     "der Überschuss", "die Bilanz"],
    "worterklaerungen": {
        "Stöchiometrie": "Das Rechnen mit Mengen in chemischen Reaktionen.",
        "Ausbeute": "Wie viel Produkt tatsächlich gewonnen wurde, verglichen mit der Rechnung.",
        "Überschuss": "Der Teil eines Edukts, der nicht reagieren kann, weil der Partner ausgeht."
    },
    "can_do": {
        "A": "Ich rechne einfache Aufgaben mit n = m : M.",
        "B": "Ich berechne Produktmassen über das Stoffmengenverhältnis der Gleichung.",
        "C": "Ich berücksichtige Überschuss und Ausbeute und beurteile Ergebnisse auf Plausibilität."
    },
    "lernkarten": {
        "A": karte("Der Rechenweg",
                   "Bei jeder Aufgabe geht es über die Stoffmenge.",
                   ["Erst die Masse in mol umrechnen.", "Dann mit der Gleichung weiterrechnen."],
                   "Masse → Stoffmenge → Gleichung → Stoffmenge → Masse.",
                   visual=anim("mol", "A")),
        "B": karte("Die vier Schritte",
                   "Jede stöchiometrische Aufgabe folgt demselben Ablauf. Wer ihn einhält, verrechnet sich selten.",
                   ["1. Reaktionsgleichung aufstellen und ausgleichen. Ohne sie fehlt das Stoffmengenverhältnis.",
                    "2. Gegebene Masse in Stoffmenge umrechnen: n = m : M.",
                    "3. Über die Koeffizienten zur Stoffmenge des gesuchten Stoffes.",
                    "4. Zurück zur Masse oder zum Volumen: m = n · M bzw. V = n · 22,4 L/mol.",
                    "Am Ende Einheit und Größenordnung prüfen."],
                   "Ohne ausgeglichene Gleichung fehlt das Verhältnis — Schritt 1 ist nicht optional.",
                   visual=anim("ausgleichen", "B")),
        "C": karte("Überschuss und Ausbeute",
                   "In der Praxis reagiert selten alles vollständig. Zwei Begriffe erfassen das.",
                   ["Überschuss: Ist ein Edukt im Überschuss, bestimmt der andere Stoff, wie viel Produkt entstehen kann. Erst prüfen, welcher Stoff zuerst ausgeht.",
                    "Ausbeute: tatsächliche Produktmasse geteilt durch die berechnete, in Prozent. Sie liegt praktisch immer unter 100 %.",
                    "Ursachen für Verluste: unvollständige Reaktion, Rückstände im Gefäß, Nebenreaktionen.",
                    "Eine Ausbeute über 100 % ist ein Hinweis auf einen Fehler — meist auf Feuchtigkeit im Produkt."],
                   "Der Stoff, der zuerst ausgeht, begrenzt die Produktmenge.",
                   visual=anim("mol", "C"))
    },
    "formelkarte": {"formeln": ["n = m : M", "m = n · M", "V = n · 22,4 L/mol",
                               "Ausbeute = m(tatsächlich) : m(berechnet) · 100 %"],
                    "saetze": ["Immer über die Stoffmenge rechnen, nie Massen direkt übertragen.",
                               "Ohne ausgeglichene Gleichung kein Stoffmengenverhältnis.",
                               "Der Stoff, der zuerst ausgeht, begrenzt die Ausbeute.",
                               "Am Ende Einheit und Größenordnung prüfen."]},
    "tasks": [
        aufgabe("QB05-A1-001", "A", 1, "numeric",
                "Wie viel mol sind 90 g Wasser? (M = 18 g/mol)",
                answer=5, unit_label="mol", tolerance=0.05,
                hints=["n = m : M.", "90 : 18.", "5 mol."],
                solution="n = 90 g : 18 g/mol = 5 mol",
                tags=["pruefung"], spiral=["K-QUANT"]),
        aufgabe("QB05-A2-002", "A", 2, "numeric",
                "Welche Masse haben 3 mol Kohlenstoffdioxid? (M = 44 g/mol)",
                answer=132, unit_label="g", tolerance=1,
                hints=["m = n · M.", "3 · 44.", "132 g."],
                solution="m = 3 mol · 44 g/mol = 132 g",
                tags=["pruefung"], spiral=["K-QUANT"]),
        aufgabe("QB05-A3-003", "A", 3, "numeric",
                "Welches Volumen haben 1,5 mol Gas bei Normbedingungen?",
                answer=33.6, unit_label="L", tolerance=0.3,
                hints=["V = n · 22,4.", "1,5 · 22,4.", "33,6 L."],
                solution="V = 1,5 mol · 22,4 L/mol = 33,6 L",
                tags=["pruefung"], spiral=["K-QUANT"]),
        aufgabe("QB05-A4-004", "A", 4, "numeric",
                "Berechnet wurden 40 g Produkt, gewonnen wurden 34 g. Wie hoch ist die Ausbeute?",
                answer=85, unit_label="%", tolerance=0.5,
                hints=["Ausbeute = tatsächlich : berechnet.", "34 : 40.", "Mal 100."],
                solution="34 g : 40 g = 0,85 → 85 %",
                misconceptions=[fv("anteil_umgedreht", 117.6,
                                   "Ausbeute = tatsächlich geteilt durch berechnet. Sie kann nicht über 100 % liegen.")],
                tags=["pruefung", "rechnen"], spiral=["K-QUANT"]),
        aufgabe("QB05-B1-005", "B", 1, "multi",
                "24 g Kohlenstoff (M = 12 g/mol) verbrennen vollständig zu CO₂ (M = 44 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Kohlenstoffs", "answer": 2, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse des entstehenden CO₂", "answer": 88, "unit_label": "g", "tolerance": 1}
                ],
                hints=["n = 24 : 12 = 2 mol.",
                       "C + O₂ → CO₂ läuft 1 : 1.",
                       "m = 2 · 44."],
                solution="n(C) = 2 mol → n(CO₂) = 2 mol → m = 88 g",
                tags=["pruefung", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-B2-006", "B", 2, "numeric",
                "Wie viel Gramm Sauerstoff werden gebraucht, um 4,8 g Magnesium (M = 24 g/mol) vollständig zu MgO zu verbrennen? (2 Mg + O₂ → 2 MgO, M(O₂) = 32 g/mol)",
                answer=3.2, unit_label="g", tolerance=0.1,
                hints=["n(Mg) = 4,8 : 24 = 0,2 mol.",
                       "Auf 2 Mg kommt 1 O₂, also 0,1 mol.",
                       "m = 0,1 · 32."],
                solution="n(Mg) = 0,2 mol\nn(O₂) = 0,1 mol\nm(O₂) = 0,1 · 32 = 3,2 g",
                misconceptions=[fv("masse_direkt_uebertragen", 6.4,
                                   "Das Verhältnis 2 : 1 gilt für Stoffmengen, nicht für Massen.")],
                tags=["pruefung", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-B2-007", "B", 2, "numeric",
                "Welches Volumen Wasserstoff entsteht aus 6,5 g Zink (M = 65 g/mol)? (Zn + 2 HCl → ZnCl₂ + H₂)",
                answer=2.24, unit_label="L", tolerance=0.1,
                hints=["n(Zn) = 6,5 : 65 = 0,1 mol.",
                       "1 : 1 zu H₂.",
                       "V = 0,1 · 22,4."],
                solution="n(Zn) = 0,1 mol → n(H₂) = 0,1 mol → V = 2,24 L",
                tags=["pruefung", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-B3-008", "B", 3, "multi",
                "50 g Calciumcarbonat CaCO₃ (M = 100 g/mol) werden erhitzt: CaCO₃ → CaO + CO₂.",
                fields=[
                    {"label": "Stoffmenge des Carbonats", "answer": 0.5, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "Masse des entstehenden CaO (M = 56 g/mol)", "answer": 28, "unit_label": "g", "tolerance": 0.5},
                    {"label": "Volumen des entstehenden CO₂", "answer": 11.2, "unit_label": "L", "tolerance": 0.3}
                ],
                hints=["n = 50 : 100 = 0,5 mol.",
                       "Alle Verhältnisse sind 1 : 1.",
                       "V = 0,5 · 22,4."],
                solution="n = 0,5 mol\nm(CaO) = 0,5 · 56 = 28 g\nV(CO₂) = 0,5 · 22,4 = 11,2 L\nProbe: 28 g + 22 g CO₂ = 50 g — die Masse bleibt erhalten.",
                tags=["pruefung", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-B3-009", "B", 3, "choice",
                "Warum liegt die Ausbeute in der Praxis fast immer unter 100 %?",
                options=["Reaktionen laufen unvollständig ab, Reste bleiben im Gefäß, Nebenreaktionen treten auf.",
                         "Weil Masse verloren geht.",
                         "Weil die Formel falsch ist."],
                answer=0,
                hints=["Bleibt beim Umfüllen wirklich nichts zurück?",
                       "Nein.",
                       "Und nicht jede Reaktion läuft vollständig."],
                solution="Die berechnete Masse ist ein Höchstwert. In der Praxis reagiert nicht alles, Reste haften am Gefäß und Nebenreaktionen verbrauchen Edukte. Masse geht dabei nicht verloren — sie landet nur nicht im Produkt.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Masse geht nie verloren. Sie steckt in Resten und Nebenprodukten.",
                                   "masse_verschwindet")],
                tags=["pruefung", "bbr"], spiral=["K-REAK"]),
        aufgabe("QB05-B4-010", "B", 4, "numeric",
                "Berechnet wurden 12,5 g Produkt. Die Ausbeute beträgt 80 %. Wie viel wurde tatsächlich gewonnen?",
                answer=10, unit_label="g", tolerance=0.2,
                hints=["80 % von 12,5 g.", "12,5 · 0,8.", "10 g."],
                solution="12,5 g · 0,80 = 10 g",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-SL"]),
        aufgabe("QB05-C2-011", "C", 2, "choice",
                "4 g Wasserstoff und 4 g Sauerstoff werden gezündet. Welcher Stoff begrenzt die Wassermenge?",
                options=["Der Sauerstoff — von ihm ist zu wenig da.",
                         "Der Wasserstoff.", "Beide reagieren vollständig."],
                answer=0,
                hints=["Rechne beide Stoffmengen aus: n(H₂) = 4 : 2 = 2 mol, n(O₂) = 4 : 32 = 0,125 mol.",
                       "Gebraucht wird 1 O₂ auf 2 H₂.",
                       "Für 2 mol H₂ bräuchte es 1 mol O₂."],
                solution="n(H₂) = 2 mol, n(O₂) = 0,125 mol. Für 2 mol Wasserstoff wäre 1 mol Sauerstoff nötig — vorhanden sind nur 0,125 mol. Der Sauerstoff geht zuerst aus und begrenzt die Ausbeute.",
                misconceptions=[fv("masse_direkt_uebertragen", 1,
                                   "Gleiche Massen bedeuten nicht gleiche Stoffmengen. Rechne beide in mol um.")],
                tags=["pruefung", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-C3-012", "C", 3, "multi",
                "Aus 32 g Kupfer (M = 64 g/mol) soll Kupferoxid CuO (M = 80 g/mol) hergestellt werden. Gewonnen werden 36 g.",
                fields=[
                    {"label": "Stoffmenge des Kupfers", "answer": 0.5, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "berechnete Masse des Kupferoxids", "answer": 40, "unit_label": "g", "tolerance": 0.5},
                    {"label": "Ausbeute in Prozent", "answer": 90, "unit_label": "%", "tolerance": 1}
                ],
                hints=["n(Cu) = 32 : 64 = 0,5 mol.",
                       "2 Cu + O₂ → 2 CuO läuft 1 : 1.",
                       "36 : 40 · 100 %."],
                solution="n(Cu) = 0,5 mol → n(CuO) = 0,5 mol → m = 40 g\nAusbeute: 36 : 40 = 0,90 → 90 %",
                tags=["pruefung", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("QB05-C3-013", "C", 3, "choice",
                "Eine Rechnung ergibt eine Ausbeute von 112 %. Was folgt daraus?",
                options=["Es liegt ein Fehler vor — meist ist das Produkt noch feucht oder verunreinigt.",
                         "Die Reaktion lief besonders gut.",
                         "Es ist Masse entstanden."],
                answer=0,
                hints=["Kann mehr Produkt entstehen, als die Bilanz zulässt?",
                       "Nein.",
                       "Also stimmt etwas mit der Messung nicht."],
                solution="Mehr Produkt als berechnet kann nicht entstehen — sonst wäre Masse aus dem Nichts gekommen. In der Praxis ist das Produkt meist noch feucht oder enthält Verunreinigungen.",
                misconceptions=[fv("masse_verschwindet", 2,
                                   "Masse entsteht nicht. Über 100 % ist immer ein Messfehler.",
                                   "masse_verschwindet")],
                tags=["pruefung", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("QB05-C4-014", "C", 4, "choice",
                "Welcher erste Schritt gehört an den Anfang jeder stöchiometrischen Aufgabe?",
                options=["Die Reaktionsgleichung aufstellen und ausgleichen.",
                         "Die Massen addieren.",
                         "Das Ergebnis schätzen."],
                answer=0,
                hints=["Woher kommt das Stoffmengenverhältnis?",
                       "Aus den Koeffizienten.",
                       "Die gibt es erst nach dem Ausgleichen."],
                solution="Ohne ausgeglichene Gleichung fehlt das Stoffmengenverhältnis — und damit die Verbindung zwischen den beteiligten Stoffen. Alle weiteren Schritte bauen darauf auf.",
                tags=["pruefung", "operatoren", "msa"], spiral=["K-REAK"])
    ]
})

if __name__ == "__main__":
    schreiben("qb", E, "Bereich QB · Einheiten 4 und 5")
