# -*- coding: utf-8 -*-
"""Bereich GA · Gase (Klasse 7, Themenfeld 3.3) — GA-01 bis GA-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "GA-01",
    "title": "Luft ist ein Gasgemisch",
    "leitidee": "B1",
    "standards": ["K1", "K2.2", "K2.4"],
    "klasse": 7,
    "wortspeicher": ["das Gasgemisch", "der Stickstoff", "der Sauerstoff", "das Edelgas",
                     "das Kohlenstoffdioxid", "der Volumenanteil"],
    "worterklaerungen": {
        "Gasgemisch": "Mehrere Gase liegen nebeneinander vor. Sie sind nicht miteinander verbunden.",
        "Volumenanteil": "Wie viel Prozent des Volumens auf ein Gas entfallen."
    },
    "can_do": {
        "A": "Ich nenne die Hauptbestandteile der Luft und ihre ungefähren Anteile.",
        "B": "Ich rechne mit Volumenanteilen und beschreibe den Versuch zur Sauerstoffbestimmung.",
        "C": "Ich begründe, warum Luft ein Gemisch und keine Verbindung ist."
    },
    "lernkarten": {
        "A": karte("Woraus Luft besteht",
                   "Luft ist kein einzelner Stoff.",
                   ["Etwa 78 % sind Stickstoff.", "Etwa 21 % sind Sauerstoff.", "Der Rest ist sehr wenig."],
                   "Luft ist ein Gemisch aus mehreren Gasen.",
                   visual={"type": "anteil", "titel": "Zusammensetzung der Luft",
                           "segmente": [{"anteil": 78, "label": "N₂"}, {"anteil": 21, "label": "O₂"},
                                        {"anteil": 1, "label": "Ar u. a."}],
                           "alt": "Balken mit den Volumenanteilen der Luft: 78 % Stickstoff, 21 % Sauerstoff, 1 % Rest."},
                   beispiel={"titel": "Wie viel Sauerstoff?", "aufgabe": "In 100 L Luft — wie viel Liter Sauerstoff?",
                             "schritte": ["21 % von 100 L", "= 21 L"],
                             "ergebnis": "21 L Sauerstoff.",
                             "luecke": {"schritt": 1, "wert": 21, "einheit": "L"}}),
        "B": karte("Anteile und ihre Messung",
                   "Die Zusammensetzung der Luft ist keine Schätzung, sondern messbar — und der Versuch dazu ist einfach.",
                   ["Stickstoff 78 %, Sauerstoff 21 %, Edelgase rund 0,9 %, Kohlenstoffdioxid rund 0,04 %.",
                    "Zur Messung lässt man in einem abgeschlossenen Luftvolumen etwas verbrennen, das nur mit Sauerstoff reagiert — etwa Eisenwolle oder eine Kerze.",
                    "Der verbrauchte Sauerstoff wird gebunden, Wasser steigt nach: rund ein Fünftel des Volumens.",
                    "Das übrige Gas lässt einen Glimmspan erlöschen — es ist überwiegend Stickstoff."],
                   "Rund ein Fünftel der Luft ist Sauerstoff. Das ist messbar, nicht geraten.",
                   visual={"type": "apparatur", "aufbau": "pneumatisch",
                           "alt": "Pneumatische Wanne mit einem über Wasser aufgefangenen Gas."}),
        "C": karte("Gemisch, nicht Verbindung",
                   "Dass Luft ein Gemisch ist und keine Verbindung, folgt aus mehreren voneinander unabhängigen Befunden. Ein einzelner davon würde nicht genügen.",
                   ["Die Anteile sind nicht konstant: In großer Höhe, in einem geschlossenen Raum oder über einem Wald sind sie messbar verschieden. Eine Verbindung hätte feste Zahlenverhältnisse.",
                    "Die Bestandteile behalten ihre Eigenschaften: Sauerstoff unterhält die Verbrennung, ob rein oder in Luft.",
                    "Die Trennung gelingt physikalisch — durch Verflüssigen und fraktionierte Destillation, ohne chemische Reaktion.",
                    "Luft hat deshalb auch keinen festen Siedepunkt, sondern einen Siedebereich."],
                   "Feste Verhältnisse, erhaltene Eigenschaften, physikalische Trennbarkeit — daran erkennt man ein Gemisch.",
                   visual={"type": "anteil", "titel": "Volumenanteile der trockenen Luft",
                           "segmente": [{"anteil": 78.08, "label": "N₂"}, {"anteil": 20.95, "label": "O₂"},
                                        {"anteil": 0.93, "label": "Ar"}, {"anteil": 0.04, "label": "CO₂"}],
                           "alt": "Genaue Volumenanteile der trockenen Luft."})
    },
    "formelkarte": {"formeln": ["Volumenanteil = V(Gas) : V(Luft) · 100 %"],
                    "saetze": ["Luft: 78 % Stickstoff, 21 % Sauerstoff, rund 1 % Edelgase, 0,04 % CO₂.",
                               "Ein Fünftel der Luft ist Sauerstoff.",
                               "Gemisch: Bestandteile behalten ihre Eigenschaften und sind physikalisch trennbar."]},
    "tasks": [
        aufgabe("GA01-A1-001", "A", 1, "choice",
                "Welches Gas ist in der Luft am häufigsten?",
                options=["Stickstoff", "Sauerstoff", "Kohlenstoffdioxid"], answer=0,
                visual={"type": "anteil", "segmente": [{"anteil": 78, "label": "N₂"}, {"anteil": 21, "label": "O₂"}, {"anteil": 1, "label": "Rest"}],
                        "alt": "Balken mit den Anteilen der Luft."},
                hints=["Sieh dir den Balken an.", "Der größte Teil ist blau.", "Das ist Stickstoff."],
                solution="Rund 78 % der Luft sind Stickstoff — deutlich mehr als Sauerstoff.",
                misconceptions=[fv("sauerstoff_als_hauptbestandteil", 1,
                                   "Sauerstoff macht nur etwa 21 % aus. Der Hauptbestandteil ist Stickstoff.")],
                tags=["luft"], spiral=["W-STOF"]),
        aufgabe("GA01-A2-002", "A", 2, "numeric",
                "Wie viel Prozent der Luft sind Sauerstoff?",
                answer=21, unit_label="%", tolerance=1,
                hints=["Etwa ein Fünftel.", "Ein Fünftel sind 20 %.", "Genauer: 21 %."],
                solution="Rund 21 % der Luft sind Sauerstoff — etwa ein Fünftel.",
                tags=["luft"], spiral=["W-LOES"]),
        aufgabe("GA01-A3-003", "A", 3, "numeric",
                "Wie viele Liter Sauerstoff stecken in 200 L Luft?",
                answer=42, unit_label="L", tolerance=1,
                hints=["21 % von 200 L.", "1 % sind 2 L.", "21 · 2 L."],
                solution="1 % von 200 L = 2 L → 21 % = 42 L",
                misconceptions=[fv("anteil_umgedreht", 9.52,
                                   "Du hast geteilt. 21 % von 200 L heißt 200 · 0,21.")],
                tags=["luft", "rechnen"], spiral=["W-LOES"]),
        aufgabe("GA01-A4-004", "A", 4, "choice",
                "Warum erlischt eine Kerze in einem geschlossenen Glas?",
                options=["Der Sauerstoff im Glas ist verbraucht.", "Der Stickstoff ist verbraucht.", "Es wird zu warm."],
                answer=0,
                hints=["Welches Gas braucht die Verbrennung?", "Sauerstoff.", "Und im Glas ist nur wenig davon."],
                solution="Nur der Sauerstoff wird bei der Verbrennung verbraucht. Ist er aufgebraucht, erlischt die Flamme — der Stickstoff bleibt übrig.",
                tags=["luft"], spiral=["W-GLEI"]),
        aufgabe("GA01-B1-005", "B", 1, "choice",
                "In einem abgeschlossenen Luftvolumen verbrennt Eisenwolle. Um welchen Anteil steigt das Wasser nach?",
                options=["um etwa ein Fünftel", "um etwa die Hälfte", "gar nicht"], answer=0,
                visual={"type": "apparatur", "aufbau": "pneumatisch",
                        "alt": "Über Wasser abgeschlossenes Luftvolumen."},
                hints=["Welcher Anteil der Luft wird gebunden?", "Der Sauerstoff.", "Das ist etwa ein Fünftel."],
                solution="Die Eisenwolle bindet den Sauerstoff — rund ein Fünftel des Volumens. Genau um diesen Anteil steigt das Wasser nach.",
                tags=["luft", "versuch", "bbr"], spiral=["W-GLEI"]),
        aufgabe("GA01-B2-006", "B", 2, "numeric",
                "Ein Zimmer hat 60 m³ Luft. Wie viele Kubikmeter Sauerstoff sind darin?",
                answer=12.6, unit_label="m³", tolerance=0.2,
                hints=["21 % von 60 m³.", "1 % sind 0,6 m³.", "21 · 0,6 m³."],
                solution="60 m³ · 0,21 = 12,6 m³ Sauerstoff",
                tags=["luft", "rechnen", "bbr"], spiral=["W-LOES", "W-EINH"]),
        aufgabe("GA01-B2-007", "B", 2, "choice",
                "Nach dem Versuch lässt das Restgas einen Glimmspan erlöschen. Was folgt daraus?",
                options=["Der Sauerstoff ist verbraucht; übrig ist überwiegend Stickstoff.",
                         "Das Restgas ist Kohlenstoffdioxid.",
                         "Der Versuch ist misslungen."],
                answer=0,
                hints=["Was zeigt der Glimmspan an?", "Sauerstoff — wenn er aufflammt.", "Er erlischt, also fehlt Sauerstoff."],
                solution="Ein erlöschender Glimmspan zeigt, dass kein Sauerstoff mehr da ist. Das Restgas ist überwiegend Stickstoff — er unterhält die Verbrennung nicht.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Kohlenstoffdioxid wiese man mit Kalkwasser nach. Der Glimmspan prüft auf Sauerstoff.",
                                   "nachweis_verwechselt")],
                tags=["luft", "versuch", "bbr"], spiral=["W-NACH"] if False else ["W-GLEI"]),
        aufgabe("GA01-B3-008", "B", 3, "multi",
                "Ein Kolben enthält 500 mL Luft.",
                fields=[
                    {"label": "Volumen des Stickstoffs", "answer": 390, "unit_label": "mL", "tolerance": 5},
                    {"label": "Volumen des Sauerstoffs", "answer": 105, "unit_label": "mL", "tolerance": 5},
                    {"label": "Volumen des Restes", "answer": 5, "unit_label": "mL", "tolerance": 2}
                ],
                hints=["78 %, 21 % und 1 % von 500 mL.",
                       "1 % sind 5 mL.",
                       "78 · 5 = 390 mL."],
                solution="N₂: 500 · 0,78 = 390 mL\nO₂: 500 · 0,21 = 105 mL\nRest: 500 · 0,01 = 5 mL",
                tags=["luft", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("GA01-B3-009", "B", 3, "choice",
                "Warum eignet sich eine Kerze schlechter als Eisenwolle für die Bestimmung des Sauerstoffanteils?",
                options=["Bei der Kerze entsteht Kohlenstoffdioxid als Gas, das den Volumenverlust teilweise ausgleicht.",
                         "Die Kerze brennt zu hell.", "Eisenwolle brennt länger."],
                answer=0,
                hints=["Was entsteht bei der Verbrennung von Wachs?",
                       "Kohlenstoffdioxid und Wasserdampf.",
                       "Ein Gas nimmt wieder Volumen ein."],
                solution="Eisenwolle bindet Sauerstoff zu festem Eisenoxid — das Volumen sinkt vollständig. Bei der Kerze entsteht gasförmiges Kohlenstoffdioxid, das einen Teil des Volumens wieder einnimmt. Deshalb misst man mit der Kerze zu wenig.",
                tags=["luft", "planen", "msa"], spiral=["W-GLEI"]),
        aufgabe("GA01-B4-010", "B", 4, "choice",
                "Warum ist Luft ein Gemisch und keine Verbindung?",
                options=["Die Anteile sind nicht überall gleich, und die Bestandteile behalten ihre Eigenschaften.",
                         "Weil Luft unsichtbar ist.", "Weil Luft ein Gas ist."],
                answer=0,
                hints=["Was gilt für eine Verbindung?",
                       "Feste Zahlenverhältnisse und neue Eigenschaften.",
                       "Beides trifft auf Luft nicht zu."],
                solution="Eine Verbindung hat feste Massenverhältnisse und neue Eigenschaften. Bei Luft schwanken die Anteile, und Sauerstoff unterhält die Verbrennung auch in der Luft — die Bestandteile behalten ihre Eigenschaften.",
                misconceptions=[fv("aggregatzustand_als_kriterium", 2,
                                   "Ob etwas Gas ist, sagt nichts über Gemisch oder Verbindung. Wasserdampf ist ein Gas und eine Verbindung.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["luft", "bbr"], spiral=["W-STOF"]),
        aufgabe("GA01-C2-011", "C", 2, "choice",
                "Wie wird Stickstoff technisch aus der Luft gewonnen?",
                options=["Durch Verflüssigen und fraktionierte Destillation — die Siedepunkte unterscheiden sich.",
                         "Durch Filtrieren der Luft.",
                         "Durch chemische Zerlegung der Luft."],
                answer=0,
                hints=["Luft ist ein Gemisch, also physikalisch trennbar.",
                       "Welches Verfahren trennt über Siedepunkte?",
                       "Die Destillation."],
                solution="Luft wird verflüssigt und dann destilliert. Stickstoff siedet bei −196 °C, Sauerstoff erst bei −183 °C. Weil es ein Gemisch ist, genügt ein physikalisches Verfahren.",
                misconceptions=[fv("geloestes_filtrierbar", 1,
                                   "Ein Filter trennt nach Größe. Gasteilchen sind viel kleiner als jede Pore.",
                                   "trennverfahren_verwechselt")],
                tags=["luft", "technik", "msa"], spiral=["W-STOF"]),
        aufgabe("GA01-C3-012", "C", 3, "multi",
                "In einem Versuch werden 250 mL Luft eingeschlossen. Nach dem Verbrennen von Eisenwolle bleiben 199 mL Gas übrig.",
                fields=[
                    {"label": "verbrauchtes Sauerstoffvolumen", "answer": 51, "unit_label": "mL", "tolerance": 1},
                    {"label": "gemessener Sauerstoffanteil in Prozent", "answer": 20.4, "unit_label": "%", "tolerance": 0.3}
                ],
                hints=["Verbraucht = vorher − nachher.",
                       "250 − 199 = 51 mL.",
                       "Anteil = 51 : 250 · 100 %."],
                solution="verbraucht: 250 mL − 199 mL = 51 mL\nAnteil: 51 : 250 = 0,204 → 20,4 %\nDas liegt sehr nahe am Literaturwert von 20,95 %.",
                tags=["luft", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("GA01-C3-013", "C", 3, "choice",
                "Ein Versuch ergibt einen Sauerstoffanteil von 17 % statt 21 %. Welche Erklärung ist am plausibelsten?",
                options=["Die Reaktion war unvollständig — nicht aller Sauerstoff wurde gebunden.",
                         "Die Luft im Raum enthielt tatsächlich weniger Sauerstoff.",
                         "Der Messzylinder war zu groß."],
                answer=0,
                hints=["Welche Fehlerquelle liegt im Versuch selbst?",
                       "Wird wirklich aller Sauerstoff verbraucht?",
                       "Meist bleibt ein Rest."],
                solution="Bleibt Sauerstoff ungebunden, sinkt das Volumen zu wenig und der gemessene Anteil fällt zu klein aus. Die Zusammensetzung der Raumluft schwankt dagegen nur um Bruchteile eines Prozents.",
                tags=["luft", "fehler", "msa"]),
        aufgabe("GA01-C4-014", "C", 4, "choice",
                "Kohlenstoffdioxid macht nur 0,04 % der Luft aus. Ein Schüler folgert: „So wenig kann keine Wirkung haben.“ Wie bewertest du das?",
                options=["Der Schluss ist unzulässig — die Wirkung eines Stoffes hängt nicht allein von seinem Anteil ab.",
                         "Richtig — 0,04 % sind vernachlässigbar.",
                         "Falsch — CO₂ macht in Wirklichkeit 4 % aus."],
                answer=0,
                hints=["Gibt es Stoffe, die in kleinsten Mengen stark wirken?",
                       "Ja, viele.",
                       "Der Anteil allein sagt nichts über die Wirkung."],
                solution="Ein kleiner Anteil bedeutet keine kleine Wirkung: Kohlenstoffdioxid absorbiert Wärmestrahlung sehr wirksam, Stickstoff und Sauerstoff dagegen kaum. Von der Menge auf die Wirkung zu schließen, ist ein häufiger Fehlschluss.",
                tags=["luft", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "GA-02",
    "title": "Nachweise: Sauerstoff, Wasserstoff, Kohlenstoffdioxid",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.2"],
    "klasse": 7,
    "sicherheit": [
        "Die Knallgasprobe wird nur mit kleinen Mengen und im Reagenzglas durchgeführt.",
        "Beim Arbeiten mit Gasen immer Schutzbrille tragen."
    ],
    "wortspeicher": ["der Nachweis", "die Glimmspanprobe", "die Knallgasprobe", "das Kalkwasser",
                     "der Nachweisreagenz", "eindeutig"],
    "worterklaerungen": {
        "Nachweis": "Ein Versuch, der zeigt, ob ein bestimmter Stoff da ist.",
        "Glimmspanprobe": "Ein glimmender Holzspan wird ins Gas gehalten. Bei Sauerstoff flammt er auf.",
        "Kalkwasser": "Eine klare Lösung. Mit Kohlenstoffdioxid wird sie milchig trüb."
    },
    "can_do": {
        "A": "Ich ordne jedem der drei Gase seinen Nachweis zu.",
        "B": "Ich beschreibe Durchführung und Beobachtung der drei Nachweise.",
        "C": "Ich erkläre die Nachweisreaktionen und beurteile, wann ein Nachweis eindeutig ist."
    },
    "lernkarten": {
        "A": karte("Drei Gase, drei Proben",
                   "Man kann Gase nicht sehen.",
                   ["Für jedes Gas gibt es einen eigenen Versuch.", "Der Versuch heißt Nachweis."],
                   "Glimmspan → Sauerstoff. Knall → Wasserstoff. Trübung → Kohlenstoffdioxid.",
                   visual=anim("nachweise", "A"),
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "Ein Span flammt im Gas hell auf.",
                             "schritte": ["Das ist die Glimmspanprobe.", "Sie zeigt Sauerstoff an."],
                             "ergebnis": "Das Gas ist Sauerstoff."}),
        "B": karte("Durchführung und Beobachtung",
                   "Ein Nachweis besteht immer aus drei Teilen: Was wird getan, was wird beobachtet, was folgt daraus. Ohne den dritten Teil ist es kein Nachweis, sondern nur ein Versuch.",
                   ["Glimmspanprobe: Ein glimmender Span wird in das Gas gehalten. Er flammt hell auf → Sauerstoff.",
                    "Knallgasprobe: Das Gas wird im Reagenzglas aufgefangen und an der Öffnung entzündet. Es knallt pfeifend → Wasserstoff.",
                    "Kalkwasserprobe: Das Gas wird in klares Kalkwasser geleitet. Es wird milchig trüb → Kohlenstoffdioxid."],
                   "Durchführung, Beobachtung, Schlussfolgerung — alle drei gehören zum Nachweis.",
                   visual=anim("nachweise", "B")),
        "C": karte("Warum die Nachweise funktionieren",
                   "Jeder Nachweis beruht auf einer chemischen Reaktion, die nur mit dem gesuchten Stoff abläuft. Genau das macht ihn eindeutig.",
                   ["Glimmspanprobe: Sauerstoff unterhält die Verbrennung. In reinem Sauerstoff verbrennt die Glut so schnell, dass der Span wieder mit Flamme brennt.",
                    "Knallgasprobe: 2 H₂ + O₂ → 2 H₂O läuft explosionsartig ab. Das pfeifende Geräusch zeigt an, dass das Gemisch nahezu rein war; ein dumpfer Knall zeigt Luftbeimischung.",
                    "Kalkwasserprobe: CO₂ + Ca(OH)₂ → CaCO₃ + H₂O. Calciumcarbonat ist schwerlöslich und fällt als feiner Feststoff aus — das ist die Trübung.",
                    "Ein Nachweis ist nur dann eindeutig, wenn kein anderer anwesender Stoff dieselbe Beobachtung erzeugt."],
                   "Ein Nachweis ist so viel wert wie seine Eindeutigkeit.",
                   visual=anim("nachweise", "C"))
    },
    "formelkarte": {"formeln": ["2 H₂ + O₂ → 2 H₂O", "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O"],
                    "saetze": ["Glimmspan flammt auf → Sauerstoff.",
                               "Pfeifender Knall → Wasserstoff.",
                               "Kalkwasser wird trüb → Kohlenstoffdioxid.",
                               "Nachweis = Durchführung + Beobachtung + Schlussfolgerung."]},
    "tasks": [
        aufgabe("GA02-A1-001", "A", 1, "choice",
                "Ein glimmender Span flammt im Gas hell auf. Welches Gas ist es?",
                options=["Sauerstoff", "Wasserstoff", "Kohlenstoffdioxid"], answer=0,
                visual=anim("nachweise", "A"),
                hints=["Welches Gas hilft beim Brennen?", "Sauerstoff.", "Der Span brennt weiter."],
                solution="Sauerstoff unterhält die Verbrennung. Der glimmende Span flammt hell auf.",
                misconceptions=[fv("nachweis_verwechselt", 2,
                                   "Kohlenstoffdioxid löscht die Glut, es lässt sie nicht aufflammen.",
                                   "nachweis_verwechselt")],
                tags=["nachweise"], spiral=["W-GLEI"]),
        aufgabe("GA02-A2-002", "A", 2, "assign",
                "Ordne jedem Gas seinen Nachweis zu.",
                slots=["Sauerstoff", "Wasserstoff", "Kohlenstoffdioxid"],
                values=["Glimmspanprobe", "Knallgasprobe", "Kalkwasserprobe"],
                answer=[0, 1, 2],
                hints=["Drei Gase, drei Proben.", "Wasserstoff macht ein Geräusch.", "Kalkwasser wird trüb."],
                solution="Sauerstoff → Glimmspanprobe.\nWasserstoff → Knallgasprobe.\nKohlenstoffdioxid → Kalkwasserprobe.",
                tags=["nachweise"], spiral=["W-GLEI"]),
        aufgabe("GA02-A3-003", "A", 3, "choice",
                "Kalkwasser wird beim Einleiten eines Gases milchig trüb. Welches Gas war es?",
                options=["Kohlenstoffdioxid", "Sauerstoff", "Stickstoff"], answer=0,
                hints=["Welche Probe ist das?", "Die Kalkwasserprobe.", "Sie zeigt Kohlenstoffdioxid an."],
                solution="Die Trübung des Kalkwassers ist der Nachweis für Kohlenstoffdioxid.",
                tags=["nachweise"], spiral=["W-GLEI"]),
        aufgabe("GA02-A4-004", "A", 4, "choice",
                "Warum darf die Knallgasprobe nur mit kleinen Mengen gemacht werden?",
                options=["Weil die Reaktion sehr schnell abläuft.", "Weil Wasserstoff giftig ist.", "Weil sie sonst nicht funktioniert."],
                answer=0,
                hints=["Was passiert bei der Knallgasprobe?", "Es knallt.", "Bei viel Gas wird es gefährlich."],
                solution="Wasserstoff und Sauerstoff reagieren explosionsartig. Bei kleinen Mengen bleibt es beim Knall — bei großen wird es gefährlich.",
                misconceptions=[fv("wasserstoff_giftig", 1,
                                   "Wasserstoff ist nicht giftig. Gefährlich ist die sehr schnelle Reaktion.",
                                   "sicherheitsregel_missachtet")],
                tags=["nachweise", "sicherheit"]),
        aufgabe("GA02-B1-005", "B", 1, "choice",
                "Wie wird die Kalkwasserprobe richtig durchgeführt?",
                options=["Das Gas wird in klares Kalkwasser eingeleitet.",
                         "Kalkwasser wird in das Gas gegossen.",
                         "Kalkwasser wird erhitzt."],
                answer=0,
                hints=["Das Gas muss mit der Lösung in Kontakt kommen.",
                       "Man leitet es ein.",
                       "Dann kann die Reaktion ablaufen."],
                solution="Das Gas wird durch ein Rohr in klares Kalkwasser eingeleitet. Nur so kommt es ausreichend mit der Lösung in Kontakt.",
                tags=["nachweise", "arbeitstechnik", "bbr"]),
        aufgabe("GA02-B2-006", "B", 2, "choice",
                "Ein Reagenzglas mit einem Gas erzeugt beim Entzünden einen dumpfen Knall statt eines pfeifenden. Was bedeutet das?",
                options=["Das Gas war mit Luft vermischt.", "Es war kein Wasserstoff.", "Das Reagenzglas war zu klein."],
                answer=0,
                hints=["Wovon hängt das Geräusch ab?", "Von der Reinheit des Gases.", "Luftbeimischung dämpft den Knall."],
                solution="Ein pfeifender Knall zeigt nahezu reinen Wasserstoff an. Ein dumpfer Knall bedeutet, dass Luft beigemischt war — das Gas war noch nicht vollständig aufgefangen.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Es knallt — also ist Wasserstoff da. Nur nicht rein genug.",
                                   "nachweis_verwechselt")],
                tags=["nachweise", "bbr"], spiral=["W-GLEI"]),
        aufgabe("GA02-B2-007", "B", 2, "choice",
                "Warum eignet sich die Glimmspanprobe nicht als Nachweis für Kohlenstoffdioxid?",
                options=["Auch Stickstoff und andere Gase lassen den Span erlöschen — die Beobachtung wäre nicht eindeutig.",
                         "Kohlenstoffdioxid lässt den Span aufflammen.",
                         "Der Span ist zu klein."],
                answer=0,
                hints=["Was tut der Span in Stickstoff?",
                       "Er erlischt ebenfalls.",
                       "Also ist die Beobachtung nicht eindeutig."],
                solution="Der Span erlischt in jedem Gas, das die Verbrennung nicht unterhält — auch in Stickstoff oder Argon. Ein Nachweis muss eindeutig sein, deshalb braucht Kohlenstoffdioxid das Kalkwasser.",
                tags=["nachweise", "bewerten", "bbr"]),
        aufgabe("GA02-B3-008", "B", 3, "assign",
                "Ordne jeder Beobachtung die richtige Schlussfolgerung zu.",
                slots=["Span flammt auf", "Kalkwasser bleibt klar", "pfeifender Knall"],
                values=["Sauerstoff ist vorhanden", "kein Kohlenstoffdioxid vorhanden", "Wasserstoff ist vorhanden"],
                answer=[0, 1, 2],
                hints=["Auch ein negativer Befund ist ein Ergebnis.",
                       "Klares Kalkwasser heißt: kein CO₂.",
                       "Der Knall gehört zum Wasserstoff."],
                solution="Span flammt auf → Sauerstoff.\nKalkwasser klar → kein Kohlenstoffdioxid.\nPfeifender Knall → Wasserstoff.",
                tags=["nachweise", "bbr"]),
        aufgabe("GA02-B3-009", "B", 3, "choice",
                "In einem Gasgemisch soll geprüft werden, ob Sauerstoff und Kohlenstoffdioxid enthalten sind. Welche Reihenfolge ist sinnvoll?",
                options=["Erst Kalkwasser einleiten, dann den Glimmspan halten.",
                         "Erst den Glimmspan, dann das Kalkwasser.",
                         "Die Reihenfolge ist egal."],
                answer=0,
                hints=["Was verändert die Probe?",
                       "Der brennende Span verbraucht Sauerstoff und erzeugt CO₂.",
                       "Das würde die zweite Probe verfälschen."],
                solution="Der brennende Span verbraucht Sauerstoff und erzeugt Kohlenstoffdioxid — er verfälscht die Kalkwasserprobe. Deshalb wird zuerst auf CO₂ geprüft.",
                tags=["nachweise", "planen", "msa"]),
        aufgabe("GA02-B4-010", "B", 4, "choice",
                "Warum beschlägt bei der Knallgasprobe die Innenwand des Reagenzglases?",
                options=["Es entsteht Wasser, das an der kühleren Wand kondensiert.",
                         "Das Glas schmilzt an.", "Der Wasserstoff wird flüssig."],
                answer=0,
                hints=["Was entsteht bei der Reaktion?",
                       "Wasser.",
                       "Es schlägt sich an der kühlen Wand nieder."],
                solution="2 H₂ + O₂ → 2 H₂O. Das entstehende Wasser kondensiert an der kühleren Glaswand — ein zusätzlicher Beleg für das Produkt.",
                tags=["nachweise", "bbr"], spiral=["W-GLEI"]),
        aufgabe("GA02-C2-011", "C", 2, "choice",
                "Warum wird das Kalkwasser bei längerem Einleiten von CO₂ wieder klar?",
                options=["Im Überschuss bildet sich lösliches Hydrogencarbonat, der Niederschlag löst sich wieder auf.",
                         "Das Kalkwasser ist verbraucht.", "Der Versuch war fehlerhaft."],
                answer=0,
                hints=["Der Niederschlag verschwindet, nicht das Kalkwasser.",
                       "Es entsteht eine lösliche Verbindung.",
                       "Das ist Calciumhydrogencarbonat."],
                solution="Zunächst fällt schwerlösliches Calciumcarbonat aus. Bei weiterem Einleiten entsteht daraus lösliches Calciumhydrogencarbonat — die Trübung verschwindet. Deshalb wird nur kurz eingeleitet.",
                tags=["nachweise", "msa"], spiral=["W-LOES"]),
        aufgabe("GA02-C3-012", "C", 3, "choice",
                "Ein Schüler prüft ein Gas mit dem Glimmspan; er flammt auf. Er schließt: „Das Gas ist reiner Sauerstoff.“ Was fehlt?",
                options=["Der Nachweis zeigt nur, dass Sauerstoff enthalten ist — über die Reinheit sagt er nichts.",
                         "Nichts, der Schluss ist vollständig.",
                         "Der Span hätte erlöschen müssen."],
                answer=0,
                hints=["Was genau zeigt der Nachweis an?",
                       "Anwesenheit, nicht Reinheit.",
                       "Auch sauerstoffangereicherte Luft lässt den Span aufflammen."],
                solution="Der Nachweis belegt die Anwesenheit von Sauerstoff. Auch ein Gemisch mit erhöhtem Sauerstoffanteil lässt den Span aufflammen. Über die Reinheit sagt die Probe nichts.",
                misconceptions=[fv("nachweis_ueberdehnt", 1,
                                   "Ein Nachweis zeigt Anwesenheit, nicht Reinheit oder Menge.",
                                   "nachweis_verwechselt")],
                tags=["nachweise", "bewerten", "msa"]),
        aufgabe("GA02-C3-013", "C", 3, "multi",
                "Bei der Knallgasprobe reagieren Wasserstoff und Sauerstoff im Volumenverhältnis 2 : 1.",
                fields=[
                    {"label": "Sauerstoffvolumen für 40 mL Wasserstoff", "answer": 20, "unit_label": "mL", "tolerance": 0.5,
                     "misconceptions": [fv("verhaeltnis_umgedreht", 80,
                                           "Vom Sauerstoff wird die <b>Hälfte</b> gebraucht, nicht das Doppelte.")]},
                    {"label": "Gesamtvolumen des reagierenden Gemisches", "answer": 60, "unit_label": "mL", "tolerance": 0.5}
                ],
                hints=["2 Teile Wasserstoff auf 1 Teil Sauerstoff.",
                       "40 mL : 2 = 20 mL.",
                       "40 + 20 = 60 mL."],
                solution="O₂: 40 mL : 2 = 20 mL\ngesamt: 40 + 20 = 60 mL",
                tags=["nachweise", "rechnen", "msa"], spiral=["W-GLEI", "W-RECH"]),
        aufgabe("GA02-C4-014", "C", 4, "choice",
                "In einem Kellerraum wird ein Gas vermutet, das Kerzen erlöschen lässt. Welche Untersuchung führt am sichersten zur Antwort?",
                options=["Kalkwasserprobe — sie unterscheidet Kohlenstoffdioxid eindeutig von anderen erstickenden Gasen.",
                         "Glimmspanprobe — sie zeigt an, welches Gas es ist.",
                         "Knallgasprobe — sie ist am empfindlichsten."],
                answer=0,
                hints=["Welche Gase lassen eine Kerze erlöschen?",
                       "Viele — Stickstoff, Argon, CO₂.",
                       "Nur ein Nachweis unterscheidet sie."],
                solution="Erlöschen ist nicht eindeutig: Auch Stickstoff und Argon tun das. Nur die Kalkwasserprobe unterscheidet Kohlenstoffdioxid von anderen erstickenden Gasen. Eine Knallgasprobe wäre in einem Kellerraum zudem gefährlich.",
                tags=["nachweise", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("ga", E, "Bereich GA · Einheiten 1 und 2")
