# -*- coding: utf-8 -*-
"""Bereich GA · Gase — GA-03 bis GA-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "GA-03",
    "title": "Elektronenpaarbindung und Oktettregel",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 7,
    "wortspeicher": ["die Elektronenpaarbindung", "die Atombindung", "das bindende Elektronenpaar",
                     "das freie Elektronenpaar", "die Oktettregel", "die Lewis-Formel", "das Molekül"],
    "worterklaerungen": {
        "Elektronenpaarbindung": "Zwei Atome teilen sich ein Elektronenpaar. Beide zählen es mit.",
        "Oktettregel": "Atome streben acht Außenelektronen an. Wasserstoff nur zwei.",
        "Lewis-Formel": "Eine Schreibweise mit Strichen für Elektronenpaare."
    },
    "can_do": {
        "A": "Ich weiß, dass zwei Nichtmetallatome sich Elektronen teilen, und erkenne einen Bindungsstrich.",
        "B": "Ich zeichne Lewis-Formeln einfacher Moleküle und wende die Oktettregel an.",
        "C": "Ich leite aus der Zahl der Außenelektronen die Zahl der Bindungen ab und begründe Mehrfachbindungen."
    },
    "lernkarten": {
        "A": karte("Teilen statt abgeben",
                   "Zwei Nichtmetallatome geben keine Elektronen ab.",
                   ["Sie teilen sich ein Paar.", "Der Strich in der Formel ist dieses Paar."],
                   "Ein Strich = ein gemeinsames Elektronenpaar.",
                   visual=anim("oktettregel", "A"),
                   beispiel={"titel": "Wasserstoff", "aufgabe": "Zwei H-Atome kommen zusammen.",
                             "schritte": ["Jedes bringt ein Elektron mit.", "Zusammen ein Paar.",
                                          "Fertig ist H₂."],
                             "ergebnis": "H–H"}),
        "B": karte("Die Oktettregel anwenden",
                   "Ein Atom bildet so viele Bindungen, wie ihm zur vollen Außenschale fehlen. Diese eine Regel erklärt fast alle Molekülformeln der Mittelstufe.",
                   ["Fehlende Elektronen = 8 minus Außenelektronen. Bei Wasserstoff: 2 minus 1.",
                    "Sauerstoff hat 6 Außenelektronen, ihm fehlen 2 — er bildet zwei Bindungen. Deshalb H₂O.",
                    "Stickstoff hat 5, ihm fehlen 3 — er bildet drei Bindungen. Deshalb NH₃.",
                    "Kohlenstoff hat 4, ihm fehlen 4 — er bildet vier Bindungen. Deshalb CH₄.",
                    "Elektronenpaare, die nicht an einer Bindung beteiligt sind, heißen freie Elektronenpaare."],
                   "Zahl der Bindungen = 8 − Außenelektronen (bei Wasserstoff: 2 − 1).",
                   visual={"type": "lewis", "molekuel": "h2o", "formel": "H2O",
                           "alt": "Lewis-Formel von Wasser mit zwei bindenden und zwei freien Elektronenpaaren."}),
        "C": karte("Wenn ein Paar nicht reicht",
                   "Manchmal genügt ein gemeinsames Elektronenpaar nicht, um beide Atome auf acht zu bringen. Dann werden zwei oder drei Paare geteilt.",
                   ["Sauerstoff fehlen je zwei Elektronen. Zwei Sauerstoffatome teilen deshalb zwei Paare — eine Doppelbindung, O₂.",
                    "Stickstoff fehlen je drei. N₂ hat eine Dreifachbindung. Sie ist sehr stabil — deshalb ist Stickstoff so reaktionsträge und macht 78 % der Luft aus, ohne mit irgendetwas zu reagieren.",
                    "Je mehr Paare geteilt werden, desto kürzer und fester ist die Bindung.",
                    "Edelgase bilden gar keine Bindungen: Ihre Schale ist bereits voll."],
                   "Eine Mehrfachbindung entsteht, wenn ein geteiltes Paar nicht ausreicht.",
                   visual={"type": "lewis", "molekuel": "n2", "formel": "N2",
                           "alt": "Lewis-Formel von Stickstoff mit einer Dreifachbindung."})
    },
    "formelkarte": {"formeln": ["Zahl der Bindungen = 8 − Außenelektronen",
                               "H₂ · O₂ · N₂ · H₂O · NH₃ · CH₄ · CO₂"],
                    "saetze": ["Ein Strich = ein gemeinsames Elektronenpaar.",
                               "Oktettregel: acht Außenelektronen, bei Wasserstoff zwei.",
                               "Bindungen: H 1 · O 2 · N 3 · C 4.",
                               "Freie Elektronenpaare gehören nur einem Atom."]},
    "tasks": [
        aufgabe("GA03-A1-001", "A", 1, "choice",
                "Was bedeutet der Strich zwischen zwei Atomen in H–H?",
                options=["Ein gemeinsames Elektronenpaar", "Ein Elektron", "Ein Abstand"], answer=0,
                visual=anim("oktettregel", "A"),
                hints=["Der Strich steht für Elektronen.", "Es sind zwei.", "Ein Paar."],
                solution="Ein Strich steht für ein gemeinsames Elektronenpaar — zwei Elektronen, die beiden Atomen gehören.",
                misconceptions=[fv("strich_als_elektron", 1,
                                   "Ein Strich sind zwei Elektronen, nicht eines.",
                                   "bindungsart_verwechselt")],
                tags=["bindung"], spiral=["K-BIND"]),
        aufgabe("GA03-A2-002", "A", 2, "numeric",
                "Wie viele Außenelektronen hat Sauerstoff?",
                answer=6, tolerance=0,
                hints=["Sauerstoff steht in Hauptgruppe VI.", "Die Gruppennummer gibt die Außenelektronen.", "6."],
                solution="Sauerstoff steht in Hauptgruppe VI und hat 6 Außenelektronen.",
                tags=["bindung"], spiral=["K-ATOM"]),
        aufgabe("GA03-A3-003", "A", 3, "numeric",
                "Wie viele Elektronen fehlen dem Sauerstoff zur vollen Schale?",
                answer=2, tolerance=0,
                hints=["Voll heißt 8.", "8 − 6.", "2."],
                solution="8 − 6 = 2. Sauerstoff bildet deshalb zwei Bindungen.",
                misconceptions=[fv("ladung_falsch_herum", 6,
                                   "Das ist die Zahl der vorhandenen Außenelektronen. Gefragt war, wie viele fehlen.",
                                   "ladung_unvollstaendig")],
                tags=["bindung"], spiral=["K-ATOM"]),
        aufgabe("GA03-A4-004", "A", 4, "choice",
                "Warum bildet Wasser die Formel H₂O und nicht HO?",
                options=["Sauerstoff braucht zwei Bindungen, also zwei H-Atome.",
                         "Weil Wasser leichter ist.", "Zufall."],
                answer=0, visual={"type": "lewis", "molekuel": "h2o", "alt": "Lewis-Formel von Wasser."},
                hints=["Wie viele Bindungen bildet Sauerstoff?", "Zwei.", "Also zwei Wasserstoffatome."],
                solution="Sauerstoff fehlen zwei Elektronen, er bildet zwei Bindungen. Jedes Wasserstoffatom liefert eine — also H₂O.",
                tags=["bindung"], spiral=["K-BIND"]),
        aufgabe("GA03-B1-005", "B", 1, "assign",
                "Ordne jedem Atom die Zahl seiner Bindungen zu.",
                slots=["Wasserstoff", "Sauerstoff", "Stickstoff"],
                values=["1", "2", "3"], answer=[0, 1, 2],
                hints=["8 minus Außenelektronen — außer bei Wasserstoff.",
                       "Sauerstoff hat 6 Außenelektronen.",
                       "Stickstoff hat 5."],
                solution="Wasserstoff: 2 − 1 = 1 Bindung.\nSauerstoff: 8 − 6 = 2.\nStickstoff: 8 − 5 = 3.",
                tags=["bindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("GA03-B2-006", "B", 2, "numeric",
                "Wie viele Wasserstoffatome bindet ein Kohlenstoffatom?",
                answer=4, tolerance=0,
                visual={"type": "lewis", "molekuel": "ch4", "alt": "Lewis-Formel von Methan."},
                hints=["Kohlenstoff hat 4 Außenelektronen.", "8 − 4 = 4.", "Also vier H-Atome."],
                solution="Kohlenstoff fehlen 4 Elektronen und bildet 4 Bindungen: CH₄, das Methan.",
                misconceptions=[fv("formel_ohne_plus_zwei", 2,
                                   "Kohlenstoff bildet vier Bindungen, nicht zwei.",
                                   "summenformel_falsch_gelesen")],
                tags=["bindung", "bbr"], spiral=["K-BIND"]),
        aufgabe("GA03-B2-007", "B", 2, "choice",
                "Was ist ein freies Elektronenpaar?",
                options=["Ein Paar, das nur einem Atom gehört und keine Bindung bildet.",
                         "Ein Paar, das zwischen zwei Atomen liegt.",
                         "Ein Elektron ohne Partner."],
                answer=0, visual={"type": "lewis", "molekuel": "nh3", "alt": "Lewis-Formel von Ammoniak."},
                hints=["Nicht jedes Paar bildet eine Bindung.",
                       "Manche gehören nur einem Atom.",
                       "Die heißen frei."],
                solution="Ein freies Elektronenpaar gehört nur einem Atom und ist an keiner Bindung beteiligt. In der Lewis-Formel steht es als Strich am Atom, nicht zwischen zwei Atomen.",
                tags=["bindung", "bbr"], spiral=["K-BIND"]),
        aufgabe("GA03-B3-008", "B", 3, "choice",
                "Warum hat Sauerstoff im O₂-Molekül eine Doppelbindung?",
                options=["Jedem Atom fehlen zwei Elektronen; ein geteiltes Paar reicht nicht.",
                         "Weil Sauerstoff schwer ist.", "Damit das Molekül stabiler aussieht."],
                answer=0, visual={"type": "lewis", "molekuel": "o2", "alt": "Lewis-Formel von Sauerstoff mit Doppelbindung."},
                hints=["Wie viele Elektronen fehlen jedem Sauerstoffatom?",
                       "Zwei.",
                       "Ein Paar bringt nur eines pro Atom."],
                solution="Jedem Sauerstoffatom fehlen zwei Elektronen. Ein einzelnes geteiltes Paar würde nur eines liefern — deshalb werden zwei Paare geteilt: eine Doppelbindung.",
                tags=["bindung", "bbr"], spiral=["K-BIND"]),
        aufgabe("GA03-B3-009", "B", 3, "numeric",
                "Wie viele bindende Elektronenpaare enthält ein Methanmolekül CH₄?",
                answer=4, tolerance=0,
                hints=["Jede Bindung ist ein Paar.", "Kohlenstoff bildet vier Bindungen.", "4."],
                solution="Vier Bindungen, also vier bindende Elektronenpaare. Freie Elektronenpaare hat Methan keine.",
                tags=["bindung", "bbr"], spiral=["K-BIND"]),
        aufgabe("GA03-B4-010", "B", 4, "choice",
                "Warum bilden Edelgase keine Moleküle?",
                options=["Ihre Außenschale ist bereits voll — es fehlt nichts.",
                         "Sie sind zu schwer.", "Sie sind zu selten."],
                answer=0,
                hints=["Wann bildet ein Atom eine Bindung?",
                       "Wenn ihm Elektronen fehlen.",
                       "Edelgasen fehlt nichts."],
                solution="Edelgase haben bereits acht Außenelektronen. Es fehlt ihnen nichts, also bilden sie keine Bindungen und kommen als einzelne Atome vor.",
                tags=["bindung", "msa"], spiral=["K-ATOM"]),
        aufgabe("GA03-C2-011", "C", 2, "choice",
                "Warum ist Stickstoff so reaktionsträge, obwohl er 78 % der Luft ausmacht?",
                options=["Die Dreifachbindung im N₂-Molekül ist sehr stabil und muss erst gebrochen werden.",
                         "Stickstoff ist zu leicht.", "Stickstoff ist ein Edelgas."],
                answer=0, visual={"type": "lewis", "molekuel": "n2", "alt": "Lewis-Formel von Stickstoff."},
                hints=["Wie viele Paare teilen sich zwei Stickstoffatome?",
                       "Drei.",
                       "Diese Bindung ist sehr fest."],
                solution="Zwei Stickstoffatome teilen sich drei Elektronenpaare. Diese Dreifachbindung ist außerordentlich stabil — sie zu brechen kostet viel Energie. Deshalb reagiert Stickstoff kaum, obwohl er überall ist.",
                misconceptions=[fv("edelgas_verwechselt", 2,
                                   "Stickstoff ist kein Edelgas. Seine Trägheit kommt von der Dreifachbindung.",
                                   "bindungsart_verwechselt")],
                tags=["bindung", "erklaeren", "msa"], spiral=["K-BIND"]),
        aufgabe("GA03-C3-012", "C", 3, "multi",
                "Betrachte das Kohlenstoffdioxid-Molekül CO₂.",
                fields=[
                    {"label": "Zahl der Bindungen des Kohlenstoffatoms", "answer": 4, "tolerance": 0},
                    {"label": "Zahl der Doppelbindungen im Molekül", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der freien Elektronenpaare insgesamt", "answer": 4, "tolerance": 0}
                ],
                visual={"type": "lewis", "molekuel": "co2", "alt": "Lewis-Formel von Kohlenstoffdioxid."},
                hints=["Kohlenstoff bildet immer vier Bindungen.",
                       "Zwei Sauerstoffatome mit je zwei Bindungen.",
                       "Jedes Sauerstoffatom trägt zwei freie Paare."],
                solution="C bildet 4 Bindungen, verteilt auf zwei Doppelbindungen (O=C=O).\nJedes O-Atom trägt zwei freie Elektronenpaare, zusammen 4.",
                tags=["bindung", "msa"], spiral=["K-BIND"]),
        aufgabe("GA03-C3-013", "C", 3, "choice",
                "Ein Schüler zeichnet H–O–H mit einem zusätzlichen Strich zwischen den beiden H-Atomen. Was ist falsch?",
                options=["Wasserstoff kann nur eine Bindung bilden — er hat nur ein Elektron beizusteuern.",
                         "Nichts, die Formel ist richtig.",
                         "Der Sauerstoff müsste vier Bindungen haben."],
                answer=0,
                hints=["Wie viele Bindungen bildet Wasserstoff?",
                       "Genau eine.",
                       "Für eine zweite fehlt ihm das Elektron."],
                solution="Wasserstoff hat ein Außenelektron und erreicht mit einer Bindung bereits die volle Schale von zwei. Eine zweite Bindung ist ihm nicht möglich.",
                misconceptions=[fv("oktett_auf_wasserstoff", 2,
                                   "Sauerstoff bildet zwei Bindungen. Der Fehler liegt beim Wasserstoff.",
                                   "bindungsart_verwechselt")],
                tags=["bindung", "bewerten", "msa"], spiral=["K-BIND"]),
        aufgabe("GA03-C4-014", "C", 4, "choice",
                "Warum gilt die Oktettregel für Wasserstoff nicht?",
                options=["Seine erste Schale fasst nur zwei Elektronen — mehr passen nicht hinein.",
                         "Wasserstoff ist eine Ausnahme ohne Grund.",
                         "Wasserstoff hat gar keine Elektronen."],
                answer=0,
                hints=["Wie viele Elektronen fasst die erste Schale?",
                       "Zwei.",
                       "Voll ist bei Wasserstoff also schon bei zwei erreicht."],
                solution="Die Oktettregel beschreibt eine volle Außenschale. Bei Wasserstoff ist die äußerste Schale die erste, und die fasst nur zwei Elektronen. Die Regel ist also nicht durchbrochen, sondern richtig angewendet.",
                tags=["bindung", "bewerten", "msa"], spiral=["K-ATOM"])
    ]
})

E.append({
    "unit": "GA-04",
    "title": "Treibhausgase, Luftschadstoffe, Edelgase",
    "leitidee": "B3",
    "standards": ["K1", "K3.3", "K4.1", "K4.3"],
    "klasse": 7,
    "wortspeicher": ["das Treibhausgas", "der Treibhauseffekt", "das Stickoxid", "der Katalysator",
                     "das Edelgas", "der Feinstaub"],
    "worterklaerungen": {
        "Treibhausgas": "Ein Gas, das Wärmestrahlung von der Erde zurückhält.",
        "Katalysator": "Ein Stoff, der eine Reaktion beschleunigt und dabei selbst erhalten bleibt.",
        "Stickoxid": "Eine Verbindung aus Stickstoff und Sauerstoff. Entsteht bei hohen Verbrennungstemperaturen."
    },
    "can_do": {
        "A": "Ich nenne Treibhausgase und eine Maßnahme zu ihrer Verringerung.",
        "B": "Ich erkläre den Treibhauseffekt und die Wirkung eines Katalysators.",
        "C": "Ich bewerte Maßnahmen zur Luftreinhaltung und begründe meine Einschätzung."
    },
    "lernkarten": {
        "A": karte("Gase, die die Erde wärmen",
                   "Manche Gase halten Wärme zurück.",
                   ["Kohlenstoffdioxid ist eines davon.", "Es entsteht beim Verbrennen."],
                   "Weniger verbrennen heißt weniger Treibhausgas.",
                   visual={"type": "anteil", "titel": "Treibhausgase im Vergleich",
                           "segmente": [{"anteil": 76, "label": "CO₂"}, {"anteil": 16, "label": "CH₄"},
                                        {"anteil": 8, "label": "andere"}],
                           "alt": "Anteile der Treibhausgase am menschengemachten Treibhauseffekt."},
                   beispiel={"titel": "Woher CO₂ kommt", "aufgabe": "Wobei entsteht Kohlenstoffdioxid?",
                             "schritte": ["Beim Verbrennen von Holz, Kohle, Öl und Gas.",
                                          "Beim Atmen.", "In Kraftwerken und Motoren."],
                             "ergebnis": "Überall, wo Kohlenstoff verbrennt."}),
        "B": karte("Treibhauseffekt und Katalysator",
                   "Zwei Wirkungen, die oft verwechselt werden: Das eine betrifft das Klima, das andere die Abgasreinigung.",
                   ["Sonnenlicht erwärmt den Boden. Der Boden gibt Wärmestrahlung ab. Treibhausgase halten einen Teil davon zurück — ohne sie wäre die Erde rund 33 °C kälter.",
                    "Problematisch ist die Verstärkung durch zusätzliche Gase aus Verbrennungsprozessen.",
                    "Der Autokatalysator wandelt schädliche Abgase um: Stickoxide werden zu Stickstoff reduziert, Kohlenstoffmonoxid zu Kohlenstoffdioxid oxidiert.",
                    "Der Katalysator wird dabei nicht verbraucht — er beschleunigt nur. Am Kohlenstoffdioxid ändert er nichts."],
                   "Der Katalysator reinigt Abgase. Gegen Kohlenstoffdioxid hilft er nicht.",
                   visual={"type": "energie", "verlauf": "exotherm", "katalysator": True,
                           "alt": "Energiediagramm mit und ohne Katalysator."}),
        "C": karte("Maßnahmen beurteilen",
                   "Eine Bewertung braucht ein Kriterium. Ohne Kriterium ist „gut“ oder „schlecht“ nur eine Meinung — und dann ist auch die Note für die Antwort eine Meinung.",
                   ["Wirksamkeit: Um wie viel sinkt der Ausstoß tatsächlich? Ein Katalysator senkt Stickoxide stark, Kohlenstoffdioxid gar nicht.",
                    "Reichweite: Betrifft die Maßnahme die Ursache oder nur die Folge? Filter behandeln Folgen, Verbrauchssenkung die Ursache.",
                    "Nebenwirkungen und Kosten: Wer trägt sie, und stehen sie im Verhältnis?",
                    "Eine gute Antwort nennt das Kriterium, wendet es an und kommt dann zu einem Urteil — in dieser Reihenfolge."],
                   "Erst das Kriterium nennen, dann bewerten.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["2 CO + O₂ → 2 CO₂", "2 NO → N₂ + O₂  (am Katalysator)"],
                    "saetze": ["Treibhausgase: CO₂, Methan, Lachgas, Wasserdampf.",
                               "Ohne natürlichen Treibhauseffekt wäre die Erde rund 33 °C kälter.",
                               "Der Katalysator wird nicht verbraucht.",
                               "Edelgase: reaktionsträge, volle Außenschale.",
                               "Bewerten heißt: Kriterium nennen, anwenden, urteilen."]},
    "tasks": [
        aufgabe("GA04-A1-001", "A", 1, "choice",
                "Welches Gas ist das wichtigste vom Menschen verursachte Treibhausgas?",
                options=["Kohlenstoffdioxid", "Stickstoff", "Argon"], answer=0,
                hints=["Es entsteht beim Verbrennen.", "Es ist in der Luft nur zu 0,04 % enthalten.", "Kohlenstoffdioxid."],
                solution="Kohlenstoffdioxid ist das wichtigste vom Menschen verursachte Treibhausgas. Stickstoff und Argon wirken nicht als Treibhausgase.",
                tags=["umwelt"], spiral=["K-STOF"]),
        aufgabe("GA04-A2-002", "A", 2, "choice",
                "Wobei entsteht Kohlenstoffdioxid?",
                options=["Beim Verbrennen von Holz, Kohle, Öl und Gas", "Beim Schmelzen von Eis", "Beim Lösen von Salz"],
                answer=0,
                hints=["Es geht um eine chemische Reaktion.", "Kohlenstoff reagiert mit Sauerstoff.", "Beim Verbrennen."],
                solution="Kohlenstoffdioxid entsteht bei jeder Verbrennung kohlenstoffhaltiger Stoffe.",
                tags=["umwelt"], spiral=["K-REAK"]),
        aufgabe("GA04-A3-003", "A", 3, "choice",
                "Was tut ein Katalysator im Auto?",
                options=["Er wandelt schädliche Abgase in weniger schädliche um.",
                         "Er verbraucht weniger Benzin.", "Er kühlt den Motor."],
                answer=0,
                hints=["Der Katalysator sitzt im Abgasstrang.", "Er verändert die Abgase.", "Er macht sie weniger schädlich."],
                solution="Der Katalysator wandelt Stickoxide und Kohlenstoffmonoxid in Stickstoff und Kohlenstoffdioxid um.",
                tags=["umwelt"], spiral=["K-REAK"]),
        aufgabe("GA04-A4-004", "A", 4, "choice",
                "Warum werden Edelgase in Glühlampen und Luftballons verwendet?",
                options=["Sie reagieren nicht.", "Sie sind besonders billig.", "Sie leuchten von selbst."],
                answer=0,
                hints=["Was ist typisch für Edelgase?", "Sie reagieren kaum.", "Deshalb sind sie sicher."],
                solution="Edelgase reagieren nicht. In der Glühlampe verhindern sie das Verbrennen des Drahts, im Ballon können sie sich nicht entzünden — anders als Wasserstoff.",
                tags=["umwelt", "edelgase"], spiral=["K-ATOM"]),
        aufgabe("GA04-B1-005", "B", 1, "choice",
                "Wie wirkt der Treibhauseffekt?",
                options=["Treibhausgase halten einen Teil der von der Erde abgestrahlten Wärme zurück.",
                         "Treibhausgase erwärmen sich in der Sonne und heizen die Luft.",
                         "Treibhausgase lassen mehr Sonnenlicht durch."],
                answer=0,
                hints=["Was passiert mit der Wärme, die die Erde abgibt?",
                       "Ein Teil wird zurückgehalten.",
                       "Sonnenlicht kommt hinein, Wärmestrahlung kommt schlechter hinaus."],
                solution="Sonnenlicht erreicht den Boden und erwärmt ihn. Der Boden strahlt Wärme ab, und Treibhausgase halten einen Teil davon zurück. Ohne diesen natürlichen Effekt wäre die Erde rund 33 °C kälter.",
                misconceptions=[fv("gas_erwaermt_sich", 1,
                                   "Die Gase heizen nicht selbst. Sie halten die von der Erde abgestrahlte Wärme zurück.")],
                tags=["umwelt", "bbr"], spiral=["K-STOF"]),
        aufgabe("GA04-B2-006", "B", 2, "choice",
                "Ein Katalysator wird bei der Reaktion nicht verbraucht. Was folgt daraus?",
                options=["Eine kleine Menge genügt für sehr viele Reaktionen.",
                         "Er muss ständig nachgefüllt werden.",
                         "Er verändert die Produkte."],
                answer=0,
                hints=["Was heißt „nicht verbraucht“?",
                       "Er liegt nach der Reaktion unverändert vor.",
                       "Also kann er wieder wirken."],
                solution="Der Katalysator liegt nach der Reaktion unverändert vor und kann erneut wirken. Deshalb reicht eine kleine Menge — im Autokatalysator wenige Gramm Edelmetall.",
                tags=["umwelt", "katalysator", "bbr"]),
        aufgabe("GA04-B2-007", "B", 2, "choice",
                "Warum entstehen Stickoxide gerade im Motor, obwohl Stickstoff sonst kaum reagiert?",
                options=["Bei den hohen Temperaturen im Motor wird die stabile Dreifachbindung aufgebrochen.",
                         "Weil Benzin Stickstoff enthält.",
                         "Weil der Katalysator sie erzeugt."],
                answer=0,
                hints=["Was macht Stickstoff normalerweise reaktionsträge?",
                       "Die Dreifachbindung.",
                       "Bei sehr hoher Temperatur bricht sie auf."],
                solution="Stickstoff ist wegen seiner Dreifachbindung träge. Bei über 1000 °C im Motor reicht die Energie, sie aufzubrechen — dann reagiert der Luftstickstoff mit dem Luftsauerstoff zu Stickoxiden.",
                misconceptions=[fv("brennstoff_als_quelle", 1,
                                   "Der Stickstoff stammt aus der Luft, nicht aus dem Kraftstoff.")],
                tags=["umwelt", "bbr"], spiral=["K-REAK"]),
        aufgabe("GA04-B3-008", "B", 3, "numeric",
                "Ein Auto stößt 120 g CO₂ je Kilometer aus. Wie viele Kilogramm sind das auf 1000 km?",
                answer=120, unit_label="kg", tolerance=1,
                hints=["120 g mal 1000 km.", "Das sind 120 000 g.", "In Kilogramm: durch 1000."],
                solution="120 g/km · 1000 km = 120 000 g = 120 kg",
                misconceptions=[fv("faktor_falsch", 120000,
                                   "Gefragt war in Kilogramm. 120 000 g sind 120 kg.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["umwelt", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("GA04-B3-009", "B", 3, "choice",
                "Welche Maßnahme senkt den Kohlenstoffdioxid-Ausstoß eines Autos tatsächlich?",
                options=["Weniger fahren oder weniger Kraftstoff verbrauchen.",
                         "Ein besserer Katalysator.", "Ein Rußpartikelfilter."],
                answer=0,
                hints=["Woraus entsteht CO₂?",
                       "Aus dem verbrannten Kraftstoff.",
                       "Der Katalysator ändert daran nichts."],
                solution="Kohlenstoffdioxid entsteht zwangsläufig aus dem verbrannten Kohlenstoff. Katalysator und Partikelfilter reinigen andere Bestandteile, am CO₂ ändern sie nichts. Nur weniger Kraftstoff bedeutet weniger CO₂.",
                misconceptions=[fv("katalysator_gegen_co2", 1,
                                   "Der Katalysator wandelt CO sogar <b>zu</b> CO₂ um. Er verringert es nicht.")],
                tags=["umwelt", "bewerten", "bbr"], spiral=["K-REAK"]),
        aufgabe("GA04-B4-010", "B", 4, "choice",
                "Warum werden Heliumballons statt Wasserstoffballons verwendet, obwohl Wasserstoff leichter ist?",
                options=["Helium ist ein Edelgas und nicht brennbar.",
                         "Helium ist billiger.", "Wasserstoff steigt nicht auf."],
                answer=0,
                hints=["Was ist an Wasserstoff gefährlich?",
                       "Er ist brennbar.",
                       "Helium reagiert gar nicht."],
                solution="Wasserstoff ist leichter, aber brennbar — die Hindenburg-Katastrophe zeigte die Folgen. Helium hat eine volle Außenschale, reagiert nicht und ist deshalb sicher.",
                tags=["umwelt", "edelgase", "bbr"], spiral=["K-ATOM"]),
        aufgabe("GA04-C2-011", "C", 2, "choice",
                "Warum ist der natürliche Treibhauseffekt kein Problem, seine Verstärkung aber schon?",
                options=["Ohne ihn wäre die Erde unbewohnbar kalt; problematisch ist die zusätzliche Erwärmung durch mehr Treibhausgase.",
                         "Der natürliche Treibhauseffekt existiert nicht.",
                         "Beide sind gleich problematisch."],
                answer=0,
                hints=["Wie warm wäre die Erde ohne Treibhausgase?",
                       "Rund 33 °C kälter.",
                       "Das Problem ist die Zunahme, nicht der Effekt selbst."],
                solution="Ohne natürlichen Treibhauseffekt läge die Durchschnittstemperatur bei rund −18 °C. Problematisch ist nicht der Effekt, sondern seine rasche Verstärkung durch zusätzlich freigesetzte Gase.",
                tags=["umwelt", "bewerten", "msa"]),
        aufgabe("GA04-C3-012", "C", 3, "multi",
                "Ein Haushalt verbraucht im Jahr 1800 m³ Erdgas. Je Kubikmeter entstehen rund 2,0 kg CO₂.",
                fields=[
                    {"label": "CO₂-Ausstoß in Tonnen", "answer": 3.6, "unit_label": "t", "tolerance": 0.05},
                    {"label": "Ausstoß nach einer Verbrauchssenkung um 25 %, in Tonnen", "answer": 2.7, "unit_label": "t", "tolerance": 0.05}
                ],
                hints=["1800 · 2,0 kg.",
                       "3600 kg = 3,6 t.",
                       "25 % weniger heißt · 0,75."],
                solution="1800 m³ · 2,0 kg = 3600 kg = 3,6 t\nnach Senkung: 3,6 t · 0,75 = 2,7 t",
                tags=["umwelt", "rechnen", "msa"], spiral=["K-QUANT", "K-SL"]),
        aufgabe("GA04-C3-013", "C", 3, "choice",
                "Bewerte: „Ein Elektroauto ist immer klimafreundlicher als ein Verbrenner.“",
                options=["Die Aussage braucht ein Kriterium — entscheidend sind Strommix und Herstellung, nicht nur der Betrieb.",
                         "Die Aussage ist uneingeschränkt richtig.",
                         "Die Aussage ist uneingeschränkt falsch."],
                answer=0,
                hints=["Wo entsteht beim Elektroauto CO₂?",
                       "Bei der Stromerzeugung und der Herstellung.",
                       "Also hängt es davon ab, woher der Strom kommt."],
                solution="Im Betrieb stößt ein Elektroauto kein CO₂ aus. Ob es insgesamt klimafreundlicher ist, hängt vom Strommix und vom Aufwand der Batterieherstellung ab. Eine Bewertung ohne Bilanzgrenze ist keine.",
                misconceptions=[fv("bilanzgrenze_zu_eng", 1,
                                   "Nur den Betrieb zu betrachten, zieht die Bilanzgrenze zu eng — genau wie beim Wiegen im offenen Gefäß.",
                                   "masse_verschwindet")],
                tags=["umwelt", "bewerten", "msa"]),
        aufgabe("GA04-C4-014", "C", 4, "choice",
                "Welche Antwort auf „Beurteile den Nutzen eines Autokatalysators“ ist am besten?",
                options=["Er senkt Stickoxide und Kohlenstoffmonoxid deutlich, ändert am CO₂ aber nichts — gemessen an der Luftqualität ist er wirksam, gemessen am Klimaschutz nicht.",
                         "Er ist gut, weil er die Abgase reinigt.",
                         "Er ist schlecht, weil er teuer ist."],
                answer=0,
                hints=["Was verlangt „Beurteile“?",
                       "Ein Kriterium, seine Anwendung und ein Urteil.",
                       "Und die Antwort darf differenzieren."],
                solution="Eine Beurteilung nennt das Kriterium und wendet es an. Antwort 1 unterscheidet zwei Kriterien — Luftqualität und Klimaschutz — und kommt zu einem differenzierten Urteil. Die anderen behaupten nur.",
                tags=["umwelt", "operatoren", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("ga", E, "Bereich GA · Einheiten 3 und 4")
