# -*- coding: utf-8 -*-
"""Bereich SZ · Salze — SZ-04 und SZ-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "SZ-04",
    "title": "Löslichkeit, Leitfähigkeit, Kristalle",
    "leitidee": "B2",
    "standards": ["K1", "K2.2", "K2.4"],
    "klasse": 8,
    "wortspeicher": ["die Löslichkeit", "die gesättigte Lösung", "die Leitfähigkeit",
                     "die Kristallisation", "die Fällungsreaktion", "die Gitterenergie"],
    "worterklaerungen": {
        "gesättigte Lösung": "Es löst sich nichts mehr. Weiteres Salz bleibt als Bodensatz liegen.",
        "Kristallisation": "Aus einer Lösung wachsen wieder feste Kristalle.",
        "Fällungsreaktion": "Beim Mischen zweier Lösungen entsteht ein unlöslicher Feststoff."
    },
    "can_do": {
        "A": "Ich weiß, dass sich nur eine bestimmte Menge Salz löst, und erkenne eine gesättigte Lösung.",
        "B": "Ich rechne mit Löslichkeitsangaben und erkläre die Leitfähigkeit von Salzlösungen.",
        "C": "Ich erkläre Lösen und Ausfällen über Gitter- und Hydratationsenergie."
    },
    "lernkarten": {
        "A": karte("Nicht alles löst sich",
                   "In Wasser löst sich nur eine bestimmte Menge Salz.",
                   ["Danach bleibt der Rest liegen.", "Die Lösung ist dann gesättigt."],
                   "Ist die Grenze erreicht, bleibt der Rest als Bodensatz.",
                   visual=anim("ionengitter", "A"),
                   beispiel={"titel": "Kochsalz", "aufgabe": "In 100 g Wasser lösen sich 36 g Salz.",
                             "schritte": ["Du gibst 50 g hinein.", "36 g lösen sich.",
                                          "50 − 36 = 14 g bleiben liegen."],
                             "ergebnis": "14 g Bodensatz.",
                             "luecke": {"schritt": 2, "wert": 14, "einheit": "g"}}),
        "B": karte("Löslichkeit und Leitfähigkeit",
                   "Zwei messbare Größen, die beide etwas über die Ionen aussagen — die eine über ihre Menge, die andere über ihre Beweglichkeit.",
                   ["Die Löslichkeit wird in Gramm je 100 g Wasser angegeben und hängt stark von der Temperatur ab. Bei den meisten Salzen steigt sie mit der Temperatur.",
                    "Kühlt eine gesättigte heiße Lösung ab, kann sie das Salz nicht mehr halten — es kristallisiert aus. Langsames Abkühlen ergibt große Kristalle.",
                    "Je mehr Ionen in Lösung sind, desto besser leitet sie. Destilliertes Wasser leitet praktisch nicht.",
                    "Mischt man zwei Lösungen und entsteht dabei ein schwerlösliches Salz, fällt es als Niederschlag aus — eine Fällungsreaktion."],
                   "Löslichkeit sagt, wie viel. Leitfähigkeit sagt, wie viele Ionen beweglich sind.",
                   visual={"type": "diagramm", "titel": "Löslichkeit in Wasser",
                           "xtitel": "Temperatur in °C", "ytitel": "g je 100 g Wasser",
                           "punkte": [[0, 35.7], [20, 36], [40, 36.6], [60, 37.3], [80, 38.4], [100, 39.8]],
                           "ymin": 0, "ymax": 45,
                           "alt": "Löslichkeitskurve von Kochsalz — sie steigt nur schwach."}),
        "C": karte("Warum sich manches nicht löst",
                   "Ob sich ein Salz löst, entscheidet ein Vergleich zweier Energien. Damit lässt sich auch erklären, warum manche Salze praktisch unlöslich sind.",
                   ["Zum Lösen muss das Gitter auseinandergenommen werden — das kostet Gitterenergie.",
                    "Beim Umhüllen der Ionen mit Wassermolekülen wird Hydratationsenergie frei.",
                    "Sind beide etwa gleich groß, löst sich das Salz gut. Überwiegt die Gitterenergie deutlich, bleibt es ungelöst.",
                    "Deshalb ist Kochsalz gut löslich, Bariumsulfat dagegen praktisch nicht — und genau das macht es als Röntgenkontrastmittel verwendbar, obwohl Barium-Ionen giftig sind.",
                    "Ob sich die Lösung dabei erwärmt oder abkühlt, hängt davon ab, welche der beiden Energien überwiegt."],
                   "Gitterenergie gegen Hydratationsenergie — ihr Verhältnis entscheidet über die Löslichkeit.",
                   visual=anim("loesen", "C"))
    },
    "formelkarte": {"formeln": ["w = m(Salz) : m(Lösung) · 100 %"],
                    "saetze": ["Löslichkeit: Gramm Salz je 100 g Wasser, temperaturabhängig.",
                               "Gesättigt: Es löst sich nichts mehr, der Rest bleibt liegen.",
                               "Nur bewegliche Ionen leiten den Strom.",
                               "Langsames Abkühlen ergibt große Kristalle.",
                               "Gitterenergie gegen Hydratationsenergie entscheidet über die Löslichkeit."]},
    "tasks": [
        aufgabe("SZ04-A1-001", "A", 1, "numeric",
                "In 100 g Wasser lösen sich 36 g Kochsalz. Du gibst 50 g hinein. Wie viel bleibt liegen?",
                answer=14, unit_label="g", tolerance=0,
                hints=["Es lösen sich nur 36 g.", "50 − 36.", "14 g."],
                solution="50 g − 36 g = 14 g bleiben als Bodensatz liegen.",
                misconceptions=[fv("saettigung_ignoriert", 0,
                                   "Über der Löslichkeitsgrenze löst sich nichts mehr — der Rest bleibt liegen.")],
                tags=["loeslichkeit"], spiral=["W-LOES"]),
        aufgabe("SZ04-A2-002", "A", 2, "choice",
                "Was bedeutet „gesättigte Lösung“?",
                options=["Es löst sich kein weiteres Salz mehr.", "Die Lösung ist sehr warm.", "Die Lösung ist trüb."],
                answer=0,
                hints=["Was passiert, wenn du noch mehr Salz zugibst?",
                       "Es bleibt liegen.",
                       "Die Lösung ist gesättigt."],
                solution="In einer gesättigten Lösung ist die Löslichkeitsgrenze erreicht — weiteres Salz bleibt ungelöst.",
                tags=["loeslichkeit"], spiral=["W-LOES"]),
        aufgabe("SZ04-A3-003", "A", 3, "choice",
                "Welche Lösung leitet den elektrischen Strom?",
                options=["Kochsalzlösung", "Zuckerlösung", "destilliertes Wasser"], answer=0,
                hints=["Was muss in der Lösung sein?", "Bewegliche Ionen.", "Zucker liegt als Moleküle vor."],
                solution="Nur die Kochsalzlösung enthält frei bewegliche Ionen. Zucker löst sich als Moleküle, destilliertes Wasser enthält praktisch keine Ionen.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Auch Zucker löst sich gut — aber als Moleküle, nicht als Ionen. Deshalb leitet er nicht.",
                                   "ion_und_atom_verwechselt")],
                tags=["loeslichkeit", "leitfaehigkeit"], spiral=["W-LOES"]),
        aufgabe("SZ04-A4-004", "A", 4, "choice",
                "Eine heiße gesättigte Lösung kühlt langsam ab. Was passiert?",
                options=["Es bilden sich Kristalle.", "Die Lösung wird trüb und bleibt so.", "Nichts."],
                answer=0,
                hints=["Bei Kälte löst sich weniger.",
                       "Was passiert mit dem Überschuss?",
                       "Er kristallisiert aus."],
                solution="Beim Abkühlen sinkt die Löslichkeit. Das überschüssige Salz kristallisiert aus — langsam abgekühlt entstehen große Kristalle.",
                tags=["loeslichkeit", "kristalle"], spiral=["W-LOES"]),
        aufgabe("SZ04-B1-005", "B", 1, "numeric",
                "In 100 g Wasser lösen sich 36 g Kochsalz. Wie viel löst sich in 350 g Wasser?",
                answer=126, unit_label="g", tolerance=1,
                hints=["Dreisatz.", "36 g je 100 g.", "350 : 100 · 36."],
                solution="350 g : 100 · 36 g = 126 g",
                misconceptions=[fv("anteil_umgedreht", 10.3,
                                   "Mehr Wasser löst mehr Salz — hier wird multipliziert, nicht geteilt.")],
                tags=["loeslichkeit", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ04-B2-006", "B", 2, "choice",
                "Warum leitet eine konzentrierte Salzlösung besser als eine verdünnte?",
                options=["Sie enthält mehr bewegliche Ionen je Volumen.",
                         "Sie ist dickflüssiger.", "Sie ist wärmer."],
                answer=0,
                hints=["Was transportiert die Ladung?", "Die Ionen.", "Mehr Ionen, mehr Ladungstransport."],
                solution="Die Leitfähigkeit hängt an der Zahl der beweglichen Ionen je Volumen. Je konzentrierter die Lösung, desto besser leitet sie.",
                tags=["loeslichkeit", "leitfaehigkeit", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ04-B2-007", "B", 2, "numeric",
                "Eine gesättigte Lösung enthält 36 g Salz in 100 g Wasser. Wie viel Prozent Salz enthält sie?",
                answer=26.5, unit_label="%", tolerance=0.3,
                hints=["Das Ganze ist Salz plus Wasser.", "36 + 100 = 136 g.", "36 : 136."],
                solution="36 g : 136 g = 0,2647 → 26,5 %",
                misconceptions=[fv("loesungsmittel_als_ganzes", 36,
                                   "Du hast durch 100 g geteilt. Zur Lösung gehört auch das gelöste Salz.")],
                tags=["loeslichkeit", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ04-B3-008", "B", 3, "choice",
                "Wie züchtet man einen möglichst großen Kristall?",
                options=["Eine gesättigte Lösung sehr langsam abkühlen oder verdunsten lassen.",
                         "Die Lösung schnell in Eis stellen.",
                         "Die Lösung kräftig rühren."],
                answer=0,
                hints=["Was passiert bei schnellem Abkühlen?",
                       "Viele kleine Kristalle entstehen gleichzeitig.",
                       "Langsam heißt: wenige, große."],
                solution="Schnelles Abkühlen erzeugt viele Kristallisationskeime und damit viele kleine Kristalle. Langsames Abkühlen oder Verdunsten lässt wenige Keime langsam wachsen — daraus werden große Kristalle.",
                tags=["loeslichkeit", "kristalle", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ04-B3-009", "B", 3, "choice",
                "Beim Mischen zweier klarer Lösungen entsteht ein weißer Feststoff. Wie heißt so eine Reaktion?",
                options=["Fällungsreaktion", "Neutralisation", "Elektrolyse"], answer=0,
                hints=["Etwas fällt aus der Lösung heraus.",
                       "Der Name sagt es.",
                       "Fällungsreaktion."],
                solution="Entsteht beim Mischen ein schwerlösliches Salz, fällt es als Niederschlag aus. Das nennt man Fällungsreaktion — sie dient auch dem Nachweis von Ionen.",
                tags=["loeslichkeit", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ04-B4-010", "B", 4, "multi",
                "Von einem Salz lösen sich bei 20 °C 20 g, bei 80 °C 60 g je 100 g Wasser. Eine bei 80 °C gesättigte Lösung mit 200 g Wasser wird auf 20 °C abgekühlt.",
                fields=[
                    {"label": "gelöste Masse bei 80 °C", "answer": 120, "unit_label": "g", "tolerance": 1},
                    {"label": "gelöste Masse bei 20 °C", "answer": 40, "unit_label": "g", "tolerance": 1},
                    {"label": "auskristallisierte Masse", "answer": 80, "unit_label": "g", "tolerance": 1}
                ],
                hints=["Bei 80 °C: 200 : 100 · 60.",
                       "Bei 20 °C: 200 : 100 · 20.",
                       "Die Differenz kristallisiert aus."],
                solution="80 °C: 2 · 60 g = 120 g\n20 °C: 2 · 20 g = 40 g\nauskristallisiert: 120 − 40 = 80 g",
                tags=["loeslichkeit", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ04-C2-011", "C", 2, "choice",
                "Warum kühlt sich Wasser beim Lösen mancher Salze ab?",
                options=["Die aufzuwendende Gitterenergie ist größer als die frei werdende Hydratationsenergie.",
                         "Salz ist immer kalt.",
                         "Weil das Salz das Wasser verdrängt."],
                answer=0,
                hints=["Beim Lösen laufen zwei Vorgänge ab.",
                       "Einer kostet Energie, einer liefert welche.",
                       "Überwiegt der erste, wird es kalt."],
                solution="Das Auseinandernehmen des Gitters kostet Energie, das Umhüllen der Ionen liefert welche. Überwiegt der erste Anteil, wird die Energie der Umgebung entnommen — die Lösung kühlt ab.",
                tags=["loeslichkeit", "energie", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ04-C3-012", "C", 3, "choice",
                "Bariumsulfat ist praktisch unlöslich, obwohl Barium-Ionen giftig sind. Warum kann es trotzdem als Röntgenkontrastmittel geschluckt werden?",
                options=["Es geht nicht in Lösung; die Barium-Ionen werden nicht frei und passieren den Körper unverändert.",
                         "Barium ist im Sulfat ungiftig geworden.",
                         "Die Menge ist zu klein für eine Wirkung."],
                answer=0,
                hints=["Wirkt ein Ion, das nie in Lösung geht?",
                       "Nein — es muss gelöst sein, um aufgenommen zu werden.",
                       "Die Gitterenergie ist hier zu groß."],
                solution="Bei Bariumsulfat überwiegt die Gitterenergie so stark, dass es sich praktisch nicht löst. Die Ionen werden nicht frei und können nicht aufgenommen werden. Lösliche Bariumsalze sind dagegen hochgiftig — der Unterschied liegt allein in der Löslichkeit.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Das Barium-Ion bleibt giftig. Es wird nur nie freigesetzt.",
                                   "ion_und_atom_verwechselt")],
                tags=["loeslichkeit", "bewerten", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ04-C3-013", "C", 3, "multi",
                "300 g einer bei 60 °C gesättigten Lösung enthalten 80 g Salz. Beim Abkühlen auf 20 °C fallen 35 g aus.",
                fields=[
                    {"label": "Wassermasse in der Lösung", "answer": 220, "unit_label": "g", "tolerance": 1},
                    {"label": "gelöste Salzmasse bei 20 °C", "answer": 45, "unit_label": "g", "tolerance": 1},
                    {"label": "Löslichkeit bei 20 °C je 100 g Wasser", "answer": 20.5, "unit_label": "g", "tolerance": 0.5}
                ],
                hints=["Wasser = 300 g − 80 g.",
                       "Gelöst bleiben 80 − 35 = 45 g.",
                       "45 g auf 220 g Wasser → auf 100 g umrechnen."],
                solution="Wasser: 300 − 80 = 220 g\ngelöst bei 20 °C: 80 − 35 = 45 g\nje 100 g Wasser: 45 : 220 · 100 = 20,5 g",
                tags=["loeslichkeit", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ04-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Wenn eine Lösung nicht mehr aufnimmt, ist das Wasser voll.“ Wie bewertest du das Bild?",
                options=["Es trägt nur teilweise — die Grenze hängt von der Temperatur und vom Salz ab, nicht von einem Platzmangel.",
                         "Es ist völlig richtig.",
                         "Es ist völlig falsch, es gibt keine Grenze."],
                answer=0,
                hints=["Ändert sich die Grenze mit der Temperatur?",
                       "Ja, deutlich.",
                       "Ein voller Behälter würde nicht bei Wärme mehr fassen."],
                solution="Das Bild vom vollen Behälter erklärt nicht, warum sich bei 80 °C mehr löst als bei 20 °C und warum verschiedene Salze so verschiedene Grenzen haben. Entscheidend ist das Verhältnis von Gitter- und Hydratationsenergie, nicht der Platz.",
                tags=["loeslichkeit", "bewerten", "msa"], spiral=["W-LOES"])
    ]
})

E.append({
    "unit": "SZ-05",
    "title": "Anwenden & Prüfungstraining Salze",
    "leitidee": "B2",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 8,
    "wortspeicher": ["die Verhältnisformel", "das Ionengitter", "die Leitfähigkeit",
                     "die Flammenfärbung", "der Nachweis", "die Fällungsreaktion"],
    "worterklaerungen": {
        "Flammenfärbung": "Manche Metall-Ionen färben eine Flamme charakteristisch."
    },
    "can_do": {
        "A": "Ich stelle einfache Salzformeln auf und nenne Eigenschaften von Salzen.",
        "B": "Ich verbinde Formel, Gitter und Eigenschaften und werte Nachweise aus.",
        "C": "Ich begründe Eigenschaften der Salze aus dem Gitteraufbau und bewerte Aussagen."
    },
    "lernkarten": {
        "A": karte("Salze auf einen Blick",
                   "Salze bestehen aus Ionen.",
                   ["Die Ladungen gleichen sich aus.", "Salze sind hart, spröde und hochschmelzend."],
                   "Ladungssumme null — daraus folgt die Formel.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Ionen nachweisen",
                   "Welche Ionen in einer Probe stecken, lässt sich mit einfachen Mitteln zeigen.",
                   ["Flammenfärbung: Natrium gelb, Kalium violett, Calcium ziegelrot, Kupfer grün.",
                    "Fällungsreaktionen: Chlorid-Ionen ergeben mit Silber-Ionen einen weißen Niederschlag, Sulfat-Ionen mit Barium-Ionen einen weißen.",
                    "Leitfähigkeit zeigt, dass überhaupt Ionen vorliegen — welche, sagt sie nicht.",
                    "Wie immer gilt: Ein Nachweis ist nur so viel wert wie seine Eindeutigkeit."],
                   "Flammenfärbung zeigt Metall-Ionen, Fällung zeigt Säurerest-Ionen.",
                   visual=anim("ionengitter", "B")),
        "C": karte("Sauber begründen",
                   "Bei Salzen wird fast immer in derselben Richtung begründet: vom Gitter zur Eigenschaft.",
                   ["Warum spröde? Weil beim Verschieben gleiche Ladungen aufeinandertreffen.",
                    "Warum hochschmelzend? Weil die Anziehung zwischen den Ionen stark ist.",
                    "Warum erst gelöst leitfähig? Weil die Ionen erst dann beweglich sind.",
                    "Jede dieser Antworten beginnt beim Bau und endet bei der beobachtbaren Eigenschaft."],
                   "Vom Aufbau zur Eigenschaft — nie umgekehrt.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["NaCl · MgO · CaCl₂ · Al₂O₃ · Na₂SO₄ · Ca(OH)₂"],
                    "saetze": ["Ladungssumme null — daraus folgt die Verhältnisformel.",
                               "Salze: hart, spröde, hochschmelzend.",
                               "Leitfähig erst gelöst oder geschmolzen.",
                               "Flammenfärbung: Na gelb · K violett · Ca ziegelrot · Cu grün."]},
    "tasks": [
        aufgabe("SZ05-A1-001", "A", 1, "choice",
                "K⁺ und Cl⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["KCl", "K₂Cl", "KCl₂"], answer=0,
                hints=["Beide einfach geladen.", "Je ein Ion.", "KCl."],
                solution="1+ und 1− gleichen sich aus: KCl.",
                tags=["pruefung"], spiral=["W-SYMB"]),
        aufgabe("SZ05-A2-002", "A", 2, "choice",
                "Welche Eigenschaft passt zu Salzen?",
                options=["hoher Schmelzpunkt", "biegsam", "leitet als Feststoff"], answer=0,
                hints=["Salze sind spröde.", "Fest leiten sie nicht.", "Aber sie schmelzen sehr hoch."],
                solution="Salze haben hohe Schmelztemperaturen, sind spröde und leiten erst gelöst oder geschmolzen.",
                tags=["pruefung"], spiral=["W-STOF"]),
        aufgabe("SZ05-A3-003", "A", 3, "numeric",
                "Mg²⁺ und Cl⁻: Wie viele Chlorid-Ionen gehören zu einem Magnesium-Ion?",
                answer=2, tolerance=0,
                hints=["Zwei positive Ladungen.", "Jedes Cl⁻ bringt eine negative.", "Zwei."],
                solution="MgCl₂ — zwei Chlorid-Ionen gleichen die zweifach positive Ladung aus.",
                tags=["pruefung"], spiral=["W-SYMB"]),
        aufgabe("SZ05-A4-004", "A", 4, "choice",
                "Eine Flamme färbt sich gelb. Welches Ion ist vermutlich enthalten?",
                options=["Natrium", "Kalium", "Kupfer"], answer=0,
                hints=["Jedes Metall-Ion färbt anders.", "Gelb gehört zu einem sehr häufigen Ion.", "Natrium."],
                solution="Natrium-Ionen färben die Flamme intensiv gelb. Kalium färbt violett, Kupfer grün.",
                misconceptions=[fv("nachweis_verwechselt", 2,
                                   "Kupfer färbt grün. Gelb ist typisch für Natrium.",
                                   "nachweis_verwechselt")],
                tags=["pruefung", "nachweise"], spiral=["W-SYMB"]),
        aufgabe("SZ05-B1-005", "B", 1, "choice",
                "Al³⁺ und SO₄²⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["Al₂(SO₄)₃", "AlSO₄", "Al₃(SO₄)₂"], answer=0,
                hints=["Kleinstes gemeinsames Vielfaches von 3 und 2 ist 6.",
                       "Zwei Al³⁺ und drei SO₄²⁻.",
                       "Die Klammer ist nötig."],
                solution="2 · 3+ = 6+ und 3 · 2− = 6−: Al₂(SO₄)₃. Die Klammer ist nötig, weil das Sulfat dreimal vorkommt.",
                misconceptions=[fv("ladung_unvollstaendig", 2,
                                   "Über Kreuz: Die 3 vom Aluminium wird zum Index des Sulfats, die 2 vom Sulfat zum Index des Aluminiums.",
                                   "ladung_unvollstaendig")],
                tags=["pruefung", "formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ05-B2-006", "B", 2, "choice",
                "Eine Probe leitet gelöst den Strom und färbt die Flamme gelb. Was folgt daraus?",
                options=["Es liegen Ionen vor, darunter Natrium-Ionen.",
                         "Es ist reines Wasser.", "Es ist Zucker."],
                answer=0,
                hints=["Leitfähigkeit zeigt Ionen.",
                       "Die Flammenfärbung sagt, welches Metall-Ion.",
                       "Gelb heißt Natrium."],
                solution="Leitfähigkeit belegt bewegliche Ionen, die gelbe Flammenfärbung weist Natrium-Ionen nach. Zucker würde nicht leiten.",
                tags=["pruefung", "nachweise", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ05-B2-007", "B", 2, "numeric",
                "In 250 g Wasser lösen sich bei 20 °C höchstens 90 g eines Salzes. Wie viel löst sich in 100 g Wasser?",
                answer=36, unit_label="g", tolerance=1,
                hints=["Dreisatz zurück auf 100 g.", "90 : 250 · 100.", "36 g."],
                solution="90 g : 250 g · 100 g = 36 g je 100 g Wasser.",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ05-B3-008", "B", 3, "choice",
                "Warum zerspringt ein Salzkristall beim Hammerschlag, ein Kupferblech aber nicht?",
                options=["Im Salz treffen nach dem Verschieben gleiche Ladungen aufeinander, im Metall nicht.",
                         "Salz ist weicher als Kupfer.",
                         "Kupfer enthält keine Teilchen."],
                answer=0,
                hints=["Was liegt zwischen den Teilchen im Metall?",
                       "Das Elektronengas.",
                       "Im Salz wechseln sich Ladungen ab."],
                solution="Im Ionengitter zerstört eine Verschiebung die Abfolge der Ladungen — gleiche Ladungen stoßen sich ab, der Kristall springt. Im Metall umgibt das Elektronengas alle Rümpfe gleichmäßig, die Bindung bleibt.",
                tags=["pruefung", "bbr"], spiral=["W-TEIL"]),
        aufgabe("SZ05-B3-009", "B", 3, "choice",
                "Welche Antwort auf „Erkläre, warum Salzlösungen den Strom leiten“ ist vollständig?",
                options=["Beim Lösen werden die Ionen aus dem Gitter gelöst und frei beweglich; bewegliche Ladungsträger leiten den Strom.",
                         "Weil Salz Ionen enthält.",
                         "Weil Wasser den Strom leitet."],
                answer=0,
                hints=["Ionen sind auch im Feststoff vorhanden.",
                       "Was fehlt dort?",
                       "Die Beweglichkeit."],
                solution="Antwort 2 greift zu kurz — Ionen sind auch im Feststoff da, der aber nicht leitet. Entscheidend ist die Beweglichkeit. Reines Wasser leitet praktisch nicht.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Ionen allein genügen nicht. Sie müssen beweglich sein.",
                                   "ion_und_atom_verwechselt")],
                tags=["pruefung", "operatoren", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ05-B4-010", "B", 4, "multi",
                "Ein Salz besteht aus Ca²⁺ und NO₃⁻.",
                fields=[
                    {"label": "Zahl der Nitrat-Ionen", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der Sauerstoffatome in der Formeleinheit", "answer": 6, "tolerance": 0}
                ],
                hints=["Ca²⁺ braucht zwei einfach negative Ionen.",
                       "Ca(NO₃)₂.",
                       "Jedes Nitrat hat drei O-Atome."],
                solution="Ca(NO₃)₂ — zwei Nitrat-Ionen mit je 3 Sauerstoffatomen, zusammen 6.",
                tags=["pruefung", "formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ05-C2-011", "C", 2, "choice",
                "Welcher Nachweis ist für Chlorid-Ionen geeignet?",
                options=["Zugabe einer Silbernitratlösung — es entsteht ein weißer Niederschlag.",
                         "Die Flammenfärbung.",
                         "Die Leitfähigkeitsmessung."],
                answer=0,
                hints=["Flammenfärbung zeigt Metall-Ionen.",
                       "Leitfähigkeit zeigt nur, dass Ionen da sind.",
                       "Für Chlorid braucht es eine Fällung."],
                solution="Silber-Ionen bilden mit Chlorid-Ionen schwerlösliches Silberchlorid — ein weißer Niederschlag. Flammenfärbung und Leitfähigkeit sagen nichts über das Säurerest-Ion.",
                misconceptions=[fv("nachweis_verwechselt", 2,
                                   "Leitfähigkeit belegt nur, dass Ionen vorliegen — nicht welche.",
                                   "nachweis_verwechselt")],
                tags=["pruefung", "nachweise", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ05-C3-012", "C", 3, "multi",
                "Eine gesättigte Lösung bei 80 °C enthält 150 g Salz in 250 g Wasser. Beim Abkühlen auf 20 °C lösen sich nur noch 36 g je 100 g Wasser.",
                fields=[
                    {"label": "gelöste Masse bei 20 °C", "answer": 90, "unit_label": "g", "tolerance": 2},
                    {"label": "auskristallisierte Masse", "answer": 60, "unit_label": "g", "tolerance": 2}
                ],
                hints=["250 g Wasser sind 2,5-mal 100 g.",
                       "2,5 · 36 g = 90 g.",
                       "150 − 90 = 60 g."],
                solution="bei 20 °C gelöst: 2,5 · 36 g = 90 g\nauskristallisiert: 150 g − 90 g = 60 g",
                tags=["pruefung", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("SZ05-C3-013", "C", 3, "choice",
                "Warum ist die Formel NaCl keine Molekülformel?",
                options=["Im Gitter hat jedes Ion sechs gleichberechtigte Nachbarn — es gibt keine abgegrenzte Teilcheneinheit.",
                         "Weil Natrium ein Metall ist.",
                         "Weil die Formel zu kurz ist."],
                answer=0,
                hints=["Wie viele Nachbarn hat jedes Ion?",
                       "Sechs.",
                       "Ein Molekül wäre eine abgegrenzte Einheit."],
                solution="Ein Molekül ist eine abgegrenzte Teilcheneinheit. Im Ionengitter ist jedes Na⁺ von sechs Cl⁻ umgeben — kein Partner ist ausgezeichnet. NaCl nennt deshalb nur das Zahlenverhältnis.",
                tags=["pruefung", "msa"], spiral=["W-SYMB"]),
        aufgabe("SZ05-C4-014", "C", 4, "choice",
                "Ein Schüler behauptet: „Alle Salze lösen sich in Wasser.“ Wie bewertest du das?",
                options=["Falsch — die Löslichkeit hängt vom Verhältnis der Gitter- zur Hydratationsenergie ab; Bariumsulfat etwa ist praktisch unlöslich.",
                         "Richtig — alle Salze lösen sich.",
                         "Falsch — kein Salz löst sich vollständig."],
                answer=0,
                hints=["Kennst du ein Gegenbeispiel?",
                       "Bariumsulfat, Silberchlorid, Calciumcarbonat.",
                       "Ein Gegenbeispiel genügt."],
                solution="Ein Gegenbeispiel widerlegt die Behauptung: Bariumsulfat, Silberchlorid und Calciumcarbonat sind praktisch unlöslich. Genau darauf beruhen die Fällungsnachweise.",
                misconceptions=[fv("verallgemeinert", 1,
                                   "Für eine Widerlegung genügt ein Gegenbeispiel — Fällungsreaktionen liefern viele.")],
                tags=["pruefung", "bewerten", "msa"], spiral=["W-LOES"])
    ]
})

if __name__ == "__main__":
    schreiben("sz", E, "Bereich SZ · Einheiten 4 und 5")
