# -*- coding: utf-8 -*-
"""Bereich KW · Kohlenwasserstoffe — KW-04 bis KW-06."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "KW-04",
    "title": "Isomerie und Nomenklatur",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 9,
    "wortspeicher": ["das Isomer", "die Konstitutionsisomerie", "verzweigt", "unverzweigt",
                     "die Hauptkette", "die Seitenkette", "die Nomenklatur"],
    "worterklaerungen": {
        "Isomer": "Ein Stoff mit gleicher Summenformel, aber anderem Bau.",
        "Hauptkette": "Die längste zusammenhängende Kette aus Kohlenstoffatomen.",
        "Seitenkette": "Ein Zweig, der von der Hauptkette abgeht."
    },
    "can_do": {
        "A": "Ich erkenne, dass zwei Moleküle mit gleicher Summenformel verschieden sein können.",
        "B": "Ich zeichne Isomere und benenne verzweigte Alkane nach den Regeln.",
        "C": "Ich begründe unterschiedliche Eigenschaften von Isomeren mit ihrem Bau."
    },
    "lernkarten": {
        "A": karte("Gleiche Formel, anderer Bau",
                   "Zwei Stoffe können dieselbe Summenformel haben.",
                   ["Trotzdem sind sie verschieden.", "Der Bau ist anders."],
                   "Gleiche Summenformel heißt nicht gleicher Stoff.",
                   visual=anim("isomerie", "A"),
                   beispiel={"titel": "C₄H₁₀", "aufgabe": "Zwei Möglichkeiten.",
                             "schritte": ["Eine gerade Kette aus vier C-Atomen.",
                                          "Oder eine Kette aus drei mit einem Zweig."],
                             "ergebnis": "Butan und Isobutan."}),
        "B": karte("Isomere benennen",
                   "Verzweigte Alkane bekommen einen Namen nach festen Regeln. Sie sind international vereinbart, damit jede Formel eindeutig benannt werden kann.",
                   ["1. Die längste Kette suchen — sie ist die Hauptkette und bestimmt den Stammnamen.",
                    "2. Die Kohlenstoffatome so nummerieren, dass die Seitenketten möglichst kleine Zahlen bekommen.",
                    "3. Die Seitenketten benennen: CH₃ ist eine Methyl-Gruppe, C₂H₅ eine Ethyl-Gruppe.",
                    "4. Zusammensetzen: 2-Methylpropan. Bei mehreren gleichen Gruppen: di, tri, tetra.",
                    "Zahl der Isomere: C₄ hat 2, C₅ hat 3, C₆ hat 5, C₇ hat 9 — die Zahl wächst rasch."],
                   "Längste Kette suchen, günstig nummerieren, Seitenketten benennen.",
                   visual=anim("isomerie", "B")),
        "C": karte("Warum Isomere sich unterscheiden",
                   "Isomere haben dieselben Atome — und trotzdem verschiedene Siedetemperaturen, Dichten und teils andere Reaktionen. Das liegt allein an der Gestalt.",
                   ["Ein unverzweigtes Molekül ist langgestreckt und kann sich mit vielen Nachbarn berühren. Die van-der-Waals-Kräfte sind entsprechend stark.",
                    "Ein verzweigtes Molekül ist kompakter, fast kugelig. Es berührt seine Nachbarn auf kleinerer Fläche — die Anziehung ist schwächer.",
                    "Deshalb siedet Butan bei −0,5 °C, Isobutan schon bei −11,7 °C. Gleiche Summenformel, verschiedene Siedetemperatur.",
                    "Bei Kraftstoffen ist das technisch bedeutsam: Verzweigte Alkane haben eine höhere Klopffestigkeit — daher die Oktanzahl."],
                   "Gestreckt heißt mehr Kontaktfläche und höhere Siedetemperatur.",
                   visual=anim("isomerie", "C"))
    },
    "formelkarte": {"formeln": ["C₄H₁₀: Butan und 2-Methylpropan",
                               "Zahl der Isomere: C₄ 2 · C₅ 3 · C₆ 5 · C₇ 9"],
                    "saetze": ["Isomere: gleiche Summenformel, anderer Bau.",
                               "Hauptkette = längste Kette. Sie bestimmt den Stammnamen.",
                               "So nummerieren, dass die Seitenketten kleine Zahlen bekommen.",
                               "Verzweigte Moleküle sieden tiefer als unverzweigte."]},
    "tasks": [
        aufgabe("KW04-A1-001", "A", 1, "choice",
                "Zwei Stoffe haben dieselbe Summenformel. Sind sie derselbe Stoff?",
                options=["Nein, der Bau kann verschieden sein.", "Ja, immer.", "Nur bei kurzen Ketten."],
                answer=0, visual=anim("isomerie", "A"),
                hints=["Denk an Butan und Isobutan.",
                       "Beide haben C₄H₁₀.",
                       "Trotzdem sind es zwei Stoffe."],
                solution="Gleiche Summenformel heißt nicht gleicher Stoff. Bei verschiedenem Bau spricht man von Isomeren.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 1,
                                   "Butan und Isobutan haben beide C₄H₁₀ und sind trotzdem verschieden.",
                                   "isomer_als_gleicher_stoff")],
                tags=["isomerie"], spiral=["W-ORG"]),
        aufgabe("KW04-A2-002", "A", 2, "numeric",
                "Wie viele Isomere hat das Alkan mit 4 C-Atomen?",
                answer=2, tolerance=0,
                hints=["Eine gerade Kette und eine verzweigte.", "Mehr Möglichkeiten gibt es nicht.", "2."],
                solution="C₄H₁₀ hat zwei Isomere: Butan (gerade) und 2-Methylpropan (verzweigt).",
                tags=["isomerie"], spiral=["W-ORG"]),
        aufgabe("KW04-A3-003", "A", 3, "choice",
                "Was ist eine Hauptkette?",
                options=["Die längste Kette aus C-Atomen.", "Die kürzeste Kette.", "Eine Seitenkette."],
                answer=0,
                hints=["Sie bestimmt den Namen.", "Es ist die längste.", "Die Hauptkette."],
                solution="Die Hauptkette ist die längste zusammenhängende Kohlenstoffkette. Sie bestimmt den Stammnamen.",
                tags=["isomerie", "namen"], spiral=["W-ORG"]),
        aufgabe("KW04-A4-004", "A", 4, "numeric",
                "Wie viele Isomere hat das Alkan mit 5 C-Atomen?",
                answer=3, tolerance=0,
                hints=["Gerade Kette, einfach verzweigt, doppelt verzweigt.", "Drei Möglichkeiten.", "3."],
                solution="C₅H₁₂ hat drei Isomere: Pentan, 2-Methylbutan und 2,2-Dimethylpropan.",
                tags=["isomerie"], spiral=["W-ORG"]),
        aufgabe("KW04-B1-005", "B", 1, "choice",
                "Wie heißt die Seitenkette CH₃?",
                options=["Methyl-Gruppe", "Ethyl-Gruppe", "Propyl-Gruppe"], answer=0,
                hints=["Ein C-Atom heißt Meth.",
                       "Als Seitenkette endet es auf -yl.",
                       "Methyl."],
                solution="Eine Seitenkette aus einem C-Atom heißt Methyl-Gruppe. Zwei C-Atome ergeben eine Ethyl-Gruppe.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Ethyl hat zwei C-Atome. Ein C-Atom heißt Methyl.",
                                   "nomenklatur_falsch")],
                tags=["isomerie", "namen", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW04-B2-006", "B", 2, "choice",
                "Ein Molekül hat eine Hauptkette aus drei C-Atomen mit einer Methyl-Gruppe am mittleren Atom. Wie heißt es?",
                options=["2-Methylpropan", "1-Methylpropan", "Methylbutan"], answer=0,
                hints=["Die Hauptkette hat drei C-Atome: Propan.",
                       "Die Seitenkette sitzt am zweiten Atom.",
                       "2-Methylpropan."],
                solution="Hauptkette Propan, Methyl-Gruppe am zweiten C-Atom: 2-Methylpropan. Es ist dasselbe wie Isobutan.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Am ersten C-Atom wäre die Gruppe Teil der Hauptkette — dann wäre es Butan.",
                                   "nomenklatur_falsch")],
                tags=["isomerie", "namen", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW04-B2-007", "B", 2, "choice",
                "Warum wird so nummeriert, dass die Seitenketten kleine Zahlen bekommen?",
                options=["Damit jeder Stoff genau einen eindeutigen Namen hat.",
                         "Damit der Name kürzer wird.",
                         "Das ist willkürlich."],
                answer=0,
                hints=["Von welcher Seite könnte man sonst zählen?",
                       "Von beiden.",
                       "Dann gäbe es zwei Namen für einen Stoff."],
                solution="Ohne diese Regel könnte man von beiden Seiten zählen und käme zu zwei Namen für denselben Stoff. Die Nomenklatur soll aber eindeutig sein — deshalb die Festlegung auf die kleinstmöglichen Zahlen.",
                tags=["isomerie", "namen", "bbr"]),
        aufgabe("KW04-B3-008", "B", 3, "numeric",
                "Wie viele Isomere hat das Alkan mit 6 C-Atomen?",
                answer=5, tolerance=0,
                hints=["Mehr als bei fünf C-Atomen.", "Die Zahl wächst rasch.", "5."],
                solution="C₆H₁₄ hat fünf Isomere. Bei sieben C-Atomen sind es schon neun — die Zahl wächst sehr schnell.",
                tags=["isomerie", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW04-B3-009", "B", 3, "choice",
                "Butan siedet bei −0,5 °C, Isobutan bei −11,7 °C. Wie erklärst du den Unterschied?",
                options=["Das verzweigte Molekül ist kompakter und hat weniger Kontaktfläche zu den Nachbarn.",
                         "Isobutan ist leichter.",
                         "Isobutan hat weniger H-Atome."],
                answer=0,
                visual=anim("isomerie", "C"),
                hints=["Beide haben dieselbe Summenformel.",
                       "Verschieden ist die Gestalt.",
                       "Kompakt heißt weniger Berührungsfläche."],
                solution="Beide haben C₄H₁₀ und dieselbe Masse. Das verzweigte Isobutan ist aber kompakter und berührt seine Nachbarn auf kleinerer Fläche — die van-der-Waals-Kräfte sind schwächer, es siedet früher.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 2,
                                   "Isomere haben dieselbe Summenformel und damit gleich viele H-Atome.",
                                   "isomer_als_gleicher_stoff")],
                tags=["isomerie", "msa"], spiral=["W-ORG"]),
        aufgabe("KW04-B4-010", "B", 4, "choice",
                "Warum sind Butan und Isobutan verschiedene Stoffe, obwohl sie dieselben Atome enthalten?",
                options=["Die Atome sind anders miteinander verknüpft; der Bau bestimmt die Eigenschaften.",
                         "Sie enthalten verschiedene Atome.",
                         "Sie sind gar nicht verschieden."],
                answer=0,
                hints=["Was unterscheidet sie?",
                       "Die Anordnung.",
                       "Und die bestimmt die Eigenschaften."],
                solution="Beide bestehen aus vier C- und zehn H-Atomen. Verschieden ist allein die Verknüpfung — und daraus folgen verschiedene Siedetemperaturen und Dichten. Der Bau bestimmt die Eigenschaften.",
                tags=["isomerie", "msa"], spiral=["W-ORG"]),
        aufgabe("KW04-C2-011", "C", 2, "choice",
                "Warum werden verzweigte Alkane als Kraftstoffbestandteile bevorzugt?",
                options=["Sie sind klopffester — sie entzünden sich im Motor nicht vorzeitig.",
                         "Sie sind billiger.",
                         "Sie enthalten mehr Energie."],
                answer=0,
                hints=["Wonach wird Benzin bewertet?",
                       "Nach der Oktanzahl.",
                       "Sie misst die Klopffestigkeit."],
                solution="Verzweigte Alkane entzünden sich unter Druck weniger leicht von selbst. Diese Klopffestigkeit wird als Oktanzahl angegeben — der Bezugsstoff ist das stark verzweigte Isooctan. Der Energiegehalt ist praktisch gleich.",
                tags=["isomerie", "anwenden", "msa"]),
        aufgabe("KW04-C3-012", "C", 3, "choice",
                "Warum wächst die Zahl der Isomere mit der Kettenlänge so schnell?",
                options=["Mit jedem C-Atom kommen mehr Möglichkeiten hinzu, Seitenketten anzuordnen.",
                         "Weil die Moleküle schwerer werden.",
                         "Weil mehr Wasserstoff dazukommt."],
                answer=0,
                hints=["Wie viele Stellen gibt es für einen Zweig bei 4 C-Atomen?",
                       "Wenige.",
                       "Bei 10 C-Atomen sehr viele."],
                solution="Jedes zusätzliche C-Atom bietet neue Positionen für Verzweigungen und neue Längen für Seitenketten. Bei C₁₀ gibt es bereits 75 Isomere, bei C₂₀ über 300 000.",
                tags=["isomerie", "msa"], spiral=["W-ORG"]),
        aufgabe("KW04-C3-013", "C", 3, "choice",
                "Ein Molekül hat eine Hauptkette aus vier C-Atomen mit je einer Methyl-Gruppe am zweiten und dritten Atom. Wie heißt es?",
                options=["2,3-Dimethylbutan", "2-Methylbutan", "Dimethylpropan"], answer=0,
                hints=["Hauptkette mit vier C-Atomen: Butan.",
                       "Zwei Methyl-Gruppen: Dimethyl.",
                       "An den Positionen 2 und 3."],
                solution="Hauptkette Butan, zwei Methyl-Gruppen an Position 2 und 3: 2,3-Dimethylbutan. Beide Positionen werden genannt, auch wenn sie gleich sind.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Bei zwei Seitenketten müssen beide Positionen genannt werden.",
                                   "nomenklatur_falsch")],
                tags=["isomerie", "namen", "msa"], spiral=["W-ORG"]),
        aufgabe("KW04-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Isomere haben dieselbe molare Masse, also auch dieselbe Siedetemperatur.“ Wie bewertest du das?",
                options=["Falsch — die Siedetemperatur hängt auch von der Molekülgestalt ab, nicht nur von der Masse.",
                         "Richtig.",
                         "Falsch — Isomere haben verschiedene molare Massen."],
                answer=0,
                hints=["Butan und Isobutan haben dieselbe Masse.",
                       "Trotzdem sieden sie 11 °C auseinander.",
                       "Also zählt noch etwas anderes."],
                solution="Die molare Masse ist identisch — die Siedetemperaturen unterscheiden sich trotzdem um über 11 °C. Entscheidend ist zusätzlich die Kontaktfläche zwischen den Molekülen, und die hängt an der Gestalt.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 1,
                                   "Gleiche Masse bedeutet nicht gleiche Eigenschaften. Die Gestalt zählt mit.",
                                   "isomer_als_gleicher_stoff")],
                tags=["isomerie", "bewerten", "msa"], spiral=["W-ORG"])
    ]
})

E.append({
    "unit": "KW-05",
    "title": "Siedetemperaturen und van-der-Waals-Kräfte",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K2.4"],
    "klasse": 9,
    "wortspeicher": ["die van-der-Waals-Kraft", "die Siedetemperatur", "der Aggregatzustand",
                     "die Kontaktfläche", "die zwischenmolekulare Kraft"],
    "worterklaerungen": {
        "van-der-Waals-Kraft": "Eine schwache Anziehung zwischen Molekülen.",
        "zwischenmolekulare Kraft": "Eine Kraft zwischen Molekülen — nicht innerhalb eines Moleküls."
    },
    "can_do": {
        "A": "Ich lese Siedetemperaturen aus einer Tabelle ab und erkenne den Trend.",
        "B": "Ich erkläre den Anstieg der Siedetemperaturen mit den van-der-Waals-Kräften.",
        "C": "Ich begründe Aggregatzustände und technische Anwendungen aus dem Trend."
    },
    "lernkarten": {
        "A": karte("Längere Kette, höherer Siedepunkt",
                   "Je länger die Kette, desto höher die Siedetemperatur.",
                   ["Methan siedet bei −162 °C.", "Octan erst bei 126 °C."],
                   "Lange Ketten sieden spät.",
                   visual=anim("siedekurve", "A"),
                   beispiel={"titel": "Bei Zimmertemperatur", "aufgabe": "Welcher Zustand?",
                             "schritte": ["Bis 4 C-Atome: gasförmig.",
                                          "Ab 5 C-Atome: flüssig.",
                                          "Ab etwa 17: fest."],
                             "ergebnis": "Der Zustand folgt der Kettenlänge."}),
        "B": karte("Warum das so ist",
                   "Zwischen unpolaren Molekülen wirken schwache Anziehungskräfte. Ihre Stärke hängt davon ab, wie groß die Berührungsfläche zwischen zwei Molekülen ist.",
                   ["Die van-der-Waals-Kräfte entstehen durch kurzzeitige, zufällige Ladungsverschiebungen in der Elektronenhülle.",
                    "Je größer die Kontaktfläche zweier Moleküle, desto mehr solcher Kräfte wirken gleichzeitig.",
                    "Ein längeres Molekül hat mehr Kontaktfläche — die Anziehung ist stärker, das Sieden braucht mehr Energie.",
                    "Beim Sieden werden nur diese zwischenmolekularen Kräfte überwunden. Die Moleküle selbst bleiben unversehrt."],
                   "Längere Kette → größere Kontaktfläche → stärkere Anziehung → höhere Siedetemperatur.",
                   visual=anim("siedekurve", "B")),
        "C": karte("Was daraus folgt",
                   "Der Trend erklärt nicht nur Zahlen in einer Tabelle, sondern die gesamte Verwendung der Erdölprodukte.",
                   ["Bei Zimmertemperatur sind C₁ bis C₄ gasförmig — Feuerzeuggas und Campinggas.",
                    "C₅ bis etwa C₁₆ sind flüssig — Benzin, Petroleum, Diesel.",
                    "Ab etwa C₁₇ sind sie fest — Paraffin und Wachs.",
                    "Genau dieser Trend macht die fraktionierte Destillation des Erdöls möglich: In einer Kolonne kondensieren die Fraktionen in verschiedenen Höhen, sortiert nach Kettenlänge.",
                    "Verzweigte Isomere sieden tiefer als unverzweigte gleicher Masse — auch das folgt aus der Kontaktfläche."],
                   "Der Siedepunkttrend ordnet die gesamte Erdölverarbeitung.",
                   visual=anim("siedekurve", "C"))
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Siedetemperaturen: Methan −162 · Butan 0 · Pentan 36 · Octan 126 °C.",
                               "C₁ bis C₄ gasförmig · C₅ bis C₁₆ flüssig · ab C₁₇ fest.",
                               "van-der-Waals-Kräfte wachsen mit der Kontaktfläche.",
                               "Beim Sieden bleiben die Moleküle unversehrt."]},
    "tasks": [
        aufgabe("KW05-A1-001", "A", 1, "choice",
                "Was passiert mit der Siedetemperatur, wenn die Kette länger wird?",
                options=["Sie steigt.", "Sie sinkt.", "Sie bleibt gleich."], answer=0,
                visual=anim("siedekurve", "A"),
                hints=["Sieh dir die Kurve an.", "Sie steigt von links nach rechts.", "Sie steigt."],
                solution="Je länger die Kette, desto höher die Siedetemperatur.",
                tags=["siedepunkt"], spiral=["W-ORG"]),
        aufgabe("KW05-A2-002", "A", 2, "choice",
                "Methan siedet bei −162 °C. In welchem Zustand ist es bei 20 °C?",
                options=["gasförmig", "flüssig", "fest"], answer=0,
                hints=["Liegt 20 °C über oder unter −162 °C?",
                       "Weit darüber.",
                       "Über dem Siedepunkt ist ein Stoff gasförmig."],
                solution="20 °C liegt weit über der Siedetemperatur von −162 °C. Methan ist bei Zimmertemperatur gasförmig.",
                tags=["siedepunkt"], spiral=["W-STOF"]),
        aufgabe("KW05-A3-003", "A", 3, "choice",
                "Ab wie vielen C-Atomen sind Alkane bei Zimmertemperatur flüssig?",
                options=["ab 5", "ab 2", "ab 10"], answer=0,
                visual=anim("siedekurve", "A"),
                hints=["Butan mit 4 C-Atomen ist noch gasförmig.",
                       "Pentan mit 5 ist flüssig.",
                       "Ab 5."],
                solution="Bis vier C-Atome sind die Alkane gasförmig, ab fünf flüssig.",
                tags=["siedepunkt"], spiral=["W-ORG"]),
        aufgabe("KW05-A4-004", "A", 4, "numeric",
                "Pentan siedet bei 36 °C, Hexan bei 69 °C. Wie groß ist der Unterschied?",
                answer=33, unit_label="°C", tolerance=1,
                hints=["69 − 36.", "Die Differenz.", "33 °C."],
                solution="69 °C − 36 °C = 33 °C",
                tags=["siedepunkt", "rechnen"], spiral=["W-EINH"]),
        aufgabe("KW05-B1-005", "B", 1, "choice",
                "Welche Kräfte müssen beim Sieden eines Alkans überwunden werden?",
                options=["die van-der-Waals-Kräfte zwischen den Molekülen",
                         "die Bindungen innerhalb der Moleküle",
                         "die Ionenbindungen"],
                answer=0,
                hints=["Werden die Moleküle beim Sieden zerlegt?",
                       "Nein — sie bleiben ganz.",
                       "Nur die Kräfte zwischen ihnen werden überwunden."],
                solution="Beim Sieden werden nur die zwischenmolekularen van-der-Waals-Kräfte überwunden. Die Moleküle selbst bleiben unversehrt — sonst wäre es eine chemische Reaktion.",
                misconceptions=[fv("bindungsart_verwechselt", 1,
                                   "Die Bindungen im Molekül bleiben erhalten. Sieden ist eine Zustandsänderung.",
                                   "bindungsart_verwechselt")],
                tags=["siedepunkt", "bbr"], spiral=["W-STOF"]),
        aufgabe("KW05-B2-006", "B", 2, "choice",
                "Warum sind die van-der-Waals-Kräfte bei längeren Ketten stärker?",
                options=["Längere Moleküle berühren einander auf größerer Fläche.",
                         "Längere Moleküle sind schwerer.",
                         "Längere Moleküle sind geladen."],
                answer=0,
                visual=anim("siedekurve", "B"),
                hints=["Wovon hängt die Zahl der wirkenden Kräfte ab?",
                       "Von der Berührungsfläche.",
                       "Ein langes Molekül bietet mehr davon."],
                solution="Die van-der-Waals-Kräfte wirken über die gesamte Berührungsfläche. Ein längeres Molekül bietet mehr davon — die Summe der Anziehung wächst.",
                tags=["siedepunkt", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW05-B2-007", "B", 2, "choice",
                "Warum werden bei der Erdöldestillation verschiedene Fraktionen in verschiedenen Höhen der Kolonne abgezogen?",
                options=["Die Fraktionen kondensieren bei verschiedenen Temperaturen, weil ihre Ketten verschieden lang sind.",
                         "Weil die Kolonne unterschiedlich breit ist.",
                         "Weil die Fraktionen verschieden schwer sind."],
                answer=0,
                hints=["Was unterscheidet die Fraktionen?",
                       "Die Kettenlänge und damit die Siedetemperatur.",
                       "Oben ist es kühler."],
                solution="Kurze Ketten sieden früh und steigen weit nach oben, lange kondensieren schon unten. Weil die Kolonne nach oben kühler wird, sortieren sich die Fraktionen nach Kettenlänge.",
                tags=["siedepunkt", "technik", "bbr"], spiral=["W-STOF"]),
        aufgabe("KW05-B3-008", "B", 3, "multi",
                "Gegeben sind die Siedetemperaturen: Methan −162 °C, Butan 0 °C, Octan 126 °C.",
                fields=[
                    {"label": "Unterschied Methan zu Butan", "answer": 162, "unit_label": "°C", "tolerance": 2},
                    {"label": "Unterschied Butan zu Octan", "answer": 126, "unit_label": "°C", "tolerance": 2}
                ],
                hints=["0 − (−162).",
                       "126 − 0.",
                       "Auf das Vorzeichen achten."],
                solution="0 − (−162) = 162 °C\n126 − 0 = 126 °C\nDer Anstieg wird mit wachsender Kettenlänge flacher.",
                tags=["siedepunkt", "rechnen", "bbr"], spiral=["W-EINH"]),
        aufgabe("KW05-B3-009", "B", 3, "choice",
                "Warum ist Paraffinwachs bei Zimmertemperatur fest?",
                options=["Seine Ketten sind sehr lang; die van-der-Waals-Kräfte sind entsprechend stark.",
                         "Es enthält Metall.",
                         "Es ist gefroren."],
                answer=0,
                hints=["Wie lang sind die Ketten im Paraffin?",
                       "Über 17 C-Atome.",
                       "Entsprechend groß ist die Kontaktfläche."],
                solution="Paraffin besteht aus Alkanen mit mehr als 17 C-Atomen. Die van-der-Waals-Kräfte sind dort so stark, dass der Stoff bei Zimmertemperatur fest ist.",
                tags=["siedepunkt", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW05-B4-010", "B", 4, "choice",
                "Warum sind Alkane trotz starker C–H-Bindungen so leicht flüchtig?",
                options=["Beim Verdampfen werden nur die schwachen Kräfte zwischen den Molekülen überwunden.",
                         "Weil die C–H-Bindung schwach ist.",
                         "Weil Alkane wenig wiegen."],
                answer=0,
                hints=["Was wird beim Verdampfen überwunden?",
                       "Nicht die Bindungen im Molekül.",
                       "Sondern die Kräfte dazwischen."],
                solution="Die Bindungen innerhalb des Moleküls sind stark, spielen beim Verdampfen aber keine Rolle. Überwunden werden nur die schwachen van-der-Waals-Kräfte zwischen den Molekülen.",
                tags=["siedepunkt", "msa"], spiral=["W-STOF"]),
        aufgabe("KW05-C2-011", "C", 2, "choice",
                "Warum siedet Wasser mit M = 18 g/mol bei 100 °C, Butan mit M = 58 g/mol aber schon bei 0 °C?",
                options=["Zwischen Wassermolekülen wirken Wasserstoffbrücken, zwischen Alkanmolekülen nur van-der-Waals-Kräfte.",
                         "Wasser ist schwerer.",
                         "Butan ist ein Gemisch."],
                answer=0,
                hints=["Butan ist deutlich schwerer und siedet trotzdem früher.",
                       "Also liegt es nicht an der Masse.",
                       "Wasser ist ein Dipol."],
                solution="Trotz größerer Masse siedet Butan viel früher. Der Grund: Zwischen Wassermolekülen wirken starke Wasserstoffbrücken, zwischen den unpolaren Alkanmolekülen nur schwache van-der-Waals-Kräfte.",
                tags=["siedepunkt", "msa"], spiral=["W-STOF"]),
        aufgabe("KW05-C3-012", "C", 3, "choice",
                "Warum siedet 2,2-Dimethylpropan (9,5 °C) früher als Pentan (36 °C), obwohl beide C₅H₁₂ sind?",
                options=["Das verzweigte Molekül ist fast kugelig und hat weniger Kontaktfläche.",
                         "Es hat weniger Atome.",
                         "Es ist leichter."],
                answer=0,
                hints=["Beide haben dieselbe Summenformel.",
                       "Verschieden ist nur die Gestalt.",
                       "Kugelig heißt wenig Berührungsfläche."],
                solution="Beide haben C₅H₁₂ und dieselbe Masse. Das dreifach verzweigte Molekül ist nahezu kugelig und berührt seine Nachbarn auf minimaler Fläche — die van-der-Waals-Kräfte sind entsprechend schwach.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 1,
                                   "Isomere haben gleich viele Atome und dieselbe Masse. Verschieden ist die Gestalt.",
                                   "isomer_als_gleicher_stoff")],
                tags=["siedepunkt", "msa"], spiral=["W-ORG"]),
        aufgabe("KW05-C3-013", "C", 3, "choice",
                "Warum werden Flüssiggasflaschen unter Druck gesetzt?",
                options=["Unter Druck verflüssigen sich Propan und Butan schon bei Zimmertemperatur.",
                         "Damit das Gas nicht entweicht.",
                         "Damit es kälter bleibt."],
                answer=0,
                hints=["Bei welchen Temperaturen sieden Propan und Butan?",
                       "Unter 0 °C.",
                       "Druck verschiebt den Siedepunkt nach oben."],
                solution="Propan und Butan sind bei Normaldruck gasförmig. Höherer Druck verschiebt die Siedetemperatur nach oben, sodass sie sich schon bei Zimmertemperatur verflüssigen — dadurch passt viel mehr Stoff in die Flasche.",
                tags=["siedepunkt", "anwenden", "msa"], spiral=["W-STOF"]),
        aufgabe("KW05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Beim Sieden von Benzin brechen die C–C-Bindungen auf.“ Wie bewertest du das?",
                options=["Falsch — beim Sieden bleiben die Moleküle vollständig erhalten; nur die Kräfte zwischen ihnen werden überwunden.",
                         "Richtig.",
                         "Falsch — es brechen nur die C–H-Bindungen."],
                answer=0,
                hints=["Was ist im Dampf enthalten?",
                       "Dieselben Moleküle wie in der Flüssigkeit.",
                       "Sieden ist eine Zustandsänderung."],
                solution="Sieden ist eine Zustandsänderung, keine chemische Reaktion. Im Dampf liegen dieselben Moleküle vor. Erst beim Cracken werden C–C-Bindungen gebrochen — dafür braucht es hohe Temperaturen und Katalysatoren.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 1,
                                   "Sieden ist eine Zustandsänderung. Die Moleküle bleiben ganz.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["siedepunkt", "bewerten", "msa"], spiral=["W-STOF"])
    ]
})

if __name__ == "__main__":
    schreiben("kw", E, "Bereich KW · Einheiten 4 und 5")
