# -*- coding: utf-8 -*-
"""Bereich KW · Kohlenwasserstoffe — KW-06 und KW-07."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "KW-06",
    "title": "Verbrennung von Kohlenwasserstoffen",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K4.1"],
    "klasse": 9,
    "sicherheit": [
        "Verbrennungsversuche mit Kohlenwasserstoffen nur in kleinen Mengen und mit Abzug.",
        "Bei unvollständiger Verbrennung entsteht giftiges Kohlenstoffmonoxid."
    ],
    "wortspeicher": ["die vollständige Verbrennung", "die unvollständige Verbrennung",
                     "das Kohlenstoffmonoxid", "der Ruß", "die Reaktionsgleichung"],
    "worterklaerungen": {
        "vollständige Verbrennung": "Genug Sauerstoff. Es entstehen nur CO₂ und H₂O.",
        "unvollständige Verbrennung": "Zu wenig Sauerstoff. Es entstehen zusätzlich CO und Ruß.",
        "Kohlenstoffmonoxid": "CO. Ein farb- und geruchloses, sehr giftiges Gas."
    },
    "can_do": {
        "A": "Ich nenne die Produkte einer vollständigen Verbrennung.",
        "B": "Ich stelle Verbrennungsgleichungen für Alkane auf und gleiche sie aus.",
        "C": "Ich unterscheide vollständige und unvollständige Verbrennung und beurteile die Gefahren."
    },
    "lernkarten": {
        "A": karte("Was beim Verbrennen entsteht",
                   "Kohlenwasserstoffe verbrennen mit Sauerstoff.",
                   ["Aus dem Kohlenstoff wird Kohlenstoffdioxid.",
                    "Aus dem Wasserstoff wird Wasser."],
                   "Vollständige Verbrennung: nur CO₂ und H₂O.",
                   visual=anim("nachweise", "A"),
                   beispiel={"titel": "Methan verbrennt", "aufgabe": "CH₄ + 2 O₂ → ?",
                             "schritte": ["Ein C-Atom ergibt ein CO₂.",
                                          "Vier H-Atome ergeben zwei H₂O."],
                             "ergebnis": "CH₄ + 2 O₂ → CO₂ + 2 H₂O"}),
        "B": karte("Verbrennungsgleichungen ausgleichen",
                   "Verbrennungsgleichungen folgen immer demselben Muster. Wer die Reihenfolge einhält, kommt zuverlässig zum Ziel.",
                   ["1. Kohlenstoff: Die Zahl der C-Atome ergibt die Zahl der CO₂-Moleküle.",
                    "2. Wasserstoff: Die Zahl der H-Atome geteilt durch 2 ergibt die Zahl der H₂O-Moleküle.",
                    "3. Sauerstoff zuletzt: Alle O-Atome rechts zählen und durch 2 teilen.",
                    "4. Ergibt sich ein Halbes, wird die ganze Gleichung verdoppelt.",
                    "Beispiel: C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O. Rechts: 6 + 4 = 10 O-Atome, also 5 O₂."],
                   "Erst C, dann H, zuletzt O — und bei Halben verdoppeln.",
                   visual=anim("ausgleichen", "B")),
        "C": karte("Wenn der Sauerstoff nicht reicht",
                   "Ob eine Verbrennung vollständig abläuft, entscheidet allein die Sauerstoffzufuhr — und das hat handfeste Folgen.",
                   ["Bei ausreichendem Sauerstoff entstehen nur Kohlenstoffdioxid und Wasser. Die Flamme ist blau und rußt nicht.",
                    "Bei Sauerstoffmangel entstehen zusätzlich Kohlenstoffmonoxid und Ruß. Die Flamme leuchtet gelb.",
                    "Kohlenstoffmonoxid ist farb- und geruchlos und bindet im Blut an den roten Blutfarbstoff — deutlich fester als Sauerstoff. Deshalb sind Gasthermen in geschlossenen Räumen gefährlich.",
                    "Bei unvollständiger Verbrennung bleibt zudem Energie ungenutzt, weil der Brennstoff nicht vollständig umgesetzt wird."],
                   "Sauerstoffmangel erzeugt Kohlenstoffmonoxid — farblos, geruchlos, lebensgefährlich.",
                   visual={"type": "energie", "verlauf": "exotherm",
                           "alt": "Energiediagramm einer exothermen Verbrennung."})
    },
    "formelkarte": {"formeln": ["CH₄ + 2 O₂ → CO₂ + 2 H₂O",
                               "C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O",
                               "2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O"],
                    "saetze": ["Vollständige Verbrennung: nur CO₂ und H₂O.",
                               "Unvollständige Verbrennung: zusätzlich CO und Ruß.",
                               "Reihenfolge beim Ausgleichen: C, dann H, zuletzt O.",
                               "Kohlenstoffmonoxid ist farb- und geruchlos und sehr giftig."]},
    "tasks": [
        aufgabe("KW06-A1-001", "A", 1, "choice",
                "Was entsteht bei der vollständigen Verbrennung von Methan?",
                options=["Kohlenstoffdioxid und Wasser", "nur Wasser", "Kohlenstoffmonoxid"],
                answer=0,
                hints=["Der Kohlenstoff wird zu CO₂.", "Der Wasserstoff zu H₂O.", "Beides."],
                solution="CH₄ + 2 O₂ → CO₂ + 2 H₂O. Bei vollständiger Verbrennung entstehen nur diese beiden Produkte.",
                tags=["verbrennung"], spiral=["K-REAK"]),
        aufgabe("KW06-A2-002", "A", 2, "numeric",
                "Wie viele CO₂-Moleküle entstehen bei der Verbrennung eines Propanmoleküls C₃H₈?",
                answer=3, tolerance=0,
                hints=["Jedes C-Atom ergibt ein CO₂.", "Propan hat drei C-Atome.", "3."],
                solution="Drei C-Atome ergeben drei CO₂-Moleküle.",
                tags=["verbrennung"], spiral=["K-ORG", "K-REAK"]),
        aufgabe("KW06-A3-003", "A", 3, "numeric",
                "Wie viele Wassermoleküle entstehen aus einem Molekül Methan CH₄?",
                answer=2, tolerance=0,
                hints=["Vier H-Atome.", "Je zwei ergeben ein Wassermolekül.", "4 : 2 = 2."],
                solution="Vier H-Atome ergeben zwei Wassermoleküle.",
                misconceptions=[fv("h_nicht_halbiert", 4,
                                   "Zwei H-Atome bilden zusammen ein Wassermolekül — halbiere die H-Zahl.")],
                tags=["verbrennung"], spiral=["K-ORG"]),
        aufgabe("KW06-A4-004", "A", 4, "choice",
                "Woran erkennst du eine unvollständige Verbrennung?",
                options=["Die Flamme ist gelb und rußt.", "Die Flamme ist blau.", "Es entsteht kein Wasser."],
                answer=0,
                hints=["Denk an den Gasbrenner.", "Gelb bedeutet Sauerstoffmangel.", "Sie rußt."],
                solution="Eine gelbe, rußende Flamme zeigt Sauerstoffmangel an — die Verbrennung ist unvollständig.",
                misconceptions=[fv("farben_vertauscht", 1,
                                   "Blau zeigt eine vollständige Verbrennung an.")],
                tags=["verbrennung"], spiral=["K-REAK"]),
        aufgabe("KW06-B1-005", "B", 1, "numeric",
                "C₂H₆ + ? O₂ → 2 CO₂ + 3 H₂O. Welcher Koeffizient fehlt?",
                answer=3.5, tolerance=0.1,
                hints=["Zähle die O-Atome rechts: 2 · 2 + 3.",
                       "Zusammen 7.",
                       "7 : 2 = 3,5."],
                solution="Rechts stehen 4 + 3 = 7 O-Atome. Links liefert jedes O₂ zwei: 7 : 2 = 3,5. Anschließend wird die ganze Gleichung verdoppelt.",
                tags=["verbrennung", "bbr"], spiral=["K-REAK"]),
        aufgabe("KW06-B2-006", "B", 2, "numeric",
                "C₃H₈ + ? O₂ → 3 CO₂ + 4 H₂O. Welcher Koeffizient fehlt?",
                answer=5, tolerance=0,
                hints=["O-Atome rechts: 3 · 2 = 6 plus 4 = 10.",
                       "10 : 2.",
                       "5."],
                solution="Rechts: 6 O-Atome aus CO₂ plus 4 aus H₂O = 10. Also 5 O₂ links.",
                misconceptions=[fv("nur_teil_berechnet", 3,
                                   "Auch die Sauerstoffatome im Wasser gehören zur Bilanz.")],
                tags=["verbrennung", "bbr"], spiral=["K-REAK"]),
        aufgabe("KW06-B2-007", "B", 2, "choice",
                "Warum ist Kohlenstoffmonoxid besonders gefährlich?",
                options=["Es ist farb- und geruchlos und bindet fester an den Blutfarbstoff als Sauerstoff.",
                         "Es riecht sehr streng.",
                         "Es ist brennbar."],
                answer=0,
                hints=["Kann man CO wahrnehmen?",
                       "Nein.",
                       "Und es verdrängt den Sauerstoff im Blut."],
                solution="Kohlenstoffmonoxid ist nicht wahrnehmbar und bindet rund 300-mal fester an den roten Blutfarbstoff als Sauerstoff. Der Sauerstofftransport bricht zusammen, ohne dass man es merkt.",
                misconceptions=[fv("sicherheitsregel_missachtet", 1,
                                   "Gerade die Geruchlosigkeit macht CO so gefährlich.",
                                   "sicherheitsregel_missachtet")],
                tags=["verbrennung", "sicherheit", "bbr"]),
        aufgabe("KW06-B3-008", "B", 3, "multi",
                "Gleiche aus: 2 C₄H₁₀ + ? O₂ → ? CO₂ + ? H₂O",
                fields=[
                    {"label": "Koeffizient vor O₂", "answer": 13, "tolerance": 0},
                    {"label": "Koeffizient vor CO₂", "answer": 8, "tolerance": 0},
                    {"label": "Koeffizient vor H₂O", "answer": 10, "tolerance": 0}
                ],
                hints=["2 · 4 = 8 C-Atome → 8 CO₂.",
                       "2 · 10 = 20 H-Atome → 10 H₂O.",
                       "O-Atome rechts: 16 + 10 = 26 → 13 O₂."],
                solution="2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O\nProbe: C 8 = 8, H 20 = 20, O 26 = 26.",
                tags=["verbrennung", "bbr"], spiral=["K-REAK"]),
        aufgabe("KW06-B3-009", "B", 3, "choice",
                "Warum entsteht bei einer Gastherme in einem geschlossenen Raum Gefahr?",
                options=["Der Sauerstoff wird knapp; es entsteht Kohlenstoffmonoxid.",
                         "Der Raum wird zu warm.",
                         "Das Gas riecht unangenehm."],
                answer=0,
                hints=["Was passiert, wenn der Sauerstoff knapp wird?",
                       "Die Verbrennung wird unvollständig.",
                       "Dann entsteht CO."],
                solution="In einem geschlossenen Raum wird der Sauerstoff verbraucht. Die Verbrennung läuft unvollständig ab, und es entsteht Kohlenstoffmonoxid — unbemerkt, weil es farb- und geruchlos ist.",
                tags=["verbrennung", "sicherheit", "bbr"]),
        aufgabe("KW06-B4-010", "B", 4, "numeric",
                "Wie viele O₂-Moleküle braucht die vollständige Verbrennung eines Moleküls Pentan C₅H₁₂?",
                answer=8, tolerance=0,
                hints=["5 CO₂ ergeben 10 O-Atome.",
                       "6 H₂O ergeben 6 O-Atome.",
                       "16 : 2 = 8."],
                solution="C₅H₁₂ + 8 O₂ → 5 CO₂ + 6 H₂O\nO-Atome rechts: 10 + 6 = 16 → 8 O₂.",
                tags=["verbrennung", "msa"], spiral=["K-REAK", "K-ORG"]),
        aufgabe("KW06-C2-011", "C", 2, "choice",
                "Warum liefert eine unvollständige Verbrennung weniger Energie?",
                options=["Der Brennstoff wird nicht vollständig umgesetzt; im CO und im Ruß steckt noch Energie.",
                         "Weil die Flamme kleiner ist.",
                         "Weil weniger Brennstoff verbraucht wird."],
                answer=0,
                hints=["Was ist im Ruß noch enthalten?",
                       "Unverbrannter Kohlenstoff.",
                       "Der könnte noch Energie liefern."],
                solution="Ruß und Kohlenstoffmonoxid sind nicht zu Ende oxidiert — in ihnen steckt noch chemische Energie. Sie geht ungenutzt verloren, weshalb eine gelbe Flamme auch kühler ist.",
                tags=["verbrennung", "energie", "msa"]),
        aufgabe("KW06-C3-012", "C", 3, "multi",
                "16 g Methan CH₄ (M = 16 g/mol) verbrennen vollständig.",
                fields=[
                    {"label": "Stoffmenge des Methans", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "benötigte Stoffmenge Sauerstoff", "answer": 2, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse des entstehenden CO₂ (M = 44 g/mol)", "answer": 44, "unit_label": "g", "tolerance": 1}
                ],
                hints=["n(CH₄) = 16 : 16 = 1 mol.",
                       "CH₄ + 2 O₂ → CO₂ + 2 H₂O.",
                       "n(CO₂) = 1 mol → m = 44 g."],
                solution="n(CH₄) = 1 mol\nn(O₂) = 2 mol\nn(CO₂) = 1 mol → m = 44 g",
                tags=["verbrennung", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("KW06-C3-013", "C", 3, "choice",
                "Warum entstehen bei jeder Verbrennung eines Kohlenwasserstoffs zwangsläufig CO₂-Emissionen?",
                options=["Der Kohlenstoff des Brennstoffs wird zwangsläufig zu CO₂ oxidiert.",
                         "Weil der Motor nicht gut genug ist.",
                         "Weil zu viel Sauerstoff verwendet wird."],
                answer=0,
                hints=["Wo kommt der Kohlenstoff her?",
                       "Aus dem Brennstoff selbst.",
                       "Er muss irgendwohin."],
                solution="Der Kohlenstoff steckt im Brennstoff und wird bei der Verbrennung zu Kohlenstoffdioxid. Kein Filter und kein besserer Motor kann das ändern — nur weniger Brennstoff oder ein kohlenstofffreier Energieträger.",
                tags=["verbrennung", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("KW06-C4-014", "C", 4, "choice",
                "Ein Schüler behauptet: „Ein Katalysator verhindert die CO₂-Bildung im Auto.“ Wie bewertest du das?",
                options=["Falsch — der Katalysator wandelt CO sogar zu CO₂ um; er verringert es nicht.",
                         "Richtig.",
                         "Falsch — der Katalysator erzeugt gar nichts."],
                answer=0,
                hints=["Was macht der Katalysator mit Kohlenstoffmonoxid?",
                       "Er oxidiert es.",
                       "Dabei entsteht CO₂."],
                solution="Der Katalysator wandelt giftiges Kohlenstoffmonoxid in Kohlenstoffdioxid um — er erhöht dessen Menge sogar. Für die Luftqualität ist er wirksam, für den Klimaschutz nicht.",
                misconceptions=[fv("katalysator_gegen_co2", 1,
                                   "Der Katalysator erzeugt CO₂ aus CO. Er verringert es nicht.")],
                tags=["verbrennung", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

E.append({
    "unit": "KW-07",
    "title": "Anwenden & Prüfungstraining Alkane",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 9,
    "wortspeicher": ["die homologe Reihe", "die Isomerie", "die van-der-Waals-Kraft",
                     "die Verbrennung", "das Erdöl", "die Fraktion"],
    "worterklaerungen": {
        "Fraktion": "Ein Bereich von Kohlenwasserstoffen mit ähnlichen Siedetemperaturen."
    },
    "can_do": {
        "A": "Ich stelle Alkanformeln auf und benenne die Glieder der Reihe.",
        "B": "Ich verbinde Bau, Eigenschaften und Reaktionen der Alkane.",
        "C": "Ich begründe Eigenschaften aus dem Molekülbau und bewerte Anwendungen."
    },
    "lernkarten": {
        "A": karte("Alkane auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["CₙH₂ₙ₊₂ ist die Formel aller Alkane.",
                    "Längere Ketten sieden später."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen.",
                   ["Bau: Kohlenstoff ist vierbindig und bindet an sich selbst — daraus folgen homologe Reihe und Isomerie.",
                    "Eigenschaften: Zwischen den unpolaren Molekülen wirken van-der-Waals-Kräfte, die mit der Kontaktfläche wachsen.",
                    "Reaktion: Alkane sind reaktionsträge, verbrennen aber vollständig zu CO₂ und H₂O."],
                   "Vom Bau zu den Kräften, von den Kräften zu den Eigenschaften.",
                   visual=anim("siedekurve", "B")),
        "C": karte("Erdöl und seine Verarbeitung",
                   "Die Kenntnisse über Alkane erklären unmittelbar, wie aus Erdöl Benzin, Diesel und Kunststoffe werden.",
                   ["Erdöl ist ein Gemisch aus Kohlenwasserstoffen verschiedener Kettenlänge.",
                    "In der fraktionierten Destillation trennen sich die Fraktionen nach Siedetemperatur — also nach Kettenlänge.",
                    "Beim Cracken werden lange Ketten in kürzere gespalten, weil die Nachfrage nach Benzin größer ist als der Anteil in der Rohölfraktion.",
                    "Alkane sind reaktionsträge — deshalb werden sie fast ausschließlich verbrannt oder erst über weitere Schritte in reaktivere Stoffe umgewandelt."],
                   "Erdölverarbeitung ist angewandte Siedepunktlehre.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["CₙH₂ₙ₊₂",
                               "CH₄ + 2 O₂ → CO₂ + 2 H₂O",
                               "C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O"],
                    "saetze": ["Meth 1 · Eth 2 · Prop 3 · But 4 · Pent 5 · Hex 6 · Hept 7 · Oct 8.",
                               "Längere Ketten sieden später — größere Kontaktfläche.",
                               "Isomere: gleiche Summenformel, anderer Bau.",
                               "Ausgleichen: erst C, dann H, zuletzt O."]},
    "tasks": [
        aufgabe("KW07-A1-001", "A", 1, "numeric",
                "Wie viele H-Atome hat ein Alkan mit 6 C-Atomen?",
                answer=14, tolerance=0,
                hints=["2n + 2.", "2 · 6 + 2.", "14."],
                solution="2 · 6 + 2 = 14. Es ist Hexan C₆H₁₄.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("KW07-A2-002", "A", 2, "choice",
                "Wie heißt das Alkan mit fünf C-Atomen?",
                options=["Pentan", "Butan", "Hexan"], answer=0,
                hints=["Pent steht für 5.", "But für 4, Hex für 6.", "Pentan."],
                solution="Fünf C-Atome ergeben Pentan, C₅H₁₂.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("KW07-A3-003", "A", 3, "choice",
                "Was entsteht bei der vollständigen Verbrennung von Butan?",
                options=["CO₂ und H₂O", "nur CO₂", "CO und Ruß"], answer=0,
                hints=["Vollständig heißt: genug Sauerstoff.", "Dann entstehen nur zwei Produkte.", "CO₂ und H₂O."],
                solution="Bei vollständiger Verbrennung entstehen ausschließlich Kohlenstoffdioxid und Wasser.",
                tags=["pruefung"], spiral=["K-REAK"]),
        aufgabe("KW07-A4-004", "A", 4, "choice",
                "Welches Alkan ist bei Zimmertemperatur flüssig?",
                options=["Pentan", "Methan", "Propan"], answer=0,
                visual=anim("siedekurve", "A"),
                hints=["Bis vier C-Atome gasförmig.", "Pentan hat fünf.", "Pentan."],
                solution="Bis vier C-Atome sind Alkane gasförmig, ab fünf flüssig. Pentan siedet bei 36 °C.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("KW07-B1-005", "B", 1, "numeric",
                "C₄H₁₀ + ? O₂ → 4 CO₂ + 5 H₂O. Welcher Koeffizient fehlt? (Halbe zulässig)",
                answer=6.5, tolerance=0.1,
                hints=["O-Atome rechts: 8 + 5 = 13.",
                       "13 : 2.",
                       "6,5."],
                solution="Rechts stehen 13 O-Atome. 13 : 2 = 6,5 O₂. Verdoppelt: 2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O.",
                tags=["pruefung", "bbr"], spiral=["K-REAK"]),
        aufgabe("KW07-B2-006", "B", 2, "choice",
                "Warum siedet Hexan später als Butan?",
                options=["Die längere Kette bietet mehr Kontaktfläche für van-der-Waals-Kräfte.",
                         "Hexan ist polar.",
                         "Hexan hat eine Doppelbindung."],
                answer=0,
                hints=["Beide sind unpolar.",
                       "Verschieden ist die Kettenlänge.",
                       "Längere Kette, mehr Kontaktfläche."],
                solution="Beide Stoffe sind unpolar. Die längere Hexankette bietet mehr Berührungsfläche, die van-der-Waals-Kräfte sind stärker — es siedet später.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("KW07-B2-007", "B", 2, "numeric",
                "Wie viele Isomere hat C₅H₁₂?",
                answer=3, tolerance=0,
                hints=["Gerade Kette, einfach verzweigt, doppelt verzweigt.", "Drei.", "3."],
                solution="C₅H₁₂ hat drei Isomere: Pentan, 2-Methylbutan und 2,2-Dimethylpropan.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("KW07-B3-008", "B", 3, "multi",
                "44 g Propan C₃H₈ (M = 44 g/mol) verbrennen vollständig.",
                fields=[
                    {"label": "Stoffmenge des Propans", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Stoffmenge des entstehenden CO₂", "answer": 3, "unit_label": "mol", "tolerance": 0.1},
                    {"label": "Masse des entstehenden CO₂ (M = 44 g/mol)", "answer": 132, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 44 : 44 = 1 mol.",
                       "C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O.",
                       "3 mol · 44 g/mol."],
                solution="n(C₃H₈) = 1 mol\nn(CO₂) = 3 mol\nm(CO₂) = 132 g — aus 44 g Brennstoff werden 132 g CO₂.",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("KW07-B3-009", "B", 3, "choice",
                "Warum werden lange Kohlenwasserstoffketten gecrackt?",
                options=["Die Nachfrage nach kurzkettigem Benzin ist größer als sein Anteil im Rohöl.",
                         "Lange Ketten sind giftig.",
                         "Kurze Ketten verbrennen unvollständig."],
                answer=0,
                hints=["Welche Fraktion wird am meisten gebraucht?",
                       "Benzin.",
                       "Im Rohöl steckt davon zu wenig."],
                solution="Rohöl enthält weniger kurzkettige Bestandteile, als für Kraftstoffe gebraucht werden. Beim Cracken werden lange Ketten in kürzere gespalten und so an die Nachfrage angepasst.",
                tags=["pruefung", "technik", "msa"]),
        aufgabe("KW07-B4-010", "B", 4, "choice",
                "Welche Antwort auf „Erkläre, warum Octan bei Zimmertemperatur flüssig ist“ ist vollständig?",
                options=["Die acht C-Atome bieten große Kontaktfläche; die van-der-Waals-Kräfte sind so stark, dass der Siedepunkt bei 126 °C liegt.",
                         "Weil es acht C-Atome hat.",
                         "Weil es Benzin ist."],
                answer=0,
                hints=["„Erkläre“ verlangt eine Ursache.",
                       "Die Kettenlänge allein ist nur eine Angabe.",
                       "Die Ursache sind die Anziehungskräfte."],
                solution="Antwort 2 nennt nur eine Tatsache, Antwort 3 gar keine Ursache. Vollständig ist die Kette: Kettenlänge → Kontaktfläche → van-der-Waals-Kräfte → Siedetemperatur.",
                tags=["pruefung", "operatoren", "bbr"], spiral=["K-ORG"]),
        aufgabe("KW07-C2-011", "C", 2, "choice",
                "Warum sind Alkane chemisch reaktionsträge?",
                options=["Die C–C- und C–H-Bindungen sind stabil und unpolar; es gibt keine Angriffspunkte.",
                         "Sie enthalten keinen Sauerstoff.",
                         "Sie sind zu leicht."],
                answer=0,
                hints=["Wo könnte ein Reaktionspartner angreifen?",
                       "Es gibt keine Teilladungen.",
                       "Und die Bindungen sind fest."],
                solution="Die Bindungen im Alkan sind unpolar und stabil. Es gibt keine Teilladungen, an denen ein Partner angreifen könnte. Deshalb der alte Name „Paraffine“ — von parum affinis, „wenig verwandt“.",
                tags=["pruefung", "msa"], spiral=["K-ORG"]),
        aufgabe("KW07-C3-012", "C", 3, "multi",
                "Ein Feuerzeug enthält 8 g Butan C₄H₁₀ (M = 58 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Butans", "answer": 0.138, "unit_label": "mol", "tolerance": 0.01},
                    {"label": "Stoffmenge des entstehenden CO₂", "answer": 0.552, "unit_label": "mol", "tolerance": 0.03},
                    {"label": "Masse des entstehenden CO₂ (M = 44 g/mol)", "answer": 24.3, "unit_label": "g", "tolerance": 1}
                ],
                hints=["n = 8 : 58 = 0,138 mol.",
                       "Je Butan entstehen 4 CO₂.",
                       "m = 0,552 · 44."],
                solution="n(C₄H₁₀) = 8 g : 58 g/mol = 0,138 mol\nn(CO₂) = 4 · 0,138 = 0,552 mol\nm(CO₂) = 24,3 g — dreimal so viel wie der Brennstoff wog.",
                tags=["pruefung", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("KW07-C3-013", "C", 3, "choice",
                "Warum wiegt das entstehende CO₂ mehr als der verbrannte Kraftstoff?",
                options=["Der Sauerstoff aus der Luft wird gebunden und mitgewogen.",
                         "Die Masse nimmt bei jeder Reaktion zu.",
                         "Das ist ein Rechenfehler."],
                answer=0,
                hints=["Woher kommt der Sauerstoff im CO₂?",
                       "Aus der Luft.",
                       "Er zählt zur Produktmasse dazu."],
                solution="Der Kohlenstoff des Kraftstoffs bindet Sauerstoff aus der Luft. Dieser Sauerstoff ist im Produkt enthalten — deshalb ist die CO₂-Masse ein Vielfaches der Kraftstoffmasse. Massenerhaltung gilt trotzdem, wenn man die Luft mitrechnet.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Die Masse nimmt nicht von selbst zu — der gebundene Luftsauerstoff kommt hinzu.",
                                   "masse_verschwindet")],
                tags=["pruefung", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("KW07-C4-014", "C", 4, "choice",
                "Bewerte: „Erdgas ist ein sauberer Brennstoff.“",
                options=["Bezogen auf Ruß und Schwefel ja, bezogen auf CO₂ nur im Vergleich zu Kohle — kohlenstofffrei ist es nicht.",
                         "Richtig, Erdgas verbrennt rückstandsfrei.",
                         "Falsch, Erdgas ist der schmutzigste Brennstoff."],
                answer=0,
                hints=["Was entsteht bei jeder Verbrennung von CH₄?",
                       "CO₂ und Wasser.",
                       "Also ist eine Bewertung nur mit Kriterium möglich."],
                solution="Erdgas verbrennt ohne Ruß und Schwefeldioxid und setzt je Energieeinheit weniger CO₂ frei als Kohle. Kohlenstofffrei ist es nicht — bei jeder Verbrennung entsteht CO₂. „Sauber“ ist ohne Kriterium keine Aussage.",
                tags=["pruefung", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("kw", E, "Bereich KW · Einheiten 6 und 7")
