# -*- coding: utf-8 -*-
"""Bereich ME · Metalle (Klasse 8, Themenfeld 3.6) — ME-01 bis ME-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ME-01",
    "title": "Eigenschaften der Metalle",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K2.4"],
    "klasse": 8,
    "wortspeicher": ["der Metallglanz", "die elektrische Leitfähigkeit", "die Wärmeleitfähigkeit",
                     "verformbar", "die Dichte", "das Schwermetall", "das Leichtmetall"],
    "worterklaerungen": {
        "Metallglanz": "Metalle spiegeln Licht an einer frischen Schnittfläche.",
        "verformbar": "Lässt sich biegen und walzen, ohne zu brechen.",
        "Leichtmetall": "Ein Metall mit einer Dichte unter 5 g/cm³."
    },
    "can_do": {
        "A": "Ich nenne drei Eigenschaften, die alle Metalle gemeinsam haben.",
        "B": "Ich vergleiche Metalle über Dichte, Schmelztemperatur und Leitfähigkeit.",
        "C": "Ich wähle für eine Anwendung ein geeignetes Metall aus und begründe die Wahl."
    },
    "lernkarten": {
        "A": karte("Was alle Metalle können",
                   "Metalle haben gemeinsame Eigenschaften.",
                   ["Sie glänzen und leiten Strom.", "Sie leiten Wärme und lassen sich verformen."],
                   "Glänzen, leiten, verformbar — das haben alle Metalle gemeinsam.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "element",
                           "alt": "Teilchenmodell eines Metalls im festen Zustand."},
                   beispiel={"titel": "Ein Kupferdraht", "aufgabe": "Warum eignet sich Kupfer für Kabel?",
                             "schritte": ["Es leitet den Strom sehr gut.",
                                          "Es lässt sich zu Draht ziehen."],
                             "ergebnis": "Beide Eigenschaften braucht ein Kabel."}),
        "B": karte("Metalle unterscheiden sich",
                   "Die gemeinsamen Eigenschaften sagen noch nicht, welches Metall für welchen Zweck taugt. Dafür braucht es Zahlen.",
                   ["Dichte: Aluminium 2,7 g/cm³ ist ein Leichtmetall, Blei 11,3 g/cm³ ein Schwermetall. Die Grenze liegt bei 5 g/cm³.",
                    "Schmelztemperatur: Quecksilber ist bei Zimmertemperatur flüssig (−39 °C), Wolfram schmilzt erst bei 3422 °C.",
                    "Leitfähigkeit: Silber leitet am besten, dicht gefolgt von Kupfer. Für Kabel wird trotzdem Kupfer genommen — der Preis entscheidet.",
                    "Härte und Verformbarkeit unterscheiden sich ebenfalls stark: Gold lässt sich zu hauchdünner Folie schlagen, Chrom ist sehr hart."],
                   "Alle Metalle leiten — wie gut, entscheidet über den Einsatz.",
                   visual={"type": "diagramm", "titel": "Dichten einiger Metalle",
                           "xtitel": "Metall (1 Al · 2 Fe · 3 Cu · 4 Pb)", "ytitel": "Dichte in g/cm³",
                           "punkte": [[1, 2.7, "Al"], [2, 7.9, "Fe"], [3, 8.9, "Cu"], [4, 11.3, "Pb"]],
                           "linie": False, "ymin": 0, "ymax": 13,
                           "alt": "Dichten von Aluminium, Eisen, Kupfer und Blei im Vergleich."}),
        "C": karte("Das passende Metall wählen",
                   "Für jede Anwendung entscheidet eine andere Eigenschaft. Eine Begründung ohne Bezug auf den Zweck ist keine.",
                   ["Flugzeugbau: geringe Dichte bei ausreichender Festigkeit — Aluminium und seine Legierungen.",
                    "Stromkabel: hohe Leitfähigkeit bei vertretbarem Preis — Kupfer. In Überlandleitungen dagegen Aluminium, weil dort das Gewicht zählt.",
                    "Kochtopf: gute Wärmeleitfähigkeit und Beständigkeit — Edelstahl mit Aluminiumboden.",
                    "Zusätzlich zu bedenken: Korrosionsbeständigkeit, Preis, Verfügbarkeit und Recyclingfähigkeit. Ein Metall ist nie „das beste“, sondern das beste für einen Zweck."],
                   "Erst den Zweck nennen, dann die entscheidende Eigenschaft, dann das Metall.",
                   visual=anim("elektronengas", "C"))
    },
    "formelkarte": {"formeln": ["ρ = m : V"],
                    "saetze": ["Alle Metalle: Glanz, elektrische und Wärmeleitfähigkeit, Verformbarkeit.",
                               "Leichtmetall unter 5 g/cm³, Schwermetall darüber.",
                               "Dichten: Al 2,7 · Fe 7,9 · Cu 8,9 · Pb 11,3 g/cm³.",
                               "Bestes Metall gibt es nicht — nur das beste für einen Zweck."]},
    "tasks": [
        aufgabe("ME01-A1-001", "A", 1, "choice",
                "Welche Eigenschaft haben alle Metalle?",
                options=["Sie leiten den elektrischen Strom.", "Sie sind alle silbrig.", "Sie sind alle schwer."],
                answer=0,
                hints=["Kupfer ist rötlich, Gold gelb.", "Blei ist schwer, Aluminium leicht.", "Aber alle leiten Strom."],
                solution="Alle Metalle leiten den elektrischen Strom. Farbe und Dichte sind dagegen sehr verschieden.",
                misconceptions=[fv("verallgemeinert", 1,
                                   "Kupfer ist rötlich, Gold gelb. Die Farbe ist keine gemeinsame Eigenschaft.")],
                tags=["metalle"], spiral=["K-STOF"]),
        aufgabe("ME01-A2-002", "A", 2, "numeric",
                "Ein Aluminiumblock hat 20 cm³ und die Dichte 2,7 g/cm³. Welche Masse hat er?",
                answer=54, unit_label="g", tolerance=0.5,
                hints=["m = ρ · V.", "2,7 · 20.", "54 g."],
                solution="m = 2,7 g/cm³ · 20 cm³ = 54 g",
                misconceptions=[fv("dichte_geteilt_statt_mal", 7.41,
                                   "Aus Dichte und Volumen wird die Masse durch Multiplizieren.")],
                tags=["metalle", "rechnen"], spiral=["K-STOF"]),
        aufgabe("ME01-A3-003", "A", 3, "choice",
                "Warum wird Kupfer für Stromkabel verwendet?",
                options=["Es leitet den Strom sehr gut.", "Es ist besonders schwer.", "Es ist besonders billig."],
                answer=0,
                hints=["Was muss ein Kabel können?", "Strom leiten.", "Kupfer leitet sehr gut."],
                solution="Kupfer leitet den Strom sehr gut und lässt sich zu Draht ziehen. Beides braucht ein Kabel.",
                tags=["metalle"], spiral=["K-STOF"]),
        aufgabe("ME01-A4-004", "A", 4, "choice",
                "Aluminium hat 2,7 g/cm³, Blei 11,3 g/cm³. Welches ist ein Leichtmetall?",
                options=["Aluminium", "Blei", "beide"], answer=0,
                hints=["Die Grenze liegt bei 5 g/cm³.", "2,7 liegt darunter.", "Aluminium."],
                solution="Leichtmetalle haben eine Dichte unter 5 g/cm³. Aluminium mit 2,7 g/cm³ gehört dazu, Blei mit 11,3 g/cm³ nicht.",
                tags=["metalle"], spiral=["K-STOF"]),
        aufgabe("ME01-B1-005", "B", 1, "numeric",
                "Ein Eisenwürfel mit 3 cm Kantenlänge wiegt 213,3 g. Wie groß ist die Dichte?",
                answer=7.9, unit_label="g/cm³", tolerance=0.1,
                hints=["Erst das Volumen: 3 · 3 · 3.", "27 cm³.", "213,3 : 27."],
                solution="V = 27 cm³, ρ = 213,3 g : 27 cm³ = 7,9 g/cm³ — das ist Eisen.",
                misconceptions=[fv("volumen_als_flaeche", 23.7,
                                   "Ein Würfel hat das Volumen a · a · a = 27 cm³.")],
                tags=["metalle", "rechnen", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME01-B2-006", "B", 2, "choice",
                "Warum werden Überlandleitungen aus Aluminium statt aus Kupfer gebaut?",
                options=["Aluminium ist viel leichter; die Masten müssten sonst deutlich stärker sein.",
                         "Aluminium leitet besser als Kupfer.",
                         "Aluminium rostet nicht."],
                answer=0,
                hints=["Was ist bei einer Freileitung das Problem?",
                       "Das Gewicht zwischen den Masten.",
                       "Aluminium hat weniger als ein Drittel der Dichte von Kupfer."],
                solution="Kupfer leitet zwar besser, ist aber mehr als dreimal so dicht. Bei einer Freileitung entscheidet das Gewicht — deshalb Aluminium, mit etwas größerem Querschnitt.",
                misconceptions=[fv("verallgemeinert", 1,
                                   "Kupfer leitet besser als Aluminium. Den Ausschlag gibt hier das Gewicht.")],
                tags=["metalle", "bewerten", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME01-B2-007", "B", 2, "choice",
                "Warum fühlt sich ein Metallgriff kälter an als ein Holzgriff bei gleicher Temperatur?",
                options=["Metall leitet die Wärme schneller von der Hand weg.",
                         "Metall ist tatsächlich kälter.",
                         "Holz erzeugt Wärme."],
                answer=0,
                hints=["Beide haben dieselbe Temperatur.",
                       "Was unterscheidet sie?",
                       "Die Wärmeleitfähigkeit."],
                solution="Beide haben dieselbe Temperatur. Metall leitet die Wärme aber viel schneller von der Hand weg — deshalb fühlt es sich kälter an. Was du spürst, ist der Wärmestrom, nicht die Temperatur.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Beide Gegenstände haben dieselbe Temperatur. Verschieden ist die Wärmeleitfähigkeit.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["metalle", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME01-B3-008", "B", 3, "multi",
                "Ein Bauteil aus Aluminium (2,7 g/cm³) soll durch ein gleich großes aus Eisen (7,9 g/cm³) ersetzt werden. Das Volumen beträgt 350 cm³.",
                fields=[
                    {"label": "Masse aus Aluminium", "answer": 945, "unit_label": "g", "tolerance": 5},
                    {"label": "Masse aus Eisen", "answer": 2765, "unit_label": "g", "tolerance": 10},
                    {"label": "Mehrgewicht in Prozent", "answer": 192.6, "unit_label": "%", "tolerance": 3}
                ],
                hints=["m = ρ · V für beide.",
                       "2,7 · 350 und 7,9 · 350.",
                       "Mehrgewicht = (2765 − 945) : 945 · 100 %."],
                solution="Al: 2,7 · 350 = 945 g\nFe: 7,9 · 350 = 2765 g\nMehrgewicht: 1820 : 945 = 1,926 → 192,6 %",
                tags=["metalle", "rechnen", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME01-B3-009", "B", 3, "choice",
                "Warum wird für Glühwendel Wolfram verwendet?",
                options=["Es hat mit 3422 °C die höchste Schmelztemperatur aller Metalle.",
                         "Es leitet am besten.", "Es ist am billigsten."],
                answer=0,
                hints=["Was muss ein Glühdraht aushalten?",
                       "Sehr hohe Temperaturen.",
                       "Er darf nicht schmelzen."],
                solution="Ein Glühdraht wird über 2000 °C heiß. Nur Wolfram mit einer Schmelztemperatur von 3422 °C hält das aus — Leitfähigkeit und Preis sind hier zweitrangig.",
                tags=["metalle", "bewerten", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME01-B4-010", "B", 4, "assign",
                "Ordne jeder Anwendung die entscheidende Eigenschaft zu.",
                slots=["Flugzeugbau", "Stromkabel", "Kochtopfboden"],
                values=["geringe Dichte", "hohe elektrische Leitfähigkeit", "hohe Wärmeleitfähigkeit"],
                answer=[0, 1, 2],
                hints=["Für jede Anwendung zählt etwas anderes.",
                       "Im Flugzeug zählt das Gewicht.",
                       "Im Topfboden die Wärme."],
                solution="Flugzeug → geringe Dichte.\nKabel → elektrische Leitfähigkeit.\nTopfboden → Wärmeleitfähigkeit.",
                tags=["metalle", "bewerten", "bbr"]),
        aufgabe("ME01-C2-011", "C", 2, "choice",
                "Silber leitet besser als Kupfer. Warum werden Hausleitungen trotzdem aus Kupfer gebaut?",
                options=["Der geringe Vorteil rechtfertigt den weit höheren Preis nicht.",
                         "Silber leitet in Wirklichkeit schlechter.",
                         "Silber ist zu weich."],
                answer=0,
                hints=["Wie groß ist der Unterschied in der Leitfähigkeit?",
                       "Nur wenige Prozent.",
                       "Der Preisunterschied ist dagegen erheblich."],
                solution="Silber leitet nur wenige Prozent besser, kostet aber ein Vielfaches. Bei einer technischen Entscheidung wird immer abgewogen — die beste Eigenschaft entscheidet nicht allein.",
                tags=["metalle", "bewerten", "msa"]),
        aufgabe("ME01-C3-012", "C", 3, "choice",
                "Ein Bauteil soll leicht, korrosionsbeständig und gut zu verarbeiten sein. Welches Metall ist geeignet und warum?",
                options=["Aluminium — geringe Dichte, gut verformbar, bildet eine schützende Oxidschicht.",
                         "Blei — es ist weich und leicht zu verarbeiten.",
                         "Eisen — es ist am häufigsten verfügbar."],
                answer=0,
                hints=["Drei Kriterien müssen erfüllt sein.",
                       "Blei ist sehr dicht, Eisen rostet.",
                       "Aluminium erfüllt alle drei."],
                solution="Aluminium hat eine geringe Dichte, lässt sich gut verformen und schützt sich durch eine dichte Oxidschicht selbst vor weiterer Korrosion. Blei ist zu dicht, Eisen rostet ohne Schutz.",
                tags=["metalle", "bewerten", "msa"], spiral=["K-STOF"]),
        aufgabe("ME01-C3-013", "C", 3, "multi",
                "Eine Kupferleitung (8,9 g/cm³) mit 200 cm³ soll durch Aluminium (2,7 g/cm³) ersetzt werden. Wegen der schlechteren Leitfähigkeit braucht Aluminium 60 % mehr Volumen.",
                fields=[
                    {"label": "Masse der Kupferleitung", "answer": 1780, "unit_label": "g", "tolerance": 10},
                    {"label": "benötigtes Aluminiumvolumen", "answer": 320, "unit_label": "cm³", "tolerance": 5},
                    {"label": "Masse der Aluminiumleitung", "answer": 864, "unit_label": "g", "tolerance": 10}
                ],
                hints=["Cu: 8,9 · 200.",
                       "Volumen: 200 · 1,6.",
                       "Al: 2,7 · 320."],
                solution="Cu: 8,9 · 200 = 1780 g\nAl-Volumen: 200 · 1,6 = 320 cm³\nAl: 2,7 · 320 = 864 g\nTrotz größeren Volumens weniger als die Hälfte der Masse.",
                tags=["metalle", "rechnen", "msa"], spiral=["K-STOF"]),
        aufgabe("ME01-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt: „Gold ist das beste Metall.“ Wie bewertest du diese Aussage?",
                options=["Ohne Zweck ist „bestes Metall“ keine sinnvolle Aussage — für einen Glühdraht wäre Gold ungeeignet.",
                         "Richtig — Gold ist am wertvollsten.",
                         "Falsch — Silber ist das beste Metall."],
                answer=0,
                hints=["Wofür soll das Metall verwendet werden?",
                       "Das steht nicht in der Aussage.",
                       "Ohne Zweck lässt sich nicht bewerten."],
                solution="Gold ist korrosionsbeständig und gut leitfähig, aber weich, teuer und schmilzt bei 1064 °C. Für Kontakte in der Elektronik ist es hervorragend, für einen Glühdraht unbrauchbar. Bewertungen brauchen ein Kriterium und einen Zweck.",
                tags=["metalle", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "ME-02",
    "title": "Metallbindung und Elektronengas",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["die Metallbindung", "der Atomrumpf", "das Elektronengas", "das Metallgitter",
                     "verformbar", "die Legierung"],
    "worterklaerungen": {
        "Atomrumpf": "Ein Metallatom, das seine Außenelektronen abgegeben hat. Es ist positiv geladen.",
        "Elektronengas": "Die frei beweglichen Außenelektronen zwischen den Atomrümpfen."
    },
    "can_do": {
        "A": "Ich weiß, dass sich im Metall frei bewegliche Elektronen befinden.",
        "B": "Ich erkläre Leitfähigkeit und Verformbarkeit mit dem Elektronengasmodell.",
        "C": "Ich vergleiche Metall-, Ionen- und Elektronenpaarbindung und begründe die Unterschiede."
    },
    "lernkarten": {
        "A": karte("Elektronen, die wandern",
                   "Im Metall geben die Atome ihre Außenelektronen ab.",
                   ["Zurück bleiben positive Rümpfe.", "Die Elektronen bewegen sich frei dazwischen."],
                   "Frei bewegliche Elektronen — deshalb leiten Metalle.",
                   visual=anim("elektronengas", "A"),
                   beispiel={"titel": "Strom im Draht", "aufgabe": "Warum leitet ein Kupferdraht?",
                             "schritte": ["Die Elektronen sind frei beweglich.",
                                          "Sie wandern zum Pluspol."],
                             "ergebnis": "Es fließt Strom."}),
        "B": karte("Zwei Eigenschaften, ein Modell",
                   "Das Elektronengasmodell erklärt zwei auffällige Eigenschaften der Metalle mit derselben Vorstellung.",
                   ["Leitfähigkeit: Die Elektronen sind nicht an einzelne Atome gebunden und können durch das ganze Stück wandern.",
                    "Verformbarkeit: Verschiebt man zwei Gitterschichten, liegen wieder Rümpfe im Elektronengas — die Bindung hält. Das Metall verformt sich statt zu brechen.",
                    "Im Ionengitter träfen bei derselben Verschiebung gleiche Ladungen aufeinander. Deshalb ist Salz spröde und Metall nicht.",
                    "Auch der Metallglanz beruht auf den freien Elektronen: Sie reflektieren das Licht."],
                   "Frei bewegliche Elektronen erklären Leitfähigkeit, Verformbarkeit und Glanz zugleich.",
                   visual=anim("elektronengas", "B")),
        "C": karte("Drei Bindungsarten im Vergleich",
                   "Welche Bindung entsteht, hängt davon ab, welche Partner zusammenkommen — und daraus folgen die Eigenschaften des Stoffes.",
                   ["Metall + Metall: Metallbindung. Die Außenelektronen werden gemeinsam genutzt und sind frei beweglich. Folge: leitfähig, verformbar, glänzend.",
                    "Metall + Nichtmetall: Ionenbindung. Elektronen werden übertragen, es entstehen Ionen. Folge: hart, spröde, erst gelöst leitfähig.",
                    "Nichtmetall + Nichtmetall: Elektronenpaarbindung. Elektronen werden zu zweit geteilt. Folge: meist niedrig schmelzend, nicht leitfähig.",
                    "Die Zuordnung ist keine Regel ohne Ausnahme, aber für die Mittelstufe tragfähig — und sie erlaubt Vorhersagen."],
                   "Metall + Metall → Metallbindung. Metall + Nichtmetall → Ionenbindung. Nichtmetall + Nichtmetall → Elektronenpaarbindung.",
                   visual=anim("elektronengas", "C"))
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Metallgitter: positive Atomrümpfe im Elektronengas.",
                               "Frei bewegliche Elektronen → Leitfähigkeit und Glanz.",
                               "Verschiebbare Schichten → Verformbarkeit.",
                               "Metall+Metall → Metallbindung · Metall+Nichtmetall → Ionenbindung · Nichtmetall+Nichtmetall → Elektronenpaarbindung."]},
    "tasks": [
        aufgabe("ME02-A1-001", "A", 1, "choice",
                "Was befindet sich im Metall zwischen den Atomrümpfen?",
                options=["frei bewegliche Elektronen", "Wasser", "nichts"], answer=0,
                visual=anim("elektronengas", "A"),
                hints=["Die Atome haben ihre Außenelektronen abgegeben.",
                       "Wo sind diese Elektronen jetzt?",
                       "Zwischen den Rümpfen."],
                solution="Zwischen den positiven Atomrümpfen bewegen sich die abgegebenen Außenelektronen frei — das Elektronengas.",
                tags=["metallbindung"], spiral=["K-ATOM"]),
        aufgabe("ME02-A2-002", "A", 2, "choice",
                "Warum leiten Metalle den elektrischen Strom?",
                options=["Weil sich die Elektronen frei bewegen können.",
                         "Weil sie hart sind.", "Weil sie glänzen."],
                answer=0,
                hints=["Was transportiert die Ladung?", "Elektronen.", "Sie sind im Metall frei beweglich."],
                solution="Die frei beweglichen Elektronen des Elektronengases transportieren die Ladung durch das ganze Metallstück.",
                tags=["metallbindung"], spiral=["K-ATOM"]),
        aufgabe("ME02-A3-003", "A", 3, "choice",
                "Wie ist ein Atomrumpf geladen?",
                options=["positiv", "negativ", "gar nicht"], answer=0,
                hints=["Er hat Elektronen abgegeben.", "Elektronen sind negativ.", "Ohne sie überwiegt das Positive."],
                solution="Ein Atomrumpf hat seine Außenelektronen abgegeben und ist deshalb positiv geladen.",
                misconceptions=[fv("ladung_falsch_herum", 1,
                                   "Wer negative Elektronen abgibt, wird positiv.",
                                   "ladung_unvollstaendig")],
                tags=["metallbindung"], spiral=["K-ATOM"]),
        aufgabe("ME02-A4-004", "A", 4, "choice",
                "Warum lässt sich ein Metall verbiegen, ohne zu brechen?",
                options=["Die Schichten verschieben sich, die Bindung bleibt bestehen.",
                         "Metall ist sehr weich.", "Metall enthält Luft."],
                answer=0, visual=anim("elektronengas", "A"),
                hints=["Was passiert beim Verbiegen mit den Schichten?",
                       "Sie verschieben sich gegeneinander.",
                       "Und das Elektronengas hält weiter zusammen."],
                solution="Beim Verbiegen verschieben sich Gitterschichten. Weil das Elektronengas alle Rümpfe umgibt, bleibt die Bindung erhalten — das Metall verformt sich statt zu brechen.",
                tags=["metallbindung"], spiral=["K-ATOM"]),
        aufgabe("ME02-B1-005", "B", 1, "choice",
                "Woraus besteht ein Metallgitter?",
                options=["Aus positiven Atomrümpfen und frei beweglichen Elektronen.",
                         "Aus positiven und negativen Ionen.",
                         "Aus Molekülen."],
                answer=0, visual=anim("elektronengas", "B"),
                hints=["Es gibt nur eine Sorte Rümpfe.", "Alle sind positiv.", "Dazu das Elektronengas."],
                solution="Im Metallgitter sitzen ausschließlich positive Atomrümpfe, umgeben vom Elektronengas. Positive und negative Ionen im Wechsel wären ein Ionengitter.",
                misconceptions=[fv("bindungsart_verwechselt", 1,
                                   "Abwechselnd positive und negative Ionen bilden ein Salzgitter, kein Metallgitter.",
                                   "bindungsart_verwechselt")],
                tags=["metallbindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME02-B2-006", "B", 2, "choice",
                "Warum ist ein Salzkristall spröde, ein Metall aber verformbar?",
                options=["Im Salz treffen nach dem Verschieben gleiche Ladungen aufeinander, im Metall nicht.",
                         "Salz ist härter als Metall.",
                         "Metalle enthalten keine Ladungen."],
                answer=0,
                hints=["Was liegt im Metall zwischen den Rümpfen?",
                       "Das Elektronengas — gleichmäßig verteilt.",
                       "Im Salz wechseln sich Ladungen ab."],
                solution="Im Ionengitter zerstört eine Verschiebung die Abfolge der Ladungen. Im Metall ist das Elektronengas überall gleich — nach der Verschiebung passt alles wieder zusammen.",
                tags=["metallbindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME02-B2-007", "B", 2, "choice",
                "Warum glänzen Metalle?",
                options=["Die freien Elektronen reflektieren das Licht.",
                         "Die Oberfläche ist besonders glatt.",
                         "Metalle senden selbst Licht aus."],
                answer=0,
                hints=["Was ist an der Metalloberfläche besonders?",
                       "Das Elektronengas reicht bis dorthin.",
                       "Es wirft das Licht zurück."],
                solution="Die frei beweglichen Elektronen an der Oberfläche reflektieren das auftreffende Licht nahezu vollständig — das ergibt den Metallglanz. Eine frische Schnittfläche glänzt deshalb am stärksten.",
                tags=["metallbindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME02-B3-008", "B", 3, "assign",
                "Ordne jeder Kombination die passende Bindungsart zu.",
                slots=["Kupfer und Zink", "Natrium und Chlor", "Wasserstoff und Sauerstoff"],
                values=["Metallbindung", "Ionenbindung", "Elektronenpaarbindung"],
                answer=[0, 1, 2],
                hints=["Zwei Metalle ergeben eine Metallbindung.",
                       "Metall und Nichtmetall ergeben Ionen.",
                       "Zwei Nichtmetalle teilen Elektronenpaare."],
                solution="Kupfer + Zink → Metallbindung (Messing).\nNatrium + Chlor → Ionenbindung.\nWasserstoff + Sauerstoff → Elektronenpaarbindung.",
                misconceptions=[fv("bindungsart_verwechselt", 1,
                                   "Zwei Metalle bilden nie Ionen — beide würden Elektronen abgeben wollen.",
                                   "bindungsart_verwechselt")],
                tags=["metallbindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME02-B3-009", "B", 3, "choice",
                "Warum leitet ein Metall auch dann noch, wenn es zu Draht gezogen wurde?",
                options=["Die Elektronen bleiben frei beweglich, unabhängig von der Form.",
                         "Beim Ziehen entstehen neue Elektronen.",
                         "Nur dicke Stücke leiten gut."],
                answer=0,
                hints=["Ändert das Verformen die Bindung?",
                       "Nein — das Elektronengas bleibt.",
                       "Deshalb leitet auch dünner Draht."],
                solution="Beim Verformen verschieben sich nur die Schichten; das Elektronengas bleibt vollständig erhalten. Die Leitfähigkeit hängt vom Material ab, nicht von der Form — der Querschnitt beeinflusst nur den Widerstand.",
                tags=["metallbindung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME02-B4-010", "B", 4, "choice",
                "Warum steigt der elektrische Widerstand eines Metalls bei Erwärmung?",
                options=["Die Atomrümpfe schwingen stärker und behindern die wandernden Elektronen.",
                         "Es gibt weniger Elektronen.",
                         "Das Metall dehnt sich aus."],
                answer=0,
                hints=["Was ändert sich bei Wärme im Gitter?",
                       "Die Rümpfe schwingen stärker.",
                       "Die Elektronen kommen schlechter durch."],
                solution="Bei höherer Temperatur schwingen die Atomrümpfe stärker um ihre Plätze. Die wandernden Elektronen stoßen häufiger an — der Widerstand steigt. Die Zahl der Elektronen bleibt gleich.",
                tags=["metallbindung", "msa"], spiral=["K-ATOM"]),
        aufgabe("ME02-C2-011", "C", 2, "choice",
                "Warum sind Metalle gute Wärmeleiter?",
                options=["Die frei beweglichen Elektronen transportieren die Energie schnell durch das Gitter.",
                         "Metalle sind dicht gepackt.",
                         "Metalle speichern viel Wärme."],
                answer=0,
                hints=["Was bewegt sich im Metall besonders leicht?",
                       "Die Elektronen.",
                       "Sie transportieren auch Energie."],
                solution="Neben der Ladung transportieren die freien Elektronen auch Energie. Deshalb leiten Metalle Wärme viel besser als Stoffe ohne Elektronengas — Leitfähigkeit für Strom und Wärme haben dieselbe Ursache.",
                tags=["metallbindung", "msa"], spiral=["K-ATOM"]),
        aufgabe("ME02-C3-012", "C", 3, "choice",
                "Warum ist eine Legierung meist härter als das reine Metall?",
                options=["Fremdatome anderer Größe stören die Ordnung; die Schichten lassen sich schwerer verschieben.",
                         "Legierungen haben mehr Elektronen.",
                         "Legierungen enthalten kein Elektronengas."],
                answer=0,
                hints=["Was macht ein Metall weich?",
                       "Dass Schichten leicht gleiten.",
                       "Fremdatome behindern genau das."],
                solution="Eingelagerte Fremdatome haben andere Größen und stören die regelmäßige Schichtung. Die Schichten gleiten schwerer — die Legierung wird härter, aber weniger verformbar. Deshalb ist Bronze härter als Kupfer.",
                tags=["metallbindung", "msa"], spiral=["K-STOF"]),
        aufgabe("ME02-C3-013", "C", 3, "choice",
                "Welche Aussage über die Metallbindung ist richtig?",
                options=["Die Elektronen gehören dem gesamten Metallstück, nicht einzelnen Atomen.",
                         "Jedes Elektron gehört zu genau zwei Atomrümpfen.",
                         "Die Elektronen sitzen fest zwischen je zwei Rümpfen."],
                answer=0,
                hints=["Vergleiche mit der Elektronenpaarbindung.",
                       "Dort gehört ein Paar zu genau zwei Atomen.",
                       "Im Metall ist es anders."],
                solution="Anders als bei der Elektronenpaarbindung sind die Elektronen im Metall nicht zwei bestimmten Partnern zugeordnet. Sie gehören dem gesamten Stück — genau das macht sie frei beweglich.",
                misconceptions=[fv("bindungsart_verwechselt", 1,
                                   "Das beschreibt die Elektronenpaarbindung. Im Metall gehören die Elektronen allen Rümpfen gemeinsam.",
                                   "bindungsart_verwechselt")],
                tags=["metallbindung", "msa"], spiral=["K-ATOM"]),
        aufgabe("ME02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Im Metall sind Ionen, also müsste es wie Salz spröde sein.“ Wie antwortest du?",
                options=["Im Metall gibt es nur positive Rümpfe in einem gemeinsamen Elektronengas — keine abwechselnden Ladungen, die beim Verschieben kollidieren.",
                         "Er hat recht, Metalle sind spröde.",
                         "Im Metall gibt es gar keine geladenen Teilchen."],
                answer=0,
                hints=["Was unterscheidet Metallgitter und Ionengitter?",
                       "Im Salz wechseln sich positive und negative Ionen ab.",
                       "Im Metall sind alle Rümpfe positiv."],
                solution="Der Ansatz ist richtig — es gibt geladene Teilchen. Entscheidend ist aber die Anordnung: Im Salz wechseln sich positive und negative Ionen ab, im Metall sind alle Rümpfe gleich geladen und werden vom Elektronengas zusammengehalten. Deshalb bricht das eine und verformt sich das andere.",
                tags=["metallbindung", "bewerten", "msa"], spiral=["K-ATOM"])
    ]
})

if __name__ == "__main__":
    schreiben("me", E, "Bereich ME · Einheiten 1 und 2")
