# -*- coding: utf-8 -*-
"""OS-04, OS-05 (Abschluss organische Säuren) und ES-01, ES-02 (Ester)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

OS = []
ES = []

OS.append({
    "unit": "OS-04",
    "title": "Fruchtsäuren, Dicarbon- und Aminosäuren",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K3.1"],
    "klasse": 10,
    "wortspeicher": ["die Hydroxycarbonsäure", "die Dicarbonsäure", "die Aminosäure",
                     "die Aminogruppe", "die Citronensäure", "die Milchsäure"],
    "worterklaerungen": {
        "Hydroxycarbonsäure": "Eine Säure mit zusätzlicher OH-Gruppe, etwa Milchsäure.",
        "Dicarbonsäure": "Eine Säure mit zwei Carboxygruppen, etwa Oxalsäure.",
        "Aminosäure": "Ein Molekül mit einer Carboxy- und einer Aminogruppe."
    },
    "can_do": {
        "A": "Ich erkenne Moleküle mit mehreren funktionellen Gruppen.",
        "B": "Ich ordne Fruchtsäuren und Dicarbonsäuren zu und erkläre ihre gute Löslichkeit.",
        "C": "Ich beschreibe den Bau von Aminosäuren und begründe ihre Besonderheit."
    },
    "lernkarten": {
        "A": karte("Mehrere Gruppen an einem Molekül",
                   "Manche Moleküle haben mehr als eine funktionelle Gruppe.",
                   ["Milchsäure hat eine COOH- und eine OH-Gruppe.",
                    "Oxalsäure hat zwei COOH-Gruppen."],
                   "Mehr Gruppen: besser wasserlöslich.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "cooh", "name": "Fruchtsäure",
                           "alt": "Strukturformel einer Carbonsäure."},
                   beispiel={"titel": "Milchsäure", "aufgabe": "Welche Gruppen sind da?",
                             "schritte": ["Eine Carboxygruppe –COOH.",
                                          "Eine Hydroxylgruppe –OH."],
                             "ergebnis": "Zwei funktionelle Gruppen."}),
        "B": karte("Fruchtsäuren und Dicarbonsäuren",
                   "In Früchten und im Stoffwechsel finden sich Säuren mit mehreren Gruppen — und das prägt ihre Eigenschaften.",
                   ["Milchsäure trägt zusätzlich eine OH-Gruppe. Sie entsteht bei der Milchsäuregärung und im Muskel bei starker Belastung.",
                    "Citronensäure hat drei Carboxygruppen und eine OH-Gruppe. Sie ist deshalb sehr gut wasserlöslich und wirkt als Entkalker.",
                    "Oxalsäure ist die einfachste Dicarbonsäure. Sie kommt in Rhabarber und Sauerampfer vor und bindet Calcium — deshalb die Empfehlung, Rhabarber mit Milch zu essen.",
                    "Weinsäure findet sich in Trauben, Äpfelsäure in Äpfeln.",
                    "Grundsatz: Jede zusätzliche polare Gruppe verbessert die Wasserlöslichkeit und erhöht die Siedetemperatur."],
                   "Mehr polare Gruppen bedeuten bessere Löslichkeit und höhere Siedetemperatur.",
                   visual={"type": "phskala", "marken": [{"wert": 2.2, "stoff": "Citronensäure"},
                                                         {"wert": 3.9, "stoff": "Milchsäure"}],
                           "alt": "pH-Werte von Citronensäure und Milchsäure."}),
        "C": karte("Aminosäuren — zwei Gruppen mit Gegensatz",
                   "Aminosäuren tragen zwei funktionelle Gruppen mit entgegengesetztem Verhalten: eine saure und eine basische. Daraus folgt ihre besondere Rolle im Leben.",
                   ["Die Carboxygruppe –COOH kann ein Proton abgeben, die Aminogruppe –NH₂ eines aufnehmen.",
                    "Deshalb liegt eine Aminosäure meist als Zwitterion vor: Das Proton ist von der einen zur anderen Gruppe gewandert.",
                    "Sie kann sowohl mit Säuren als auch mit Laugen reagieren — man nennt das amphoter.",
                    "Über die beiden Gruppen können Aminosäuren miteinander verknüpft werden. Aus vielen entsteht ein Eiweiß.",
                    "Einfache Vertreter: Glycin, Alanin. Rund 20 verschiedene Aminosäuren bilden alle Eiweiße des Körpers."],
                   "Saure und basische Gruppe im selben Molekül — daher amphoter und verknüpfbar.",
                   visual={"type": "struktur", "kette": 2, "gruppe": "cooh", "name": "Aminosäure (Grundgerüst)",
                           "alt": "Strukturformel einer einfachen Aminosäure."})
    },
    "formelkarte": {"formeln": ["Milchsäure CH₃–CHOH–COOH",
                               "Oxalsäure HOOC–COOH",
                               "Glycin H₂N–CH₂–COOH"],
                    "saetze": ["Hydroxycarbonsäure: COOH plus OH.",
                               "Dicarbonsäure: zwei COOH-Gruppen.",
                               "Aminosäure: COOH plus NH₂ — amphoter.",
                               "Mehr polare Gruppen: bessere Löslichkeit."]},
    "tasks": [
        aufgabe("OS04-A1-001", "A", 1, "choice",
                "Welche Gruppen hat Milchsäure?",
                options=["eine COOH- und eine OH-Gruppe", "zwei COOH-Gruppen", "nur eine OH-Gruppe"],
                answer=0,
                hints=["Es ist eine Säure — also COOH.", "Dazu kommt eine weitere Gruppe.", "Eine OH-Gruppe."],
                solution="Milchsäure trägt eine Carboxygruppe und zusätzlich eine Hydroxylgruppe.",
                tags=["fruchtsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS04-A2-002", "A", 2, "choice",
                "In welcher Frucht steckt viel Citronensäure?",
                options=["Zitrone", "Banane", "Kartoffel"], answer=0,
                hints=["Der Name verrät es.", "Zitrone.", "Daher der Name."],
                solution="Citronensäure kommt vor allem in Zitrusfrüchten vor — daher ihr Name.",
                tags=["fruchtsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS04-A3-003", "A", 3, "numeric",
                "Wie viele Carboxygruppen hat Oxalsäure?",
                answer=2, tolerance=0,
                hints=["Es ist eine Dicarbonsäure.", "Di steht für zwei.", "2."],
                solution="Oxalsäure ist die einfachste Dicarbonsäure und hat zwei Carboxygruppen: HOOC–COOH.",
                tags=["fruchtsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS04-A4-004", "A", 4, "choice",
                "Welche zwei Gruppen hat eine Aminosäure?",
                options=["–COOH und –NH₂", "zwei –COOH", "–OH und –NH₂"], answer=0,
                hints=["Der Name sagt beides.", "Amino und Säure.", "–NH₂ und –COOH."],
                solution="Eine Aminosäure trägt eine Aminogruppe –NH₂ und eine Carboxygruppe –COOH.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 2,
                                   "Der Säureteil ist die Carboxygruppe –COOH, nicht die Hydroxylgruppe.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["fruchtsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS04-B1-005", "B", 1, "choice",
                "Warum ist Citronensäure sehr gut wasserlöslich?",
                options=["Sie hat drei Carboxygruppen und eine OH-Gruppe — viele polare Stellen.",
                         "Sie ist besonders leicht.",
                         "Sie ist unpolar."],
                answer=0,
                hints=["Zähle die polaren Gruppen.",
                       "Es sind vier.",
                       "Viele polare Gruppen heißt gut löslich."],
                solution="Vier polare Gruppen an einem kleinen Molekül bedeuten sehr viele Wasserstoffbrücken zum Wasser — Citronensäure löst sich hervorragend.",
                tags=["fruchtsaeuren", "bbr"], spiral=["K-SL"]),
        aufgabe("OS04-B2-006", "B", 2, "choice",
                "Warum wird empfohlen, Rhabarber mit Milch zu essen?",
                options=["Die Oxalsäure bindet das Calcium der Milch statt das des Körpers.",
                         "Milch neutralisiert den Geschmack.",
                         "Milch macht die Säure süßer."],
                answer=0,
                hints=["Was macht Oxalsäure mit Calcium?",
                       "Sie bindet es zu schwerlöslichem Calciumoxalat.",
                       "Besser das Calcium der Milch als das eigene."],
                solution="Oxalsäure bildet mit Calcium schwerlösliches Calciumoxalat. Wird Calcium über Milch zugeführt, bindet die Säure dieses statt das körpereigene aus Knochen und Zähnen.",
                tags=["fruchtsaeuren", "bewerten", "msa"], spiral=["K-SL"]),
        aufgabe("OS04-B2-007", "B", 2, "choice",
                "Wobei entsteht Milchsäure im Körper?",
                options=["Bei starker Muskelbelastung ohne ausreichenden Sauerstoff.",
                         "Bei der Verdauung von Fett.",
                         "Beim Atmen."],
                answer=0,
                hints=["Wann brennt der Muskel?",
                       "Bei starker Belastung.",
                       "Dann fehlt Sauerstoff für den vollständigen Abbau."],
                solution="Reicht der Sauerstoff im Muskel nicht aus, wird Glucose unvollständig abgebaut — es entsteht Milchsäure. Dieselbe Reaktion nutzen Milchsäurebakterien bei der Herstellung von Joghurt und Sauerkraut.",
                tags=["fruchtsaeuren", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS04-B3-008", "B", 3, "assign",
                "Ordne jede Säure ihrem Vorkommen zu.",
                slots=["Citronensäure", "Weinsäure", "Oxalsäure"],
                values=["Zitrusfrüchte", "Trauben", "Rhabarber"], answer=[0, 1, 2],
                hints=["Die Namen helfen.",
                       "Weinsäure kommt aus Trauben.",
                       "Oxalsäure aus Rhabarber und Sauerampfer."],
                solution="Citronensäure → Zitrusfrüchte, Weinsäure → Trauben, Oxalsäure → Rhabarber.",
                tags=["fruchtsaeuren", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS04-B3-009", "B", 3, "choice",
                "Was bedeutet „amphoter“ bei einer Aminosäure?",
                options=["Sie kann sowohl als Säure als auch als Base reagieren.",
                         "Sie ist besonders stark.",
                         "Sie löst sich in Fett und Wasser."],
                answer=0,
                hints=["Sie hat zwei gegensätzliche Gruppen.",
                       "Eine gibt Protonen ab, eine nimmt auf.",
                       "Also beides."],
                solution="Die Carboxygruppe kann ein Proton abgeben, die Aminogruppe eines aufnehmen. Deshalb reagiert eine Aminosäure je nach Partner als Säure oder als Base — sie ist amphoter, wie auch Wasser.",
                tags=["fruchtsaeuren", "msa"], spiral=["K-SL"]),
        aufgabe("OS04-B4-010", "B", 4, "choice",
                "Warum können Aminosäuren zu langen Ketten verknüpft werden?",
                options=["Die Carboxygruppe der einen reagiert mit der Aminogruppe der nächsten.",
                         "Weil sie klein sind.",
                         "Weil sie geladen sind."],
                answer=0,
                hints=["Jede Aminosäure hat zwei verschiedene Enden.",
                       "Sie passen zueinander.",
                       "So entsteht eine Kette."],
                solution="Jede Aminosäure hat ein saures und ein basisches Ende. Reagiert die Carboxygruppe der einen mit der Aminogruppe der nächsten, entsteht eine Verknüpfung — aus vielen wird ein Eiweiß.",
                tags=["fruchtsaeuren", "msa"], spiral=["K-ORG"]),
        aufgabe("OS04-C2-011", "C", 2, "choice",
                "Warum liegt eine Aminosäure in Lösung meist als Zwitterion vor?",
                options=["Das Proton wandert von der Carboxygruppe zur Aminogruppe im selben Molekül.",
                         "Weil zwei Moleküle sich verbinden.",
                         "Weil Wasser Protonen liefert."],
                answer=0,
                hints=["Beide Gruppen sitzen am selben Molekül.",
                       "Die eine gibt ab, die andere nimmt auf.",
                       "Der Weg ist kurz."],
                solution="Die Carboxygruppe gibt ihr Proton ab, die Aminogruppe desselben Moleküls nimmt es auf. Das Molekül trägt dann eine positive und eine negative Ladung — ein Zwitterion. Nach außen ist es dennoch ungeladen.",
                tags=["fruchtsaeuren", "msa"], spiral=["K-SL"]),
        aufgabe("OS04-C3-012", "C", 3, "choice",
                "Warum schmelzen Aminosäuren erst bei sehr hohen Temperaturen?",
                options=["Als Zwitterionen ziehen sie einander wie in einem Ionengitter an.",
                         "Sie sind sehr große Moleküle.",
                         "Sie enthalten Metall."],
                answer=0,
                hints=["Welche Ladungen tragen sie?",
                       "Positive und negative im selben Molekül.",
                       "Das wirkt wie in einem Salz."],
                solution="Als Zwitterionen ziehen sich die Moleküle wie Ionen in einem Gitter an. Deshalb sind Aminosäuren feste, hochschmelzende Stoffe — anders als andere organische Moleküle ähnlicher Größe.",
                tags=["fruchtsaeuren", "msa"], spiral=["K-ATOM"]),
        aufgabe("OS04-C3-013", "C", 3, "numeric",
                "Wie groß ist die molare Masse von Glycin H₂N–CH₂–COOH? (C = 12, H = 1, N = 14, O = 16 g/mol)",
                answer=75, unit_label="g/mol", tolerance=1,
                hints=["2 C, 5 H, 1 N, 2 O.",
                       "24 + 5 + 14 + 32.",
                       "75 g/mol."],
                solution="M = 2 · 12 + 5 · 1 + 14 + 2 · 16 = 24 + 5 + 14 + 32 = 75 g/mol",
                tags=["fruchtsaeuren", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("OS04-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Fruchtsäuren sind natürlich, also gut für die Zähne.“ Wie bewertest du das?",
                options=["Falsch — Fruchtsäuren greifen den Zahnschmelz an, unabhängig von ihrer Herkunft.",
                         "Richtig.",
                         "Falsch — Fruchtsäuren haben keine Wirkung auf Zähne."],
                answer=0,
                hints=["Was macht eine Säure mit Kalk?",
                       "Sie löst ihn.",
                       "Zahnschmelz enthält Calciumverbindungen."],
                solution="Zahnschmelz besteht überwiegend aus Calciumverbindungen und wird von jeder Säure angegriffen — die Herkunft spielt keine Rolle. Deshalb die Empfehlung, nach saurem Obst zu warten, bevor die Zähne geputzt werden.",
                tags=["fruchtsaeuren", "bewerten", "msa"], spiral=["K-SL"])
    ]
})

OS.append({
    "unit": "OS-05",
    "title": "Anwenden & Prüfungstraining Carbonsäuren",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["die Carboxygruppe", "die homologe Reihe", "das Carboxylat",
                     "die Neutralisation", "die Aminosäure"],
    "worterklaerungen": {
        "Struktur-Eigenschafts-Konzept": "Aus dem Bau folgen die Eigenschaften."
    },
    "can_do": {
        "A": "Ich benenne Carbonsäuren und erkenne die Carboxygruppe.",
        "B": "Ich verbinde Bau, Eigenschaften und Reaktionen der Carbonsäuren.",
        "C": "Ich begründe Eigenschaften aus der Struktur und bewerte Aussagen."
    },
    "lernkarten": {
        "A": karte("Carbonsäuren auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["–COOH ist die funktionelle Gruppe.", "Die Salze enden auf -at."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen.",
                   ["Bau: Die Carboxygruppe gibt ein Proton ab — anders als die Hydroxylgruppe des Alkohols.",
                    "Reihe: CₙH₂ₙ₊₁COOH, Endung -säure, Trivialnamen daneben.",
                    "Reaktion: Mit Laugen entstehen Salze, mit Alkoholen Ester."],
                   "Die funktionelle Gruppe bestimmt das Reaktionsverhalten.",
                   visual=anim("veresterung", "B")),
        "C": karte("Typische Prüfungsfehler",
                   "Vier Fehler tauchen in diesem Bereich regelmäßig auf.",
                   ["Das C-Atom der Carboxygruppe nicht mitzählen — Ethansäure hat zwei C-Atome, nicht drei.",
                    "Stärke und Konzentration verwechseln: Auch konzentrierte Essigsäure bleibt eine schwache Säure.",
                    "Von natürlicher Herkunft auf Unbedenklichkeit schließen.",
                    "Alkohol und Säure verwechseln: Die OH-Gruppe allein macht noch nicht sauer."],
                   "Das C der Carboxygruppe zählt mit. Stärke ist nicht Konzentration.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["R–COOH + H₂O ⇌ R–COO⁻ + H₃O⁺",
                               "CH₃COOH + NaOH → CH₃COONa + H₂O",
                               "HCOOH 46 · CH₃COOH 60 · C₂H₅COOH 74 g/mol"],
                    "saetze": ["–COOH ist die Carboxygruppe.",
                               "Organische Säuren sind schwache Säuren.",
                               "Aus -säure wird -at.",
                               "Das C-Atom der Carboxygruppe zählt zur Kette."]},
    "tasks": [
        aufgabe("OS05-A1-001", "A", 1, "choice",
                "Welche Gruppe macht eine organische Säure sauer?",
                options=["–COOH", "–OH", "–CH₃"], answer=0,
                hints=["Die Carboxygruppe.", "Sie enthält zwei O-Atome.", "–COOH."],
                solution="Die Carboxygruppe –COOH gibt das Proton ab.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("OS05-A2-002", "A", 2, "choice",
                "Wie heißt das Salz der Essigsäure?",
                options=["Acetat", "Formiat", "Citrat"], answer=0,
                hints=["Aus -säure wird -at.", "Essigsäure heißt lateinisch acidum aceticum.", "Acetat."],
                solution="Das Salz der Essigsäure heißt Acetat.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("OS05-A3-003", "A", 3, "numeric",
                "Wie viele C-Atome hat Ethansäure insgesamt?",
                answer=2, tolerance=0,
                hints=["Eth steht für 2.", "Das C der COOH-Gruppe zählt mit.", "2."],
                solution="Ethansäure CH₃COOH hat zwei C-Atome, eines davon in der Carboxygruppe.",
                misconceptions=[fv("summenformel_falsch_gelesen", 3,
                                   "Eth steht für zwei C-Atome insgesamt.",
                                   "summenformel_falsch_gelesen")],
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("OS05-A4-004", "A", 4, "choice",
                "Was entsteht aus Essigsäure und Natronlauge?",
                options=["Natriumacetat und Wasser", "ein Gas", "ein Alkohol"], answer=0,
                hints=["Es ist eine Neutralisation.", "Salz und Wasser.", "Natriumacetat."],
                solution="CH₃COOH + NaOH → CH₃COONa + H₂O",
                tags=["pruefung"], spiral=["K-REAK"]),
        aufgabe("OS05-B1-005", "B", 1, "numeric",
                "Wie groß ist die molare Masse von Essigsäure? (C = 12, H = 1, O = 16 g/mol)",
                answer=60, unit_label="g/mol", tolerance=1,
                hints=["2 C, 4 H, 2 O.", "24 + 4 + 32.", "60 g/mol."],
                solution="M(CH₃COOH) = 24 + 4 + 32 = 60 g/mol",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("OS05-B2-006", "B", 2, "choice",
                "Warum reagiert Ethanol neutral, Essigsäure aber sauer?",
                options=["Nur in der Carboxygruppe wird die O–H-Bindung durch die benachbarte Doppelbindung geschwächt.",
                         "Ethanol hat kein Wasserstoffatom.",
                         "Essigsäure ist konzentrierter."],
                answer=0,
                hints=["Beide haben eine OH-Gruppe.",
                       "Verschieden ist die Nachbarschaft.",
                       "Die C=O-Doppelbindung macht den Unterschied."],
                solution="Die benachbarte Doppelbindung zum Sauerstoff zieht Elektronen ab und schwächt die Bindung zum Wasserstoff. Nur dann kann das Proton abgegeben werden.",
                tags=["pruefung", "msa"], spiral=["K-ORG"]),
        aufgabe("OS05-B2-007", "B", 2, "numeric",
                "60 mL Essigsäurelösung (0,1 mol/L) werden neutralisiert. Wie viel Natronlauge mit 0,2 mol/L wird gebraucht?",
                answer=30, unit_label="mL", tolerance=1,
                hints=["c₁ · V₁ = c₂ · V₂.",
                       "0,1 · 60 = 0,2 · V₂.",
                       "V₂ = 30 mL."],
                solution="0,1 mol/L · 60 mL = 0,2 mol/L · V₂ → V₂ = 30 mL",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-SL"]),
        aufgabe("OS05-B3-008", "B", 3, "choice",
                "Warum siedet Essigsäure (118 °C) höher als Ethanol (78 °C)?",
                options=["Die Carboxygruppe bildet über beide Sauerstoffatome Wasserstoffbrücken.",
                         "Essigsäure ist deutlich schwerer.",
                         "Essigsäure ist unpolar."],
                answer=0,
                hints=["Wie viele Brücken kann eine Carboxygruppe bilden?",
                       "Zwei.",
                       "Zwei Moleküle bilden ein stabiles Paar."],
                solution="Die Carboxygruppe kann über beide Sauerstoffatome Brücken bilden. Zwei Moleküle lagern sich zu einem Doppelmolekül zusammen — das erfordert beim Sieden mehr Energie.",
                tags=["pruefung", "msa"], spiral=["K-ORG"]),
        aufgabe("OS05-B3-009", "B", 3, "choice",
                "Warum ist Natriumacetat geruchlos, Essigsäure aber nicht?",
                options=["Das Salz besteht aus Ionen im Gitter und ist nicht flüchtig.",
                         "Das Salz ist trocken.",
                         "Das Salz enthält kein Kohlenstoff."],
                answer=0,
                hints=["Was riecht man überhaupt?",
                       "Flüchtige Teilchen.",
                       "Ionen im Gitter sind nicht flüchtig."],
                solution="Geruch setzt flüchtige Teilchen voraus. Im Ionengitter des Salzes sind die Teilchen fest gebunden — es riecht nicht.",
                tags=["pruefung", "bbr"], spiral=["K-ATOM"]),
        aufgabe("OS05-B4-010", "B", 4, "assign",
                "Ordne jeder Stoffklasse ihre funktionelle Gruppe zu.",
                slots=["Alkohol", "Carbonsäure", "Aminosäure"],
                values=["–OH", "–COOH", "–COOH und –NH₂"], answer=[0, 1, 2],
                hints=["Alkohole tragen die Hydroxylgruppe.",
                       "Säuren die Carboxygruppe.",
                       "Aminosäuren beide plus Amino."],
                solution="Alkohol → –OH.\nCarbonsäure → –COOH.\nAminosäure → –COOH und –NH₂.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS05-C2-011", "C", 2, "choice",
                "Warum ist Citronensäure besser wasserlöslich als Buttersäure?",
                options=["Sie hat vier polare Gruppen bei kurzer Kette, Buttersäure nur eine.",
                         "Sie ist leichter.",
                         "Sie ist eine stärkere Säure."],
                answer=0,
                hints=["Zähle die polaren Gruppen.",
                       "Citronensäure: drei COOH und eine OH.",
                       "Buttersäure: eine COOH."],
                solution="Vier polare Gruppen an einem kleinen Molekül binden viele Wassermoleküle. Buttersäure hat nur eine polare Gruppe bei längerer unpolarer Kette.",
                tags=["pruefung", "msa"], spiral=["K-SL"]),
        aufgabe("OS05-C3-012", "C", 3, "multi",
                "30 g Essigsäure (M = 60 g/mol) werden mit Natronlauge neutralisiert.",
                fields=[
                    {"label": "Stoffmenge der Säure", "answer": 0.5, "unit_label": "mol", "tolerance": 0.03},
                    {"label": "benötigte Stoffmenge NaOH", "answer": 0.5, "unit_label": "mol", "tolerance": 0.03},
                    {"label": "Masse des Natriumacetats (M = 82 g/mol)", "answer": 41, "unit_label": "g", "tolerance": 1}
                ],
                hints=["n = 30 : 60 = 0,5 mol.",
                       "Einprotonig, also 1 : 1.",
                       "m = 0,5 · 82."],
                solution="n(Säure) = 0,5 mol → n(NaOH) = 0,5 mol → m(Salz) = 41 g",
                tags=["pruefung", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("OS05-C3-013", "C", 3, "choice",
                "Welche Antwort auf „Erkläre, warum Essigsäure sauer reagiert“ ist vollständig?",
                options=["Die Carboxygruppe gibt in Wasser ein Proton ab; dabei entstehen Oxonium-Ionen, die die Lösung sauer machen.",
                         "Weil sie eine Säure ist.",
                         "Weil sie sauer schmeckt."],
                answer=0,
                hints=["„Erkläre“ verlangt eine Ursache.",
                       "Welche Teilchen machen sauer?",
                       "Oxonium-Ionen."],
                solution="Antwort 2 wiederholt die Frage, Antwort 3 nennt eine Beobachtung. Nur Antwort 1 nennt Vorgang und Ursache.",
                tags=["pruefung", "operatoren", "msa"]),
        aufgabe("OS05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Konzentrierte Essigsäure ist eine starke Säure.“ Wie bewertest du das?",
                options=["Falsch — stark und konzentriert sind zwei verschiedene Begriffe; Essigsäure bleibt schwach.",
                         "Richtig.",
                         "Falsch — Essigsäure ist gar keine Säure."],
                answer=0,
                hints=["Was bedeutet „stark“?",
                       "Wie vollständig Protonen abgegeben werden.",
                       "Konzentriert sagt nur, wie viel Stoff da ist."],
                solution="„Stark“ beschreibt, wie vollständig eine Säure ihre Protonen abgibt — das ist eine Stoffeigenschaft. „Konzentriert“ beschreibt, wie viel Stoff je Volumen vorliegt. Konzentrierte Essigsäure ist ätzend, aber chemisch weiterhin eine schwache Säure.",
                misconceptions=[fv("staerke_und_konzentration", 1,
                                   "Stärke ist eine Stoffeigenschaft, Konzentration eine Mengenangabe.")],
                tags=["pruefung", "bewerten", "msa"], spiral=["K-SL"])
    ]
})

# ============================================================
# ES-01 · Veresterung
# ============================================================
ES.append({
    "unit": "ES-01",
    "title": "Veresterung: aus Säure und Alkohol",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.4"],
    "klasse": 10,
    "sicherheit": [
        "Konzentrierte Schwefelsäure als Katalysator ist stark ätzend — Schutzbrille und Handschuhe.",
        "Ester sind meist leicht entzündbar; kein offenes Feuer beim Erhitzen."
    ],
    "wortspeicher": ["die Veresterung", "der Ester", "die Kondensationsreaktion",
                     "der Katalysator", "das Gleichgewicht", "die Esterbindung"],
    "worterklaerungen": {
        "Veresterung": "Aus einer Säure und einem Alkohol entstehen ein Ester und Wasser.",
        "Kondensationsreaktion": "Zwei Moleküle verbinden sich unter Abspaltung von Wasser."
    },
    "can_do": {
        "A": "Ich weiß, dass aus Säure und Alkohol ein Ester und Wasser entstehen.",
        "B": "Ich benenne Ester und stelle die Reaktionsgleichung auf.",
        "C": "Ich erkläre die Rolle des Katalysators und das Gleichgewicht."
    },
    "lernkarten": {
        "A": karte("Zwei Stoffe werden eins",
                   "Eine Säure und ein Alkohol reagieren miteinander.",
                   ["Es entsteht ein Ester.", "Und ein Molekül Wasser."],
                   "Säure + Alkohol → Ester + Wasser.",
                   visual=anim("veresterung", "A"),
                   beispiel={"titel": "Essigsäure und Ethanol",
                             "aufgabe": "Was entsteht?",
                             "schritte": ["Die OH-Gruppe der Säure geht ab.",
                                          "Das H der Alkoholgruppe auch.",
                                          "Beide bilden Wasser."],
                             "ergebnis": "Essigsäureethylester und Wasser"}),
        "B": karte("Woher das Wasser kommt",
                   "Die Veresterung ist eine Kondensationsreaktion: Zwei Moleküle verbinden sich, und dabei wird Wasser frei. Woher genau dessen Bestandteile stammen, ist der Kern der Sache.",
                   ["Aus der Carboxygruppe der Säure stammt die OH-Gruppe.",
                    "Aus der Hydroxylgruppe des Alkohols stammt das Wasserstoffatom.",
                    "Beide zusammen ergeben das Wassermolekül. Die verbleibenden Reste sind über eine Esterbindung verknüpft.",
                    "Der Name folgt einer Regel: Säure zuerst, dann der Alkoholrest, dann „ester“ — Essigsäureethylester.",
                    "Allgemein: R–COOH + HO–R' ⇌ R–COO–R' + H₂O"],
                   "Die OH-Gruppe stammt aus der Säure, das H aus dem Alkohol.",
                   visual=anim("veresterung", "B")),
        "C": karte("Gleichgewicht und Katalysator",
                   "Die Veresterung läuft nie vollständig ab. Wer das versteht, versteht auch, warum konzentrierte Schwefelsäure zugesetzt wird.",
                   ["Die Reaktion ist umkehrbar: Ester und Wasser reagieren zurück zu Säure und Alkohol. Diese Rückreaktion heißt Esterspaltung oder Hydrolyse.",
                    "Es stellt sich ein Gleichgewicht ein — typischerweise bei rund zwei Dritteln Umsatz.",
                    "Konzentrierte Schwefelsäure wirkt doppelt: Sie beschleunigt die Reaktion als Katalysator und entzieht zugleich das entstehende Wasser.",
                    "Weil das Wasser aus dem Gleichgewicht entfernt wird, verschiebt es sich zur Seite des Esters. Die Ausbeute steigt.",
                    "Der Katalysator wird dabei nicht verbraucht — er liegt am Ende unverändert vor."],
                   "Der Katalysator beschleunigt und entzieht Wasser — beides erhöht die Ausbeute.",
                   visual=anim("veresterung", "C"))
    },
    "formelkarte": {"formeln": ["R–COOH + HO–R' ⇌ R–COO–R' + H₂O",
                               "CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O"],
                    "saetze": ["Säure + Alkohol ⇌ Ester + Wasser.",
                               "Die OH-Gruppe stammt aus der Säure, das H aus dem Alkohol.",
                               "Die Reaktion ist umkehrbar und stellt ein Gleichgewicht ein.",
                               "Konzentrierte Schwefelsäure katalysiert und entzieht Wasser."]},
    "tasks": [
        aufgabe("ES01-A1-001", "A", 1, "choice",
                "Was entsteht bei der Veresterung?",
                options=["ein Ester und Wasser", "nur ein Ester", "ein Salz"], answer=0,
                visual=anim("veresterung", "A"),
                hints=["Es entstehen zwei Produkte.", "Eines davon ist Wasser.", "Ester und Wasser."],
                solution="Aus Säure und Alkohol entstehen ein Ester und ein Molekül Wasser.",
                tags=["ester"], spiral=["K-REAK"]),
        aufgabe("ES01-A2-002", "A", 2, "choice",
                "Welche zwei Stoffe braucht man für eine Veresterung?",
                options=["eine Säure und einen Alkohol", "zwei Säuren", "zwei Alkohole"],
                answer=0,
                hints=["Der Name Ester kommt von Essigäther.", "Es sind zwei verschiedene Stoffklassen.", "Säure und Alkohol."],
                solution="Eine Carbonsäure und ein Alkohol reagieren zum Ester.",
                tags=["ester"], spiral=["K-ORG"]),
        aufgabe("ES01-A3-003", "A", 3, "choice",
                "Woher stammt das Wasserstoffatom im entstehenden Wasser?",
                options=["aus der OH-Gruppe des Alkohols", "aus der Säure", "aus der Luft"],
                answer=0, visual=anim("veresterung", "A"),
                hints=["Sieh dir die Animation an.",
                       "Der Alkohol gibt sein H ab.",
                       "Die Säure gibt die OH-Gruppe."],
                solution="Das Wasserstoffatom stammt aus der Hydroxylgruppe des Alkohols, die OH-Gruppe aus der Säure.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Die Säure liefert die OH-Gruppe, der Alkohol das H-Atom.",
                                   "edukt_produkt_vertauscht")],
                tags=["ester"], spiral=["K-REAK"]),
        aufgabe("ES01-A4-004", "A", 4, "choice",
                "Wozu wird konzentrierte Schwefelsäure zugesetzt?",
                options=["Sie beschleunigt die Reaktion und entzieht Wasser.",
                         "Sie liefert den Alkohol.", "Sie färbt den Ester."],
                answer=0,
                hints=["Sie wird nicht verbraucht.", "Sie wirkt als Katalysator.", "Und entzieht Wasser."],
                solution="Die konzentrierte Schwefelsäure wirkt als Katalysator und entzieht zugleich das entstehende Wasser — beides erhöht die Ausbeute.",
                tags=["ester"], spiral=["K-REAK"]),
        aufgabe("ES01-B1-005", "B", 1, "choice",
                "Wie heißt der Ester aus Essigsäure und Ethanol?",
                options=["Essigsäureethylester", "Ethansäuremethylester", "Ethylessigsäure"],
                answer=0,
                hints=["Erst die Säure nennen.",
                       "Dann den Alkoholrest.",
                       "Dann „ester“."],
                solution="Der Name folgt der Regel Säure + Alkoholrest + ester: Essigsäureethylester.",
                misconceptions=[fv("nomenklatur_falsch", 2,
                                   "Die Säure steht im Namen zuerst, der Alkoholrest danach.",
                                   "nomenklatur_falsch")],
                tags=["ester", "namen", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES01-B2-006", "B", 2, "choice",
                "Warum steht in der Gleichung der Veresterung ein Doppelpfeil?",
                options=["Die Reaktion ist umkehrbar; es stellt sich ein Gleichgewicht ein.",
                         "Weil zwei Produkte entstehen.",
                         "Weil zwei Edukte beteiligt sind."],
                answer=0,
                hints=["Können Ester und Wasser zurückreagieren?",
                       "Ja — das ist die Esterspaltung.",
                       "Deshalb der Doppelpfeil."],
                solution="Ester und Wasser reagieren zurück zu Säure und Alkohol. Es stellt sich ein Gleichgewicht ein — der Doppelpfeil zeigt das an.",
                tags=["ester", "bbr"], spiral=["K-REAK"]),
        aufgabe("ES01-B2-007", "B", 2, "choice",
                "Warum erhöht das Entziehen von Wasser die Ausbeute?",
                options=["Ohne Wasser kann die Rückreaktion nicht ablaufen; das Gleichgewicht verschiebt sich zum Ester.",
                         "Wasser verdünnt den Ester.",
                         "Wasser zerstört den Katalysator."],
                answer=0,
                hints=["Was braucht die Rückreaktion?",
                       "Ester und Wasser.",
                       "Fehlt eines, läuft sie nicht."],
                solution="Die Rückreaktion benötigt Wasser. Wird es entzogen, kann sie kaum ablaufen und das Gleichgewicht verschiebt sich zugunsten des Esters.",
                tags=["ester", "msa"], spiral=["K-REAK"]),
        aufgabe("ES01-B3-008", "B", 3, "choice",
                "Welche Bindung entsteht bei der Veresterung?",
                options=["die Esterbindung –COO–", "eine Ionenbindung", "eine Wasserstoffbrücke"],
                answer=0,
                hints=["Sie verbindet die beiden Reste.",
                       "Sie enthält zwei Sauerstoffatome.",
                       "–COO–."],
                solution="Zwischen den beiden Resten entsteht die Esterbindung –COO–.",
                misconceptions=[fv("bindungsart_verwechselt", 2,
                                   "Wasserstoffbrücken wirken zwischen Molekülen, nicht als Verknüpfung im Molekül.",
                                   "bindungsart_verwechselt")],
                tags=["ester", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES01-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Essigsäureethylester CH₃COOC₂H₅? (C = 12, H = 1, O = 16 g/mol)",
                answer=88, unit_label="g/mol", tolerance=1,
                hints=["4 C, 8 H, 2 O.",
                       "48 + 8 + 32.",
                       "88 g/mol."],
                solution="M = 4 · 12 + 8 · 1 + 2 · 16 = 48 + 8 + 32 = 88 g/mol",
                tags=["ester", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("ES01-B4-010", "B", 4, "choice",
                "Warum wird der Katalysator nicht verbraucht?",
                options=["Er geht aus der Reaktion unverändert hervor.",
                         "Er wird nur wenig eingesetzt.",
                         "Er verdampft."],
                answer=0,
                hints=["Was ist die Definition eines Katalysators?",
                       "Er beschleunigt und bleibt erhalten.",
                       "Unverändert."],
                solution="Ein Katalysator beschleunigt die Reaktion und liegt danach unverändert vor. Deshalb genügt eine kleine Menge für sehr viele Umsetzungen.",
                tags=["ester", "bbr"], spiral=["K-REAK"]),
        aufgabe("ES01-C2-011", "C", 2, "choice",
                "Warum erreicht die Veresterung ohne Wasserentzug nur rund zwei Drittel Umsatz?",
                options=["Hin- und Rückreaktion laufen gleich schnell, sobald sich das Gleichgewicht eingestellt hat.",
                         "Der Alkohol ist verbraucht.",
                         "Der Katalysator wirkt nicht mehr."],
                answer=0,
                hints=["Was passiert im Gleichgewicht?",
                       "Beide Richtungen laufen gleich schnell.",
                       "Von außen scheint sich nichts mehr zu ändern."],
                solution="Im Gleichgewicht laufen Hin- und Rückreaktion gleich schnell — die Mengen ändern sich nicht mehr. Beide Stoffe sind weiterhin vorhanden, die Reaktion ist nur nicht mehr sichtbar.",
                tags=["ester", "msa"], spiral=["K-REAK"]),
        aufgabe("ES01-C3-012", "C", 3, "multi",
                "60 g Essigsäure (M = 60 g/mol) reagieren mit Ethanol zu Essigsäureethylester (M = 88 g/mol). Die Ausbeute beträgt 65 %.",
                fields=[
                    {"label": "Stoffmenge der Säure", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "theoretische Estermasse", "answer": 88, "unit_label": "g", "tolerance": 2},
                    {"label": "tatsächliche Estermasse", "answer": 57.2, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 60 : 60 = 1 mol.",
                       "1 : 1 zum Ester → 88 g.",
                       "88 · 0,65."],
                solution="n = 1 mol → theoretisch 88 g\ntatsächlich: 88 · 0,65 = 57,2 g",
                tags=["ester", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("ES01-C3-013", "C", 3, "choice",
                "Wie ließe sich die Ausbeute außer durch Wasserentzug noch erhöhen?",
                options=["Einen der beiden Ausgangsstoffe im Überschuss einsetzen.",
                         "Die Temperatur senken.",
                         "Mehr Katalysator zugeben."],
                answer=0,
                hints=["Was verschiebt ein Gleichgewicht?",
                       "Eine Änderung der Mengen.",
                       "Ein Überschuss eines Edukts."],
                solution="Ein Überschuss eines Ausgangsstoffs verschiebt das Gleichgewicht zur Produktseite. Mehr Katalysator beschleunigt nur, verschiebt aber nichts — die Gleichgewichtslage bleibt.",
                misconceptions=[fv("katalysator_verschiebt_gleichgewicht", 2,
                                   "Ein Katalysator beschleunigt beide Richtungen gleichermaßen und verschiebt das Gleichgewicht nicht.")],
                tags=["ester", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("ES01-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Das Wasser bei der Veresterung stammt aus dem Alkohol.“ Wie korrigierst du?",
                options=["Nur das Wasserstoffatom — die OH-Gruppe stammt aus der Säure.",
                         "Richtig, es stammt vollständig aus dem Alkohol.",
                         "Falsch, es stammt vollständig aus der Säure."],
                answer=0,
                visual=anim("veresterung", "C"),
                hints=["Ein Wassermolekül besteht aus OH und H.",
                       "Beide stammen aus verschiedenen Molekülen.",
                       "OH aus der Säure, H aus dem Alkohol."],
                solution="Das Wassermolekül wird aus zwei Quellen gebildet: Die OH-Gruppe stammt aus der Carboxygruppe der Säure, das Wasserstoffatom aus der Hydroxylgruppe des Alkohols. Der Nachweis gelingt mit markiertem Sauerstoff.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Nur das H-Atom stammt aus dem Alkohol, die OH-Gruppe aus der Säure.",
                                   "edukt_produkt_vertauscht")],
                tags=["ester", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

if __name__ == "__main__":
    schreiben("os", OS, "Bereich OS · Einheiten 4 und 5")
    schreiben("es", ES, "Bereich ES · Einheit 1")
