# -*- coding: utf-8 -*-
"""Bereich SZ · Salze — SZ-02 und SZ-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "SZ-02",
    "title": "Das Ionengitter",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.3"],
    "klasse": 8,
    "wortspeicher": ["das Ionengitter", "die Ionenbindung", "die Gitterenergie", "spröde",
                     "der Kristall", "die Formeleinheit"],
    "worterklaerungen": {
        "Ionengitter": "Eine regelmäßige Anordnung aus positiven und negativen Ionen.",
        "Ionenbindung": "Die Anziehung zwischen entgegengesetzt geladenen Ionen.",
        "spröde": "Bricht bei Belastung, statt sich zu verformen.",
        "Formeleinheit": "Das kleinste Zahlenverhältnis der Ionen. Ein Salzmolekül gibt es nicht."
    },
    "can_do": {
        "A": "Ich beschreibe den Aufbau eines Salzkristalls und nenne zwei Eigenschaften von Salzen.",
        "B": "Ich erkläre Härte, Sprödigkeit und hohe Schmelztemperatur mit dem Ionengitter.",
        "C": "Ich begründe, warum es keine Salzmoleküle gibt, und vergleiche Ionen- und Molekülsubstanzen."
    },
    "lernkarten": {
        "A": karte("Ordnung im Kristall",
                   "Im Salz sitzen die Ionen in einem Gitter.",
                   ["Positive und negative Ionen wechseln sich ab.", "Sie halten sich gegenseitig fest."],
                   "Ungleiche Ladungen ziehen sich an — das hält den Kristall zusammen.",
                   visual=anim("ionengitter", "A"),
                   beispiel={"titel": "Kochsalz", "aufgabe": "Wie sieht ein Kochsalzkristall aus?",
                             "schritte": ["Er ist würfelförmig.",
                                          "Innen wechseln sich Na⁺ und Cl⁻ ab."],
                             "ergebnis": "Ein regelmäßiges Gitter."}),
        "B": karte("Eigenschaften aus dem Gitter",
                   "Alle typischen Eigenschaften der Salze folgen aus einer Sache: der starken Anziehung zwischen entgegengesetzt geladenen Ionen im Gitter.",
                   ["Hart und hochschmelzend: Die Anziehung ist stark. Kochsalz schmilzt erst bei 801 °C.",
                    "Spröde: Verschiebt man eine Schicht, treffen gleiche Ladungen aufeinander und stoßen sich ab — der Kristall springt. Ein Metall verformt sich stattdessen.",
                    "Fest nicht leitend, gelöst oder geschmolzen leitend: Erst dann sind die Ionen beweglich.",
                    "Die Energie, die zum Auseinandernehmen des Gitters nötig ist, heißt Gitterenergie."],
                   "Starke Anziehung im Gitter erklärt hart, spröde, hochschmelzend und die Leitfähigkeit.",
                   visual=anim("ionengitter", "B")),
        "C": karte("Warum es keine Salzmoleküle gibt",
                   "„NaCl“ sieht aus wie eine Molekülformel, ist aber keine. Der Unterschied ist keine Spitzfindigkeit, sondern betrifft den Aufbau des Stoffes.",
                   ["Im Kristall ist jedes Na⁺ von sechs Cl⁻ umgeben und umgekehrt. Kein Ion gehört zu einem bestimmten Partner.",
                    "NaCl ist deshalb eine Verhältnisformel: Sie nennt das Zahlenverhältnis 1 : 1, nicht den Bau eines Teilchens.",
                    "Bei Molekülsubstanzen wie H₂O ist es anders: Dort gehören genau zwei H-Atome zu einem O-Atom, und diese Einheit bleibt beim Verdampfen erhalten.",
                    "Deshalb sind die Schmelztemperaturen so verschieden: Beim Salz muss ein durchgehendes Gitter aufgebrochen werden, beim Wasser nur Anziehung zwischen fertigen Molekülen."],
                   "Salze bestehen aus Ionengittern, nicht aus Molekülen. NaCl nennt ein Verhältnis.",
                   visual=anim("ionengitter", "C"))
    },
    "formelkarte": {"formeln": ["NaCl · MgO · CaCl₂ · Al₂O₃"],
                    "saetze": ["Ionenbindung: Anziehung zwischen positiven und negativen Ionen.",
                               "Salze sind hart, spröde und hochschmelzend.",
                               "Fest nicht leitend — gelöst und geschmolzen leitend.",
                               "Salzformeln sind Verhältnisformeln, keine Molekülformeln."]},
    "tasks": [
        aufgabe("SZ02-A1-001", "A", 1, "choice",
                "Was hält die Ionen im Salzkristall zusammen?",
                options=["Die Anziehung zwischen positiven und negativen Ionen.",
                         "Gemeinsame Elektronenpaare.", "Nichts, sie liegen nur nebeneinander."],
                answer=0, visual=anim("ionengitter", "A"),
                hints=["Welche Ladungen sind im Kristall?", "Positive und negative.", "Ungleiche Ladungen ziehen sich an."],
                solution="Positive und negative Ionen ziehen sich an. Diese Anziehung heißt Ionenbindung.",
                misconceptions=[fv("bindungsart_verwechselt", 1,
                                   "Gemeinsame Elektronenpaare gibt es zwischen Nichtmetallen. Bei Salzen wirkt die Anziehung zwischen Ionen.",
                                   "bindungsart_verwechselt")],
                tags=["salze"], spiral=["W-TEIL"]),
        aufgabe("SZ02-A2-002", "A", 2, "choice",
                "Welche Eigenschaft haben Salze?",
                options=["Sie sind hart und spröde.", "Sie sind weich und biegsam.", "Sie sind flüssig."],
                answer=0,
                hints=["Denk an einen Kochsalzkristall.", "Er lässt sich nicht biegen.", "Er zerbricht."],
                solution="Salze sind hart und spröde: Sie lassen sich nicht verformen, sondern zerbrechen.",
                tags=["salze"], spiral=["W-STOF"]),
        aufgabe("SZ02-A3-003", "A", 3, "choice",
                "Leitet festes Kochsalz den elektrischen Strom?",
                options=["Nein — die Ionen sind im Gitter nicht beweglich.",
                         "Ja — es enthält Ionen.", "Nur bei Wärme."],
                answer=0, visual=anim("ionengitter", "A"),
                hints=["Ionen sind da — aber können sie sich bewegen?",
                       "Im Gitter nicht.",
                       "Ohne Bewegung kein Strom."],
                solution="Ionen sind vorhanden, sitzen aber auf festen Plätzen. Erst gelöst oder geschmolzen sind sie beweglich und leiten.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Ionen allein genügen nicht — sie müssen beweglich sein.",
                                   "ion_und_atom_verwechselt")],
                tags=["salze"], spiral=["W-LOES"]),
        aufgabe("SZ02-A4-004", "A", 4, "numeric",
                "Kochsalz schmilzt bei 801 °C, Eis bei 0 °C. Wie groß ist der Unterschied?",
                answer=801, unit_label="°C", tolerance=0,
                hints=["801 − 0.", "Der Unterschied ist die Differenz.", "801 °C."],
                solution="801 °C − 0 °C = 801 °C. Der große Unterschied zeigt, wie stark die Anziehung im Ionengitter ist.",
                tags=["salze", "rechnen"], spiral=["W-EINH"]),
        aufgabe("SZ02-B1-005", "B", 1, "choice",
                "Warum sind Salze spröde?",
                options=["Beim Verschieben treffen gleiche Ladungen aufeinander und stoßen sich ab.",
                         "Sie enthalten Luftblasen.", "Sie sind zu leicht."],
                answer=0, visual=anim("ionengitter", "B"),
                hints=["Was passiert, wenn eine Schicht verschoben wird?",
                       "Positiv trifft auf positiv.",
                       "Gleiche Ladungen stoßen sich ab."],
                solution="Verschiebt man eine Gitterschicht um einen Platz, stehen sich plötzlich gleiche Ladungen gegenüber. Die Abstoßung sprengt den Kristall — er springt statt sich zu verformen.",
                tags=["salze", "bbr"], spiral=["W-TEIL"]),
        aufgabe("SZ02-B2-006", "B", 2, "choice",
                "Warum schmelzen Salze erst bei sehr hohen Temperaturen?",
                options=["Die Anziehung zwischen den Ionen ist sehr stark und muss überwunden werden.",
                         "Salze sind besonders schwer.",
                         "Salze enthalten kein Wasser."],
                answer=0,
                hints=["Was muss beim Schmelzen überwunden werden?",
                       "Die Anziehung im Gitter.",
                       "Sie ist bei Ionen sehr stark."],
                solution="Zum Schmelzen müssen die Ionen aus ihren Gitterplätzen gelöst werden. Die elektrische Anziehung zwischen ihnen ist sehr stark — dafür braucht es viel Energie.",
                tags=["salze", "bbr"], spiral=["W-STOF"]),
        aufgabe("SZ02-B2-007", "B", 2, "choice",
                "Wann leitet ein Salz den elektrischen Strom?",
                options=["Gelöst oder geschmolzen.", "Nur im festen Zustand.", "Nie."],
                answer=0, visual=anim("ionengitter", "B"),
                hints=["Wann sind die Ionen beweglich?",
                       "Wenn das Gitter aufgelöst ist.",
                       "Also gelöst oder geschmolzen."],
                solution="Erst wenn das Gitter aufgelöst ist — durch Lösen in Wasser oder durch Schmelzen — sind die Ionen beweglich und transportieren Ladung.",
                tags=["salze", "bbr"], spiral=["W-LOES"]),
        aufgabe("SZ02-B3-008", "B", 3, "choice",
                "Ein Metall lässt sich verbiegen, ein Salzkristall zerspringt. Worin liegt der Unterschied?",
                options=["Im Metall bleiben nach dem Verschieben Rümpfe im Elektronengas; im Salz treffen gleiche Ladungen aufeinander.",
                         "Metalle sind weicher.",
                         "Salze sind schwerer."],
                answer=0,
                hints=["Was liegt zwischen den Teilchen im Metall?",
                       "Frei bewegliche Elektronen.",
                       "Sie halten die Bindung auch nach dem Verschieben."],
                solution="Im Metallgitter umgibt das Elektronengas alle Rümpfe gleichmäßig — nach dem Verschieben passt alles wieder. Im Ionengitter zerstört dieselbe Verschiebung die Ordnung aus abwechselnden Ladungen.",
                tags=["salze", "msa"], spiral=["W-TEIL"]),
        aufgabe("SZ02-B3-009", "B", 3, "numeric",
                "In einem Kochsalzgitter ist jedes Natrium-Ion von wie vielen Chlorid-Ionen umgeben?",
                answer=6, tolerance=0,
                hints=["Denk an die sechs Richtungen im Raum.",
                       "Oben, unten, links, rechts, vorn, hinten.",
                       "6."],
                solution="Jedes Na⁺ ist von sechs Cl⁻ umgeben und umgekehrt. Genau deshalb gibt es keine Paare und damit keine Moleküle.",
                tags=["salze", "msa"], spiral=["W-TEIL"]),
        aufgabe("SZ02-B4-010", "B", 4, "choice",
                "Was bedeutet die Formel NaCl?",
                options=["Auf ein Natrium-Ion kommt ein Chlorid-Ion.",
                         "Ein Natriumatom ist an ein Chloratom gebunden.",
                         "Ein Molekül aus Na und Cl."],
                answer=0,
                hints=["Gibt es im Salz einzelne Teilchen aus Na und Cl?",
                       "Nein — jedes Ion hat sechs Nachbarn.",
                       "Die Formel nennt ein Verhältnis."],
                solution="NaCl ist eine Verhältnisformel: Sie sagt, dass Natrium- und Chlorid-Ionen im Verhältnis 1 : 1 vorliegen. Ein NaCl-Molekül gibt es nicht.",
                misconceptions=[fv("summenformel_falsch_gelesen", 2,
                                   "Ein Salzmolekül gibt es nicht. Die Formel nennt das Zahlenverhältnis im Gitter.",
                                   "summenformel_falsch_gelesen", 1)],
                tags=["salze", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ02-C2-011", "C", 2, "choice",
                "Warum schmilzt Magnesiumoxid (2852 °C) deutlich höher als Kochsalz (801 °C)?",
                options=["Die Ionen tragen zweifache Ladungen; die Anziehung ist dadurch viel stärker.",
                         "Magnesiumoxid ist schwerer.",
                         "Magnesiumoxid hat mehr Ionen im Gitter."],
                answer=0,
                hints=["Vergleiche die Ladungen: Na⁺Cl⁻ gegen Mg²⁺O²⁻.",
                       "Zweifach statt einfach.",
                       "Die Anziehung wächst mit dem Produkt der Ladungen."],
                solution="In NaCl stehen sich einfach geladene Ionen gegenüber, in MgO zweifach geladene. Die Anziehung ist dadurch etwa viermal so stark — das erklärt die weit höhere Schmelztemperatur.",
                tags=["salze", "msa"], spiral=["W-TEIL"]),
        aufgabe("SZ02-C3-012", "C", 3, "choice",
                "Warum ist der Vergleich „Salz besteht aus NaCl-Molekülen“ irreführend?",
                options=["Jedes Ion hat sechs gleichberechtigte Nachbarn — es gibt keine abgegrenzten Teilcheneinheiten.",
                         "Weil NaCl gar nicht existiert.",
                         "Weil Moleküle immer aus drei Atomen bestehen."],
                answer=0,
                hints=["Wie viele Nachbarn hat ein Ion?",
                       "Sechs.",
                       "Zu welchem davon soll es gehören?"],
                solution="Ein Molekül ist eine abgegrenzte Einheit. Im Ionengitter hat jedes Ion sechs gleichberechtigte Nachbarn, keiner ist ausgezeichnet. Deshalb lässt sich kein Teilchen abgrenzen — der Kristall selbst ist die Einheit.",
                tags=["salze", "msa"], spiral=["W-SYMB"]),
        aufgabe("SZ02-C3-013", "C", 3, "multi",
                "Vergleiche Kochsalz (Schmelztemperatur 801 °C) und Wasser (0 °C).",
                fields=[
                    {"label": "Temperaturunterschied", "answer": 801, "unit_label": "°C", "tolerance": 1},
                    {"label": "Um welchen Faktor ist die Schmelztemperatur von MgO (2852 °C) höher als die von NaCl?", "answer": 3.56, "tolerance": 0.1}
                ],
                hints=["Erst die Differenz.",
                       "Dann 2852 : 801.",
                       "Rund 3,6."],
                solution="801 °C − 0 °C = 801 °C\n2852 : 801 = 3,56\nBeide Zahlen zeigen: Ionengitter halten weit stärker zusammen als Molekülverbände.",
                tags=["salze", "rechnen", "msa"], spiral=["W-EINH"]),
        aufgabe("SZ02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Wenn Salz schmilzt, zerfallen die Ionen in Atome.“ Wie bewertest du das?",
                options=["Falsch — beim Schmelzen wird nur das Gitter aufgelöst; die Ionen bleiben Ionen und leiten deshalb den Strom.",
                         "Richtig — beim Schmelzen entstehen Atome.",
                         "Falsch — Salz schmilzt gar nicht."],
                answer=0,
                hints=["Was zeigt die Leitfähigkeit der Schmelze?",
                       "Dass geladene Teilchen vorhanden sind.",
                       "Also Ionen, keine Atome."],
                solution="Schmelzen ist eine Zustandsänderung: Das Gitter löst sich auf, die Ionen werden beweglich. Dass die Schmelze den Strom leitet, beweist, dass es weiterhin Ionen sind — Atome wären ungeladen.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 1,
                                   "Beim Schmelzen findet keine chemische Reaktion statt. Die Ionen bleiben erhalten.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["salze", "bewerten", "msa"], spiral=["W-STOF"])
    ]
})

E.append({
    "unit": "SZ-03",
    "title": "Verhältnisformeln aufstellen",
    "leitidee": "B1",
    "standards": ["K1", "K2.4", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["die Verhältnisformel", "der Ladungsausgleich", "das Kation", "das Anion",
                     "die Formeleinheit", "die Nomenklatur"],
    "worterklaerungen": {
        "Verhältnisformel": "Sie nennt das kleinste Zahlenverhältnis der Ionen in einem Salz.",
        "Ladungsausgleich": "Positive und negative Ladungen müssen sich zu null ergänzen."
    },
    "can_do": {
        "A": "Ich stelle die Formel eines Salzes aus zwei einfach geladenen Ionen auf.",
        "B": "Ich gleiche unterschiedliche Ladungen aus und benenne das Salz korrekt.",
        "C": "Ich stelle Formeln mit mehratomigen Ionen auf und begründe die Klammersetzung."
    },
    "lernkarten": {
        "A": karte("Plus und Minus müssen sich ausgleichen",
                   "Ein Salz ist nach außen ungeladen.",
                   ["Die positiven und negativen Ladungen heben sich auf.",
                    "Bei 1+ und 1− kommt auf jedes Ion genau eines."],
                   "Die Summe der Ladungen muss null ergeben.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "ionen",
                           "alt": "Ionengitter aus abwechselnd positiven und negativen Ionen."},
                   beispiel={"titel": "Kochsalz", "aufgabe": "Na⁺ und Cl⁻ — welche Formel?",
                             "schritte": ["1+ und 1− gleichen sich aus.",
                                          "Also je ein Ion."],
                             "ergebnis": "NaCl"}),
        "B": karte("Wenn die Ladungen verschieden sind",
                   "Sind die Ladungen unterschiedlich groß, braucht es mehr Ionen der einen Sorte. Die Regel dafür ist einfach und immer gleich.",
                   ["Schreibe beide Ionen mit ihrer Ladung auf: Ca²⁺ und Cl⁻.",
                    "Frage: Wie viele von jedem, damit die Summe null ergibt? Eine 2+ braucht zwei 1−.",
                    "Ergebnis: CaCl₂. Die Zahl steht als Index hinter dem Ion.",
                    "Der Name nennt zuerst das Metall, dann das Nichtmetall mit der Endung -id: Calciumchlorid."],
                   "Über Kreuz: Die Ladungszahl des einen wird zum Index des anderen — danach kürzen.",
                   visual=anim("ionenbildung", "B")),
        "C": karte("Mehratomige Ionen und Klammern",
                   "Manche Ionen bestehen aus mehreren Atomen und bleiben als Einheit erhalten. Sobald mehrere davon gebraucht werden, ist eine Klammer nötig.",
                   ["Häufige mehratomige Ionen: Sulfat SO₄²⁻, Nitrat NO₃⁻, Carbonat CO₃²⁻, Hydroxid OH⁻, Ammonium NH₄⁺.",
                    "Werden zwei davon gebraucht, kommt die Klammer: Ca(OH)₂ bedeutet ein Calcium-Ion und zwei Hydroxid-Ionen.",
                    "Ohne Klammer stünde CaOH₂ — das wären ein O und zwei H, also etwas anderes.",
                    "Nach dem Ausgleich wird gekürzt: Mg²⁺ und O²⁻ ergeben nicht Mg₂O₂, sondern MgO. Eine Verhältnisformel nennt immer das kleinste Verhältnis."],
                   "Klammer, sobald ein mehratomiges Ion mehrfach vorkommt. Am Ende kürzen.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "ionen",
                           "alt": "Ionengitter mit abwechselnden Ladungen."})
    },
    "formelkarte": {"formeln": ["NaCl · MgO · CaCl₂ · Al₂O₃ · Na₂SO₄ · Ca(OH)₂ · NH₄NO₃"],
                    "saetze": ["Die Summe aller Ladungen muss null ergeben.",
                               "Über Kreuz: Ladungszahl des einen wird Index des anderen — dann kürzen.",
                               "Klammer, wenn ein mehratomiges Ion mehrfach vorkommt.",
                               "Ionen: SO₄²⁻ Sulfat · NO₃⁻ Nitrat · CO₃²⁻ Carbonat · OH⁻ Hydroxid · NH₄⁺ Ammonium."]},
    "tasks": [
        aufgabe("SZ03-A1-001", "A", 1, "choice",
                "Na⁺ und Cl⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["NaCl", "Na₂Cl", "NaCl₂"], answer=0,
                hints=["1+ und 1− gleichen sich aus.", "Also je ein Ion.", "NaCl."],
                solution="Eine positive und eine negative Ladung heben sich auf: NaCl.",
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("SZ03-A2-002", "A", 2, "choice",
                "K⁺ und Br⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["KBr", "K₂Br", "KBr₂"], answer=0,
                hints=["Beide sind einfach geladen.", "Je ein Ion genügt.", "KBr."],
                solution="1+ und 1− gleichen sich aus: KBr, Kaliumbromid.",
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("SZ03-A3-003", "A", 3, "numeric",
                "Ca²⁺ und Cl⁻: Wie viele Chlorid-Ionen gehören zu einem Calcium-Ion?",
                answer=2, tolerance=0,
                hints=["Zwei positive Ladungen müssen ausgeglichen werden.",
                       "Jedes Cl⁻ bringt eine negative.",
                       "Also zwei."],
                solution="Ca²⁺ trägt zwei positive Ladungen. Es braucht zwei Cl⁻: CaCl₂.",
                misconceptions=[fv("ladung_unvollstaendig", 1,
                                   "Ein Cl⁻ gleicht nur eine der beiden positiven Ladungen aus.",
                                   "ladung_unvollstaendig")],
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("SZ03-A4-004", "A", 4, "choice",
                "Wie heißt die Verbindung aus Natrium und Chlor?",
                options=["Natriumchlorid", "Chlornatrium", "Natriumchlor"], answer=0,
                hints=["Zuerst das Metall.", "Dann das Nichtmetall mit -id.", "Natriumchlorid."],
                solution="Zuerst das Metall, dann das Nichtmetall mit der Endung -id: Natriumchlorid.",
                misconceptions=[fv("nomenklatur_falsch", 2,
                                   "Das Nichtmetall bekommt die Endung -id: Chlorid, nicht Chlor.",
                                   "nomenklatur_falsch")],
                tags=["formeln", "namen"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B1-005", "B", 1, "choice",
                "Mg²⁺ und O²⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["MgO", "Mg₂O₂", "MgO₂"], answer=0,
                hints=["Beide Ladungen sind zweifach.", "Sie gleichen sich direkt aus.", "Und dann wird gekürzt."],
                solution="2+ und 2− gleichen sich direkt aus. Mg₂O₂ wäre nicht falsch gerechnet, aber eine Verhältnisformel nennt das kleinste Verhältnis: MgO.",
                misconceptions=[fv("nicht_gekuerzt", 1,
                                   "Richtig ausgeglichen, aber nicht gekürzt. Eine Verhältnisformel nennt das kleinste Verhältnis.",
                                   "summenformel_falsch_gelesen")],
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B2-006", "B", 2, "choice",
                "Al³⁺ und O²⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["Al₂O₃", "AlO", "Al₃O₂"], answer=0,
                hints=["Suche das kleinste gemeinsame Vielfache von 3 und 2.",
                       "Das ist 6.",
                       "Zwei Al³⁺ ergeben 6+, drei O²⁻ ergeben 6−."],
                solution="2 · (3+) = 6+ und 3 · (2−) = 6−. Die Formel lautet Al₂O₃, Aluminiumoxid.",
                misconceptions=[fv("ladung_unvollstaendig", 2,
                                   "Über Kreuz: die Ladungszahl des einen wird zum Index des anderen — also Al₂O₃, nicht Al₃O₂.",
                                   "ladung_unvollstaendig")],
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B2-007", "B", 2, "choice",
                "Na⁺ und SO₄²⁻ bilden ein Salz. Wie lautet die Formel?",
                options=["Na₂SO₄", "NaSO₄", "Na(SO₄)₂"], answer=0,
                hints=["Sulfat trägt zwei negative Ladungen.",
                       "Es braucht zwei Na⁺.",
                       "Na₂SO₄."],
                solution="SO₄²⁻ braucht zwei Na⁺ zum Ausgleich: Na₂SO₄, Natriumsulfat. Eine Klammer ist nicht nötig, weil das Sulfat nur einmal vorkommt.",
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B3-008", "B", 3, "choice",
                "Ca²⁺ und OH⁻ bilden ein Salz. Warum schreibt man Ca(OH)₂ und nicht CaOH₂?",
                options=["Die Klammer zeigt, dass zwei ganze OH-Einheiten gemeint sind.",
                         "Die Klammer ist nur Schmuck.",
                         "CaOH₂ wäre auch richtig."],
                answer=0,
                hints=["Was würde CaOH₂ bedeuten?",
                       "Ein O und zwei H.",
                       "Gemeint sind aber zwei OH."],
                solution="Ca(OH)₂ bedeutet zwei Hydroxid-Ionen, also zwei O und zwei H. CaOH₂ hieße ein O und zwei H — ein anderer Stoff. Die Klammer ist keine Formalität.",
                misconceptions=[fv("klammer_ignoriert", 2,
                                   "Ohne Klammer gilt der Index nur für das H. Gemeint sind zwei vollständige OH-Ionen.",
                                   "summenformel_falsch_gelesen")],
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B3-009", "B", 3, "assign",
                "Ordne jedem Ion seinen Namen zu.",
                slots=["SO₄²⁻", "NO₃⁻", "CO₃²⁻"],
                values=["Sulfat", "Nitrat", "Carbonat"], answer=[0, 1, 2],
                hints=["Alle drei enthalten Sauerstoff.",
                       "Schwefel → Sulfat.",
                       "Stickstoff → Nitrat."],
                solution="SO₄²⁻ Sulfat, NO₃⁻ Nitrat, CO₃²⁻ Carbonat.",
                tags=["formeln", "namen", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-B4-010", "B", 4, "multi",
                "Stelle die Formeln auf.",
                fields=[
                    {"label": "Zahl der Cl⁻ in der Verbindung mit Al³⁺", "answer": 3, "tolerance": 0},
                    {"label": "Zahl der Na⁺ in der Verbindung mit O²⁻", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der NO₃⁻ in der Verbindung mit Ca²⁺", "answer": 2, "tolerance": 0}
                ],
                hints=["Die Summe der Ladungen muss null sein.",
                       "Al³⁺ braucht drei einfach negative Ionen.",
                       "Ca²⁺ braucht zwei Nitrat-Ionen."],
                solution="AlCl₃ · Na₂O · Ca(NO₃)₂ — beim letzten ist die Klammer nötig, weil das Nitrat zweimal vorkommt.",
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SZ03-C2-011", "C", 2, "choice",
                "Warum wird Mg₂O₂ zu MgO gekürzt, Al₂O₃ aber nicht weiter?",
                options=["Eine Verhältnisformel nennt das kleinste ganzzahlige Verhältnis; 2 : 3 lässt sich nicht kürzen.",
                         "Weil Al₂O₃ ein Molekül ist.",
                         "Weil Aluminium ein Metall ist."],
                answer=0,
                hints=["Lässt sich 2 : 2 kürzen?",
                       "Ja, zu 1 : 1.",
                       "2 : 3 dagegen nicht."],
                solution="2 : 2 lässt sich zu 1 : 1 kürzen, deshalb MgO. Das Verhältnis 2 : 3 ist bereits das kleinste ganzzahlige — Al₂O₃ bleibt stehen.",
                tags=["formeln", "msa"], spiral=["W-SYMB"]),
        aufgabe("SZ03-C3-012", "C", 3, "multi",
                "Bestimme für Aluminiumsulfat aus Al³⁺ und SO₄²⁻.",
                fields=[
                    {"label": "Zahl der Al³⁺", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der SO₄²⁻", "answer": 3, "tolerance": 0},
                    {"label": "Zahl der Sauerstoffatome in der Formeleinheit", "answer": 12, "tolerance": 0}
                ],
                hints=["Kleinstes gemeinsames Vielfaches von 3 und 2 ist 6.",
                       "Zwei Al³⁺ und drei SO₄²⁻.",
                       "3 · 4 = 12 Sauerstoffatome."],
                solution="Al₂(SO₄)₃\n2 · 3+ = 6+, 3 · 2− = 6−\nSauerstoff: 3 · 4 = 12 Atome",
                tags=["formeln", "msa"], spiral=["W-SYMB"]),
        aufgabe("SZ03-C3-013", "C", 3, "choice",
                "Wie heißt die Verbindung Fe₂O₃, wenn Eisen darin dreifach positiv geladen ist?",
                options=["Eisen(III)-oxid", "Eisenoxid", "Dieisentrioxid"], answer=0,
                hints=["Eisen kann verschiedene Ladungen bilden.",
                       "Deshalb wird sie im Namen angegeben.",
                       "In römischen Ziffern."],
                solution="Weil Eisen mehrere Ionenladungen bilden kann, wird die Ladung im Namen angegeben: Eisen(III)-oxid. „Eisenoxid“ wäre nicht eindeutig — es gäbe auch Eisen(II)-oxid.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Bei Metallen mit mehreren möglichen Ladungen muss die Ladung im Namen stehen.",
                                   "nomenklatur_falsch")],
                tags=["formeln", "namen", "msa"], spiral=["W-SYMB"]),
        aufgabe("SZ03-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt für Calciumchlorid „Ca₂Cl“. Wo liegt der Denkfehler?",
                options=["Er hat die Ladungszahlen vertauscht — die Zahl des einen Ions wird zum Index des anderen.",
                         "Nichts, die Formel ist richtig.",
                         "Er hat die Klammer vergessen."],
                answer=0,
                hints=["Ca²⁺ und Cl⁻.",
                       "Wie viele Cl⁻ braucht ein Ca²⁺?",
                       "Zwei — die 2 gehört ans Chlorid."],
                solution="Ca²⁺ trägt zwei positive Ladungen und braucht zwei Cl⁻: CaCl₂. In Ca₂Cl stünden vier positive gegen eine negative Ladung — der Ausgleich stimmt nicht.",
                misconceptions=[fv("ladung_unvollstaendig", 1,
                                   "Prüfe die Ladungssumme: 2 · (2+) und 1 · (1−) ergeben nicht null.",
                                   "ladung_unvollstaendig")],
                tags=["formeln", "bewerten", "msa"], spiral=["W-SYMB"])
    ]
})

if __name__ == "__main__":
    schreiben("sz", E, "Bereich SZ · Einheiten 2 und 3")
