# -*- coding: utf-8 -*-
"""Bereich ME · Metalle — ME-03 bis ME-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ME-03",
    "title": "Edle und unedle Metalle",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.3"],
    "klasse": 8,
    "wortspeicher": ["edel", "unedel", "die Redoxreihe", "die Korrosion",
                     "die Reaktionsfähigkeit", "der Rost"],
    "worterklaerungen": {
        "edel": "Reagiert kaum mit Sauerstoff oder Säuren. Gold und Silber sind edel.",
        "unedel": "Reagiert leicht. Gibt Elektronen bereitwillig ab.",
        "Redoxreihe": "Eine Reihenfolge der Metalle nach ihrer Bereitschaft, Elektronen abzugeben."
    },
    "can_do": {
        "A": "Ich unterscheide edle und unedle Metalle an Beispielen.",
        "B": "Ich nutze die Redoxreihe, um vorherzusagen, ob eine Reaktion abläuft.",
        "C": "Ich begründe Korrosionsschutzverfahren mit der Stellung in der Redoxreihe."
    },
    "lernkarten": {
        "A": karte("Edel und unedel",
                   "Manche Metalle reagieren leicht, andere kaum.",
                   ["Gold bleibt jahrhundertelang blank.", "Eisen rostet schon nach Tagen."],
                   "Edel = reagiert kaum. Unedel = reagiert leicht.",
                   visual=anim("redox", "A"),
                   beispiel={"titel": "Zwei Nägel", "aufgabe": "Ein Eisennagel und ein Goldring liegen im Freien.",
                             "schritte": ["Der Nagel rostet.", "Der Ring bleibt blank."],
                             "ergebnis": "Eisen ist unedel, Gold edel."}),
        "B": karte("Die Redoxreihe nutzen",
                   "Die Metalle lassen sich nach ihrer Bereitschaft ordnen, Elektronen abzugeben. Diese Reihe sagt vorher, welche Reaktion abläuft und welche nicht.",
                   ["Reihenfolge von unedel nach edel: Kalium, Calcium, Natrium, Magnesium, Aluminium, Zink, Eisen, Blei, Kupfer, Silber, Gold.",
                    "Regel: Das unedlere Metall gibt Elektronen ab und geht in Lösung. Das edlere scheidet sich ab.",
                    "Ein Eisennagel in Kupfersulfatlösung überzieht sich mit Kupfer. Umgekehrt passiert nichts: Kupfer ist edler als Eisen.",
                    "Unedle Metalle reagieren auch mit Säuren unter Wasserstoffentwicklung — edle nicht."],
                   "Das unedlere Metall gibt ab. Umgekehrt läuft die Reaktion nicht.",
                   visual=anim("redox", "B")),
        "C": karte("Korrosion und Schutz",
                   "Aus derselben Reihe folgt, wie sich Eisen vor dem Rosten schützen lässt — und warum ausgerechnet ein unedleres Metall hilft.",
                   ["Passiver Schutz: Lack, Fett oder Kunststoff halten Wasser und Sauerstoff ab. Wird die Schicht verletzt, rostet es dort weiter.",
                    "Aktiver Schutz: Ein unedleres Metall wie Zink wird als Opferanode aufgebracht. Es gibt seine Elektronen bevorzugt ab und schützt das Eisen — auch an einer Kratzstelle.",
                    "Verzinktes Blech rostet deshalb selbst dann nicht, wenn es beschädigt ist. Verzinntes Blech dagegen rostet an der Kratzstelle schneller: Zinn ist edler als Eisen.",
                    "Aluminium schützt sich selbst: Seine Oxidschicht ist dicht und haftet fest, anders als der poröse Rost auf Eisen."],
                   "Ein unedleres Metall schützt, ein edleres beschleunigt die Korrosion.",
                   visual=anim("redox", "C"))
    },
    "formelkarte": {"formeln": ["Fe + Cu²⁺ → Fe²⁺ + Cu",
                               "Zn + 2 HCl → ZnCl₂ + H₂"],
                    "saetze": ["Redoxreihe: K · Ca · Na · Mg · Al · Zn · Fe · Pb · Cu · Ag · Au.",
                               "Links unedel, rechts edel.",
                               "Das unedlere Metall gibt Elektronen ab und geht in Lösung.",
                               "Unedle Metalle reagieren mit Säuren zu Wasserstoff.",
                               "Opferanode: ein unedleres Metall schützt das edlere."]},
    "tasks": [
        aufgabe("ME03-A1-001", "A", 1, "choice",
                "Welches Metall ist edel?",
                options=["Gold", "Eisen", "Magnesium"], answer=0,
                hints=["Edle Metalle reagieren kaum.", "Eisen rostet, Magnesium brennt.", "Gold bleibt blank."],
                solution="Gold ist ein edles Metall — es reagiert kaum mit Sauerstoff oder Säuren.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME03-A2-002", "A", 2, "choice",
                "Was passiert mit einem Eisennagel im Freien?",
                options=["Er rostet.", "Er bleibt blank.", "Er schmilzt."],
                answer=0,
                hints=["Eisen ist unedel.", "Es reagiert mit Sauerstoff und Wasser.", "Es rostet."],
                solution="Eisen ist unedel und reagiert mit Sauerstoff und Wasser zu Rost.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME03-A3-003", "A", 3, "choice",
                "Ein Eisennagel liegt in blauer Kupfersulfatlösung. Was passiert?",
                options=["Der Nagel überzieht sich mit Kupfer.", "Nichts.", "Der Nagel löst sich vollständig auf."],
                answer=0, visual=anim("redox", "A"),
                hints=["Eisen ist unedler als Kupfer.", "Das unedlere gibt Elektronen ab.", "Das Kupfer scheidet sich ab."],
                solution="Eisen ist unedler und gibt Elektronen ab. Die Kupfer-Ionen nehmen sie auf und scheiden sich als Kupfer auf dem Nagel ab.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME03-A4-004", "A", 4, "choice",
                "Welches Metall reagiert mit Salzsäure unter Wasserstoffentwicklung?",
                options=["Zink", "Gold", "Silber"], answer=0,
                hints=["Nur unedle Metalle reagieren mit Säuren.", "Gold und Silber sind edel.", "Zink ist unedel."],
                solution="Zink ist unedel und reagiert mit Säure zu Zinkchlorid und Wasserstoff. Gold und Silber sind edel und reagieren nicht.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME03-B1-005", "B", 1, "choice",
                "Was sagt die Stellung eines Metalls in der Redoxreihe aus?",
                options=["Wie bereitwillig es Elektronen abgibt.",
                         "Wie schwer es ist.", "Wie teuer es ist."],
                answer=0,
                hints=["Die Reihe ordnet nach Reaktionsbereitschaft.",
                       "Es geht um Elektronen.",
                       "Links stehen die, die leicht abgeben."],
                solution="Die Redoxreihe ordnet die Metalle danach, wie bereitwillig sie Elektronen abgeben. Links stehen die unedlen, rechts die edlen.",
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME03-B2-006", "B", 2, "choice",
                "Ein Kupferblech wird in Eisensulfatlösung gelegt. Was beobachtest du?",
                options=["Nichts — Kupfer ist edler als Eisen.",
                         "Das Blech überzieht sich mit Eisen.",
                         "Das Blech löst sich auf."],
                answer=0,
                hints=["Welches Metall ist edler?",
                       "Kupfer.",
                       "Das edlere gibt keine Elektronen ab."],
                solution="Nur das unedlere Metall gibt Elektronen ab. Kupfer ist edler als Eisen, also läuft die Reaktion nicht — die Richtung der Redoxreihe ist eindeutig.",
                misconceptions=[fv("redox_richtung", 1,
                                   "Die Reaktion läuft nur, wenn das eingetauchte Metall <b>unedler</b> ist als das Ion in der Lösung.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME03-B2-007", "B", 2, "choice",
                "Warum schützt eine Zinkschicht Eisen auch dann, wenn sie zerkratzt ist?",
                options=["Zink ist unedler und gibt seine Elektronen bevorzugt ab.",
                         "Zink füllt den Kratzer wieder auf.",
                         "Zink ist härter als Eisen."],
                answer=0,
                hints=["Wo steht Zink in der Redoxreihe?",
                       "Links von Eisen — also unedler.",
                       "Es reagiert bevorzugt."],
                solution="Zink steht in der Redoxreihe links von Eisen. An einer Kratzstelle gibt es seine Elektronen bevorzugt ab und schützt das Eisen weiterhin — deshalb heißt es Opferanode.",
                tags=["redox", "korrosion", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME03-B3-008", "B", 3, "assign",
                "Ordne die Metalle nach zunehmender Edelkeit.",
                slots=["am unedelsten", "in der Mitte", "am edelsten"],
                values=["Magnesium", "Eisen", "Silber"], answer=[0, 1, 2],
                hints=["Denk an die Redoxreihe.",
                       "Magnesium brennt schon an der Luft.",
                       "Silber läuft nur langsam an."],
                solution="Magnesium ist am unedelsten, Eisen liegt dazwischen, Silber ist am edelsten.",
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME03-B3-009", "B", 3, "choice",
                "Warum rostet verzinntes Blech an einer Kratzstelle schneller als unbeschichtetes Eisen?",
                options=["Zinn ist edler als Eisen; an der Kratzstelle gibt das Eisen seine Elektronen bevorzugt ab.",
                         "Zinn zieht Wasser an.",
                         "Zinn ist giftig für Eisen."],
                answer=0,
                hints=["Wo steht Zinn in der Redoxreihe?",
                       "Rechts von Eisen — also edler.",
                       "Dann opfert sich das Eisen."],
                solution="Solange die Zinnschicht geschlossen ist, schützt sie mechanisch. An einer Kratzstelle bildet sich ein Kontakt zwischen edlerem Zinn und unedlerem Eisen — das Eisen gibt bevorzugt Elektronen ab und rostet schneller.",
                tags=["redox", "korrosion", "msa"], spiral=["K-REAK"]),
        aufgabe("ME03-B4-010", "B", 4, "choice",
                "Warum korrodiert Aluminium trotz seiner Unedelkeit kaum?",
                options=["Es bildet eine dichte, festhaftende Oxidschicht, die das Metall darunter schützt.",
                         "Aluminium ist in Wirklichkeit edel.",
                         "Aluminium reagiert nicht mit Sauerstoff."],
                answer=0,
                hints=["Aluminium reagiert sehr wohl mit Sauerstoff.",
                       "Was passiert mit dem entstandenen Oxid?",
                       "Es bleibt als dichte Schicht liegen."],
                solution="Aluminium reagiert sofort mit Sauerstoff — die entstehende Oxidschicht ist aber dicht und haftet fest. Sie schützt das Metall darunter. Rost auf Eisen ist dagegen porös und blättert ab.",
                misconceptions=[fv("edel_unedel_verwechselt", 1,
                                   "Aluminium ist unedel. Es schützt sich durch seine eigene Oxidschicht.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "korrosion", "msa"], spiral=["K-REAK"]),
        aufgabe("ME03-C2-011", "C", 2, "choice",
                "Ein Zinkblech wird in Kupfersulfatlösung gelegt. Was passiert und warum?",
                options=["Kupfer scheidet sich ab, Zink geht in Lösung — Zink ist unedler.",
                         "Nichts, beide sind gleich edel.",
                         "Zink scheidet sich ab, Kupfer geht in Lösung."],
                answer=0,
                hints=["Vergleiche die Stellung in der Redoxreihe.",
                       "Zink steht links von Kupfer.",
                       "Also gibt Zink ab."],
                solution="Zink steht links von Kupfer und ist damit unedler. Es gibt Elektronen ab und geht als Zn²⁺ in Lösung; die Cu²⁺-Ionen nehmen die Elektronen auf und scheiden sich als Kupfer ab.",
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME03-C3-012", "C", 3, "choice",
                "Warum lässt sich Gold in der Natur als reines Metall finden, Eisen aber nur als Erz?",
                options=["Gold ist so edel, dass es kaum Verbindungen bildet; Eisen liegt wegen seiner Unedelkeit als Oxid vor.",
                         "Gold ist seltener als Eisen.",
                         "Eisen wird von Bakterien zersetzt."],
                answer=0,
                hints=["Was tut ein unedles Metall über lange Zeiträume?",
                       "Es reagiert mit Sauerstoff.",
                       "Gold tut das nicht."],
                solution="Unedle Metalle reagieren über geologische Zeiträume vollständig mit Sauerstoff und liegen als Oxide vor. Gold ist so edel, dass es gediegen — also als Metall — vorkommt. Deshalb war Gold vor Eisen bekannt.",
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME03-C3-013", "C", 3, "choice",
                "Ein Schiffsrumpf aus Stahl trägt Zinkblöcke unter der Wasserlinie. Welche Aufgabe haben sie?",
                options=["Als Opferanode: Das unedlere Zink korrodiert anstelle des Stahls.",
                         "Sie beschweren das Schiff.",
                         "Sie verhindern, dass Wasser eindringt."],
                answer=0,
                hints=["Zink ist unedler als Eisen.",
                       "Was passiert dann bei elektrischem Kontakt?",
                       "Das Zink reagiert bevorzugt."],
                solution="Zink ist unedler als Eisen und gibt seine Elektronen bevorzugt ab. Es korrodiert anstelle des Stahls und wird regelmäßig ersetzt — deshalb der Name Opferanode.",
                tags=["redox", "anwenden", "msa"], spiral=["K-REAK"]),
        aufgabe("ME03-C4-014", "C", 4, "choice",
                "Ein Schüler will Silber aus einer Silbersalzlösung gewinnen und überlegt, welches Metall er eintauchen soll. Was rätst du?",
                options=["Ein unedleres Metall wie Kupfer oder Zink — es gibt Elektronen ab, das Silber scheidet sich ab.",
                         "Ein edleres Metall wie Gold.",
                         "Es funktioniert mit jedem Metall gleich gut."],
                answer=0,
                hints=["Wer muss die Elektronen liefern?",
                       "Das eingetauchte Metall.",
                       "Also muss es unedler sein als Silber."],
                solution="Damit sich Silber abscheidet, müssen die Silber-Ionen Elektronen aufnehmen. Liefern kann sie nur ein unedleres Metall — Kupfer oder Zink. Gold ist edler als Silber und gibt nichts ab.",
                misconceptions=[fv("redox_richtung", 1,
                                   "Ein edleres Metall gibt keine Elektronen ab. Die Reaktion liefe nicht.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

E.append({
    "unit": "ME-04",
    "title": "Legierungen und Gebrauchsmetalle",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.1"],
    "klasse": 8,
    "wortspeicher": ["die Legierung", "das Messing", "die Bronze", "der Stahl",
                     "die Härte", "das Gebrauchsmetall", "das Recycling"],
    "worterklaerungen": {
        "Legierung": "Ein Metall, dem andere Stoffe zugesetzt wurden.",
        "Messing": "Eine Legierung aus Kupfer und Zink.",
        "Bronze": "Eine Legierung aus Kupfer und Zinn.",
        "Stahl": "Eisen mit weniger als 2 % Kohlenstoff."
    },
    "can_do": {
        "A": "Ich nenne zwei Legierungen und ihre Bestandteile.",
        "B": "Ich erkläre, warum Legierungen härter sind als die reinen Metalle, und rechne mit Massenanteilen.",
        "C": "Ich bewerte den Einsatz von Legierungen und die Bedeutung des Recyclings."
    },
    "lernkarten": {
        "A": karte("Metalle mischen",
                   "Reine Metalle sind oft zu weich.",
                   ["Man mischt sie mit anderen Stoffen.", "Die Mischung heißt Legierung."],
                   "Legierung = Metall plus Zusatz.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "legierung",
                           "alt": "Teilchenmodell einer Legierung aus zwei Atomsorten."},
                   beispiel={"titel": "Messing", "aufgabe": "Woraus besteht Messing?",
                             "schritte": ["Aus Kupfer.", "Und aus Zink."],
                             "ergebnis": "Messing ist härter als reines Kupfer."}),
        "B": karte("Warum Legierungen härter sind",
                   "Eine Legierung ist kein neuer Stoff im chemischen Sinn, sondern ein verändertes Gitter — und genau das ändert die Eigenschaften.",
                   ["Die eingelagerten Fremdatome haben andere Größen und stören die regelmäßige Schichtung.",
                    "Die Schichten lassen sich schlechter gegeneinander verschieben — die Legierung ist härter, aber weniger verformbar.",
                    "Auch die Schmelztemperatur ändert sich: Lötzinn schmilzt tiefer als beide Bestandteile einzeln.",
                    "Wichtige Legierungen: Messing (Cu + Zn), Bronze (Cu + Sn), Stahl (Fe + C), Edelstahl (Fe + Cr + Ni)."],
                   "Fremdatome stören die Schichten — daher die größere Härte.",
                   visual=anim("elektronengas", "B")),
        "C": karte("Legierungen beurteilen",
                   "Ob eine Legierung die richtige Wahl ist, entscheidet sich an mehreren Kriterien zugleich — und die widersprechen einander oft.",
                   ["Härte gegen Verformbarkeit: Was härter ist, lässt sich schlechter biegen. Für ein Werkzeug ist das gut, für ein Karosserieblech schlecht.",
                    "Korrosionsbeständigkeit: Edelstahl rostet nicht, ist aber teurer und schwerer zu bearbeiten.",
                    "Recycling: Metalle lassen sich nahezu vollständig einschmelzen und wiederverwenden. Aluminium aus Schrott braucht nur rund 5 % der Energie der Neugewinnung.",
                    "Legierungen erschweren das Recycling allerdings, weil die Bestandteile getrennt werden müssen."],
                   "Jede Verbesserung hat einen Preis — zu bewerten ist immer bezogen auf den Zweck.",
                   visual={"type": "anteil", "titel": "Zusammensetzung von Messing",
                           "segmente": [{"anteil": 63, "label": "Cu"}, {"anteil": 37, "label": "Zn"}],
                           "alt": "Messing besteht zu etwa 63 % aus Kupfer und 37 % aus Zink."})
    },
    "formelkarte": {"formeln": ["w = m(Bestandteil) : m(Legierung) · 100 %"],
                    "saetze": ["Messing = Kupfer + Zink. Bronze = Kupfer + Zinn.",
                               "Stahl = Eisen mit weniger als 2 % Kohlenstoff.",
                               "Fremdatome stören die Schichten → größere Härte.",
                               "Aluminiumrecycling spart rund 95 % der Energie."]},
    "tasks": [
        aufgabe("ME04-A1-001", "A", 1, "choice",
                "Woraus besteht Messing?",
                options=["Kupfer und Zink", "Kupfer und Zinn", "Eisen und Kohlenstoff"], answer=0,
                hints=["Es sind zwei Metalle.", "Eines davon ist Kupfer.", "Das andere Zink."],
                solution="Messing besteht aus Kupfer und Zink. Kupfer und Zinn ergeben Bronze.",
                misconceptions=[fv("legierung_verwechselt", 1,
                                   "Kupfer und Zinn ergeben Bronze. Messing enthält Zink.")],
                tags=["legierungen"], spiral=["K-STOF"]),
        aufgabe("ME04-A2-002", "A", 2, "choice",
                "Warum werden Metalle legiert?",
                options=["Um sie härter oder beständiger zu machen.", "Um sie billiger zu machen.", "Um sie leichter zu machen."],
                answer=0,
                hints=["Reine Metalle sind oft zu weich.", "Die Legierung soll besser sein.", "Meist härter."],
                solution="Reine Metalle sind häufig zu weich oder nicht beständig genug. Legierungen sind härter und oft korrosionsbeständiger.",
                tags=["legierungen"], spiral=["K-STOF"]),
        aufgabe("ME04-A3-003", "A", 3, "numeric",
                "Messing besteht zu 60 % aus Kupfer. Wie viel Kupfer stecken in 200 g Messing?",
                answer=120, unit_label="g", tolerance=1,
                hints=["60 % von 200 g.", "1 % sind 2 g.", "60 · 2 g."],
                solution="200 g · 0,60 = 120 g Kupfer",
                misconceptions=[fv("rest_statt_anteil", 80,
                                   "Das ist der Zinkanteil. Gefragt war das Kupfer.")],
                tags=["legierungen", "rechnen"], spiral=["K-SL"]),
        aufgabe("ME04-A4-004", "A", 4, "choice",
                "Was ist Stahl?",
                options=["Eisen mit wenig Kohlenstoff", "reines Eisen", "Eisen mit Kupfer"], answer=0,
                hints=["Stahl entsteht aus Eisen.", "Ein Nichtmetall kommt dazu.", "Kohlenstoff."],
                solution="Stahl ist Eisen mit weniger als 2 % Kohlenstoff. Der Kohlenstoffgehalt bestimmt Härte und Verformbarkeit.",
                tags=["legierungen"], spiral=["K-STOF"]),
        aufgabe("ME04-B1-005", "B", 1, "choice",
                "Warum ist eine Legierung härter als das reine Metall?",
                options=["Fremdatome anderer Größe stören die Schichten, die sich dadurch schlechter verschieben lassen.",
                         "Legierungen haben mehr Elektronen.",
                         "Legierungen sind schwerer."],
                answer=0,
                hints=["Was macht ein reines Metall weich?",
                       "Dass die Schichten leicht gleiten.",
                       "Fremdatome behindern das."],
                solution="In einer Legierung sitzen Atome verschiedener Größe im Gitter. Die regelmäßige Schichtung ist gestört, das Gleiten wird erschwert — das Metall wird härter, aber weniger verformbar.",
                tags=["legierungen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("ME04-B2-006", "B", 2, "numeric",
                "Eine Bronze enthält 88 % Kupfer. Wie viel Zinn stecken in 500 g Bronze?",
                answer=60, unit_label="g", tolerance=1,
                hints=["Der Rest zu 100 % ist Zinn.", "100 − 88 = 12 %.", "12 % von 500 g."],
                solution="Zinnanteil: 100 % − 88 % = 12 %\n500 g · 0,12 = 60 g Zinn",
                misconceptions=[fv("anteil_statt_rest", 440,
                                   "Das ist der Kupferanteil. Gefragt war das Zinn.")],
                tags=["legierungen", "rechnen", "bbr"], spiral=["K-SL"]),
        aufgabe("ME04-B2-007", "B", 2, "choice",
                "Warum schmilzt Lötzinn tiefer als beide reinen Metalle?",
                options=["Die gestörte Gitterordnung senkt die Schmelztemperatur.",
                         "Lötzinn enthält Wasser.",
                         "Lötzinn ist besonders rein."],
                answer=0,
                hints=["Was passiert mit der Ordnung im Gitter?",
                       "Sie wird gestört.",
                       "Ein gestörtes Gitter zerfällt leichter."],
                solution="In einem gestörten Gitter halten die Teilchen weniger regelmäßig zusammen — es lässt sich bei niedrigerer Temperatur auflösen. Deshalb schmelzen viele Legierungen tiefer als ihre Bestandteile.",
                tags=["legierungen", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME04-B3-008", "B", 3, "multi",
                "Eine Messingprobe wiegt 340 g und enthält 63 % Kupfer.",
                fields=[
                    {"label": "Kupfermasse", "answer": 214.2, "unit_label": "g", "tolerance": 1},
                    {"label": "Zinkmasse", "answer": 125.8, "unit_label": "g", "tolerance": 1}
                ],
                hints=["63 % von 340 g.",
                       "Der Rest ist Zink.",
                       "340 − 214,2 = 125,8 g."],
                solution="Cu: 340 · 0,63 = 214,2 g\nZn: 340 − 214,2 = 125,8 g",
                tags=["legierungen", "rechnen", "bbr"], spiral=["K-SL"]),
        aufgabe("ME04-B3-009", "B", 3, "choice",
                "Warum wird für Karosseriebleche ein weicherer Stahl verwendet als für Werkzeuge?",
                options=["Bleche müssen sich umformen lassen; Werkzeuge müssen hart sein.",
                         "Weicher Stahl ist billiger.",
                         "Harter Stahl rostet schneller."],
                answer=0,
                hints=["Was passiert mit einem Blech in der Presse?",
                       "Es wird umgeformt.",
                       "Zu harter Stahl würde reißen."],
                solution="Karosseriebleche werden tiefgezogen und müssen sich verformen lassen. Werkzeuge müssen dagegen hart und verschleißfest sein. Härte und Verformbarkeit schließen einander weitgehend aus — deshalb verschiedene Stähle.",
                tags=["legierungen", "bewerten", "bbr"]),
        aufgabe("ME04-B4-010", "B", 4, "choice",
                "Warum ist Recycling von Aluminium besonders lohnend?",
                options=["Das Einschmelzen braucht nur rund 5 % der Energie der Neugewinnung.",
                         "Aluminium ist besonders selten.",
                         "Recyceltes Aluminium ist reiner."],
                answer=0,
                hints=["Wie aufwendig ist die Gewinnung aus Erz?",
                       "Sehr aufwendig — Elektrolyse.",
                       "Einschmelzen ist dagegen billig."],
                solution="Die Gewinnung aus Bauxit erfordert eine energieintensive Elektrolyse. Das Einschmelzen von Schrott benötigt nur rund 5 % davon — deshalb ist Aluminiumrecycling wirtschaftlich und ökologisch besonders wirksam.",
                tags=["legierungen", "bewerten", "msa"]),
        aufgabe("ME04-C2-011", "C", 2, "choice",
                "Warum ist Edelstahl rostbeständig?",
                options=["Chrom bildet eine dichte Oxidschicht, die das Eisen darunter schützt.",
                         "Edelstahl enthält kein Eisen.",
                         "Edelstahl ist besonders hart."],
                answer=0,
                hints=["Welcher Zusatz macht den Unterschied?",
                       "Chrom.",
                       "Es bildet eine schützende Schicht — wie Aluminium."],
                solution="Der Chromzusatz bildet an der Oberfläche eine dichte, festhaftende Oxidschicht. Sie schützt das darunterliegende Eisen — nach demselben Prinzip wie bei Aluminium. Edelstahl enthält weiterhin überwiegend Eisen.",
                tags=["legierungen", "msa"], spiral=["K-REAK"]),
        aufgabe("ME04-C3-012", "C", 3, "multi",
                "Aus 800 kg Aluminiumschrott wird neues Aluminium gewonnen. Die Neugewinnung aus Erz benötigt 15 kWh je Kilogramm, das Recycling nur 5 % davon.",
                fields=[
                    {"label": "Energie bei Neugewinnung", "answer": 12000, "unit_label": "kWh", "tolerance": 50},
                    {"label": "Energie beim Recycling", "answer": 600, "unit_label": "kWh", "tolerance": 20},
                    {"label": "Ersparnis in kWh", "answer": 11400, "unit_label": "kWh", "tolerance": 50}
                ],
                hints=["800 · 15 kWh.",
                       "5 % davon.",
                       "Differenz bilden."],
                solution="Neugewinnung: 800 · 15 = 12 000 kWh\nRecycling: 12 000 · 0,05 = 600 kWh\nErsparnis: 11 400 kWh",
                tags=["legierungen", "rechnen", "msa"], spiral=["K-SL"]),
        aufgabe("ME04-C3-013", "C", 3, "choice",
                "Warum erschweren Legierungen das Recycling?",
                options=["Die Bestandteile müssen aufwendig getrennt oder die Legierung sortenrein gesammelt werden.",
                         "Legierungen lassen sich nicht einschmelzen.",
                         "Legierungen verlieren beim Schmelzen ihre Metalle."],
                answer=0,
                hints=["Was entsteht, wenn verschiedene Legierungen gemeinsam eingeschmolzen werden?",
                       "Eine unbekannte Mischung.",
                       "Sie ist für den ursprünglichen Zweck oft unbrauchbar."],
                solution="Beim gemeinsamen Einschmelzen entsteht eine Mischung unbekannter Zusammensetzung, die für hochwertige Anwendungen nicht mehr taugt. Deshalb wird sortenrein gesammelt — der Aufwand ist der Preis für die verbesserten Eigenschaften.",
                tags=["legierungen", "bewerten", "msa"]),
        aufgabe("ME04-C4-014", "C", 4, "choice",
                "Eine Firma will ein Fahrradgestell bauen. Welche Begründung für die Materialwahl ist fachlich am tragfähigsten?",
                options=["Aluminiumlegierung: geringe Dichte für ein leichtes Rad, ausreichende Festigkeit durch die Legierung, korrosionsbeständig durch die Oxidschicht.",
                         "Reines Kupfer, weil es gut leitet.",
                         "Blei, weil es sich leicht verarbeiten lässt."],
                answer=0,
                hints=["Welche Eigenschaften braucht ein Fahrradrahmen?",
                       "Leicht, fest, rostbeständig.",
                       "Leitfähigkeit spielt keine Rolle."],
                solution="Für einen Rahmen zählen geringe Masse, ausreichende Festigkeit und Korrosionsbeständigkeit. Eine Aluminiumlegierung erfüllt alle drei. Leitfähigkeit ist kein Kriterium, und Blei wäre viel zu schwer und zu weich.",
                tags=["legierungen", "bewerten", "msa"], spiral=["K-STOF"])
    ]
})

if __name__ == "__main__":
    schreiben("me", E, "Bereich ME · Einheiten 3 und 4")
