# -*- coding: utf-8 -*-
"""Bereich KW · Kohlenwasserstoffe — KW-02 bis KW-04."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "KW-02",
    "title": "Die homologe Reihe der Alkane",
    "leitidee": "B1",
    "standards": ["K1", "K2.1", "K3.4"],
    "klasse": 9,
    "wortspeicher": ["das Alkan", "die homologe Reihe", "die Summenformel", "die CH₂-Gruppe",
                     "die Nomenklatur", "gesättigt"],
    "worterklaerungen": {
        "homologe Reihe": "Eine Reihe von Stoffen, die sich jeweils um eine CH₂-Gruppe unterscheiden.",
        "gesättigt": "Alle Bindungen zwischen den C-Atomen sind Einfachbindungen.",
        "Alkan": "Ein gesättigter Kohlenwasserstoff mit der Formel CₙH₂ₙ₊₂."
    },
    "can_do": {
        "A": "Ich nenne die ersten Alkane und ihre Zahl der C-Atome.",
        "B": "Ich stelle Summenformeln mit CₙH₂ₙ₊₂ auf und benenne Alkane.",
        "C": "Ich begründe die Regelmäßigkeit der homologen Reihe mit dem Bau der Moleküle."
    },
    "lernkarten": {
        "A": karte("Eine Reihe von Stoffen",
                   "Die Alkane bilden eine Reihe.",
                   ["Jedes Glied hat ein C-Atom mehr.", "Die Namen folgen einer festen Ordnung."],
                   "Meth 1 · Eth 2 · Prop 3 · But 4 · Pent 5.",
                   visual=anim("homologereihe", "A"),
                   beispiel={"titel": "Von Methan zu Ethan", "aufgabe": "Was kommt dazu?",
                             "schritte": ["Methan hat 1 C-Atom.", "Ethan hat 2.",
                                          "Dazu kommt eine CH₂-Gruppe."],
                             "ergebnis": "CH₄ → C₂H₆"}),
        "B": karte("Formel und Name",
                   "Für die ganze Reihe genügen eine Formel und eine Namensregel. Beides zusammen erschließt jedes einzelne Glied.",
                   ["Allgemeine Formel: CₙH₂ₙ₊₂. Für n = 3 also C₃H₈ — Propan.",
                    "Namen: Meth 1, Eth 2, Prop 3, But 4, Pent 5, Hex 6, Hept 7, Oct 8, Non 9, Dec 10.",
                    "Alle Alkane enden auf -an. Das kennzeichnet die gesättigten Kohlenwasserstoffe.",
                    "Von Glied zu Glied kommt genau eine CH₂-Gruppe hinzu — das ist die Bedeutung von „homolog“."],
                   "CₙH₂ₙ₊₂ und die Namensreihe genügen für jedes Alkan.",
                   visual=anim("homologereihe", "B")),
        "C": karte("Warum die Formel stimmt",
                   "Die Formel CₙH₂ₙ₊₂ ist keine Setzung, sondern eine Folge der Vierbindigkeit — sie lässt sich herleiten.",
                   ["Jedes C-Atom bildet vier Bindungen. In der Kette gehen zwei davon an die Nachbarn, zwei bleiben für Wasserstoff.",
                    "Die beiden Kettenenden haben nur einen Nachbarn und tragen deshalb je ein H-Atom mehr.",
                    "Daraus folgt: 2n Wasserstoffatome aus der Kette plus 2 an den Enden — also 2n + 2.",
                    "Weil jedes Glied denselben Bau hat, ändern sich Eigenschaften regelmäßig statt sprunghaft: Schmelz- und Siedetemperaturen steigen stetig, die chemischen Reaktionen bleiben gleich."],
                   "2n aus der Kette, 2 von den Enden — daher CₙH₂ₙ₊₂.",
                   visual=anim("homologereihe", "C"))
    },
    "formelkarte": {"formeln": ["Alkane: CₙH₂ₙ₊₂",
                               "CH₄ · C₂H₆ · C₃H₈ · C₄H₁₀ · C₅H₁₂ · C₆H₁₄"],
                    "saetze": ["Meth 1 · Eth 2 · Prop 3 · But 4 · Pent 5 · Hex 6 · Hept 7 · Oct 8.",
                               "Alle Alkane enden auf -an.",
                               "Von Glied zu Glied kommt eine CH₂-Gruppe dazu.",
                               "Gesättigt heißt: nur Einfachbindungen zwischen den C-Atomen."]},
    "tasks": [
        aufgabe("KW02-A1-001", "A", 1, "numeric",
                "Wie viele Kohlenstoffatome hat Propan?",
                answer=3, tolerance=0,
                visual=anim("homologereihe", "A"),
                hints=["Prop steht für eine bestimmte Zahl.", "Meth 1, Eth 2, Prop 3.", "3."],
                solution="Prop steht für drei Kohlenstoffatome: C₃H₈.",
                tags=["alkane"], spiral=["W-ORG"]),
        aufgabe("KW02-A2-002", "A", 2, "choice",
                "Wie heißt das Alkan mit vier C-Atomen?",
                options=["Butan", "Propan", "Pentan"], answer=0,
                hints=["Meth 1, Eth 2, Prop 3, But 4.", "Vier heißt But.", "Butan."],
                solution="Vier Kohlenstoffatome ergeben Butan, C₄H₁₀.",
                misconceptions=[fv("nomenklatur_falsch", 2,
                                   "Pentan hat fünf C-Atome. Vier heißt Butan.",
                                   "nomenklatur_falsch")],
                tags=["alkane"], spiral=["W-ORG"]),
        aufgabe("KW02-A3-003", "A", 3, "numeric",
                "Wie viele Wasserstoffatome hat Methan CH₄?",
                answer=4, tolerance=0,
                hints=["Sieh die Formel an.", "Der Index sagt es.", "4."],
                solution="Methan hat vier Wasserstoffatome: CH₄.",
                tags=["alkane"], spiral=["W-SYMB"]),
        aufgabe("KW02-A4-004", "A", 4, "numeric",
                "Wie viele C-Atome kommen von einem Glied der Reihe zum nächsten dazu?",
                answer=1, tolerance=0,
                visual=anim("homologereihe", "A"),
                hints=["Von Methan zu Ethan.", "Von 1 auf 2.", "Eines."],
                solution="Von Glied zu Glied kommt genau ein C-Atom dazu — zusammen mit zwei H-Atomen, also eine CH₂-Gruppe.",
                tags=["alkane"], spiral=["W-ORG"]),
        aufgabe("KW02-B1-005", "B", 1, "numeric",
                "Wie viele H-Atome hat ein Alkan mit 5 C-Atomen?",
                answer=12, tolerance=0,
                hints=["Formel CₙH₂ₙ₊₂.", "2 · 5 + 2.", "12."],
                solution="2 · 5 + 2 = 12. Pentan hat die Formel C₅H₁₂.",
                misconceptions=[fv("formel_ohne_plus_zwei", 10,
                                   "Die beiden Kettenenden tragen je ein H-Atom zusätzlich: 2n + 2.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkane", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW02-B2-006", "B", 2, "choice",
                "Welche Summenformel hat Hexan?",
                options=["C₆H₁₄", "C₆H₁₂", "C₆H₆"], answer=0,
                hints=["Hex steht für 6.", "2 · 6 + 2 = 14.", "C₆H₁₄."],
                solution="Hexan hat 6 C-Atome: 2 · 6 + 2 = 14 H-Atome, also C₆H₁₄.",
                misconceptions=[fv("formel_ohne_plus_zwei", 1,
                                   "C₆H₁₂ wäre ein Alken. Alkane haben 2n + 2 H-Atome.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkane", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW02-B2-007", "B", 2, "numeric",
                "Ein Alkan hat die Summenformel C₈H₁₈. Wie viele C-Atome hat es?",
                answer=8, tolerance=0,
                hints=["Der erste Index sagt es.", "8.", "Es ist Octan."],
                solution="C₈H₁₈ hat acht Kohlenstoffatome — es ist Octan. Probe: 2 · 8 + 2 = 18.",
                tags=["alkane", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW02-B3-008", "B", 3, "multi",
                "Betrachte die Alkane mit 2, 4 und 7 Kohlenstoffatomen.",
                fields=[
                    {"label": "H-Atome bei 2 C-Atomen", "answer": 6, "tolerance": 0},
                    {"label": "H-Atome bei 4 C-Atomen", "answer": 10, "tolerance": 0},
                    {"label": "H-Atome bei 7 C-Atomen", "answer": 16, "tolerance": 0}
                ],
                hints=["Jeweils 2n + 2.",
                       "2 · 2 + 2 = 6.",
                       "2 · 7 + 2 = 16."],
                solution="Ethan C₂H₆, Butan C₄H₁₀, Heptan C₇H₁₆.",
                tags=["alkane", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW02-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Propan C₃H₈? (C = 12, H = 1 g/mol)",
                answer=44, unit_label="g/mol", tolerance=0.5,
                hints=["3 · 12 + 8 · 1.", "36 + 8.", "44 g/mol."],
                solution="M(C₃H₈) = 3 · 12 + 8 · 1 = 44 g/mol",
                tags=["alkane", "rechnen", "bbr"], spiral=["W-ORG", "W-RECH"]),
        aufgabe("KW02-B4-010", "B", 4, "choice",
                "Was bedeutet „gesättigt“ bei einem Kohlenwasserstoff?",
                options=["Zwischen den C-Atomen bestehen nur Einfachbindungen.",
                         "Der Stoff löst sich nicht mehr.",
                         "Er enthält keinen Wasserstoff mehr."],
                answer=0,
                hints=["Es geht um die Bindungen im Molekül.",
                       "Alle Bindungen sind einfach.",
                       "Mehr H-Atome passen nicht hinein."],
                solution="Gesättigt heißt: Zwischen den C-Atomen bestehen nur Einfachbindungen, das Molekül trägt die größtmögliche Zahl an H-Atomen. Mit dem Lösen hat der Begriff nichts zu tun.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "„Gesättigt“ bezieht sich auf die Bindungen, nicht auf das Lösen.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["alkane", "msa"], spiral=["W-ORG"]),
        aufgabe("KW02-C2-011", "C", 2, "choice",
                "Warum lautet die Formel CₙH₂ₙ₊₂ und nicht CₙH₂ₙ?",
                options=["Die beiden Kettenenden tragen je ein H-Atom mehr, weil sie nur einen Nachbarn haben.",
                         "Das ist eine willkürliche Festlegung.",
                         "Weil Kohlenstoff fünf Bindungen bildet."],
                answer=0,
                visual=anim("homologereihe", "C"),
                hints=["Wie viele Nachbarn hat ein C-Atom in der Kettenmitte?",
                       "Zwei — also zwei H-Atome.",
                       "Am Ende nur einer, also drei H-Atome."],
                solution="In der Kettenmitte gehen zwei der vier Bindungen an Nachbarn, zwei an Wasserstoff. An den beiden Enden ist nur ein Nachbar da, dort bleiben drei Bindungen für Wasserstoff — insgesamt zwei H-Atome mehr.",
                tags=["alkane", "msa"], spiral=["W-ORG"]),
        aufgabe("KW02-C3-012", "C", 3, "multi",
                "Berechne für Octan C₈H₁₈. (C = 12, H = 1 g/mol)",
                fields=[
                    {"label": "molare Masse", "answer": 114, "unit_label": "g/mol", "tolerance": 1},
                    {"label": "Massenanteil des Kohlenstoffs in Prozent", "answer": 84.2, "unit_label": "%", "tolerance": 0.5}
                ],
                hints=["8 · 12 + 18 · 1.",
                       "96 + 18 = 114.",
                       "96 : 114 · 100 %."],
                solution="M = 96 + 18 = 114 g/mol\nw(C) = 96 : 114 = 84,2 %",
                tags=["alkane", "rechnen", "msa"], spiral=["W-ORG", "W-RECH"]),
        aufgabe("KW02-C3-013", "C", 3, "choice",
                "Warum ändern sich die Eigenschaften innerhalb der homologen Reihe regelmäßig?",
                options=["Alle Glieder haben denselben Bau; es ändert sich nur die Kettenlänge.",
                         "Weil die Stoffe zufällig ähnlich sind.",
                         "Weil sie alle gleich schwer sind."],
                answer=0,
                hints=["Was unterscheidet die Glieder?",
                       "Nur die Zahl der CH₂-Gruppen.",
                       "Der Bau bleibt derselbe."],
                solution="Alle Alkane sind gleich gebaut und unterscheiden sich nur in der Kettenlänge. Deshalb ändern sich Schmelz- und Siedetemperatur stetig, und die chemischen Reaktionen bleiben dieselben. Genau das macht die Reihe zu einer Reihe.",
                tags=["alkane", "msa"], spiral=["W-ORG"]),
        aufgabe("KW02-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt für ein Alkan mit 3 C-Atomen die Formel C₃H₆. Wo liegt der Fehler?",
                options=["Er hat die zwei zusätzlichen H-Atome der Kettenenden vergessen — richtig ist C₃H₈.",
                         "Nichts, die Formel ist richtig.",
                         "Es müsste C₃H₁₀ heißen."],
                answer=0,
                hints=["Formel prüfen: 2n + 2.",
                       "2 · 3 + 2 = 8.",
                       "C₃H₆ wäre ein Alken."],
                solution="2 · 3 + 2 = 8, also C₃H₈. C₃H₆ hätte zwei H-Atome zu wenig — das wäre Propen, ein Alken mit Doppelbindung.",
                misconceptions=[fv("formel_ohne_plus_zwei", 1,
                                   "Prüfe mit 2n + 2: Für n = 3 sind es 8 H-Atome.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkane", "bewerten", "msa"], spiral=["W-ORG"])
    ]
})

E.append({
    "unit": "KW-03",
    "title": "Summenformel, Struktur- und Halbstrukturformel",
    "leitidee": "B1",
    "standards": ["K1", "K3.2", "K3.4"],
    "klasse": 9,
    "wortspeicher": ["die Summenformel", "die Strukturformel", "die Halbstrukturformel",
                     "das Kohlenstoffgerüst", "die Bindungsstriche"],
    "worterklaerungen": {
        "Summenformel": "Sie nennt nur, wie viele Atome jeder Sorte enthalten sind.",
        "Strukturformel": "Sie zeigt jede Bindung als Strich.",
        "Halbstrukturformel": "Eine Kurzform: CH₃–CH₂–CH₃ statt aller Striche."
    },
    "can_do": {
        "A": "Ich lese eine Strukturformel und zähle die Atome.",
        "B": "Ich wandle zwischen Summen-, Struktur- und Halbstrukturformel um.",
        "C": "Ich begründe, welche Schreibweise für welche Fragestellung geeignet ist."
    },
    "lernkarten": {
        "A": karte("Drei Schreibweisen",
                   "Denselben Stoff kann man auf drei Arten aufschreiben.",
                   ["Die Summenformel zählt nur die Atome.",
                    "Die Strukturformel zeigt jede Bindung."],
                   "Summenformel zählt, Strukturformel zeigt den Bau.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "keine", "formel": "C3H8",
                           "alt": "Strukturformel von Propan."},
                   beispiel={"titel": "Propan", "aufgabe": "Drei Schreibweisen für denselben Stoff.",
                             "schritte": ["Summenformel: C₃H₈",
                                          "Halbstrukturformel: CH₃–CH₂–CH₃",
                                          "Strukturformel: alle Striche einzeln"],
                             "ergebnis": "Alle drei meinen dasselbe Molekül."}),
        "B": karte("Umwandeln zwischen den Formeln",
                   "Jede Schreibweise lässt sich in die andere überführen. Der Weg von der Struktur zur Summenformel ist immer möglich — umgekehrt nicht immer eindeutig.",
                   ["Von der Strukturformel zur Summenformel: alle C-Atome und alle H-Atome zählen.",
                    "Von der Summenformel zur Halbstrukturformel: die Kette aufschreiben, jedem C-Atom die passende Zahl H-Atome geben.",
                    "In der Halbstrukturformel steht CH₃ für ein Kettenende und CH₂ für ein Kettenglied in der Mitte.",
                    "Wichtig: Aus der Summenformel folgt der Bau nicht eindeutig. C₄H₁₀ kann Butan oder Isobutan sein."],
                   "CH₃ am Ende, CH₂ in der Mitte — daraus baut sich jede Halbstrukturformel.",
                   visual={"type": "struktur", "kette": 4, "gruppe": "keine", "formel": "C4H10",
                           "alt": "Strukturformel von Butan."}),
        "C": karte("Welche Schreibweise wofür",
                   "Die drei Formeln sind nicht gleichwertig — jede beantwortet andere Fragen, und keine ist grundsätzlich die beste.",
                   ["Die Summenformel eignet sich für Massenberechnungen und Reaktionsgleichungen. Sie ist kurz und eindeutig zählbar.",
                    "Die Strukturformel zeigt, welches Atom an welchem hängt. Nur sie unterscheidet Isomere und zeigt funktionelle Gruppen.",
                    "Die Halbstrukturformel ist der Kompromiss: kurz genug für den Fließtext, ausführlich genug, um den Bau zu erkennen.",
                    "Für eine Reaktionsgleichung wird deshalb die Summenformel genommen, für die Frage nach Isomeren die Strukturformel."],
                   "Für die Bilanz die Summenformel, für den Bau die Strukturformel.",
                   visual={"type": "struktur", "kette": 5, "gruppe": "keine", "formel": "C5H12",
                           "alt": "Strukturformel von Pentan."})
    },
    "formelkarte": {"formeln": ["CH₄ · CH₃–CH₃ · CH₃–CH₂–CH₃ · CH₃–CH₂–CH₂–CH₃"],
                    "saetze": ["Summenformel: zählt Atome. Strukturformel: zeigt Bindungen.",
                               "CH₃ steht am Kettenende, CH₂ in der Mitte.",
                               "Aus der Summenformel folgt der Bau nicht eindeutig.",
                               "Für Reaktionsgleichungen die Summenformel verwenden."]},
    "tasks": [
        aufgabe("KW03-A1-001", "A", 1, "numeric",
                "Wie viele C-Atome zeigt die Strukturformel von Propan?",
                answer=3, tolerance=0,
                visual={"type": "struktur", "kette": 3, "gruppe": "keine",
                        "alt": "Strukturformel von Propan mit drei C-Atomen."},
                hints=["Zähle die C im Bild.", "Es sind drei.", "3."],
                solution="Propan hat drei Kohlenstoffatome.",
                tags=["formeln"], spiral=["W-ORG"]),
        aufgabe("KW03-A2-002", "A", 2, "choice",
                "Welche Summenformel gehört zu CH₃–CH₃?",
                options=["C₂H₆", "C₂H₄", "CH₆"], answer=0,
                hints=["Zähle die C-Atome: zwei.",
                       "Zähle die H-Atome: 3 + 3 = 6.",
                       "C₂H₆."],
                solution="CH₃–CH₃ enthält 2 C-Atome und 6 H-Atome: C₂H₆, also Ethan.",
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("KW03-A3-003", "A", 3, "numeric",
                "Wie viele H-Atome zeigt CH₃–CH₂–CH₃?",
                answer=8, tolerance=0,
                hints=["3 + 2 + 3.", "Zähle einzeln.", "8."],
                solution="3 + 2 + 3 = 8 Wasserstoffatome. Es ist Propan C₃H₈.",
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("KW03-A4-004", "A", 4, "choice",
                "Was bedeutet CH₃ am Ende einer Halbstrukturformel?",
                options=["Ein Kettenende mit drei H-Atomen.", "Drei Kohlenstoffatome.", "Eine Doppelbindung."],
                answer=0,
                hints=["Wie viele Nachbarn hat ein C-Atom am Kettenende?",
                       "Einen.",
                       "Also drei Bindungen für Wasserstoff."],
                solution="CH₃ bezeichnet ein Kohlenstoffatom am Kettenende mit drei Wasserstoffatomen.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "Die 3 steht für die H-Atome, nicht für C-Atome.",
                                   "summenformel_falsch_gelesen")],
                tags=["formeln"], spiral=["W-SYMB"]),
        aufgabe("KW03-B1-005", "B", 1, "choice",
                "Welche Halbstrukturformel gehört zu Butan C₄H₁₀?",
                options=["CH₃–CH₂–CH₂–CH₃", "CH₃–CH₃–CH₃–CH₃", "CH₄–CH₄"], answer=0,
                visual={"type": "struktur", "kette": 4, "gruppe": "keine",
                        "alt": "Strukturformel von Butan."},
                hints=["Vier C-Atome in einer Kette.",
                       "Die Enden tragen CH₃, die Mitte CH₂.",
                       "CH₃–CH₂–CH₂–CH₃."],
                solution="Zwei Kettenenden mit CH₃, zwei Mittelglieder mit CH₂: CH₃–CH₂–CH₂–CH₃. Probe: 3 + 2 + 2 + 3 = 10 H-Atome.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "In der Kettenmitte sind nur zwei Bindungen für Wasserstoff frei — dort steht CH₂.",
                                   "summenformel_falsch_gelesen")],
                tags=["formeln", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW03-B2-006", "B", 2, "numeric",
                "Wie viele H-Atome enthält CH₃–CH₂–CH₂–CH₂–CH₃?",
                answer=12, tolerance=0,
                hints=["3 + 2 + 2 + 2 + 3.", "Zähle einzeln.", "12."],
                solution="3 + 2 + 2 + 2 + 3 = 12. Es ist Pentan C₅H₁₂.",
                tags=["formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("KW03-B2-007", "B", 2, "choice",
                "Warum steht in der Kettenmitte CH₂ und nicht CH₃?",
                options=["Ein mittleres C-Atom hat zwei Nachbarn; nur zwei Bindungen bleiben für Wasserstoff.",
                         "Weil es dann kürzer ist.",
                         "Weil in der Mitte weniger Platz ist."],
                answer=0,
                hints=["Wie viele Bindungen bildet Kohlenstoff?",
                       "Vier.",
                       "Zwei gehen an die Nachbarn."],
                solution="Kohlenstoff bildet vier Bindungen. In der Kettenmitte gehen zwei an die Nachbarn, zwei bleiben für Wasserstoff — deshalb CH₂.",
                tags=["formeln", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW03-B3-008", "B", 3, "multi",
                "Gegeben ist die Halbstrukturformel CH₃–CH₂–CH₂–CH₂–CH₂–CH₃.",
                fields=[
                    {"label": "Zahl der C-Atome", "answer": 6, "tolerance": 0},
                    {"label": "Zahl der H-Atome", "answer": 14, "tolerance": 0}
                ],
                hints=["Zähle die Gruppen: sechs.",
                       "3 + 2 + 2 + 2 + 2 + 3.",
                       "14."],
                solution="6 C-Atome, 14 H-Atome — es ist Hexan C₆H₁₄. Probe: 2 · 6 + 2 = 14.",
                tags=["formeln", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW03-B3-009", "B", 3, "choice",
                "Welche Formel eignet sich am besten für eine Reaktionsgleichung?",
                options=["die Summenformel", "die Strukturformel", "die Halbstrukturformel"],
                answer=0,
                hints=["Was wird in einer Gleichung gebraucht?",
                       "Die Atomzahlen.",
                       "Die stehen in der Summenformel."],
                solution="Für eine Reaktionsgleichung müssen Atome gezählt werden — dafür ist die Summenformel am kürzesten und eindeutig. Die Strukturformel würde die Gleichung unlesbar machen.",
                tags=["formeln", "bbr"], spiral=["W-GLEI"]),
        aufgabe("KW03-B4-010", "B", 4, "choice",
                "Welche Formel zeigt, ob zwei Stoffe Isomere sind?",
                options=["die Strukturformel", "die Summenformel", "keine der beiden"],
                answer=0,
                hints=["Isomere haben dieselbe Summenformel.",
                       "Also hilft sie nicht weiter.",
                       "Nur der Bau unterscheidet sie."],
                solution="Isomere haben dieselbe Summenformel — sie kann sie also nicht unterscheiden. Nur die Strukturformel zeigt den unterschiedlichen Bau.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 1,
                                   "Isomere haben dieselbe Summenformel. Sie unterscheidet die Stoffe gerade nicht.",
                                   "isomer_als_gleicher_stoff")],
                tags=["formeln", "msa"], spiral=["W-ORG"]),
        aufgabe("KW03-C2-011", "C", 2, "choice",
                "Warum lässt sich aus der Summenformel C₄H₁₀ nicht eindeutig auf den Bau schließen?",
                options=["Es gibt zwei Isomere: geradkettiges Butan und verzweigtes Isobutan.",
                         "Die Formel ist falsch.",
                         "C₄H₁₀ existiert nicht."],
                answer=0,
                hints=["Kann eine Kette aus vier C-Atomen auch verzweigt sein?",
                       "Ja.",
                       "Dann gibt es zwei Anordnungen."],
                solution="Vier Kohlenstoffatome lassen sich als gerade Kette oder als verzweigte Anordnung verknüpfen. Beide haben C₄H₁₀, sind aber verschiedene Stoffe mit verschiedenen Siedetemperaturen.",
                tags=["formeln", "msa"], spiral=["W-ORG"]),
        aufgabe("KW03-C3-012", "C", 3, "choice",
                "Wofür ist die Halbstrukturformel besser geeignet als die Strukturformel?",
                options=["Für den Fließtext — sie zeigt den Bau und ist trotzdem in einer Zeile schreibbar.",
                         "Für Massenberechnungen.",
                         "Für nichts, sie ist immer schlechter."],
                answer=0,
                hints=["Wie viel Platz braucht eine Strukturformel?",
                       "Viel — sie ist zweidimensional.",
                       "Die Halbstrukturformel passt in eine Zeile."],
                solution="Die Halbstrukturformel zeigt das Kohlenstoffgerüst und passt trotzdem in eine Textzeile. Für Massenberechnungen ist die Summenformel praktischer, für Feinheiten des Baus die vollständige Strukturformel.",
                tags=["formeln", "bewerten", "msa"]),
        aufgabe("KW03-C3-013", "C", 3, "multi",
                "Ein Molekül hat die Halbstrukturformel CH₃–CH₂–CH₂–CH₂–CH₂–CH₂–CH₃. (C = 12, H = 1 g/mol)",
                fields=[
                    {"label": "Zahl der C-Atome", "answer": 7, "tolerance": 0},
                    {"label": "Zahl der H-Atome", "answer": 16, "tolerance": 0},
                    {"label": "molare Masse", "answer": 100, "unit_label": "g/mol", "tolerance": 1}
                ],
                hints=["Sieben Gruppen.",
                       "2 · 7 + 2 = 16.",
                       "M = 7 · 12 + 16 = 100 g/mol."],
                solution="Heptan C₇H₁₆\nM = 84 + 16 = 100 g/mol",
                tags=["formeln", "rechnen", "msa"], spiral=["W-ORG", "W-RECH"]),
        aufgabe("KW03-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt CH₃–CH₃–CH₃ für Propan. Wo liegt der Fehler?",
                options=["Das mittlere C-Atom hat zwei Nachbarn und kann nur zwei H-Atome tragen — richtig ist CH₃–CH₂–CH₃.",
                         "Nichts, die Formel ist richtig.",
                         "Propan hat vier C-Atome."],
                answer=0,
                hints=["Zähle die Bindungen am mittleren C-Atom.",
                       "Zwei Nachbarn plus drei H wären fünf Bindungen.",
                       "Kohlenstoff bildet nur vier."],
                solution="Das mittlere C-Atom hätte mit CH₃ fünf Bindungen — zwei zu den Nachbarn und drei zu Wasserstoff. Kohlenstoff bildet aber nur vier. Richtig ist CH₃–CH₂–CH₃.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "Zähle die Bindungen: Das mittlere C-Atom hätte fünf. Kohlenstoff bildet vier.",
                                   "summenformel_falsch_gelesen")],
                tags=["formeln", "bewerten", "msa"], spiral=["W-ORG"])
    ]
})

if __name__ == "__main__":
    schreiben("kw", E, "Bereich KW · Einheiten 2 und 3")
