# -*- coding: utf-8 -*-
"""Bereich FC · Faszination Chemie — Einheiten FC-05 bis FC-08."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

# ============================================================
# FC-05 · Chemische Reaktion erkennen
# ============================================================
E.append({
    "unit": "FC-05",
    "title": "Chemische Reaktion erkennen",
    "leitidee": "B3",
    "standards": ["K1", "K2.1", "K3.3"],
    "klasse": 7,
    "wortspeicher": ["die chemische Reaktion", "der Ausgangsstoff", "das Edukt", "das Produkt",
                     "die Stoffumwandlung", "exotherm", "endotherm", "umkehrbar"],
    "worterklaerungen": {
        "chemische Reaktion": "Aus alten Stoffen werden neue Stoffe. Die neuen Stoffe haben andere Eigenschaften.",
        "Edukt": "Ein Stoff, der am Anfang da ist.",
        "Produkt": "Ein Stoff, der neu entsteht.",
        "exotherm": "Bei der Reaktion wird Energie frei. Es wird warm.",
        "endotherm": "Für die Reaktion wird Energie gebraucht. Es wird kalt oder man muss heizen."
    },
    "can_do": {
        "A": "Ich erkenne an den Eigenschaften, ob ein neuer Stoff entstanden ist.",
        "B": "Ich unterscheide chemische Reaktion und Zustandsänderung und benenne Edukte und Produkte.",
        "C": "Ich begründe die Einordnung eines Vorgangs über Stoffeigenschaften und Energiebilanz."
    },
    "lernkarten": {
        "A": karte("Ist ein neuer Stoff da?",
                   "Bei einer chemischen Reaktion entsteht ein neuer Stoff.",
                   ["Der neue Stoff sieht anders aus.", "Er hat andere Eigenschaften."],
                   "Neuer Stoff = chemische Reaktion.",
                   visual={"type": "energie", "verlauf": "exotherm",
                           "alt": "Energiediagramm einer exothermen Reaktion: die Produkte liegen tiefer als die Edukte."},
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "Eisenwolle wird verbrannt.",
                             "schritte": ["Vorher: grau, biegsam, magnetisch.",
                                          "Nachher: schwarz, brüchig.",
                                          "Die Eigenschaften sind anders."],
                             "ergebnis": "Ein neuer Stoff ist entstanden."}),
        "B": karte("Reaktion oder nur Zustandswechsel",
                   "Schmelzen, Lösen und Verdampfen sehen manchmal dramatisch aus — und sind trotzdem keine chemischen Reaktionen. Der Unterschied liegt nicht im Aussehen, sondern darin, ob ein neuer Stoff da ist.",
                   ["Bei einer chemischen Reaktion entstehen Stoffe mit anderen Eigenschaften: andere Farbe, andere Dichte, anderer Schmelzpunkt.",
                    "Bei einer Zustandsänderung bleibt der Stoff derselbe. Wasser, Eis und Wasserdampf sind alle Wasser.",
                    "Eine chemische Reaktion lässt sich nicht durch Abkühlen rückgängig machen — Eis dagegen entsteht aus Wasser einfach wieder."],
                   "Frage nicht „sieht es anders aus?“, sondern „ist es ein anderer Stoff?“",
                   visual=anim("aggregat", "B")),
        "C": karte("Stoffumwandlung und Energieumsatz",
                   "Jede chemische Reaktion ist zweierlei zugleich: eine Stoffumwandlung und ein Energieumsatz. Beides gehört zur Beschreibung, und beides lässt sich messen.",
                   ["Exotherm: Die Produkte liegen energetisch tiefer als die Edukte, die Differenz wird als Wärme frei. Verbrennungen sind der Regelfall.",
                    "Endotherm: Die Produkte liegen höher, Energie muss dauerhaft zugeführt werden. Die Reaktion hört auf, sobald man aufhört zu heizen.",
                    "Die Aktivierungsenergie ist davon unabhängig: Auch eine stark exotherme Reaktion braucht einen Anstoß — sonst würde Papier bei Zimmertemperatur brennen."],
                   "Exotherm oder endotherm sagt, wohin die Energie geht. Die Aktivierungsenergie sagt, was zum Start nötig ist.",
                   visual={"type": "energie", "verlauf": "endotherm", "katalysator": True,
                           "alt": "Energiediagramm einer endothermen Reaktion mit und ohne Katalysator."})
    },
    "formelkarte": {"formeln": ["Edukte → Produkte"],
                    "saetze": ["Neuer Stoff mit neuen Eigenschaften = chemische Reaktion.",
                               "Zustandsänderung: derselbe Stoff, andere Anordnung der Teilchen.",
                               "Exotherm: Energie wird frei. Endotherm: Energie wird gebraucht.",
                               "Jede Reaktion braucht Aktivierungsenergie zum Start."]},
    "tasks": [
        aufgabe("FC05-A1-001", "A", 1, "choice",
                "Eisenwolle wird verbrannt. Vorher ist sie grau und biegsam, nachher schwarz und brüchig. Was ist passiert?",
                options=["Ein neuer Stoff ist entstanden.", "Das Eisen ist nur schmutzig geworden.", "Das Eisen ist geschmolzen."],
                answer=0,
                hints=["Vergleiche die Eigenschaften vorher und nachher.",
                       "Grau und biegsam gegen schwarz und brüchig.",
                       "Andere Eigenschaften heißt: anderer Stoff."],
                solution="Die Eigenschaften haben sich vollständig geändert. Es ist ein neuer Stoff entstanden — eine chemische Reaktion.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 2,
                                   "Beim Schmelzen bliebe das Eisen grau und würde beim Abkühlen wieder fest. Hier ist ein neuer Stoff da.",
                                   "reaktion_und_zustandsaenderung_verwechselt", 1)],
                tags=["reaktion"], spiral=["K-STOF"]),
        aufgabe("FC05-A2-002", "A", 2, "assign",
                "Ordne zu: chemische Reaktion oder Zustandsänderung?",
                slots=["Eis schmilzt", "Holz verbrennt", "Wasser verdampft"],
                values=["Zustandsänderung", "chemische Reaktion", "Zustandsänderung (zweite Zeile)"],
                answer=[0, 1, 2],
                hints=["Frage bei jedem: Ist danach ein anderer Stoff da?",
                       "Eis und Wasser sind derselbe Stoff.",
                       "Aus Holz wird Asche und Gas — das ist etwas anderes."],
                solution="Eis schmilzt → Zustandsänderung (immer noch Wasser).\nHolz verbrennt → chemische Reaktion (Asche, Gase).\nWasser verdampft → Zustandsänderung.",
                tags=["reaktion"], spiral=["K-STOF"]),
        aufgabe("FC05-A3-003", "A", 3, "choice",
                "Bei einer Reaktion wird das Reagenzglas warm. Wie nennt man das?",
                options=["exotherm", "endotherm", "neutral"], answer=0,
                hints=["Wird Energie frei oder gebraucht?",
                       "Es wird warm, also wird Energie frei.",
                       "Das heißt exotherm."],
                solution="Wird es warm, gibt die Reaktion Energie ab. Sie ist exotherm.",
                misconceptions=[fv("exo_endo_vertauscht", 1,
                                   "Endotherm wäre es, wenn es kalt würde. Warm heißt exotherm.")],
                tags=["reaktion", "energie"]),
        aufgabe("FC05-A4-004", "A", 4, "choice",
                "Zucker wird in Wasser gerührt und verschwindet. Ist das eine chemische Reaktion?",
                options=["Nein — der Zucker ist noch da, nur verteilt.", "Ja — der Zucker ist weg.", "Ja — Wasser und Zucker werden zu etwas Neuem."],
                answer=0,
                hints=["Schmeckt das Wasser danach süß?",
                       "Ja — der Zucker ist also noch da.",
                       "Beim Eindampfen kommt er zurück."],
                solution="Der Zucker ist nicht verschwunden, sondern gelöst. Beim Eindampfen erhält man ihn zurück — es ist keine chemische Reaktion.",
                misconceptions=[fv("loesen_als_reaktion", 1,
                                   "Gelöst heißt nicht verschwunden. Das Wasser schmeckt süß, und beim Eindampfen kommt der Zucker zurück.",
                                   "reaktion_und_zustandsaenderung_verwechselt", 1)],
                tags=["reaktion"], spiral=["K-STOF"]),
        aufgabe("FC05-B1-005", "B", 1, "assign",
                "Ordne die Begriffe der Reaktion Eisen + Schwefel → Eisensulfid zu.",
                slots=["Eisen", "Schwefel", "Eisensulfid"],
                values=["Edukt", "Edukt (zweites)", "Produkt"],
                answer=[0, 1, 2],
                hints=["Was steht links vom Pfeil, was rechts?",
                       "Links stehen die Edukte.",
                       "Rechts steht das Produkt."],
                solution="Eisen und Schwefel sind die Edukte (Ausgangsstoffe), Eisensulfid ist das Produkt.",
                misconceptions=[fv("edukt_produkt_vertauscht", 2,
                                   "Edukte stehen links vom Pfeil, Produkte rechts.",
                                   "edukt_produkt_vertauscht")],
                tags=["reaktion", "fachsprache"], spiral=["K-REAK"]),
        aufgabe("FC05-B2-006", "B", 2, "choice",
                "Woran erkennst du zuverlässig, dass eine chemische Reaktion stattgefunden hat?",
                options=["Es liegt ein Stoff mit anderen Eigenschaften vor.",
                         "Es hat sich etwas bewegt.", "Es ist warm geworden."],
                answer=0,
                hints=["Wärme entsteht auch beim Lösen von Salz.",
                       "Entscheidend ist der Stoff, nicht die Begleiterscheinung.",
                       "Andere Eigenschaften = anderer Stoff."],
                solution="Wärme allein reicht nicht — auch das Lösen von Salz kann Wärme freisetzen oder verbrauchen. Beweisend ist ein Stoff mit anderen Eigenschaften.",
                misconceptions=[fv("waerme_als_beweis", 2,
                                   "Wärme begleitet fast jede Reaktion, ist aber kein Beweis: Auch Lösen kann wärmen oder kühlen.",
                                   "reaktion_und_zustandsaenderung_verwechselt", 0)],
                tags=["reaktion", "bbr"], spiral=["K-STOF"]),
        aufgabe("FC05-B2-007", "B", 2, "choice",
                "In einem Beutel mit Wasser und Backpulver wird es deutlich kalt. Wie ist die Reaktion einzuordnen?",
                options=["endotherm — sie nimmt Energie aus der Umgebung auf.",
                         "exotherm — es entsteht ein Gas.", "gar keine Reaktion — es wird nur kalt."],
                answer=0,
                hints=["Wird Energie frei oder aufgenommen?",
                       "Es wird kalt, die Umgebung verliert also Energie.",
                       "Das heißt endotherm."],
                solution="Die Umgebung wird kälter, weil die Reaktion ihr Energie entzieht. Das ist endotherm. Dass zugleich Gas entsteht, zeigt: Es ist sehr wohl eine Reaktion.",
                misconceptions=[fv("exo_endo_vertauscht", 1,
                                   "Exotherm hieße: Es wird warm. Hier wird es kalt.")],
                tags=["reaktion", "energie", "bbr"]),
        aufgabe("FC05-B3-008", "B", 3, "choice",
                "Ein Nagel rostet über Wochen. Handelt es sich um eine chemische Reaktion?",
                options=["Ja — Rost hat andere Eigenschaften als Eisen.",
                         "Nein — es geht viel zu langsam.", "Nein — der Nagel ist noch da."],
                answer=0,
                hints=["Spielt die Geschwindigkeit eine Rolle für die Einordnung?",
                       "Nein — nur der Stoff zählt.",
                       "Rost ist brüchig, nicht magnetisch und braun."],
                solution="Rost ist ein anderer Stoff als Eisen: braun, brüchig, nicht magnetisch. Wie lange eine Reaktion dauert, ändert nichts an ihrer Einordnung.",
                misconceptions=[fv("geschwindigkeit_als_kriterium", 1,
                                   "Die Dauer ist kein Kriterium. Auch eine Reaktion über Wochen ist eine chemische Reaktion.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["reaktion", "bbr"], spiral=["K-STOF"]),
        aufgabe("FC05-B3-009", "B", 3, "numeric",
                "Bei einer exothermen Reaktion steigt die Temperatur von 21 °C auf 68 °C. Um wie viel Kelvin ist das?",
                answer=47, unit_label="K", tolerance=0,
                hints=["Eine Temperaturdifferenz ist in °C und K zahlengleich.",
                       "68 − 21.",
                       "47 K."],
                solution="68 °C − 21 °C = 47 K. Eine Differenz von 1 °C entspricht genau 1 K.",
                misconceptions=[fv("kelvin_subtrahiert", 273,
                                   "Die 273 gehören zur Umrechnung eines Temperaturwertes, nicht einer Differenz.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["reaktion", "rechnen"], spiral=["K-QUANT"]),
        aufgabe("FC05-B4-010", "B", 4, "choice",
                "Warum brennt Papier nicht schon bei Zimmertemperatur, obwohl die Verbrennung exotherm ist?",
                options=["Weil zuerst Aktivierungsenergie zugeführt werden muss.",
                         "Weil Papier bei Zimmertemperatur nicht exotherm reagiert.",
                         "Weil bei Zimmertemperatur kein Sauerstoff da ist."],
                answer=0,
                hints=["Was braucht jede Reaktion zum Start?",
                       "Einen Anstoß.",
                       "Der heißt Aktivierungsenergie."],
                solution="Exotherm sagt nur, dass am Ende Energie frei wird. Zum Start braucht jede Reaktion Aktivierungsenergie — beim Papier ein Streichholz.",
                misconceptions=[fv("aktivierung_vergessen", 1,
                                   "Die Reaktion ist exotherm, auch bei Zimmertemperatur. Sie startet nur nicht von selbst.")],
                tags=["reaktion", "energie", "msa"]),
        aufgabe("FC05-C2-011", "C", 2, "choice",
                "Ein Schüler sagt: „Beim Verdampfen von Wasser wird das Wasser zerstört.“ Was ist daran falsch?",
                options=["Die Wassermoleküle bleiben unverändert; nur ihr Abstand wird größer.",
                         "Nichts — Wasserdampf ist tatsächlich ein anderer Stoff.",
                         "Wasser wird beim Verdampfen zu Wasserstoff und Sauerstoff."],
                answer=0,
                hints=["Was passiert beim Verdampfen mit den Teilchen?",
                       "Sie bleiben dieselben.",
                       "Nur der Abstand ändert sich."],
                solution="Beim Verdampfen bleiben die Wassermoleküle vollständig erhalten. Erst die Elektrolyse zerlegt Wasser in Wasserstoff und Sauerstoff — das ist eine chemische Reaktion, das Verdampfen nicht.",
                misconceptions=[fv("verdampfen_als_zerlegung", 2,
                                   "Das wäre die Elektrolyse. Beim Verdampfen bleibt jedes Wassermolekül ganz.",
                                   "reaktion_und_zustandsaenderung_verwechselt", 1)],
                tags=["reaktion", "teilchen", "msa"], spiral=["K-STOF"]),
        aufgabe("FC05-C3-012", "C", 3, "choice",
                "Eine Reaktion läuft nur, solange der Brenner darunter steht. Was folgt daraus?",
                options=["Sie ist endotherm — sie braucht dauerhaft Energiezufuhr.",
                         "Sie ist exotherm — der Brenner liefert nur die Aktivierungsenergie.",
                         "Daraus lässt sich nichts folgern."],
                answer=0,
                hints=["Was passiert, wenn du den Brenner wegnimmst?",
                       "Die Reaktion hört auf.",
                       "Eine exotherme Reaktion liefe von allein weiter."],
                solution="Eine exotherme Reaktion trägt sich nach dem Start selbst — die frei werdende Wärme hält sie in Gang. Hört die Reaktion ohne Brenner auf, braucht sie ständig Energie: Sie ist endotherm.",
                misconceptions=[fv("aktivierung_mit_endotherm_verwechselt", 1,
                                   "Aktivierungsenergie wird nur einmal zum Start gebraucht. Hier wird dauerhaft geheizt — das unterscheidet endotherm von exotherm.")],
                tags=["reaktion", "energie", "msa"]),
        aufgabe("FC05-C3-013", "C", 3, "multi",
                "5,6 g Eisen reagieren vollständig mit 3,2 g Schwefel zu Eisensulfid. Dabei wird das Reagenzglas glühend heiß.",
                fields=[
                    {"label": "Masse des Produkts", "answer": 8.8, "unit_label": "g", "tolerance": 0.01,
                     "misconceptions": [fv("masse_verschwindet", 2.4,
                                           "Du hast subtrahiert. Bei einer Vereinigung addieren sich die Massen der Edukte.",
                                           "masse_verschwindet")]},
                    {"label": "Massenanteil des Eisens im Produkt in Prozent", "answer": 63.64, "unit_label": "%", "tolerance": 0.1}
                ],
                hints=["Es geht keine Masse verloren.",
                       "5,6 g + 3,2 g = 8,8 g.",
                       "Anteil = 5,6 : 8,8 · 100 %."],
                solution="m(Produkt) = 5,6 g + 3,2 g = 8,8 g\nw(Fe) = 5,6 g : 8,8 g = 0,6364 → 63,64 %\nDass es heiß wird, zeigt zusätzlich: Die Reaktion ist exotherm.",
                tags=["reaktion", "rechnen", "msa"], spiral=["K-REAK"]),
        aufgabe("FC05-C4-014", "C", 4, "choice",
                "Beim Lösen von Kochsalz in Wasser kühlt die Lösung leicht ab. Ein Schüler schließt: „Also ist Lösen eine chemische Reaktion.“ Wie bewertest du das?",
                options=["Der Schluss ist falsch: Ein Energieumsatz allein macht noch keine chemische Reaktion.",
                         "Der Schluss ist richtig: Energieumsatz beweist eine Reaktion.",
                         "Der Schluss ist richtig, weil Ionen entstehen."],
                answer=0,
                hints=["Was ist das Kriterium für eine chemische Reaktion?",
                       "Ein neuer Stoff mit neuen Eigenschaften.",
                       "Beim Eindampfen kommt dasselbe Salz zurück."],
                solution="Auch physikalische Vorgänge setzen Energie um. Entscheidend ist, ob ein neuer Stoff vorliegt — beim Eindampfen erhält man dasselbe Kochsalz zurück. Dass die Ionen in Lösung getrennt vorliegen, ändert daran nichts.",
                misconceptions=[fv("waerme_als_beweis", 1,
                                   "Ein Energieumsatz begleitet auch das Lösen und Schmelzen. Beweisend ist nur ein neuer Stoff.",
                                   "reaktion_und_zustandsaenderung_verwechselt", 0)],
                tags=["reaktion", "bewerten", "msa"], spiral=["K-STOF"])
    ]
})

# ============================================================
# FC-06 · Das Feuerdreieck: Brennen und Löschen
# ============================================================
E.append({
    "unit": "FC-06",
    "title": "Das Feuerdreieck: Brennen und Löschen",
    "leitidee": "B4",
    "standards": ["K1", "K2.1", "K4.1"],
    "klasse": 7,
    "sicherheit": [
        "Löschversuche werden nur mit kleinen Mengen und auf Anweisung durchgeführt.",
        "Brennendes Fett und brennende Metalle werden niemals mit Wasser gelöscht."
    ],
    "wortspeicher": ["das Feuerdreieck", "der Brennstoff", "die Zündtemperatur", "der Zerteilungsgrad",
                     "die Verbrennung", "das Löschen", "ersticken", "kühlen"],
    "worterklaerungen": {
        "Feuerdreieck": "Drei Dinge müssen zusammenkommen: Brennstoff, Sauerstoff und Wärme.",
        "Zündtemperatur": "Die Temperatur, ab der ein Stoff von selbst weiterbrennt.",
        "Zerteilungsgrad": "Wie fein ein Stoff verteilt ist. Feiner Staub brennt schneller als ein Klotz."
    },
    "can_do": {
        "A": "Ich nenne die drei Bedingungen für eine Verbrennung und ein passendes Löschmittel.",
        "B": "Ich erkläre Löschmethoden über das Feuerdreieck und nenne die Rolle des Zerteilungsgrades.",
        "C": "Ich bewerte Löschmittel für konkrete Brände und begründe Ausnahmen wie den Fettbrand."
    },
    "lernkarten": {
        "A": karte("Drei Dinge zum Brennen",
                   "Feuer braucht drei Dinge.",
                   ["Brennstoff, Sauerstoff und Wärme.", "Fehlt eines, geht das Feuer aus."],
                   "Nimm eines weg, und es brennt nicht mehr.",
                   visual=anim("feuerdreieck", "A"),
                   beispiel={"titel": "Kerze löschen", "aufgabe": "Du stülpst ein Glas über eine Kerze.",
                             "schritte": ["Der Sauerstoff wird knapp.", "Die Flamme wird kleiner.", "Sie geht aus."],
                             "ergebnis": "Ohne Sauerstoff kein Feuer."}),
        "B": karte("Jede Löschmethode nimmt eine Seite weg",
                   "Löschen heißt nicht „Wasser drauf“, sondern: eine der drei Bedingungen entfernen. Welche das ist, entscheidet über das richtige Mittel.",
                   ["Ersticken entfernt den Sauerstoff: Löschdecke, Sand, Kohlenstoffdioxid.",
                    "Kühlen entfernt die Wärme: Wasser bringt den Stoff unter die Zündtemperatur.",
                    "Entfernen des Brennstoffs: Gashahn zudrehen, brennbares Material wegräumen.",
                    "Wie schnell etwas brennt, hängt am Zerteilungsgrad: Mehlstaub in der Luft kann explodieren, ein Mehlsack nicht."],
                   "Erst fragen: Welche Seite des Dreiecks kann ich hier wegnehmen?",
                   visual=anim("feuerdreieck", "B")),
        "C": karte("Wenn Wasser das Falsche ist",
                   "Wasser kühlt gut und ist fast immer richtig — aber „fast immer“ ist in der Chemie eine Warnung.",
                   ["Fettbrand: Brennendes Fett ist über 300 °C heiß. Wasser verdampft schlagartig, dehnt sich auf das Tausendfache aus und reißt brennendes Fett mit — eine Stichflamme. Richtig ist Ersticken mit dem Topfdeckel.",
                    "Metallbrand: Brennendes Magnesium entzieht dem Wasser den Sauerstoff und setzt Wasserstoff frei. Richtig ist trockener Sand.",
                    "Elektrische Anlagen: Wasser leitet. Erst spannungsfrei schalten, dann löschen."],
                   "Wasser kühlt — aber nur dort, wo es nicht selbst zum Problem wird.",
                   visual=anim("feuerdreieck", "C"))
    },
    "formelkarte": {"formeln": ["Brennstoff + Sauerstoff → Oxide + Energie"],
                    "saetze": ["Feuerdreieck: Brennstoff, Sauerstoff, Zündtemperatur.",
                               "Löschen = eine Seite des Dreiecks entfernen.",
                               "Fettbrand und Metallbrand niemals mit Wasser.",
                               "Je feiner verteilt, desto schneller die Verbrennung."]},
    "tasks": [
        aufgabe("FC06-A1-001", "A", 1, "choice",
                "Welche drei Dinge braucht ein Feuer?",
                options=["Brennstoff, Sauerstoff, Wärme", "Brennstoff, Wasser, Wärme", "Sauerstoff, Wasser, Licht"],
                answer=0, visual=anim("feuerdreieck", "A"),
                hints=["Sieh dir das Feuerdreieck an.", "Eine Ecke ist der Brennstoff.", "Die anderen sind Sauerstoff und Wärme."],
                solution="Das Feuerdreieck: Brennstoff, Sauerstoff und Wärme. Fehlt eines, brennt es nicht.",
                tags=["feuer"]),
        aufgabe("FC06-A2-002", "A", 2, "assign",
                "Ordne jeder Löschmethode zu, was sie wegnimmt.",
                slots=["Glas über die Kerze stülpen", "Wasser auf brennendes Holz", "Gashahn zudrehen"],
                values=["den Sauerstoff", "die Wärme", "den Brennstoff"],
                answer=[0, 1, 2],
                hints=["Jede Methode nimmt eine Ecke weg.", "Ein Glas lässt keine Luft durch.", "Wasser kühlt."],
                solution="Glas → Sauerstoff weg.\nWasser → Wärme weg.\nGashahn → Brennstoff weg.",
                tags=["feuer", "loeschen"]),
        aufgabe("FC06-A3-003", "A", 3, "choice",
                "Was passiert, wenn du eine brennende Kerze mit einem Glas abdeckst?",
                options=["Sie geht aus, weil der Sauerstoff aufgebraucht wird.", "Sie brennt heller.", "Nichts."],
                answer=0,
                hints=["Was ist unter dem Glas begrenzt?", "Die Luft und damit der Sauerstoff.", "Ohne Sauerstoff erlischt die Flamme."],
                solution="Unter dem Glas ist nur wenig Sauerstoff. Ist er verbraucht, erlischt die Flamme.",
                tags=["feuer"]),
        aufgabe("FC06-A4-004", "A", 4, "choice",
                "In der Küche brennt Fett in einer Pfanne. Was tust du?",
                options=["Deckel drauf", "Wasser drauf", "Pfanne nach draußen tragen"],
                answer=0,
                hints=["Wasser und heißes Fett vertragen sich nicht.",
                       "Der Deckel nimmt den Sauerstoff weg.",
                       "Deckel drauf."],
                solution="Der Deckel erstickt die Flamme. Wasser würde schlagartig verdampfen und brennendes Fett herausschleudern.",
                misconceptions=[fv("wasser_bei_fettbrand", 1,
                                   "Wasser ist bei einem Fettbrand lebensgefährlich: Es verdampft schlagartig und reißt brennendes Fett mit.",
                                   "sicherheitsregel_missachtet", 0)],
                tags=["feuer", "sicherheit"]),
        aufgabe("FC06-B1-005", "B", 1, "choice",
                "Was bedeutet Zündtemperatur?",
                options=["Die Temperatur, ab der ein Stoff von selbst weiterbrennt.",
                         "Die Temperatur der Flamme.", "Die Temperatur, bei der ein Stoff schmilzt."],
                answer=0,
                hints=["Es geht um den Start der Verbrennung.",
                       "Ab wann brennt es ohne weitere Hilfe?",
                       "Das ist die Zündtemperatur."],
                solution="Die Zündtemperatur ist die Temperatur, ab der ein Stoff ohne weitere Energiezufuhr weiterbrennt. Sie ist nicht die Flammentemperatur.",
                tags=["feuer", "fachsprache"]),
        aufgabe("FC06-B2-006", "B", 2, "choice",
                "Warum brennt Holzwolle schneller als ein Holzscheit gleicher Masse?",
                options=["Sie hat einen höheren Zerteilungsgrad, also mehr Oberfläche für den Sauerstoff.",
                         "Sie ist trockener.", "Sie hat eine niedrigere Zündtemperatur."],
                answer=0,
                hints=["Vergleiche die Oberfläche bei gleicher Masse.",
                       "Wo kann der Sauerstoff überall angreifen?",
                       "Mehr Oberfläche = schnellere Reaktion."],
                solution="Bei gleicher Masse hat Holzwolle eine viel größere Oberfläche. Der Sauerstoff kann an mehr Stellen gleichzeitig angreifen — die Verbrennung läuft schneller ab.",
                misconceptions=[fv("zuendtemperatur_als_grund", 2,
                                   "Die Zündtemperatur ist eine Stoffeigenschaft und bei beiden gleich. Es geht um die Oberfläche.")],
                tags=["feuer", "bbr"], spiral=["K-STOF"]),
        aufgabe("FC06-B2-007", "B", 2, "choice",
                "Warum kann Mehlstaub in einer Mühle explodieren, ein Sack Mehl aber nicht?",
                options=["Im Staub ist jedes Teilchen von Luft umgeben — alles reagiert fast gleichzeitig.",
                         "Mehlstaub ist chemisch etwas anderes als Mehl.",
                         "Im Sack fehlt der Brennstoff."],
                answer=0,
                hints=["Wo ist die Oberfläche größer?",
                       "Im Staub kann Sauerstoff überall gleichzeitig angreifen.",
                       "Deshalb läuft alles auf einmal ab."],
                solution="Es ist derselbe Stoff. Im Staub ist die Oberfläche so groß und der Sauerstoffkontakt so vollständig, dass die Verbrennung praktisch gleichzeitig abläuft — das ist die Explosion.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Mehlstaub ist chemisch dasselbe Mehl. Der Unterschied liegt allein im Zerteilungsgrad.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["feuer", "bbr"], spiral=["K-STOF"]),
        aufgabe("FC06-B3-008", "B", 3, "assign",
                "Ordne jedem Brand das richtige Löschmittel zu.",
                slots=["brennendes Papier", "Fettbrand in der Pfanne", "brennendes Magnesium"],
                values=["Wasser", "Topfdeckel", "trockener Sand"],
                answer=[0, 1, 2],
                hints=["Ein Löschmittel passt nicht überall.",
                       "Fett und Wasser vertragen sich nicht.",
                       "Magnesium reagiert sogar mit Wasser."],
                solution="Papier → Wasser (kühlen).\nFettbrand → Topfdeckel (ersticken).\nMagnesium → trockener Sand; Wasser würde zersetzt und Wasserstoff freigesetzt.",
                misconceptions=[fv("wasser_bei_fettbrand", 0,
                                   "Wasser ist bei Fett- und Metallbränden gefährlich. Jedes Löschmittel hat seinen Einsatzbereich.",
                                   "sicherheitsregel_missachtet")],
                tags=["feuer", "loeschen", "bbr"]),
        aufgabe("FC06-B3-009", "B", 3, "numeric",
                "Ein Liter Wasser wird beim Verdampfen etwa 1700-mal so groß. Welches Dampfvolumen in Litern ergeben 0,2 L Wasser?",
                answer=340, unit_label="L", tolerance=1,
                hints=["0,2 L mal 1700.", "0,2 · 1700.", "340 L."],
                solution="0,2 L · 1700 = 340 L. Diese schlagartige Ausdehnung ist der Grund, warum Wasser bei einem Fettbrand so gefährlich ist.",
                misconceptions=[fv("geteilt_statt_mal", 8500,
                                   "Du hast geteilt. Das Volumen wird größer, also wird multipliziert.")],
                tags=["feuer", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("FC06-B4-010", "B", 4, "choice",
                "Eine Löschdecke wird über ein brennendes Kleidungsstück gelegt. Welche Seite des Feuerdreiecks wird entfernt?",
                options=["der Sauerstoff", "der Brennstoff", "die Wärme"],
                answer=0,
                hints=["Was hält die Decke ab?", "Sie hält Luft ab.", "Also den Sauerstoff."],
                solution="Die Löschdecke schließt die Luft ab. Ohne Sauerstoff erlischt die Flamme — sie erstickt.",
                tags=["feuer", "loeschen"]),
        aufgabe("FC06-C2-011", "C", 2, "choice",
                "Warum darf brennendes Magnesium nicht mit Wasser gelöscht werden?",
                options=["Magnesium entzieht dem Wasser den Sauerstoff; dabei entsteht Wasserstoff, der explodiert.",
                         "Wasser kühlt Magnesium zu schnell ab.",
                         "Magnesium löst sich in Wasser."],
                answer=0,
                hints=["Magnesium ist sehr reaktionsfreudig.",
                       "Es kann sogar Sauerstoff aus Verbindungen holen.",
                       "Übrig bleibt der Wasserstoff."],
                solution="Brennendes Magnesium ist so heiß und so reaktionsfreudig, dass es dem Wasser den Sauerstoff entreißt. Zurück bleibt Wasserstoff — und der bildet mit Luft ein explosionsfähiges Gemisch.",
                misconceptions=[fv("kuehlen_als_gefahr", 1,
                                   "Zu schnelles Abkühlen wäre kein Sicherheitsproblem. Gefährlich ist der entstehende Wasserstoff.",
                                   "sicherheitsregel_missachtet")],
                tags=["feuer", "erklaeren", "msa"]),
        aufgabe("FC06-C3-012", "C", 3, "choice",
                "Kohlenstoffdioxid-Löscher sind bei elektrischen Anlagen zugelassen, Wasser nicht. Warum?",
                options=["CO₂ leitet den Strom nicht und hinterlässt keine Rückstände.",
                         "CO₂ kühlt besser als Wasser.", "Wasser reagiert mit Kupfer."],
                answer=0,
                hints=["Was ist bei Strom das Problem an Wasser?",
                       "Wasser leitet.",
                       "CO₂ nicht."],
                solution="Wasser leitet den Strom und gefährdet die löschende Person. Kohlenstoffdioxid leitet nicht, erstickt die Flamme und hinterlässt keine Rückstände in der Elektronik. Zum Kühlen taugt es dagegen kaum.",
                tags=["feuer", "bewerten", "msa"]),
        aufgabe("FC06-C3-013", "C", 3, "choice",
                "Ein Kaminfeuer wird durch Zusammenschieben der Scheite größer, obwohl nicht mehr Holz dazukommt. Wie erklärst du das?",
                options=["Die Scheite strahlen sich gegenseitig Wärme zu; die Temperatur bleibt über der Zündtemperatur.",
                         "Zusammengeschoben ist mehr Sauerstoff verfügbar.",
                         "Der Zerteilungsgrad steigt beim Zusammenschieben."],
                answer=0,
                hints=["Welche Ecke des Dreiecks wird verstärkt?",
                       "Nicht der Brennstoff, nicht der Sauerstoff.",
                       "Die Wärme."],
                solution="Eng beieinander strahlen die Scheite sich gegenseitig Wärme zu. Dadurch bleiben sie sicher über der Zündtemperatur. Auseinandergezogen kühlen sie ab und das Feuer geht aus — deshalb löscht man ein Lagerfeuer durch Auseinanderziehen.",
                misconceptions=[fv("sauerstoff_als_grund", 1,
                                   "Zusammengeschoben kommt eher <b>weniger</b> Luft dazwischen. Entscheidend ist die gegenseitige Wärmestrahlung.")],
                tags=["feuer", "erklaeren", "msa"]),
        aufgabe("FC06-C4-014", "C", 4, "choice",
                "Ein Feuerlöscher trägt die Kennzeichnung „ABC“. Ein Schüler folgert: „Damit kann ich jeden Brand löschen.“ Wie bewertest du das?",
                options=["Falsch — die Klassen A, B und C decken Feststoffe, Flüssigkeiten und Gase ab, aber nicht Metallbrände (Klasse D) und nicht Fettbrände (Klasse F).",
                         "Richtig — ABC bedeutet alle Brandklassen.",
                         "Falsch — ABC-Löscher sind nur für Papier zugelassen."],
                answer=0,
                hints=["Wie viele Brandklassen gibt es?",
                       "Es gibt A, B, C, D und F.",
                       "D und F sind nicht abgedeckt."],
                solution="A steht für Feststoffe, B für Flüssigkeiten, C für Gase. Metallbrände (D) und Speisefettbrände (F) verlangen eigene Löschmittel. Ein ABC-Löscher deckt also das Meiste ab, aber nicht alles.",
                misconceptions=[fv("kennzeichnung_ueberdehnt", 1,
                                   "ABC nennt genau drei Klassen. D und F fehlen — und gerade dort ist das falsche Mittel gefährlich.",
                                   "sicherheitsregel_missachtet")],
                tags=["feuer", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("fc", E, "Bereich FC · Einheiten 5 und 6")
