# -*- coding: utf-8 -*-
"""Bereich PS · Das Periodensystem der Elemente — PS-01 bis PS-04 (Klasse 7)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

# ============================================================
# PS-01 · Aufbau des PSE: Perioden und Gruppen
# ============================================================
E.append({
    "unit": "PS-01",
    "title": "Aufbau des PSE: Perioden und Gruppen",
    "leitidee": "B1",
    "standards": ["K1", "K2.1", "K3.1"],
    "klasse": 7,
    "wortspeicher": ["das Periodensystem", "die Periode", "die Hauptgruppe", "das Element",
                     "das Elementsymbol", "das Metall", "das Nichtmetall", "die Ordnungszahl"],
    "worterklaerungen": {
        "Periode": "Eine Zeile im Periodensystem.",
        "Hauptgruppe": "Eine Spalte im Periodensystem. Die Elemente darin ähneln sich.",
        "Elementsymbol": "Die Abkürzung für ein Element. Der erste Buchstabe ist immer groß.",
        "Ordnungszahl": "Die Nummer eines Elements im Periodensystem."
    },
    "can_do": {
        "A": "Ich finde ein Element im Periodensystem und lese Symbol und Ordnungszahl ab.",
        "B": "Ich unterscheide Perioden und Gruppen und ordne Metalle und Nichtmetalle zu.",
        "C": "Ich begründe die Anordnung im Periodensystem über gemeinsame Eigenschaften."
    },
    "lernkarten": {
        "A": karte("Zeilen und Spalten",
                   "Das Periodensystem ist eine Tabelle.",
                   ["Die Zeilen heißen Perioden.", "Die Spalten heißen Gruppen."],
                   "Zeile = Periode. Spalte = Gruppe.",
                   visual={"type": "pse", "markiert": ["Na", "Cl"], "perioden": 3,
                           "alt": "Ausschnitt des Periodensystems, Natrium und Chlor hervorgehoben."},
                   beispiel={"titel": "Natrium finden", "aufgabe": "Wo steht Natrium?",
                             "schritte": ["Das Symbol ist Na.", "Es steht in Periode 3.", "Es steht in Gruppe I."],
                             "ergebnis": "Periode 3, Gruppe I."}),
        "B": karte("Was Zeile und Spalte bedeuten",
                   "Die Anordnung ist keine Laune: Sie folgt der Ordnungszahl und bringt Elemente mit ähnlichen Eigenschaften untereinander.",
                   ["Innerhalb einer Periode steigt die Ordnungszahl von links nach rechts um jeweils eins.",
                    "Elemente einer Hauptgruppe reagieren ähnlich: Alle Alkalimetalle reagieren heftig mit Wasser, alle Edelgase reagieren fast gar nicht.",
                    "Links und in der Mitte stehen die Metalle, rechts oben die Nichtmetalle. Dazwischen verläuft eine Trennlinie."],
                   "Gleiche Spalte heißt: ähnliche Eigenschaften.",
                   visual={"type": "pse", "markiert": ["Li", "Na", "K"], "perioden": 4,
                           "legende": "Die Alkalimetalle stehen untereinander in Gruppe I.",
                           "alt": "Periodensystem-Ausschnitt mit hervorgehobener erster Hauptgruppe."}),
        "C": karte("Warum die Ordnung trägt",
                   "Mendelejew ordnete die Elemente nach Eigenschaften und ließ dort Lücken, wo keines passte — und sagte damit Elemente vorher, die noch niemand kannte. Das unterscheidet ein tragfähiges Ordnungssystem von einer bloßen Liste.",
                   ["Eine Ordnung, die Vorhersagen erlaubt, ist mehr als eine Sortierung. Mendelejews Lücken wurden später mit Gallium und Germanium gefüllt — mit fast genau den vorhergesagten Eigenschaften.",
                    "Heute erklärt der Atombau die Ordnung: Die Periode gibt die Zahl der besetzten Schalen an, die Hauptgruppennummer die Zahl der Außenelektronen.",
                    "Damit ist die Ähnlichkeit innerhalb einer Gruppe kein Zufall mehr, sondern eine Folge gleicher Außenelektronenzahl."],
                   "Die Ordnung im PSE ist kein Katalog, sondern ein Werkzeug für Vorhersagen.",
                   visual=anim("pseordnung", "C") if False else {"type": "pse", "markiert": ["He", "Ne", "Ar"], "perioden": 4,
                                                                 "legende": "Edelgase: rechte Spalte, alle reaktionsträge.",
                                                                 "alt": "Periodensystem-Ausschnitt mit hervorgehobenen Edelgasen."})
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Periode = Zeile = Zahl der besetzten Schalen.",
                               "Hauptgruppe = Spalte = Zahl der Außenelektronen.",
                               "Metalle links und Mitte, Nichtmetalle rechts oben.",
                               "Gleiche Gruppe → ähnliche Reaktionen."]},
    "tasks": [
        aufgabe("PS01-A1-001", "A", 1, "choice",
                "Wie heißen die Zeilen im Periodensystem?",
                options=["Perioden", "Gruppen", "Schalen"], answer=0,
                visual={"type": "pse", "perioden": 3, "alt": "Ausschnitt des Periodensystems."},
                hints=["Zeilen gehen von links nach rechts.", "Spalten heißen Gruppen.", "Zeilen heißen Perioden."],
                solution="Die Zeilen heißen Perioden, die Spalten Gruppen.",
                misconceptions=[fv("periode_gruppe_vertauscht", 1,
                                   "Gruppen sind die <b>Spalten</b>. Zeilen heißen Perioden.")],
                tags=["pse"], spiral=["W-TEIL"]),
        aufgabe("PS01-A2-002", "A", 2, "numeric",
                "Welche Ordnungszahl hat Sauerstoff (O)?",
                answer=8, tolerance=0,
                hints=["Sieh im Periodensystem nach.", "Sauerstoff steht in der zweiten Periode.", "Die Ordnungszahl ist 8."],
                solution="Sauerstoff hat die Ordnungszahl 8.",
                tags=["pse"], spiral=["W-TEIL"]),
        aufgabe("PS01-A3-003", "A", 3, "assign",
                "Ordne jedem Element sein Symbol zu.",
                slots=["Natrium", "Kohlenstoff", "Chlor"],
                values=["Na", "C", "Cl"], answer=[0, 1, 2],
                hints=["Das Symbol beginnt meist mit dem ersten Buchstaben des Namens.",
                       "Natrium kommt vom lateinischen natrium.",
                       "Kohlenstoff heißt lateinisch carboneum — daher C."],
                solution="Natrium → Na, Kohlenstoff → C, Chlor → Cl.",
                misconceptions=[fv("symbol_verwechselt", 1,
                                   "Symbole werden aus dem lateinischen Namen gebildet, nicht immer aus dem deutschen.")],
                tags=["pse", "symbole"], spiral=["W-SYMB"]),
        aufgabe("PS01-A4-004", "A", 4, "choice",
                "Ist Eisen ein Metall oder ein Nichtmetall?",
                options=["Metall", "Nichtmetall", "beides"], answer=0,
                hints=["Wo steht Eisen im Periodensystem?", "In der Mitte links.", "Dort stehen die Metalle."],
                solution="Eisen steht im linken und mittleren Bereich des Periodensystems — dort stehen die Metalle. Es glänzt, leitet Strom und ist verformbar.",
                tags=["pse"], spiral=["W-TEIL"]),
        aufgabe("PS01-B1-005", "B", 1, "choice",
                "Was haben alle Elemente einer Hauptgruppe gemeinsam?",
                options=["Sie haben gleich viele Außenelektronen und reagieren ähnlich.",
                         "Sie haben gleich viele Schalen.", "Sie haben dieselbe Atommasse."],
                answer=0,
                hints=["Was ändert sich innerhalb einer Spalte, was bleibt gleich?",
                       "Die Zahl der Schalen wächst nach unten.",
                       "Die Zahl der Außenelektronen bleibt gleich."],
                solution="Elemente einer Hauptgruppe haben gleich viele Außenelektronen. Deshalb reagieren sie ähnlich. Die Zahl der Schalen wächst dagegen von oben nach unten.",
                misconceptions=[fv("periode_gruppe_vertauscht", 1,
                                   "Gleich viele Schalen haben die Elemente einer <b>Periode</b>, nicht einer Gruppe.")],
                tags=["pse", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS01-B2-006", "B", 2, "numeric",
                "In welcher Periode steht Chlor (Ordnungszahl 17)?",
                answer=3, tolerance=0,
                hints=["Die erste Periode hat 2 Elemente, die zweite 8, die dritte 8.",
                       "2 + 8 = 10, danach beginnt die dritte Periode.",
                       "17 liegt zwischen 11 und 18."],
                solution="Nach 2 + 8 = 10 Elementen beginnt die dritte Periode. Chlor mit der Ordnungszahl 17 steht dort.",
                tags=["pse", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS01-B2-007", "B", 2, "choice",
                "Lithium, Natrium und Kalium reagieren alle heftig mit Wasser. Was erklärt das?",
                options=["Sie stehen in derselben Hauptgruppe und haben je ein Außenelektron.",
                         "Sie stehen in derselben Periode.", "Sie haben dieselbe Atommasse."],
                answer=0,
                visual={"type": "pse", "markiert": ["Li", "Na", "K"], "perioden": 4,
                        "alt": "Periodensystem mit hervorgehobener erster Hauptgruppe."},
                hints=["Sieh nach, ob sie unter- oder nebeneinander stehen.",
                       "Sie stehen untereinander.",
                       "Also dieselbe Gruppe."],
                solution="Alle drei stehen in der ersten Hauptgruppe und besitzen ein Außenelektron, das leicht abgegeben wird. Deshalb reagieren sie ähnlich heftig.",
                tags=["pse", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS01-B3-008", "B", 3, "assign",
                "Ordne jedes Element seiner Gruppe zu.",
                slots=["Magnesium", "Fluor", "Neon"],
                values=["Erdalkalimetalle (II)", "Halogene (VII)", "Edelgase (VIII)"],
                answer=[0, 1, 2],
                hints=["Zähle die Spalte von links.",
                       "Magnesium steht in der zweiten Spalte.",
                       "Neon steht ganz rechts."],
                solution="Magnesium → Gruppe II (Erdalkalimetalle).\nFluor → Gruppe VII (Halogene).\nNeon → Gruppe VIII (Edelgase).",
                tags=["pse", "gruppen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS01-B3-009", "B", 3, "numeric",
                "Wie viele Elemente enthält die zweite Periode?",
                answer=8, tolerance=0,
                hints=["Von Lithium bis Neon.",
                       "Zähle: Li, Be, B, C, N, O, F, Ne.",
                       "Das sind 8."],
                solution="Die zweite Periode reicht von Lithium (3) bis Neon (10) und enthält 8 Elemente — genauso viele Elektronen fasst die zweite Schale.",
                tags=["pse"], spiral=["W-TEIL"]),
        aufgabe("PS01-B4-010", "B", 4, "choice",
                "Warum steht Wasserstoff meist über den Alkalimetallen, obwohl er ein Nichtmetall ist?",
                options=["Er hat wie sie ein Außenelektron.", "Er ist das leichteste Metall.", "Es ist nur eine Platzfrage."],
                answer=0,
                hints=["Wonach ist das PSE geordnet?",
                       "Nach Ordnungszahl und Außenelektronen.",
                       "Wasserstoff hat ein Elektron."],
                solution="Wasserstoff besitzt ein Außenelektron und steht deshalb formal in der ersten Hauptgruppe. Seine Eigenschaften unterscheiden sich davon deutlich — ein guter Anlass, die Grenzen einer Ordnung zu besprechen.",
                misconceptions=[fv("wasserstoff_als_metall", 1,
                                   "Wasserstoff ist ein Nichtmetall. Er steht dort nur wegen seines einen Außenelektrons.")],
                tags=["pse", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS01-C2-011", "C", 2, "choice",
                "Mendelejew ließ in seinem System Lücken frei. Warum war das ein Zeichen von Stärke und nicht von Schwäche?",
                options=["Er sagte damit unbekannte Elemente samt Eigenschaften vorher — und behielt recht.",
                         "Er wusste nicht, wohin mit den Elementen.",
                         "Die Lücken waren Druckfehler."],
                answer=0,
                hints=["Was passierte mit den Lücken später?",
                       "Sie wurden gefüllt.",
                       "Und zwar mit Elementen, deren Eigenschaften er vorhergesagt hatte."],
                solution="Mendelejew ordnete nach Eigenschaften und ließ Plätze frei, wo kein bekanntes Element passte. Gallium und Germanium füllten sie später — mit fast genau den vorhergesagten Eigenschaften. Eine Ordnung, die Vorhersagen erlaubt, ist mehr als eine Sortierung.",
                tags=["pse", "modelle", "msa"]),
        aufgabe("PS01-C3-012", "C", 3, "choice",
                "Warum reagieren Edelgase kaum mit anderen Stoffen?",
                options=["Ihre äußerste Schale ist vollständig besetzt.",
                         "Sie sind zu schwer.", "Sie kommen zu selten vor."],
                answer=0,
                visual={"type": "atom", "z": 10, "symbol": "Ne", "neutronen": 10,
                        "alt": "Schalenmodell von Neon mit voll besetzter Außenschale."},
                hints=["Sieh dir die Außenschale an.",
                       "Sie ist voll.",
                       "Ein voller Zustand wird nicht freiwillig verändert."],
                solution="Edelgase haben eine vollständig besetzte Außenschale. Sie müssen weder Elektronen abgeben noch aufnehmen und reagieren deshalb kaum. Genau diesen Zustand streben andere Atome an.",
                tags=["pse", "erklaeren", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS01-C3-013", "C", 3, "multi",
                "Ein Element steht in Periode 3 und Hauptgruppe VI.",
                fields=[
                    {"label": "Zahl der besetzten Schalen", "answer": 3, "tolerance": 0},
                    {"label": "Zahl der Außenelektronen", "answer": 6, "tolerance": 0},
                    {"label": "Ordnungszahl", "answer": 16, "tolerance": 0}
                ],
                hints=["Die Periode gibt die Schalenzahl.",
                       "Die Gruppennummer gibt die Außenelektronen.",
                       "2 + 8 + 6 = 16 — das ist Schwefel."],
                solution="Periode 3 → 3 Schalen.\nGruppe VI → 6 Außenelektronen.\n2 + 8 + 6 = 16 → Schwefel.",
                tags=["pse", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS01-C4-014", "C", 4, "choice",
                "Ein Schüler ordnet die Elemente nach der Atommasse und stellt fest, dass Argon schwerer ist als Kalium, im PSE aber davor steht. Wie ist das zu bewerten?",
                options=["Das PSE ist nach der Ordnungszahl geordnet, nicht nach der Masse — die Eigenschaften bestätigen die Reihenfolge.",
                         "Das PSE enthält an dieser Stelle einen Fehler.",
                         "Argon und Kalium müssten getauscht werden."],
                answer=0,
                hints=["Wonach ist das moderne PSE geordnet?",
                       "Nach der Ordnungszahl.",
                       "Argon ist ein Edelgas, Kalium ein Alkalimetall — die Eigenschaften passen so."],
                solution="Ordnete man nach Masse, stünde Argon bei den Alkalimetallen und Kalium bei den Edelgasen — beides widerspräche allen Eigenschaften. Das moderne PSE ordnet nach der Ordnungszahl, und genau deshalb stimmt die Reihenfolge.",
                misconceptions=[fv("masse_als_ordnungsprinzip", 2,
                                   "Ein Tausch würde ein reaktionsträges Gas zu den heftig reagierenden Alkalimetallen stellen. Geordnet wird nach der Ordnungszahl.")],
                tags=["pse", "bewerten", "msa"], spiral=["W-TEIL"])
    ]
})

# ============================================================
# PS-02 · Modelle in der Chemie
# ============================================================
E.append({
    "unit": "PS-02",
    "title": "Modelle in der Chemie",
    "leitidee": "B1",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 7,
    "wortspeicher": ["das Modell", "das Anschauungsmodell", "das Funktionsmodell", "das Gedankenmodell",
                     "die Modellgrenze", "das Original"],
    "worterklaerungen": {
        "Modell": "Ein vereinfachtes Abbild. Es zeigt das Wichtige und lässt anderes weg.",
        "Modellgrenze": "Die Stelle, an der ein Modell etwas Falsches behaupten würde.",
        "Funktionsmodell": "Ein Modell, das zeigt, wie etwas funktioniert — nicht, wie es aussieht."
    },
    "can_do": {
        "A": "Ich erkenne ein Modell als vereinfachtes Abbild und nenne einen Unterschied zum Original.",
        "B": "Ich unterscheide Anschauungs-, Funktions- und Gedankenmodelle.",
        "C": "Ich benenne die Grenzen eines Modells und begründe, wofür es trotzdem taugt."
    },
    "lernkarten": {
        "A": karte("Ein Modell ist nicht das Original",
                   "Ein Modell zeigt nur das Wichtige.",
                   ["Vieles lässt es weg.", "Deshalb ist es einfacher als die Wirklichkeit."],
                   "Ein Modell hilft beim Verstehen. Es ist nicht die Wirklichkeit.",
                   beispiel={"titel": "Kugeln als Atome",
                             "aufgabe": "Im Modell sind Atome bunte Kugeln.",
                             "schritte": ["Kugeln kann man anfassen.", "Atome nicht.",
                                          "Atome haben auch keine Farbe."],
                             "ergebnis": "Das Modell hilft trotzdem beim Zählen."}),
        "B": karte("Drei Arten von Modellen",
                   "Nicht jedes Modell will dasselbe. Wer die Art kennt, weiß auch, welche Fragen es beantworten kann.",
                   ["Ein Anschauungsmodell zeigt den Bau: das Kalottenmodell eines Wassermoleküls.",
                    "Ein Funktionsmodell zeigt einen Vorgang: das Hochofenmodell im Kleinen.",
                    "Ein Gedankenmodell existiert nur im Kopf und in der Zeichnung: das Kern-Hülle-Modell.",
                    "Farben in Modellen sind Verabredungen. Sauerstoff ist nicht rot — er wird nur so gezeichnet."],
                   "Frage zuerst: Was soll dieses Modell zeigen?",
                   visual={"type": "teilchen", "zustand": "fest", "art": "verbindung",
                           "alt": "Teilchenmodell einer Verbindung im festen Zustand."}),
        "C": karte("Wo ein Modell aufhört",
                   "Jedes Modell hat eine Grenze, und diese Grenze zu kennen ist wichtiger als das Modell selbst. Ein Modell jenseits seiner Grenze zu benutzen erzeugt zuverlässig falsche Vorstellungen.",
                   ["Das Kugelmodell erklärt Aggregatzustände gut, sagt aber nichts über chemische Bindungen.",
                    "Das Schalenmodell erklärt Ionenladungen und Hauptgruppen gut, versagt aber bei den Nebengruppen.",
                    "Kein Modell ist „richtig“ oder „falsch“ — es ist geeignet oder ungeeignet für eine bestimmte Frage. Deshalb arbeiten Chemiker mit mehreren Modellen nebeneinander."],
                   "Ein Modell wird nicht widerlegt, sondern in seiner Reichweite bestimmt.",
                   visual={"type": "atom", "z": 11, "symbol": "Na", "neutronen": 12,
                           "alt": "Schalenmodell von Natrium mit einem Außenelektron."})
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Ein Modell vereinfacht und lässt weg.",
                               "Anschauungsmodell: zeigt den Bau. Funktionsmodell: zeigt den Vorgang.",
                               "Gedankenmodell: existiert nur in der Vorstellung.",
                               "Jedes Modell hat eine Grenze. Sie zu kennen gehört zum Modell."]},
    "tasks": [
        aufgabe("PS02-A1-001", "A", 1, "choice",
                "Warum benutzt man in der Chemie Modelle?",
                options=["Weil Atome zu klein sind, um sie zu sehen.", "Weil Modelle schöner sind.", "Weil es schneller geht."],
                answer=0,
                hints=["Kann man ein Atom mit dem Auge sehen?", "Nein, es ist viel zu klein.", "Ein Modell macht es vorstellbar."],
                solution="Atome sind zu klein, um sie zu sehen. Ein Modell macht sie vorstellbar und besprechbar.",
                tags=["modelle"], spiral=["W-TEIL"]),
        aufgabe("PS02-A2-002", "A", 2, "choice",
                "Im Modell ist ein Sauerstoffatom rot. Ist ein echtes Sauerstoffatom rot?",
                options=["Nein — die Farbe ist nur eine Verabredung.", "Ja — deshalb wird es so gezeichnet.", "Nur bei tiefen Temperaturen."],
                answer=0,
                hints=["Kann ein einzelnes Atom überhaupt eine Farbe haben?",
                       "Farbe entsteht erst bei sehr vielen Teilchen.",
                       "Die Farbe im Modell ist eine Verabredung."],
                solution="Einzelne Atome haben keine Farbe. Rot für Sauerstoff ist eine Verabredung, damit man Modelle leichter liest.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Farbe ist eine Eigenschaft des Stoffes, nicht des einzelnen Atoms.",
                                   "teilchen_traegt_stoffeigenschaft", 3)],
                tags=["modelle"], spiral=["W-TEIL"]),
        aufgabe("PS02-A3-003", "A", 3, "assign",
                "Ordne zu: Was zeigt jedes Modell?",
                slots=["Kalottenmodell eines Moleküls", "Hochofenmodell im Kleinen", "Kern-Hülle-Modell"],
                values=["den Bau", "einen Vorgang", "eine Vorstellung im Kopf"],
                answer=[0, 1, 2],
                hints=["Ein Modell zeigt den Bau, eines einen Ablauf, eines eine Idee.",
                       "Das Kalottenmodell kann man anfassen.",
                       "Das Kern-Hülle-Modell ist nur gezeichnet."],
                solution="Kalottenmodell → Bau (Anschauungsmodell).\nHochofenmodell → Vorgang (Funktionsmodell).\nKern-Hülle-Modell → Vorstellung (Gedankenmodell).",
                tags=["modelle"], spiral=["W-TEIL"]),
        aufgabe("PS02-A4-004", "A", 4, "choice",
                "Was ist ein Nachteil jedes Modells?",
                options=["Es lässt etwas weg.", "Es ist zu teuer.", "Es ist zu groß."],
                answer=0,
                hints=["Ein Modell ist einfacher als die Wirklichkeit.",
                       "Etwas fehlt also immer.",
                       "Es lässt etwas weg."],
                solution="Jedes Modell vereinfacht und lässt dabei etwas weg. Genau das macht es brauchbar — und begrenzt es zugleich.",
                tags=["modelle"]),
        aufgabe("PS02-B1-005", "B", 1, "choice",
                "Was ist ein Funktionsmodell?",
                options=["Ein Modell, das zeigt, wie ein Vorgang abläuft.",
                         "Ein Modell, das genau wie das Original aussieht.",
                         "Ein Modell, das man nur denken kann."],
                answer=0,
                hints=["Der Name verrät es.", "Es geht um die Funktion.", "Also um einen Ablauf."],
                solution="Ein Funktionsmodell zeigt, wie etwas abläuft — nicht, wie es aussieht. Ein Hochofenmodell im Kleinen ist ein Beispiel.",
                tags=["modelle", "fachsprache"]),
        aufgabe("PS02-B2-006", "B", 2, "choice",
                "Im Kugelmodell liegen die Teilchen eines Feststoffs dicht nebeneinander. Was erklärt dieses Modell gut, was nicht?",
                options=["Gut: Aggregatzustände. Nicht: chemische Bindungen.",
                         "Gut: chemische Bindungen. Nicht: Aggregatzustände.",
                         "Es erklärt beides gleich gut."],
                answer=0,
                hints=["Was sieht man im Kugelmodell?",
                       "Abstände und Anordnung.",
                       "Über Bindungen sagt es nichts."],
                solution="Das Kugelmodell zeigt Abstände und Anordnung — damit erklärt es Aggregatzustände überzeugend. Warum Teilchen aneinander haften, zeigt es nicht; dafür braucht es Bindungsmodelle.",
                tags=["modelle", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS02-B2-007", "B", 2, "choice",
                "Ein Schüler sagt: „Das Schalenmodell ist falsch, weil Elektronen nicht auf Kreisbahnen laufen.“ Wie ist das zu bewerten?",
                options=["Modelle sind nicht falsch oder richtig, sondern geeignet oder ungeeignet für eine Frage.",
                         "Er hat recht, das Modell gehört abgeschafft.",
                         "Er hat unrecht, Elektronen laufen auf Kreisbahnen."],
                answer=0,
                hints=["Wozu benutzt man das Schalenmodell?",
                       "Um Ionenladungen und Gruppen zu erklären.",
                       "Dafür funktioniert es sehr gut."],
                solution="Elektronen laufen tatsächlich nicht auf Kreisbahnen. Für die Frage, wie viele Elektronen ein Atom abgibt, liefert das Schalenmodell trotzdem die richtige Antwort. Modelle werden nach ihrer Eignung beurteilt, nicht nach Wahrheit.",
                tags=["modelle", "bewerten", "bbr"]),
        aufgabe("PS02-B3-008", "B", 3, "assign",
                "Ordne jedem Modell seine wichtigste Grenze zu.",
                slots=["Kugelmodell", "Schalenmodell", "Kalottenmodell"],
                values=["sagt nichts über Bindungen", "versagt bei den Nebengruppen", "zeigt keine Bewegung"],
                answer=[0, 1, 2],
                hints=["Jedes Modell kann etwas nicht.",
                       "Das Schalenmodell funktioniert bei den Hauptgruppen gut.",
                       "Ein Kalottenmodell steht still."],
                solution="Kugelmodell → keine Bindungen.\nSchalenmodell → Nebengruppen.\nKalottenmodell → keine Bewegung.",
                tags=["modelle", "msa"]),
        aufgabe("PS02-B3-009", "B", 3, "choice",
                "Warum werden in der Chemie mehrere Atommodelle nebeneinander benutzt?",
                options=["Jedes beantwortet andere Fragen gut.",
                         "Weil man sich nicht einigen konnte.",
                         "Weil ältere Modelle einfacher zu zeichnen sind."],
                answer=0,
                hints=["Jedes Modell hat eine Reichweite.",
                       "Für verschiedene Fragen taugen verschiedene Modelle.",
                       "Deshalb bleiben alte Modelle in Gebrauch."],
                solution="Für die Frage nach Aggregatzuständen genügt das Kugelmodell, für Ionenladungen braucht es das Schalenmodell, für Bindungen ein weiteres. Jedes Modell wird dort eingesetzt, wo es trägt.",
                tags=["modelle", "msa"]),
        aufgabe("PS02-B4-010", "B", 4, "choice",
                "Ein Modell des Sonnensystems wird für den Atombau benutzt. Wo führt der Vergleich in die Irre?",
                options=["Planeten ziehen sich durch Schwerkraft an, Elektronen werden elektrisch angezogen — und Elektronen haben keine festen Bahnen.",
                         "Planeten sind größer als Elektronen.",
                         "Das Sonnensystem ist älter als das Atom."],
                answer=0,
                hints=["Welche Kraft wirkt jeweils?",
                       "Schwerkraft gegen elektrische Anziehung.",
                       "Und Bahnen gibt es beim Atom nicht."],
                solution="Der Vergleich trägt für die Vorstellung „schwerer Kern, leichte Hülle“. Er versagt bei der Art der Kraft und bei der Vorstellung fester Bahnen — Elektronen haben keine.",
                tags=["modelle", "msa"]),
        aufgabe("PS02-C2-011", "C", 2, "choice",
                "Warum ist das Kalottenmodell für Größenverhältnisse innerhalb eines Atoms ungeeignet?",
                options=["Es zeigt nur die Hülle; der Kern wäre darin unsichtbar klein.",
                         "Es ist nicht bunt genug.", "Es zeigt zu viele Elektronen."],
                answer=0,
                hints=["Wie groß ist der Kern im Verhältnis zum Atom?",
                       "Rund zehntausendmal kleiner.",
                       "In einem Modell von 10 cm wäre er 0,01 mm groß."],
                solution="Der Kern ist rund zehntausendmal kleiner als das Atom. In einem Kalottenmodell von 10 cm Durchmesser wäre er nicht mehr sichtbar. Das Modell zeigt deshalb nur die Hülle — für Größenverhältnisse im Inneren taugt es nicht.",
                tags=["modelle", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS02-C3-012", "C", 3, "choice",
                "Welche Aussage über Modelle ist fachlich korrekt?",
                options=["Ein Modell wird verworfen, sobald es Beobachtungen widerspricht, die es erklären soll.",
                         "Ein Modell wird verworfen, sobald ein neueres existiert.",
                         "Ein Modell ist unabhängig von Beobachtungen gültig."],
                answer=0,
                hints=["Wonach wird ein Modell beurteilt?",
                       "Nach dem, was es erklären soll.",
                       "Widerspricht es dort den Beobachtungen, trägt es nicht mehr."],
                solution="Das Daltonsche Modell wurde nicht abgeschafft, weil ein neueres kam, sondern weil der Streuversuch Beobachtungen lieferte, die es nicht erklären konnte. Für die Massenverhältnisse in Verbindungen genügt es bis heute.",
                tags=["modelle", "msa"]),
        aufgabe("PS02-C3-013", "C", 3, "multi",
                "Ein Atom hat einen Durchmesser von etwa 0,1 nm, sein Kern etwa 0,00001 nm.",
                fields=[
                    {"label": "Wie oft passt der Kerndurchmesser in den Atomdurchmesser?", "answer": 10000, "tolerance": 1},
                    {"label": "Kerndurchmesser in einem Modell mit 10 cm Atomdurchmesser, in mm", "answer": 0.01, "tolerance": 0.001}
                ],
                hints=["0,1 : 0,00001.",
                       "Das sind 10 000.",
                       "10 cm = 100 mm; 100 mm : 10 000 = 0,01 mm."],
                solution="0,1 nm : 0,00001 nm = 10 000\n100 mm : 10 000 = 0,01 mm — mit bloßem Auge nicht mehr zu sehen.",
                tags=["modelle", "rechnen", "msa"], spiral=["W-EINH"]),
        aufgabe("PS02-C4-014", "C", 4, "choice",
                "Zwei Gruppen streiten, ob das Schalenmodell oder das Kugelmodell „besser“ ist. Wie löst du den Streit fachlich auf?",
                options=["Die Frage ist falsch gestellt — es kommt darauf an, welche Frage beantwortet werden soll.",
                         "Das Schalenmodell ist neuer und deshalb besser.",
                         "Das Kugelmodell ist einfacher und deshalb besser."],
                answer=0,
                hints=["Kann man Modelle unabhängig von der Fragestellung vergleichen?",
                       "Nein.",
                       "Erst die Frage, dann das Modell."],
                solution="Für Aggregatzustände ist das Kugelmodell geeigneter, für Ionenladungen das Schalenmodell. Modelle lassen sich nur bezogen auf eine Fragestellung vergleichen — „besser“ ohne Frage ist keine sinnvolle Aussage.",
                tags=["modelle", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("ps", E, "Bereich PS · Einheiten 1 und 2")
