# -*- coding: utf-8 -*-
"""Bereich WA · Wasser — WA-02 und WA-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "WA-02",
    "title": "Analyse und Synthese von Wasser",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K2.4"],
    "klasse": 8,
    "sicherheit": [
        "Die Knallgasreaktion wird nur mit kleinen Gasmengen und hinter einer Scheibe gezeigt.",
        "Beim Elektrolyseversuch keine offenen Flammen in der Nähe."
    ],
    "wortspeicher": ["die Analyse", "die Synthese", "die Elektrolyse", "die Knallgasreaktion",
                     "umkehrbar", "das Volumenverhältnis"],
    "worterklaerungen": {
        "Analyse": "Eine Verbindung wird in ihre Bestandteile zerlegt.",
        "Synthese": "Aus Bestandteilen entsteht eine Verbindung.",
        "Elektrolyse": "Zerlegen mit Hilfe von elektrischem Strom.",
        "umkehrbar": "Die Reaktion läuft in beide Richtungen."
    },
    "can_do": {
        "A": "Ich weiß, dass Wasser aus Wasserstoff und Sauerstoff besteht, und kenne das Verhältnis 2 : 1.",
        "B": "Ich beschreibe Elektrolyse und Knallgasreaktion und erkenne sie als Umkehrung voneinander.",
        "C": "Ich leite aus dem Volumenverhältnis die Formel H₂O ab und begründe die Energiebilanz."
    },
    "lernkarten": {
        "A": karte("Wasser lässt sich zerlegen",
                   "Wasser ist kein Element.",
                   ["Mit Strom zerfällt es in zwei Gase.", "Es entsteht doppelt so viel Wasserstoff wie Sauerstoff."],
                   "Wasser besteht aus Wasserstoff und Sauerstoff.",
                   visual=anim("elektrolyse", "A"),
                   beispiel={"titel": "Im Zersetzer", "aufgabe": "Wie viel Gas entsteht?",
                             "schritte": ["Links 20 mL Wasserstoff.", "Rechts halb so viel Sauerstoff.",
                                          "Das sind 10 mL."],
                             "ergebnis": "20 mL zu 10 mL — das Verhältnis 2 : 1.",
                             "luecke": {"schritt": 2, "wert": 10, "einheit": "mL"}}),
        "B": karte("Zerlegen und wieder verbinden",
                   "Zwei Versuche, die in entgegengesetzte Richtungen laufen — und genau deshalb zusammengehören.",
                   ["Elektrolyse: Strom zerlegt Wasser. Am Minuspol entsteht Wasserstoff, am Pluspol Sauerstoff, im Volumenverhältnis 2 : 1. Energie wird zugeführt — die Reaktion ist endotherm.",
                    "Knallgasreaktion: Wasserstoff und Sauerstoff verbinden sich wieder zu Wasser. Energie wird frei — die Reaktion ist exotherm.",
                    "Beide Vorgänge sind Umkehrungen voneinander. Was die eine Reaktion an Energie aufnimmt, gibt die andere wieder ab."],
                   "Analyse braucht Energie, Synthese gibt sie frei. Es ist dieselbe Reaktion in zwei Richtungen.",
                   visual=anim("elektrolyse", "B")),
        "C": karte("Vom Volumenverhältnis zur Formel",
                   "Das gemessene Volumenverhältnis ist nicht nur ein Zahlenwert, sondern der Weg zur Formel des Wassers.",
                   ["Gleiche Gasvolumina enthalten bei gleichen Bedingungen gleich viele Teilchen. Das Verhältnis 2 : 1 im Volumen bedeutet also 2 : 1 in der Teilchenzahl.",
                    "Auf ein Sauerstoffmolekül kommen zwei Wasserstoffmoleküle: 2 H₂ + O₂ → 2 H₂O.",
                    "Weil jedes Sauerstoffmolekül zwei Atome enthält, entstehen daraus zwei Wassermoleküle — jedes mit einem O-Atom und zwei H-Atomen.",
                    "In der Praxis wird etwas weniger Sauerstoff aufgefangen als berechnet: Er löst sich besser im Wasser als Wasserstoff."],
                   "Gleiche Volumina, gleiche Teilchenzahl — daraus folgt die Formel.",
                   visual=anim("elektrolyse", "C"))
    },
    "formelkarte": {"formeln": ["2 H₂O → 2 H₂ + O₂   (Elektrolyse, endotherm)",
                               "2 H₂ + O₂ → 2 H₂O   (Knallgasreaktion, exotherm)"],
                    "saetze": ["Volumenverhältnis bei der Elektrolyse: 2 Teile H₂ zu 1 Teil O₂.",
                               "Am Minuspol entsteht Wasserstoff, am Pluspol Sauerstoff.",
                               "Analyse: endotherm. Synthese: exotherm.",
                               "Gleiche Gasvolumina enthalten gleich viele Teilchen."]},
    "tasks": [
        aufgabe("WA02-A1-001", "A", 1, "choice",
                "Woraus besteht Wasser?",
                options=["aus Wasserstoff und Sauerstoff", "aus Wasserstoff und Stickstoff", "aus einem einzigen Element"],
                answer=0, visual=anim("elektrolyse", "A"),
                hints=["Bei der Elektrolyse entstehen zwei Gase.", "Eines ist Sauerstoff.", "Das andere ist Wasserstoff."],
                solution="Wasser ist eine Verbindung aus Wasserstoff und Sauerstoff. Die Elektrolyse zeigt es.",
                tags=["wasser", "analyse"], spiral=["K-REAK"]),
        aufgabe("WA02-A2-002", "A", 2, "numeric",
                "Bei der Elektrolyse entstehen 30 mL Wasserstoff. Wie viel Sauerstoff entsteht?",
                answer=15, unit_label="mL", tolerance=1,
                hints=["Das Verhältnis ist 2 : 1.", "Vom Sauerstoff entsteht die Hälfte.", "30 : 2."],
                solution="30 mL : 2 = 15 mL Sauerstoff. Es entsteht immer doppelt so viel Wasserstoff.",
                misconceptions=[fv("verhaeltnis_umgedreht", 60,
                                   "Vom Sauerstoff entsteht die <b>Hälfte</b>, nicht das Doppelte.")],
                tags=["wasser", "rechnen"], spiral=["K-REAK"]),
        aufgabe("WA02-A3-003", "A", 3, "choice",
                "An welchem Pol entsteht Wasserstoff?",
                options=["am Minuspol", "am Pluspol", "an beiden"], answer=0,
                visual={"type": "apparatur", "aufbau": "elektrolyse",
                        "alt": "Elektrolyseapparatur mit Plus- und Minuspol."},
                hints=["Am Minuspol entsteht das häufigere Gas.", "Das ist Wasserstoff.", "Also am Minuspol."],
                solution="Am Minuspol entsteht Wasserstoff, am Pluspol Sauerstoff.",
                misconceptions=[fv("pole_vertauscht", 1,
                                   "Am Pluspol entsteht Sauerstoff — dort ist es auch das kleinere Volumen.")],
                tags=["wasser", "analyse"], spiral=["K-REAK"]),
        aufgabe("WA02-A4-004", "A", 4, "choice",
                "Was passiert bei der Knallgasreaktion?",
                options=["Wasserstoff und Sauerstoff werden wieder zu Wasser.",
                         "Wasser wird zerlegt.", "Es entsteht Kohlenstoffdioxid."],
                answer=0,
                hints=["Es ist die umgekehrte Richtung der Elektrolyse.", "Aus zwei Gasen wird eine Verbindung.", "Es entsteht Wasser."],
                solution="Wasserstoff und Sauerstoff verbinden sich zu Wasser. Das ist die Umkehrung der Elektrolyse.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Das Zerlegen ist die Elektrolyse. Die Knallgasreaktion verbindet wieder.",
                                   "edukt_produkt_vertauscht")],
                tags=["wasser", "synthese"], spiral=["K-REAK"]),
        aufgabe("WA02-B1-005", "B", 1, "numeric",
                "In einem Zersetzer werden 48 mL Wasserstoff aufgefangen. Wie viel Sauerstoff sollte entstanden sein?",
                answer=24, unit_label="mL", tolerance=1,
                hints=["Verhältnis 2 : 1.", "48 : 2.", "24 mL."],
                solution="48 mL : 2 = 24 mL Sauerstoff.",
                tags=["wasser", "rechnen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA02-B2-006", "B", 2, "choice",
                "Warum ist die Elektrolyse endotherm?",
                options=["Es muss ständig elektrische Energie zugeführt werden, sonst hört sie auf.",
                         "Weil das Wasser dabei warm wird.",
                         "Weil dabei Gase entstehen."],
                answer=0,
                hints=["Was passiert, wenn du den Strom abschaltest?",
                       "Die Reaktion stoppt sofort.",
                       "Also braucht sie dauerhaft Energie."],
                solution="Ohne Stromzufuhr hört die Elektrolyse sofort auf. Sie nimmt dauerhaft Energie auf und ist damit endotherm — anders als die exotherme Knallgasreaktion.",
                misconceptions=[fv("aktivierung_mit_endotherm_verwechselt", 1,
                                   "Wärme allein macht eine Reaktion nicht endotherm. Entscheidend ist die dauerhafte Energiezufuhr.")],
                tags=["wasser", "energie", "bbr"]),
        aufgabe("WA02-B2-007", "B", 2, "choice",
                "Warum sind Elektrolyse und Knallgasreaktion Umkehrungen voneinander?",
                options=["Die Edukte der einen sind die Produkte der anderen.",
                         "Beide laufen gleich schnell ab.",
                         "Beide brauchen Strom."],
                answer=0,
                hints=["Vergleiche die Gleichungen.",
                       "2 H₂O → 2 H₂ + O₂ und 2 H₂ + O₂ → 2 H₂O.",
                       "Links und rechts sind vertauscht."],
                solution="2 H₂O → 2 H₂ + O₂ gegenüber 2 H₂ + O₂ → 2 H₂O: Edukte und Produkte sind vertauscht. Was die eine an Energie aufnimmt, gibt die andere ab.",
                tags=["wasser", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA02-B3-008", "B", 3, "multi",
                "Bei einer Elektrolyse werden insgesamt 90 mL Gas aufgefangen.",
                fields=[
                    {"label": "Wasserstoffvolumen", "answer": 60, "unit_label": "mL", "tolerance": 1},
                    {"label": "Sauerstoffvolumen", "answer": 30, "unit_label": "mL", "tolerance": 1}
                ],
                hints=["Das Gesamtvolumen besteht aus 2 + 1 = 3 Teilen.",
                       "1 Teil = 90 : 3 = 30 mL.",
                       "Wasserstoff sind 2 Teile."],
                solution="1 Teil = 90 mL : 3 = 30 mL\nH₂ = 2 · 30 = 60 mL, O₂ = 30 mL",
                misconceptions=[],
                tags=["wasser", "rechnen", "bbr"], spiral=["K-REAK", "K-QUANT"]),
        aufgabe("WA02-B3-009", "B", 3, "choice",
                "Wie weist du nach, dass das Gas am Minuspol Wasserstoff ist?",
                options=["Mit der Knallgasprobe — es ertönt ein pfeifender Knall.",
                         "Mit der Glimmspanprobe — der Span flammt auf.",
                         "Mit Kalkwasser — es wird trüb."],
                answer=0,
                hints=["Welcher Nachweis gehört zu Wasserstoff?",
                       "Die Knallgasprobe.",
                       "Der Glimmspan gehört zum Sauerstoff."],
                solution="Wasserstoff wird mit der Knallgasprobe nachgewiesen. Am Pluspol ließe sich der Sauerstoff mit dem Glimmspan zeigen.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Der Glimmspan weist Sauerstoff nach — der entsteht am Pluspol.",
                                   "nachweis_verwechselt")],
                tags=["wasser", "nachweise", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA02-B4-010", "B", 4, "choice",
                "In der Praxis wird etwas weniger Sauerstoff aufgefangen als 1 : 2 erwarten lässt. Warum?",
                options=["Sauerstoff löst sich besser im Wasser als Wasserstoff.",
                         "Die Elektrolyse funktioniert nicht richtig.",
                         "Sauerstoff entweicht durch das Glas."],
                answer=0,
                hints=["Wo könnte Sauerstoff bleiben?",
                       "Im Wasser gelöst.",
                       "Er ist besser löslich als Wasserstoff."],
                solution="Sauerstoff löst sich deutlich besser in Wasser als Wasserstoff. Ein Teil bleibt deshalb gelöst und wird nicht aufgefangen — ein systematischer Fehler, kein Versuchsfehler.",
                tags=["wasser", "fehler", "msa"], spiral=["K-SL"]),
        aufgabe("WA02-C2-011", "C", 2, "choice",
                "Warum folgt aus dem Volumenverhältnis 2 : 1 die Formel H₂O?",
                options=["Gleiche Gasvolumina enthalten gleich viele Teilchen; auf 2 H₂ kommt also 1 O₂.",
                         "Weil Wasserstoff leichter ist.",
                         "Weil Sauerstoff doppelt so schwer ist."],
                answer=0,
                hints=["Was sagt das Volumen über die Teilchenzahl?",
                       "Bei gleichen Bedingungen: dasselbe.",
                       "Also 2 H₂-Moleküle auf 1 O₂-Molekül."],
                solution="Gleiche Volumina enthalten gleich viele Teilchen. 2 : 1 im Volumen heißt 2 H₂ auf 1 O₂. Daraus entstehen 2 H₂O — jedes mit zwei H-Atomen und einem O-Atom.",
                tags=["wasser", "erklaeren", "msa"], spiral=["K-QUANT"]),
        aufgabe("WA02-C3-012", "C", 3, "multi",
                "Bei der Elektrolyse entstehen 112 mL Wasserstoff (Normbedingungen, V_m = 22,4 L/mol).",
                fields=[
                    {"label": "Stoffmenge des Wasserstoffs in mmol", "answer": 5, "unit_label": "mmol", "tolerance": 0.2},
                    {"label": "Sauerstoffvolumen", "answer": 56, "unit_label": "mL", "tolerance": 1},
                    {"label": "Masse des zersetzten Wassers", "answer": 90, "unit_label": "mg", "tolerance": 3}
                ],
                hints=["112 mL = 0,112 L; n = 0,112 : 22,4.",
                       "Sauerstoff: die Hälfte des Wasserstoffvolumens.",
                       "n(H₂O) = n(H₂) = 5 mmol; m = n · 18 g/mol."],
                solution="n(H₂) = 0,112 L : 22,4 L/mol = 0,005 mol = 5 mmol\nV(O₂) = 112 mL : 2 = 56 mL\nn(H₂O) = 5 mmol → m = 0,005 mol · 18 g/mol = 0,09 g = 90 mg",
                tags=["wasser", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("WA02-C3-013", "C", 3, "choice",
                "Warum ist die Elektrolyse von Wasser trotz hohen Energiebedarfs technisch interessant?",
                options=["Mit überschüssigem Strom lässt sich Wasserstoff als speicherbarer Energieträger gewinnen.",
                         "Weil dabei Energie gewonnen wird.",
                         "Weil sie Trinkwasser erzeugt."],
                answer=0,
                hints=["Wozu braucht man Wasserstoff?",
                       "Als Energieträger.",
                       "Strom lässt sich schlecht speichern, Wasserstoff gut."],
                solution="Die Elektrolyse verbraucht Energie — gewinnt keine. Ihr Nutzen liegt darin, schlecht speicherbaren Strom in speicherbaren Wasserstoff umzuwandeln, der später über die Knallgasreaktion wieder Energie liefert.",
                misconceptions=[fv("energie_gewonnen", 1,
                                   "Eine endotherme Reaktion liefert keine Energie. Der Nutzen liegt in der Speicherbarkeit.")],
                tags=["wasser", "bewerten", "msa"]),
        aufgabe("WA02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Weil Wasser zerlegbar ist, ist es ein Gemisch.“ Wie bewertest du das?",
                options=["Falsch — Wasser lässt sich nur chemisch zerlegen und hat feste Massenverhältnisse; das kennzeichnet eine Verbindung.",
                         "Richtig — was zerlegbar ist, ist ein Gemisch.",
                         "Falsch — Wasser ist gar nicht zerlegbar."],
                answer=0,
                hints=["Wie wird Wasser zerlegt?",
                       "Mit Strom — also chemisch.",
                       "Ein Gemisch ließe sich physikalisch trennen."],
                solution="Ein Gemisch lässt sich physikalisch trennen, etwa durch Destillation. Wasser braucht dagegen eine chemische Reaktion und liefert dabei immer dasselbe Verhältnis 2 : 1. Beides kennzeichnet eine Verbindung.",
                misconceptions=[fv("trennverfahren_verwechselt", 1,
                                   "Auch Verbindungen lassen sich zerlegen — nur chemisch, nicht physikalisch.",
                                   "trennverfahren_verwechselt")],
                tags=["wasser", "bewerten", "msa"], spiral=["K-STOF"])
    ]
})

E.append({
    "unit": "WA-03",
    "title": "Von der Wortgleichung zur Reaktionsgleichung",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["die Reaktionsgleichung", "der Koeffizient", "der Index", "das Ausgleichen",
                     "die Atombilanz", "die Formeleinheit"],
    "worterklaerungen": {
        "Koeffizient": "Die Zahl vor einer Formel. Sie sagt, wie viele Teilchen gemeint sind.",
        "Index": "Die kleine Zahl in einer Formel. Sie gehört zum Stoff und darf nicht verändert werden.",
        "Ausgleichen": "Koeffizienten so setzen, dass links und rechts gleich viele Atome stehen."
    },
    "can_do": {
        "A": "Ich zähle Atome in einer Formel und erkenne, ob eine Gleichung ausgeglichen ist.",
        "B": "Ich gleiche einfache Reaktionsgleichungen aus.",
        "C": "Ich gleiche mehrstufige Gleichungen systematisch aus und begründe das Vorgehen."
    },
    "lernkarten": {
        "A": karte("Links und rechts gleich viele",
                   "In einer Reaktionsgleichung müssen links und rechts gleich viele Atome stehen.",
                   ["Es geht kein Atom verloren.", "Dafür setzt man Zahlen vor die Formeln."],
                   "Zähle jede Atomsorte einzeln.",
                   visual=anim("ausgleichen", "A"),
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "H₂ + O₂ → H₂O ausgleichen.",
                             "schritte": ["Rechts 2 H₂O — jetzt stimmt der Sauerstoff.",
                                          "Links 2 H₂ — jetzt stimmt der Wasserstoff."],
                             "ergebnis": "2 H₂ + O₂ → 2 H₂O"}),
        "B": karte("So wird ausgeglichen",
                   "Ausgleichen ist kein Raten. Es gibt eine Reihenfolge, die fast immer zum Ziel führt.",
                   ["Erst die Atomsorte, die nur in je einem Stoff links und rechts vorkommt.",
                    "Sauerstoff und Wasserstoff zuletzt — sie stecken meist in mehreren Stoffen.",
                    "Nur Koeffizienten ändern, niemals Indizes: Aus H₂O darf kein H₂O₂ werden, das wäre ein anderer Stoff.",
                    "Am Ende jede Atomsorte noch einmal einzeln nachzählen."],
                   "Nur die Zahlen VOR den Formeln dürfen sich ändern.",
                   visual=anim("ausgleichen", "B")),
        "C": karte("Systematisch statt probierend",
                   "Bei größeren Gleichungen führt Probieren nicht weiter. Ein festes Vorgehen schon.",
                   ["Bei Verbrennungen organischer Stoffe: erst Kohlenstoff, dann Wasserstoff, zuletzt Sauerstoff.",
                    "Ergibt sich für Sauerstoff ein Halbes, wird die gesamte Gleichung verdoppelt.",
                    "Kommt eine Atomgruppe unverändert auf beiden Seiten vor — etwa SO₄ —, wird sie als Einheit gezählt statt Atom für Atom.",
                    "Die Probe am Ende ist kein Zierrat: Sie ist der einzige Beleg, dass die Gleichung stimmt."],
                   "Erst das Seltene, dann Wasserstoff, zuletzt Sauerstoff — und immer die Probe.",
                   visual=anim("ausgleichen", "C"))
    },
    "formelkarte": {"formeln": ["2 H₂ + O₂ → 2 H₂O",
                               "C + O₂ → CO₂",
                               "CH₄ + 2 O₂ → CO₂ + 2 H₂O",
                               "2 Mg + O₂ → 2 MgO"],
                    "saetze": ["Nur Koeffizienten ändern, nie die Indizes.",
                               "Reihenfolge: seltene Atomsorte → Wasserstoff → Sauerstoff.",
                               "Ergibt sich ein Halbes, alles verdoppeln.",
                               "Zum Schluss jede Atomsorte einzeln nachzählen."]},
    "tasks": [
        aufgabe("WA03-A1-001", "A", 1, "numeric",
                "Wie viele Sauerstoffatome stehen in 3 H₂O?",
                answer=3, tolerance=0,
                hints=["Jedes H₂O hat ein O-Atom.", "Es sind 3 Moleküle.", "3 O-Atome."],
                solution="3 · 1 = 3 Sauerstoffatome.",
                tags=["gleichungen"], spiral=["K-BIND"]),
        aufgabe("WA03-A2-002", "A", 2, "numeric",
                "Wie viele Wasserstoffatome stehen in 2 H₂?",
                answer=4, tolerance=0,
                hints=["Jedes H₂ hat zwei H-Atome.", "2 · 2.", "4."],
                solution="2 · 2 = 4 Wasserstoffatome.",
                misconceptions=[fv("koeffizient_ignoriert", 2,
                                   "Die 2 vor der Formel verdoppelt das ganze Molekül.",
                                   "summenformel_falsch_gelesen")],
                tags=["gleichungen"], spiral=["K-BIND"]),
        aufgabe("WA03-A3-003", "A", 3, "numeric",
                "2 H₂ + O₂ → ? H₂O. Welche Zahl fehlt?",
                answer=2, tolerance=0,
                visual=anim("ausgleichen", "A"),
                hints=["Zähle die Wasserstoffatome links: 2 · 2 = 4.",
                       "Rechts hat jedes H₂O zwei H-Atome.",
                       "4 : 2 = 2."],
                solution="Links stehen 4 H-Atome. Rechts braucht es 2 H₂O, um ebenfalls 4 zu haben. Der Sauerstoff stimmt dann auch: 2 links, 2 rechts.",
                tags=["gleichungen"], spiral=["K-REAK"]),
        aufgabe("WA03-A4-004", "A", 4, "choice",
                "Was darfst du beim Ausgleichen verändern?",
                options=["Nur die Zahlen vor den Formeln.", "Auch die kleinen Zahlen in den Formeln.", "Alles."],
                answer=0, visual=anim("ausgleichen", "A"),
                hints=["Die kleine Zahl gehört zum Stoff.",
                       "Wer sie ändert, erfindet einen anderen Stoff.",
                       "Nur die Zahlen davor."],
                solution="Nur Koeffizienten — die Zahlen vor den Formeln. Der Index gehört zum Stoff: Aus H₂O würde sonst H₂O₂, also Wasserstoffperoxid.",
                misconceptions=[fv("index_statt_koeffizient", 1,
                                   "Die kleine Zahl gehört zum Stoff. Änderst du sie, steht dort ein anderer Stoff.",
                                   "index_statt_koeffizient")],
                tags=["gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA03-B1-005", "B", 1, "numeric",
                "? Mg + O₂ → 2 MgO. Welcher Koeffizient fehlt links?",
                answer=2, tolerance=0,
                hints=["Rechts stehen 2 MgO.", "Das sind 2 Mg-Atome.", "Also links 2 Mg."],
                solution="Rechts stehen 2 Magnesiumatome, also links ebenfalls 2: 2 Mg + O₂ → 2 MgO. Der Sauerstoff stimmt mit 2 auf beiden Seiten.",
                tags=["gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA03-B2-006", "B", 2, "numeric",
                "CH₄ + ? O₂ → CO₂ + 2 H₂O. Welcher Koeffizient fehlt?",
                answer=2, tolerance=0,
                hints=["Zähle die O-Atome rechts: 2 aus CO₂ und 2 aus dem Wasser.",
                       "Zusammen 4.",
                       "4 : 2 = 2 Sauerstoffmoleküle."],
                solution="Rechts: 2 O-Atome im CO₂ plus 2 im Wasser = 4. Links liefert jedes O₂ zwei Atome, also 2 O₂.",
                misconceptions=[fv("nur_teil_berechnet", 1,
                                   "Du hast nur das CO₂ gezählt. Auch die O-Atome im Wasser gehören dazu.")],
                tags=["gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA03-B2-007", "B", 2, "choice",
                "Ein Schüler gleicht so aus: H₂ + O₂ → H₂O₂. Was ist der Fehler?",
                options=["Er hat den Index verändert und damit einen anderen Stoff erfunden.",
                         "Die Gleichung ist richtig.",
                         "Er hat einen Koeffizienten vergessen."],
                answer=0,
                hints=["Vergleiche H₂O und H₂O₂.",
                       "Das sind zwei verschiedene Stoffe.",
                       "Der Index darf nicht verändert werden."],
                solution="H₂O₂ ist Wasserstoffperoxid, ein anderer Stoff als Wasser. Die Gleichung ist zwar zahlenmäßig ausgeglichen, beschreibt aber eine andere Reaktion. Indizes dürfen nie verändert werden.",
                misconceptions=[fv("index_statt_koeffizient", 1,
                                   "Zahlenmäßig stimmt es — inhaltlich steht dort ein anderer Stoff.",
                                   "index_statt_koeffizient", 2)],
                tags=["gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA03-B3-008", "B", 3, "multi",
                "Gleiche aus: ? Fe + ? O₂ → 2 Fe₂O₃",
                fields=[
                    {"label": "Koeffizient vor Fe", "answer": 4, "tolerance": 0},
                    {"label": "Koeffizient vor O₂", "answer": 3, "tolerance": 0}
                ],
                hints=["Rechts stehen 2 · 2 = 4 Eisenatome.",
                       "Rechts stehen 2 · 3 = 6 Sauerstoffatome.",
                       "6 : 2 = 3 Sauerstoffmoleküle."],
                solution="4 Fe + 3 O₂ → 2 Fe₂O₃\nProbe: Fe 4 = 4, O 6 = 6.",
                tags=["gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA03-B3-009", "B", 3, "numeric",
                "2 C₂H₆ + ? O₂ → 4 CO₂ + 6 H₂O. Welcher Koeffizient fehlt?",
                answer=7, tolerance=0,
                hints=["Zähle die O-Atome rechts: 4 · 2 = 8 und 6 · 1 = 6.",
                       "Zusammen 14.",
                       "14 : 2 = 7."],
                solution="Rechts: 8 O-Atome aus CO₂ plus 6 aus H₂O = 14. Links liefert jedes O₂ zwei Atome: 14 : 2 = 7 O₂.",
                tags=["gleichungen", "msa"], spiral=["K-REAK"]),
        aufgabe("WA03-B4-010", "B", 4, "choice",
                "In welcher Reihenfolge gleicht man eine Verbrennungsgleichung sinnvoll aus?",
                options=["Kohlenstoff, dann Wasserstoff, zuletzt Sauerstoff.",
                         "Sauerstoff, dann Kohlenstoff, zuletzt Wasserstoff.",
                         "Die Reihenfolge ist gleichgültig."],
                answer=0,
                hints=["Womit fängt man an?",
                       "Mit der Sorte, die nur in einem Stoff links und rechts vorkommt.",
                       "Sauerstoff steckt in mehreren Produkten."],
                solution="Kohlenstoff kommt links und rechts in je einem Stoff vor, Wasserstoff ebenso. Sauerstoff steckt dagegen in beiden Produkten — deshalb kommt er zuletzt, wenn alles andere schon feststeht.",
                tags=["gleichungen", "msa"], spiral=["K-REAK"]),
        aufgabe("WA03-C2-011", "C", 2, "numeric",
                "Beim Ausgleichen von C₂H₆ + O₂ → CO₂ + H₂O ergibt sich für O₂ zunächst 3,5. Mit welcher Zahl multipliziert man die ganze Gleichung?",
                answer=2, tolerance=0,
                hints=["Halbe Moleküle gibt es nicht.",
                       "Womit wird 3,5 zu einer ganzen Zahl?",
                       "Mit 2."],
                solution="3,5 · 2 = 7. Die gesamte Gleichung wird verdoppelt: 2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O.",
                tags=["gleichungen", "msa"], spiral=["K-REAK"]),
        aufgabe("WA03-C3-012", "C", 3, "multi",
                "Gleiche aus: ? Al + ? O₂ → ? Al₂O₃",
                fields=[
                    {"label": "Koeffizient vor Al", "answer": 4, "tolerance": 0},
                    {"label": "Koeffizient vor O₂", "answer": 3, "tolerance": 0},
                    {"label": "Koeffizient vor Al₂O₃", "answer": 2, "tolerance": 0}
                ],
                hints=["Setze zunächst 2 vor Al₂O₃, damit die O-Zahl gerade wird.",
                       "Dann stehen rechts 4 Al und 6 O.",
                       "Links also 4 Al und 3 O₂."],
                solution="4 Al + 3 O₂ → 2 Al₂O₃\nProbe: Al 4 = 4, O 6 = 6.",
                tags=["gleichungen", "msa"], spiral=["K-REAK"]),
        aufgabe("WA03-C3-013", "C", 3, "choice",
                "Warum darf man bei H₂SO₄ die Gruppe SO₄ als Einheit zählen, wenn sie unverändert auf beiden Seiten steht?",
                options=["Weil sie als Ganzes erhalten bleibt — das Nachzählen jedes Atoms führt zum selben Ergebnis, dauert aber länger.",
                         "Weil SO₄ ein einzelnes Atom ist.",
                         "Weil Sauerstoff nicht mitzählt."],
                answer=0,
                hints=["Ändert sich innerhalb der Gruppe etwas?",
                       "Nein, sie bleibt vollständig erhalten.",
                       "Dann darf man sie als Block behandeln."],
                solution="Bleibt eine Atomgruppe unverändert erhalten, führt das Zählen als Einheit zum selben Ergebnis wie das Zählen jedes Atoms — nur schneller. Sobald die Gruppe aufgebrochen wird, muss wieder atomweise gezählt werden.",
                tags=["gleichungen", "msa"], spiral=["K-BIND"]),
        aufgabe("WA03-C4-014", "C", 4, "choice",
                "Eine ausgeglichene Gleichung ist gefunden. Ein Schüler fragt: „Beweist das, dass die Reaktion wirklich so abläuft?“ Wie antwortest du?",
                options=["Nein — das Ausgleichen sichert nur die Atombilanz. Ob die Produkte stimmen, zeigt allein der Versuch.",
                         "Ja, eine ausgeglichene Gleichung ist immer richtig.",
                         "Nein, ausgeglichene Gleichungen sind nie richtig."],
                answer=0,
                hints=["Was prüft das Ausgleichen?",
                       "Nur die Zahl der Atome.",
                       "Welche Stoffe entstehen, sagt es nicht."],
                solution="Ausgleichen sichert allein, dass links und rechts gleich viele Atome stehen. H₂ + O₂ → H₂O₂ lässt sich ebenfalls ausgleichen und beschreibt trotzdem eine andere Reaktion. Welche Produkte entstehen, entscheidet der Versuch.",
                tags=["gleichungen", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

if __name__ == "__main__":
    schreiben("wa", E, "Bereich WA · Einheiten 2 und 3")
