# -*- coding: utf-8 -*-
"""Bereich FC · Faszination Chemie — Einheiten FC-07 und FC-08."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

# ============================================================
# FC-07 · Oxidation: Verbrennungsprodukte sind Oxide
# ============================================================
E.append({
    "unit": "FC-07",
    "title": "Oxidation: Verbrennungsprodukte sind Oxide",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.4"],
    "klasse": 7,
    "wortspeicher": ["die Oxidation", "das Oxid", "der Sauerstoff", "die Verbrennung",
                     "die Wortgleichung", "das Metalloxid", "das Nichtmetalloxid"],
    "worterklaerungen": {
        "Oxidation": "Ein Stoff reagiert mit Sauerstoff.",
        "Oxid": "Ein Stoff, der Sauerstoff enthält. Er entsteht bei der Oxidation.",
        "Wortgleichung": "Die Reaktion in Worten: Edukte, Pfeil, Produkte."
    },
    "can_do": {
        "A": "Ich benenne das Produkt einer Verbrennung als Oxid und lese eine Wortgleichung.",
        "B": "Ich stelle Wortgleichungen für Verbrennungen auf und benenne die Oxide korrekt.",
        "C": "Ich ordne Oxide als Metall- oder Nichtmetalloxid ein und leite ihr Verhalten in Wasser ab."
    },
    "lernkarten": {
        "A": karte("Was beim Verbrennen entsteht",
                   "Beim Verbrennen reagiert ein Stoff mit Sauerstoff.",
                   ["Das neue Produkt heißt Oxid.", "Der Name sagt: Der Stoff enthält Sauerstoff."],
                   "Verbrennen heißt: Reaktion mit Sauerstoff. Es entsteht ein Oxid.",
                   beispiel={"titel": "Magnesium verbrennt",
                             "aufgabe": "Magnesium brennt an der Luft.",
                             "schritte": ["Magnesium reagiert mit Sauerstoff.",
                                          "Es entsteht ein weißes Pulver.",
                                          "Das Pulver heißt Magnesiumoxid."],
                             "ergebnis": "Magnesium + Sauerstoff → Magnesiumoxid"}),
        "B": karte("Wortgleichungen aufstellen",
                   "Eine Wortgleichung ist der kürzeste ehrliche Bericht über eine Reaktion: links das, was da war, rechts das, was entstanden ist, dazwischen ein Pfeil.",
                   ["Der Pfeil bedeutet „reagiert zu“, nicht „ist gleich“. Er hat eine Richtung.",
                    "Der Name des Oxids setzt sich zusammen: Element + „oxid“, also Kupferoxid, Schwefeldioxid, Kohlenstoffdioxid.",
                    "Vorsilben wie „di“ oder „tri“ sagen, wie viele Sauerstoffatome gebunden sind — Kohlenstoffdioxid enthält zwei."],
                   "Links Edukte, rechts Produkte, dazwischen der Pfeil mit Richtung.",
                   visual=anim("nachweise", "B")),
        "C": karte("Metalloxide und Nichtmetalloxide",
                   "Alle Oxide enthalten Sauerstoff — und verhalten sich trotzdem gegensätzlich, sobald sie ins Wasser kommen. Die Einteilung nach Metall und Nichtmetall sagt das voraus.",
                   ["Metalloxide (Magnesiumoxid, Calciumoxid) bilden mit Wasser Laugen. Der Indikator wird blau.",
                    "Nichtmetalloxide (Schwefeldioxid, Kohlenstoffdioxid) bilden mit Wasser Säuren. Der Indikator wird rot.",
                    "Damit erklärt sich der saure Regen: Schwefeldioxid aus Verbrennungsprozessen bildet mit Regenwasser schweflige Säure."],
                   "Metalloxid + Wasser → Lauge. Nichtmetalloxid + Wasser → Säure.",
                   visual={"type": "phskala", "marken": [{"wert": 4, "stoff": "SO₂ in Wasser"},
                                                         {"wert": 11, "stoff": "CaO in Wasser"}],
                           "alt": "pH-Skala mit einer sauren und einer alkalischen Marke."})
    },
    "formelkarte": {"formeln": ["Stoff + Sauerstoff → Oxid",
                               "Magnesium + Sauerstoff → Magnesiumoxid",
                               "Kohlenstoff + Sauerstoff → Kohlenstoffdioxid"],
                    "saetze": ["Oxidation = Reaktion mit Sauerstoff.",
                               "Der Pfeil bedeutet „reagiert zu“ und hat eine Richtung.",
                               "Metalloxid + Wasser → Lauge.",
                               "Nichtmetalloxid + Wasser → Säure."]},
    "tasks": [
        aufgabe("FC07-A1-001", "A", 1, "choice",
                "Magnesium verbrennt an der Luft. Wie heißt das Produkt?",
                options=["Magnesiumoxid", "Magnesiumsulfid", "Magnesiumchlorid"], answer=0,
                hints=["Womit reagiert der Stoff beim Verbrennen?", "Mit Sauerstoff.", "Das Produkt heißt Oxid."],
                solution="Beim Verbrennen reagiert Magnesium mit Sauerstoff. Das Produkt ist Magnesiumoxid.",
                tags=["oxidation"], spiral=["W-SYMB"]),
        aufgabe("FC07-A2-002", "A", 2, "choice",
                "Was bedeutet der Pfeil in „Eisen + Sauerstoff → Eisenoxid“?",
                options=["reagiert zu", "ist gleich", "ist ungefähr"], answer=0,
                hints=["Der Pfeil zeigt in eine Richtung.", "Er ist kein Gleichheitszeichen.", "Er heißt „reagiert zu“."],
                solution="Der Pfeil bedeutet „reagiert zu“. Er hat eine Richtung: links stehen die Ausgangsstoffe, rechts das Produkt.",
                misconceptions=[fv("pfeil_als_gleichheitszeichen", 1,
                                   "Der Pfeil ist kein Gleichheitszeichen. Er zeigt eine Richtung an.",
                                   "edukt_produkt_vertauscht")],
                tags=["oxidation", "fachsprache"], spiral=["W-GLEI"]),
        aufgabe("FC07-A3-003", "A", 3, "assign",
                "Ordne jedem Stoff sein Verbrennungsprodukt zu.",
                slots=["Kohlenstoff", "Schwefel", "Kupfer"],
                values=["Kohlenstoffdioxid", "Schwefeldioxid", "Kupferoxid"],
                answer=[0, 1, 2],
                hints=["Der Name des Produkts enthält den Namen des Stoffes.",
                       "Und dazu „oxid“.",
                       "Kohlenstoff → Kohlenstoffdioxid."],
                solution="Kohlenstoff → Kohlenstoffdioxid.\nSchwefel → Schwefeldioxid.\nKupfer → Kupferoxid.",
                tags=["oxidation"], spiral=["W-SYMB"]),
        aufgabe("FC07-A4-004", "A", 4, "choice",
                "Eine Kerze brennt in einem geschlossenen Glas und geht nach einiger Zeit aus. Warum?",
                options=["Der Sauerstoff ist verbraucht.", "Das Wachs ist alle.", "Es ist zu kalt geworden."],
                answer=0,
                hints=["Was braucht die Verbrennung außer Wachs?", "Sauerstoff.", "Im Glas ist nur wenig davon."],
                solution="Im geschlossenen Glas ist die Sauerstoffmenge begrenzt. Ist er verbraucht, erlischt die Flamme — obwohl noch Wachs da ist.",
                tags=["oxidation"], spiral=["W-GLEI"]),
        aufgabe("FC07-B1-005", "B", 1, "choice",
                "Welche Wortgleichung ist richtig aufgestellt?",
                options=["Eisen + Sauerstoff → Eisenoxid",
                         "Eisenoxid → Eisen + Sauerstoff (bei der Verbrennung)",
                         "Eisen → Eisenoxid + Sauerstoff"],
                answer=0,
                hints=["Was ist am Anfang da, was entsteht?",
                       "Eisen und Sauerstoff sind die Edukte.",
                       "Eisenoxid entsteht."],
                solution="Bei der Verbrennung sind Eisen und Sauerstoff die Edukte, Eisenoxid ist das Produkt.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Das ist die Rückreaktion (Reduktion). Bei der Verbrennung entsteht das Oxid.",
                                   "edukt_produkt_vertauscht", 0)],
                tags=["oxidation", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC07-B2-006", "B", 2, "choice",
                "Eisenwolle wird verbrannt und auf einer Waage gewogen. Was zeigt die Waage danach?",
                options=["mehr als vorher — der gebundene Sauerstoff wird mitgewogen",
                         "weniger als vorher — etwas ist verbrannt",
                         "genau dasselbe"],
                answer=0, visual=anim("massenerhaltung", "B"),
                hints=["Woher kommt der Sauerstoff im Oxid?",
                       "Aus der Luft.",
                       "Er wird jetzt mitgewogen."],
                solution="Der Sauerstoff aus der Luft wird im Oxid gebunden und liegt danach mit auf der Waage. Die Masse nimmt deshalb zu.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "„Verbrannt“ heißt nicht „verschwunden“. Der gebundene Sauerstoff kommt hinzu.",
                                   "masse_verschwindet")],
                tags=["oxidation", "masse", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC07-B2-007", "B", 2, "choice",
                "Eine Kerze verbrennt offen auf einer Waage. Die Anzeige sinkt. Widerspricht das dem Gesetz von der Erhaltung der Masse?",
                options=["Nein — die entstehenden Gase entweichen und werden nicht mitgewogen.",
                         "Ja — hier geht Masse verloren.",
                         "Nein — Kerzenwachs hat keine Masse."],
                answer=0,
                hints=["Was entsteht bei der Verbrennung von Wachs?",
                       "Kohlenstoffdioxid und Wasserdampf.",
                       "Beide sind gasförmig und entweichen."],
                solution="Es entstehen Kohlenstoffdioxid und Wasserdampf. Beide entweichen und liegen nicht mehr auf der Waage. Im geschlossenen Gefäß bliebe die Masse konstant.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Die Masse geht nicht verloren, sie verlässt nur die Waage. Im geschlossenen Gefäß bliebe sie gleich.",
                                   "masse_verschwindet", 1)],
                tags=["oxidation", "masse", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC07-B3-008", "B", 3, "numeric",
                "24 g Magnesium reagieren mit 16 g Sauerstoff. Wie viel Gramm Magnesiumoxid entstehen?",
                answer=40, unit_label="g", tolerance=0,
                hints=["Es geht keine Masse verloren.", "24 + 16.", "40 g."],
                solution="24 g + 16 g = 40 g Magnesiumoxid. Die Masse der Edukte ist gleich der Masse des Produkts.",
                misconceptions=[fv("masse_verschwindet", 8,
                                   "Du hast subtrahiert. Bei einer Vereinigung addieren sich die Massen.",
                                   "masse_verschwindet")],
                tags=["oxidation", "rechnen", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC07-B3-009", "B", 3, "numeric",
                "Aus 32 g Kupfer entstehen 40 g Kupferoxid. Wie viel Gramm Sauerstoff wurden gebunden?",
                answer=8, unit_label="g", tolerance=0,
                hints=["Die Massen der Edukte ergeben zusammen das Produkt.",
                       "40 − 32.",
                       "8 g."],
                solution="40 g − 32 g = 8 g Sauerstoff wurden aus der Luft gebunden.",
                misconceptions=[fv("masse_verschwindet", 72,
                                   "Du hast addiert. Der Sauerstoff ist der fehlende Teil zwischen Kupfer und Kupferoxid.",
                                   "masse_verschwindet")],
                tags=["oxidation", "rechnen", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC07-B4-010", "B", 4, "assign",
                "Ordne jedes Oxid seiner Gruppe zu.",
                slots=["Magnesiumoxid", "Schwefeldioxid", "Calciumoxid"],
                values=["Metalloxid", "Nichtmetalloxid", "Metalloxid (zweites)"],
                answer=[0, 1, 2],
                hints=["Ist der Partner des Sauerstoffs ein Metall?",
                       "Magnesium und Calcium sind Metalle.",
                       "Schwefel ist ein Nichtmetall."],
                solution="Magnesiumoxid und Calciumoxid sind Metalloxide, Schwefeldioxid ist ein Nichtmetalloxid.",
                tags=["oxidation", "einordnen"], spiral=["W-TEIL"]),
        aufgabe("FC07-C2-011", "C", 2, "choice",
                "Calciumoxid wird in Wasser gegeben, dann wird Universalindikator zugesetzt. Welche Farbe erwartest du?",
                options=["blau — es entsteht eine Lauge", "rot — es entsteht eine Säure", "grün — die Lösung bleibt neutral"],
                answer=0,
                hints=["Ist Calcium ein Metall oder ein Nichtmetall?",
                       "Ein Metall.",
                       "Metalloxid + Wasser → Lauge."],
                solution="Calcium ist ein Metall, Calciumoxid also ein Metalloxid. Mit Wasser bildet es Calciumhydroxid — eine Lauge. Der Indikator wird blau.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "Rot ergäbe ein Nichtmetalloxid. Metalloxide bilden Laugen.",
                                   "saeure_lauge_vertauscht", 0)],
                tags=["oxidation", "einordnen", "msa"], spiral=["W-LOES"]),
        aufgabe("FC07-C3-012", "C", 3, "choice",
                "Beim Verbrennen schwefelhaltiger Kohle entsteht Schwefeldioxid. Wie hängt das mit saurem Regen zusammen?",
                options=["Schwefeldioxid ist ein Nichtmetalloxid und bildet mit Regenwasser eine Säure.",
                         "Schwefeldioxid löst den Kalk aus dem Regen.",
                         "Schwefeldioxid kühlt den Regen ab."],
                answer=0,
                hints=["Zu welcher Gruppe gehört Schwefeldioxid?",
                       "Schwefel ist ein Nichtmetall.",
                       "Nichtmetalloxid + Wasser → Säure."],
                solution="Schwefel ist ein Nichtmetall. Schwefeldioxid reagiert mit Regenwasser zu schwefliger Säure — der Regen wird sauer und greift Bauwerke und Böden an.",
                tags=["oxidation", "umwelt", "msa"], spiral=["W-LOES"]),
        aufgabe("FC07-C3-013", "C", 3, "multi",
                "Bei der Verbrennung von 12 g Kohlenstoff entstehen 44 g Kohlenstoffdioxid.",
                fields=[
                    {"label": "gebundene Sauerstoffmasse", "answer": 32, "unit_label": "g", "tolerance": 0.01,
                     "misconceptions": [fv("masse_verschwindet", 56,
                                           "Du hast addiert. Der Sauerstoff ist die Differenz zwischen Produkt und Kohlenstoff.",
                                           "masse_verschwindet")]},
                    {"label": "Massenanteil des Kohlenstoffs im Produkt in Prozent", "answer": 27.27, "unit_label": "%", "tolerance": 0.1}
                ],
                hints=["Sauerstoff = Produktmasse − Kohlenstoffmasse.",
                       "44 − 12 = 32 g.",
                       "Anteil = 12 : 44 · 100 %."],
                solution="m(O) = 44 g − 12 g = 32 g\nw(C) = 12 g : 44 g = 0,2727 → 27,27 %",
                tags=["oxidation", "rechnen", "msa"], spiral=["W-GLEI", "W-RECH"]),
        aufgabe("FC07-C4-014", "C", 4, "choice",
                "Ein Schüler behauptet: „Beim Verbrennen wird Masse in Energie umgewandelt, deshalb wird die Kerze leichter.“ Wie bewertest du das?",
                options=["Falsch — die Massenabnahme erklärt sich vollständig durch entweichende Gase.",
                         "Richtig — Energie und Masse sind dasselbe.",
                         "Falsch — die Kerze wird gar nicht leichter."],
                answer=0,
                hints=["Wohin gehen Kohlenstoffdioxid und Wasserdampf?",
                       "In die Luft.",
                       "Im geschlossenen Gefäß bliebe die Masse gleich."],
                solution="Die Massenabnahme lässt sich vollständig durch die entweichenden Gase erklären. Der Beweis: Im geschlossenen Gefäß bleibt die Masse konstant. Eine messbare Umwandlung von Masse in Energie gibt es bei chemischen Reaktionen nicht.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Bei chemischen Reaktionen bleibt die Masse erhalten. Der geschlossene Versuch zeigt es.",
                                   "masse_verschwindet", 1)],
                tags=["oxidation", "bewerten", "msa"], spiral=["W-GLEI"])
    ]
})

# ============================================================
# FC-08 · Wortgleichung, Massenerhaltung & Prüfungstraining
# ============================================================
E.append({
    "unit": "FC-08",
    "title": "Wortgleichung, Massenerhaltung & Prüfungstraining",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3"],
    "klasse": 7,
    "wortspeicher": ["das Gesetz von der Erhaltung der Masse", "das Edukt", "das Produkt",
                     "das geschlossene System", "der Operator"],
    "worterklaerungen": {
        "geschlossenes System": "Ein Gefäß, aus dem nichts entweichen kann.",
        "Operator": "Das Fragewort einer Aufgabe. Es sagt, was du tun sollst."
    },
    "can_do": {
        "A": "Ich weiß, dass bei einer Reaktion keine Masse verloren geht, und rechne einfache Bilanzen.",
        "B": "Ich erkläre scheinbare Massenänderungen und stelle Wortgleichungen sicher auf.",
        "C": "Ich erkenne an Signalwörtern, was eine Aufgabe verlangt, und beantworte sie vollständig."
    },
    "lernkarten": {
        "A": karte("Nichts geht verloren",
                   "Bei einer Reaktion geht keine Masse verloren.",
                   ["Was vorher da war, ist nachher noch da.", "Es ist nur anders verbunden."],
                   "Masse vorher = Masse nachher.",
                   visual=anim("massenerhaltung", "A"),
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "7 g Eisen und 4 g Schwefel reagieren.",
                             "schritte": ["7 g + 4 g", "= 11 g"],
                             "ergebnis": "11 g Eisensulfid",
                             "luecke": {"schritt": 1, "wert": 11, "einheit": "g"}}),
        "B": karte("Wenn die Waage etwas anderes sagt",
                   "Das Gesetz von der Erhaltung der Masse gilt ausnahmslos. Trotzdem zeigt die Waage im Unterricht regelmäßig etwas anderes — und das hat immer denselben Grund.",
                   ["Nimmt die Masse zu, wurde etwas aus der Luft gebunden: meist Sauerstoff.",
                    "Nimmt sie ab, ist etwas entwichen: meist ein Gas.",
                    "Im geschlossenen Gefäß verschwindet der scheinbare Widerspruch sofort."],
                   "Die Masse ändert sich nie. Zu eng gezogen war die Grenze, innerhalb derer gewogen wurde.",
                   visual=anim("massenerhaltung", "B")),
        "C": karte("Was die Aufgabe verlangt",
                   "In der Prüfung entscheidet oft nicht das Wissen, sondern das Lesen. Jeder Operator verlangt eine bestimmte Form der Antwort — und wer auf „begründe“ nur beschreibt, verliert Punkte für Wissen, das er hat.",
                   ["„Nenne“ und „gib an“ verlangen eine Aufzählung ohne Erklärung.",
                    "„Beschreibe“ verlangt ganze Sätze über das, was zu beobachten ist — noch ohne Deutung.",
                    "„Erkläre“ und „begründe“ verlangen eine Ursache: weil …, deshalb …",
                    "„Berechne“ verlangt Ansatz, Rechnung und Ergebnis mit Einheit."],
                   "Erst das Fragewort lesen, dann antworten.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["m(Edukte) = m(Produkte)"],
                    "saetze": ["Bei chemischen Reaktionen bleibt die Gesamtmasse erhalten.",
                               "Massenzunahme: etwas wurde aus der Luft gebunden.",
                               "Massenabnahme: ein Gas ist entwichen.",
                               "nennen · beschreiben · erklären · berechnen — jedes Wort verlangt etwas anderes."]},
    "tasks": [
        aufgabe("FC08-A1-001", "A", 1, "numeric",
                "3 g Kohlenstoff reagieren mit 8 g Sauerstoff. Wie viel Gramm Kohlenstoffdioxid entstehen?",
                answer=11, unit_label="g", tolerance=0,
                hints=["Es geht keine Masse verloren.", "3 + 8.", "11 g."],
                solution="3 g + 8 g = 11 g",
                misconceptions=[fv("masse_verschwindet", 5,
                                   "Du hast subtrahiert. Beide Edukte gehen vollständig in das Produkt ein.",
                                   "masse_verschwindet")],
                tags=["masse"], spiral=["W-GLEI"]),
        aufgabe("FC08-A2-002", "A", 2, "choice",
                "Ein Versuch läuft in einem fest verschlossenen Kolben. Was zeigt die Waage nach der Reaktion?",
                options=["genau dasselbe wie vorher", "mehr als vorher", "weniger als vorher"],
                answer=0, visual=anim("massenerhaltung", "A"),
                hints=["Kann etwas aus dem Kolben heraus?", "Nein, er ist verschlossen.", "Also bleibt die Masse gleich."],
                solution="Aus einem verschlossenen Kolben kann nichts entweichen und nichts hinein. Die Masse bleibt gleich.",
                tags=["masse"], spiral=["W-GLEI"]),
        aufgabe("FC08-A3-003", "A", 3, "numeric",
                "Bei einer Reaktion entstehen 25 g Produkt. Ein Edukt wog 9 g. Wie schwer war das andere?",
                answer=16, unit_label="g", tolerance=0,
                hints=["Beide Edukte ergeben zusammen das Produkt.", "25 − 9.", "16 g."],
                solution="25 g − 9 g = 16 g",
                misconceptions=[fv("masse_verschwindet", 34,
                                   "Du hast addiert. Das zweite Edukt ist der fehlende Teil zum Produkt.",
                                   "masse_verschwindet")],
                tags=["masse"], spiral=["W-GLEI"]),
        aufgabe("FC08-A4-004", "A", 4, "choice",
                "Wozu fordert dich das Wort „Berechne“ auf?",
                options=["Rechnen und das Ergebnis mit Einheit hinschreiben",
                         "Etwas aufzählen", "Etwas beschreiben"],
                answer=0, visual=anim("signalwoerter", "A"),
                hints=["Das Wort sagt, was du tun sollst.", "Es verlangt eine Rechnung.", "Mit Einheit."],
                solution="„Berechne“ verlangt eine Rechnung mit Ansatz und ein Ergebnis mit Einheit.",
                tags=["pruefung", "operatoren"]),
        aufgabe("FC08-B1-005", "B", 1, "choice",
                "Warum nimmt die Masse beim offenen Verbrennen von Eisenwolle zu?",
                options=["Sauerstoff aus der Luft wird gebunden und mitgewogen.",
                         "Das Eisen dehnt sich aus.", "Die Waage wird durch die Wärme ungenau."],
                answer=0, visual=anim("massenerhaltung", "B"),
                hints=["Woraus besteht das Produkt?", "Aus Eisen und Sauerstoff.", "Der Sauerstoff kam aus der Luft."],
                solution="Das Produkt Eisenoxid enthält den Sauerstoff aus der Luft. Er liegt nach der Reaktion mit auf der Waage.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Ausdehnung ändert die Masse nicht. Hinzugekommen ist gebundener Sauerstoff.",
                                   "masse_verschwindet")],
                tags=["masse", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC08-B2-006", "B", 2, "assign",
                "Ordne jedem Operator zu, was er verlangt.",
                slots=["Nenne", "Beschreibe", "Begründe"],
                values=["eine Aufzählung ohne Erklärung", "in Sätzen, was zu beobachten ist", "eine Ursache mit „weil“"],
                answer=[0, 1, 2],
                visual=anim("signalwoerter", "B"),
                hints=["Drei Wörter, drei verschiedene Antwortformen.",
                       "„Nenne“ ist am kürzesten.",
                       "„Begründe“ verlangt eine Ursache."],
                solution="Nenne → Aufzählung.\nBeschreibe → Beobachtung in Sätzen.\nBegründe → Ursache, meist mit „weil“.",
                tags=["pruefung", "operatoren", "bbr"]),
        aufgabe("FC08-B2-007", "B", 2, "numeric",
                "In einem geschlossenen Kolben wiegen Edukte 62,5 g. Nach der Reaktion wird gewogen. Welchen Wert zeigt die Waage?",
                answer=62.5, unit_label="g", tolerance=0.01,
                hints=["Was kann aus einem geschlossenen Kolben heraus?", "Nichts.", "Der Wert bleibt gleich."],
                solution="62,5 g. Im geschlossenen System bleibt die Gesamtmasse unverändert.",
                misconceptions=[fv("masse_verschwindet", 0,
                                   "Auch wenn ein Gas entsteht: Im geschlossenen Kolben bleibt es drin und wird mitgewogen.",
                                   "masse_verschwindet")],
                tags=["masse", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC08-B3-008", "B", 3, "multi",
                "5 g Magnesium verbrennen vollständig. Es entstehen 8,3 g Magnesiumoxid.",
                fields=[
                    {"label": "gebundene Sauerstoffmasse", "answer": 3.3, "unit_label": "g", "tolerance": 0.01},
                    {"label": "Massenanteil des Magnesiums im Oxid in Prozent", "answer": 60.24, "unit_label": "%", "tolerance": 0.2}
                ],
                hints=["Sauerstoff = Produkt − Magnesium.",
                       "8,3 − 5 = 3,3 g.",
                       "Anteil = 5 : 8,3 · 100 %."],
                solution="m(O) = 8,3 g − 5 g = 3,3 g\nw(Mg) = 5 : 8,3 = 0,6024 → 60,24 %",
                tags=["masse", "rechnen", "bbr"], spiral=["W-GLEI", "W-RECH"]),
        aufgabe("FC08-B3-009", "B", 3, "choice",
                "Eine Brausetablette wird in einem offenen Glas Wasser aufgelöst. Die Waage zeigt weniger an. Warum?",
                options=["Es entweicht Kohlenstoffdioxid.", "Das Wasser verdunstet so schnell.", "Die Tablette verschwindet."],
                answer=0,
                hints=["Was sprudelt aus dem Glas?", "Ein Gas.", "Es entweicht und wird nicht mehr gewogen."],
                solution="Beim Auflösen entsteht Kohlenstoffdioxid, das entweicht. Im verschlossenen Gefäß bliebe die Masse gleich.",
                misconceptions=[fv("masse_verschwindet", 2,
                                   "Nichts verschwindet. Das Gas verlässt nur das Glas.",
                                   "masse_verschwindet")],
                tags=["masse", "bbr"], spiral=["W-GLEI"]),
        aufgabe("FC08-B4-010", "B", 4, "choice",
                "Welche Aufgabe verlangt mehr als eine Aufzählung: „Nenne drei Gefahrensymbole“ oder „Erkläre, warum Wasser bei Fettbränden ungeeignet ist“?",
                options=["die zweite — sie verlangt eine Ursache",
                         "die erste — sie verlangt drei Antworten", "beide gleich viel"],
                answer=0, visual=anim("signalwoerter", "B"),
                hints=["Vergleiche die Operatoren.", "„Nenne“ gegen „Erkläre“.", "„Erkläre“ verlangt eine Ursache."],
                solution="„Nenne“ verlangt eine Aufzählung, auch wenn es drei Stück sind. „Erkläre“ verlangt eine Ursache-Wirkungs-Kette — inhaltlich deutlich mehr.",
                tags=["pruefung", "operatoren"]),
        aufgabe("FC08-C2-011", "C", 2, "choice",
                "Bei welchem Versuch lässt sich das Gesetz von der Erhaltung der Masse am überzeugendsten zeigen?",
                options=["Verbrennung von Eisenwolle in einem verschlossenen Kolben",
                         "offenes Verbrennen einer Kerze",
                         "Auflösen von Zucker in Wasser"],
                answer=0,
                hints=["Wo kann nichts entweichen und nichts hinzukommen?",
                       "Im geschlossenen Kolben.",
                       "Und es muss eine chemische Reaktion sein."],
                solution="Nur im geschlossenen System sind alle beteiligten Stoffe auf der Waage. Das Auflösen von Zucker zeigt zwar auch Massenerhaltung, ist aber keine chemische Reaktion und damit kein Beleg für das Gesetz.",
                tags=["masse", "planen", "msa"], spiral=["W-GLEI"]),
        aufgabe("FC08-C3-012", "C", 3, "multi",
                "In einem geschlossenen Kolben (Leermasse 128,0 g) befinden sich 4,0 g Eisen und 2,3 g Schwefel. Nach der Reaktion wird erneut gewogen.",
                fields=[
                    {"label": "Gesamtmasse vor der Reaktion", "answer": 134.3, "unit_label": "g", "tolerance": 0.01},
                    {"label": "Gesamtmasse nach der Reaktion", "answer": 134.3, "unit_label": "g", "tolerance": 0.01,
                     "misconceptions": [fv("masse_verschwindet", 128,
                                           "Der Kolben ist verschlossen — es kann nichts entweichen. Die Masse bleibt gleich.",
                                           "masse_verschwindet")]},
                    {"label": "Masse des gebildeten Eisensulfids", "answer": 6.3, "unit_label": "g", "tolerance": 0.01}
                ],
                hints=["Vorher: Kolben + beide Edukte.",
                       "Im geschlossenen System ändert sich die Gesamtmasse nicht.",
                       "Das Produkt ist die Summe der beiden Edukte."],
                solution="vorher: 128,0 + 4,0 + 2,3 = 134,3 g\nnachher: 134,3 g — nichts kann entweichen\nProdukt: 4,0 + 2,3 = 6,3 g Eisensulfid",
                tags=["masse", "rechnen", "msa"], spiral=["W-GLEI"]),
        aufgabe("FC08-C3-013", "C", 3, "choice",
                "Eine Prüfungsaufgabe lautet: „Erkläre, warum die Masse beim offenen Verbrennen von Eisenwolle zunimmt.“ Welche Antwort ist vollständig?",
                options=["Eisen reagiert mit Sauerstoff aus der Luft zu Eisenoxid; der gebundene Sauerstoff wird mitgewogen, deshalb steigt die Masse.",
                         "Die Masse nimmt zu.",
                         "Eisenwolle wird beim Verbrennen schwarz und brüchig."],
                answer=0,
                hints=["Was verlangt „Erkläre“?",
                       "Eine Ursache, keine Beobachtung.",
                       "Die Antwort braucht ein „weil“ oder „deshalb“."],
                solution="„Erkläre“ verlangt die Ursache. Antwort 2 wiederholt nur die Frage, Antwort 3 beschreibt eine Beobachtung. Nur Antwort 1 nennt Reaktion und Ursache der Massenzunahme.",
                misconceptions=[fv("beschreiben_statt_erklaeren", 2,
                                   "Das ist eine Beschreibung. „Erkläre“ verlangt eine Ursache.")],
                tags=["pruefung", "operatoren", "msa"]),
        aufgabe("FC08-C4-014", "C", 4, "choice",
                "Antoine Lavoisier wog Versuche im geschlossenen Gefäß, seine Vorgänger im offenen. Warum war das entscheidend?",
                options=["Nur im geschlossenen Gefäß werden auch die gasförmigen Beteiligten mitgewogen.",
                         "Geschlossene Gefäße halten die Temperatur konstant.",
                         "Im offenen Gefäß sind Waagen ungenauer."],
                answer=0,
                hints=["Was fehlte den früheren Messungen?",
                       "Die Gase.",
                       "Die wurden schlicht nicht gewogen."],
                solution="Vor Lavoisier wurden Gase nicht mitgewogen — deshalb schienen Massen zu verschwinden oder zu entstehen. Erst der geschlossene Versuch zeigte, dass die Gesamtmasse immer erhalten bleibt. Nicht die Waage war besser, sondern die Grenze richtig gezogen.",
                tags=["masse", "bewerten", "msa"], spiral=["W-GLEI"])
    ]
})

if __name__ == "__main__":
    schreiben("fc", E, "Bereich FC · Einheiten 7 und 8")
