# -*- coding: utf-8 -*-
"""Bereich ME · Metalle — ME-05 bis ME-07."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ME-05",
    "title": "Redoxreaktionen: Oxidation und Reduktion",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["die Oxidation", "die Reduktion", "die Redoxreaktion", "das Oxidationsmittel",
                     "das Reduktionsmittel", "der Elektronenübergang", "die Teilgleichung"],
    "worterklaerungen": {
        "Oxidation": "Abgabe von Elektronen.",
        "Reduktion": "Aufnahme von Elektronen.",
        "Oxidationsmittel": "Der Stoff, der Elektronen aufnimmt und dadurch einen anderen oxidiert.",
        "Reduktionsmittel": "Der Stoff, der Elektronen abgibt."
    },
    "can_do": {
        "A": "Ich weiß, dass bei einer Redoxreaktion Elektronen übergehen.",
        "B": "Ich benenne Oxidation und Reduktion und bestimme Oxidations- und Reduktionsmittel.",
        "C": "Ich stelle Teilgleichungen auf und gleiche die Elektronenzahl aus."
    },
    "lernkarten": {
        "A": karte("Elektronen wechseln die Seite",
                   "Bei manchen Reaktionen wandern Elektronen von einem Teilchen zum anderen.",
                   ["Wer abgibt, wird oxidiert.", "Wer aufnimmt, wird reduziert."],
                   "Abgeben = Oxidation. Aufnehmen = Reduktion.",
                   visual=anim("redox", "A"),
                   beispiel={"titel": "Eisen und Kupfer", "aufgabe": "Ein Eisennagel in Kupfersulfatlösung.",
                             "schritte": ["Eisen gibt Elektronen ab.",
                                          "Kupfer-Ionen nehmen sie auf."],
                             "ergebnis": "Eisen wird oxidiert, Kupfer reduziert."}),
        "B": karte("Beides zugleich",
                   "Oxidation und Reduktion laufen immer gemeinsam ab. Es kann kein Teilchen Elektronen abgeben, ohne dass ein anderes sie aufnimmt.",
                   ["Oxidation ist die Abgabe von Elektronen, Reduktion die Aufnahme.",
                    "Die alte Bedeutung — Aufnahme oder Abgabe von Sauerstoff — ist ein Sonderfall davon. Der Elektronenbegriff ist der allgemeinere.",
                    "Das Reduktionsmittel gibt Elektronen ab und wird dabei selbst oxidiert.",
                    "Das Oxidationsmittel nimmt Elektronen auf und wird dabei selbst reduziert. Diese Namen verwirren zuverlässig — sie benennen die Wirkung auf den Partner, nicht das eigene Schicksal."],
                   "Reduktionsmittel gibt ab und wird oxidiert. Oxidationsmittel nimmt auf und wird reduziert.",
                   visual=anim("redox", "B")),
        "C": karte("Teilgleichungen aufstellen",
                   "Eine Redoxgleichung lässt sich in zwei Hälften zerlegen. Das macht den Elektronenübergang sichtbar und das Ausgleichen systematisch.",
                   ["Oxidation getrennt aufschreiben: Fe → Fe²⁺ + 2 e⁻",
                    "Reduktion getrennt aufschreiben: Cu²⁺ + 2 e⁻ → Cu",
                    "Die Zahl der abgegebenen und aufgenommenen Elektronen muss gleich sein. Stimmt sie nicht, werden die Teilgleichungen passend vervielfacht.",
                    "Beispiel: Al → Al³⁺ + 3 e⁻ und Cu²⁺ + 2 e⁻ → Cu. Kleinstes gemeinsames Vielfaches von 3 und 2 ist 6 — also 2 Al und 3 Cu²⁺.",
                    "Zum Schluss werden beide Hälften addiert; die Elektronen kürzen sich heraus."],
                   "Abgegebene und aufgenommene Elektronen müssen gleich viele sein.",
                   visual=anim("redox", "C"))
    },
    "formelkarte": {"formeln": ["Fe → Fe²⁺ + 2 e⁻   (Oxidation)",
                               "Cu²⁺ + 2 e⁻ → Cu   (Reduktion)",
                               "Fe + Cu²⁺ → Fe²⁺ + Cu",
                               "2 Al + 3 Cu²⁺ → 2 Al³⁺ + 3 Cu"],
                    "saetze": ["Oxidation = Elektronenabgabe. Reduktion = Elektronenaufnahme.",
                               "Beide laufen immer gemeinsam ab.",
                               "Reduktionsmittel gibt ab und wird oxidiert.",
                               "Abgegebene und aufgenommene Elektronen müssen gleich viele sein."]},
    "tasks": [
        aufgabe("ME05-A1-001", "A", 1, "choice",
                "Was passiert bei einer Oxidation?",
                options=["Elektronen werden abgegeben.", "Elektronen werden aufgenommen.", "Nichts passiert."],
                answer=0, visual=anim("redox", "A"),
                hints=["Oxidation und Reduktion sind Gegenteile.", "Eines ist Abgabe.", "Oxidation ist die Abgabe."],
                solution="Bei der Oxidation gibt ein Teilchen Elektronen ab.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Das ist die Reduktion. Oxidation ist die Abgabe von Elektronen.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME05-A2-002", "A", 2, "choice",
                "Ein Eisennagel liegt in Kupfersulfatlösung. Wer gibt Elektronen ab?",
                options=["das Eisen", "das Kupfer-Ion", "das Wasser"], answer=0,
                visual=anim("redox", "A"),
                hints=["Das unedlere Metall gibt ab.", "Eisen ist unedler als Kupfer.", "Also das Eisen."],
                solution="Eisen ist unedler und gibt Elektronen ab. Die Kupfer-Ionen nehmen sie auf.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME05-A3-003", "A", 3, "choice",
                "Was passiert bei einer Reduktion?",
                options=["Elektronen werden aufgenommen.", "Elektronen werden abgegeben.", "Sauerstoff wird aufgenommen."],
                answer=0,
                hints=["Es ist das Gegenteil der Oxidation.", "Oxidation ist Abgabe.", "Reduktion ist Aufnahme."],
                solution="Bei der Reduktion nimmt ein Teilchen Elektronen auf.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Abgabe ist die Oxidation. Reduktion ist die Aufnahme.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME05-A4-004", "A", 4, "choice",
                "Warum laufen Oxidation und Reduktion immer gemeinsam ab?",
                options=["Elektronen können nicht einfach verschwinden — wer abgibt, braucht einen Empfänger.",
                         "Weil beide gleich schnell sind.",
                         "Das ist Zufall."],
                answer=0,
                hints=["Wohin gehen die abgegebenen Elektronen?",
                       "Zu einem anderen Teilchen.",
                       "Also nimmt eines auf, wenn eines abgibt."],
                solution="Abgegebene Elektronen müssen irgendwo bleiben. Deshalb gibt es keine Oxidation ohne gleichzeitige Reduktion — beides zusammen heißt Redoxreaktion.",
                tags=["redox"], spiral=["K-REAK"]),
        aufgabe("ME05-B1-005", "B", 1, "choice",
                "In Fe + Cu²⁺ → Fe²⁺ + Cu: Was ist das Reduktionsmittel?",
                options=["Eisen", "Kupfer-Ion", "beides"], answer=0,
                hints=["Das Reduktionsmittel gibt Elektronen ab.",
                       "Wer gibt hier ab?",
                       "Das Eisen."],
                solution="Eisen gibt Elektronen ab und ermöglicht dadurch die Reduktion des Kupfers. Es ist das Reduktionsmittel — und wird dabei selbst oxidiert.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Das Kupfer-Ion nimmt auf, es ist das Oxidationsmittel.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME05-B2-006", "B", 2, "numeric",
                "Ein Aluminiumatom wird zu Al³⁺. Wie viele Elektronen gibt es ab?",
                answer=3, tolerance=0,
                hints=["Die Ladung sagt es.", "3+ heißt drei fehlende Elektronen.", "3."],
                solution="Al → Al³⁺ + 3 e⁻. Jede positive Ladung entspricht einem abgegebenen Elektron.",
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME05-B2-007", "B", 2, "choice",
                "Welche Teilgleichung beschreibt eine Reduktion?",
                options=["Cu²⁺ + 2 e⁻ → Cu", "Zn → Zn²⁺ + 2 e⁻", "Fe → Fe³⁺ + 3 e⁻"], answer=0,
                hints=["Wo stehen die Elektronen — links oder rechts?",
                       "Bei der Reduktion werden sie aufgenommen.",
                       "Sie stehen also links."],
                solution="Bei der Reduktion werden Elektronen aufgenommen, sie stehen deshalb links vom Pfeil: Cu²⁺ + 2 e⁻ → Cu.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Hier stehen die Elektronen rechts — das ist eine Oxidation.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME05-B3-008", "B", 3, "multi",
                "Betrachte die Reaktion Zn + Cu²⁺ → Zn²⁺ + Cu.",
                fields=[
                    {"label": "Zahl der übergehenden Elektronen", "answer": 2, "tolerance": 0},
                    {"label": "Ladung des entstehenden Zink-Ions", "answer": 2, "tolerance": 0}
                ],
                hints=["Zink gibt zwei Elektronen ab.",
                       "Das Kupfer-Ion nimmt genau diese zwei auf.",
                       "Zn²⁺."],
                solution="Zn → Zn²⁺ + 2 e⁻ und Cu²⁺ + 2 e⁻ → Cu. Es gehen zwei Elektronen über.",
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME05-B3-009", "B", 3, "choice",
                "Warum ist auch die Verbrennung von Magnesium eine Redoxreaktion?",
                options=["Magnesium gibt Elektronen an den Sauerstoff ab; es entstehen Mg²⁺ und O²⁻.",
                         "Weil dabei Wärme frei wird.",
                         "Weil ein Gas beteiligt ist."],
                answer=0,
                hints=["Was entsteht bei der Verbrennung?",
                       "Magnesiumoxid — ein Salz aus Ionen.",
                       "Also muss ein Elektronenübergang stattgefunden haben."],
                solution="Im Magnesiumoxid liegen Mg²⁺- und O²⁻-Ionen vor. Die Elektronen müssen also vom Magnesium zum Sauerstoff übergegangen sein — eine Redoxreaktion, auch ohne Lösung.",
                tags=["redox", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME05-B4-010", "B", 4, "choice",
                "Ein Schüler sagt: „Das Oxidationsmittel wird oxidiert.“ Stimmt das?",
                options=["Nein — es nimmt Elektronen auf und wird selbst reduziert.",
                         "Ja, deshalb heißt es so.",
                         "Nur bei Metallen."],
                answer=0,
                hints=["Was tut ein Oxidationsmittel mit dem Partner?",
                       "Es oxidiert ihn.",
                       "Dafür muss es selbst Elektronen aufnehmen."],
                solution="Der Name beschreibt die Wirkung auf den Partner, nicht das eigene Schicksal. Ein Oxidationsmittel oxidiert den anderen — indem es dessen Elektronen aufnimmt und dabei selbst reduziert wird.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Der Name nennt die Wirkung auf den Partner. Das Mittel selbst wird reduziert.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME05-C2-011", "C", 2, "multi",
                "Aluminium reagiert mit Kupfer(II)-Ionen. Al gibt 3 Elektronen ab, Cu²⁺ nimmt 2 auf.",
                fields=[
                    {"label": "Zahl der Aluminiumatome in der Gleichung", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der Kupfer-Ionen in der Gleichung", "answer": 3, "tolerance": 0},
                    {"label": "Zahl der übergehenden Elektronen", "answer": 6, "tolerance": 0}
                ],
                hints=["Kleinstes gemeinsames Vielfaches von 3 und 2.",
                       "Das ist 6.",
                       "2 Al geben 6 ab, 3 Cu²⁺ nehmen 6 auf."],
                solution="2 Al → 2 Al³⁺ + 6 e⁻\n3 Cu²⁺ + 6 e⁻ → 3 Cu\nzusammen: 2 Al + 3 Cu²⁺ → 2 Al³⁺ + 3 Cu",
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME05-C3-012", "C", 3, "choice",
                "Warum ist der Elektronenbegriff der bessere Zugang zur Oxidation als der Sauerstoffbegriff?",
                options=["Er erfasst auch Reaktionen ohne Sauerstoff, etwa Zink mit Chlor.",
                         "Er ist einfacher zu merken.",
                         "Sauerstoff spielt in der Chemie keine Rolle."],
                answer=0,
                hints=["Gibt es Oxidationen ohne Sauerstoff?",
                       "Ja — Zink reagiert auch mit Chlor unter Elektronenabgabe.",
                       "Der alte Begriff erfasst das nicht."],
                solution="Zn + Cl₂ → ZnCl₂ ist eine Oxidation des Zinks, obwohl kein Sauerstoff beteiligt ist. Der Sauerstoffbegriff ist ein historischer Sonderfall; der Elektronenbegriff umfasst alle diese Reaktionen.",
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME05-C3-013", "C", 3, "choice",
                "In der Reaktion 2 Mg + O₂ → 2 MgO — welche Aussage ist richtig?",
                options=["Magnesium ist das Reduktionsmittel, Sauerstoff das Oxidationsmittel.",
                         "Sauerstoff ist das Reduktionsmittel.",
                         "Es gibt kein Oxidationsmittel."],
                answer=0,
                hints=["Wer gibt Elektronen ab?",
                       "Magnesium.",
                       "Wer abgibt, ist das Reduktionsmittel."],
                solution="Magnesium gibt Elektronen ab — es ist das Reduktionsmittel und wird oxidiert. Sauerstoff nimmt sie auf — er ist das Oxidationsmittel und wird reduziert.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Sauerstoff nimmt Elektronen auf. Er ist das Oxidationsmittel.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "msa"], spiral=["K-REAK"]),
        aufgabe("ME05-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt als Teilgleichung: Fe²⁺ → Fe + 2 e⁻. Was ist falsch?",
                options=["Die Richtung stimmt nicht — bei der Abscheidung von Eisen werden Elektronen aufgenommen, nicht abgegeben.",
                         "Nichts, die Gleichung ist richtig.",
                         "Es müssten drei Elektronen sein."],
                answer=0,
                hints=["Aus Fe²⁺ soll Fe werden — die Ladung sinkt.",
                       "Wie verschwindet eine positive Ladung?",
                       "Durch Aufnahme von Elektronen."],
                solution="Aus Fe²⁺ wird Fe, die Ladung geht von 2+ auf 0. Dafür müssen zwei Elektronen aufgenommen werden: Fe²⁺ + 2 e⁻ → Fe. Die Elektronen gehören auf die linke Seite.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Prüfe die Ladungsbilanz: Links 2+, rechts 0 plus 2 negative Elektronen — das ergibt −2, nicht 2+.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["redox", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

E.append({
    "unit": "ME-06",
    "title": "Erze, Reduktion und der Hochofen",
    "leitidee": "B4",
    "standards": ["K1", "K2.2", "K4.1"],
    "klasse": 8,
    "wortspeicher": ["das Erz", "die Verhüttung", "der Hochofen", "das Roheisen",
                     "der Koks", "die Reduktion", "die Schlacke"],
    "worterklaerungen": {
        "Erz": "Ein Gestein, aus dem sich ein Metall gewinnen lässt.",
        "Verhüttung": "Die Gewinnung eines Metalls aus seinem Erz.",
        "Koks": "Fast reiner Kohlenstoff. Er dient im Hochofen als Reduktionsmittel und Brennstoff.",
        "Schlacke": "Das geschmolzene Gestein, das sich über dem Eisen sammelt."
    },
    "can_do": {
        "A": "Ich weiß, dass Eisen aus Erz gewonnen wird und dabei Sauerstoff entzogen wird.",
        "B": "Ich beschreibe den Hochofenprozess und benenne die Rolle des Kokses.",
        "C": "Ich erkläre die Reduktion mit Kohlenstoffmonoxid und bewerte den Prozess ökologisch."
    },
    "lernkarten": {
        "A": karte("Vom Stein zum Metall",
                   "Eisen kommt in der Natur nicht als Metall vor.",
                   ["Es steckt als Oxid im Erz.", "Der Sauerstoff muss entfernt werden."],
                   "Erz → Sauerstoff weg → Metall.",
                   visual=anim("redox", "A"),
                   beispiel={"titel": "Kupfer aus Malachit", "aufgabe": "Wie gewinnt man Kupfer?",
                             "schritte": ["Das Erz wird mit Kohle erhitzt.",
                                          "Die Kohle nimmt den Sauerstoff auf.",
                                          "Zurück bleibt Kupfer."],
                             "ergebnis": "Rotes Kupfermetall."}),
        "B": karte("Der Hochofen",
                   "Der Hochofen ist ein Gegenstromreaktor: Von oben kommen Erz und Koks, von unten heiße Luft. Auf dem Weg nach unten wird das Erz stufenweise reduziert.",
                   ["Beschickt wird von oben mit Eisenerz, Koks und Zuschlägen wie Kalk.",
                    "Unten wird Heißluft eingeblasen. Der Koks verbrennt zu Kohlenstoffdioxid und liefert die nötige Wärme — bis zu 2000 °C.",
                    "Am glühenden Koks entsteht daraus Kohlenstoffmonoxid. Dieses Gas ist das eigentliche Reduktionsmittel.",
                    "Der Kalk bindet das Gestein zu Schlacke, die auf dem flüssigen Eisen schwimmt und abgezogen wird.",
                    "Unten fließt Roheisen mit rund 4 % Kohlenstoff ab. Es ist hart und spröde und wird erst im Stahlwerk weiterverarbeitet."],
                   "Koks liefert Wärme und erzeugt das Reduktionsmittel Kohlenstoffmonoxid.",
                   visual={"type": "energie", "verlauf": "exotherm",
                           "alt": "Energiediagramm der exothermen Koksverbrennung im Hochofen."}),
        "C": karte("Reduktion und Bilanz",
                   "Der Hochofenprozess ist eine Redoxreaktion im großen Maßstab — und zugleich einer der größten industriellen Kohlenstoffdioxid-Quellen.",
                   ["Die Reduktion läuft stufenweise: Fe₂O₃ → Fe₃O₄ → FeO → Fe. Das Kohlenstoffmonoxid nimmt jeweils Sauerstoff auf und wird zu CO₂ oxidiert.",
                    "Gesamtgleichung: Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂.",
                    "Je Tonne Roheisen entstehen rund 1,8 Tonnen Kohlenstoffdioxid. Die Stahlindustrie verursacht damit einen erheblichen Teil der industriellen Emissionen.",
                    "Alternative Verfahren nutzen Wasserstoff als Reduktionsmittel: Fe₂O₃ + 3 H₂ → 2 Fe + 3 H₂O. Dabei entsteht Wasser statt Kohlenstoffdioxid — allerdings nur dann klimafreundlich, wenn der Wasserstoff aus erneuerbarem Strom stammt."],
                   "Das Reduktionsmittel bestimmt das Nebenprodukt: Kohlenstoff ergibt CO₂, Wasserstoff ergibt Wasser.",
                   visual=anim("redox", "C"))
    },
    "formelkarte": {"formeln": ["C + O₂ → CO₂",
                               "CO₂ + C → 2 CO",
                               "Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂",
                               "Fe₂O₃ + 3 H₂ → 2 Fe + 3 H₂O"],
                    "saetze": ["Erz enthält das Metall als Oxid.",
                               "Reduktion: dem Oxid wird der Sauerstoff entzogen.",
                               "Im Hochofen ist Kohlenstoffmonoxid das Reduktionsmittel.",
                               "Roheisen enthält rund 4 % Kohlenstoff und ist spröde."]},
    "tasks": [
        aufgabe("ME06-A1-001", "A", 1, "choice",
                "In welcher Form kommt Eisen in der Natur meist vor?",
                options=["als Oxid im Erz", "als reines Metall", "als Gas"], answer=0,
                hints=["Eisen ist unedel.", "Unedle Metalle reagieren mit Sauerstoff.", "Also als Oxid."],
                solution="Eisen ist unedel und liegt in der Natur als Oxid im Erz vor. Reines Eisen findet man praktisch nicht.",
                tags=["hochofen"], spiral=["K-REAK"]),
        aufgabe("ME06-A2-002", "A", 2, "choice",
                "Was muss geschehen, um aus Eisenerz Eisen zu gewinnen?",
                options=["Der Sauerstoff muss entfernt werden.", "Das Erz muss geschmolzen werden.", "Das Erz muss gewaschen werden."],
                answer=0,
                hints=["Im Erz ist Eisenoxid.", "Was ist zu viel darin?", "Der Sauerstoff."],
                solution="Im Erz liegt Eisenoxid vor. Um Eisen zu erhalten, muss der Sauerstoff entfernt werden — das ist eine Reduktion.",
                tags=["hochofen"], spiral=["K-REAK"]),
        aufgabe("ME06-A3-003", "A", 3, "choice",
                "Womit wird im Hochofen der Sauerstoff entfernt?",
                options=["mit Kohlenstoff bzw. Kohlenstoffmonoxid", "mit Wasser", "mit Luft"], answer=0,
                hints=["Es muss ein Stoff sein, der Sauerstoff aufnimmt.", "Koks ist fast reiner Kohlenstoff.", "Er nimmt den Sauerstoff auf."],
                solution="Der Koks liefert Kohlenstoffmonoxid. Dieses Gas nimmt den Sauerstoff aus dem Erz auf und wird zu Kohlenstoffdioxid.",
                tags=["hochofen"], spiral=["K-REAK"]),
        aufgabe("ME06-A4-004", "A", 4, "choice",
                "Was ist Roheisen?",
                options=["Eisen mit rund 4 % Kohlenstoff, hart und spröde.",
                         "Reines Eisen.", "Eisen mit Kupfer."],
                answer=0,
                hints=["Es kommt direkt aus dem Hochofen.", "Es enthält noch Kohlenstoff.", "Deshalb ist es spröde."],
                solution="Roheisen enthält rund 4 % Kohlenstoff und ist hart und spröde. Erst im Stahlwerk wird der Kohlenstoffgehalt gesenkt.",
                tags=["hochofen"], spiral=["K-STOF"]),
        aufgabe("ME06-B1-005", "B", 1, "choice",
                "Welche Aufgaben hat der Koks im Hochofen?",
                options=["Er liefert Wärme und erzeugt das Reduktionsmittel Kohlenstoffmonoxid.",
                         "Er hält das Erz zusammen.",
                         "Er kühlt den Ofen."],
                answer=0,
                hints=["Der Koks verbrennt.", "Dabei entsteht Wärme.", "Und daraus entsteht CO."],
                solution="Der Koks hat zwei Aufgaben: Seine Verbrennung liefert die nötige Wärme, und am glühenden Koks entsteht aus CO₂ das Kohlenstoffmonoxid, das die eigentliche Reduktion bewirkt.",
                tags=["hochofen", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME06-B2-006", "B", 2, "choice",
                "Warum schwimmt die Schlacke auf dem flüssigen Eisen?",
                options=["Sie hat eine geringere Dichte.", "Sie ist heißer.", "Sie ist fest."],
                answer=0,
                hints=["Was entscheidet, ob etwas oben schwimmt?", "Die Dichte.", "Die Schlacke ist leichter."],
                solution="Die geschmolzene Schlacke hat eine geringere Dichte als flüssiges Eisen und sammelt sich darüber. So lassen sich beide getrennt abstechen.",
                tags=["hochofen", "bbr"], spiral=["K-STOF"]),
        aufgabe("ME06-B2-007", "B", 2, "numeric",
                "Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂. Wie viele CO-Moleküle werden je Formeleinheit Fe₂O₃ gebraucht?",
                answer=3, tolerance=0,
                hints=["Sieh dir die Gleichung an.", "Vor dem CO steht eine 3.", "3."],
                solution="Fe₂O₃ enthält drei Sauerstoffatome. Jedes wird von einem CO-Molekül aufgenommen — also drei.",
                tags=["hochofen", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME06-B3-008", "B", 3, "multi",
                "Ein Erz enthält 70 % Eisenoxid Fe₂O₃, davon sind 70 % der Masse Eisen. Es werden 500 kg Erz eingesetzt.",
                fields=[
                    {"label": "Masse des Eisenoxids", "answer": 350, "unit_label": "kg", "tolerance": 2},
                    {"label": "gewinnbare Eisenmasse", "answer": 245, "unit_label": "kg", "tolerance": 3}
                ],
                hints=["70 % von 500 kg.",
                       "Davon wieder 70 %.",
                       "350 · 0,70."],
                solution="Eisenoxid: 500 · 0,70 = 350 kg\nEisen: 350 · 0,70 = 245 kg",
                tags=["hochofen", "rechnen", "bbr"], spiral=["K-SL", "K-QUANT"]),
        aufgabe("ME06-B3-009", "B", 3, "choice",
                "Warum wird dem Hochofen Kalk zugesetzt?",
                options=["Er bindet das Begleitgestein zu Schlacke.",
                         "Er reduziert das Erz.",
                         "Er kühlt den Ofen."],
                answer=0,
                hints=["Im Erz ist nicht nur Eisenoxid.", "Was passiert mit dem Gestein?", "Es wird gebunden."],
                solution="Der Kalk verbindet sich mit dem Begleitgestein zu leichtflüssiger Schlacke, die abgezogen werden kann. Mit der Reduktion selbst hat er nichts zu tun.",
                tags=["hochofen", "bbr"], spiral=["K-REAK"]),
        aufgabe("ME06-B4-010", "B", 4, "choice",
                "Warum ist der Hochofenprozess eine Redoxreaktion?",
                options=["Das Eisen wird reduziert, der Kohlenstoff bzw. das CO wird oxidiert.",
                         "Weil er sehr heiß ist.",
                         "Weil ein Gas beteiligt ist."],
                answer=0,
                hints=["Wer verliert Sauerstoff, wer nimmt ihn auf?",
                       "Das Eisenoxid verliert, das CO nimmt auf.",
                       "Reduktion und Oxidation zugleich."],
                solution="Das Eisenoxid gibt seinen Sauerstoff ab — Eisen wird reduziert. Das Kohlenstoffmonoxid nimmt ihn auf und wird zu CO₂ oxidiert. Beides zugleich ist eine Redoxreaktion.",
                tags=["hochofen", "msa"], spiral=["K-REAK"]),
        aufgabe("ME06-C2-011", "C", 2, "choice",
                "Warum ist Kohlenstoffmonoxid und nicht der feste Koks das eigentliche Reduktionsmittel?",
                options=["Als Gas erreicht es jede Stelle des Erzes; fester Koks berührt es nur an wenigen Punkten.",
                         "Koks ist zu kalt.",
                         "Koks reagiert gar nicht."],
                answer=0,
                hints=["Wie gut kommt ein Feststoff an ein anderes Feststoffkorn heran?",
                       "Nur an der Berührungsfläche.",
                       "Ein Gas dringt überall ein."],
                solution="Zwei Feststoffe berühren sich nur an wenigen Punkten. Das Gas Kohlenstoffmonoxid dringt dagegen in das poröse Erz ein und erreicht jede Stelle — deshalb läuft die Reduktion darüber.",
                tags=["hochofen", "msa"], spiral=["K-REAK"]),
        aufgabe("ME06-C3-012", "C", 3, "multi",
                "Je Tonne Roheisen entstehen rund 1,8 t Kohlenstoffdioxid. Ein Werk produziert 4000 t im Monat.",
                fields=[
                    {"label": "CO₂-Ausstoß im Monat", "answer": 7200, "unit_label": "t", "tolerance": 50},
                    {"label": "CO₂-Ausstoß im Jahr", "answer": 86400, "unit_label": "t", "tolerance": 500}
                ],
                hints=["4000 · 1,8.",
                       "7200 t im Monat.",
                       "Mal 12 Monate."],
                solution="Monat: 4000 t · 1,8 = 7200 t\nJahr: 7200 · 12 = 86 400 t",
                tags=["hochofen", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("ME06-C3-013", "C", 3, "choice",
                "Bei der Direktreduktion wird Wasserstoff statt Kohlenstoff verwendet. Welcher Unterschied ist entscheidend?",
                options=["Statt Kohlenstoffdioxid entsteht Wasser als Nebenprodukt.",
                         "Die Reaktion braucht keine Energie mehr.",
                         "Es entsteht mehr Eisen."],
                answer=0,
                hints=["Wohin geht der Sauerstoff aus dem Erz?",
                       "An das Reduktionsmittel.",
                       "Wasserstoff plus Sauerstoff ergibt Wasser."],
                solution="Fe₂O₃ + 3 H₂ → 2 Fe + 3 H₂O. Der Sauerstoff aus dem Erz bindet sich an den Wasserstoff — es entsteht Wasser statt Kohlenstoffdioxid. Energie wird weiterhin gebraucht.",
                tags=["hochofen", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("ME06-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Stahl aus Wasserstoff ist immer klimaneutral.“ Wie bewertest du das?",
                options=["Nur wenn der Wasserstoff mit erneuerbarem Strom hergestellt wurde — sonst verschiebt sich die Emission lediglich.",
                         "Richtig — es entsteht ja nur Wasser.",
                         "Falsch — auch bei Wasserstoff entsteht CO₂ im Ofen."],
                answer=0,
                hints=["Woher kommt der Wasserstoff?",
                       "Aus der Elektrolyse — und die braucht Strom.",
                       "Die Bilanz muss den Strom einschließen."],
                solution="Im Ofen entsteht tatsächlich nur Wasser. Der Wasserstoff muss aber erst durch Elektrolyse gewonnen werden. Stammt der Strom aus Kohle, ist die Emission nur verschoben. Die Bilanzgrenze muss die Herstellung einschließen.",
                misconceptions=[fv("bilanzgrenze_zu_eng", 1,
                                   "Die Bilanz endet nicht am Ofen. Auch die Herstellung des Wasserstoffs gehört hinein.",
                                   "masse_verschwindet")],
                tags=["hochofen", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("me", E, "Bereich ME · Einheiten 5 und 6")
