# -*- coding: utf-8 -*-
"""WA-06 (Abschluss Wasser) sowie SZ-01 und SZ-02 (Beginn Salze)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

WA = []
SZ = []

WA.append({
    "unit": "WA-06",
    "title": "Anwenden & Prüfungstraining Wasser",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 8,
    "wortspeicher": ["die Reaktionsgleichung", "der Dipol", "die Hydrathülle", "die Elektrolyse",
                     "die Dichteanomalie", "die Schlussfolgerung"],
    "worterklaerungen": {
        "Schlussfolgerung": "Der Satz, der aus Beobachtung und Wissen das Ergebnis zieht."
    },
    "can_do": {
        "A": "Ich beantworte gemischte Aufgaben zum Thema Wasser sicher.",
        "B": "Ich verbinde Molekülbau, Eigenschaften und Reaktionen des Wassers miteinander.",
        "C": "Ich begründe Eigenschaften des Wassers aus seinem Bau und bewerte Aussagen dazu."
    },
    "lernkarten": {
        "A": karte("Alles über Wasser",
                   "In dieser Stunde kommt alles zusammen.",
                   ["Wasser besteht aus H und O.", "Wasser ist ein Dipol.", "Eis schwimmt."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen. Wer sie kennt, kann fast jede Aufgabe beantworten.",
                   ["Zusammensetzung: Wasser ist eine Verbindung aus H und O im Verhältnis 2 : 1 — nachweisbar durch Elektrolyse.",
                    "Bau: Das Molekül ist gewinkelt und trägt Teilladungen. Es ist ein Dipol.",
                    "Folgen: Aus dem Dipolcharakter ergeben sich Löseverhalten, hohe Siedetemperatur und Dichteanomalie."],
                   "Zusammensetzung → Bau → Eigenschaften. In dieser Richtung wird begründet.",
                   visual=anim("dipol", "B")),
        "C": karte("Sauber begründen",
                   "Eine gute Begründung geht vom Bau aus und endet bei der Eigenschaft — nicht umgekehrt. „Wasser ist ein Dipol, weil es Salze löst“ verwechselt Ursache und Wirkung.",
                   ["Richtig: Der gewinkelte Bau erzeugt Teilladungen, deshalb ist Wasser ein Dipol, deshalb löst es Ionen.",
                    "Falsch: Wasser löst Ionen, deshalb ist es ein Dipol. Die Beobachtung ist der Beleg, nicht die Ursache.",
                    "Bei Vergleichsaufgaben immer beide Seiten nennen: Was ist gleich, was ist verschieden?",
                    "Bei Bewertungsaufgaben zuerst das Kriterium nennen."],
                   "Von der Ursache zur Wirkung begründen — nicht rückwärts.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["2 H₂O → 2 H₂ + O₂", "2 H₂ + O₂ → 2 H₂O"],
                    "saetze": ["Elektrolyse: 2 Teile H₂ zu 1 Teil O₂.",
                               "Wasser ist gewinkelt gebaut und damit ein Dipol.",
                               "Gleiches löst sich in Gleichem.",
                               "Größte Dichte bei 4 °C; Eis schwimmt.",
                               "Nur Koeffizienten ändern, nie die Indizes."]},
    "tasks": [
        aufgabe("WA06-A1-001", "A", 1, "choice",
                "Was entsteht bei der Elektrolyse von Wasser?",
                options=["Wasserstoff und Sauerstoff", "Wasserstoff und Stickstoff", "nur Wasserstoff"],
                answer=0, visual=anim("elektrolyse", "A"),
                hints=["Es sind zwei Gase.", "Eines davon ist Sauerstoff.", "Das andere Wasserstoff."],
                solution="Wasser wird in Wasserstoff und Sauerstoff zerlegt, im Volumenverhältnis 2 : 1.",
                tags=["pruefung"], spiral=["K-REAK"]),
        aufgabe("WA06-A2-002", "A", 2, "numeric",
                "Wie viel Sauerstoff entsteht, wenn 24 mL Wasserstoff aufgefangen werden?",
                answer=12, unit_label="mL", tolerance=1,
                hints=["Verhältnis 2 : 1.", "24 : 2.", "12 mL."],
                solution="24 mL : 2 = 12 mL Sauerstoff.",
                tags=["pruefung", "rechnen"], spiral=["K-REAK"]),
        aufgabe("WA06-A3-003", "A", 3, "choice",
                "Welcher Stoff löst sich nicht in Wasser?",
                options=["Speiseöl", "Kochsalz", "Zucker"], answer=0,
                hints=["Zwei lösen sich, einer nicht.", "Öl ist unpolar.", "Es löst sich nicht."],
                solution="Öl ist unpolar und löst sich nicht in polarem Wasser.",
                tags=["pruefung"], spiral=["K-SL"]),
        aufgabe("WA06-A4-004", "A", 4, "choice",
                "Warum friert ein See nicht bis zum Grund zu?",
                options=["Eis schwimmt oben und wirkt wie eine Isolierschicht.",
                         "Das Wasser unten ist salzig.", "Fische wärmen das Wasser."],
                answer=0,
                hints=["Wo liegt das Eis?", "Oben.", "Darunter bleibt es flüssig."],
                solution="Eis ist leichter als Wasser und schwimmt. Die Eisdecke isoliert, darunter bleibt Wasser bei 4 °C flüssig.",
                tags=["pruefung"], spiral=["K-STOF"]),
        aufgabe("WA06-B1-005", "B", 1, "numeric",
                "Gleiche aus: ? H₂ + O₂ → 2 H₂O. Welcher Koeffizient fehlt?",
                answer=2, tolerance=0,
                hints=["Rechts stehen 4 H-Atome.", "Jedes H₂ liefert zwei.", "4 : 2 = 2."],
                solution="2 H₂ + O₂ → 2 H₂O. Probe: H 4 = 4, O 2 = 2.",
                tags=["pruefung", "gleichungen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA06-B2-006", "B", 2, "choice",
                "Warum löst Wasser Kochsalz, Benzin aber nicht?",
                options=["Wasser ist ein Dipol und kann die Ionen umhüllen; Benzin ist unpolar.",
                         "Wasser ist dünnflüssiger.", "Benzin ist zu leicht."],
                answer=0,
                hints=["Was brauchen Ionen zum Lösen?", "Geladene Partner.", "Nur Wasser bietet die."],
                solution="Wassermoleküle sind Dipole und lagern sich mit ihren Teilladungen um die Ionen. Benzin ist unpolar und kann das Ionengitter nicht aufbrechen.",
                tags=["pruefung", "bbr"], spiral=["K-SL"]),
        aufgabe("WA06-B2-007", "B", 2, "choice",
                "Welche Aussage ist eine Begründung, keine Beobachtung?",
                options=["Weil der Sauerstoff die Elektronen stärker anzieht, trägt er eine negative Teilladung.",
                         "Der Wasserstrahl wird abgelenkt.",
                         "Am Minuspol entsteht mehr Gas."],
                answer=0, visual=anim("signalwoerter", "B"),
                hints=["Eine Begründung enthält ein „weil“.",
                       "Beobachtungen beschreiben nur.",
                       "Nur eine Aussage nennt eine Ursache."],
                solution="Nur die erste Aussage nennt eine Ursache. Die beiden anderen beschreiben, was zu sehen ist.",
                tags=["pruefung", "operatoren", "bbr"]),
        aufgabe("WA06-B3-008", "B", 3, "multi",
                "Bei einer Elektrolyse werden insgesamt 120 mL Gas aufgefangen.",
                fields=[
                    {"label": "Wasserstoffvolumen", "answer": 80, "unit_label": "mL", "tolerance": 2},
                    {"label": "Sauerstoffvolumen", "answer": 40, "unit_label": "mL", "tolerance": 2}
                ],
                hints=["Insgesamt 3 Teile.", "1 Teil = 40 mL.", "Wasserstoff sind 2 Teile."],
                solution="1 Teil = 120 : 3 = 40 mL\nH₂ = 80 mL, O₂ = 40 mL",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-REAK"]),
        aufgabe("WA06-B3-009", "B", 3, "choice",
                "Ein Stoff löst sich gut in Wasser und leitet in Lösung den Strom. Was folgt daraus?",
                options=["Es liegen Ionen vor.", "Der Stoff ist ein Metall.", "Der Stoff ist unpolar."],
                answer=0,
                hints=["Was transportiert die Ladung in einer Lösung?",
                       "Bewegliche Ionen.",
                       "Zuckerlösung leitet dagegen nicht."],
                solution="Leitfähigkeit in Lösung setzt frei bewegliche Ionen voraus. Zucker löst sich zwar auch gut, liegt aber als Moleküle vor und leitet deshalb nicht.",
                tags=["pruefung", "bbr"], spiral=["K-SL"]),
        aufgabe("WA06-B4-010", "B", 4, "choice",
                "Warum ist die Knallgasreaktion exotherm, die Elektrolyse aber endotherm?",
                options=["Es ist dieselbe Reaktion in zwei Richtungen; was die eine aufnimmt, gibt die andere ab.",
                         "Weil bei der Elektrolyse Strom fließt.",
                         "Das ist Zufall."],
                answer=0,
                hints=["Vergleiche die beiden Gleichungen.",
                       "Edukte und Produkte sind vertauscht.",
                       "Dann muss auch die Energie die Richtung wechseln."],
                solution="2 H₂O → 2 H₂ + O₂ und 2 H₂ + O₂ → 2 H₂O sind Umkehrungen voneinander. Die Energie, die beim Zerlegen aufgenommen wird, wird beim Verbinden wieder frei.",
                tags=["pruefung", "energie", "msa"], spiral=["K-REAK"]),
        aufgabe("WA06-C2-011", "C", 2, "choice",
                "Welche Begründung ist fachlich richtig aufgebaut?",
                options=["Wasser ist gewinkelt gebaut, deshalb ein Dipol, deshalb löst es Ionen.",
                         "Wasser löst Ionen, deshalb ist es ein Dipol, deshalb ist es gewinkelt.",
                         "Wasser ist ein Dipol, deshalb ist es gewinkelt gebaut."],
                answer=0,
                hints=["Was ist Ursache, was Wirkung?",
                       "Der Bau ist die Ursache.",
                       "Das Löseverhalten die Wirkung."],
                solution="Begründet wird von der Ursache zur Wirkung: Bau → Dipol → Löseverhalten. Die beiden anderen Ketten verwechseln Beleg und Ursache.",
                tags=["pruefung", "operatoren", "msa"]),
        aufgabe("WA06-C3-012", "C", 3, "multi",
                "9,0 g Wasser werden vollständig elektrolysiert. (M(H₂O) = 18 g/mol, V_m = 22,4 L/mol)",
                fields=[
                    {"label": "Stoffmenge des Wassers", "answer": 0.5, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "Volumen des Wasserstoffs", "answer": 11.2, "unit_label": "L", "tolerance": 0.3},
                    {"label": "Volumen des Sauerstoffs", "answer": 5.6, "unit_label": "L", "tolerance": 0.2}
                ],
                hints=["n = m : M = 9,0 : 18.",
                       "Aus 2 H₂O entstehen 2 H₂ — also gleich viel Stoffmenge.",
                       "Sauerstoff: die halbe Stoffmenge."],
                solution="n(H₂O) = 9,0 g : 18 g/mol = 0,5 mol\nn(H₂) = 0,5 mol → V = 0,5 · 22,4 = 11,2 L\nn(O₂) = 0,25 mol → V = 5,6 L",
                tags=["pruefung", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("WA06-C3-013", "C", 3, "choice",
                "Ein Schüler schreibt: „Beim Sieden zerfällt Wasser in Wasserstoff und Sauerstoff.“ Wie korrigierst du?",
                options=["Beim Sieden werden nur die Anziehungskräfte zwischen den Molekülen gelöst; die Moleküle selbst bleiben ganz.",
                         "Der Satz stimmt.",
                         "Beim Sieden entsteht Wasserstoffperoxid."],
                answer=0,
                hints=["Was passiert beim Sieden mit den Molekülen?",
                       "Sie werden voneinander getrennt.",
                       "Zerlegt werden sie erst bei der Elektrolyse."],
                solution="Sieden ist eine Zustandsänderung: Die Wasserstoffbrücken zwischen den Molekülen werden überwunden, die Moleküle selbst bleiben unversehrt. Für die Zerlegung braucht es eine chemische Reaktion.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 1,
                                   "Zustandsänderung und chemische Reaktion sind zu unterscheiden. Wasserdampf ist noch Wasser.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["pruefung", "bewerten", "msa"], spiral=["K-STOF"]),
        aufgabe("WA06-C4-014", "C", 4, "choice",
                "„Wasserstoff ist der Energieträger der Zukunft.“ Welche Antwort bewertet diese Aussage fachlich?",
                options=["Wasserstoff speichert Energie, erzeugt sie aber nicht — entscheidend ist, woher der Strom für die Elektrolyse kommt.",
                         "Richtig, denn bei der Verbrennung entsteht nur Wasser.",
                         "Falsch, denn Wasserstoff ist zu gefährlich."],
                answer=0,
                hints=["Woher kommt der Wasserstoff?",
                       "Aus der Elektrolyse — und die braucht Strom.",
                       "Die Bewertung hängt an der Stromquelle."],
                solution="Bei der Verbrennung entsteht tatsächlich nur Wasser. Der Wasserstoff muss aber zuerst mit Energie hergestellt werden. Ob die Bilanz aufgeht, entscheidet die Stromquelle — eine Bewertung ohne diesen Blick zieht die Bilanzgrenze zu eng.",
                tags=["pruefung", "bewerten", "msa"])
    ]
})

# ============================================================
# SZ-01 · Ionen
# ============================================================
SZ.append({
    "unit": "SZ-01",
    "title": "Ionen: aus Atomen werden geladene Teilchen",
    "leitidee": "B1",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["das Ion", "das Kation", "das Anion", "die Ionenbildung",
                     "die Edelgaskonfiguration", "die Ladung"],
    "worterklaerungen": {
        "Ion": "Ein geladenes Teilchen. Es hat Elektronen abgegeben oder aufgenommen.",
        "Kation": "Ein positiv geladenes Ion. Es hat Elektronen abgegeben.",
        "Anion": "Ein negativ geladenes Ion. Es hat Elektronen aufgenommen."
    },
    "can_do": {
        "A": "Ich weiß, dass Metalle Elektronen abgeben und Nichtmetalle sie aufnehmen.",
        "B": "Ich gebe die Ionenladung aus der Hauptgruppe an und benenne Kationen und Anionen.",
        "C": "Ich begründe die Ionenbildung über die Edelgaskonfiguration und vergleiche Atom- und Ionengröße."
    },
    "lernkarten": {
        "A": karte("Aus Atomen werden Ionen",
                   "Ein Atom kann Elektronen abgeben oder aufnehmen.",
                   ["Dann ist es geladen.", "Ein geladenes Teilchen heißt Ion."],
                   "Elektron weg → positiv. Elektron dazu → negativ.",
                   visual=anim("ionenbildung", "A"),
                   beispiel={"titel": "Natrium und Chlor", "aufgabe": "Was passiert?",
                             "schritte": ["Natrium gibt ein Elektron ab → Na⁺.",
                                          "Chlor nimmt es auf → Cl⁻."],
                             "ergebnis": "Zwei Ionen, die sich anziehen."}),
        "B": karte("Ladung aus der Hauptgruppe",
                   "Die Ionenladung muss nicht auswendig gelernt werden — sie steht in der Hauptgruppennummer.",
                   ["Metalle geben ab: Hauptgruppe I → 1+, Hauptgruppe II → 2+, Hauptgruppe III → 3+.",
                    "Nichtmetalle nehmen auf: Hauptgruppe VII → 1−, Hauptgruppe VI → 2−, Hauptgruppe V → 3−.",
                    "Positive Ionen heißen Kationen, negative Anionen.",
                    "Der Name folgt einer Regel: Aus Chlor wird das Chlorid-Ion, aus Sauerstoff das Oxid-Ion, aus Schwefel das Sulfid-Ion. Metallionen behalten ihren Namen."],
                   "Bis Gruppe III abgeben, ab Gruppe V aufnehmen. Die Gruppennummer nennt die Zahl.",
                   visual=anim("ionenbildung", "B")),
        "C": karte("Warum gerade so viele",
                   "Die Zahl der abgegebenen oder aufgenommenen Elektronen ist nicht beliebig: Es ist immer die Zahl, die zur vollen Außenschale fehlt oder zu viel ist.",
                   ["Natrium mit einem Außenelektron gibt genau dieses ab und erreicht die Konfiguration von Neon. Zwei abzugeben wäre energetisch viel zu aufwendig.",
                    "Chlor mit sieben Außenelektronen nimmt genau eines auf und erreicht die Konfiguration von Argon.",
                    "Beim Übergang ändert sich die Größe deutlich: Na⁺ ist kleiner als das Na-Atom — eine ganze Schale fällt weg. Cl⁻ ist größer als das Cl-Atom — die zusätzliche Abstoßung dehnt die Hülle.",
                    "Ionen haben völlig andere Eigenschaften als die zugehörigen Atome. Natrium reagiert heftig mit Wasser, Natrium-Ionen sind in jedem Mineralwasser."],
                   "Ein Ion ist kein „geladenes Atom“ mit denselben Eigenschaften — es ist ein anderes Teilchen.",
                   visual=anim("ionenbildung", "C"))
    },
    "formelkarte": {"formeln": ["Na → Na⁺ + e⁻", "Cl + e⁻ → Cl⁻"],
                    "saetze": ["Kation: positiv, hat Elektronen abgegeben.",
                               "Anion: negativ, hat Elektronen aufgenommen.",
                               "Ladung = Hauptgruppennummer (I–III) bzw. Hauptgruppennummer − 8 (V–VII).",
                               "Namen: Chlorid, Oxid, Sulfid — Metallionen behalten ihren Namen."]},
    "tasks": [
        aufgabe("SZ01-A1-001", "A", 1, "choice",
                "Was ist ein Ion?",
                options=["Ein geladenes Teilchen", "Ein sehr kleines Atom", "Ein Molekül"], answer=0,
                visual=anim("ionenbildung", "A"),
                hints=["Es hat Elektronen abgegeben oder aufgenommen.", "Dadurch ist es geladen.", "Ein geladenes Teilchen."],
                solution="Ein Ion ist ein geladenes Teilchen — entstanden durch Abgabe oder Aufnahme von Elektronen.",
                tags=["ionen"], spiral=["K-ATOM"]),
        aufgabe("SZ01-A2-002", "A", 2, "choice",
                "Natrium gibt ein Elektron ab. Wie ist es danach geladen?",
                options=["positiv", "negativ", "gar nicht"], answer=0,
                hints=["Ein Elektron ist negativ.", "Es fehlt jetzt eines.", "Also überwiegt das Positive."],
                solution="Fehlt ein negatives Elektron, überwiegen die positiven Protonen: Na⁺.",
                misconceptions=[fv("ladung_falsch_herum", 1,
                                   "Abgeben eines negativen Elektrons macht das Teilchen <b>positiv</b>.",
                                   "ladung_unvollstaendig")],
                tags=["ionen"], spiral=["K-ATOM"]),
        aufgabe("SZ01-A3-003", "A", 3, "assign",
                "Ordne zu: gibt ab oder nimmt auf?",
                slots=["Natrium", "Chlor", "Magnesium"],
                values=["gibt 1 Elektron ab", "nimmt 1 Elektron auf", "gibt 2 Elektronen ab"],
                answer=[0, 1, 2],
                hints=["Metalle geben ab, Nichtmetalle nehmen auf.",
                       "Die Hauptgruppennummer sagt, wie viele.",
                       "Magnesium steht in Gruppe II."],
                solution="Natrium (Gruppe I) → 1 ab.\nChlor (Gruppe VII) → 1 auf.\nMagnesium (Gruppe II) → 2 ab.",
                tags=["ionen"], spiral=["K-ATOM"]),
        aufgabe("SZ01-A4-004", "A", 4, "choice",
                "Wie heißt das Ion, das aus einem Chloratom entsteht?",
                options=["Chlorid-Ion", "Chlor-Ion", "Chlorat-Ion"], answer=0,
                hints=["Der Name ändert sich.", "Er endet auf -id.", "Chlorid."],
                solution="Aus Chlor wird das Chlorid-Ion Cl⁻. Nichtmetall-Anionen enden auf -id.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Anionen der Nichtmetalle bekommen die Endung -id: Chlorid, Oxid, Sulfid.",
                                   "nomenklatur_falsch")],
                tags=["ionen", "namen"], spiral=["K-BIND"]),
        aufgabe("SZ01-B1-005", "B", 1, "choice",
                "Welche Ladung hat ein Ion aus Hauptgruppe VI?",
                options=["2−", "6−", "2+"], answer=0,
                hints=["Wie viele Außenelektronen hat es?", "Sechs — es fehlen zwei.", "Es nimmt zwei auf."],
                solution="Sechs Außenelektronen, zwei fehlen zur vollen Schale. Das Ion nimmt zwei auf und ist 2− geladen, etwa O²⁻.",
                misconceptions=[fv("ladung_falsch_herum", 2,
                                   "Nichtmetalle nehmen Elektronen auf und werden dadurch <b>negativ</b>.",
                                   "ladung_unvollstaendig")],
                tags=["ionen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("SZ01-B2-006", "B", 2, "multi",
                "Ein Aluminiumatom hat 13 Elektronen und steht in Hauptgruppe III.",
                fields=[
                    {"label": "Zahl der abgegebenen Elektronen", "answer": 3, "tolerance": 0},
                    {"label": "Ladung des Ions", "answer": 3, "tolerance": 0},
                    {"label": "Zahl der Elektronen im Ion", "answer": 10, "tolerance": 0}
                ],
                hints=["Hauptgruppe III → drei Außenelektronen.",
                       "Alle drei werden abgegeben.",
                       "13 − 3 = 10 — wie Neon."],
                solution="3 Elektronen ab → Al³⁺ mit 10 Elektronen, also der Konfiguration von Neon.",
                tags=["ionen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("SZ01-B2-007", "B", 2, "choice",
                "Warum gibt Natrium genau ein Elektron ab und nicht zwei?",
                options=["Nach einem abgegebenen Elektron ist die Edelgaskonfiguration erreicht.",
                         "Weil es nur ein Elektron besitzt.",
                         "Zwei abzugeben wäre auch möglich."],
                answer=0, visual=anim("ionenbildung", "B"),
                hints=["Was ist nach dem ersten Elektron erreicht?",
                       "Eine volle Außenschale.",
                       "Ein weiteres müsste aus einer vollen Schale kommen."],
                solution="Nach Abgabe des einen Außenelektrons hat Natrium die Konfiguration von Neon. Ein zweites müsste aus der vollen darunterliegenden Schale kommen — dafür ist der Energieaufwand viel zu hoch.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Natrium hat 11 Elektronen, nur eines davon ist ein Außenelektron.",
                                   "ion_und_atom_verwechselt")],
                tags=["ionen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("SZ01-B3-008", "B", 3, "assign",
                "Ordne jedem Ion seinen Namen zu.",
                slots=["Na⁺", "O²⁻", "S²⁻"],
                values=["Natrium-Ion", "Oxid-Ion", "Sulfid-Ion"],
                answer=[0, 1, 2],
                hints=["Metallionen behalten ihren Namen.",
                       "Nichtmetall-Anionen enden auf -id.",
                       "Aus Schwefel wird Sulfid."],
                solution="Na⁺ → Natrium-Ion (Name bleibt).\nO²⁻ → Oxid-Ion.\nS²⁻ → Sulfid-Ion.",
                tags=["ionen", "namen", "bbr"], spiral=["K-BIND"]),
        aufgabe("SZ01-B3-009", "B", 3, "choice",
                "Warum ist ein Natrium-Ion kleiner als ein Natriumatom?",
                options=["Mit dem Außenelektron fällt eine ganze Schale weg.",
                         "Das Ion hat weniger Protonen.",
                         "Das Ion ist schwerer und zieht sich zusammen."],
                answer=0,
                hints=["Was passiert mit der äußersten Schale?",
                       "Sie wird leer.",
                       "Damit ist das Teilchen deutlich kleiner."],
                solution="Natrium hat die Verteilung 2 · 8 · 1. Gibt es das eine Außenelektron ab, ist die dritte Schale leer — das Ion ist deutlich kleiner. Die Protonenzahl bleibt unverändert.",
                misconceptions=[fv("ordnungszahl_aendert_sich", 1,
                                   "Bei der Ionenbildung ändert sich nur die Elektronenzahl, nie die Protonenzahl.",
                                   "ion_und_atom_verwechselt")],
                tags=["ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("SZ01-B4-010", "B", 4, "choice",
                "Natrium reagiert heftig mit Wasser, Natrium-Ionen sind in jedem Mineralwasser harmlos. Wie erklärst du das?",
                options=["Atom und Ion sind verschiedene Teilchen mit verschiedenen Eigenschaften.",
                         "Im Mineralwasser ist die Menge zu klein.",
                         "Natrium-Ionen sind dasselbe wie Natriumatome."],
                answer=0,
                hints=["Was unterscheidet Na und Na⁺?",
                       "Das Außenelektron.",
                       "Und genau das macht die heftige Reaktion aus."],
                solution="Die heftige Reaktion beruht auf der Abgabe des Außenelektrons. Das Ion hat es bereits abgegeben und kann nicht mehr so reagieren. Atom und Ion sind verschiedene Teilchen — das ist einer der wichtigsten Unterschiede der Mittelstufe.",
                misconceptions=[fv("ion_und_atom_verwechselt", 2,
                                   "Ein Ion ist kein „Atom mit Ladung“, sondern ein Teilchen mit anderen Eigenschaften.",
                                   "ion_und_atom_verwechselt")],
                tags=["ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("SZ01-C2-011", "C", 2, "choice",
                "Warum ist ein Chlorid-Ion größer als ein Chloratom?",
                options=["Das zusätzliche Elektron verstärkt die Abstoßung in der Hülle, die sich dadurch ausdehnt.",
                         "Das Ion hat mehr Protonen.",
                         "Das Ion hat eine zusätzliche Schale."],
                answer=0,
                hints=["Kommt eine neue Schale dazu?",
                       "Nein — das Elektron passt in die vorhandene.",
                       "Aber die Abstoßung nimmt zu."],
                solution="Das aufgenommene Elektron kommt in die vorhandene Schale. Bei unveränderter Protonenzahl verteilt sich dieselbe Anziehung nun auf mehr Elektronen, und die gegenseitige Abstoßung nimmt zu — die Hülle dehnt sich.",
                tags=["ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("SZ01-C3-012", "C", 3, "multi",
                "Betrachte die Ionen Mg²⁺, O²⁻ und Al³⁺.",
                fields=[
                    {"label": "Elektronenzahl von Mg²⁺ (Z = 12)", "answer": 10, "tolerance": 0},
                    {"label": "Elektronenzahl von O²⁻ (Z = 8)", "answer": 10, "tolerance": 0},
                    {"label": "Elektronenzahl von Al³⁺ (Z = 13)", "answer": 10, "tolerance": 0}
                ],
                hints=["Positiv heißt: Elektronen fehlen.",
                       "Negativ heißt: Elektronen sind dazugekommen.",
                       "Alle drei erreichen dieselbe Konfiguration."],
                solution="Mg²⁺: 12 − 2 = 10\nO²⁻: 8 + 2 = 10\nAl³⁺: 13 − 3 = 10\nAlle drei haben die Elektronenkonfiguration von Neon — sie sind isoelektronisch.",
                tags=["ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("SZ01-C3-013", "C", 3, "choice",
                "Mg²⁺, O²⁻ und Al³⁺ haben alle 10 Elektronen. Warum sind sie trotzdem verschieden groß?",
                options=["Sie haben verschieden viele Protonen; mehr Protonen ziehen die Hülle stärker zusammen.",
                         "Sie sind gleich groß.",
                         "Sie haben verschieden viele Neutronen."],
                answer=0,
                hints=["Was unterscheidet sie noch?",
                       "Die Kernladung.",
                       "Al³⁺ hat 13 Protonen, O²⁻ nur 8."],
                solution="Bei gleicher Elektronenzahl entscheidet die Kernladung: Al³⁺ mit 13 Protonen zieht die zehn Elektronen am stärksten an und ist am kleinsten, O²⁻ mit 8 Protonen am größten.",
                tags=["ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("SZ01-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt: „Chlor ist giftig, also ist Kochsalz auch giftig, denn es enthält Chlor.“ Wie bewertest du das?",
                options=["Falsch — im Kochsalz liegen Chlorid-Ionen vor, und die haben andere Eigenschaften als Chloratome oder Chlormoleküle.",
                         "Richtig — die Bestandteile bleiben erhalten.",
                         "Falsch — Kochsalz enthält gar kein Chlor."],
                answer=0,
                hints=["Was liegt im Kochsalz vor?",
                       "Chlorid-Ionen, nicht Chlormoleküle.",
                       "Ionen haben andere Eigenschaften."],
                solution="Im Kochsalz liegen Cl⁻-Ionen vor. Sie haben ein Elektron mehr als das Chloratom und völlig andere Eigenschaften als das giftige Chlorgas Cl₂. Eigenschaften eines Elements auf seine Ionen zu übertragen ist einer der hartnäckigsten Fehlschlüsse.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Die Bestandteile bleiben als Ionen erhalten — mit anderen Eigenschaften als die Elemente.",
                                   "ion_und_atom_verwechselt")],
                tags=["ionen", "bewerten", "msa"], spiral=["K-ATOM"])
    ]
})

if __name__ == "__main__":
    schreiben("wa", WA, "Bereich WA · Einheit 6")
    schreiben("sz", SZ, "Bereich SZ · Einheit 1")
