# -*- coding: utf-8 -*-
"""Bereich SL · Säuren und Laugen — SL-05 bis SL-07."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "SL-05",
    "title": "Säuren und Laugen aus Oxiden",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K4.3"],
    "klasse": 9,
    "wortspeicher": ["das Nichtmetalloxid", "das Metalloxid", "der saure Regen",
                     "die schweflige Säure", "die Kohlensäure", "das Löschen von Kalk"],
    "worterklaerungen": {
        "Nichtmetalloxid": "Ein Oxid eines Nichtmetalls. Es bildet mit Wasser eine Säure.",
        "Metalloxid": "Ein Oxid eines Metalls. Es bildet mit Wasser eine Lauge.",
        "saurer Regen": "Regen, der durch gelöste Nichtmetalloxide sauer geworden ist."
    },
    "can_do": {
        "A": "Ich weiß, dass Nichtmetalloxide Säuren und Metalloxide Laugen bilden.",
        "B": "Ich stelle die Gleichungen für die Bildung von Säuren und Laugen aus Oxiden auf.",
        "C": "Ich erkläre den sauren Regen und bewerte Gegenmaßnahmen."
    },
    "lernkarten": {
        "A": karte("Oxide im Wasser",
                   "Oxide reagieren mit Wasser.",
                   ["Metalloxide ergeben eine Lauge.", "Nichtmetalloxide ergeben eine Säure."],
                   "Metall → Lauge. Nichtmetall → Säure.",
                   visual={"type": "phskala", "marken": [{"wert": 4, "stoff": "SO₂ in Wasser"},
                                                         {"wert": 12, "stoff": "CaO in Wasser"}],
                           "alt": "pH-Skala mit einer sauren und einer alkalischen Marke."},
                   beispiel={"titel": "Kohlensäure", "aufgabe": "CO₂ wird in Wasser geleitet.",
                             "schritte": ["Kohlenstoff ist ein Nichtmetall.",
                                          "Also entsteht eine Säure.",
                                          "Es ist Kohlensäure."],
                             "ergebnis": "CO₂ + H₂O → H₂CO₃"}),
        "B": karte("Die Gleichungen",
                   "Beide Fälle folgen demselben Muster: Das Oxid nimmt Wasser auf. Was dabei entsteht, hängt allein davon ab, ob ein Metall oder ein Nichtmetall beteiligt ist.",
                   ["Nichtmetalloxide: CO₂ + H₂O → H₂CO₃, SO₂ + H₂O → H₂SO₃, SO₃ + H₂O → H₂SO₄.",
                    "Metalloxide: CaO + H₂O → Ca(OH)₂, Na₂O + H₂O → 2 NaOH.",
                    "Der Zusammenhang lässt sich auch rückwärts lesen: Aus der Formel einer Säure lässt sich das zugehörige Oxid bestimmen.",
                    "Deshalb ist Mineralwasser leicht sauer: Gelöstes Kohlenstoffdioxid bildet Kohlensäure."],
                   "Oxid plus Wasser — das Metall entscheidet über Säure oder Lauge.",
                   visual=anim("phwert", "B")),
        "C": karte("Saurer Regen",
                   "Der saure Regen ist das Musterbeispiel dafür, wie eine chemische Reaktion zu einem gesellschaftlichen Problem wird — und wie sie sich auch wieder eindämmen lässt.",
                   ["Beim Verbrennen schwefelhaltiger Brennstoffe entsteht Schwefeldioxid. Mit Regenwasser bildet es schweflige Säure.",
                    "Stickoxide aus Verbrennungsmotoren bilden salpetrige Säure und Salpetersäure.",
                    "Auch unbelasteter Regen ist mit pH 5,6 leicht sauer — durch gelöstes Kohlenstoffdioxid. Von saurem Regen spricht man erst deutlich darunter.",
                    "Folgen: Schäden an Wäldern, Versauerung von Seen, Auflösen von Kalkstein an Bauwerken.",
                    "Maßnahmen: Rauchgasentschwefelung, schwefelarme Kraftstoffe, Katalysatoren. Sie haben in Mitteleuropa gewirkt — die Schwefeldioxid-Belastung ist seit den 1980er Jahren stark gesunken."],
                   "Nichtmetalloxide aus Verbrennungen machen den Regen sauer.",
                   visual=anim("phwert", "C"))
    },
    "formelkarte": {"formeln": ["CO₂ + H₂O → H₂CO₃",
                               "SO₂ + H₂O → H₂SO₃",
                               "SO₃ + H₂O → H₂SO₄",
                               "CaO + H₂O → Ca(OH)₂",
                               "Na₂O + H₂O → 2 NaOH"],
                    "saetze": ["Nichtmetalloxid + Wasser → Säure.",
                               "Metalloxid + Wasser → Lauge.",
                               "Unbelasteter Regen hat pH 5,6 durch gelöstes CO₂.",
                               "Saurer Regen: SO₂ und Stickoxide aus Verbrennungen."]},
    "tasks": [
        aufgabe("SL05-A1-001", "A", 1, "choice",
                "Was entsteht, wenn ein Nichtmetalloxid in Wasser gelöst wird?",
                options=["eine Säure", "eine Lauge", "nichts"], answer=0,
                hints=["Nichtmetall und Metall verhalten sich entgegengesetzt.",
                       "Metalloxide ergeben Laugen.",
                       "Nichtmetalloxide ergeben Säuren."],
                solution="Nichtmetalloxide bilden mit Wasser Säuren — etwa CO₂ zu Kohlensäure.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "Laugen entstehen aus Metalloxiden.",
                                   "saeure_lauge_vertauscht")],
                tags=["oxide"], spiral=["K-REAK"]),
        aufgabe("SL05-A2-002", "A", 2, "choice",
                "Was entsteht, wenn Calciumoxid in Wasser gegeben wird?",
                options=["eine Lauge", "eine Säure", "ein Gas"], answer=0,
                hints=["Calcium ist ein Metall.", "Metalloxid + Wasser → Lauge.", "Eine Lauge."],
                solution="Calcium ist ein Metall, also entsteht eine Lauge: CaO + H₂O → Ca(OH)₂.",
                tags=["oxide"], spiral=["K-REAK"]),
        aufgabe("SL05-A3-003", "A", 3, "choice",
                "Warum ist Mineralwasser leicht sauer?",
                options=["Gelöstes Kohlenstoffdioxid bildet Kohlensäure.",
                         "Es enthält Zitronensäure.", "Es ist gekühlt."],
                answer=0,
                hints=["Welches Gas ist im Mineralwasser gelöst?",
                       "Kohlenstoffdioxid.",
                       "Es ist ein Nichtmetalloxid."],
                solution="Gelöstes CO₂ bildet mit Wasser Kohlensäure: CO₂ + H₂O → H₂CO₃. Deshalb reagiert Mineralwasser leicht sauer.",
                tags=["oxide"], spiral=["K-REAK"]),
        aufgabe("SL05-A4-004", "A", 4, "assign",
                "Ordne jedem Oxid die entstehende Lösung zu.",
                slots=["SO₂", "Na₂O", "CO₂"],
                values=["Säure", "Lauge", "Säure (zweites)"], answer=[0, 1, 2],
                hints=["Schwefel und Kohlenstoff sind Nichtmetalle.",
                       "Natrium ist ein Metall.",
                       "Nichtmetall → Säure."],
                solution="SO₂ und CO₂ sind Nichtmetalloxide → Säuren.\nNa₂O ist ein Metalloxid → Lauge.",
                tags=["oxide"], spiral=["K-REAK"]),
        aufgabe("SL05-B1-005", "B", 1, "choice",
                "Welche Säure entsteht aus Schwefeldioxid SO₂ und Wasser?",
                options=["schweflige Säure H₂SO₃", "Schwefelsäure H₂SO₄", "Salzsäure HCl"],
                answer=0,
                hints=["SO₂ hat zwei Sauerstoffatome.",
                       "Mit dem Wasser kommt eines dazu.",
                       "Also H₂SO₃."],
                solution="SO₂ + H₂O → H₂SO₃, die schweflige Säure. Schwefelsäure entsteht aus SO₃.",
                misconceptions=[fv("index_uebersehen", 1,
                                   "H₂SO₄ entsteht aus SO₃, nicht aus SO₂. Zähle die Sauerstoffatome.",
                                   "summenformel_falsch_gelesen")],
                tags=["oxide", "bbr"], spiral=["K-REAK", "K-BIND"]),
        aufgabe("SL05-B2-006", "B", 2, "choice",
                "Warum hat auch unbelasteter Regen nur pH 5,6?",
                options=["Kohlenstoffdioxid aus der Luft löst sich und bildet Kohlensäure.",
                         "Regen ist immer verschmutzt.",
                         "Regen enthält Stickoxide."],
                answer=0,
                hints=["Welches Gas ist überall in der Luft?",
                       "Kohlenstoffdioxid.",
                       "Es löst sich im Regentropfen."],
                solution="Auch ohne Schadstoffe löst sich Kohlenstoffdioxid aus der Luft im Regentropfen und bildet Kohlensäure. Deshalb liegt der natürliche pH-Wert bei 5,6, nicht bei 7.",
                tags=["oxide", "bbr"], spiral=["K-SL"]),
        aufgabe("SL05-B2-007", "B", 2, "choice",
                "Woher stammt das Schwefeldioxid im sauren Regen hauptsächlich?",
                options=["Aus der Verbrennung schwefelhaltiger Brennstoffe.",
                         "Aus der Atmung von Pflanzen.",
                         "Aus dem Meerwasser."],
                answer=0,
                hints=["Wobei entsteht SO₂?",
                       "Bei Verbrennungen.",
                       "Wenn der Brennstoff Schwefel enthält."],
                solution="Kohle und ungereinigte Öle enthalten Schwefel. Beim Verbrennen entsteht Schwefeldioxid, das mit Regenwasser schweflige Säure bildet.",
                tags=["oxide", "umwelt", "bbr"], spiral=["K-REAK"]),
        aufgabe("SL05-B3-008", "B", 3, "choice",
                "Warum werden Kalksteinfiguren durch sauren Regen zerstört?",
                options=["Säuren lösen Kalk unter Bildung von Kohlenstoffdioxid auf.",
                         "Der Regen ist zu kalt.",
                         "Kalkstein ist wasserlöslich."],
                answer=0,
                hints=["Was passiert, wenn Säure auf Kalk trifft?",
                       "Es schäumt.",
                       "Der Kalk löst sich."],
                solution="Säuren setzen aus dem Carbonat Kohlensäure frei, die zu CO₂ und Wasser zerfällt. Der Kalkstein wird dabei aufgelöst — deshalb verlieren Figuren über Jahrzehnte ihre Konturen.",
                tags=["oxide", "umwelt", "bbr"], spiral=["K-REAK"]),
        aufgabe("SL05-B3-009", "B", 3, "assign",
                "Ordne jeder Säure ihr Ausgangsoxid zu.",
                slots=["H₂CO₃", "H₂SO₃", "H₂SO₄"],
                values=["CO₂", "SO₂", "SO₃"], answer=[0, 1, 2],
                hints=["Zieh vom Säureformel ein H₂O ab.",
                       "H₂CO₃ minus H₂O ergibt CO₂.",
                       "H₂SO₄ minus H₂O ergibt SO₃."],
                solution="H₂CO₃ − H₂O = CO₂\nH₂SO₃ − H₂O = SO₂\nH₂SO₄ − H₂O = SO₃",
                tags=["oxide", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL05-B4-010", "B", 4, "choice",
                "Welche Maßnahme verringert den sauren Regen wirksam?",
                options=["Rauchgasentschwefelung in Kraftwerken.",
                         "Höhere Schornsteine.",
                         "Kalken der Wälder."],
                answer=0,
                hints=["Was setzt an der Ursache an?",
                       "Das Entfernen des Schwefeldioxids.",
                       "Die anderen Maßnahmen behandeln Folgen."],
                solution="Die Rauchgasentschwefelung entfernt das Schwefeldioxid, bevor es in die Atmosphäre gelangt — sie setzt an der Ursache an. Höhere Schornsteine verteilen das Problem nur, Kalken behandelt eine Folge.",
                misconceptions=[fv("folge_statt_ursache", 2,
                                   "Kalken neutralisiert bereits versauerte Böden — das ist eine Folgebehandlung, keine Ursachenbekämpfung.")],
                tags=["oxide", "bewerten", "msa"]),
        aufgabe("SL05-C2-011", "C", 2, "choice",
                "Warum reagiert eine Lösung von Natriumoxid stärker alkalisch als eine von Calciumoxid gleicher Stoffmenge?",
                options=["Na₂O liefert zwei gut lösliche NaOH; Ca(OH)₂ ist dagegen schwer löslich.",
                         "Natrium ist edler als Calcium.",
                         "Calciumoxid reagiert gar nicht mit Wasser."],
                answer=0,
                hints=["Wie viele Hydroxide entstehen jeweils?",
                       "Na₂O + H₂O → 2 NaOH.",
                       "Aber entscheidend ist die Löslichkeit."],
                solution="Na₂O bildet zwei Formeleinheiten NaOH, die sich vollständig lösen. Ca(OH)₂ ist dagegen schwer löslich — es gelangen weniger OH⁻-Ionen in Lösung, obwohl je Formeleinheit zwei vorhanden wären.",
                tags=["oxide", "msa"], spiral=["K-SL"]),
        aufgabe("SL05-C3-012", "C", 3, "multi",
                "In einem Kraftwerk entstehen je Tag 320 kg Schwefeldioxid SO₂ (M = 64 g/mol).",
                fields=[
                    {"label": "Stoffmenge des SO₂ in kmol", "answer": 5, "unit_label": "kmol", "tolerance": 0.2},
                    {"label": "Masse der daraus gebildeten H₂SO₃ (M = 82 g/mol) in kg", "answer": 410, "unit_label": "kg", "tolerance": 5}
                ],
                hints=["n = 320 : 64 = 5 kmol.",
                       "SO₂ + H₂O → H₂SO₃ läuft 1 : 1.",
                       "m = 5 · 82 = 410 kg."],
                solution="n(SO₂) = 320 kg : 64 kg/kmol = 5 kmol\nn(H₂SO₃) = 5 kmol → m = 5 · 82 = 410 kg",
                tags=["oxide", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("SL05-C3-013", "C", 3, "choice",
                "Warum ist die Aussage „Saurer Regen ist Regen mit pH unter 7“ fachlich unpräzise?",
                options=["Auch unbelasteter Regen liegt bei pH 5,6; von saurem Regen spricht man erst deutlich darunter.",
                         "Regen hat immer pH 7.",
                         "Regen kann nicht sauer sein."],
                answer=0,
                hints=["Welchen pH-Wert hat unbelasteter Regen?",
                       "5,6.",
                       "Also liegt jeder Regen unter 7."],
                solution="Durch gelöstes Kohlenstoffdioxid liegt jeder Regen unter pH 7. Die Grenze für „sauren Regen“ wird deshalb bei etwa pH 5 gezogen — der natürliche Wert ist der Bezugspunkt, nicht die 7.",
                tags=["oxide", "bewerten", "msa"], spiral=["K-SL"]),
        aufgabe("SL05-C4-014", "C", 4, "choice",
                "Bewerte: „Das Kalken von Wäldern löst das Problem des sauren Regens.“",
                options=["Es mildert eine Folge, beseitigt aber die Ursache nicht — dafür braucht es geringere Emissionen.",
                         "Richtig, damit ist das Problem gelöst.",
                         "Falsch, Kalken hat gar keine Wirkung."],
                answer=0,
                hints=["Was bewirkt Kalk im Boden?",
                       "Er neutralisiert die Säure.",
                       "Aber der Regen bleibt sauer."],
                solution="Kalk neutralisiert bereits versauerte Böden — das wirkt, aber nur örtlich und vorübergehend. Solange Schwefeldioxid und Stickoxide freigesetzt werden, muss immer wieder gekalkt werden. Wirksam an der Ursache setzen Entschwefelung und Katalysatoren an.",
                tags=["oxide", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "SL-06",
    "title": "Neutralisation und Salzbildung",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K2.4"],
    "klasse": 9,
    "wortspeicher": ["die Neutralisation", "das Salz", "die Titration", "der Äquivalenzpunkt",
                     "der Indikator", "die Bürette"],
    "worterklaerungen": {
        "Neutralisation": "Säure und Lauge reagieren zu Wasser und einem Salz.",
        "Titration": "Ein Messverfahren: Man gibt so lange Lauge zu, bis die Säure neutralisiert ist.",
        "Äquivalenzpunkt": "Der Punkt, an dem genau gleich viel Säure und Lauge umgesetzt sind."
    },
    "can_do": {
        "A": "Ich weiß, dass bei der Neutralisation Wasser und ein Salz entstehen.",
        "B": "Ich stelle Neutralisationsgleichungen auf und benenne das entstehende Salz.",
        "C": "Ich werte eine Titration aus und begründe den steilen Verlauf der Kurve."
    },
    "lernkarten": {
        "A": karte("Säure trifft Lauge",
                   "Säure und Lauge heben sich gegenseitig auf.",
                   ["Es entsteht Wasser.", "Und ein Salz."],
                   "Säure + Lauge → Salz + Wasser.",
                   visual=anim("neutralisation", "A"),
                   beispiel={"titel": "Salzsäure und Natronlauge",
                             "aufgabe": "HCl trifft auf NaOH.",
                             "schritte": ["Es entsteht Wasser.",
                                          "Und Natriumchlorid.",
                                          "Die Lösung wird neutral."],
                             "ergebnis": "HCl + NaOH → NaCl + H₂O"}),
        "B": karte("Welches Salz entsteht",
                   "Das Salz setzt sich immer aus zwei Teilen zusammen: dem Metall-Ion der Lauge und dem Säurerest-Ion der Säure.",
                   ["Salzsäure + Natronlauge → Natriumchlorid.",
                    "Schwefelsäure + Kalilauge → Kaliumsulfat.",
                    "Salpetersäure + Natronlauge → Natriumnitrat.",
                    "Der eigentliche Vorgang ist immer derselbe: H₃O⁺ + OH⁻ → 2 H₂O. Die übrigen Ionen bleiben unverändert in Lösung und heißen deshalb Zuschauerionen."],
                   "Metall-Ion der Lauge + Säurerest-Ion der Säure = das Salz.",
                   visual=anim("neutralisation", "B")),
        "C": karte("Die Titration auswerten",
                   "Die Titration macht aus der Neutralisation ein Messverfahren: Aus dem verbrauchten Volumen lässt sich die unbekannte Konzentration berechnen.",
                   ["Zur Säure wird aus einer Bürette Lauge bekannter Konzentration zugegeben, bis der Indikator umschlägt.",
                    "Am Äquivalenzpunkt gilt n(Säure) = n(Lauge), bei einprotonigen Säuren also c₁ · V₁ = c₂ · V₂.",
                    "Die Titrationskurve verläuft dort sehr steil: Kurz vor dem Punkt sind fast alle Oxonium-Ionen verbraucht, ein Tropfen ändert die Konzentration dann um Größenordnungen.",
                    "Genau deshalb funktioniert das Verfahren so genau — und deshalb wird am Ende tropfenweise zugegeben."],
                   "Am Äquivalenzpunkt: c(Säure) · V(Säure) = c(Lauge) · V(Lauge).",
                   visual=anim("neutralisation", "C"))
    },
    "formelkarte": {"formeln": ["Säure + Lauge → Salz + Wasser",
                               "H₃O⁺ + OH⁻ → 2 H₂O",
                               "HCl + NaOH → NaCl + H₂O",
                               "c₁ · V₁ = c₂ · V₂"],
                    "saetze": ["Bei der Neutralisation entstehen immer Wasser und ein Salz.",
                               "Das Salz besteht aus Metall-Ion und Säurerest-Ion.",
                               "Am Äquivalenzpunkt sind die Stoffmengen gleich.",
                               "Die Neutralisation ist exotherm."]},
    "tasks": [
        aufgabe("SL06-A1-001", "A", 1, "choice",
                "Was entsteht bei einer Neutralisation immer?",
                options=["Wasser", "ein Gas", "ein Metall"], answer=0,
                visual=anim("neutralisation", "A"),
                hints=["H₃O⁺ und OH⁻ reagieren miteinander.", "Daraus wird Wasser.", "Wasser."],
                solution="Bei jeder Neutralisation entsteht Wasser — dazu ein Salz aus den übrigen Ionen.",
                tags=["neutralisation"], spiral=["K-REAK"]),
        aufgabe("SL06-A2-002", "A", 2, "choice",
                "Welches Salz entsteht aus Salzsäure und Natronlauge?",
                options=["Natriumchlorid", "Natriumsulfat", "Kaliumchlorid"], answer=0,
                hints=["Das Metall stammt aus der Lauge.", "Der Säurerest aus der Säure.", "Natrium und Chlorid."],
                solution="Aus Na⁺ der Lauge und Cl⁻ der Säure entsteht Natriumchlorid — Kochsalz.",
                tags=["neutralisation"], spiral=["K-BIND"]),
        aufgabe("SL06-A3-003", "A", 3, "choice",
                "Welchen pH-Wert hat eine vollständig neutralisierte Lösung?",
                options=["7", "1", "14"], answer=0,
                hints=["Neutral liegt in der Mitte der Skala.", "Die Skala geht von 0 bis 14.", "7."],
                solution="Nach vollständiger Neutralisation liegt der pH-Wert bei 7.",
                tags=["neutralisation"], spiral=["K-SL"]),
        aufgabe("SL06-A4-004", "A", 4, "choice",
                "Warum wird das Reagenzglas bei einer Neutralisation warm?",
                options=["Die Reaktion ist exotherm.", "Die Säure war warm.", "Der Indikator erwärmt sich."],
                answer=0,
                hints=["Wird Energie frei oder gebraucht?", "Es wird warm — also frei.", "Exotherm."],
                solution="Die Neutralisation ist exotherm — bei der Bildung von Wasser wird Energie frei.",
                misconceptions=[fv("exo_endo_vertauscht", 1,
                                   "Die Wärme entsteht bei der Reaktion selbst, nicht durch die Ausgangsstoffe.")],
                tags=["neutralisation", "energie"], spiral=["K-REAK"]),
        aufgabe("SL06-B1-005", "B", 1, "choice",
                "Welches Salz entsteht aus Schwefelsäure und Kalilauge?",
                options=["Kaliumsulfat", "Kaliumchlorid", "Natriumsulfat"], answer=0,
                hints=["Das Metall stammt aus der Lauge: Kalium.",
                       "Der Säurerest aus der Schwefelsäure: Sulfat.",
                       "Kaliumsulfat."],
                solution="K⁺ aus der Kalilauge und SO₄²⁻ aus der Schwefelsäure ergeben Kaliumsulfat K₂SO₄.",
                tags=["neutralisation", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL06-B2-006", "B", 2, "choice",
                "Welche Teilchen reagieren bei jeder Neutralisation miteinander?",
                options=["H₃O⁺ und OH⁻", "Na⁺ und Cl⁻", "H₂O und NaCl"], answer=0,
                hints=["Welche Ionen verschwinden aus der Lösung?",
                       "Die, die sauer und alkalisch machen.",
                       "H₃O⁺ und OH⁻."],
                solution="H₃O⁺ + OH⁻ → 2 H₂O ist der eigentliche Vorgang. Na⁺ und Cl⁻ bleiben unverändert in Lösung — sie sind Zuschauerionen.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Na⁺ und Cl⁻ reagieren nicht miteinander — sie bleiben gelöst.",
                                   "edukt_produkt_vertauscht")],
                tags=["neutralisation", "bbr"], spiral=["K-REAK"]),
        aufgabe("SL06-B2-007", "B", 2, "numeric",
                "20 mL Salzsäure der Konzentration 0,1 mol/L werden mit Natronlauge der Konzentration 0,1 mol/L neutralisiert. Wie viel Lauge wird gebraucht?",
                answer=20, unit_label="mL", tolerance=0.5,
                hints=["c₁ · V₁ = c₂ · V₂.",
                       "Beide Konzentrationen sind gleich.",
                       "Also auch die Volumen."],
                solution="c₁ · V₁ = c₂ · V₂ → 0,1 · 20 = 0,1 · V₂ → V₂ = 20 mL",
                tags=["neutralisation", "rechnen", "bbr"], spiral=["K-SL", "K-QUANT"]),
        aufgabe("SL06-B3-008", "B", 3, "numeric",
                "25 mL Säure unbekannter Konzentration verbrauchen 15 mL Natronlauge mit 0,2 mol/L. Wie groß ist die Säurekonzentration?",
                answer=0.12, unit_label="mol/L", tolerance=0.005,
                hints=["c₁ · V₁ = c₂ · V₂.",
                       "c₁ = c₂ · V₂ : V₁.",
                       "0,2 · 15 : 25."],
                solution="c(Säure) = 0,2 mol/L · 15 mL : 25 mL = 0,12 mol/L",
                misconceptions=[fv("verduennen_falsch_herum", 0.333,
                                   "Achte auf die Zuordnung: Das kleinere Laugenvolumen bedeutet eine kleinere Säurekonzentration.",
                                   "ph_skala_falschrum")],
                tags=["neutralisation", "rechnen", "bbr"], spiral=["K-SL"]),
        aufgabe("SL06-B3-009", "B", 3, "choice",
                "Wozu dient der Indikator bei einer Titration?",
                options=["Er zeigt durch Farbumschlag an, wann der Äquivalenzpunkt erreicht ist.",
                         "Er beschleunigt die Reaktion.",
                         "Er neutralisiert die Säure."],
                answer=0,
                hints=["Wie erkennt man das Ende der Titration?",
                       "An einem Farbwechsel.",
                       "Den zeigt der Indikator."],
                solution="Der Indikator schlägt am Äquivalenzpunkt um und macht ihn damit sichtbar. An der Reaktion selbst nimmt er praktisch nicht teil.",
                tags=["neutralisation", "bbr"], spiral=["K-SL"]),
        aufgabe("SL06-B4-010", "B", 4, "choice",
                "Warum wird gegen Ende der Titration nur noch tropfenweise zugegeben?",
                options=["Nahe dem Äquivalenzpunkt ändert schon ein Tropfen den pH-Wert stark.",
                         "Damit die Bürette länger hält.",
                         "Damit die Reaktion langsamer wird."],
                answer=0,
                visual=anim("neutralisation", "C"),
                hints=["Sieh dir den Verlauf der Titrationskurve an.",
                       "Sie ist dort sehr steil.",
                       "Ein Tropfen entscheidet."],
                solution="Kurz vor dem Äquivalenzpunkt sind fast alle Oxonium-Ionen verbraucht. Ein weiterer Tropfen ändert die Konzentration dann um Größenordnungen — die Kurve verläuft dort fast senkrecht.",
                tags=["neutralisation", "msa"], spiral=["K-SL"]),
        aufgabe("SL06-C2-011", "C", 2, "choice",
                "Warum sind Na⁺ und Cl⁻ bei der Neutralisation von HCl mit NaOH „Zuschauerionen“?",
                options=["Sie bleiben unverändert in Lösung und reagieren nicht miteinander.",
                         "Sie bilden sofort festes Kochsalz.",
                         "Sie verlassen die Lösung als Gas."],
                answer=0,
                hints=["Was passiert mit ihnen während der Reaktion?",
                       "Nichts.",
                       "Erst beim Eindampfen bilden sie einen Kristall."],
                solution="Während der Neutralisation reagieren nur H₃O⁺ und OH⁻. Na⁺ und Cl⁻ bleiben gelöst und unverändert — erst beim Eindampfen kristallisieren sie als Kochsalz aus.",
                tags=["neutralisation", "msa"], spiral=["K-SL"]),
        aufgabe("SL06-C3-012", "C", 3, "multi",
                "20 mL Schwefelsäure werden mit 32 mL Natronlauge (0,25 mol/L) neutralisiert. Schwefelsäure ist zweiprotonig.",
                fields=[
                    {"label": "Stoffmenge der Natronlauge in mmol", "answer": 8, "unit_label": "mmol", "tolerance": 0.3},
                    {"label": "Stoffmenge der Schwefelsäure in mmol", "answer": 4, "unit_label": "mmol", "tolerance": 0.2},
                    {"label": "Konzentration der Schwefelsäure", "answer": 0.2, "unit_label": "mol/L", "tolerance": 0.01}
                ],
                hints=["n(NaOH) = 0,25 · 0,032 L = 8 mmol.",
                       "Ein H₂SO₄ verbraucht zwei NaOH.",
                       "c = 4 mmol : 20 mL."],
                solution="n(NaOH) = 0,25 mol/L · 0,032 L = 8 mmol\nn(H₂SO₄) = 8 : 2 = 4 mmol\nc = 4 mmol : 0,020 L = 0,2 mol/L",
                misconceptions=[],
                tags=["neutralisation", "rechnen", "msa"], spiral=["K-QUANT", "K-SL"]),
        aufgabe("SL06-C3-013", "C", 3, "choice",
                "Warum liegt der Äquivalenzpunkt bei der Titration einer schwachen Säure mit einer starken Lauge nicht bei pH 7?",
                options=["Das entstehende Salz reagiert selbst leicht alkalisch, weil sein Anion Protonen aufnimmt.",
                         "Der Indikator ist ungenau.",
                         "Die Titration wurde falsch durchgeführt."],
                answer=0,
                hints=["Was entsteht am Äquivalenzpunkt?",
                       "Das Salz der schwachen Säure.",
                       "Sein Anion ist eine Base."],
                solution="Am Äquivalenzpunkt liegt das Salz der schwachen Säure vor. Sein Anion nimmt Protonen aus dem Wasser auf und setzt dabei OH⁻ frei — die Lösung reagiert leicht alkalisch. Deshalb wird der Indikator passend zur Säure gewählt.",
                tags=["neutralisation", "msa"], spiral=["K-SL"]),
        aufgabe("SL06-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Nach der Neutralisation ist nichts mehr da — Säure und Lauge haben sich aufgehoben.“ Wie bewertest du das?",
                options=["Falsch — die Ionen sind weiterhin vorhanden; sie bilden Wasser und ein gelöstes Salz.",
                         "Richtig, beide sind verschwunden.",
                         "Falsch — es bleibt nur Säure übrig."],
                answer=0,
                hints=["Was passiert beim Eindampfen der neutralisierten Lösung?",
                       "Ein Salz bleibt zurück.",
                       "Also war es die ganze Zeit vorhanden."],
                solution="„Aufheben“ meint nur den pH-Wert. Die Teilchen sind vollständig erhalten: H₃O⁺ und OH⁻ bilden Wasser, die übrigen Ionen bleiben gelöst und lassen sich als Salz gewinnen. Masse geht nicht verloren.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Beim Eindampfen bleibt das Salz zurück — es war die ganze Zeit da.",
                                   "masse_verschwindet")],
                tags=["neutralisation", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

if __name__ == "__main__":
    schreiben("sl", E, "Bereich SL · Einheiten 5 und 6")
