# -*- coding: utf-8 -*-
"""Bereich ES · Ester und Makromoleküle — ES-06, die letzte Einheit des Curriculums."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ES-06",
    "title": "Anwenden & Prüfungstraining Ester",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["die Veresterung", "die Verseifung", "das Glycerid", "der Polyester",
                     "die Kondensationsreaktion", "das Gleichgewicht"],
    "worterklaerungen": {
        "Kondensationsreaktion": "Zwei Moleküle verbinden sich unter Abspaltung eines kleinen Moleküls, meist Wasser."
    },
    "can_do": {
        "A": "Ich benenne Ester und weiß, woraus sie entstehen.",
        "B": "Ich verbinde Veresterung, Fette, Seifen und Polyester miteinander.",
        "C": "Ich begründe Eigenschaften aus dem Bau und bewerte Anwendungen und Recycling."
    },
    "lernkarten": {
        "A": karte("Ester auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["Säure plus Alkohol ergibt Ester und Wasser.",
                    "Fette und Kunststoffe sind ebenfalls Ester."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Ein Prinzip, vier Anwendungen",
                   "Der gesamte Bereich beruht auf einer einzigen Reaktion — der Veresterung. Alles Weitere ist ihre Anwendung in verschiedenem Maßstab.",
                   ["Ein Alkohol und eine Säure: Es entsteht ein einzelnes Estermolekül — ein Aromastoff oder Lösungsmittel.",
                    "Glycerin mit drei OH-Gruppen und drei Fettsäuren: Es entsteht ein Fett.",
                    "Ein Fett mit Lauge gespalten: Es entstehen Glycerin und Seife.",
                    "Bausteine mit je zwei funktionellen Gruppen: Es entsteht ein Polyester.",
                    "Immer dieselbe Bindung, immer dieselbe Wasserabspaltung — nur die Zahl der Gruppen unterscheidet sich."],
                   "Eine Reaktion, vier Maßstäbe: Aroma, Fett, Seife, Kunststoff.",
                   visual=anim("veresterung", "B")),
        "C": karte("Der Bogen über vier Jahre",
                   "Diese Einheit schließt nicht nur den Bereich ab, sondern das gesamte Curriculum. Dieselben Denkweisen tragen von Klasse 7 bis Klasse 10.",
                   ["Stoff und Teilchen: Was man sieht, wird auf der Teilchenebene gedeutet — vom Aggregatzustand bis zur Micelle.",
                    "Struktur und Eigenschaft: Der Bau bestimmt die Eigenschaften — vom Ionengitter über den Wasserdipol bis zur Kettenlänge im Polyester.",
                    "Chemische Reaktion: Es geht kein Atom verloren — von der Massenerhaltung bis zur Polykondensation.",
                    "Energie: Jede Reaktion setzt Energie um — von der Verbrennung bis zum Katalysator.",
                    "Und über allem: Eine Bewertung braucht ein Kriterium, eine Begründung eine Ursache und ein Modell die Kenntnis seiner Grenzen."],
                   "Vier Basiskonzepte, vier Jahre — und dieselben Fragen.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["R–COOH + HO–R' ⇌ R–COO–R' + H₂O",
                               "Fett + 3 NaOH → Glycerin + 3 Seife",
                               "Dicarbonsäure + zweiwertiger Alkohol → Polyester + n H₂O"],
                    "saetze": ["Veresterung: Säure + Alkohol ⇌ Ester + Wasser.",
                               "Verseifung ist ihre Umkehrung mit Lauge.",
                               "Fette sind Ester aus Glycerin und drei Fettsäuren.",
                               "Für einen Polyester braucht jeder Baustein zwei funktionelle Gruppen."]},
    "tasks": [
        aufgabe("ES06-A1-001", "A", 1, "choice",
                "Woraus entsteht ein Ester?",
                options=["aus einer Säure und einem Alkohol", "aus zwei Säuren", "aus zwei Alkoholen"],
                answer=0, visual=anim("veresterung", "A"),
                hints=["Zwei verschiedene Stoffklassen.", "Säure und Alkohol.", "Genau die."],
                solution="Ein Ester entsteht aus einer Carbonsäure und einem Alkohol; dabei wird Wasser frei.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("ES06-A2-002", "A", 2, "choice",
                "Woraus besteht ein Fett?",
                options=["aus Glycerin und drei Fettsäuren", "aus Zucker", "aus Eiweiß"], answer=0,
                hints=["Es ist ein Ester.", "Der Alkohol ist Glycerin.", "Dazu drei Fettsäuren."],
                solution="Fette sind Ester aus Glycerin und drei Fettsäuren — deshalb heißen sie auch Glyceride.",
                tags=["pruefung"], spiral=["K-ORG"]),
        aufgabe("ES06-A3-003", "A", 3, "choice",
                "Was entsteht bei der Verseifung?",
                options=["Glycerin und Seife", "ein Ester", "ein Alkohol und eine Säure"],
                answer=0,
                hints=["Das Fett wird mit Lauge gespalten.",
                       "Der Alkoholteil bleibt als Glycerin.",
                       "Die Säuren werden zu Salzen — der Seife."],
                solution="Bei der Verseifung entstehen Glycerin und die Natriumsalze der Fettsäuren, also Seife.",
                tags=["pruefung"], spiral=["K-REAK"]),
        aufgabe("ES06-A4-004", "A", 4, "choice",
                "Was hält ein Seifenteilchen an beiden Enden fest?",
                options=["Wasser am Kopf, Fett am Schwanz", "nur Wasser", "nur Fett"], answer=0,
                visual=anim("seife", "A"),
                hints=["Zwei Enden, zwei Aufgaben.",
                       "Der Kopf ist geladen.",
                       "Der Schwanz ist unpolar."],
                solution="Der geladene Kopf löst sich im Wasser, der unpolare Schwanz im Fett — so vermittelt die Seife zwischen beiden.",
                tags=["pruefung"], spiral=["K-SL"]),
        aufgabe("ES06-B1-005", "B", 1, "choice",
                "Warum steht bei der Veresterung ein Gleichgewichtspfeil, bei der Verseifung aber nicht?",
                options=["Bei der Verseifung wird die Säure als Salz gebunden; die Rückreaktion ist blockiert.",
                         "Die Verseifung ist schneller.",
                         "Bei der Veresterung wird nicht erhitzt."],
                answer=0,
                hints=["Was passiert bei der Verseifung mit der Säure?",
                       "Sie wird zum Salz.",
                       "Ein Salz reagiert nicht zurück."],
                solution="Die Lauge überführt die entstehende Säure sofort in ihr Salz. Damit steht sie für die Rückreaktion nicht mehr zur Verfügung — die Verseifung läuft vollständig ab.",
                tags=["pruefung", "msa"], spiral=["K-REAK"]),
        aufgabe("ES06-B2-006", "B", 2, "numeric",
                "Wie viele Esterbindungen hat ein Fettmolekül?",
                answer=3, tolerance=0,
                hints=["Glycerin hat drei OH-Gruppen.", "Jede bildet eine Bindung.", "3."],
                solution="Drei OH-Gruppen des Glycerins ergeben drei Esterbindungen.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES06-B2-007", "B", 2, "choice",
                "Warum braucht ein Polyester Bausteine mit zwei funktionellen Gruppen?",
                options=["Nur dann kann die Kette an beiden Enden weiterwachsen.",
                         "Damit der Kunststoff fester wird.",
                         "Damit er sich löst."],
                answer=0,
                hints=["Was passiert bei nur einer Gruppe?",
                       "Die Kette endet.",
                       "Für Wachstum braucht es zwei Enden."],
                solution="Mit nur einer funktionellen Gruppe endet die Kette nach der ersten Verknüpfung. Erst zwei Gruppen erlauben das Weiterwachsen.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES06-B3-008", "B", 3, "multi",
                "88 g Essigsäureethylester (M = 88 g/mol) werden vollständig gespalten. Es entstehen Essigsäure (M = 60 g/mol) und Ethanol (M = 46 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Esters", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse der entstehenden Essigsäure", "answer": 60, "unit_label": "g", "tolerance": 2},
                    {"label": "Masse des entstehenden Ethanols", "answer": 46, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 88 : 88 = 1 mol.",
                       "Je 1 mol Säure und Alkohol.",
                       "Beachte: 60 + 46 = 106, die Differenz ist das aufgenommene Wasser."],
                solution="n = 1 mol → 60 g Essigsäure und 46 g Ethanol\nProbe: 88 g Ester + 18 g Wasser = 106 g — die Massenbilanz stimmt.",
                tags=["pruefung", "rechnen", "bbr"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("ES06-B3-009", "B", 3, "choice",
                "Warum ist ein Ester flüchtiger als die Säure, aus der er stammt?",
                options=["Ihm fehlt die freie OH-Gruppe für Wasserstoffbrücken.",
                         "Er ist leichter.",
                         "Er ist wärmer."],
                answer=0,
                hints=["Was macht die Carboxygruppe?",
                       "Sie bildet Wasserstoffbrücken.",
                       "Im Ester ist sie verbraucht."],
                solution="Bei der Veresterung wird die OH-Gruppe der Säure verbraucht. Ohne sie bilden die Estermoleküle untereinander keine Wasserstoffbrücken — sie verdunsten leichter und riechen deshalb.",
                tags=["pruefung", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES06-B4-010", "B", 4, "choice",
                "Warum wäscht Seife in hartem Wasser schlecht?",
                options=["Calcium- und Magnesium-Ionen bilden mit den Fettsäureresten unlösliche Kalkseife.",
                         "Hartes Wasser ist zu kalt.",
                         "Hartes Wasser enthält keine Ionen."],
                answer=0,
                hints=["Was ist in hartem Wasser gelöst?",
                       "Calcium- und Magnesium-Ionen.",
                       "Sie fällen die Seife aus."],
                solution="Calcium- und Magnesium-Ionen bilden mit den Fettsäureresten schwerlösliche Salze. Die Seife fällt aus, steht für die Micellbildung nicht mehr zur Verfügung und hinterlässt Ränder.",
                tags=["pruefung", "msa"], spiral=["K-SL"]),
        aufgabe("ES06-C2-011", "C", 2, "choice",
                "Welche Gemeinsamkeit haben Veresterung, Fettbildung und Polykondensation?",
                options=["Bei allen wird unter Abspaltung von Wasser eine Esterbindung geknüpft.",
                         "Bei allen entsteht ein Gas.",
                         "Bei allen wird Energie frei."],
                answer=0,
                hints=["Welche Bindung entsteht jeweils?",
                       "Die Esterbindung.",
                       "Und immer wird Wasser abgespalten."],
                solution="Alle drei sind Kondensationsreaktionen: Es entsteht eine Esterbindung, und dabei wird Wasser abgespalten. Verschieden ist nur die Zahl der beteiligten funktionellen Gruppen.",
                tags=["pruefung", "msa"], spiral=["K-REAK"]),
        aufgabe("ES06-C3-012", "C", 3, "choice",
                "Warum lässt sich PET chemisch recyceln, Polyethylen aber nicht auf demselben Weg?",
                options=["PET enthält spaltbare Esterbindungen; Polyethylen besteht nur aus stabilen C–C-Bindungen.",
                         "PET ist weicher.",
                         "Polyethylen ist kein Kunststoff."],
                answer=0,
                hints=["Welche Bindungen verknüpfen die Bausteine jeweils?",
                       "Bei PET Esterbindungen.",
                       "Bei Polyethylen nur C–C."],
                solution="Esterbindungen lassen sich gezielt spalten — die Monomere sind zurückgewinnbar. Die C–C-Bindungen im Polyethylen sind dagegen sehr stabil und nicht selektiv spaltbar; dort bleibt nur werkstoffliches Recycling.",
                tags=["pruefung", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("ES06-C3-013", "C", 3, "choice",
                "Welche Antwort auf „Erkläre die Waschwirkung der Seife“ ist vollständig?",
                options=["Der unpolare Schwanz löst sich im Fett, der geladene Kopf im Wasser; es entstehen Micellen, die sich gegenseitig abstoßen und abgespült werden können.",
                         "Seife löst Fett auf.",
                         "Seife macht das Wasser sauber."],
                answer=0,
                hints=["„Erkläre“ verlangt den Mechanismus.",
                       "Zwei Enden, Micelle, Abstoßung.",
                       "Alle drei Schritte gehören hinein."],
                solution="Eine vollständige Erklärung nennt den Bau des Teilchens, die Bildung der Micelle und die Abstoßung der Tropfen. Antwort 2 und 3 beschreiben nur das Ergebnis.",
                tags=["pruefung", "operatoren", "msa"], spiral=["K-SL"]),
        aufgabe("ES06-C4-014", "C", 4, "choice",
                "Über vier Jahre Chemie hinweg: Welche Aussage trifft den gemeinsamen Kern am besten?",
                options=["Der Bau der Teilchen erklärt die Eigenschaften der Stoffe — vom Ionengitter bis zum Polyester.",
                         "Chemie besteht aus Formeln, die man auswendig lernt.",
                         "Jeder Stoff verhält sich anders, Regeln gibt es nicht."],
                answer=0,
                hints=["Was zieht sich von Klasse 7 bis 10 durch?",
                       "Der Zusammenhang von Bau und Eigenschaften.",
                       "Das Struktur-Eigenschafts-Konzept."],
                solution="Vom Teilchenmodell über das Ionengitter, den Wasserdipol und die van-der-Waals-Kräfte bis zum Makromolekül gilt derselbe Gedanke: Art, Anordnung und Wechselwirkung der Teilchen bestimmen die Eigenschaften des Stoffes. Formeln sind Werkzeuge dafür, nicht der Inhalt.",
                tags=["pruefung", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("es", E, "Bereich ES · Einheit 6 — letzte Einheit des Curriculums")
