# -*- coding: utf-8 -*-
"""Bereich AL · Alkohole (Klasse 10, Themenfeld 3.10) — AL-01 bis AL-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "AL-01",
    "title": "Alkohole im Alltag — die Hydroxylgruppe",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.2"],
    "klasse": 10,
    "sicherheit": [
        "Ethanol ist leicht entzündbar. Beim Arbeiten damit bleibt der Brenner aus.",
        "Methanol ist giftig und darf nie mit Ethanol verwechselt werden."
    ],
    "wortspeicher": ["der Alkohol", "die Hydroxylgruppe", "das Alkanol", "die funktionelle Gruppe",
                     "das Ethanol", "das Methanol", "die Gärung"],
    "worterklaerungen": {
        "Hydroxylgruppe": "Die Gruppe –OH. Sie kennzeichnet die Alkohole.",
        "funktionelle Gruppe": "Eine Atomgruppe, die die Eigenschaften einer Stoffklasse bestimmt.",
        "Alkanol": "Der Fachname für einen Alkohol."
    },
    "can_do": {
        "A": "Ich erkenne die Hydroxylgruppe und nenne Alkohole aus dem Alltag.",
        "B": "Ich erkläre, warum die funktionelle Gruppe die Eigenschaften bestimmt.",
        "C": "Ich bewerte die Wirkung von Alkoholen und begründe den Unterschied zwischen Methanol und Ethanol."
    },
    "lernkarten": {
        "A": karte("Die OH-Gruppe",
                   "Alkohole haben eine besondere Gruppe.",
                   ["Sie heißt Hydroxylgruppe und wird –OH geschrieben.",
                    "Ethanol ist der Alkohol in Getränken."],
                   "–OH kennzeichnet einen Alkohol.",
                   visual={"type": "struktur", "kette": 2, "gruppe": "oh", "name": "Ethanol",
                           "formel": "C2H5OH",
                           "alt": "Strukturformel von Ethanol mit Hydroxylgruppe."},
                   beispiel={"titel": "Ethanol", "aufgabe": "Wie ist Ethanol gebaut?",
                             "schritte": ["Zwei Kohlenstoffatome.",
                                          "Am ersten sitzt eine OH-Gruppe."],
                             "ergebnis": "CH₃–CH₂–OH"}),
        "B": karte("Die funktionelle Gruppe entscheidet",
                   "Ein Alkoholmolekül besteht aus zwei Teilen: einem unpolaren Kohlenwasserstoffrest und einer polaren OH-Gruppe. Fast alle Eigenschaften folgen aus diesem Gegensatz.",
                   ["Die OH-Gruppe ist polar und bildet Wasserstoffbrücken — untereinander und mit Wasser.",
                    "Deshalb sieden Alkohole viel höher als Alkane vergleichbarer Masse: Ethanol bei 78 °C, Propan bei −42 °C.",
                    "Deshalb sind kurzkettige Alkohole mit Wasser mischbar.",
                    "Der Kohlenwasserstoffrest ist unpolar. Je länger er wird, desto weniger überwiegt die OH-Gruppe — die Wasserlöslichkeit nimmt ab.",
                    "Alkohole reagieren nicht sauer: Die OH-Gruppe gibt hier kein Proton ab, anders als bei den Säuren."],
                   "Polare OH-Gruppe plus unpolarer Rest — das Verhältnis der beiden bestimmt alles.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "oh", "name": "Propan-1-ol",
                           "alt": "Strukturformel von Propanol."}),
        "C": karte("Warum Methanol so gefährlich ist",
                   "Methanol und Ethanol unterscheiden sich um genau eine CH₂-Gruppe — und in der Wirkung auf den Körper fundamental. Das ist ein Musterbeispiel dafür, wie wenig ein kleiner Bauunterschied bedeuten kann und wie viel doch.",
                   ["Beide werden im Körper vom selben Enzym abgebaut. Aus Ethanol entsteht dabei zunächst Ethanal, aus Methanol Methanal.",
                    "Ethanal wird rasch weiter zu Essigsäure abgebaut und ausgeschieden.",
                    "Aus Methanal entsteht Methansäure, die sich anreichert und den Sehnerv schädigt. Bereits 10 mL Methanol können erblinden lassen.",
                    "Der Geruch und der Geschmack unterscheiden beide kaum — deshalb ist der bewusste Umgang mit Kennzeichnung im Labor keine Formsache.",
                    "Auch Ethanol ist ein Zellgift; seine Wirkung setzt nur später ein und ist reversibel."],
                   "Eine CH₂-Gruppe Unterschied — und ein völlig anderes Abbauprodukt.",
                   visual={"type": "struktur", "kette": 1, "gruppe": "oh", "name": "Methanol",
                           "formel": "CH3OH",
                           "alt": "Strukturformel von Methanol."})
    },
    "formelkarte": {"formeln": ["Alkanole: CₙH₂ₙ₊₁OH",
                               "Methanol CH₃OH · Ethanol C₂H₅OH · Propanol C₃H₇OH"],
                    "saetze": ["–OH ist die Hydroxylgruppe, die funktionelle Gruppe der Alkohole.",
                               "Alkohole sieden höher als Alkane vergleichbarer Masse.",
                               "Kurzkettige Alkohole sind mit Wasser mischbar.",
                               "Alkohole reagieren nicht sauer.",
                               "Methanol ist giftig, Ethanol berauschend — beide sind Zellgifte."]},
    "tasks": [
        aufgabe("AL01-A1-001", "A", 1, "choice",
                "Welche Gruppe kennzeichnet einen Alkohol?",
                options=["–OH", "–COOH", "–CHO"], answer=0,
                visual={"type": "struktur", "kette": 2, "gruppe": "oh",
                        "alt": "Strukturformel von Ethanol."},
                hints=["Sie heißt Hydroxylgruppe.", "Sie besteht aus O und H.", "–OH."],
                solution="Die Hydroxylgruppe –OH kennzeichnet die Alkohole.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "–COOH ist die Carboxygruppe der organischen Säuren.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["alkohole"], spiral=["K-ORG"]),
        aufgabe("AL01-A2-002", "A", 2, "choice",
                "Wie heißt der Alkohol in Getränken?",
                options=["Ethanol", "Methanol", "Propanol"], answer=0,
                hints=["Er hat zwei C-Atome.", "Eth steht für 2.", "Ethanol."],
                solution="Ethanol C₂H₅OH ist der Alkohol in Getränken. Methanol ist giftig.",
                tags=["alkohole"], spiral=["K-ORG"]),
        aufgabe("AL01-A3-003", "A", 3, "numeric",
                "Wie viele C-Atome hat Methanol?",
                answer=1, tolerance=0,
                hints=["Meth steht für eine Zahl.", "Meth = 1.", "1."],
                solution="Methanol CH₃OH hat ein Kohlenstoffatom.",
                tags=["alkohole"], spiral=["K-ORG"]),
        aufgabe("AL01-A4-004", "A", 4, "choice",
                "Warum darf im Labor Methanol nie mit Ethanol verwechselt werden?",
                options=["Methanol ist giftig und kann zur Erblindung führen.",
                         "Methanol riecht schlechter.", "Methanol ist teurer."],
                answer=0,
                hints=["Beide riechen ähnlich.",
                       "Einer der beiden ist giftig.",
                       "Methanol."],
                solution="Methanol wird im Körper zu Methansäure abgebaut, die den Sehnerv schädigt. Schon kleine Mengen können zur Erblindung führen — deshalb ist die Kennzeichnung entscheidend.",
                tags=["alkohole", "sicherheit"]),
        aufgabe("AL01-B1-005", "B", 1, "choice",
                "Warum siedet Ethanol (78 °C) viel höher als Propan (−42 °C), obwohl beide ähnlich schwer sind?",
                options=["Zwischen Ethanolmolekülen wirken Wasserstoffbrücken.",
                         "Ethanol ist schwerer.",
                         "Propan ist ein Gemisch."],
                answer=0,
                hints=["Was hat Ethanol, was Propan nicht hat?",
                       "Die OH-Gruppe.",
                       "Sie bildet Wasserstoffbrücken."],
                solution="Die polare OH-Gruppe bildet Wasserstoffbrücken zwischen den Molekülen. Diese sind viel stärker als die van-der-Waals-Kräfte zwischen Alkanmolekülen — deshalb der große Siedepunktunterschied.",
                tags=["alkohole", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL01-B2-006", "B", 2, "choice",
                "Warum mischt sich Ethanol vollständig mit Wasser?",
                options=["Die OH-Gruppe bildet Wasserstoffbrücken zum Wasser.",
                         "Ethanol ist leichter als Wasser.",
                         "Ethanol ist unpolar."],
                answer=0,
                hints=["Gleiches löst sich in Gleichem.",
                       "Wasser ist polar.",
                       "Die OH-Gruppe auch."],
                solution="Die polare OH-Gruppe bildet Wasserstoffbrücken zu den Wassermolekülen. Bei Ethanol überwiegt sie den kurzen unpolaren Rest — die Mischbarkeit ist vollständig.",
                misconceptions=[fv("polar_unpolar_vertauscht", 2,
                                   "Wäre Ethanol unpolar, würde es sich wie Benzin verhalten und nicht mischen.",
                                   "polar_unpolar_vertauscht")],
                tags=["alkohole", "bbr"], spiral=["K-SL"]),
        aufgabe("AL01-B2-007", "B", 2, "choice",
                "Reagiert eine Ethanollösung sauer?",
                options=["Nein — die OH-Gruppe gibt hier kein Proton ab.",
                         "Ja, weil sie ein H enthält.",
                         "Ja, weil Alkohol ätzend ist."],
                answer=0,
                hints=["Prüfe mit Indikatorpapier.",
                       "Es bleibt neutral.",
                       "Die OH-Gruppe des Alkohols ist keine Säuregruppe."],
                solution="Trotz des Wasserstoffatoms in der OH-Gruppe gibt Ethanol kein Proton an Wasser ab. Der Indikator bleibt neutral. Erst die Carboxygruppe der Säuren tut das.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Nicht jedes H-Atom macht sauer. Entscheidend ist die funktionelle Gruppe.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["alkohole", "bbr"], spiral=["K-SL"]),
        aufgabe("AL01-B3-008", "B", 3, "choice",
                "Warum löst sich Hexanol deutlich schlechter in Wasser als Methanol?",
                options=["Der lange unpolare Rest überwiegt die polare OH-Gruppe.",
                         "Hexanol hat keine OH-Gruppe.",
                         "Hexanol ist schwerer."],
                answer=0,
                hints=["Beide haben eine OH-Gruppe.",
                       "Verschieden ist die Kettenlänge.",
                       "Der lange Rest ist unpolar."],
                solution="Beide haben eine OH-Gruppe. Bei Methanol dominiert sie das kleine Molekül, bei Hexanol überwiegt der lange unpolare Rest — das Verhältnis kippt zwischen Propanol und Butanol.",
                tags=["alkohole", "bbr"], spiral=["K-SL"]),
        aufgabe("AL01-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Ethanol C₂H₅OH? (C = 12, H = 1, O = 16 g/mol)",
                answer=46, unit_label="g/mol", tolerance=0.5,
                hints=["2 C, 6 H, 1 O.",
                       "24 + 6 + 16.",
                       "46 g/mol."],
                solution="M = 2 · 12 + 6 · 1 + 16 = 46 g/mol",
                misconceptions=[fv("summenformel_falsch_gelesen", 45,
                                   "Zähle alle H-Atome: fünf im C₂H₅ und eines in der OH-Gruppe, zusammen sechs.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkohole", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("AL01-B4-010", "B", 4, "choice",
                "Warum wirkt Ethanol desinfizierend?",
                options=["Es zerstört die Zellhülle von Mikroorganismen und fällt ihre Eiweiße aus.",
                         "Es kühlt die Haut.",
                         "Es riecht stark."],
                answer=0,
                hints=["Was macht Alkohol mit Eiweißen?",
                       "Er denaturiert sie.",
                       "Deshalb wirkt er auf Zellen."],
                solution="Ethanol löst Bestandteile der Zellmembran und fällt Eiweiße aus. Dieselbe Wirkung, die Mikroorganismen abtötet, macht es zugleich zu einem Zellgift für den Menschen.",
                tags=["alkohole", "anwenden", "msa"]),
        aufgabe("AL01-C2-011", "C", 2, "choice",
                "Warum ist Methanol giftig, Ethanol aber „nur“ berauschend?",
                options=["Aus Methanol entsteht beim Abbau Methansäure, die den Sehnerv schädigt.",
                         "Methanol ist ätzend.",
                         "Ethanol wird nicht abgebaut."],
                answer=0,
                hints=["Beide werden vom selben Enzym abgebaut.",
                       "Verschieden ist das Abbauprodukt.",
                       "Aus Methanol wird Methansäure."],
                solution="Beide Alkohole werden vom selben Enzym oxidiert. Aus Ethanol entsteht Essigsäure, die abgebaut wird. Aus Methanol entsteht Methansäure, die sich anreichert und den Sehnerv schädigt.",
                tags=["alkohole", "bewerten", "msa"], spiral=["K-ORG"]),
        aufgabe("AL01-C3-012", "C", 3, "choice",
                "Warum verdunstet Ethanol schneller als Wasser, obwohl seine Moleküle schwerer sind?",
                options=["Ein Ethanolmolekül bildet weniger Wasserstoffbrücken als ein Wassermolekül.",
                         "Ethanol ist unpolar.",
                         "Ethanol ist leichter."],
                answer=0,
                hints=["Wie viele H-Atome am Sauerstoff hat Wasser?",
                       "Zwei — Ethanol nur eines.",
                       "Weniger Brücken heißt leichteres Verdampfen."],
                solution="Ein Wassermolekül kann über zwei H-Atome Brücken bilden, Ethanol nur über eines. Die Moleküle lassen sich leichter voneinander trennen — trotz größerer Masse verdunstet Ethanol schneller.",
                tags=["alkohole", "msa"], spiral=["K-STOF"]),
        aufgabe("AL01-C3-013", "C", 3, "multi",
                "Ein Desinfektionsmittel enthält 70 % Ethanol. Es werden 250 g angesetzt. (M(Ethanol) = 46 g/mol)",
                fields=[
                    {"label": "Masse des Ethanols", "answer": 175, "unit_label": "g", "tolerance": 2},
                    {"label": "Stoffmenge des Ethanols", "answer": 3.8, "unit_label": "mol", "tolerance": 0.2}
                ],
                hints=["70 % von 250 g.",
                       "175 g.",
                       "n = 175 : 46."],
                solution="m = 250 · 0,70 = 175 g\nn = 175 g : 46 g/mol = 3,8 mol",
                tags=["alkohole", "rechnen", "msa"], spiral=["K-SL", "K-QUANT"]),
        aufgabe("AL01-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Ethanol ist ungiftig, sonst dürfte man es nicht trinken.“ Wie bewertest du das?",
                options=["Falsch — Ethanol ist ein Zellgift; entscheidend sind Menge und Geschwindigkeit des Abbaus.",
                         "Richtig, Trinkalkohol ist ungiftig.",
                         "Falsch, Ethanol ist genauso giftig wie Methanol."],
                answer=0,
                hints=["Warum wirkt Alkohol desinfizierend?",
                       "Weil er Zellen schädigt.",
                       "Auf menschliche Zellen wirkt er ebenso."],
                solution="Ethanol schädigt Zellen — genau darauf beruht seine desinfizierende Wirkung. Der Körper kann kleine Mengen abbauen, größere führen zu Vergiftungserscheinungen. Die Menge entscheidet, nicht der Stoff allein.",
                tags=["alkohole", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "AL-02",
    "title": "Homologe Reihe und Nomenklatur der Alkanole",
    "leitidee": "B1",
    "standards": ["K1", "K3.4"],
    "klasse": 10,
    "wortspeicher": ["das Alkanol", "die homologe Reihe", "die Stellungsisomerie",
                     "die Nomenklatur", "die Endung -ol"],
    "worterklaerungen": {
        "Alkanol": "Ein Alkan, bei dem ein H-Atom durch eine OH-Gruppe ersetzt ist.",
        "Stellungsisomerie": "Dieselbe Gruppe sitzt an verschiedenen Stellen der Kette."
    },
    "can_do": {
        "A": "Ich benenne die ersten Alkanole und gebe ihre Formeln an.",
        "B": "Ich wende die Nomenklaturregeln an und gebe die Stellung der OH-Gruppe an.",
        "C": "Ich unterscheide Stellungsisomere und begründe ihre verschiedenen Eigenschaften."
    },
    "lernkarten": {
        "A": karte("Eine Reihe wie bei den Alkanen",
                   "Auch die Alkohole bilden eine homologe Reihe.",
                   ["Die Namen enden auf -ol.", "Methanol, Ethanol, Propanol …"],
                   "Alkanname plus -ol.",
                   visual=anim("homologereihe", "A", gruppe="alkanol"),
                   beispiel={"titel": "Von Alkan zu Alkanol",
                             "aufgabe": "Aus Propan wird ein Alkohol.",
                             "schritte": ["Ein H-Atom wird durch OH ersetzt.",
                                          "Der Name endet jetzt auf -ol."],
                             "ergebnis": "Propan → Propanol"}),
        "B": karte("Namen und Formeln",
                   "Die Nomenklatur der Alkanole folgt derselben Logik wie bei den Alkanen — mit einer Ergänzung für die Stellung der OH-Gruppe.",
                   ["Allgemeine Formel: CₙH₂ₙ₊₁OH.",
                    "Der Name entsteht aus dem Alkannamen und der Endung -ol: Methanol, Ethanol, Propanol, Butanol.",
                    "Ab drei C-Atomen kann die OH-Gruppe an verschiedenen Stellen sitzen. Dann wird die Position genannt: Propan-1-ol und Propan-2-ol.",
                    "Nummeriert wird so, dass die OH-Gruppe die kleinstmögliche Zahl bekommt.",
                    "Molare Massen: Methanol 32, Ethanol 46, Propanol 60 g/mol — je Glied kommen 14 g/mol dazu."],
                   "CₙH₂ₙ₊₁OH, Endung -ol, Position mit kleinster Zahl.",
                   visual=anim("homologereihe", "B", gruppe="alkanol")),
        "C": karte("Stellungsisomere",
                   "Bei den Alkanolen kommt zur Kettenisomerie eine zweite Art hinzu: Dieselbe Kette, aber die OH-Gruppe an anderer Stelle.",
                   ["Propan-1-ol und Propan-2-ol haben beide C₃H₈O — die Kette ist gleich, nur die Position der OH-Gruppe unterscheidet sie.",
                    "Die Eigenschaften unterscheiden sich messbar: Propan-1-ol siedet bei 97 °C, Propan-2-ol bei 82 °C.",
                    "Der Grund ist derselbe wie bei den Alkanen: Die endständige OH-Gruppe ist besser zugänglich und bildet wirksamere Wasserstoffbrücken.",
                    "Wichtiger noch: Die Stellung entscheidet über das Verhalten bei der Oxidation — primär, sekundär oder tertiär."],
                   "Gleiche Formel, andere Position der OH-Gruppe — andere Eigenschaften und anderes Reaktionsverhalten.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "oh", "position": 2,
                           "name": "Propan-2-ol",
                           "alt": "Strukturformel von Propan-2-ol mit OH-Gruppe am mittleren C-Atom."})
    },
    "formelkarte": {"formeln": ["Alkanole: CₙH₂ₙ₊₁OH",
                               "CH₃OH 32 · C₂H₅OH 46 · C₃H₇OH 60 · C₄H₉OH 74 g/mol"],
                    "saetze": ["Der Name entsteht aus dem Alkannamen plus -ol.",
                               "Ab drei C-Atomen wird die Position der OH-Gruppe genannt.",
                               "So nummerieren, dass die OH-Gruppe die kleinste Zahl bekommt.",
                               "Je Glied der Reihe kommen 14 g/mol dazu."]},
    "tasks": [
        aufgabe("AL02-A1-001", "A", 1, "choice",
                "Wie heißt der Alkohol mit drei C-Atomen?",
                options=["Propanol", "Ethanol", "Butanol"], answer=0,
                hints=["Prop steht für 3.", "Dazu die Endung -ol.", "Propanol."],
                solution="Drei C-Atome ergeben Propanol, C₃H₇OH.",
                misconceptions=[fv("nomenklatur_falsch", 2,
                                   "Butanol hat vier C-Atome.",
                                   "nomenklatur_falsch")],
                tags=["alkanole"], spiral=["K-ORG"]),
        aufgabe("AL02-A2-002", "A", 2, "choice",
                "Auf welche Endung enden die Namen der Alkohole?",
                options=["-ol", "-an", "-säure"], answer=0,
                hints=["Methanol, Ethanol, Propanol.", "Alle enden gleich.", "-ol."],
                solution="Alkohole enden auf -ol. Die Alkane enden auf -an.",
                tags=["alkanole"], spiral=["K-ORG"]),
        aufgabe("AL02-A3-003", "A", 3, "numeric",
                "Wie viele C-Atome hat Butanol?",
                answer=4, tolerance=0,
                hints=["But steht für eine Zahl.", "But = 4.", "4."],
                solution="Butanol hat vier Kohlenstoffatome: C₄H₉OH.",
                tags=["alkanole"], spiral=["K-ORG"]),
        aufgabe("AL02-A4-004", "A", 4, "choice",
                "Welche Formel gehört zu Methanol?",
                options=["CH₃OH", "C₂H₅OH", "CH₄"], answer=0,
                hints=["Ein C-Atom.", "Dazu drei H und die OH-Gruppe.", "CH₃OH."],
                solution="Methanol hat ein C-Atom: CH₃OH.",
                tags=["alkanole"], spiral=["K-BIND"]),
        aufgabe("AL02-B1-005", "B", 1, "numeric",
                "Wie groß ist die molare Masse von Propanol C₃H₇OH? (C = 12, H = 1, O = 16 g/mol)",
                answer=60, unit_label="g/mol", tolerance=0.5,
                hints=["3 C, 8 H, 1 O.",
                       "36 + 8 + 16.",
                       "60 g/mol."],
                solution="M = 3 · 12 + 8 · 1 + 16 = 60 g/mol. Die acht H-Atome verteilen sich auf C₃H₇ und OH.",
                misconceptions=[fv("summenformel_falsch_gelesen", 59,
                                   "Zähle alle H-Atome: sieben im Rest und eines in der OH-Gruppe.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkanole", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("AL02-B2-006", "B", 2, "choice",
                "Warum heißt es Propan-2-ol und nicht einfach Propanol?",
                options=["Die OH-Gruppe kann an zwei verschiedenen Stellen sitzen; die Zahl macht es eindeutig.",
                         "Weil es zwei OH-Gruppen hat.",
                         "Weil es zwei C-Atome hat."],
                answer=0,
                visual={"type": "struktur", "kette": 3, "gruppe": "oh", "position": 2,
                        "alt": "Strukturformel von Propan-2-ol."},
                hints=["Wo kann die OH-Gruppe bei drei C-Atomen sitzen?",
                       "Am Ende oder in der Mitte.",
                       "Deshalb die Zahl."],
                solution="Bei drei C-Atomen kann die OH-Gruppe am ersten oder am mittleren Atom sitzen. Die Zahl macht den Namen eindeutig — es sind zwei verschiedene Stoffe.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Die 2 nennt die Position der OH-Gruppe, nicht ihre Anzahl.",
                                   "nomenklatur_falsch")],
                tags=["alkanole", "namen", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL02-B2-007", "B", 2, "numeric",
                "Wie viele H-Atome hat ein Alkanol mit 4 C-Atomen? (CₙH₂ₙ₊₁OH)",
                answer=10, tolerance=0,
                hints=["2 · 4 + 1 = 9 im Rest.",
                       "Dazu eines in der OH-Gruppe.",
                       "10."],
                solution="C₄H₉OH: neun H-Atome im Rest plus eines in der OH-Gruppe, zusammen 10. Summenformel C₄H₁₀O.",
                misconceptions=[fv("summenformel_falsch_gelesen", 9,
                                   "Das H der OH-Gruppe zählt mit.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkanole", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL02-B3-008", "B", 3, "multi",
                "Berechne die molaren Massen. (C = 12, H = 1, O = 16 g/mol)",
                fields=[
                    {"label": "M(Methanol CH₃OH)", "answer": 32, "unit_label": "g/mol", "tolerance": 0.5},
                    {"label": "M(Ethanol C₂H₅OH)", "answer": 46, "unit_label": "g/mol", "tolerance": 0.5},
                    {"label": "M(Butanol C₄H₉OH)", "answer": 74, "unit_label": "g/mol", "tolerance": 0.5}
                ],
                hints=["Alle Atome einzeln zählen.",
                       "Von Glied zu Glied kommen 14 g/mol dazu.",
                       "32, 46, 60, 74."],
                solution="CH₃OH = 12 + 4 + 16 = 32\nC₂H₅OH = 24 + 6 + 16 = 46\nC₄H₉OH = 48 + 10 + 16 = 74 g/mol",
                tags=["alkanole", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("AL02-B3-009", "B", 3, "choice",
                "Propan-1-ol siedet bei 97 °C, Propan-2-ol bei 82 °C. Was folgt daraus?",
                options=["Stellungsisomere sind verschiedene Stoffe mit verschiedenen Eigenschaften.",
                         "Eine der Messungen ist falsch.",
                         "Beide sind derselbe Stoff."],
                answer=0,
                hints=["Beide haben C₃H₈O.",
                       "Trotzdem sieden sie verschieden.",
                       "Also sind es verschiedene Stoffe."],
                solution="Beide haben dieselbe Summenformel, unterscheiden sich aber in der Position der OH-Gruppe — und damit messbar in den Eigenschaften. Sie sind Stellungsisomere.",
                misconceptions=[fv("isomer_als_gleicher_stoff", 2,
                                   "Gleiche Summenformel heißt nicht gleicher Stoff.",
                                   "isomer_als_gleicher_stoff")],
                tags=["alkanole", "msa"], spiral=["K-ORG"]),
        aufgabe("AL02-B4-010", "B", 4, "numeric",
                "Um wie viel g/mol unterscheiden sich zwei benachbarte Glieder der Alkanolreihe?",
                answer=14, tolerance=0.5,
                hints=["Eine CH₂-Gruppe kommt dazu.",
                       "12 + 2 · 1.",
                       "14 g/mol."],
                solution="Eine CH₂-Gruppe wiegt 12 + 2 = 14 g/mol. Deshalb: 32, 46, 60, 74 …",
                tags=["alkanole", "rechnen", "bbr"], spiral=["K-QUANT", "K-ORG"]),
        aufgabe("AL02-C2-011", "C", 2, "choice",
                "Warum siedet Propan-1-ol höher als Propan-2-ol?",
                options=["Die endständige OH-Gruppe ist besser zugänglich und bildet wirksamere Wasserstoffbrücken.",
                         "Propan-1-ol ist schwerer.",
                         "Propan-2-ol hat keine OH-Gruppe."],
                answer=0,
                hints=["Beide haben dieselbe Masse.",
                       "Verschieden ist die Zugänglichkeit der OH-Gruppe.",
                       "Am Kettenende ist sie freier."],
                solution="Bei gleicher Masse entscheidet, wie gut die OH-Gruppen einander erreichen. Am Kettenende ist sie weniger von Nachbargruppen abgeschirmt — die Wasserstoffbrücken sind wirksamer, der Siedepunkt liegt höher.",
                tags=["alkanole", "msa"], spiral=["K-ORG"]),
        aufgabe("AL02-C3-012", "C", 3, "numeric",
                "Wie viele Stellungsisomere gibt es beim Butanol (unverzweigte Kette)?",
                answer=2, tolerance=0,
                hints=["Die OH-Gruppe kann an Position 1 oder 2 sitzen.",
                       "Position 3 wäre dasselbe wie 2, Position 4 dasselbe wie 1.",
                       "2."],
                solution="Bei unverzweigtem Butan gibt es Butan-1-ol und Butan-2-ol. Die Positionen 3 und 4 ergeben durch Umnummerierung dieselben Stoffe.",
                tags=["alkanole", "msa"], spiral=["K-ORG"]),
        aufgabe("AL02-C3-013", "C", 3, "choice",
                "Warum wird bei der Nummerierung die kleinstmögliche Zahl gewählt?",
                options=["Sonst hätte derselbe Stoff je nach Zählrichtung zwei verschiedene Namen.",
                         "Damit der Name kürzer wird.",
                         "Das ist willkürlich festgelegt."],
                answer=0,
                hints=["Von welcher Seite lässt sich zählen?",
                       "Von beiden.",
                       "Ohne Regel wären beide Namen zulässig."],
                solution="Butan-2-ol ließe sich von der anderen Seite als Butan-3-ol lesen. Damit jeder Stoff genau einen Namen hat, wird die kleinstmögliche Zahl festgelegt.",
                tags=["alkanole", "namen", "msa"]),
        aufgabe("AL02-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt für Ethanol die Summenformel C₂H₅O. Was fehlt?",
                options=["Das Wasserstoffatom der OH-Gruppe — richtig ist C₂H₆O.",
                         "Nichts, die Formel ist richtig.",
                         "Ein Kohlenstoffatom."],
                answer=0,
                hints=["Zähle alle H-Atome.",
                       "Fünf im Rest, eines in der OH-Gruppe.",
                       "Zusammen sechs."],
                solution="C₂H₅OH enthält sechs Wasserstoffatome: fünf im Rest und eines in der Hydroxylgruppe. Als Summenformel geschrieben also C₂H₆O.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "Das H der OH-Gruppe gehört zur Summenformel.",
                                   "summenformel_falsch_gelesen")],
                tags=["alkanole", "bewerten", "msa"], spiral=["K-BIND"])
    ]
})

if __name__ == "__main__":
    schreiben("al", E, "Bereich AL · Einheiten 1 und 2")
