# -*- coding: utf-8 -*-
"""Bereich QB · Quantitative Betrachtungen — QB-02 bis QB-04."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "QB-02",
    "title": "Die Stoffmenge n und das Mol",
    "leitidee": "B1",
    "standards": ["K1", "K2.4", "K3.4"],
    "klasse": 9,
    "wortspeicher": ["die Stoffmenge", "das Mol", "die Avogadro-Konstante", "die Teilchenzahl",
                     "die molare Masse"],
    "worterklaerungen": {
        "Stoffmenge": "Eine Größe, die die Zahl der Teilchen angibt. Ihr Formelzeichen ist n.",
        "Mol": "Die Einheit der Stoffmenge. 1 mol sind 6,022 · 10²³ Teilchen.",
        "Avogadro-Konstante": "Die Zahl der Teilchen in einem Mol."
    },
    "can_do": {
        "A": "Ich weiß, dass ein Mol immer dieselbe Teilchenzahl bedeutet.",
        "B": "Ich rechne zwischen Stoffmenge, Teilchenzahl und Masse um.",
        "C": "Ich begründe, warum in der Chemie in Stoffmengen und nicht in Massen gerechnet wird."
    },
    "lernkarten": {
        "A": karte("Eine Zahl für sehr viele Teilchen",
                   "Atome sind winzig. Man kann sie nicht einzeln zählen.",
                   ["Deshalb zählt man in Portionen.", "Eine Portion heißt Mol."],
                   "1 mol ist immer dieselbe Anzahl Teilchen.",
                   visual=anim("mol", "A"),
                   beispiel={"titel": "Ein Vergleich", "aufgabe": "Wie beim Bäcker das Dutzend.",
                             "schritte": ["Ein Dutzend sind immer 12 Stück.",
                                          "Ein Mol sind immer 6,022 · 10²³ Teilchen.",
                                          "Die Masse ist trotzdem verschieden."],
                             "ergebnis": "Gleiche Anzahl, andere Masse."}),
        "B": karte("Zwischen Masse und Teilchenzahl",
                   "Das Mol ist die Brücke zwischen dem, was man wiegen kann, und dem, was in einer Reaktionsgleichung steht.",
                   ["1 mol enthält 6,022 · 10²³ Teilchen — die Avogadro-Konstante.",
                    "Die molare Masse M in g/mol ist zahlengleich zur Atom- oder Molekülmasse aus dem PSE.",
                    "Damit gilt: n = m : M und m = n · M.",
                    "Beispiel: 18 g Wasser sind 1 mol und enthalten 6,022 · 10²³ Wassermoleküle."],
                   "n = m : M. Die Zahlen der molaren Masse stehen im Periodensystem.",
                   visual=anim("mol", "B")),
        "C": karte("Warum in Mol gerechnet wird",
                   "Reaktionsgleichungen zählen Teilchen, keine Gramm. Genau deshalb ist die Stoffmenge die Größe, die zwischen Gleichung und Waage vermittelt.",
                   ["2 H₂ + O₂ → 2 H₂O bedeutet: zwei Wasserstoffmoleküle auf ein Sauerstoffmolekül — nicht zwei Gramm auf ein Gramm.",
                    "Die Koeffizienten einer Gleichung sind unmittelbar Stoffmengenverhältnisse. In Massen umgerechnet ergäben sie krumme Zahlen.",
                    "Deshalb der Weg jeder stöchiometrischen Rechnung: Masse → Stoffmenge → über die Gleichung zur gesuchten Stoffmenge → zurück zur Masse.",
                    "Das Mol ist so definiert, dass die relative Atommasse zahlengleich zur molaren Masse in g/mol ist. Genau das macht den Weg praktikabel."],
                   "Gleichungen zählen Teilchen. Deshalb wird über die Stoffmenge gerechnet.",
                   visual=anim("mol", "C"))
    },
    "formelkarte": {"formeln": ["n = m : M", "m = n · M", "M = m : n",
                               "N = n · 6,022 · 10²³"],
                    "saetze": ["1 mol enthält 6,022 · 10²³ Teilchen.",
                               "Die molare Masse in g/mol ist zahlengleich zur Atommasse im PSE.",
                               "Rechenweg: Masse → Stoffmenge → Gleichung → Stoffmenge → Masse."]},
    "tasks": [
        aufgabe("QB02-A1-001", "A", 1, "choice",
                "Was bedeutet 1 mol?",
                options=["Eine bestimmte Anzahl Teilchen", "Ein Gramm", "Ein Liter"], answer=0,
                visual=anim("mol", "A"),
                hints=["Es ist eine Zähleinheit.", "Wie ein Dutzend.", "Eine bestimmte Anzahl."],
                solution="1 mol bezeichnet immer dieselbe Anzahl Teilchen: 6,022 · 10²³.",
                misconceptions=[fv("groesse_und_einheit_verwechselt", 1,
                                   "Mol ist keine Masseneinheit. Es zählt Teilchen.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["mol"], spiral=["W-RECH"]),
        aufgabe("QB02-A2-002", "A", 2, "numeric",
                "Wie viel wiegt 1 mol Wasser? (M = 18 g/mol)",
                answer=18, unit_label="g", tolerance=0,
                hints=["m = n · M.", "1 · 18.", "18 g."],
                solution="m = 1 mol · 18 g/mol = 18 g",
                tags=["mol"], spiral=["W-RECH"]),
        aufgabe("QB02-A3-003", "A", 3, "numeric",
                "Wie viel wiegen 2 mol Kohlenstoffdioxid? (M = 44 g/mol)",
                answer=88, unit_label="g", tolerance=0,
                hints=["m = n · M.", "2 · 44.", "88 g."],
                solution="m = 2 mol · 44 g/mol = 88 g",
                misconceptions=[fv("mol_geteilt_statt_mal", 22,
                                   "Aus Stoffmenge und molarer Masse wird die Masse durch Multiplizieren.")],
                tags=["mol", "rechnen"], spiral=["W-RECH"]),
        aufgabe("QB02-A4-004", "A", 4, "choice",
                "1 mol Eisen und 1 mol Schwefel — was ist gleich?",
                options=["die Teilchenzahl", "die Masse", "das Volumen"], answer=0,
                visual=anim("mol", "A"),
                hints=["Ein Mol ist immer dieselbe Anzahl.", "Die Atome sind aber verschieden schwer.", "Gleich ist die Anzahl."],
                solution="Ein Mol bedeutet immer dieselbe Teilchenzahl. Weil Eisen- und Schwefelatome verschieden schwer sind, sind die Massen verschieden: 56 g gegen 32 g.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "1 mol Eisen wiegt 56 g, 1 mol Schwefel 32 g. Gleich ist nur die Anzahl.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["mol"], spiral=["W-RECH"]),
        aufgabe("QB02-B1-005", "B", 1, "numeric",
                "Wie viel mol sind 36 g Wasser? (M = 18 g/mol)",
                answer=2, unit_label="mol", tolerance=0.01,
                hints=["n = m : M.", "36 : 18.", "2 mol."],
                solution="n = 36 g : 18 g/mol = 2 mol",
                misconceptions=[fv("mol_mal_statt_geteilt", 648,
                                   "Aus Masse und molarer Masse wird die Stoffmenge durch Teilen: n = m : M.")],
                tags=["mol", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB02-B2-006", "B", 2, "numeric",
                "Wie viel mol sind 8,8 g Kohlenstoffdioxid? (M = 44 g/mol)",
                answer=0.2, unit_label="mol", tolerance=0.01,
                hints=["n = m : M.", "8,8 : 44.", "0,2 mol."],
                solution="n = 8,8 g : 44 g/mol = 0,2 mol",
                tags=["mol", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB02-B2-007", "B", 2, "numeric",
                "Wie viele Teilchen (in Vielfachen von 10²³) enthalten 0,5 mol?",
                answer=3.011, tolerance=0.02,
                hints=["1 mol enthält 6,022 · 10²³.", "Die Hälfte davon.", "3,011 · 10²³."],
                solution="0,5 · 6,022 · 10²³ = 3,011 · 10²³ Teilchen",
                tags=["mol", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB02-B3-008", "B", 3, "multi",
                "Gegeben sind 5,6 g Eisen (M = 56 g/mol).",
                fields=[
                    {"label": "Stoffmenge", "answer": 0.1, "unit_label": "mol", "tolerance": 0.005},
                    {"label": "Teilchenzahl in Vielfachen von 10²³", "answer": 0.602, "tolerance": 0.01}
                ],
                hints=["n = 5,6 : 56.",
                       "0,1 mol.",
                       "0,1 · 6,022 = 0,602."],
                solution="n = 5,6 g : 56 g/mol = 0,1 mol\nN = 0,1 · 6,022 · 10²³ = 6,022 · 10²² Teilchen",
                tags=["mol", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB02-B3-009", "B", 3, "numeric",
                "0,25 mol eines Stoffes wiegen 14 g. Wie groß ist die molare Masse?",
                answer=56, unit_label="g/mol", tolerance=0.5,
                hints=["M = m : n.", "14 : 0,25.", "56 g/mol — das ist Eisen."],
                solution="M = 14 g : 0,25 mol = 56 g/mol",
                misconceptions=[fv("groesse_und_einheit_verwechselt", 0.018,
                                   "Achte auf die Einheit: g/mol heißt Gramm <b>durch</b> Mol.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["mol", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB02-B4-010", "B", 4, "choice",
                "Warum ist die molare Masse zahlengleich zur Atommasse aus dem Periodensystem?",
                options=["Das Mol wurde genau so definiert.", "Das ist Zufall.", "Weil Gramm und atomare Masseneinheit dasselbe sind."],
                answer=0,
                hints=["Wurde das so festgelegt oder ergibt es sich?",
                       "Es wurde festgelegt.",
                       "Genau deshalb ist die Umrechnung so einfach."],
                solution="Die Stoffmenge Mol ist genau so definiert, dass die relative Atommasse zahlengleich zur molaren Masse in g/mol ist. Das erlaubt es, direkt aus dem Periodensystem in eine Wägung zu übersetzen.",
                tags=["mol", "msa"], spiral=["W-RECH"]),
        aufgabe("QB02-C2-011", "C", 2, "choice",
                "Warum steht in Reaktionsgleichungen die Stoffmenge und nicht die Masse im Vordergrund?",
                options=["Die Koeffizienten zählen Teilchen; in Massen ergäben sich krumme Verhältnisse.",
                         "Massen lassen sich nicht messen.",
                         "Stoffmengen sind einfacher zu schreiben."],
                answer=0,
                hints=["Was sagt der Koeffizient 2 in 2 H₂ aus?",
                       "Zwei Moleküle.",
                       "Nicht zwei Gramm."],
                solution="2 H₂ + O₂ → 2 H₂O bedeutet zwei Moleküle auf eines, nicht zwei Gramm auf ein Gramm. Die Koeffizienten sind Stoffmengenverhältnisse — deshalb führt jeder Rechenweg über n.",
                tags=["mol", "msa"], spiral=["W-GLEI", "W-RECH"]),
        aufgabe("QB02-C3-012", "C", 3, "multi",
                "Verglichen werden 1 mol Kohlenstoff (M = 12 g/mol) und 1 mol Blei (M = 207 g/mol).",
                fields=[
                    {"label": "Masse des Kohlenstoffs", "answer": 12, "unit_label": "g", "tolerance": 0.5},
                    {"label": "Masse des Bleis", "answer": 207, "unit_label": "g", "tolerance": 1},
                    {"label": "Verhältnis der Teilchenzahlen (Blei zu Kohlenstoff)", "answer": 1, "tolerance": 0.01}
                ],
                hints=["m = n · M für beide.",
                       "Gleiche Stoffmenge heißt gleiche Teilchenzahl.",
                       "Das Verhältnis ist 1 : 1."],
                solution="C: 12 g · Pb: 207 g\nBeide enthalten 6,022 · 10²³ Atome — das Verhältnis ist 1 : 1. Verschieden ist nur die Masse je Atom.",
                tags=["mol", "msa"], spiral=["W-RECH"]),
        aufgabe("QB02-C3-013", "C", 3, "numeric",
                "Ein Wassertropfen wiegt 0,05 g. Wie viele Wassermoleküle enthält er (in Vielfachen von 10²¹)? (M = 18 g/mol)",
                answer=1.673, tolerance=0.05,
                hints=["Erst n = 0,05 : 18.",
                       "n ≈ 0,002778 mol.",
                       "n · 6,022 · 10²³ = 1,673 · 10²¹."],
                solution="n = 0,05 g : 18 g/mol = 0,002778 mol\nN = 0,002778 · 6,022 · 10²³ ≈ 1,673 · 10²¹ Moleküle\nIn einem einzigen Tropfen — das zeigt, warum einzelnes Zählen ausscheidet.",
                tags=["mol", "rechnen", "msa"], spiral=["W-RECH"]),
        aufgabe("QB02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „1 mol ist eine Masse.“ Wie korrigierst du?",
                options=["Mol ist die Einheit der Stoffmenge und zählt Teilchen; die zugehörige Masse hängt vom Stoff ab.",
                         "Richtig, 1 mol sind immer 18 g.",
                         "Mol ist eine Volumeneinheit."],
                answer=0,
                hints=["Wiegt 1 mol Eisen genauso viel wie 1 mol Wasser?",
                       "Nein — 56 g gegen 18 g.",
                       "Gleich ist nur die Teilchenzahl."],
                solution="Mol ist die Einheit der Stoffmenge, nicht der Masse. 1 mol Wasser wiegt 18 g, 1 mol Eisen 56 g — die Teilchenzahl ist in beiden Fällen dieselbe.",
                misconceptions=[fv("groesse_und_einheit_verwechselt", 1,
                                   "18 g gelten für Wasser. Für andere Stoffe hat 1 mol eine andere Masse.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["mol", "bewerten", "msa"], spiral=["W-EINH"])
    ]
})

E.append({
    "unit": "QB-03",
    "title": "Rechnen mit n = m : M",
    "leitidee": "B1",
    "standards": ["K1", "K2.4"],
    "klasse": 9,
    "wortspeicher": ["die Stoffmenge", "die molare Masse", "die Masse", "das Umstellen",
                     "die Einheitenkontrolle"],
    "worterklaerungen": {
        "Einheitenkontrolle": "Die Prüfung, ob die Einheit des Ergebnisses zur gesuchten Größe passt."
    },
    "can_do": {
        "A": "Ich berechne die Stoffmenge aus Masse und molarer Masse.",
        "B": "Ich stelle die Formel nach jeder der drei Größen um.",
        "C": "Ich löse mehrschrittige Aufgaben und prüfe das Ergebnis über die Einheiten."
    },
    "lernkarten": {
        "A": karte("Eine Formel, drei Größen",
                   "n = m : M verbindet drei Größen.",
                   ["m ist die Masse in Gramm.", "M ist die molare Masse in g/mol.", "n ist die Stoffmenge in mol."],
                   "Zwei Größen bekannt → die dritte lässt sich ausrechnen.",
                   visual=anim("mol", "A"),
                   beispiel={"titel": "Ein Beispiel", "aufgabe": "44 g CO₂, M = 44 g/mol.",
                             "schritte": ["n = m : M", "n = 44 : 44", "n = 1 mol"],
                             "ergebnis": "1 mol",
                             "luecke": {"schritt": 2, "wert": 1, "einheit": "mol"}}),
        "B": karte("Die Formel umstellen",
                   "Aus einer Formel werden drei, wenn man sie umstellen kann. Welche gesucht ist, verrät die Einheit in der Frage.",
                   ["Gesucht n (in mol): n = m : M",
                    "Gesucht m (in g): m = n · M",
                    "Gesucht M (in g/mol): M = m : n",
                    "Kontrolle über die Einheiten: g geteilt durch g/mol ergibt mol. Passt die Einheit nicht, ist die Formel falsch umgestellt."],
                   "Die Einheit der Frage sagt, welche Größe gesucht ist.",
                   visual=anim("mol", "B")),
        "C": karte("Mehrschrittig rechnen",
                   "Sobald zwei Stoffe beteiligt sind, führt der Weg immer über dieselben vier Schritte.",
                   ["1. Gegebene Masse in Stoffmenge umrechnen: n = m : M.",
                    "2. Über die Koeffizienten der Reaktionsgleichung zur Stoffmenge des gesuchten Stoffes.",
                    "3. Zurück zur Masse: m = n · M.",
                    "4. Ergebnis prüfen: Passt die Einheit? Ist die Größenordnung plausibel?",
                    "Der häufigste Fehler ist, Schritt 2 zu überspringen und Massen direkt zu übertragen — die Koeffizienten gelten aber für Teilchen, nicht für Gramm."],
                   "Masse → Stoffmenge → Gleichung → Stoffmenge → Masse.",
                   visual=anim("mol", "C"))
    },
    "formelkarte": {"formeln": ["n = m : M", "m = n · M", "M = m : n"],
                    "saetze": ["Einheiten: m in g, M in g/mol, n in mol.",
                               "g : (g/mol) = mol — die Einheitenkontrolle deckt Umstellfehler auf.",
                               "Bei zwei Stoffen immer über die Stoffmenge rechnen.",
                               "Massen dürfen nie direkt über die Gleichung übertragen werden."]},
    "tasks": [
        aufgabe("QB03-A1-001", "A", 1, "numeric",
                "Wie viel mol sind 32 g Sauerstoff O₂? (M = 32 g/mol)",
                answer=1, unit_label="mol", tolerance=0.01,
                hints=["n = m : M.", "32 : 32.", "1 mol."],
                solution="n = 32 g : 32 g/mol = 1 mol",
                tags=["stoffmenge"], spiral=["W-RECH"]),
        aufgabe("QB03-A2-002", "A", 2, "numeric",
                "Wie viel mol sind 54 g Wasser? (M = 18 g/mol)",
                answer=3, unit_label="mol", tolerance=0.01,
                hints=["n = m : M.", "54 : 18.", "3 mol."],
                solution="n = 54 g : 18 g/mol = 3 mol",
                misconceptions=[fv("mol_mal_statt_geteilt", 972,
                                   "n = m : M — hier wird geteilt.")],
                tags=["stoffmenge"], spiral=["W-RECH"]),
        aufgabe("QB03-A3-003", "A", 3, "numeric",
                "Welche Masse haben 0,5 mol Kohlenstoffdioxid? (M = 44 g/mol)",
                answer=22, unit_label="g", tolerance=0.1,
                hints=["m = n · M.", "0,5 · 44.", "22 g."],
                solution="m = 0,5 mol · 44 g/mol = 22 g",
                tags=["stoffmenge"], spiral=["W-RECH"]),
        aufgabe("QB03-A4-004", "A", 4, "numeric",
                "Wie viel mol sind 100 g Calciumcarbonat? (M = 100 g/mol)",
                answer=1, unit_label="mol", tolerance=0.01,
                hints=["n = m : M.", "100 : 100.", "1 mol."],
                solution="n = 100 g : 100 g/mol = 1 mol",
                tags=["stoffmenge"], spiral=["W-RECH"]),
        aufgabe("QB03-B1-005", "B", 1, "numeric",
                "0,4 mol eines Stoffes wiegen 22,4 g. Wie groß ist die molare Masse?",
                answer=56, unit_label="g/mol", tolerance=0.5,
                hints=["M = m : n.", "22,4 : 0,4.", "56 g/mol."],
                solution="M = 22,4 g : 0,4 mol = 56 g/mol",
                tags=["stoffmenge", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB03-B2-006", "B", 2, "numeric",
                "Welche Masse haben 2,5 mol Schwefelsäure? (M = 98 g/mol)",
                answer=245, unit_label="g", tolerance=1,
                hints=["m = n · M.", "2,5 · 98.", "245 g."],
                solution="m = 2,5 mol · 98 g/mol = 245 g",
                tags=["stoffmenge", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB03-B2-007", "B", 2, "numeric",
                "Wie viel mol sind 5,85 g Natriumchlorid? (M = 58,5 g/mol)",
                answer=0.1, unit_label="mol", tolerance=0.005,
                hints=["n = m : M.", "5,85 : 58,5.", "0,1 mol."],
                solution="n = 5,85 g : 58,5 g/mol = 0,1 mol",
                tags=["stoffmenge", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB03-B3-008", "B", 3, "multi",
                "Gegeben sind 25 g Calciumcarbonat CaCO₃ (M = 100 g/mol).",
                fields=[
                    {"label": "Stoffmenge", "answer": 0.25, "unit_label": "mol", "tolerance": 0.01},
                    {"label": "Masse von 0,25 mol Calciumoxid CaO (M = 56 g/mol)", "answer": 14, "unit_label": "g", "tolerance": 0.2}
                ],
                hints=["n = 25 : 100 = 0,25 mol.",
                       "Aus CaCO₃ entsteht CaO im Verhältnis 1 : 1.",
                       "m = 0,25 · 56."],
                solution="n(CaCO₃) = 25 g : 100 g/mol = 0,25 mol\nn(CaO) = 0,25 mol\nm(CaO) = 0,25 · 56 = 14 g",
                tags=["stoffmenge", "bbr"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("QB03-B3-009", "B", 3, "choice",
                "Woran erkennst du, ob du n = m : M oder m = n · M brauchst?",
                options=["An der Einheit der gesuchten Größe.",
                         "An der Größe der Zahlen.", "Das ist gleichgültig."],
                answer=0,
                hints=["Was ist gefragt — mol oder Gramm?",
                       "Gefragt in mol heißt teilen.",
                       "Gefragt in Gramm heißt multiplizieren."],
                solution="Ist eine Stoffmenge in mol gesucht, wird geteilt. Ist eine Masse in Gramm gesucht, wird multipliziert. Die Einheit der Frage entscheidet — nicht die Größe der Zahlen.",
                tags=["stoffmenge", "bbr"], spiral=["W-EINH"]),
        aufgabe("QB03-B4-010", "B", 4, "numeric",
                "Wie viel Gramm wiegen 0,05 mol Kupfersulfat? (M = 160 g/mol)",
                answer=8, unit_label="g", tolerance=0.1,
                hints=["m = n · M.", "0,05 · 160.", "8 g."],
                solution="m = 0,05 mol · 160 g/mol = 8 g",
                misconceptions=[fv("mol_geteilt_statt_mal", 3200,
                                   "Aus Stoffmenge und molarer Masse wird die Masse durch Multiplizieren.")],
                tags=["stoffmenge", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB03-C2-011", "C", 2, "multi",
                "12 g Kohlenstoff (M = 12 g/mol) verbrennen vollständig zu CO₂ (M = 44 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Kohlenstoffs", "answer": 1, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "Stoffmenge des entstehenden CO₂", "answer": 1, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "Masse des entstehenden CO₂", "answer": 44, "unit_label": "g", "tolerance": 0.5}
                ],
                hints=["n(C) = 12 : 12 = 1 mol.",
                       "C + O₂ → CO₂ läuft 1 : 1.",
                       "m = 1 · 44."],
                solution="n(C) = 1 mol\nn(CO₂) = 1 mol (Verhältnis 1 : 1)\nm(CO₂) = 44 g\nAus 12 g Kohlenstoff werden 44 g CO₂ — die Differenz ist der gebundene Sauerstoff.",
                tags=["stoffmenge", "msa"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("QB03-C3-012", "C", 3, "numeric",
                "Wie viel Gramm Magnesium (M = 24 g/mol) werden gebraucht, um 0,75 mol Magnesiumoxid zu erhalten?",
                answer=18, unit_label="g", tolerance=0.3,
                hints=["2 Mg + O₂ → 2 MgO läuft für Mg und MgO 1 : 1.",
                       "n(Mg) = 0,75 mol.",
                       "m = 0,75 · 24."],
                solution="n(Mg) = n(MgO) = 0,75 mol\nm = 0,75 mol · 24 g/mol = 18 g",
                misconceptions=[fv("masse_direkt_uebertragen", 0.75,
                                   "0,75 ist die Stoffmenge, nicht die Masse. Rechne mit m = n · M weiter.")],
                tags=["stoffmenge", "msa"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("QB03-C3-013", "C", 3, "multi",
                "8 g Methan CH₄ (M = 16 g/mol) verbrennen: CH₄ + 2 O₂ → CO₂ + 2 H₂O.",
                fields=[
                    {"label": "Stoffmenge des Methans", "answer": 0.5, "unit_label": "mol", "tolerance": 0.02},
                    {"label": "benötigte Stoffmenge Sauerstoff", "answer": 1, "unit_label": "mol", "tolerance": 0.03},
                    {"label": "Masse des entstehenden Wassers (M = 18 g/mol)", "answer": 18, "unit_label": "g", "tolerance": 0.5}
                ],
                hints=["n(CH₄) = 8 : 16 = 0,5 mol.",
                       "Auf 1 CH₄ kommen 2 O₂, also 1 mol.",
                       "Auf 1 CH₄ kommen 2 H₂O, also 1 mol → 18 g."],
                solution="n(CH₄) = 0,5 mol\nn(O₂) = 2 · 0,5 = 1 mol\nn(H₂O) = 2 · 0,5 = 1 mol → m = 18 g",
                tags=["stoffmenge", "msa"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("QB03-C4-014", "C", 4, "choice",
                "Ein Schüler rechnet: „Aus 12 g Kohlenstoff entstehen 12 g CO₂, weil das Verhältnis 1 : 1 ist.“ Wo liegt der Fehler?",
                options=["Das Verhältnis 1 : 1 gilt für Stoffmengen, nicht für Massen — es kommt Sauerstoff hinzu.",
                         "Nichts, die Rechnung stimmt.",
                         "Das Verhältnis ist 2 : 1."],
                answer=0,
                hints=["Was sagt der Koeffizient aus?",
                       "Ein Teilchen auf ein Teilchen.",
                       "Ein CO₂-Molekül ist aber schwerer als ein C-Atom."],
                solution="Die Koeffizienten sind Stoffmengenverhältnisse. 1 mol C ergibt 1 mol CO₂ — aber 12 g ergeben 44 g, weil der Sauerstoff hinzukommt. Massen dürfen nie direkt über die Gleichung übertragen werden.",
                misconceptions=[fv("masse_direkt_uebertragen", 1,
                                   "Die Massen sind nicht gleich — nur die Stoffmengen. Rechne über n.")],
                tags=["stoffmenge", "bewerten", "msa"], spiral=["W-RECH", "W-GLEI"])
    ]
})

if __name__ == "__main__":
    schreiben("qb", E, "Bereich QB · Einheiten 2 und 3")
