# -*- coding: utf-8 -*-
"""Bereich OS · Organische Säuren — OS-02 bis OS-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "OS-02",
    "title": "Homologe Reihe und Nomenklatur der Alkansäuren",
    "leitidee": "B1",
    "standards": ["K1", "K3.4"],
    "klasse": 10,
    "wortspeicher": ["die Alkansäure", "die homologe Reihe", "der Trivialname",
                     "die Methansäure", "die Ethansäure", "die Endung -säure"],
    "worterklaerungen": {
        "Alkansäure": "Der Fachname für eine organische Säure mit einer Carboxygruppe.",
        "Trivialname": "Ein historisch gewachsener Name, etwa Ameisensäure für Methansäure."
    },
    "can_do": {
        "A": "Ich nenne die ersten Alkansäuren und ihre Trivialnamen.",
        "B": "Ich stelle Formeln der Alkansäuren auf und wende die Nomenklatur an.",
        "C": "Ich begründe die Regelmäßigkeit der Reihe und ordne Fettsäuren ein."
    },
    "lernkarten": {
        "A": karte("Eine Reihe wie bei den Alkanen",
                   "Auch die Säuren bilden eine homologe Reihe.",
                   ["Die Namen enden auf -säure.", "Viele haben zusätzlich einen alten Namen."],
                   "Alkanname plus -säure.",
                   visual=anim("homologereihe", "A", gruppe="alkansaeure"),
                   beispiel={"titel": "Zwei Namen", "aufgabe": "Wie heißt HCOOH?",
                             "schritte": ["Ein C-Atom: Meth.",
                                          "Also Methansäure.",
                                          "Der alte Name ist Ameisensäure."],
                             "ergebnis": "Methansäure = Ameisensäure"}),
        "B": karte("Namen und Formeln",
                   "Die Nomenklatur folgt derselben Logik wie bei Alkanen und Alkanolen. Das C-Atom der Carboxygruppe zählt zur Kette mit.",
                   ["Allgemeine Formel: CₙH₂ₙ₊₁COOH — oder mit der Carboxygruppe eingerechnet CₙH₂ₙO₂.",
                    "Namen: Methansäure (1 C), Ethansäure (2 C), Propansäure (3 C), Butansäure (4 C).",
                    "Trivialnamen: Ameisensäure, Essigsäure, Propionsäure, Buttersäure.",
                    "Das C-Atom der COOH-Gruppe wird mitgezählt: Ethansäure hat insgesamt zwei C-Atome, davon eines in der Carboxygruppe.",
                    "Molare Massen: 46, 60, 74, 88 g/mol — je Glied kommen wie immer 14 g/mol dazu."],
                   "Das C-Atom der Carboxygruppe zählt zur Kette.",
                   visual=anim("homologereihe", "B", gruppe="alkansaeure")),
        "C": karte("Von der Essigsäure zur Fettsäure",
                   "Die Reihe hört nicht bei kurzen Säuren auf — mit wachsender Kettenlänge werden aus ihnen die Fettsäuren, und die Eigenschaften ändern sich entsprechend.",
                   ["Kurzkettige Säuren sind gut wasserlöslich und riechen stechend. Buttersäure ist für den Geruch ranziger Butter verantwortlich.",
                    "Ab etwa zehn C-Atomen spricht man von Fettsäuren. Sie sind fest, geruchsarm und kaum wasserlöslich.",
                    "Der Grund ist derselbe wie bei den Alkoholen: Die lange unpolare Kette überwiegt die polare Carboxygruppe.",
                    "Gesättigte Fettsäuren wie Palmitinsäure haben nur Einfachbindungen; ungesättigte wie Ölsäure enthalten Doppelbindungen und sind bei Zimmertemperatur flüssig.",
                    "Die Zahl der C-Atome in natürlichen Fettsäuren ist fast immer gerade — eine Folge ihres Aufbaus im Stoffwechsel aus C₂-Einheiten."],
                   "Kurze Säuren sind löslich und riechen, lange sind fest und geruchsarm.",
                   visual={"type": "diagramm", "titel": "Siedetemperaturen der Alkansäuren",
                           "xtitel": "Zahl der C-Atome", "ytitel": "Siedetemperatur in °C",
                           "punkte": [[1, 101], [2, 118], [3, 141], [4, 164], [5, 186]],
                           "ymin": 0, "ymax": 220,
                           "alt": "Die Siedetemperaturen der Alkansäuren steigen mit der Kettenlänge."})
    },
    "formelkarte": {"formeln": ["Alkansäuren: CₙH₂ₙ₊₁COOH",
                               "HCOOH 46 · CH₃COOH 60 · C₂H₅COOH 74 · C₃H₇COOH 88 g/mol"],
                    "saetze": ["Methansäure = Ameisensäure · Ethansäure = Essigsäure.",
                               "Propansäure = Propionsäure · Butansäure = Buttersäure.",
                               "Das C-Atom der Carboxygruppe zählt zur Kette.",
                               "Ab etwa zehn C-Atomen spricht man von Fettsäuren."]},
    "tasks": [
        aufgabe("OS02-A1-001", "A", 1, "choice",
                "Wie heißt die Säure mit einem C-Atom?",
                options=["Methansäure", "Ethansäure", "Propansäure"], answer=0,
                hints=["Meth steht für 1.", "Dazu -säure.", "Methansäure."],
                solution="Ein C-Atom ergibt Methansäure HCOOH — der Trivialname ist Ameisensäure.",
                tags=["carbonsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS02-A2-002", "A", 2, "choice",
                "Wie lautet der Trivialname der Ethansäure?",
                options=["Essigsäure", "Ameisensäure", "Buttersäure"], answer=0,
                hints=["Sie steckt im Speiseessig.", "Essigsäure.", "Ethansäure = Essigsäure."],
                solution="Ethansäure heißt umgangssprachlich Essigsäure.",
                misconceptions=[fv("nomenklatur_falsch", 1,
                                   "Ameisensäure ist die Methansäure mit einem C-Atom.",
                                   "nomenklatur_falsch")],
                tags=["carbonsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS02-A3-003", "A", 3, "numeric",
                "Wie viele C-Atome hat Propansäure insgesamt?",
                answer=3, tolerance=0,
                hints=["Prop steht für 3.", "Das C der COOH-Gruppe zählt mit.", "3."],
                solution="Propansäure hat drei C-Atome, eines davon in der Carboxygruppe: C₂H₅COOH.",
                misconceptions=[fv("summenformel_falsch_gelesen", 2,
                                   "Das C-Atom der Carboxygruppe zählt zur Kette.",
                                   "summenformel_falsch_gelesen")],
                tags=["carbonsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS02-A4-004", "A", 4, "choice",
                "Auf welche Endung enden die Namen der organischen Säuren?",
                options=["-säure", "-ol", "-an"], answer=0,
                hints=["Methansäure, Ethansäure …", "Alle enden gleich.", "-säure."],
                solution="Organische Säuren enden auf -säure. Alkohole enden auf -ol, Alkane auf -an.",
                tags=["carbonsaeuren"], spiral=["K-ORG"]),
        aufgabe("OS02-B1-005", "B", 1, "numeric",
                "Wie groß ist die molare Masse von Methansäure HCOOH? (C = 12, H = 1, O = 16 g/mol)",
                answer=46, unit_label="g/mol", tolerance=1,
                hints=["1 C, 2 H, 2 O.", "12 + 2 + 32.", "46 g/mol."],
                solution="M = 12 + 2 · 1 + 2 · 16 = 46 g/mol",
                tags=["carbonsaeuren", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("OS02-B2-006", "B", 2, "choice",
                "Welche Formel gehört zu Propansäure?",
                options=["C₂H₅COOH", "C₃H₇COOH", "CH₃COOH"], answer=0,
                hints=["Drei C-Atome insgesamt.",
                       "Eines steckt in der COOH-Gruppe.",
                       "Also C₂H₅ als Rest."],
                solution="Propansäure hat drei C-Atome. Eines gehört zur Carboxygruppe, zwei bilden den Rest: C₂H₅COOH.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "C₃H₇COOH hätte vier C-Atome — das wäre Butansäure.",
                                   "summenformel_falsch_gelesen")],
                tags=["carbonsaeuren", "bbr"], spiral=["K-BIND"]),
        aufgabe("OS02-B2-007", "B", 2, "assign",
                "Ordne jeder Säure ihren Trivialnamen zu.",
                slots=["Methansäure", "Ethansäure", "Butansäure"],
                values=["Ameisensäure", "Essigsäure", "Buttersäure"], answer=[0, 1, 2],
                hints=["Die Trivialnamen stammen aus der Herkunft.",
                       "Ameisen enthalten Methansäure.",
                       "Ranzige Butter riecht nach Butansäure."],
                solution="Methansäure = Ameisensäure, Ethansäure = Essigsäure, Butansäure = Buttersäure.",
                tags=["carbonsaeuren", "namen", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS02-B3-008", "B", 3, "numeric",
                "Um wie viel g/mol unterscheiden sich zwei benachbarte Alkansäuren?",
                answer=14, tolerance=0.5,
                hints=["Eine CH₂-Gruppe kommt dazu.", "12 + 2.", "14 g/mol."],
                solution="Wie in jeder homologen Reihe kommt eine CH₂-Gruppe dazu: 14 g/mol. Die Reihe lautet 46, 60, 74, 88 …",
                tags=["carbonsaeuren", "rechnen", "bbr"], spiral=["K-QUANT", "K-ORG"]),
        aufgabe("OS02-B3-009", "B", 3, "choice",
                "Warum riecht ranzige Butter unangenehm?",
                options=["Es entsteht Butansäure, die stechend riecht.",
                         "Es entsteht Essigsäure.",
                         "Es entsteht Alkohol."],
                answer=0,
                hints=["Der Name der Säure verrät es.",
                       "Buttersäure.",
                       "Sie entsteht beim Verderben."],
                solution="Beim Verderben von Butter wird Butansäure frei — der Trivialname Buttersäure kommt genau daher. Kurzkettige Säuren riechen stechend, längere kaum.",
                tags=["carbonsaeuren", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS02-B4-010", "B", 4, "choice",
                "Warum sind kurzkettige Säuren gut wasserlöslich, langkettige nicht?",
                options=["Bei langen Ketten überwiegt der unpolare Rest die polare Carboxygruppe.",
                         "Lange Säuren haben keine Carboxygruppe.",
                         "Lange Säuren sind schwerer."],
                answer=0,
                hints=["Wie bei den Alkoholen.",
                       "Zwei Bereiche im Molekül.",
                       "Das Verhältnis entscheidet."],
                solution="Wie bei den Alkoholen konkurrieren polare Gruppe und unpolare Kette. Bei Essigsäure überwiegt die Carboxygruppe, bei Fettsäuren die lange Kette — sie sind praktisch wasserunlöslich.",
                tags=["carbonsaeuren", "msa"], spiral=["K-SL"]),
        aufgabe("OS02-C2-011", "C", 2, "choice",
                "Warum enthalten natürliche Fettsäuren fast immer eine gerade Zahl von C-Atomen?",
                options=["Sie werden im Stoffwechsel aus C₂-Einheiten aufgebaut.",
                         "Ungerade Zahlen sind chemisch unmöglich.",
                         "Das ist reiner Zufall."],
                answer=0,
                hints=["Woraus baut der Körper Fettsäuren auf?",
                       "Aus Bausteinen mit zwei C-Atomen.",
                       "Daraus folgt eine gerade Gesamtzahl."],
                solution="Der Aufbau erfolgt schrittweise aus Bausteinen mit je zwei C-Atomen. Deshalb ist die Gesamtzahl fast immer gerade — Palmitinsäure hat 16, Stearinsäure 18 C-Atome.",
                tags=["carbonsaeuren", "msa"], spiral=["K-ORG"]),
        aufgabe("OS02-C3-012", "C", 3, "multi",
                "Berechne die molaren Massen. (C = 12, H = 1, O = 16 g/mol)",
                fields=[
                    {"label": "M(Ethansäure CH₃COOH)", "answer": 60, "unit_label": "g/mol", "tolerance": 1},
                    {"label": "M(Butansäure C₃H₇COOH)", "answer": 88, "unit_label": "g/mol", "tolerance": 1}
                ],
                hints=["Alle Atome zählen.",
                       "Ethansäure: 2 C, 4 H, 2 O.",
                       "Butansäure: 4 C, 8 H, 2 O."],
                solution="CH₃COOH = 24 + 4 + 32 = 60 g/mol\nC₃H₇COOH = 48 + 8 + 32 = 88 g/mol",
                tags=["carbonsaeuren", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("OS02-C3-013", "C", 3, "choice",
                "Was unterscheidet eine gesättigte von einer ungesättigten Fettsäure?",
                options=["Die ungesättigte enthält mindestens eine C=C-Doppelbindung.",
                         "Die ungesättigte hat mehr Carboxygruppen.",
                         "Die ungesättigte ist kürzer."],
                answer=0,
                hints=["Der Begriff ist derselbe wie bei den Alkanen.",
                       "Gesättigt heißt: nur Einfachbindungen.",
                       "Ungesättigt heißt: mindestens eine Doppelbindung."],
                solution="Wie bei den Kohlenwasserstoffen bezieht sich „gesättigt“ auf die Bindungen in der Kette. Ungesättigte Fettsäuren wie Ölsäure haben Doppelbindungen — sie sind deshalb bei Zimmertemperatur flüssig.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Die Zahl der Carboxygruppen bestimmt die Wertigkeit, nicht die Sättigung.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["carbonsaeuren", "msa"], spiral=["K-ORG"]),
        aufgabe("OS02-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt für Ethansäure die Formel C₂H₅COOH. Was ist falsch?",
                options=["Damit hätte die Säure drei C-Atome — richtig ist CH₃COOH.",
                         "Nichts, die Formel ist richtig.",
                         "Es fehlt ein Sauerstoffatom."],
                answer=0,
                hints=["Zähle die C-Atome in C₂H₅COOH.",
                       "Zwei im Rest plus eines in der COOH-Gruppe.",
                       "Das wären drei."],
                solution="C₂H₅COOH enthält drei C-Atome — das ist Propansäure. Ethansäure hat zwei: CH₃COOH. Das C-Atom der Carboxygruppe zählt immer mit.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "Zähle das C-Atom der Carboxygruppe mit.",
                                   "summenformel_falsch_gelesen")],
                tags=["carbonsaeuren", "bewerten", "msa"], spiral=["K-BIND"])
    ]
})

E.append({
    "unit": "OS-03",
    "title": "Struktur, Eigenschaften und Salze",
    "leitidee": "B2",
    "standards": ["K1", "K2.4", "K3.3"],
    "klasse": 10,
    "wortspeicher": ["das Carboxylat", "das Acetat", "die Neutralisation", "das Salz",
                     "die Wasserstoffbrücke", "die Löslichkeit"],
    "worterklaerungen": {
        "Carboxylat": "Das Anion einer Carbonsäure, entstanden durch Abgabe des Protons.",
        "Acetat": "Das Anion der Essigsäure, CH₃COO⁻."
    },
    "can_do": {
        "A": "Ich weiß, dass Carbonsäuren mit Laugen Salze bilden.",
        "B": "Ich benenne die Salze der Carbonsäuren und stelle Neutralisationsgleichungen auf.",
        "C": "Ich begründe Löslichkeit und Siedeverhalten der Säuren und ihrer Salze."
    },
    "lernkarten": {
        "A": karte("Säuren bilden Salze",
                   "Auch organische Säuren reagieren mit Laugen.",
                   ["Es entstehen Wasser und ein Salz.", "Das Salz heißt Acetat, Formiat oder ähnlich."],
                   "Säure + Lauge → Salz + Wasser.",
                   visual={"type": "struktur", "kette": 2, "gruppe": "cooh",
                           "alt": "Strukturformel von Essigsäure."},
                   beispiel={"titel": "Essigsäure und Natronlauge",
                             "aufgabe": "Was entsteht?",
                             "schritte": ["Wasser entsteht.",
                                          "Und Natriumacetat."],
                             "ergebnis": "CH₃COOH + NaOH → CH₃COONa + H₂O"}),
        "B": karte("Die Salze benennen",
                   "Die Salze der Carbonsäuren tragen eigene Namen, die sich aus dem Säurenamen ableiten.",
                   ["Aus Methansäure wird das Methanoat, Trivialname Formiat.",
                    "Aus Ethansäure wird das Ethanoat, Trivialname Acetat.",
                    "Aus Citronensäure wird das Citrat, aus Milchsäure das Lactat.",
                    "Die Bildung folgt dem bekannten Muster: Säure + Lauge → Salz + Wasser.",
                    "Diese Salze finden sich auf vielen Zutatenlisten: Natriumcitrat, Calciumlactat, Natriumbenzoat."],
                   "Aus -säure wird -at: Acetat, Citrat, Lactat.",
                   visual={"type": "phskala", "marken": [{"wert": 2.4, "stoff": "Essigsäure"},
                                                         {"wert": 8.9, "stoff": "Natriumacetat"}],
                           "alt": "pH-Skala: Essigsäure sauer, ihr Salz leicht alkalisch."}),
        "C": karte("Warum Salze anders sind als Säuren",
                   "Aus einer flüchtigen, stechend riechenden Flüssigkeit wird durch Neutralisation ein geruchloser Feststoff. Der Grund liegt im Wechsel der Bindungsart.",
                   ["Die Säure besteht aus Molekülen, die über Wasserstoffbrücken zusammenhalten. Sie ist flüchtig und riecht.",
                    "Das Salz besteht aus Ionen im Gitter. Es ist fest, geruchlos und hochschmelzend — dieselbe Logik wie bei den anorganischen Salzen.",
                    "Deshalb ist Natriumacetat geruchlos, obwohl Essigsäure stechend riecht.",
                    "Auch die Löslichkeit ändert sich: Langkettige Fettsäuren sind wasserunlöslich, ihre Natriumsalze dagegen löslich — genau das sind die Seifen.",
                    "Das Salz einer schwachen Säure reagiert in Lösung leicht alkalisch, weil sein Anion Protonen aufnimmt."],
                   "Aus Molekülen werden Ionen — daher fest, geruchlos, anders löslich.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "ionen",
                           "alt": "Ionengitter eines Carbonsäuresalzes."})
    },
    "formelkarte": {"formeln": ["CH₃COOH + NaOH → CH₃COONa + H₂O",
                               "R–COOH + H₂O ⇌ R–COO⁻ + H₃O⁺"],
                    "saetze": ["Aus -säure wird -at: Acetat, Citrat, Lactat, Formiat.",
                               "Säuren bestehen aus Molekülen, ihre Salze aus Ionen.",
                               "Salze sind fest, geruchlos und hochschmelzend.",
                               "Das Salz einer schwachen Säure reagiert leicht alkalisch."]},
    "tasks": [
        aufgabe("OS03-A1-001", "A", 1, "choice",
                "Was entsteht, wenn Essigsäure mit Natronlauge reagiert?",
                options=["ein Salz und Wasser", "ein Gas", "ein Alkohol"], answer=0,
                hints=["Es ist eine Neutralisation.", "Wie bei jeder Säure mit einer Lauge.", "Salz und Wasser."],
                solution="CH₃COOH + NaOH → CH₃COONa + H₂O. Es entstehen Natriumacetat und Wasser.",
                tags=["salze"], spiral=["K-REAK"]),
        aufgabe("OS03-A2-002", "A", 2, "choice",
                "Wie heißt das Salz der Essigsäure?",
                options=["Acetat", "Citrat", "Formiat"], answer=0,
                hints=["Der Trivialname der Essigsäure ist acidum aceticum.", "Daher Acetat.", "Acetat."],
                solution="Das Salz der Essigsäure heißt Acetat, etwa Natriumacetat CH₃COONa.",
                misconceptions=[fv("nomenklatur_falsch", 2,
                                   "Formiat ist das Salz der Methansäure.",
                                   "nomenklatur_falsch")],
                tags=["salze", "namen"], spiral=["K-ORG"]),
        aufgabe("OS03-A3-003", "A", 3, "choice",
                "Riecht Natriumacetat wie Essigsäure?",
                options=["Nein — es ist ein geruchloser Feststoff.", "Ja, genauso.", "Es riecht stärker."],
                answer=0,
                hints=["Das Salz besteht aus Ionen.",
                       "Ionen sind nicht flüchtig.",
                       "Also geruchlos."],
                solution="Das Salz besteht aus Ionen im Gitter und ist nicht flüchtig. Es riecht deshalb nicht — anders als die molekulare Essigsäure.",
                tags=["salze"], spiral=["K-STOF"]),
        aufgabe("OS03-A4-004", "A", 4, "choice",
                "Wie heißt das Salz der Citronensäure?",
                options=["Citrat", "Acetat", "Lactat"], answer=0,
                hints=["Aus -säure wird -at.", "Citronensäure → Citrat.", "Citrat."],
                solution="Das Salz der Citronensäure heißt Citrat — auf Zutatenlisten oft als Natriumcitrat.",
                tags=["salze", "namen"], spiral=["K-ORG"]),
        aufgabe("OS03-B1-005", "B", 1, "choice",
                "Warum ist Natriumacetat fest, Essigsäure aber flüssig?",
                options=["Das Salz besteht aus Ionen im Gitter, die Säure aus Molekülen.",
                         "Das Salz ist schwerer.",
                         "Das Salz enthält kein Wasser."],
                answer=0,
                hints=["Welche Bindungsart liegt jeweils vor?",
                       "Ionenbindung gegen Molekülverband.",
                       "Ionengitter halten viel stärker zusammen."],
                solution="Bei der Neutralisation wechselt die Bindungsart: Aus Molekülen mit Wasserstoffbrücken wird ein Ionengitter. Deshalb ist das Salz fest, geruchlos und hochschmelzend.",
                tags=["salze", "bbr"], spiral=["K-ATOM"]),
        aufgabe("OS03-B2-006", "B", 2, "choice",
                "Welches Salz entsteht aus Methansäure und Kalilauge?",
                options=["Kaliumformiat", "Kaliumacetat", "Kaliumcitrat"], answer=0,
                hints=["Das Metall stammt aus der Lauge: Kalium.",
                       "Das Anion aus der Methansäure: Formiat.",
                       "Kaliumformiat."],
                solution="Methansäure ergibt das Formiat, die Kalilauge liefert das Kalium: Kaliumformiat HCOOK.",
                tags=["salze", "bbr"], spiral=["K-BIND"]),
        aufgabe("OS03-B2-007", "B", 2, "choice",
                "Warum reagiert eine Natriumacetat-Lösung leicht alkalisch?",
                options=["Das Acetat-Ion nimmt Protonen aus dem Wasser auf; dabei entsteht OH⁻.",
                         "Weil Natrium ein Metall ist.",
                         "Weil noch Natronlauge übrig ist."],
                answer=0,
                hints=["Das Anion stammt von einer schwachen Säure.",
                       "Solche Anionen sind Basen.",
                       "Sie nehmen Protonen auf."],
                solution="Das Acetat-Ion ist die korrespondierende Base der schwachen Essigsäure. Es nimmt Protonen aus dem Wasser auf, dabei bleibt OH⁻ zurück — die Lösung reagiert leicht alkalisch.",
                tags=["salze", "msa"], spiral=["K-SL"]),
        aufgabe("OS03-B3-008", "B", 3, "assign",
                "Ordne jeder Säure ihr Salz zu.",
                slots=["Methansäure", "Ethansäure", "Milchsäure"],
                values=["Formiat", "Acetat", "Lactat"], answer=[0, 1, 2],
                hints=["Aus -säure wird -at.",
                       "Ameisensäure → Formiat.",
                       "Milchsäure → Lactat."],
                solution="Methansäure → Formiat, Ethansäure → Acetat, Milchsäure → Lactat.",
                tags=["salze", "namen", "bbr"], spiral=["K-ORG"]),
        aufgabe("OS03-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Natriumacetat CH₃COONa? (C = 12, H = 1, O = 16, Na = 23 g/mol)",
                answer=82, unit_label="g/mol", tolerance=1,
                hints=["2 C, 3 H, 2 O, 1 Na.",
                       "24 + 3 + 32 + 23.",
                       "82 g/mol."],
                solution="M = 2 · 12 + 3 · 1 + 2 · 16 + 23 = 24 + 3 + 32 + 23 = 82 g/mol",
                tags=["salze", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("OS03-B4-010", "B", 4, "choice",
                "Warum sind Fettsäuren wasserunlöslich, ihre Natriumsalze aber löslich?",
                options=["Das Salz liegt als Ion vor; Ionen werden von Wasser hydratisiert.",
                         "Das Salz hat eine kürzere Kette.",
                         "Das Salz enthält mehr Sauerstoff."],
                answer=0,
                hints=["Was ändert sich bei der Neutralisation?",
                       "Aus der Carboxygruppe wird ein Ion.",
                       "Ionen ziehen Wassermoleküle an."],
                solution="Das geladene Carboxylat-Ion wird von Wassermolekülen hydratisiert. Die Kette bleibt gleich lang, aber der polare Kopf ist nun geladen — genau darauf beruht die Wirkung der Seifen.",
                tags=["salze", "msa"], spiral=["K-SL"]),
        aufgabe("OS03-C2-011", "C", 2, "multi",
                "60 g Essigsäure (M = 60 g/mol) werden mit Natronlauge vollständig neutralisiert.",
                fields=[
                    {"label": "Stoffmenge der Essigsäure", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "benötigte Stoffmenge NaOH", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse des entstehenden Natriumacetats (M = 82 g/mol)", "answer": 82, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 60 : 60 = 1 mol.",
                       "Essigsäure ist einprotonig.",
                       "m = 1 · 82."],
                solution="n(Säure) = 1 mol → n(NaOH) = 1 mol → m(Salz) = 82 g",
                tags=["salze", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("OS03-C3-012", "C", 3, "choice",
                "Warum sieden Carbonsäuren höher als Alkohole vergleichbarer Masse?",
                options=["Zwei Säuremoleküle lagern sich über zwei Wasserstoffbrücken zu Paaren zusammen.",
                         "Sie sind schwerer.",
                         "Sie sind unpolar."],
                answer=0,
                hints=["Wie viele Brücken kann eine Carboxygruppe bilden?",
                       "Zwei — über beide Sauerstoffatome.",
                       "Das ergibt besonders stabile Paare."],
                solution="Die Carboxygruppe kann über beide Sauerstoffatome Wasserstoffbrücken bilden. Zwei Moleküle lagern sich zu einem Doppelmolekül zusammen — deshalb siedet Essigsäure (118 °C) höher als Ethanol (78 °C).",
                tags=["salze", "msa"], spiral=["K-ORG"]),
        aufgabe("OS03-C3-013", "C", 3, "choice",
                "Warum werden Konservierungsmittel oft als Salze eingesetzt, etwa Natriumbenzoat statt Benzoesäure?",
                options=["Die Salze sind besser wasserlöslich und lassen sich leichter dosieren.",
                         "Die Salze wirken stärker.",
                         "Die Säuren sind giftig."],
                answer=0,
                hints=["Wie löslich sind langkettige Säuren?",
                       "Schlecht.",
                       "Die Salze deutlich besser."],
                solution="Benzoesäure ist in Wasser schwer löslich, ihr Natriumsalz gut. Für die Anwendung in wässrigen Lebensmitteln ist das entscheidend — im sauren Milieu entsteht daraus wieder die wirksame Säure.",
                tags=["salze", "bewerten", "msa"], spiral=["K-SL"]),
        aufgabe("OS03-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Natriumacetat ist dasselbe wie Essigsäure, nur mit Natrium.“ Wie bewertest du das?",
                options=["Zu ungenau — mit der Neutralisation wechselt die Bindungsart, und damit ändern sich Zustand, Geruch und Löslichkeit vollständig.",
                         "Richtig.",
                         "Falsch — beide haben nichts miteinander zu tun."],
                answer=0,
                hints=["Was ändert sich bei der Neutralisation?",
                       "Aus Molekülen werden Ionen.",
                       "Und damit alle Eigenschaften."],
                solution="Der Zusammenhang stimmt — das Acetat stammt aus der Essigsäure. Verändert hat sich aber die Bindungsart: Aus einer flüchtigen, stechend riechenden Flüssigkeit wird ein geruchloser, hochschmelzender Feststoff. „Nur mit Natrium“ verkennt das.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Aus Molekülen werden Ionen — die Eigenschaften ändern sich vollständig.",
                                   "ion_und_atom_verwechselt")],
                tags=["salze", "bewerten", "msa"], spiral=["K-ATOM"])
    ]
})

if __name__ == "__main__":
    schreiben("os", E, "Bereich OS · Einheiten 2 und 3")
