# -*- coding: utf-8 -*-
"""Bereich ES · Ester und Makromoleküle — ES-04 bis ES-06."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ES-04",
    "title": "Verseifung und die Wirkung der Seife",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.3"],
    "klasse": 10,
    "sicherheit": [
        "Bei der Seifenherstellung wird konzentrierte Natronlauge verwendet — stark ätzend.",
        "Schutzbrille und Handschuhe sind Pflicht, die Mischung wird heiß."
    ],
    "wortspeicher": ["die Verseifung", "die Seife", "die Micelle", "hydrophil", "hydrophob",
                     "die Emulsion", "die Kernseife"],
    "worterklaerungen": {
        "Verseifung": "Die Spaltung eines Fettes mit Lauge. Es entstehen Glycerin und Seife.",
        "Micelle": "Eine Kugel aus Seifenteilchen um einen Fetttropfen.",
        "Emulsion": "Feine Fetttröpfchen, die im Wasser verteilt bleiben."
    },
    "can_do": {
        "A": "Ich weiß, dass Seife Fett und Wasser verbindet.",
        "B": "Ich beschreibe die Verseifung und den Bau eines Seifenteilchens.",
        "C": "Ich erkläre die Micellbildung und die Grenzen der Seifenwirkung."
    },
    "lernkarten": {
        "A": karte("Seife verbindet Fett und Wasser",
                   "Wasser allein löst kein Fett.",
                   ["Mit Seife geht es.", "Das Seifenteilchen hat zwei Enden."],
                   "Ein Ende mag Wasser, das andere Fett.",
                   visual=anim("seife", "A"),
                   beispiel={"titel": "Beim Händewaschen",
                             "aufgabe": "Was passiert mit dem Fett?",
                             "schritte": ["Die Seifenteilchen umhüllen es.",
                                          "Der Tropfen wird abgespült."],
                             "ergebnis": "Das Fett geht mit dem Wasser weg."}),
        "B": karte("Verseifung und Bau der Seife",
                   "Seife entsteht durch die Umkehrung der Veresterung: Ein Fett wird mit Lauge gespalten.",
                   ["Fett + Natronlauge → Glycerin + drei Natriumsalze der Fettsäuren. Diese Salze sind die Seife.",
                    "Ein Seifenteilchen hat zwei Bereiche: eine geladene Carboxylat-Gruppe als hydrophilen Kopf und eine lange Kohlenwasserstoffkette als hydrophoben Schwanz.",
                    "Der Kopf löst sich in Wasser, der Schwanz im Fett. Damit vermittelt das Teilchen zwischen beiden.",
                    "Bei Kalilauge entsteht Schmierseife, bei Natronlauge feste Kernseife.",
                    "Die Verseifung ist die Umkehrung der Veresterung — mit Lauge statt Wasser."],
                   "Geladener Kopf ins Wasser, langer Schwanz ins Fett.",
                   visual=anim("seife", "B")),
        "C": karte("Micellen und Grenzen",
                   "Wie Seife wirkt, lässt sich vollständig aus dem Bau des Teilchens ableiten — ebenso, wo sie versagt.",
                   ["Die Schwänze stecken im Fetttropfen, die Köpfe zeigen nach außen ins Wasser. Es entsteht eine Micelle.",
                    "Nach außen trägt der Tropfen nun gleiche Ladungen. Die Tropfen stoßen sich ab und fließen nicht wieder zusammen — eine stabile Emulsion.",
                    "Seife senkt zusätzlich die Oberflächenspannung des Wassers, sodass es besser in Gewebe eindringt.",
                    "Grenze 1 — hartes Wasser: Calcium- und Magnesium-Ionen bilden mit den Fettsäureresten schwerlösliche Kalkseife. Sie wäscht nicht und hinterlässt Ränder.",
                    "Grenze 2 — saure Lösung: Dort wird aus dem Carboxylat wieder die ungeladene Fettsäure, der hydrophile Kopf verschwindet und die Waschwirkung endet."],
                   "Micelle: Schwänze innen, geladene Köpfe außen — deshalb bleiben die Tropfen getrennt.",
                   visual=anim("seife", "C"))
    },
    "formelkarte": {"formeln": ["Fett + 3 NaOH → Glycerin + 3 R–COONa"],
                    "saetze": ["Verseifung: Spaltung eines Fettes mit Lauge.",
                               "Seife = Natriumsalz einer Fettsäure.",
                               "Hydrophiler Kopf, hydrophober Schwanz.",
                               "In hartem Wasser bildet sich unlösliche Kalkseife."]},
    "tasks": [
        aufgabe("ES04-A1-001", "A", 1, "choice",
                "Warum löst Wasser mit Seife Fett besser als Wasser allein?",
                options=["Seifenteilchen haben ein Ende für Wasser und eines für Fett.",
                         "Seife macht das Wasser wärmer.",
                         "Seife löst das Fett chemisch auf."],
                answer=0, visual=anim("seife", "A"),
                hints=["Das Seifenteilchen hat zwei Enden.",
                       "Eines mag Wasser, eines Fett.",
                       "So vermittelt es."],
                solution="Ein Seifenteilchen hat einen wasserfreundlichen Kopf und einen fettfreundlichen Schwanz. Damit verbindet es beides.",
                tags=["seife"], spiral=["K-SL"]),
        aufgabe("ES04-A2-002", "A", 2, "choice",
                "Was entsteht bei der Verseifung eines Fettes?",
                options=["Glycerin und Seife", "nur Seife", "Alkohol und Säure"], answer=0,
                hints=["Das Fett wird gespalten.", "Der Alkoholteil ist Glycerin.", "Und die Salze sind die Seife."],
                solution="Bei der Verseifung entstehen Glycerin und die Natriumsalze der Fettsäuren — die Seife.",
                tags=["seife"], spiral=["K-REAK"]),
        aufgabe("ES04-A3-003", "A", 3, "choice",
                "Welches Ende des Seifenteilchens steckt im Fetttropfen?",
                options=["der lange unpolare Schwanz", "der geladene Kopf", "beide"], answer=0,
                visual=anim("seife", "A"),
                hints=["Fett ist unpolar.",
                       "Gleiches löst sich in Gleichem.",
                       "Also der unpolare Schwanz."],
                solution="Der lange unpolare Schwanz steckt im Fett, der geladene Kopf zeigt ins Wasser.",
                misconceptions=[fv("polar_unpolar_vertauscht", 1,
                                   "Der geladene Kopf löst sich im Wasser, nicht im Fett.",
                                   "polar_unpolar_vertauscht")],
                tags=["seife"], spiral=["K-SL"]),
        aufgabe("ES04-A4-004", "A", 4, "choice",
                "Warum hinterlässt Seife in hartem Wasser Ränder?",
                options=["Sie bildet mit Calcium-Ionen unlösliche Kalkseife.",
                         "Sie ist zu alt.", "Das Wasser ist zu warm."],
                answer=0,
                hints=["Was ist in hartem Wasser gelöst?",
                       "Calcium- und Magnesium-Ionen.",
                       "Sie bilden mit der Seife etwas Unlösliches."],
                solution="Calcium- und Magnesium-Ionen bilden mit den Fettsäureresten schwerlösliche Kalkseife. Sie wäscht nicht und setzt sich als Rand ab.",
                tags=["seife"], spiral=["K-SL"]),
        aufgabe("ES04-B1-005", "B", 1, "choice",
                "Was ist eine Seife chemisch?",
                options=["das Natriumsalz einer Fettsäure", "ein Alkohol", "ein Ester"],
                answer=0,
                hints=["Sie entsteht aus einem Fett und einer Lauge.",
                       "Also durch Neutralisation.",
                       "Ein Salz."],
                solution="Seife ist das Natriumsalz einer langkettigen Fettsäure — entstanden bei der Verseifung mit Natronlauge.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 2,
                                   "Der Ester war das Fett. Bei der Verseifung wird er gespalten.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["seife", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES04-B2-006", "B", 2, "choice",
                "Was ist eine Micelle?",
                options=["Ein Fetttropfen, umhüllt von Seifenteilchen mit den Köpfen nach außen.",
                         "Ein einzelnes Seifenteilchen.",
                         "Ein Wassertropfen im Fett."],
                answer=0, visual=anim("seife", "B"),
                hints=["Viele Seifenteilchen umgeben einen Tropfen.",
                       "Die Schwänze zeigen nach innen.",
                       "Die Köpfe nach außen."],
                solution="In einer Micelle stecken die unpolaren Schwänze im Fetttropfen, die geladenen Köpfe zeigen ins Wasser. So bleibt der Tropfen in der Schwebe.",
                tags=["seife", "bbr"], spiral=["K-SL"]),
        aufgabe("ES04-B2-007", "B", 2, "choice",
                "Warum fließen die umhüllten Fetttropfen nicht wieder zusammen?",
                options=["Nach außen tragen sie gleiche Ladungen und stoßen sich ab.",
                         "Sie sind zu klein.",
                         "Sie sind zu schwer."],
                answer=0,
                hints=["Was zeigt bei der Micelle nach außen?",
                       "Die geladenen Köpfe.",
                       "Alle tragen dieselbe Ladung."],
                solution="Alle Micellen tragen außen dieselbe Ladung. Gleiche Ladungen stoßen sich ab — die Tropfen bleiben getrennt. So entsteht eine stabile Emulsion.",
                tags=["seife", "msa"], spiral=["K-ATOM"]),
        aufgabe("ES04-B3-008", "B", 3, "choice",
                "Warum verliert Seife in saurer Lösung ihre Waschwirkung?",
                options=["Aus dem geladenen Carboxylat wird wieder die ungeladene Fettsäure.",
                         "Die Säure zerstört das Fett.",
                         "Die Säure löst die Seife auf."],
                answer=0,
                hints=["Was passiert mit dem Carboxylat-Ion in saurer Lösung?",
                       "Es nimmt ein Proton auf.",
                       "Dann ist es nicht mehr geladen."],
                solution="In saurer Lösung nimmt das Carboxylat-Ion ein Proton auf und wird zur ungeladenen Fettsäure. Der hydrophile Kopf verschwindet — das Teilchen kann nicht mehr zwischen Fett und Wasser vermitteln.",
                tags=["seife", "msa"], spiral=["K-SL"]),
        aufgabe("ES04-B3-009", "B", 3, "choice",
                "Welche Lauge ergibt feste Kernseife?",
                options=["Natronlauge", "Kalilauge", "Kalkwasser"], answer=0,
                hints=["Kalilauge ergibt Schmierseife.",
                       "Die andere ergibt feste Seife.",
                       "Natronlauge."],
                solution="Mit Natronlauge entsteht feste Kernseife, mit Kalilauge die weichere Schmierseife.",
                tags=["seife", "bbr"], spiral=["K-REAK"]),
        aufgabe("ES04-B4-010", "B", 4, "choice",
                "Wie hängt die Verseifung mit der Veresterung zusammen?",
                options=["Sie ist die Umkehrung — der Ester wird wieder gespalten.",
                         "Sie ist dieselbe Reaktion.",
                         "Sie haben nichts miteinander zu tun."],
                answer=0,
                hints=["Bei der Veresterung entsteht ein Ester.",
                       "Bei der Verseifung wird er gespalten.",
                       "Also die Umkehrung."],
                solution="Die Veresterung verknüpft Säure und Alkohol, die Verseifung spaltet den Ester wieder. Weil mit Lauge gearbeitet wird, entsteht statt der Säure ihr Salz — und die Reaktion läuft vollständig ab statt ins Gleichgewicht.",
                tags=["seife", "msa"], spiral=["K-REAK"]),
        aufgabe("ES04-C2-011", "C", 2, "choice",
                "Warum läuft die Verseifung vollständig ab, die Veresterung aber nur bis zum Gleichgewicht?",
                options=["Die Lauge entzieht dem System die Säure als Salz; die Rückreaktion ist damit blockiert.",
                         "Die Verseifung ist schneller.",
                         "Bei der Verseifung wird stärker erhitzt."],
                answer=0,
                hints=["Was wird bei der Verseifung aus der Säure?",
                       "Ihr Salz.",
                       "Das Salz kann nicht zurückreagieren."],
                solution="Die entstehende Säure wird von der Lauge sofort in ihr Salz überführt. Damit steht sie für die Rückreaktion nicht mehr zur Verfügung — die Verseifung läuft vollständig ab.",
                tags=["seife", "msa"], spiral=["K-REAK"]),
        aufgabe("ES04-C3-012", "C", 3, "choice",
                "Warum senkt Seife die Oberflächenspannung des Wassers?",
                options=["Die Seifenteilchen lagern sich an der Oberfläche an und stören die Wasserstoffbrücken.",
                         "Seife macht das Wasser schwerer.",
                         "Seife erwärmt das Wasser."],
                answer=0,
                hints=["Wodurch entsteht die Oberflächenspannung?",
                       "Durch Wasserstoffbrücken zwischen den Wassermolekülen.",
                       "Die Seifenteilchen stören sie."],
                solution="Die Seifenteilchen lagern sich mit den Schwänzen nach außen an der Oberfläche an und unterbrechen dort das Netz aus Wasserstoffbrücken. Das Wasser dringt dadurch besser in Gewebe ein.",
                tags=["seife", "msa"], spiral=["K-STOF"]),
        aufgabe("ES04-C3-013", "C", 3, "multi",
                "Ein Fett (M = 806 g/mol) wird mit Natronlauge (M = 40 g/mol) verseift. Je Fettmolekül werden drei NaOH gebraucht.",
                fields=[
                    {"label": "Stoffmenge NaOH je mol Fett", "answer": 3, "unit_label": "mol", "tolerance": 0.1},
                    {"label": "Masse NaOH für 1 mol Fett", "answer": 120, "unit_label": "g", "tolerance": 2},
                    {"label": "Masse NaOH für 403 g Fett", "answer": 60, "unit_label": "g", "tolerance": 2}
                ],
                hints=["Drei Esterbindungen, also 3 NaOH.",
                       "3 · 40 = 120 g.",
                       "403 g sind 0,5 mol Fett."],
                solution="je mol Fett: 3 mol NaOH = 120 g\n403 g Fett = 0,5 mol → 1,5 mol NaOH = 60 g",
                tags=["seife", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("ES04-C4-014", "C", 4, "choice",
                "Warum enthalten moderne Waschmittel meist keine klassische Seife mehr?",
                options=["Sie bildet in hartem Wasser Kalkseife; synthetische Tenside tun das nicht.",
                         "Seife ist zu teuer.",
                         "Seife schäumt zu wenig."],
                answer=0,
                hints=["Was ist das Problem der Seife in hartem Wasser?",
                       "Kalkseife.",
                       "Synthetische Tenside vermeiden das."],
                solution="Klassische Seife bildet mit Calcium- und Magnesium-Ionen unlösliche Kalkseife — sie wäscht dann nicht und hinterlässt Rückstände. Synthetische Tenside haben andere Kopfgruppen und bleiben auch in hartem Wasser löslich.",
                tags=["seife", "bewerten", "msa"], spiral=["K-SL"])
    ]
})

E.append({
    "unit": "ES-05",
    "title": "Polyester und Makromoleküle",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["das Makromolekül", "der Kunststoff", "der Polyester", "das Monomer",
                     "die Polykondensation", "die bifunktionelle Verbindung", "PET"],
    "worterklaerungen": {
        "Makromolekül": "Ein sehr großes Molekül aus vielen gleichen Bausteinen.",
        "Monomer": "Der einzelne Baustein eines Makromoleküls.",
        "bifunktionell": "Ein Molekül mit zwei funktionellen Gruppen."
    },
    "can_do": {
        "A": "Ich weiß, dass Kunststoffe aus sehr vielen gleichen Bausteinen bestehen.",
        "B": "Ich erkläre, warum für einen Polyester zwei funktionelle Gruppen je Baustein nötig sind.",
        "C": "Ich bewerte Eigenschaften und Recycling von Polyestern."
    },
    "lernkarten": {
        "A": karte("Sehr lange Ketten",
                   "Kunststoffe bestehen aus riesigen Molekülen.",
                   ["Viele gleiche Bausteine sind aneinandergehängt.",
                    "Ein solches Molekül heißt Makromolekül."],
                   "Viele Bausteine, ein Riesenmolekül.",
                   visual={"type": "struktur", "kette": 6, "gruppe": "ester",
                           "alt": "Ausschnitt aus einer Polyesterkette."},
                   beispiel={"titel": "PET-Flasche", "aufgabe": "Woraus besteht sie?",
                             "schritte": ["Aus vielen gleichen Bausteinen.",
                                          "Sie sind durch Esterbindungen verknüpft."],
                             "ergebnis": "Ein Polyester."}),
        "B": karte("Warum zwei Gruppen nötig sind",
                   "Aus Essigsäure und Ethanol entsteht nur ein einzelnes Estermolekül. Für eine Kette braucht es Bausteine mit zwei reaktionsfähigen Enden.",
                   ["Ein Baustein mit nur einer funktionellen Gruppe kann nur einmal reagieren — die Kette endet sofort.",
                    "Eine Dicarbonsäure hat zwei Carboxygruppen, ein zweiwertiger Alkohol zwei OH-Gruppen. Jeder Baustein kann an beiden Enden weiterreagieren.",
                    "So entsteht abwechselnd Säure–Alkohol–Säure–Alkohol, verknüpft über Esterbindungen — ein Polyester.",
                    "Bei jedem Verknüpfungsschritt wird Wasser abgespalten. Deshalb heißt der Vorgang Polykondensation.",
                    "PET, das Material der Getränkeflaschen, entsteht genau so."],
                   "Zwei funktionelle Gruppen je Baustein — nur so wächst die Kette weiter.",
                   visual=anim("veresterung", "B")),
        "C": karte("Eigenschaften und Recycling",
                   "Aus der Kettenlänge und der Bindungsart folgen sowohl die Eigenschaften des Kunststoffs als auch die Möglichkeiten seiner Wiederverwertung.",
                   ["Lange Ketten bedeuten viele van-der-Waals-Kontakte zwischen den Molekülen — daher Festigkeit und hohe Erweichungstemperatur.",
                    "Polyester lassen sich zu Fasern ziehen; dabei richten sich die Ketten parallel aus und die Faser wird sehr reißfest.",
                    "Werkstoffliches Recycling: Einschmelzen und neu formen. Bei jedem Durchgang werden die Ketten etwas kürzer, die Qualität sinkt.",
                    "Chemisches Recycling: Die Esterbindungen werden gespalten und die Monomere zurückgewonnen — dieselbe Reaktion wie die Verseifung, nur technisch.",
                    "Zu bedenken: Kunststoffe sind langlebig — das ist als Werkstoff ein Vorteil und als Abfall ein Problem."],
                   "Esterbindungen lassen sich spalten — deshalb ist chemisches Recycling möglich.",
                   visual={"type": "struktur", "kette": 8, "gruppe": "ester",
                           "alt": "Langer Ausschnitt einer Polyesterkette."})
    },
    "formelkarte": {"formeln": ["Dicarbonsäure + zweiwertiger Alkohol → Polyester + n H₂O"],
                    "saetze": ["Makromolekül: sehr viele gleiche Bausteine.",
                               "Für eine Kette braucht jeder Baustein zwei funktionelle Gruppen.",
                               "Polykondensation: Verknüpfung unter Wasserabspaltung.",
                               "PET ist ein Polyester und wird zu Flaschen und Fasern verarbeitet."]},
    "tasks": [
        aufgabe("ES05-A1-001", "A", 1, "choice",
                "Woraus bestehen Kunststoffe?",
                options=["aus sehr vielen gleichen Bausteinen", "aus einem einzigen Molekül", "aus Metall"],
                answer=0,
                hints=["Der Fachbegriff ist Makromolekül.",
                       "Makro heißt groß.",
                       "Aus vielen Bausteinen."],
                solution="Kunststoffe bestehen aus Makromolekülen — sehr langen Ketten aus vielen gleichen Bausteinen.",
                tags=["kunststoffe"], spiral=["K-ORG"]),
        aufgabe("ES05-A2-002", "A", 2, "choice",
                "Wie werden die Bausteine im Polyester verknüpft?",
                options=["über Esterbindungen", "über Ionenbindungen", "über Metallbindungen"],
                answer=0,
                hints=["Der Name sagt es.", "Poly-ester.", "Über Esterbindungen."],
                solution="Der Name verrät es: Im Polyester sind die Bausteine über Esterbindungen verknüpft.",
                tags=["kunststoffe"], spiral=["K-ORG"]),
        aufgabe("ES05-A3-003", "A", 3, "choice",
                "Woraus besteht eine PET-Flasche?",
                options=["aus einem Polyester", "aus Glas", "aus Metall"], answer=0,
                hints=["PET steht für Polyethylenterephthalat.",
                       "Das Wort enthält „Polye…“.",
                       "Ein Polyester."],
                solution="PET ist ein Polyester und wird für Getränkeflaschen und Textilfasern verwendet.",
                tags=["kunststoffe"], spiral=["K-ORG"]),
        aufgabe("ES05-A4-004", "A", 4, "choice",
                "Was wird bei jedem Verknüpfungsschritt abgespalten?",
                options=["Wasser", "Sauerstoff", "Kohlenstoffdioxid"], answer=0,
                hints=["Wie bei der Veresterung.",
                       "Dort entsteht auch Wasser.",
                       "Wasser."],
                solution="Bei jeder Esterbindung wird ein Wassermolekül abgespalten — deshalb heißt der Vorgang Polykondensation.",
                tags=["kunststoffe"], spiral=["K-REAK"]),
        aufgabe("ES05-B1-005", "B", 1, "choice",
                "Warum braucht ein Baustein für einen Polyester zwei funktionelle Gruppen?",
                options=["Nur dann kann er an beiden Enden weiterreagieren und die Kette wächst.",
                         "Damit er schwerer wird.",
                         "Damit er sich besser löst."],
                answer=0,
                hints=["Was passiert bei nur einer Gruppe?",
                       "Die Kette endet nach einem Schritt.",
                       "Für Wachstum braucht es zwei Enden."],
                solution="Mit nur einer funktionellen Gruppe endet die Kette nach der ersten Verknüpfung. Erst zwei Gruppen je Baustein erlauben ein Weiterwachsen an beiden Enden.",
                tags=["kunststoffe", "msa"], spiral=["K-ORG"]),
        aufgabe("ES05-B2-006", "B", 2, "choice",
                "Warum entsteht aus Essigsäure und Ethanol kein Kunststoff?",
                options=["Beide haben nur eine funktionelle Gruppe; nach einer Verknüpfung ist Schluss.",
                         "Sie reagieren zu langsam.",
                         "Sie sind zu klein."],
                answer=0,
                hints=["Zähle die funktionellen Gruppen.",
                       "Je eine.",
                       "Also nur ein Verknüpfungsschritt."],
                solution="Essigsäure hat eine Carboxygruppe, Ethanol eine Hydroxylgruppe. Nach der Veresterung ist an beiden Enden nichts mehr reaktionsfähig — es entsteht ein einzelnes Estermolekül.",
                tags=["kunststoffe", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES05-B2-007", "B", 2, "choice",
                "Warum sind Polyesterfasern besonders reißfest?",
                options=["Beim Ziehen richten sich die langen Ketten parallel aus.",
                         "Sie enthalten Metall.",
                         "Sie sind sehr dick."],
                answer=0,
                hints=["Was passiert beim Ziehen der Faser?",
                       "Die Ketten ordnen sich.",
                       "Parallele Ketten halten besser zusammen."],
                solution="Beim Verstrecken richten sich die Makromoleküle parallel zur Faserachse aus. Dadurch wirken die van-der-Waals-Kräfte über große Kontaktflächen — die Faser wird sehr reißfest.",
                tags=["kunststoffe", "msa"], spiral=["K-ORG"]),
        aufgabe("ES05-B3-008", "B", 3, "choice",
                "Warum sind Kunststoffe meist fest, obwohl sie aus Molekülen bestehen?",
                options=["Die sehr langen Ketten haben große Kontaktflächen; die van-der-Waals-Kräfte summieren sich.",
                         "Sie enthalten Ionen.",
                         "Sie sind kristallin wie Salze."],
                answer=0,
                hints=["Wie lang sind die Ketten?",
                       "Sehr lang.",
                       "Viel Kontaktfläche heißt starke Anziehung."],
                solution="Einzelne van-der-Waals-Kräfte sind schwach, aber bei Makromolekülen wirken sie über sehr große Kontaktflächen. In der Summe halten sie den Werkstoff fest zusammen.",
                tags=["kunststoffe", "bbr"], spiral=["K-ORG"]),
        aufgabe("ES05-B3-009", "B", 3, "choice",
                "Was ist chemisches Recycling von PET?",
                options=["Die Esterbindungen werden gespalten und die Bausteine zurückgewonnen.",
                         "Das PET wird eingeschmolzen.",
                         "Das PET wird verbrannt."],
                answer=0,
                hints=["Chemisch heißt: eine Reaktion findet statt.",
                       "Die Esterbindungen werden gespalten.",
                       "Wie bei der Verseifung."],
                solution="Beim chemischen Recycling werden die Esterbindungen gespalten und die ursprünglichen Bausteine zurückgewonnen. Aus ihnen lässt sich neues PET in Neuware-Qualität herstellen.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 1,
                                   "Einschmelzen ist werkstoffliches Recycling — eine Zustandsänderung, keine Reaktion.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["kunststoffe", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("ES05-B4-010", "B", 4, "choice",
                "Warum sinkt beim Einschmelzen und Neuformen die Qualität eines Kunststoffs?",
                options=["Die Ketten werden bei jedem Durchgang etwas kürzer.",
                         "Es kommt Farbe hinzu.",
                         "Der Kunststoff wird schwerer."],
                answer=0,
                hints=["Was passiert mit langen Ketten bei Hitze?",
                       "Sie brechen teilweise.",
                       "Kürzere Ketten heißt geringere Festigkeit."],
                solution="Beim Erhitzen brechen einzelne Ketten. Kürzere Ketten haben weniger Kontaktfläche — der Werkstoff wird weniger fest. Deshalb wird recyceltes PET oft für weniger anspruchsvolle Anwendungen verwendet.",
                tags=["kunststoffe", "bewerten", "msa"], spiral=["K-ORG"]),
        aufgabe("ES05-C2-011", "C", 2, "choice",
                "Warum lässt sich Polylactid aus Milchsäure herstellen, obwohl Milchsäure nur eine Carboxygruppe hat?",
                options=["Milchsäure trägt zusätzlich eine OH-Gruppe — sie ist damit bifunktionell.",
                         "Milchsäure hat zwei Carboxygruppen.",
                         "Es wird ein zweiter Baustein zugesetzt."],
                answer=0,
                hints=["Welche Gruppen hat Milchsäure?",
                       "Eine COOH- und eine OH-Gruppe.",
                       "Beide sind reaktionsfähig."],
                solution="Milchsäure ist eine Hydroxycarbonsäure: Sie trägt eine Carboxygruppe und eine Hydroxylgruppe. Beide Enden können reagieren — ein einziger Baustein genügt für die Kette.",
                tags=["kunststoffe", "msa"], spiral=["K-ORG"]),
        aufgabe("ES05-C3-012", "C", 3, "choice",
                "Warum ist Polylactid unter bestimmten Bedingungen biologisch abbaubar?",
                options=["Die Esterbindungen lassen sich durch Wasser und Enzyme spalten.",
                         "Es besteht aus Zucker.",
                         "Es enthält keine Kohlenstoffatome."],
                answer=0,
                hints=["Welche Bindung verknüpft die Bausteine?",
                       "Die Esterbindung.",
                       "Sie ist spaltbar."],
                solution="Esterbindungen lassen sich hydrolytisch und enzymatisch spalten. Unter geeigneten Bedingungen — Wärme und Feuchtigkeit in einer Industriekompostierung — zerfällt Polylactid deshalb. Im Gartenkompost geschieht das kaum.",
                tags=["kunststoffe", "bewerten", "msa"], spiral=["K-REAK"]),
        aufgabe("ES05-C3-013", "C", 3, "choice",
                "Warum ist die Langlebigkeit von Kunststoffen zugleich Vorteil und Problem?",
                options=["Als Werkstoff ist Beständigkeit erwünscht, als Abfall bedeutet sie jahrhundertelangen Verbleib.",
                         "Sie ist nur ein Vorteil.",
                         "Sie ist nur ein Problem."],
                answer=0,
                hints=["Wofür wird Beständigkeit gebraucht?",
                       "Für die Verwendung.",
                       "Und was bedeutet sie nach dem Wegwerfen?"],
                solution="Dieselbe Eigenschaft, die einen Kunststoff als Werkstoff brauchbar macht — chemische Beständigkeit —, führt dazu, dass er als Abfall über sehr lange Zeit erhalten bleibt. Eine Bewertung muss beide Seiten nennen.",
                tags=["kunststoffe", "bewerten", "msa"]),
        aufgabe("ES05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Biokunststoffe sind immer besser für die Umwelt.“ Wie bewertest du das?",
                options=["Zu pauschal — entscheidend sind Herstellung, Flächenverbrauch und die tatsächlichen Abbaubedingungen.",
                         "Richtig.",
                         "Falsch, Biokunststoffe sind immer schlechter."],
                answer=0,
                hints=["Woraus werden Biokunststoffe hergestellt?",
                       "Aus Pflanzen — das braucht Fläche.",
                       "Und der Abbau gelingt nur unter bestimmten Bedingungen."],
                solution="„Bio“ bezeichnet teils die Herkunft, teils die Abbaubarkeit — beides ist nicht dasselbe. Anbaufläche, Energieaufwand und die Frage, ob die Abbaubedingungen in der Praxis erreicht werden, gehören in jede Bewertung.",
                tags=["kunststoffe", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("es", E, "Bereich ES · Einheiten 4 und 5")
