# -*- coding: utf-8 -*-
"""AL-07 (Abschluss Alkohole) sowie OS-01 und OS-02 (Organische Säuren)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

AL = []
OS = []

AL.append({
    "unit": "AL-07",
    "title": "Anwenden & Prüfungstraining Alkohole",
    "leitidee": "B2",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["die Hydroxylgruppe", "die homologe Reihe", "primär", "sekundär", "tertiär",
                     "die Wasserstoffbrücke", "die Gärung"],
    "worterklaerungen": {
        "Struktur-Eigenschafts-Konzept": "Aus dem Bau eines Moleküls lassen sich seine Eigenschaften ableiten."
    },
    "can_do": {
        "A": "Ich benenne Alkohole und erkenne die Hydroxylgruppe sicher.",
        "B": "Ich verbinde Bau, Eigenschaften und Reaktionen der Alkohole.",
        "C": "Ich sage Eigenschaften aus der Struktur voraus und bewerte Aussagen zu Alkohol."
    },
    "lernkarten": {
        "A": karte("Alkohole auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["–OH ist die funktionelle Gruppe.", "Kurze Ketten lösen sich in Wasser."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen.",
                   ["Bau: polare OH-Gruppe plus unpolarer Rest. Ihr Verhältnis bestimmt Löslichkeit und Siedepunkt.",
                    "Reihe: CₙH₂ₙ₊₁OH, Endung -ol, ab drei C-Atomen mit Positionsangabe.",
                    "Reaktion: primär → Alkanal → Säure, sekundär → Alkanon, tertiär → nichts."],
                   "Struktur bestimmt Eigenschaften — und auch das Reaktionsverhalten.",
                   visual=anim("funktionellegruppe", "B")),
        "C": karte("Vorhersagen und bewerten",
                   "Die anspruchsvollen Aufgaben verlangen zweierlei: aus dem Bau Eigenschaften abzuleiten und Aussagen zu Alkohol fachlich zu beurteilen.",
                   ["Vorhersage: Kettenlänge, Zahl der OH-Gruppen und deren Position genügen für eine Ordnung nach Löslichkeit und Siedepunkt.",
                    "Reaktionsverhalten: Zähle die C-Nachbarn am OH-tragenden Atom — daraus folgt das Oxidationsprodukt.",
                    "Bewertung: Aussagen über die Wirkung von Alkohol brauchen Angaben zu Menge und Zeit. „Ungiftig“ oder „harmlos“ sind ohne diese Angaben keine Aussagen.",
                    "Ähnlicher Bau erlaubt keinen Schluss auf ähnliche Wirkung — Methanol und Ethanol, Glycol und Glycerin sind die Beispiele dafür."],
                   "Aus dem Bau folgen Eigenschaften — aus der Ähnlichkeit folgt keine Wirkung.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["CₙH₂ₙ₊₁OH",
                               "primär: R–CH₂–OH → R–CHO → R–COOH",
                               "C₆H₁₂O₆ → 2 C₂H₅OH + 2 CO₂",
                               "c in ‰ = m(Alkohol) : (Körpermasse · r)"],
                    "saetze": ["Die OH-Gruppe bildet Wasserstoffbrücken.",
                               "Bis Propanol mit Wasser mischbar, ab Butanol abnehmend.",
                               "Primär, sekundär, tertiär: Zahl der C-Nachbarn am OH-C-Atom.",
                               "Abbau im Blut: rund 0,1 bis 0,15 ‰ je Stunde."]},
    "tasks": [
        aufgabe("AL07-A1-001", "A", 1, "choice",
                "Welche Gruppe haben alle Alkohole?",
                options=["–OH", "–COOH", "–NH₂"], answer=0,
                hints=["Sie heißt Hydroxylgruppe.", "O und H.", "–OH."],
                solution="Alle Alkohole tragen die Hydroxylgruppe –OH.",
                tags=["pruefung"], spiral=["W-ORG"]),
        aufgabe("AL07-A2-002", "A", 2, "choice",
                "Wie heißt der Alkohol mit zwei C-Atomen?",
                options=["Ethanol", "Methanol", "Propanol"], answer=0,
                hints=["Eth steht für 2.", "Dazu -ol.", "Ethanol."],
                solution="Zwei C-Atome ergeben Ethanol, C₂H₅OH.",
                tags=["pruefung"], spiral=["W-ORG"]),
        aufgabe("AL07-A3-003", "A", 3, "numeric",
                "Wie viel reiner Alkohol steckt in 250 mL Wein mit 12 Volumenprozent?",
                answer=30, unit_label="mL", tolerance=1,
                hints=["12 % von 250 mL.", "1 % sind 2,5 mL.", "12 · 2,5."],
                solution="250 mL · 0,12 = 30 mL reiner Alkohol.",
                tags=["pruefung", "rechnen"], spiral=["W-LOES"]),
        aufgabe("AL07-A4-004", "A", 4, "choice",
                "Welcher Alkohol ist giftig und darf nicht getrunken werden?",
                options=["Methanol", "Ethanol", "beide gleich"], answer=0,
                hints=["Er hat ein C-Atom.", "Er führt zur Erblindung.", "Methanol."],
                solution="Methanol wird im Körper zu Methansäure abgebaut und schädigt den Sehnerv.",
                tags=["pruefung", "sicherheit"]),
        aufgabe("AL07-B1-005", "B", 1, "choice",
                "Warum sieden Alkohole höher als Alkane vergleichbarer Masse?",
                options=["Die OH-Gruppen bilden Wasserstoffbrücken.",
                         "Alkohole sind schwerer.",
                         "Alkohole sind verzweigt."],
                answer=0,
                hints=["Was hat der Alkohol, was das Alkan nicht hat?",
                       "Die OH-Gruppe.",
                       "Sie bildet Brücken."],
                solution="Die polare OH-Gruppe bildet Wasserstoffbrücken. Diese sind deutlich stärker als die van-der-Waals-Kräfte zwischen Alkanmolekülen.",
                tags=["pruefung", "bbr"], spiral=["W-ORG"]),
        aufgabe("AL07-B2-006", "B", 2, "choice",
                "Was entsteht aus einem primären Alkohol bei vollständiger Oxidation?",
                options=["eine Alkansäure", "ein Alkanon", "ein Alkan"], answer=0,
                visual=anim("funktionellegruppe", "B"),
                hints=["Zwei Schritte.",
                       "Zuerst das Alkanal.",
                       "Dann die Säure."],
                solution="Ein primärer Alkohol wird über das Alkanal zur Alkansäure oxidiert.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Alkanone entstehen aus sekundären Alkoholen.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["pruefung", "bbr"], spiral=["W-ORG"]),
        aufgabe("AL07-B2-007", "B", 2, "numeric",
                "Wie groß ist die molare Masse von Butanol C₄H₉OH? (C = 12, H = 1, O = 16 g/mol)",
                answer=74, unit_label="g/mol", tolerance=1,
                hints=["4 C, 10 H, 1 O.", "48 + 10 + 16.", "74 g/mol."],
                solution="M = 4 · 12 + 10 · 1 + 16 = 74 g/mol",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("AL07-B3-008", "B", 3, "multi",
                "Ein Mann (75 kg, r = 0,7) trinkt 0,3 L Wein mit 12 Volumenprozent. (Dichte 0,8 g/mL)",
                fields=[
                    {"label": "Masse des Alkohols", "answer": 28.8, "unit_label": "g", "tolerance": 1},
                    {"label": "Blutalkoholkonzentration", "answer": 0.55, "unit_label": "‰", "tolerance": 0.05}
                ],
                hints=["300 · 0,12 = 36 mL.",
                       "36 · 0,8 = 28,8 g.",
                       "28,8 : (75 · 0,7) = 28,8 : 52,5."],
                solution="V = 36 mL → m = 28,8 g\nc = 28,8 : 52,5 = 0,55 ‰",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("AL07-B3-009", "B", 3, "choice",
                "Warum löst sich Methanol besser in Wasser als Hexanol?",
                options=["Bei Methanol überwiegt die polare OH-Gruppe die kurze Kette.",
                         "Methanol ist giftiger.",
                         "Hexanol hat keine OH-Gruppe."],
                answer=0,
                hints=["Beide haben eine OH-Gruppe.",
                       "Verschieden ist die Kettenlänge.",
                       "Lange Kette heißt mehr unpolarer Anteil."],
                solution="Beide besitzen eine OH-Gruppe. Bei Methanol dominiert sie das kleine Molekül; bei Hexanol überwiegt die lange unpolare Kette.",
                tags=["pruefung", "bbr"], spiral=["W-LOES"]),
        aufgabe("AL07-B4-010", "B", 4, "choice",
                "Wie lange dauert der Abbau von 0,8 ‰ bei 0,1 ‰ je Stunde?",
                options=["8 Stunden", "2 Stunden", "30 Minuten"], answer=0,
                hints=["0,8 geteilt durch 0,1.", "8.", "8 Stunden."],
                solution="0,8 ‰ : 0,1 ‰/h = 8 Stunden. Der Abbau lässt sich nicht beschleunigen.",
                tags=["pruefung", "bewerten", "bbr"], spiral=["W-RECH"]),
        aufgabe("AL07-C2-011", "C", 2, "choice",
                "Ein Alkohol lässt die glühende Kupferspirale schwarz bleiben. Was folgt daraus?",
                options=["Er ist tertiär und lässt sich nicht oxidieren.",
                         "Er ist primär.",
                         "Es ist kein Alkohol."],
                answer=0,
                hints=["Nur oxidierbare Alkohole reduzieren das Kupferoxid.",
                       "Bleibt es schwarz, fand keine Oxidation statt.",
                       "Also tertiär."],
                solution="Bleibt das schwarze Kupferoxid unverändert, fand keine Oxidation statt. Am OH-tragenden C-Atom sitzt kein Wasserstoff mehr — der Alkohol ist tertiär.",
                tags=["pruefung", "msa"], spiral=["W-GLEI"]),
        aufgabe("AL07-C3-012", "C", 3, "choice",
                "Ordne nach steigender Siedetemperatur: Ethanol, Glycerin, Propan.",
                options=["Propan < Ethanol < Glycerin", "Ethanol < Propan < Glycerin", "Glycerin < Ethanol < Propan"],
                answer=0,
                hints=["Propan hat keine OH-Gruppe.",
                       "Ethanol eine, Glycerin drei.",
                       "Mehr OH-Gruppen heißt höherer Siedepunkt."],
                solution="Propan (−42 °C) hat keine Wasserstoffbrücken, Ethanol (78 °C) eine OH-Gruppe, Glycerin (290 °C) drei. Die Zahl der OH-Gruppen bestimmt die Reihenfolge.",
                tags=["pruefung", "msa"], spiral=["W-ORG"]),
        aufgabe("AL07-C3-013", "C", 3, "multi",
                "92 g Ethanol (M = 46 g/mol) werden vollständig zu Essigsäure oxidiert (M = 60 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Ethanols", "answer": 2, "unit_label": "mol", "tolerance": 0.1},
                    {"label": "Masse der entstehenden Essigsäure", "answer": 120, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 92 : 46 = 2 mol.",
                       "Die Oxidation läuft 1 : 1.",
                       "m = 2 · 60."],
                solution="n(Ethanol) = 2 mol → n(Essigsäure) = 2 mol → m = 120 g\nDie Massenzunahme stammt vom aufgenommenen Sauerstoff.",
                tags=["pruefung", "rechnen", "msa"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("AL07-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Glycerin und Glycol sind beide Alkohole, also beide unbedenklich.“ Wie bewertest du das?",
                options=["Falsch — Glycol wird zu Oxalsäure abgebaut und schädigt die Nieren; ähnlicher Bau sagt nichts über die Wirkung.",
                         "Richtig.",
                         "Falsch — beide sind giftig."],
                answer=0,
                hints=["Was entsteht beim Abbau von Glycol?",
                       "Oxalsäure.",
                       "Sie schädigt die Nieren."],
                solution="Beide sind mehrwertige Alkohole, aber der Abbau verläuft verschieden: Glycerin unbedenklich, Glycol zu nierenschädigender Oxalsäure. Von der Struktur auf die Wirkung zu schließen, ist unzulässig — wie schon bei Methanol und Ethanol.",
                tags=["pruefung", "bewerten", "msa"])
    ]
})

# ============================================================
# OS-01 · Die Carboxygruppe im Alltag
# ============================================================
OS.append({
    "unit": "OS-01",
    "title": "Die Carboxygruppe im Alltag",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K3.1"],
    "klasse": 10,
    "wortspeicher": ["die Carboxygruppe", "die Carbonsäure", "die Essigsäure", "die Citronensäure",
                     "der Entkalker", "das Konservierungsmittel"],
    "worterklaerungen": {
        "Carboxygruppe": "Die Gruppe –COOH. Sie kennzeichnet die organischen Säuren.",
        "Carbonsäure": "Ein anderer Name für organische Säure."
    },
    "can_do": {
        "A": "Ich erkenne die Carboxygruppe und nenne organische Säuren aus dem Alltag.",
        "B": "Ich erkläre, warum die Carboxygruppe sauer reagiert.",
        "C": "Ich vergleiche organische mit anorganischen Säuren und bewerte ihre Verwendung."
    },
    "lernkarten": {
        "A": karte("Die COOH-Gruppe",
                   "Organische Säuren haben eine besondere Gruppe.",
                   ["Sie heißt Carboxygruppe: –COOH.", "Essig und Zitronensaft enthalten sie."],
                   "–COOH kennzeichnet eine organische Säure.",
                   visual={"type": "struktur", "kette": 2, "gruppe": "cooh", "name": "Essigsäure",
                           "formel": "CH3COOH",
                           "alt": "Strukturformel von Essigsäure mit Carboxygruppe."},
                   beispiel={"titel": "Essigsäure", "aufgabe": "Wie ist Essigsäure gebaut?",
                             "schritte": ["Zwei Kohlenstoffatome.",
                                          "Am Ende sitzt die COOH-Gruppe."],
                             "ergebnis": "CH₃–COOH"}),
        "B": karte("Warum die Gruppe sauer reagiert",
                   "Die Carboxygruppe enthält ebenfalls ein OH — und gibt anders als beim Alkohol ein Proton ab. Der Unterschied liegt in der Nachbarschaft.",
                   ["Neben der OH-Gruppe sitzt eine Doppelbindung zum Sauerstoff. Diese zieht Elektronen ab und schwächt die Bindung zum Wasserstoff.",
                    "Dadurch kann das Proton an ein Wassermolekül abgegeben werden: R–COOH + H₂O ⇌ R–COO⁻ + H₃O⁺.",
                    "Der Alkohol hat diese Nachbarschaft nicht — deshalb reagiert er neutral.",
                    "Organische Säuren sind schwache Säuren: Nur ein kleiner Teil der Moleküle gibt sein Proton ab. Deshalb der Gleichgewichtspfeil.",
                    "Wichtige Vertreter: Methansäure (Ameisensäure), Ethansäure (Essigsäure), Citronensäure, Milchsäure."],
                   "Die Doppelbindung am Nachbaratom macht aus der OH-Gruppe eine Säuregruppe.",
                   visual={"type": "phskala", "marken": [{"wert": 2.4, "stoff": "Essigsäure 1 mol/L"},
                                                         {"wert": 7, "stoff": "Ethanol"}],
                           "alt": "pH-Skala: Essigsäure ist sauer, Ethanol neutral."}),
        "C": karte("Organisch und anorganisch im Vergleich",
                   "Organische Säuren wirken nach demselben Prinzip wie Salzsäure oder Schwefelsäure — aber deutlich milder. Genau das macht sie im Alltag verwendbar.",
                   ["Beide geben Protonen ab und färben Indikatoren rot, lösen Kalk und reagieren mit unedlen Metallen.",
                    "Organische Säuren sind schwach: In gleicher Konzentration liegt der pH-Wert deutlich höher als bei Salzsäure.",
                    "Deshalb sind sie im Haushalt einsetzbar — als Entkalker, Konservierungsmittel und Geschmacksgeber.",
                    "Sie sind trotzdem nicht harmlos: Konzentrierte Essigsäure ist ätzend, Ameisensäure verursacht schmerzhafte Verätzungen.",
                    "Viele sind biologisch abbaubar und werden deshalb Reinigern gegenüber Mineralsäuren vorgezogen."],
                   "Gleiches Prinzip, mildere Wirkung — deshalb im Haushalt verwendbar.",
                   visual={"type": "struktur", "kette": 1, "gruppe": "cooh", "name": "Methansäure",
                           "alt": "Strukturformel von Methansäure."})
    },
    "formelkarte": {"formeln": ["Carbonsäuren: R–COOH",
                               "R–COOH + H₂O ⇌ R–COO⁻ + H₃O⁺",
                               "Methansäure HCOOH · Essigsäure CH₃COOH"],
                    "saetze": ["–COOH ist die Carboxygruppe.",
                               "Organische Säuren sind schwache Säuren.",
                               "Alkohole reagieren neutral, Carbonsäuren sauer.",
                               "Sie lösen Kalk und reagieren mit unedlen Metallen."]},
    "tasks": [
        aufgabe("OS01-A1-001", "A", 1, "choice",
                "Welche Gruppe kennzeichnet eine organische Säure?",
                options=["–COOH", "–OH", "–CHO"], answer=0,
                visual={"type": "struktur", "kette": 2, "gruppe": "cooh",
                        "alt": "Strukturformel von Essigsäure."},
                hints=["Sie heißt Carboxygruppe.", "Sie enthält zwei O-Atome.", "–COOH."],
                solution="Die Carboxygruppe –COOH kennzeichnet die organischen Säuren.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "–OH ist die Hydroxylgruppe der Alkohole.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["carbonsaeuren"], spiral=["W-ORG"]),
        aufgabe("OS01-A2-002", "A", 2, "choice",
                "Welche Säure steckt im Speiseessig?",
                options=["Essigsäure", "Salzsäure", "Schwefelsäure"], answer=0,
                hints=["Der Name verrät es.", "Essigsäure.", "Sie ist eine organische Säure."],
                solution="Speiseessig enthält Essigsäure, chemisch Ethansäure CH₃COOH.",
                tags=["carbonsaeuren"], spiral=["W-ORG"]),
        aufgabe("OS01-A3-003", "A", 3, "choice",
                "Wozu wird Citronensäure im Haushalt verwendet?",
                options=["zum Entkalken", "zum Desinfizieren", "zum Färben"], answer=0,
                hints=["Säuren lösen Kalk.", "Citronensäure ist eine Säure.", "Zum Entkalken."],
                solution="Citronensäure löst Kalk und wird deshalb als Entkalker verwendet — milder als Mineralsäuren.",
                tags=["carbonsaeuren"], spiral=["W-LOES"]),
        aufgabe("OS01-A4-004", "A", 4, "choice",
                "Wie färbt sich Indikatorpapier in Essigsäure?",
                options=["rot", "blau", "grün"], answer=0,
                hints=["Essigsäure ist eine Säure.", "Säuren färben rot.", "Rot."],
                solution="Essigsäure reagiert sauer — der Indikator wird rot.",
                tags=["carbonsaeuren"], spiral=["W-LOES"]),
        aufgabe("OS01-B1-005", "B", 1, "choice",
                "Warum reagiert Essigsäure sauer, Ethanol aber nicht — beide enthalten eine OH-Gruppe?",
                options=["Die benachbarte Doppelbindung zum Sauerstoff schwächt die Bindung zum Wasserstoff.",
                         "Essigsäure hat mehr H-Atome.",
                         "Ethanol enthält keinen Sauerstoff."],
                answer=0,
                hints=["Was steht in der Carboxygruppe neben dem OH?",
                       "Eine Doppelbindung zum Sauerstoff.",
                       "Sie zieht Elektronen ab."],
                solution="In der Carboxygruppe zieht die benachbarte C=O-Doppelbindung Elektronen ab. Die Bindung zum Wasserstoff wird geschwächt, das Proton kann abgegeben werden. Beim Alkohol fehlt diese Nachbarschaft.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Nicht die Zahl der H-Atome entscheidet, sondern die Umgebung der OH-Gruppe.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["carbonsaeuren", "msa"], spiral=["W-ORG"]),
        aufgabe("OS01-B2-006", "B", 2, "choice",
                "Warum ist Essigsäure eine schwache Säure?",
                options=["Nur ein kleiner Teil der Moleküle gibt sein Proton ab.",
                         "Sie ist stark verdünnt.",
                         "Sie enthält wenig Wasserstoff."],
                answer=0,
                hints=["Was unterscheidet stark und schwach?",
                       "Wie vollständig das Proton abgegeben wird.",
                       "Bei Essigsäure nur teilweise."],
                solution="In einer Essigsäurelösung hat nur ein kleiner Teil der Moleküle das Proton abgegeben — deshalb der Gleichgewichtspfeil. Mit der Konzentration hat das nichts zu tun.",
                misconceptions=[fv("staerke_und_konzentration", 1,
                                   "Stärke und Konzentration sind zwei verschiedene Größen.")],
                tags=["carbonsaeuren", "bbr"], spiral=["W-LOES"]),
        aufgabe("OS01-B2-007", "B", 2, "choice",
                "Was entsteht, wenn Essigsäure auf Kalk trifft?",
                options=["ein Salz, Wasser und Kohlenstoffdioxid", "nur Wasser", "Wasserstoff"],
                answer=0,
                hints=["Wie bei jeder Säure mit Carbonat.",
                       "Es schäumt.",
                       "Kohlenstoffdioxid entweicht."],
                solution="Wie jede Säure setzt Essigsäure aus dem Carbonat Kohlensäure frei, die zu Wasser und Kohlenstoffdioxid zerfällt. Dazu entsteht ein Salz — hier Calciumacetat.",
                misconceptions=[fv("nachweis_verwechselt", 2,
                                   "Wasserstoff entsteht bei der Reaktion mit unedlen Metallen, nicht mit Kalk.",
                                   "nachweis_verwechselt")],
                tags=["carbonsaeuren", "bbr"], spiral=["W-GLEI"]),
        aufgabe("OS01-B3-008", "B", 3, "assign",
                "Ordne jeder Säure ihren Alltagsbezug zu.",
                slots=["Essigsäure", "Citronensäure", "Milchsäure"],
                values=["Speiseessig", "Zitrone und Entkalker", "Sauermilchprodukte"],
                answer=[0, 1, 2],
                hints=["Die Namen verraten viel.",
                       "Citronensäure steckt in Zitronen.",
                       "Milchsäure in Joghurt."],
                solution="Essigsäure → Essig.\nCitronensäure → Zitrone und Entkalker.\nMilchsäure → Joghurt und Sauerkraut.",
                tags=["carbonsaeuren", "bbr"], spiral=["W-ORG"]),
        aufgabe("OS01-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Essigsäure CH₃COOH? (C = 12, H = 1, O = 16 g/mol)",
                answer=60, unit_label="g/mol", tolerance=1,
                hints=["2 C, 4 H, 2 O.",
                       "24 + 4 + 32.",
                       "60 g/mol."],
                solution="M = 2 · 12 + 4 · 1 + 2 · 16 = 24 + 4 + 32 = 60 g/mol",
                misconceptions=[fv("summenformel_falsch_gelesen", 44,
                                   "Zähle beide Sauerstoffatome der Carboxygruppe.",
                                   "summenformel_falsch_gelesen")],
                tags=["carbonsaeuren", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("OS01-B4-010", "B", 4, "choice",
                "Warum wird zum Entkalken meist Citronensäure statt Salzsäure verwendet?",
                options=["Sie ist milder, biologisch abbaubar und im Haushalt sicherer zu handhaben.",
                         "Sie löst Kalk besser.",
                         "Salzsäure löst gar keinen Kalk."],
                answer=0,
                hints=["Welche Säure ist schwächer?",
                       "Die Citronensäure.",
                       "Und sie ist biologisch abbaubar."],
                solution="Salzsäure würde den Kalk sogar schneller lösen, ist aber stark ätzend und greift Metalle und Dichtungen an. Citronensäure ist milder, biologisch abbaubar und für den Haushalt geeignet.",
                tags=["carbonsaeuren", "bewerten", "msa"]),
        aufgabe("OS01-C2-011", "C", 2, "choice",
                "Warum ist konzentrierte Essigsäure trotz ihrer Schwäche als Säure ätzend?",
                options=["Bei hoher Konzentration ist die Zahl der Oxonium-Ionen dennoch groß, und die Säure entzieht Gewebe Wasser.",
                         "Sie ist in Wirklichkeit eine starke Säure.",
                         "Sie enthält Salzsäure."],
                answer=0,
                hints=["Stärke und Konzentration sind zwei Größen.",
                       "Auch eine schwache Säure kann konzentriert sein.",
                       "Dann sind absolut viele Ionen vorhanden."],
                solution="Schwach bedeutet: Nur ein kleiner Anteil der Moleküle gibt das Proton ab. Bei hoher Konzentration ist dieser kleine Anteil absolut trotzdem groß. Zusätzlich wirkt konzentrierte Essigsäure wasserentziehend.",
                tags=["carbonsaeuren", "sicherheit", "msa"], spiral=["W-LOES"]),
        aufgabe("OS01-C3-012", "C", 3, "choice",
                "Warum wirken organische Säuren konservierend?",
                options=["Der niedrige pH-Wert hemmt das Wachstum von Mikroorganismen.",
                         "Sie töten alle Zellen sofort ab.",
                         "Sie verschließen die Lebensmittel luftdicht."],
                answer=0,
                hints=["Was macht eine saure Umgebung mit Bakterien?",
                       "Sie hemmt ihr Wachstum.",
                       "Deshalb hält Sauerkraut länger."],
                solution="Die meisten Mikroorganismen wachsen im sauren Milieu schlecht. Deshalb halten Sauerkraut, eingelegtes Gemüse und Joghurt länger — die entstehende Milchsäure konserviert.",
                tags=["carbonsaeuren", "anwenden", "msa"], spiral=["W-LOES"]),
        aufgabe("OS01-C3-013", "C", 3, "choice",
                "Welche Gemeinsamkeit haben Essigsäure und Salzsäure trotz aller Unterschiede?",
                options=["Beide geben Protonen an Wasser ab und bilden Oxonium-Ionen.",
                         "Beide sind organisch.",
                         "Beide sind gleich stark."],
                answer=0,
                hints=["Was macht eine Lösung sauer?",
                       "Oxonium-Ionen.",
                       "Beide erzeugen sie."],
                solution="Beide sind Protonendonatoren und bilden in Wasser Oxonium-Ionen. Verschieden ist nur, wie vollständig — und die eine ist organisch, die andere nicht.",
                tags=["carbonsaeuren", "msa"], spiral=["W-GLEI"]),
        aufgabe("OS01-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Citronensäure ist natürlich, also ungefährlich.“ Wie bewertest du das?",
                options=["Der Schluss ist unzulässig — auch natürliche Säuren greifen in konzentrierter Form Haut und Zahnschmelz an.",
                         "Richtig.",
                         "Falsch — Citronensäure ist hochgiftig."],
                answer=0,
                hints=["Ist natürlich gleich harmlos?",
                       "Nein.",
                       "Auch Citronensäure greift Zahnschmelz an."],
                solution="Die Herkunft sagt nichts über die Wirkung. Konzentrierte Citronensäure reizt die Haut und greift Zahnschmelz an — deshalb die Empfehlung, nach saurem Obst nicht sofort die Zähne zu putzen. Die Menge entscheidet.",
                tags=["carbonsaeuren", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("al", AL, "Bereich AL · Einheit 7")
    schreiben("os", OS, "Bereich OS · Einheit 1")
