# -*- coding: utf-8 -*-
"""GA-05 (Abschluss Klasse 7) sowie WA-01 und WA-02 (Beginn Klasse 8)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

GA = []
WA = []

# ============================================================
# GA-05 · Anwenden & Prüfungstraining Gase
# ============================================================
GA.append({
    "unit": "GA-05",
    "title": "Anwenden & Prüfungstraining Gase",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.3", "K4.1"],
    "klasse": 7,
    "wortspeicher": ["der Nachweis", "das Gasgemisch", "die Elektronenpaarbindung", "das Treibhausgas",
                     "der Operator", "die Schlussfolgerung"],
    "worterklaerungen": {
        "Schlussfolgerung": "Der Satz, der aus einer Beobachtung das Ergebnis zieht.",
        "Operator": "Das Signalwort einer Aufgabe. Es sagt, welche Art Antwort verlangt wird."
    },
    "can_do": {
        "A": "Ich ordne Gase, Nachweise und Eigenschaften sicher einander zu.",
        "B": "Ich beantworte gemischte Aufgaben zu Gasen mit Beobachtung und Schlussfolgerung.",
        "C": "Ich erkenne an der Aufgabenstellung, welche Art von Antwort verlangt ist, und begründe fachlich."
    },
    "lernkarten": {
        "A": karte("Alles auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["Luft ist ein Gemisch.", "Jedes Gas hat einen eigenen Nachweis."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Beobachtung und Schluss trennen",
                   "In Prüfungsaufgaben zu Versuchen wird fast immer beides verlangt: was zu sehen ist und was daraus folgt. Wer nur eines schreibt, bekommt die halbe Punktzahl.",
                   ["Beobachtung: „Der Span flammt hell auf.“ — Sie enthält keine Deutung.",
                    "Schlussfolgerung: „Also ist Sauerstoff vorhanden.“ — Sie deutet die Beobachtung.",
                    "„Das Gas ist Sauerstoff“ allein ist keine Beobachtung, sondern schon das Ergebnis."],
                   "Erst schreiben, was zu sehen war. Dann, was daraus folgt.",
                   visual=anim("nachweise", "B")),
        "C": karte("Wissen verbinden",
                   "Die anspruchsvollen Aufgaben verlangen, zwei Themen zusammenzubringen — etwa Bindung und Reaktionsträgheit oder Zusammensetzung und Nachweis.",
                   ["Warum ist Stickstoff so häufig und trotzdem so reaktionsträge? Zusammensetzung der Luft plus Dreifachbindung.",
                    "Warum wird eine Kerze im Glas gelöscht, aber die Kalkwasserprobe positiv? Sauerstoffverbrauch plus Produktbildung.",
                    "Warum hilft ein Katalysator gegen Stickoxide, nicht aber gegen Kohlenstoffdioxid? Reaktionsprodukt plus Bilanz."],
                   "Die schwierigen Aufgaben verbinden zwei Stunden miteinander.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["2 H₂ + O₂ → 2 H₂O", "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O"],
                    "saetze": ["Luft: 78 % N₂, 21 % O₂, rund 1 % Rest.",
                               "Glimmspan → O₂ · Knall → H₂ · Kalkwasser trüb → CO₂.",
                               "Bindungen: H 1 · O 2 · N 3 · C 4.",
                               "Beobachtung und Schlussfolgerung immer getrennt aufschreiben."]},
    "tasks": [
        aufgabe("GA05-A1-001", "A", 1, "assign",
                "Ordne jedem Gas eine passende Aussage zu.",
                slots=["Stickstoff", "Sauerstoff", "Kohlenstoffdioxid"],
                values=["häufigstes Gas der Luft", "lässt den Glimmspan aufflammen", "trübt Kalkwasser"],
                answer=[0, 1, 2],
                hints=["Ein Gas ist am häufigsten.", "Eines hilft beim Brennen.", "Eines trübt Kalkwasser."],
                solution="Stickstoff → häufigstes Gas.\nSauerstoff → Glimmspan.\nKohlenstoffdioxid → Kalkwasser.",
                tags=["pruefung"], spiral=["W-STOF"]),
        aufgabe("GA05-A2-002", "A", 2, "choice",
                "Was ist eine Beobachtung?",
                options=["Der Span flammt hell auf.", "Das Gas ist Sauerstoff.", "Sauerstoff hilft beim Brennen."],
                answer=0, visual=anim("signalwoerter", "A"),
                hints=["Eine Beobachtung ist das, was man sieht.", "Noch ohne Deutung.", "Der Span flammt auf."],
                solution="Nur „Der Span flammt hell auf“ beschreibt, was zu sehen war. Die anderen beiden sind bereits Schlussfolgerungen.",
                misconceptions=[fv("beschreiben_statt_erklaeren", 1,
                                   "Das ist die Schlussfolgerung. Die Beobachtung ist das, was du siehst.")],
                tags=["pruefung", "operatoren"]),
        aufgabe("GA05-A3-003", "A", 3, "numeric",
                "Wie viele Liter Sauerstoff sind in 50 L Luft?",
                answer=10.5, unit_label="L", tolerance=0.5,
                hints=["21 % von 50 L.", "1 % sind 0,5 L.", "21 · 0,5 L."],
                solution="50 L · 0,21 = 10,5 L",
                tags=["pruefung", "rechnen"], spiral=["W-LOES"]),
        aufgabe("GA05-A4-004", "A", 4, "choice",
                "Ein Gas lässt einen glimmenden Span erlöschen und trübt Kalkwasser. Welches Gas ist es?",
                options=["Kohlenstoffdioxid", "Sauerstoff", "Wasserstoff"], answer=0,
                hints=["Zwei Hinweise zusammennehmen.", "Trübung heißt CO₂.", "Und CO₂ unterhält keine Verbrennung."],
                solution="Beide Befunde zusammen ergeben Kohlenstoffdioxid: Es unterhält die Verbrennung nicht und trübt Kalkwasser.",
                tags=["pruefung"], spiral=["W-GLEI"]),
        aufgabe("GA05-B1-005", "B", 1, "choice",
                "Warum bildet Stickstoff eine Dreifachbindung?",
                options=["Jedem N-Atom fehlen drei Elektronen zur vollen Schale.",
                         "Weil Stickstoff schwer ist.", "Weil Stickstoff ein Edelgas ist."],
                answer=0, visual={"type": "lewis", "molekuel": "n2", "alt": "Lewis-Formel von Stickstoff."},
                hints=["Wie viele Außenelektronen hat Stickstoff?", "Fünf.", "8 − 5 = 3."],
                solution="Stickstoff hat 5 Außenelektronen, ihm fehlen 3. Drei geteilte Elektronenpaare ergeben die Dreifachbindung.",
                tags=["pruefung", "bindung", "bbr"], spiral=["W-TEIL"]),
        aufgabe("GA05-B2-006", "B", 2, "multi",
                "In 2,5 L Luft sollen die Volumenanteile bestimmt werden.",
                fields=[
                    {"label": "Stickstoff", "answer": 1.95, "unit_label": "L", "tolerance": 0.05},
                    {"label": "Sauerstoff", "answer": 0.525, "unit_label": "L", "tolerance": 0.02}
                ],
                hints=["78 % und 21 % von 2,5 L.", "1 % sind 0,025 L.", "78 · 0,025 = 1,95 L."],
                solution="N₂: 2,5 L · 0,78 = 1,95 L\nO₂: 2,5 L · 0,21 = 0,525 L",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("GA05-B2-007", "B", 2, "choice",
                "Eine Kerze brennt in einem Glas und erlischt. Danach trübt das Gas im Glas Kalkwasser. Was folgt daraus?",
                options=["Der Sauerstoff wurde verbraucht und dabei Kohlenstoffdioxid gebildet.",
                         "Im Glas war von Anfang an Kohlenstoffdioxid.",
                         "Das Kalkwasser war verunreinigt."],
                answer=0,
                hints=["Was passiert beim Verbrennen von Wachs?",
                       "Sauerstoff wird verbraucht, CO₂ entsteht.",
                       "Beide Befunde passen zusammen."],
                solution="Die Flamme verbraucht den Sauerstoff und erlischt. Das dabei entstandene Kohlenstoffdioxid trübt anschließend das Kalkwasser. Beide Beobachtungen zusammen belegen die Reaktion.",
                tags=["pruefung", "bbr"], spiral=["W-GLEI"]),
        aufgabe("GA05-B3-008", "B", 3, "choice",
                "Welche Antwort auf „Beschreibe die Knallgasprobe“ ist vollständig?",
                options=["Das aufgefangene Gas wird an der Öffnung des Reagenzglases entzündet; es ertönt ein pfeifender Knall.",
                         "Es knallt.",
                         "Wasserstoff ist vorhanden."],
                answer=0,
                hints=["„Beschreibe“ verlangt Durchführung und Beobachtung.",
                       "Nicht nur das Ergebnis.",
                       "Und in ganzen Sätzen."],
                solution="„Beschreibe“ verlangt Durchführung und Beobachtung in ganzen Sätzen. Antwort 2 ist unvollständig, Antwort 3 ist bereits die Schlussfolgerung.",
                misconceptions=[fv("beschreiben_statt_erklaeren", 2,
                                   "Das ist die Schlussfolgerung, nicht die Beschreibung.")],
                tags=["pruefung", "operatoren", "bbr"]),
        aufgabe("GA05-B3-009", "B", 3, "numeric",
                "Wie viele bindende Elektronenpaare hat ein Ammoniakmolekül NH₃?",
                answer=3, tolerance=0,
                visual={"type": "lewis", "molekuel": "nh3", "alt": "Lewis-Formel von Ammoniak."},
                hints=["Wie viele Bindungen bildet Stickstoff?", "Drei.", "Also drei bindende Paare."],
                solution="Stickstoff bildet drei Bindungen zu je einem Wasserstoffatom: drei bindende Elektronenpaare. Dazu kommt ein freies Elektronenpaar am Stickstoff.",
                tags=["pruefung", "bindung", "bbr"], spiral=["W-SYMB"]),
        aufgabe("GA05-B4-010", "B", 4, "choice",
                "Warum ist Luft trotz 78 % Stickstoff atembar?",
                options=["Stickstoff ist reaktionsträge und stört nicht; die 21 % Sauerstoff genügen.",
                         "Der Körper nutzt auch den Stickstoff.",
                         "Beim Einatmen wird Stickstoff herausgefiltert."],
                answer=0,
                hints=["Was macht der Körper mit dem Stickstoff?",
                       "Nichts — er wird wieder ausgeatmet.",
                       "Gebraucht wird nur der Sauerstoff."],
                solution="Stickstoff wird unverändert wieder ausgeatmet, er ist reaktionsträge. Die 21 % Sauerstoff genügen für die Atmung — reiner Sauerstoff wäre über längere Zeit sogar schädlich.",
                tags=["pruefung", "msa"], spiral=["W-STOF"]),
        aufgabe("GA05-C2-011", "C", 2, "choice",
                "Ein unbekanntes Gas löscht einen Span und trübt Kalkwasser nicht. Was könnte es sein?",
                options=["Stickstoff oder ein Edelgas", "Sauerstoff", "Kohlenstoffdioxid"], answer=0,
                hints=["Löschen heißt: unterhält keine Verbrennung.",
                       "Keine Trübung heißt: kein CO₂.",
                       "Übrig bleiben träge Gase."],
                solution="Der Span erlischt — also kein Sauerstoff. Das Kalkwasser bleibt klar — also kein Kohlenstoffdioxid. Übrig bleiben Stickstoff und die Edelgase; für eine weitere Unterscheidung braucht es andere Verfahren.",
                tags=["pruefung", "msa"], spiral=["W-GLEI"]),
        aufgabe("GA05-C3-012", "C", 3, "multi",
                "In einem abgeschlossenen Volumen von 400 mL Luft verbrennt Eisenwolle. Danach sind 318 mL Gas übrig.",
                fields=[
                    {"label": "verbrauchtes Sauerstoffvolumen", "answer": 82, "unit_label": "mL", "tolerance": 1},
                    {"label": "gemessener Sauerstoffanteil in Prozent", "answer": 20.5, "unit_label": "%", "tolerance": 0.3},
                    {"label": "Abweichung vom Literaturwert 21 %, in Prozentpunkten", "answer": 0.5, "tolerance": 0.3}
                ],
                hints=["400 − 318 = 82 mL.",
                       "82 : 400 · 100 %.",
                       "21 − 20,5 = 0,5 Prozentpunkte."],
                solution="verbraucht: 400 − 318 = 82 mL\nAnteil: 82 : 400 = 20,5 %\nAbweichung: 21 − 20,5 = 0,5 Prozentpunkte — sehr gutes Ergebnis.",
                tags=["pruefung", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("GA05-C3-013", "C", 3, "choice",
                "Warum ist der Satz „Kohlenstoffdioxid ist ein Giftgas“ fachlich unpräzise?",
                options=["CO₂ wirkt erst in hoher Konzentration erstickend; die Wirkung hängt von der Menge ab.",
                         "CO₂ ist völlig harmlos.",
                         "CO₂ ist tatsächlich ein Giftgas."],
                answer=0,
                hints=["Wie viel CO₂ ist in der Atemluft?",
                       "0,04 % — und ausgeatmet rund 4 %.",
                       "Die Wirkung hängt von der Konzentration ab."],
                solution="Kohlenstoffdioxid ist in der Atemluft ständig vorhanden und wirkt erst in hoher Konzentration erstickend — nicht durch chemische Giftwirkung, sondern durch Verdrängung des Sauerstoffs. Ohne Angabe der Konzentration ist die Aussage nicht bewertbar.",
                tags=["pruefung", "bewerten", "msa"]),
        aufgabe("GA05-C4-014", "C", 4, "choice",
                "Eine Prüfungsaufgabe lautet: „Erkläre, warum die Zusammensetzung der Luft weitgehend konstant bleibt.“ Welche Antwort trägt am weitesten?",
                options=["Verbrauch und Nachlieferung stehen im Gleichgewicht: Pflanzen setzen Sauerstoff frei, Atmung und Verbrennung verbrauchen ihn.",
                         "Weil Luft ein Gemisch ist.",
                         "Weil Stickstoff nicht reagiert."],
                answer=0,
                hints=["Warum bleibt der Sauerstoffanteil trotz ständigen Verbrauchs gleich?",
                       "Weil er nachgeliefert wird.",
                       "Es ist ein Gleichgewicht."],
                solution="„Erkläre“ verlangt eine Ursache. Antwort 2 ist eine Einordnung, Antwort 3 erklärt nur einen Bestandteil. Nur Antwort 1 nennt den Grund: ein Gleichgewicht zwischen Verbrauch und Nachlieferung.",
                tags=["pruefung", "operatoren", "msa"])
    ]
})

# ============================================================
# WA-01 · Eigenschaften des Wassers
# ============================================================
WA.append({
    "unit": "WA-01",
    "title": "Eigenschaften des Wassers",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K2.4"],
    "klasse": 8,
    "wortspeicher": ["die Dichteanomalie", "die Oberflächenspannung", "die Siedetemperatur",
                     "die Schmelztemperatur", "das Lösungsmittel", "die Wärmekapazität"],
    "worterklaerungen": {
        "Dichteanomalie": "Wasser hat bei 4 °C die größte Dichte. Eis ist leichter als Wasser.",
        "Oberflächenspannung": "Die Wasseroberfläche verhält sich wie eine dünne Haut.",
        "Wärmekapazität": "Wie viel Energie nötig ist, um einen Stoff zu erwärmen."
    },
    "can_do": {
        "A": "Ich nenne Schmelz- und Siedetemperatur von Wasser und weiß, dass Eis schwimmt.",
        "B": "Ich beschreibe Dichteanomalie und Oberflächenspannung und nenne Beispiele aus der Natur.",
        "C": "Ich erkläre die Besonderheiten des Wassers als Folge seines Molekülbaus."
    },
    "lernkarten": {
        "A": karte("Wasser ist besonders",
                   "Wasser verhält sich anders als die meisten Stoffe.",
                   ["Eis schwimmt oben.", "Wasser siedet bei 100 °C und schmilzt bei 0 °C."],
                   "Eis ist leichter als Wasser. Das ist ungewöhnlich.",
                   visual={"type": "diagramm", "titel": "Dichte des Wassers",
                           "xtitel": "Temperatur in °C", "ytitel": "Dichte in g/cm³",
                           "punkte": [[0, 0.9998], [2, 0.99994], [4, 1.0], [8, 0.9999], [20, 0.9982], [40, 0.9922]],
                           "ymin": 0.99, "ymax": 1.001,
                           "alt": "Die Dichte des Wassers hat bei 4 °C ihr Maximum."},
                   beispiel={"titel": "Der See im Winter", "aufgabe": "Warum friert ein See nicht durch?",
                             "schritte": ["Eis ist leichter als Wasser.", "Es schwimmt oben.",
                                          "Darunter bleibt es flüssig."],
                             "ergebnis": "Fische überleben unter der Eisdecke."}),
        "B": karte("Zwei auffällige Eigenschaften",
                   "Wasser weicht bei mehreren Eigenschaften vom Erwarteten ab — und ausgerechnet diese Abweichungen machen Leben möglich.",
                   ["Dichteanomalie: Die größte Dichte hat Wasser bei 4 °C, nicht am Gefrierpunkt. Eis ist deshalb leichter und schwimmt. Seen frieren von oben zu.",
                    "Oberflächenspannung: Die Oberfläche zieht sich zusammen wie eine Haut. Wasserläufer laufen darauf, Tropfen werden rund.",
                    "Hohe Wärmekapazität: Wasser speichert viel Energie. Deshalb wirken Meere ausgleichend auf das Klima.",
                    "Vergleichbar gebaute Stoffe wie Schwefelwasserstoff sieden bei −60 °C. Wasser siedet erst bei 100 °C."],
                   "Die Besonderheiten des Wassers sind kein Zufall — sie haben eine gemeinsame Ursache.",
                   visual={"type": "diagramm", "titel": "Siedetemperaturen im Vergleich",
                           "xtitel": "Molekülmasse", "ytitel": "Siedetemperatur in °C",
                           "punkte": [[18, 100, "H₂O"], [34, -60, "H₂S"], [81, -42, "H₂Se"]],
                           "ymin": -100, "ymax": 120,
                           "alt": "Wasser siedet trotz kleinster Molekülmasse am höchsten."}),
        "C": karte("Alles folgt aus dem Bau",
                   "Alle Besonderheiten des Wassers lassen sich auf eine einzige Ursache zurückführen: den gewinkelten Bau des Moleküls und die daraus folgenden Anziehungskräfte zwischen den Molekülen.",
                   ["Das Wassermolekül ist gewinkelt und trägt Teilladungen. Zwischen den Molekülen wirken deshalb starke Anziehungskräfte — Wasserstoffbrücken.",
                    "Diese Kräfte müssen beim Sieden überwunden werden. Deshalb siedet Wasser erst bei 100 °C, obwohl seine Moleküle sehr leicht sind.",
                    "Im Eis ordnen sich die Moleküle so an, dass zwischen ihnen mehr Platz bleibt als im flüssigen Zustand. Genau daher die geringere Dichte.",
                    "Die Oberflächenspannung entsteht, weil Moleküle an der Oberfläche nur nach innen Partner haben und deshalb nach innen gezogen werden."],
                   "Gewinkelter Bau → Teilladungen → starke Anziehung zwischen den Molekülen → alle Besonderheiten.",
                   visual={"type": "lewis", "molekuel": "h2o", "formel": "H2O",
                           "alt": "Lewis-Formel des gewinkelten Wassermoleküls."})
    },
    "formelkarte": {"formeln": ["ρ = m : V"],
                    "saetze": ["Wasser: Schmelztemperatur 0 °C, Siedetemperatur 100 °C.",
                               "Größte Dichte bei 4 °C: 1,000 g/cm³.",
                               "Eis: 0,92 g/cm³ — deshalb schwimmt es.",
                               "Ursache aller Besonderheiten: der gewinkelte Molekülbau."]},
    "tasks": [
        aufgabe("WA01-A1-001", "A", 1, "numeric",
                "Bei welcher Temperatur siedet Wasser?",
                answer=100, unit_label="°C", tolerance=0,
                hints=["Bei normalem Luftdruck.", "Es ist eine glatte Zahl.", "100 °C."],
                solution="Wasser siedet bei normalem Luftdruck bei 100 °C.",
                tags=["wasser"], spiral=["W-STOF"]),
        aufgabe("WA01-A2-002", "A", 2, "choice",
                "Was ist ungewöhnlich an Eis?",
                options=["Es schwimmt auf Wasser.", "Es ist kalt.", "Es ist durchsichtig."],
                answer=0,
                hints=["Bei den meisten Stoffen sinkt der feste Zustand nach unten.",
                       "Bei Wasser nicht.",
                       "Eis schwimmt."],
                solution="Bei fast allen Stoffen ist die feste Form dichter und sinkt. Eis ist leichter als Wasser und schwimmt — das ist die Dichteanomalie.",
                tags=["wasser"], spiral=["W-STOF"]),
        aufgabe("WA01-A3-003", "A", 3, "numeric",
                "Wie viel Gramm wiegen 250 mL Wasser? (Dichte 1,0 g/cm³)",
                answer=250, unit_label="g", tolerance=1,
                hints=["1 mL entspricht 1 cm³.", "m = ρ · V.", "1,0 · 250."],
                solution="m = 1,0 g/cm³ · 250 cm³ = 250 g",
                tags=["wasser", "rechnen"], spiral=["W-STOF", "W-EINH"]),
        aufgabe("WA01-A4-004", "A", 4, "choice",
                "Warum können Wasserläufer auf dem Wasser laufen?",
                options=["Die Oberfläche wirkt wie eine dünne Haut.", "Sie sind sehr schnell.", "Sie schwimmen."],
                answer=0,
                hints=["Die Wasseroberfläche hält etwas aus.", "Sie verhält sich wie eine Haut.", "Das heißt Oberflächenspannung."],
                solution="Die Oberflächenspannung lässt die Wasseroberfläche wie eine dünne Haut wirken. Leichte Tiere sinken deshalb nicht ein.",
                tags=["wasser"], spiral=["W-STOF"]),
        aufgabe("WA01-B1-005", "B", 1, "choice",
                "Bei welcher Temperatur hat Wasser die größte Dichte?",
                options=["bei 4 °C", "bei 0 °C", "bei 100 °C"], answer=0,
                visual={"type": "diagramm", "xtitel": "Temperatur in °C", "ytitel": "Dichte in g/cm³",
                        "punkte": [[0, 0.9998], [4, 1.0], [20, 0.9982], [40, 0.9922]],
                        "ymin": 0.99, "ymax": 1.001,
                        "alt": "Dichtemaximum des Wassers bei 4 °C."},
                hints=["Sieh dir den Hochpunkt der Kurve an.", "Er liegt nicht bei 0 °C.", "Bei 4 °C."],
                solution="Wasser hat bei 4 °C seine größte Dichte. Darüber und darunter ist es leichter — das ist die Dichteanomalie.",
                misconceptions=[fv("dichtemaximum_bei_null", 1,
                                   "Bei 0 °C ist Wasser bereits wieder leichter. Das Maximum liegt bei 4 °C.")],
                tags=["wasser", "bbr"], spiral=["W-STOF"]),
        aufgabe("WA01-B2-006", "B", 2, "choice",
                "Welche Folge hat die Dichteanomalie für einen See im Winter?",
                options=["Er friert von oben zu; unter dem Eis bleibt Wasser bei 4 °C flüssig.",
                         "Er friert von unten zu.",
                         "Er friert vollständig durch."],
                answer=0,
                hints=["Wo sammelt sich das kälteste Wasser?",
                       "Oben, weil es leichter ist.",
                       "Das dichteste Wasser mit 4 °C sinkt nach unten."],
                solution="Wasser von 4 °C ist am dichtesten und sinkt nach unten. Kälteres Wasser und Eis bleiben oben. Die Eisdecke isoliert, darunter überleben Fische bei 4 °C.",
                tags=["wasser", "bbr"], spiral=["W-STOF"]),
        aufgabe("WA01-B2-007", "B", 2, "numeric",
                "Eis hat die Dichte 0,92 g/cm³. Welches Volumen nehmen 460 g Eis ein?",
                answer=500, unit_label="cm³", tolerance=2,
                hints=["V = m : ρ.", "460 : 0,92.", "500 cm³."],
                solution="V = 460 g : 0,92 g/cm³ = 500 cm³. Dieselbe Masse Wasser nähme nur 460 cm³ ein — Eis dehnt sich aus.",
                misconceptions=[fv("dichte_mal_statt_geteilt", 423.2,
                                   "Du hast multipliziert. V = m : ρ.")],
                tags=["wasser", "rechnen", "bbr"], spiral=["W-STOF"]),
        aufgabe("WA01-B3-008", "B", 3, "choice",
                "Warum platzen Wasserleitungen bei Frost?",
                options=["Wasser dehnt sich beim Gefrieren aus und sprengt das Rohr.",
                         "Das Metall zieht sich zusammen und reißt.",
                         "Das Eis ist schwerer als Wasser."],
                answer=0,
                hints=["Was passiert mit dem Volumen beim Gefrieren?",
                       "Es nimmt zu.",
                       "Im geschlossenen Rohr entsteht dabei großer Druck."],
                solution="Beim Gefrieren nimmt das Volumen um rund 9 % zu. Im geschlossenen Rohr entsteht dabei ein Druck, dem das Material nicht standhält.",
                misconceptions=[fv("eis_schwerer", 2,
                                   "Eis ist leichter als Wasser — deshalb schwimmt es. Zum Platzen führt die Volumenzunahme.")],
                tags=["wasser", "anwenden", "bbr"], spiral=["W-STOF"]),
        aufgabe("WA01-B3-009", "B", 3, "choice",
                "Warum ist es an der Küste im Sommer kühler und im Winter milder als im Landesinneren?",
                options=["Wasser hat eine hohe Wärmekapazität und wirkt dadurch ausgleichend.",
                         "Am Meer weht immer Wind.",
                         "Salzwasser ist wärmer als Süßwasser."],
                answer=0,
                hints=["Wie schnell erwärmt sich Wasser?",
                       "Langsam — und es kühlt langsam ab.",
                       "Das wirkt ausgleichend."],
                solution="Wasser nimmt sehr viel Energie auf, ohne sich stark zu erwärmen, und gibt sie langsam wieder ab. Große Wassermengen dämpfen deshalb Temperaturschwankungen.",
                tags=["wasser", "anwenden", "msa"], spiral=["W-STOF"]),
        aufgabe("WA01-B4-010", "B", 4, "choice",
                "Schwefelwasserstoff H₂S ist ähnlich gebaut wie Wasser, siedet aber bei −60 °C. Was folgt daraus?",
                options=["Zwischen Wassermolekülen wirken besonders starke Anziehungskräfte.",
                         "Wasser ist schwerer als Schwefelwasserstoff.",
                         "Die Messung muss falsch sein."],
                answer=0,
                hints=["H₂S-Moleküle sind sogar schwerer als Wassermoleküle.",
                       "Trotzdem siedet H₂S viel früher.",
                       "Also müssen bei Wasser stärkere Kräfte wirken."],
                solution="H₂S ist schwerer und müsste eigentlich später sieden. Dass Wasser erst bei 100 °C siedet, zeigt: Zwischen Wassermolekülen wirken besonders starke Anziehungskräfte, die erst überwunden werden müssen.",
                tags=["wasser", "msa"], spiral=["W-STOF"]),
        aufgabe("WA01-C2-011", "C", 2, "choice",
                "Warum ist Eis weniger dicht als flüssiges Wasser?",
                options=["Im Eiskristall ordnen sich die Moleküle mit größeren Abständen an.",
                         "Die Moleküle werden beim Gefrieren kleiner.",
                         "Im Eis sind weniger Moleküle."],
                answer=0,
                hints=["Was ändert sich beim Gefrieren?",
                       "Die Anordnung.",
                       "Sie wird regelmäßiger — und lockerer."],
                solution="Im Eis ordnen sich die Moleküle zu einem regelmäßigen Gitter mit größeren Zwischenräumen als im flüssigen Zustand. Dieselbe Zahl Moleküle nimmt deshalb mehr Raum ein — die Dichte sinkt.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Die Moleküle selbst ändern sich nicht. Nur ihre Anordnung wird lockerer.",
                                   "teilchen_traegt_stoffeigenschaft", 2)],
                tags=["wasser", "erklaeren", "msa"], spiral=["W-STOF"]),
        aufgabe("WA01-C3-012", "C", 3, "multi",
                "500 g Wasser gefrieren zu Eis (Dichte 0,92 g/cm³).",
                fields=[
                    {"label": "Volumen als Wasser", "answer": 500, "unit_label": "cm³", "tolerance": 2},
                    {"label": "Volumen als Eis", "answer": 543.5, "unit_label": "cm³", "tolerance": 3},
                    {"label": "Volumenzunahme in Prozent", "answer": 8.7, "unit_label": "%", "tolerance": 0.5}
                ],
                hints=["Wasser: 1,0 g/cm³.",
                       "Eis: 500 : 0,92.",
                       "Zunahme = (543,5 − 500) : 500 · 100 %."],
                solution="Wasser: 500 g : 1,0 = 500 cm³\nEis: 500 g : 0,92 = 543,5 cm³\nZunahme: 43,5 : 500 = 8,7 %",
                tags=["wasser", "rechnen", "msa"], spiral=["W-STOF"]),
        aufgabe("WA01-C3-013", "C", 3, "choice",
                "Ein Eiswürfel schwimmt in einem randvollen Glas Wasser. Was passiert beim Schmelzen?",
                options=["Das Glas läuft nicht über — das Schmelzwasser nimmt genau das verdrängte Volumen ein.",
                         "Das Glas läuft über.",
                         "Der Wasserspiegel sinkt deutlich."],
                answer=0,
                hints=["Wie viel Wasser verdrängt der schwimmende Würfel?",
                       "Genau so viel, wie er wiegt.",
                       "Und beim Schmelzen entsteht genau diese Masse Wasser."],
                solution="Ein schwimmender Körper verdrängt so viel Wasser, wie er selbst wiegt. Beim Schmelzen entsteht genau diese Masse Wasser — sie füllt exakt den verdrängten Raum. Der Spiegel bleibt gleich.",
                tags=["wasser", "transfer", "msa"], spiral=["W-STOF"]),
        aufgabe("WA01-C4-014", "C", 4, "choice",
                "Welche Aussage verbindet die Besonderheiten des Wassers am besten?",
                options=["Sie folgen alle aus dem gewinkelten Molekülbau und den daraus entstehenden Anziehungskräften.",
                         "Sie sind voneinander unabhängige Zufälle.",
                         "Sie folgen aus der geringen Molekülmasse."],
                answer=0,
                hints=["Gibt es eine gemeinsame Ursache?",
                       "Ja — den Bau des Moleküls.",
                       "Daraus folgen die Anziehungskräfte."],
                solution="Hohe Siedetemperatur, Dichteanomalie, Oberflächenspannung und hohe Wärmekapazität haben dieselbe Ursache: den gewinkelten Bau mit Teilladungen und die daraus folgenden starken Anziehungskräfte zwischen den Molekülen. Die geringe Masse spricht sogar dagegen — und macht den Befund erst auffällig.",
                tags=["wasser", "bewerten", "msa"], spiral=["W-STOF"])
    ]
})

if __name__ == "__main__":
    schreiben("ga", GA, "Bereich GA · Einheit 5")
    schreiben("wa", WA, "Bereich WA · Einheit 1")
