# -*- coding: utf-8 -*-
"""ME-07 (Abschluss Metalle) sowie QB-01 und QB-02 (Beginn Klasse 9)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

ME = []
QB = []

ME.append({
    "unit": "ME-07",
    "title": "Anwenden & Prüfungstraining Metalle",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 8,
    "wortspeicher": ["die Redoxreihe", "die Metallbindung", "die Legierung", "die Reduktion",
                     "die Korrosion", "die Bewertung"],
    "worterklaerungen": {
        "Bewertung": "Ein Urteil, das ein Kriterium nennt und begründet."
    },
    "can_do": {
        "A": "Ich beantworte gemischte Aufgaben zu Metallen sicher.",
        "B": "Ich verbinde Bindungsmodell, Eigenschaften und Reaktionen der Metalle.",
        "C": "Ich bewerte Materialwahl, Korrosionsschutz und Verhüttungsverfahren begründet."
    },
    "lernkarten": {
        "A": karte("Metalle auf einen Blick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["Metalle leiten und sind verformbar.", "Unedle Metalle reagieren leicht."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen.",
                   ["Bindung: positive Rümpfe im Elektronengas — daraus folgen Leitfähigkeit, Glanz und Verformbarkeit.",
                    "Reaktivität: die Redoxreihe sagt vorher, welche Reaktion abläuft und welcher Korrosionsschutz wirkt.",
                    "Gewinnung: Erze enthalten Metalloxide; die Reduktion entzieht den Sauerstoff."],
                   "Bindung erklärt Eigenschaften, Redoxreihe erklärt Reaktionen.",
                   visual=anim("elektronengas", "B")),
        "C": karte("Bewerten mit Kriterium",
                   "Bei Metallen wird häufig bewertet: Welches Material, welcher Schutz, welches Verfahren? Ohne Kriterium ist jede Antwort beliebig.",
                   ["Materialwahl: Welche Eigenschaft entscheidet für diesen Zweck? Dichte, Leitfähigkeit, Härte oder Beständigkeit?",
                    "Korrosionsschutz: Wirkt er auch bei Beschädigung? Nur ein unedleres Metall tut das.",
                    "Verfahren: Welche Stoffe und welche Energie werden gebraucht, und was entsteht dabei?",
                    "Eine gute Bewertung nennt zuerst das Kriterium, wendet es an und urteilt dann."],
                   "Kriterium nennen, anwenden, urteilen — in dieser Reihenfolge.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["Fe + Cu²⁺ → Fe²⁺ + Cu", "Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂"],
                    "saetze": ["Redoxreihe: K · Ca · Na · Mg · Al · Zn · Fe · Pb · Cu · Ag · Au.",
                               "Metallgitter: positive Rümpfe im Elektronengas.",
                               "Oxidation = Elektronenabgabe, Reduktion = Elektronenaufnahme.",
                               "Opferanode: ein unedleres Metall schützt das edlere."]},
    "tasks": [
        aufgabe("ME07-A1-001", "A", 1, "choice",
                "Welche Eigenschaft haben alle Metalle?",
                options=["Sie leiten Strom und Wärme.", "Sie sind alle magnetisch.", "Sie sind alle silbrig."],
                answer=0,
                hints=["Nur wenige Metalle sind magnetisch.", "Die Farben sind verschieden.", "Aber alle leiten."],
                solution="Alle Metalle leiten Strom und Wärme. Magnetisch sind nur Eisen, Cobalt und Nickel.",
                tags=["pruefung"], spiral=["W-STOF"]),
        aufgabe("ME07-A2-002", "A", 2, "choice",
                "Welches Metall ist unedler: Zink oder Kupfer?",
                options=["Zink", "Kupfer", "beide gleich"], answer=0,
                hints=["In der Redoxreihe steht das unedlere links.", "Zink steht links von Kupfer.", "Zink."],
                solution="Zink steht in der Redoxreihe links von Kupfer und ist damit unedler.",
                tags=["pruefung"], spiral=["W-GLEI"]),
        aufgabe("ME07-A3-003", "A", 3, "numeric",
                "Messing enthält 63 % Kupfer. Wie viel Kupfer stecken in 400 g?",
                answer=252, unit_label="g", tolerance=2,
                hints=["63 % von 400 g.", "1 % sind 4 g.", "63 · 4 g."],
                solution="400 g · 0,63 = 252 g Kupfer",
                tags=["pruefung", "rechnen"], spiral=["W-LOES"]),
        aufgabe("ME07-A4-004", "A", 4, "choice",
                "Was passiert mit einem Zinkblech in Kupfersulfatlösung?",
                options=["Es überzieht sich mit Kupfer.", "Nichts.", "Es löst sich vollständig auf."],
                answer=0, visual=anim("redox", "A"),
                hints=["Zink ist unedler.", "Das unedlere gibt Elektronen ab.", "Das Kupfer scheidet sich ab."],
                solution="Zink ist unedler und gibt Elektronen ab. Die Kupfer-Ionen nehmen sie auf und scheiden sich als Kupfer ab.",
                tags=["pruefung"], spiral=["W-GLEI"]),
        aufgabe("ME07-B1-005", "B", 1, "choice",
                "Warum ist ein Metall verformbar, ein Salz aber spröde?",
                options=["Im Metall hält das Elektronengas die verschobenen Schichten weiter zusammen.",
                         "Metalle sind weicher.", "Salze enthalten keine Ladungen."],
                answer=0,
                hints=["Was liegt im Metall zwischen den Rümpfen?",
                       "Das Elektronengas.",
                       "Es ist überall gleich."],
                solution="Nach dem Verschieben liegen im Metall wieder Rümpfe im Elektronengas — die Bindung hält. Im Ionengitter treffen dagegen gleiche Ladungen aufeinander und stoßen sich ab.",
                tags=["pruefung", "bbr"], spiral=["W-TEIL"]),
        aufgabe("ME07-B2-006", "B", 2, "choice",
                "Welche Aussage über die Reaktion Fe + Cu²⁺ → Fe²⁺ + Cu ist richtig?",
                options=["Eisen wird oxidiert, Kupfer reduziert.",
                         "Eisen wird reduziert, Kupfer oxidiert.",
                         "Beide werden oxidiert."],
                answer=0,
                hints=["Wer gibt Elektronen ab?",
                       "Das Eisen.",
                       "Abgeben ist Oxidation."],
                solution="Eisen gibt zwei Elektronen ab und wird oxidiert. Das Kupfer-Ion nimmt sie auf und wird reduziert.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Abgabe von Elektronen ist Oxidation. Das Eisen gibt ab.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["pruefung", "redox", "bbr"], spiral=["W-GLEI"]),
        aufgabe("ME07-B2-007", "B", 2, "choice",
                "Warum schützt Zink verletztes Eisenblech, Zinn aber nicht?",
                options=["Zink ist unedler als Eisen, Zinn edler.",
                         "Zink ist härter.", "Zinn löst sich in Wasser."],
                answer=0,
                hints=["Sieh in der Redoxreihe nach.",
                       "Zink steht links von Eisen, Zinn rechts.",
                       "Nur das unedlere opfert sich."],
                solution="Zink steht links von Eisen und gibt bevorzugt Elektronen ab — es schützt auch an einer Kratzstelle. Zinn ist edler; dort opfert sich das Eisen.",
                tags=["pruefung", "korrosion", "bbr"], spiral=["W-GLEI"]),
        aufgabe("ME07-B3-008", "B", 3, "multi",
                "Ein Bauteil aus Eisen (7,9 g/cm³) mit 250 cm³ soll durch Aluminium (2,7 g/cm³) ersetzt werden.",
                fields=[
                    {"label": "Masse aus Eisen", "answer": 1975, "unit_label": "g", "tolerance": 10},
                    {"label": "Masse aus Aluminium", "answer": 675, "unit_label": "g", "tolerance": 10},
                    {"label": "Gewichtsersparnis in Prozent", "answer": 65.8, "unit_label": "%", "tolerance": 1}
                ],
                hints=["m = ρ · V für beide.",
                       "7,9 · 250 und 2,7 · 250.",
                       "Ersparnis = (1975 − 675) : 1975 · 100 %."],
                solution="Fe: 1975 g · Al: 675 g\nErsparnis: 1300 : 1975 = 0,658 → 65,8 %",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-STOF"]),
        aufgabe("ME07-B3-009", "B", 3, "choice",
                "Welche Antwort auf „Erkläre, warum Metalle den Strom leiten“ ist vollständig?",
                options=["Im Metallgitter sind die Außenelektronen nicht an einzelne Atome gebunden, sondern frei beweglich; sie transportieren die Ladung.",
                         "Weil Metalle Elektronen haben.",
                         "Weil Metalle glänzen."],
                answer=0,
                hints=["Elektronen haben alle Stoffe.",
                       "Entscheidend ist die Beweglichkeit.",
                       "Und die kommt vom Elektronengas."],
                solution="Elektronen besitzt jeder Stoff. Entscheidend ist, dass sie im Metall frei beweglich sind. Antwort 2 greift zu kurz, Antwort 3 nennt eine andere Eigenschaft.",
                tags=["pruefung", "operatoren", "bbr"], spiral=["W-TEIL"]),
        aufgabe("ME07-B4-010", "B", 4, "choice",
                "Warum liegt Eisen in der Natur als Erz vor, Gold aber als Metall?",
                options=["Eisen ist unedel und reagiert mit Sauerstoff; Gold ist so edel, dass es kaum Verbindungen bildet.",
                         "Gold ist seltener.", "Eisen wird von Bakterien zersetzt."],
                answer=0,
                hints=["Wie reagieren unedle Metalle über lange Zeit?",
                       "Sie verbinden sich mit Sauerstoff.",
                       "Gold tut das nicht."],
                solution="Unedle Metalle reagieren über geologische Zeiträume vollständig zu Oxiden. Gold ist so edel, dass es gediegen vorkommt — deshalb war es früher bekannt als Eisen.",
                tags=["pruefung", "msa"], spiral=["W-GLEI"]),
        aufgabe("ME07-C2-011", "C", 2, "choice",
                "Welche Begründung für die Wahl von Aluminium im Flugzeugbau ist vollständig?",
                options=["Geringe Dichte spart Gewicht, die Legierung liefert ausreichende Festigkeit, die Oxidschicht schützt vor Korrosion.",
                         "Aluminium ist billig.",
                         "Aluminium leitet gut."],
                answer=0,
                hints=["Welche Eigenschaften braucht ein Flugzeug?",
                       "Leicht, fest, beständig.",
                       "Leitfähigkeit ist hier kein Kriterium."],
                solution="Eine vollständige Begründung nennt alle für den Zweck entscheidenden Eigenschaften. Leitfähigkeit spielt im Flugzeugbau keine Rolle, der Preis ist nachrangig.",
                tags=["pruefung", "bewerten", "msa"]),
        aufgabe("ME07-C3-012", "C", 3, "multi",
                "Aus 2000 kg Erz mit 65 % Fe₂O₃ (davon 70 % Eisen) wird Roheisen gewonnen. Je Tonne Roheisen entstehen 1,8 t CO₂.",
                fields=[
                    {"label": "Masse des Eisenoxids", "answer": 1300, "unit_label": "kg", "tolerance": 10},
                    {"label": "gewinnbare Eisenmasse", "answer": 910, "unit_label": "kg", "tolerance": 10},
                    {"label": "entstehendes CO₂", "answer": 1638, "unit_label": "kg", "tolerance": 20}
                ],
                hints=["2000 · 0,65.",
                       "1300 · 0,70.",
                       "0,91 t · 1,8 t/t = 1,638 t."],
                solution="Fe₂O₃: 2000 · 0,65 = 1300 kg\nFe: 1300 · 0,70 = 910 kg = 0,91 t\nCO₂: 0,91 · 1,8 = 1,638 t = 1638 kg",
                tags=["pruefung", "rechnen", "msa"], spiral=["W-RECH"]),
        aufgabe("ME07-C3-013", "C", 3, "choice",
                "Ein Schüler will zwei Metalle elektrisch verbinden, die im Freien liegen. Worauf muss er achten?",
                options=["Bei Kontakt zweier verschieden edler Metalle korrodiert das unedlere beschleunigt.",
                         "Die Metalle müssen gleich schwer sein.",
                         "Es passiert nichts Besonderes."],
                answer=0,
                hints=["Was passiert bei Kontakt zweier Metalle in feuchter Umgebung?",
                       "Ein Elektronenübergang.",
                       "Das unedlere gibt ab."],
                solution="Berühren sich zwei verschieden edle Metalle in feuchter Umgebung, gibt das unedlere bevorzugt Elektronen ab und korrodiert schneller als allein. Deshalb werden solche Kombinationen im Bauwesen vermieden oder isoliert.",
                tags=["pruefung", "bewerten", "msa"], spiral=["W-GLEI"]),
        aufgabe("ME07-C4-014", "C", 4, "choice",
                "Bewerte: „Recycling von Metallen ist immer besser als Neugewinnung.“",
                options=["Meist ja, weil der Energiebedarf weit geringer ist — Legierungen erfordern aber sortenreine Sammlung, sonst sinkt die Qualität.",
                         "Uneingeschränkt richtig.",
                         "Falsch, Recycling lohnt sich nie."],
                answer=0,
                hints=["Was spricht klar für Recycling?",
                       "Der geringere Energiebedarf.",
                       "Was ist die Einschränkung?"],
                solution="Der Energievorteil ist erheblich — bei Aluminium rund 95 %. Die Einschränkung liegt in der Sortenreinheit: Vermischte Legierungen ergeben Material minderer Qualität. Eine differenzierte Bewertung nennt beides.",
                tags=["pruefung", "bewerten", "msa"])
    ]
})

# ============================================================
# QB-01 · Atommasse, Molekülmasse, molare Masse
# ============================================================
QB.append({
    "unit": "QB-01",
    "title": "Atommasse, Molekülmasse, molare Masse",
    "leitidee": "B1",
    "standards": ["K1", "K2.4"],
    "klasse": 9,
    "wortspeicher": ["die Atommasse", "die Molekülmasse", "die molare Masse", "die Formeleinheit",
                     "die Einheit g/mol"],
    "worterklaerungen": {
        "molare Masse": "Die Masse von einem Mol eines Stoffes, angegeben in g/mol.",
        "Molekülmasse": "Die Summe der Atommassen aller Atome eines Moleküls."
    },
    "can_do": {
        "A": "Ich lese Atommassen ab und addiere sie zur Molekülmasse.",
        "B": "Ich berechne molare Massen auch bei Formeln mit Klammern.",
        "C": "Ich berechne Massenanteile einzelner Elemente in einer Verbindung."
    },
    "lernkarten": {
        "A": karte("Massen zusammenzählen",
                   "Jedes Element hat eine Atommasse.",
                   ["Sie steht im Periodensystem.", "Für ein Molekül werden alle addiert."],
                   "Molekülmasse = Summe aller Atommassen.",
                   visual={"type": "pse", "markiert": ["H", "O"], "perioden": 3,
                           "alt": "Periodensystem-Ausschnitt mit Wasserstoff und Sauerstoff."},
                   beispiel={"titel": "Wasser", "aufgabe": "M(H₂O) = ?",
                             "schritte": ["2 · 1 = 2", "1 · 16 = 16", "2 + 16 = 18"],
                             "ergebnis": "18 g/mol",
                             "luecke": {"schritt": 2, "wert": 18}}),
        "B": karte("Molare Masse berechnen",
                   "Die molare Masse ist zahlengleich zur Molekülmasse, trägt aber die Einheit g/mol. Damit wird aus einer Verhältniszahl eine wägbare Größe.",
                   ["Für jedes Element die Atommasse ablesen und mit dem Index multiplizieren.",
                    "Alles addieren. Das Ergebnis ist die molare Masse in g/mol.",
                    "Bei Klammern gilt der Index für alles in der Klammer: Ca(OH)₂ = 40 + 2 · (16 + 1) = 74 g/mol.",
                    "Schulwerte: H 1 · C 12 · N 14 · O 16 · Na 23 · Mg 24 · S 32 · Cl 35,5 · Ca 40 · Fe 56 · Cu 64."],
                   "M = Summe aller Atommassen · Indizes, in g/mol.",
                   visual={"type": "lewis", "molekuel": "co2", "formel": "CO2",
                           "alt": "Lewis-Formel von Kohlenstoffdioxid."}),
        "C": karte("Massenanteile bestimmen",
                   "Aus der molaren Masse folgt unmittelbar, welcher Anteil der Masse auf welches Element entfällt — das ist die Grundlage jeder Gehaltsangabe.",
                   ["Anteil eines Elements = (Zahl der Atome · Atommasse) : molare Masse · 100 %.",
                    "Beispiel Wasser: Sauerstoff 16 : 18 = 88,9 %. Obwohl zwei H-Atome enthalten sind, tragen sie nur 11,1 % der Masse.",
                    "Daraus folgt eine wichtige Unterscheidung: Das Anzahlverhältnis (2 : 1) und das Massenverhältnis (1 : 8) sind zwei verschiedene Dinge.",
                    "Umgekehrt lässt sich aus gemessenen Massenanteilen die Formel bestimmen — das Verfahren der Elementaranalyse."],
                   "Anzahlverhältnis und Massenverhältnis sind nicht dasselbe.",
                   visual={"type": "anteil", "titel": "Massenanteile im Wasser",
                           "segmente": [{"anteil": 88.9, "label": "O"}, {"anteil": 11.1, "label": "H"}],
                           "alt": "Im Wasser entfallen 88,9 % der Masse auf Sauerstoff."})
    },
    "formelkarte": {"formeln": ["M = Summe der Atommassen · Indizes",
                               "w(Element) = n · M(Element) : M(Verbindung) · 100 %"],
                    "saetze": ["H 1 · C 12 · N 14 · O 16 · Na 23 · Mg 24 · S 32 · Cl 35,5 · Ca 40 · Fe 56 · Cu 64",
                               "M(H₂O) = 18 · M(CO₂) = 44 · M(H₂SO₄) = 98 g/mol",
                               "Bei Klammern gilt der Index für alles darin.",
                               "Anzahlverhältnis und Massenverhältnis sind verschieden."]},
    "tasks": [
        aufgabe("QB01-A1-001", "A", 1, "numeric",
                "Wie groß ist die molare Masse von Wasser H₂O? (H = 1, O = 16 g/mol)",
                answer=18, unit_label="g/mol", tolerance=0,
                hints=["Zwei H und ein O.", "2 · 1 + 16.", "18 g/mol."],
                solution="M(H₂O) = 2 · 1 + 16 = 18 g/mol",
                misconceptions=[fv("index_uebersehen", 17,
                                   "Der Index 2 gilt für den Wasserstoff: 2 · 1 = 2.",
                                   "summenformel_falsch_gelesen")],
                tags=["molmasse"], spiral=["W-RECH"]),
        aufgabe("QB01-A2-002", "A", 2, "numeric",
                "Wie groß ist M(CO₂)? (C = 12, O = 16 g/mol)",
                answer=44, unit_label="g/mol", tolerance=0,
                hints=["Ein C und zwei O.", "12 + 2 · 16.", "44 g/mol."],
                solution="M(CO₂) = 12 + 32 = 44 g/mol",
                tags=["molmasse"], spiral=["W-RECH"]),
        aufgabe("QB01-A3-003", "A", 3, "numeric",
                "Wie groß ist M(NaCl)? (Na = 23, Cl = 35,5 g/mol)",
                answer=58.5, unit_label="g/mol", tolerance=0.1,
                hints=["Je ein Ion.", "23 + 35,5.", "58,5 g/mol."],
                solution="M(NaCl) = 23 + 35,5 = 58,5 g/mol",
                tags=["molmasse"], spiral=["W-RECH"]),
        aufgabe("QB01-A4-004", "A", 4, "numeric",
                "Wie groß ist M(CH₄)? (C = 12, H = 1 g/mol)",
                answer=16, unit_label="g/mol", tolerance=0,
                hints=["Ein C und vier H.", "12 + 4 · 1.", "16 g/mol."],
                solution="M(CH₄) = 12 + 4 = 16 g/mol",
                misconceptions=[fv("index_uebersehen", 13,
                                   "Der Index 4 gilt für den Wasserstoff: 4 · 1 = 4.",
                                   "summenformel_falsch_gelesen")],
                tags=["molmasse"], spiral=["W-RECH", "W-ORG"]),
        aufgabe("QB01-B1-005", "B", 1, "numeric",
                "Wie groß ist M(H₂SO₄)? (H = 1, S = 32, O = 16 g/mol)",
                answer=98, unit_label="g/mol", tolerance=0,
                hints=["Zwei H, ein S, vier O.", "2 + 32 + 64.", "98 g/mol."],
                solution="M(H₂SO₄) = 2 · 1 + 32 + 4 · 16 = 98 g/mol",
                tags=["molmasse", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB01-B2-006", "B", 2, "numeric",
                "Wie groß ist M(Ca(OH)₂)? (Ca = 40, O = 16, H = 1 g/mol)",
                answer=74, unit_label="g/mol", tolerance=0,
                hints=["Die 2 gilt für die ganze Klammer.",
                       "40 + 2 · (16 + 1).",
                       "40 + 34."],
                solution="M(Ca(OH)₂) = 40 + 2 · 17 = 74 g/mol",
                misconceptions=[fv("klammer_ignoriert", 57,
                                   "Die 2 hinter der Klammer verdoppelt O und H gemeinsam.",
                                   "summenformel_falsch_gelesen")],
                tags=["molmasse", "bbr"], spiral=["W-RECH", "W-SYMB"]),
        aufgabe("QB01-B2-007", "B", 2, "numeric",
                "Wie groß ist M(CaCO₃)? (Ca = 40, C = 12, O = 16 g/mol)",
                answer=100, unit_label="g/mol", tolerance=0,
                hints=["Ein Ca, ein C, drei O.", "40 + 12 + 48.", "100 g/mol."],
                solution="M(CaCO₃) = 40 + 12 + 3 · 16 = 100 g/mol",
                tags=["molmasse", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB01-B3-008", "B", 3, "multi",
                "Berechne die molaren Massen. (N = 14, H = 1, O = 16, S = 32, Fe = 56 g/mol)",
                fields=[
                    {"label": "M(NH₃)", "answer": 17, "unit_label": "g/mol", "tolerance": 0},
                    {"label": "M(SO₃)", "answer": 80, "unit_label": "g/mol", "tolerance": 0},
                    {"label": "M(Fe₂O₃)", "answer": 160, "unit_label": "g/mol", "tolerance": 0}
                ],
                hints=["Jeden Index einzeln beachten.",
                       "SO₃ = 32 + 3 · 16.",
                       "Fe₂O₃ = 2 · 56 + 3 · 16."],
                solution="NH₃ = 14 + 3 = 17\nSO₃ = 32 + 48 = 80\nFe₂O₃ = 112 + 48 = 160 g/mol",
                tags=["molmasse", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB01-B3-009", "B", 3, "numeric",
                "Wie viel Prozent der Masse von CO₂ entfallen auf den Kohlenstoff?",
                answer=27.3, unit_label="%", tolerance=0.3,
                hints=["Kohlenstoffmasse durch Gesamtmasse.", "12 : 44.", "Mal 100."],
                solution="12 : 44 = 0,2727 → 27,3 %",
                misconceptions=[fv("anteil_umgedreht", 72.7,
                                   "Das ist der Sauerstoffanteil. Gefragt war der Kohlenstoff.")],
                tags=["molmasse", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB01-B4-010", "B", 4, "numeric",
                "Wie viel Prozent der Masse von Eisenoxid Fe₂O₃ (M = 160 g/mol) ist Eisen? (Fe = 56 g/mol)",
                answer=70, unit_label="%", tolerance=0.5,
                hints=["Zwei Eisenatome.", "2 · 56 = 112.", "112 : 160."],
                solution="112 : 160 = 0,70 → 70 %. Deshalb liefert 1 t Fe₂O₃ höchstens 700 kg Eisen.",
                tags=["molmasse", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("QB01-C2-011", "C", 2, "multi",
                "Betrachte Ammoniumsulfat (NH₄)₂SO₄. (N = 14, H = 1, S = 32, O = 16 g/mol)",
                fields=[
                    {"label": "molare Masse", "answer": 132, "unit_label": "g/mol", "tolerance": 0,
                     "misconceptions": [fv("klammer_ignoriert", 114,
                                           "(NH₄)₂ bedeutet 2 · (14 + 4) = 36, nicht 18.",
                                           "summenformel_falsch_gelesen")]},
                    {"label": "Massenanteil des Stickstoffs in Prozent", "answer": 21.2, "unit_label": "%", "tolerance": 0.3}
                ],
                hints=["(NH₄)₂ = 2 · 18 = 36.",
                       "SO₄ = 32 + 64 = 96.",
                       "Stickstoff: 2 · 14 = 28."],
                solution="M = 36 + 96 = 132 g/mol\nw(N) = 28 : 132 = 21,2 %",
                tags=["molmasse", "msa"], spiral=["W-RECH", "W-SYMB"]),
        aufgabe("QB01-C3-012", "C", 3, "choice",
                "In Wasser stehen H und O im Anzahlverhältnis 2 : 1, im Massenverhältnis aber 1 : 8. Wie passt das zusammen?",
                options=["Ein O-Atom ist 16-mal so schwer wie ein H-Atom; die Anzahl sagt nichts über die Masse.",
                         "Eines der beiden Verhältnisse ist falsch.",
                         "Die Verhältnisse sind immer gleich."],
                answer=0,
                hints=["Wie schwer ist ein O-Atom im Vergleich zu einem H-Atom?",
                       "16-mal so schwer.",
                       "2 · 1 gegen 1 · 16."],
                solution="Zwei H-Atome wiegen zusammen 2, ein O-Atom wiegt 16 — das Massenverhältnis ist 2 : 16 = 1 : 8. Anzahl- und Massenverhältnis sind verschiedene Aussagen über dieselbe Formel.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 2,
                                   "Anzahl und Masse sind zwei verschiedene Größen. Atome verschiedener Elemente sind verschieden schwer.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["molmasse", "msa"], spiral=["W-RECH"]),
        aufgabe("QB01-C3-013", "C", 3, "numeric",
                "Ein Dünger enthält Ammoniumnitrat NH₄NO₃ (M = 80 g/mol). Wie viel Prozent Stickstoff enthält er? (N = 14 g/mol)",
                answer=35, unit_label="%", tolerance=0.5,
                hints=["Wie viele N-Atome stecken in der Formel?",
                       "Zwei — eines im Ammonium, eines im Nitrat.",
                       "2 · 14 : 80."],
                solution="2 N-Atome: 2 · 14 = 28 g/mol\n28 : 80 = 0,35 → 35 %\nDeshalb ist Ammoniumnitrat ein besonders stickstoffreicher Dünger.",
                misconceptions=[fv("index_uebersehen", 17.5,
                                   "Es sind zwei Stickstoffatome — eines im NH₄, eines im NO₃.",
                                   "summenformel_falsch_gelesen")],
                tags=["molmasse", "rechnen", "msa"], spiral=["W-RECH", "W-SYMB"]),
        aufgabe("QB01-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt: „M(O) = 16 g“. Was ist zu korrigieren?",
                options=["Die Einheit ist g/mol — 16 g wäre die Masse einer bestimmten Portion, nicht die molare Masse.",
                         "Nichts, die Angabe ist richtig.",
                         "M(O) beträgt 32 g/mol."],
                answer=0,
                hints=["Welche Einheit hat die molare Masse?",
                       "Gramm je Mol.",
                       "32 g/mol wäre O₂."],
                solution="Die molare Masse hat immer die Einheit g/mol. 16 g wäre eine konkrete Masse. Und 32 g/mol gehört zum Molekül O₂, nicht zum Atom.",
                misconceptions=[fv("groesse_und_einheit_verwechselt", 2,
                                   "32 g/mol ist die molare Masse von O₂, dem Molekül.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["molmasse", "bewerten", "msa"], spiral=["W-EINH"])
    ]
})

if __name__ == "__main__":
    schreiben("me", ME, "Bereich ME · Einheit 7")
    schreiben("qb", QB, "Bereich QB · Einheit 1")
