# -*- coding: utf-8 -*-
"""Bereich PS · Das Periodensystem — PS-07 und PS-08."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "PS-07",
    "title": "Schalenmodell und Außenelektronen",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 7,
    "wortspeicher": ["die Schale", "das Außenelektron", "das Valenzelektron", "die Edelgaskonfiguration",
                     "die Besetzungsregel", "das Schalenmodell"],
    "worterklaerungen": {
        "Schale": "Ein Bereich in der Atomhülle. Jede Schale fasst nur eine bestimmte Zahl Elektronen.",
        "Außenelektron": "Ein Elektron auf der äußersten Schale. Es bestimmt, wie ein Atom reagiert.",
        "Edelgaskonfiguration": "Eine volle Außenschale. Diesen Zustand streben Atome an."
    },
    "can_do": {
        "A": "Ich verteile Elektronen auf die Schalen und lese die Zahl der Außenelektronen ab.",
        "B": "Ich verbinde Schalenzahl mit der Periode und Außenelektronen mit der Hauptgruppe.",
        "C": "Ich sage aus der Stellung im PSE voraus, wie viele Elektronen ein Atom abgibt oder aufnimmt."
    },
    "lernkarten": {
        "A": karte("Elektronen auf Schalen",
                   "Die Elektronen sitzen auf Schalen.",
                   ["Die erste Schale fasst 2 Elektronen.", "Die zweite fasst 8. Die dritte auch 8."],
                   "Erst die innere Schale füllen, dann die nächste.",
                   visual={"type": "atom", "z": 11, "symbol": "Na", "regler": True,
                           "alt": "Schalenmodell mit Regler für die Ordnungszahl."},
                   beispiel={"titel": "Natrium verteilen", "aufgabe": "Natrium hat 11 Elektronen.",
                             "schritte": ["2 auf die erste Schale", "8 auf die zweite Schale",
                                          "1 bleibt für die dritte"],
                             "ergebnis": "2 · 8 · 1 — ein Außenelektron.",
                             "luecke": {"schritt": 2, "wert": 1}}),
        "B": karte("Schalen, Perioden, Gruppen",
                   "Das Schalenmodell erklärt den Aufbau des Periodensystems. Zwei Zusammenhänge tragen fast alles, was in Klasse 7 bis 10 gebraucht wird.",
                   ["Die Zahl der besetzten Schalen ist die Periodennummer. Natrium hat drei Schalen und steht in Periode 3.",
                    "Die Zahl der Außenelektronen ist die Hauptgruppennummer. Natrium hat ein Außenelektron und steht in Gruppe I.",
                    "Deshalb reagieren Elemente einer Gruppe ähnlich: Sie haben gleich viele Außenelektronen."],
                   "Periode = Zahl der Schalen. Hauptgruppe = Zahl der Außenelektronen.",
                   visual=anim("atombau", "B")),
        "C": karte("Was ein Atom mit seinen Außenelektronen tut",
                   "Atome streben die volle Außenschale an — die Edelgaskonfiguration. Ob sie dafür Elektronen abgeben oder aufnehmen, entscheidet allein, welcher Weg der kürzere ist.",
                   ["Ein bis drei Außenelektronen: Abgeben ist kürzer. Es entstehen positiv geladene Ionen. Das tun die Metalle.",
                    "Fünf bis sieben Außenelektronen: Aufnehmen ist kürzer. Es entstehen negativ geladene Ionen. Das tun die Nichtmetalle.",
                    "Acht Außenelektronen: Der Zustand ist bereits erreicht. Deshalb reagieren Edelgase kaum.",
                    "Damit ist die Ionenladung aus der Hauptgruppennummer vorhersagbar — und die Verhältnisformel eines Salzes ebenso."],
                   "Ein bis drei abgeben, fünf bis sieben aufnehmen — jeweils der kürzere Weg zur vollen Schale.",
                   visual=anim("atombau", "C"))
    },
    "formelkarte": {"formeln": ["Schalen fassen 2, 8, 8, 2 Elektronen"],
                    "saetze": ["Periode = Zahl der besetzten Schalen.",
                               "Hauptgruppe = Zahl der Außenelektronen.",
                               "1 bis 3 Außenelektronen → abgeben → positives Ion.",
                               "5 bis 7 Außenelektronen → aufnehmen → negatives Ion.",
                               "8 Außenelektronen: Edelgaskonfiguration, kaum Reaktion."]},
    "tasks": [
        aufgabe("PS07-A1-001", "A", 1, "numeric",
                "Wie viele Elektronen passen auf die erste Schale?",
                answer=2, tolerance=0,
                hints=["Die erste Schale ist die kleinste.", "Sie fasst weniger als die zweite.", "2."],
                solution="Die erste Schale fasst 2 Elektronen.",
                tags=["schalen"], spiral=["W-TEIL"]),
        aufgabe("PS07-A2-002", "A", 2, "numeric",
                "Sauerstoff hat 8 Elektronen. Wie viele sitzen auf der äußersten Schale?",
                answer=6, tolerance=0,
                visual={"type": "atom", "z": 8, "symbol": "O", "neutronen": 8,
                        "alt": "Schalenmodell von Sauerstoff."},
                hints=["Erst 2 auf die erste Schale.", "Es bleiben 8 − 2 = 6.", "6 Außenelektronen."],
                solution="2 auf die erste Schale, die restlichen 6 auf die zweite. Sauerstoff hat 6 Außenelektronen.",
                misconceptions=[fv("schale_falsch_gefuellt", 8,
                                   "Die erste Schale fasst nur 2. Die übrigen 6 sitzen außen.",
                                   "ion_und_atom_verwechselt")],
                tags=["schalen"], spiral=["W-TEIL"]),
        aufgabe("PS07-A3-003", "A", 3, "numeric",
                "Wie viele Schalen sind bei Natrium (11 Elektronen) besetzt?",
                answer=3, tolerance=0,
                hints=["2 auf die erste, 8 auf die zweite.", "Es bleibt 1 übrig.", "Also drei Schalen."],
                solution="2 + 8 = 10, das elfte Elektron beginnt die dritte Schale. Natrium hat drei besetzte Schalen.",
                tags=["schalen"], spiral=["W-TEIL"]),
        aufgabe("PS07-A4-004", "A", 4, "choice",
                "Welches Atom hat eine volle Außenschale?",
                options=["Neon", "Natrium", "Chlor"], answer=0,
                hints=["Volle Außenschale haben die Edelgase.", "Welches der drei ist ein Edelgas?", "Neon."],
                solution="Neon ist ein Edelgas und hat 8 Außenelektronen — die Schale ist voll. Deshalb reagiert es kaum.",
                tags=["schalen"], spiral=["W-TEIL"]),
        aufgabe("PS07-B1-005", "B", 1, "multi",
                "Verteile die Elektronen von Chlor (17 Elektronen) auf die Schalen.",
                fields=[
                    {"label": "1. Schale", "answer": 2, "tolerance": 0},
                    {"label": "2. Schale", "answer": 8, "tolerance": 0},
                    {"label": "3. Schale", "answer": 7, "tolerance": 0}
                ],
                visual={"type": "atom", "z": 17, "symbol": "Cl", "neutronen": 18,
                        "alt": "Schalenmodell von Chlor."},
                hints=["Erst die innere Schale voll machen.",
                       "2, dann 8.",
                       "17 − 2 − 8 = 7."],
                solution="2 · 8 · 7 — Chlor hat 7 Außenelektronen und steht in Hauptgruppe VII.",
                tags=["schalen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS07-B2-006", "B", 2, "choice",
                "Ein Element steht in Periode 3 und Hauptgruppe II. Wie viele Außenelektronen hat es?",
                options=["2", "3", "8"], answer=0,
                hints=["Welche Zahl gibt die Außenelektronen an?",
                       "Die Hauptgruppennummer.",
                       "Also 2."],
                solution="Die Hauptgruppennummer gibt die Zahl der Außenelektronen an: 2. Die Periode 3 sagt, dass drei Schalen besetzt sind — es ist Magnesium.",
                misconceptions=[fv("periode_gruppe_vertauscht", 1,
                                   "Die 3 ist die Periode, also die Zahl der Schalen. Die Außenelektronen gibt die Gruppennummer an.")],
                tags=["schalen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS07-B2-007", "B", 2, "choice",
                "Warum gibt Natrium beim Reagieren genau ein Elektron ab?",
                options=["Danach hat es die volle Schale eines Edelgases erreicht.",
                         "Weil es genau ein Elektron zu viel hat.",
                         "Weil es in Periode 3 steht."],
                answer=0, visual=anim("atombau", "B"),
                hints=["Was passiert mit der Hülle, wenn das eine Außenelektron weg ist?",
                       "Die darunterliegende volle Schale wird zur Außenschale.",
                       "Das ist die Edelgaskonfiguration von Neon."],
                solution="Gibt Natrium sein einziges Außenelektron ab, wird die darunterliegende volle Schale zur äußersten — die Konfiguration von Neon. Genau diesen Zustand streben Atome an.",
                tags=["schalen", "ionen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS07-B3-008", "B", 3, "numeric",
                "Wie viele Elektronen nimmt Sauerstoff (6 Außenelektronen) auf, um die volle Schale zu erreichen?",
                answer=2, tolerance=0,
                hints=["Volle Schale heißt 8.", "8 − 6.", "2."],
                solution="8 − 6 = 2. Sauerstoff nimmt zwei Elektronen auf und bildet das Ion O²⁻.",
                misconceptions=[fv("ladung_falsch_herum", 6,
                                   "Das ist die Zahl der vorhandenen Außenelektronen. Gefragt war, wie viele noch fehlen.",
                                   "ladung_unvollstaendig")],
                tags=["schalen", "ionen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS07-B3-009", "B", 3, "assign",
                "Ordne jedem Atom zu, was es tut, um die volle Schale zu erreichen.",
                slots=["Magnesium (2 Außenelektronen)", "Schwefel (6 Außenelektronen)", "Argon (8 Außenelektronen)"],
                values=["gibt 2 Elektronen ab", "nimmt 2 Elektronen auf", "tut nichts"],
                answer=[0, 1, 2],
                hints=["Der kürzere Weg entscheidet.",
                       "Bei 2 Außenelektronen ist Abgeben kürzer.",
                       "Bei 8 ist der Zustand schon erreicht."],
                solution="Magnesium → 2 abgeben (Mg²⁺).\nSchwefel → 2 aufnehmen (S²⁻).\nArgon → nichts, die Schale ist voll.",
                tags=["schalen", "ionen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS07-B4-010", "B", 4, "choice",
                "Warum reagieren Lithium, Natrium und Kalium alle heftig mit Wasser?",
                options=["Alle drei haben ein Außenelektron und geben es leicht ab.",
                         "Alle drei sind Metalle mit gleicher Masse.",
                         "Alle drei stehen in derselben Periode."],
                answer=0,
                hints=["Was haben sie gemeinsam?",
                       "Sie stehen untereinander in Gruppe I.",
                       "Also gleich viele Außenelektronen."],
                solution="Alle drei stehen in Hauptgruppe I und besitzen ein Außenelektron, das leicht abgegeben wird. Gleiche Außenelektronenzahl bedeutet ähnliches Reaktionsverhalten.",
                tags=["schalen", "gruppen", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS07-C2-011", "C", 2, "choice",
                "Ein Element hat die Elektronenverteilung 2 · 8 · 3. Wo steht es im Periodensystem?",
                options=["Periode 3, Hauptgruppe III", "Periode 2, Hauptgruppe III", "Periode 3, Hauptgruppe II"],
                answer=0,
                hints=["Zähle die besetzten Schalen.",
                       "Es sind drei.",
                       "Und außen sitzen drei Elektronen."],
                solution="Drei besetzte Schalen → Periode 3. Drei Außenelektronen → Hauptgruppe III. Es ist Aluminium.",
                misconceptions=[fv("periode_gruppe_vertauscht", 1,
                                   "Die Periode ist die Zahl der Schalen, nicht die Zahl der Außenelektronen.")],
                tags=["schalen", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS07-C3-012", "C", 3, "multi",
                "Aluminium hat 13 Elektronen, Sauerstoff 8.",
                fields=[
                    {"label": "Ladung des Aluminium-Ions", "answer": 3, "tolerance": 0},
                    {"label": "Ladung des Sauerstoff-Ions", "answer": -2, "tolerance": 0,
                     "misconceptions": [fv("ladung_falsch_herum", 2,
                                           "Sauerstoff nimmt Elektronen auf und wird dadurch <b>negativ</b>.",
                                           "ladung_unvollstaendig")]},
                    {"label": "Zahl der Aluminium-Ionen in der Verhältnisformel", "answer": 2, "tolerance": 0}
                ],
                hints=["Aluminium: 2 · 8 · 3, also 3 Außenelektronen zum Abgeben.",
                       "Sauerstoff: 6 Außenelektronen, nimmt 2 auf.",
                       "Ladungsausgleich: 2 · (+3) und 3 · (−2) ergeben null."],
                solution="Al³⁺ und O²⁻.\nLadungsausgleich: 2 · 3 = 6 = 3 · 2 → Al₂O₃.",
                tags=["schalen", "ionen", "msa"], spiral=["W-TEIL", "W-SYMB"]),
        aufgabe("PS07-C3-013", "C", 3, "choice",
                "Warum versagt das Schalenmodell bei den Nebengruppenelementen?",
                options=["Deren Elektronen füllen innere Bereiche auf, was das einfache Schalenmodell nicht abbildet.",
                         "Nebengruppenelemente haben keine Elektronen.",
                         "Nebengruppenelemente sind keine Elemente."],
                answer=0,
                hints=["Was ändert sich bei Eisen, Kupfer, Zink von einem Element zum nächsten?",
                       "Nicht die Außenelektronenzahl.",
                       "Aufgefüllt wird eine innere Ebene."],
                solution="Bei den Nebengruppen werden innere Bereiche aufgefüllt, während die Außenelektronenzahl fast gleich bleibt. Deshalb ähneln sich diese Elemente untereinander stark — mit der einfachen Regel 2, 8, 8 lässt sich das nicht darstellen. Das ist eine bekannte Modellgrenze.",
                tags=["schalen", "modelle", "msa"]),
        aufgabe("PS07-C4-014", "C", 4, "choice",
                "Ein Schüler folgert: „Kalium hat 19 Elektronen, also 2 · 8 · 8 · 1. Und Calcium 2 · 8 · 8 · 2. Dann müsste das nächste Element 2 · 8 · 8 · 3 haben.“ Wie bewertest du das?",
                options=["Die Regel trägt bis Calcium; danach beginnt eine Nebengruppe, für die das Modell nicht gemacht ist.",
                         "Die Folgerung stimmt für alle Elemente.",
                         "Die Folgerung ist falsch, weil die dritte Schale nur 8 fasst."],
                answer=0,
                hints=["Welches Element folgt auf Calcium?",
                       "Scandium — ein Nebengruppenelement.",
                       "Dort greift die einfache Regel nicht mehr."],
                solution="Bis Calcium ist die Fortsetzung richtig. Danach folgt Scandium, ein Nebengruppenelement: Dort wird eine innere Ebene aufgefüllt statt der Außenschale. Die Schlussfolgerung ist also nicht falsch gedacht, sondern über die Modellgrenze hinaus gezogen.",
                tags=["schalen", "bewerten", "msa"], spiral=["W-TEIL"])
    ]
})

E.append({
    "unit": "PS-08",
    "title": "Elementfamilien & Prüfungstraining",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K3.3", "K4.1"],
    "klasse": 7,
    "wortspeicher": ["die Alkalimetalle", "die Erdalkalimetalle", "die Halogene", "die Edelgase",
                     "die Elementfamilie", "die Reaktionsfähigkeit"],
    "worterklaerungen": {
        "Alkalimetalle": "Die Elemente der ersten Hauptgruppe. Sie reagieren heftig mit Wasser.",
        "Halogene": "Die Elemente der siebten Hauptgruppe. Sie bilden Salze.",
        "Elementfamilie": "Eine Hauptgruppe mit ähnlichen Eigenschaften."
    },
    "can_do": {
        "A": "Ich ordne bekannte Elemente ihrer Familie zu und nenne eine typische Eigenschaft.",
        "B": "Ich beschreibe Trends innerhalb einer Familie und begründe sie mit dem Atombau.",
        "C": "Ich sage Eigenschaften eines unbekannten Elements aus seiner Stellung im PSE vorher."
    },
    "lernkarten": {
        "A": karte("Familien im Periodensystem",
                   "Elemente einer Spalte bilden eine Familie.",
                   ["Alkalimetalle stehen ganz links.", "Edelgase stehen ganz rechts."],
                   "Gleiche Spalte = gleiche Familie = ähnliche Eigenschaften.",
                   visual={"type": "pse", "markiert": ["Li", "Na", "K", "F", "Cl", "He", "Ne", "Ar"], "perioden": 4,
                           "alt": "Periodensystem mit hervorgehobenen Alkalimetallen, Halogenen und Edelgasen."},
                   beispiel={"titel": "Natrium und Wasser", "aufgabe": "Natrium wird in Wasser gegeben.",
                             "schritte": ["Es zischt und schmilzt zur Kugel.",
                                          "Ein Gas entsteht.", "Die Lösung wird alkalisch."],
                             "ergebnis": "Typisch für ein Alkalimetall."}),
        "B": karte("Trends in einer Familie",
                   "Innerhalb einer Familie ändern sich Eigenschaften nicht sprunghaft, sondern regelmäßig. Diese Regelmäßigkeit macht Vorhersagen möglich.",
                   ["Bei den Alkalimetallen nimmt die Reaktionsfähigkeit nach unten zu: Lithium reagiert lebhaft, Kalium heftig, Caesium explosionsartig.",
                    "Grund: Je weiter außen das Außenelektron sitzt, desto schwächer hält der Kern es fest — desto leichter wird es abgegeben.",
                    "Bei den Halogenen ist es umgekehrt: Sie nehmen Elektronen auf, und das gelingt bei kleinen Atomen besser. Fluor ist deshalb reaktionsfreudiger als Iod."],
                   "Alkalimetalle: nach unten reaktiver. Halogene: nach oben reaktiver.",
                   visual={"type": "pse", "markiert": ["Li", "Na", "K"], "perioden": 4,
                           "legende": "Nach unten wächst bei den Alkalimetallen die Reaktionsfähigkeit.",
                           "alt": "Periodensystem mit hervorgehobener erster Hauptgruppe."}),
        "C": karte("Vorhersagen treffen",
                   "Der eigentliche Wert des Periodensystems liegt darin, dass es Aussagen über Elemente erlaubt, die man nie gesehen hat. Genau dafür wurde es gebaut.",
                   ["Aus der Gruppe folgt: Zahl der Außenelektronen, Ionenladung, Art der Verbindungen.",
                    "Aus der Periode folgt: Zahl der Schalen, Größe des Atoms.",
                    "Aus der Stellung innerhalb der Gruppe folgt die relative Reaktionsfähigkeit.",
                    "Ein Beispiel: Rubidium steht unter Kalium in Gruppe I. Also ein Außenelektron, Ion Rb⁺, Reaktion mit Wasser heftiger als bei Kalium."],
                   "Gruppe sagt was, Periode sagt wie groß, Stellung sagt wie heftig.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Gruppe I: Alkalimetalle, ein Außenelektron, Ion X⁺.",
                               "Gruppe II: Erdalkalimetalle, zwei Außenelektronen, Ion X²⁺.",
                               "Gruppe VII: Halogene, sieben Außenelektronen, Ion X⁻.",
                               "Gruppe VIII: Edelgase, volle Außenschale, kaum Reaktion.",
                               "Alkalimetalle werden nach unten reaktiver, Halogene nach oben."]},
    "tasks": [
        aufgabe("PS08-A1-001", "A", 1, "choice",
                "Zu welcher Familie gehört Natrium?",
                options=["Alkalimetalle", "Halogene", "Edelgase"], answer=0,
                hints=["In welcher Spalte steht Natrium?", "In der ersten.", "Das sind die Alkalimetalle."],
                solution="Natrium steht in der ersten Hauptgruppe — bei den Alkalimetallen.",
                tags=["familien"], spiral=["W-TEIL"]),
        aufgabe("PS08-A2-002", "A", 2, "assign",
                "Ordne jedes Element seiner Familie zu.",
                slots=["Kalium", "Chlor", "Argon"],
                values=["Alkalimetalle", "Halogene", "Edelgase"],
                answer=[0, 1, 2],
                hints=["Kalium steht ganz links.", "Argon ganz rechts.", "Chlor eine Spalte davor."],
                solution="Kalium → Alkalimetalle.\nChlor → Halogene.\nArgon → Edelgase.",
                tags=["familien"], spiral=["W-TEIL"]),
        aufgabe("PS08-A3-003", "A", 3, "choice",
                "Was passiert, wenn Natrium in Wasser gegeben wird?",
                options=["Es reagiert heftig und es entsteht ein Gas.", "Es löst sich ruhig auf.", "Es passiert nichts."],
                answer=0,
                hints=["Alkalimetalle reagieren mit Wasser.", "Und zwar heftig.", "Dabei entsteht Wasserstoff."],
                solution="Natrium reagiert heftig mit Wasser. Es entsteht Wasserstoff, und die Lösung wird alkalisch.",
                tags=["familien"], spiral=["W-GLEI"]),
        aufgabe("PS08-A4-004", "A", 4, "choice",
                "Warum reagieren Edelgase fast nicht?",
                options=["Ihre Außenschale ist bereits voll.", "Sie sind zu leicht.", "Sie sind zu selten."],
                answer=0,
                hints=["Was streben Atome an?", "Eine volle Außenschale.", "Edelgase haben sie schon."],
                solution="Edelgase haben eine volle Außenschale und müssen weder abgeben noch aufnehmen. Deshalb reagieren sie kaum.",
                tags=["familien"], spiral=["W-TEIL"]),
        aufgabe("PS08-B1-005", "B", 1, "choice",
                "Welche Ionenladung bildet ein Element der zweiten Hauptgruppe?",
                options=["2+", "2−", "1+"], answer=0,
                hints=["Wie viele Außenelektronen hat es?", "Zwei.", "Es gibt beide ab."],
                solution="Zwei Außenelektronen werden abgegeben. Es entsteht ein zweifach positiv geladenes Ion, etwa Mg²⁺.",
                misconceptions=[fv("ladung_falsch_herum", 1,
                                   "Beim Abgeben von Elektronen wird das Ion <b>positiv</b>.",
                                   "ladung_unvollstaendig")],
                tags=["familien", "ionen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS08-B2-006", "B", 2, "choice",
                "Warum reagiert Kalium heftiger mit Wasser als Lithium?",
                options=["Sein Außenelektron sitzt weiter vom Kern entfernt und wird leichter abgegeben.",
                         "Kalium ist schwerer.", "Kalium hat mehr Außenelektronen."],
                answer=0,
                hints=["Beide haben ein Außenelektron.",
                       "Der Unterschied liegt im Abstand zum Kern.",
                       "Weiter außen heißt schwächer gebunden."],
                solution="Beide haben ein Außenelektron. Bei Kalium sitzt es auf der vierten Schale, also weiter vom Kern entfernt, und wird deshalb leichter abgegeben. Nach unten nimmt die Reaktionsfähigkeit der Alkalimetalle zu.",
                misconceptions=[fv("masse_als_grund", 1,
                                   "Die Masse ist nicht die Ursache. Entscheidend ist der Abstand des Außenelektrons vom Kern.")],
                tags=["familien", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS08-B2-007", "B", 2, "choice",
                "Fluor reagiert heftiger als Iod. Wie passt das zum Trend bei den Alkalimetallen?",
                options=["Es ist der umgekehrte Trend, weil Halogene Elektronen aufnehmen statt abgeben.",
                         "Es ist derselbe Trend.", "Es ist ein Widerspruch im Periodensystem."],
                answer=0,
                hints=["Was tun Halogene mit Elektronen?",
                       "Sie nehmen auf.",
                       "Aufnehmen gelingt bei kleinen Atomen besser."],
                solution="Alkalimetalle geben ab — das gelingt bei großen Atomen leichter, also nach unten besser. Halogene nehmen auf — das gelingt bei kleinen Atomen besser, also nach oben. Beide Trends folgen derselben Ursache und zeigen nur in entgegengesetzte Richtung.",
                tags=["familien", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS08-B3-008", "B", 3, "assign",
                "Ordne jeder Familie ihre typische Ionenladung zu.",
                slots=["Alkalimetalle", "Erdalkalimetalle", "Halogene"],
                values=["1+", "2+", "1−"],
                answer=[0, 1, 2],
                hints=["Zähle die Außenelektronen.",
                       "Bis drei wird abgegeben.",
                       "Ab fünf wird aufgenommen."],
                solution="Alkalimetalle → 1+.\nErdalkalimetalle → 2+.\nHalogene → 1−.",
                tags=["familien", "ionen", "bbr"], spiral=["W-TEIL"]),
        aufgabe("PS08-B3-009", "B", 3, "choice",
                "Eine Prüfungsaufgabe lautet: „Begründe, warum Natrium und Kalium ähnlich reagieren.“ Welche Antwort ist vollständig?",
                options=["Beide stehen in Hauptgruppe I und haben je ein Außenelektron, das sie leicht abgeben — deshalb reagieren sie ähnlich.",
                         "Beide sind Metalle.",
                         "Beide reagieren mit Wasser."],
                answer=0,
                hints=["Was verlangt „Begründe“?",
                       "Eine Ursache.",
                       "Die Ursache liegt in den Außenelektronen."],
                solution="„Begründe“ verlangt die Ursache. Antwort 2 ist zu allgemein, Antwort 3 wiederholt die Beobachtung. Nur Antwort 1 nennt den Grund: gleiche Zahl der Außenelektronen.",
                misconceptions=[fv("beschreiben_statt_erklaeren", 2,
                                   "Das ist eine Beobachtung, keine Begründung.")],
                tags=["familien", "operatoren", "bbr"]),
        aufgabe("PS08-B4-010", "B", 4, "choice",
                "Warum werden Alkalimetalle unter Petroleum aufbewahrt?",
                options=["Sie reagieren mit Luftfeuchtigkeit und Sauerstoff; Petroleum schließt beides ab.",
                         "Petroleum kühlt sie.", "Petroleum macht sie schwerer."],
                answer=0,
                hints=["Womit reagieren Alkalimetalle?",
                       "Mit Wasser und Sauerstoff.",
                       "Beides steckt in der Luft."],
                solution="Alkalimetalle reagieren bereits mit der Luftfeuchtigkeit. Petroleum hält Wasser und Sauerstoff ab. Die frische Schnittfläche zeigt den metallischen Glanz — und läuft binnen Sekunden an.",
                tags=["familien", "sicherheit", "msa"]),
        aufgabe("PS08-C2-011", "C", 2, "choice",
                "Rubidium steht in Gruppe I unter Kalium. Was sagst du über seine Reaktion mit Wasser voraus?",
                options=["Noch heftiger als bei Kalium.", "Weniger heftig als bei Kalium.", "Gar keine Reaktion."],
                answer=0,
                hints=["Wie ändert sich die Reaktionsfähigkeit nach unten?",
                       "Sie nimmt zu.",
                       "Rubidium steht unter Kalium."],
                solution="Nach unten nimmt die Reaktionsfähigkeit der Alkalimetalle zu, weil das Außenelektron immer schwächer gebunden ist. Rubidium reagiert deshalb heftiger als Kalium.",
                tags=["familien", "vorhersage", "msa"], spiral=["W-TEIL"]),
        aufgabe("PS08-C3-012", "C", 3, "multi",
                "Ein unbekanntes Element X steht in Periode 4, Hauptgruppe II.",
                fields=[
                    {"label": "Zahl der Außenelektronen", "answer": 2, "tolerance": 0},
                    {"label": "Ladung seines Ions", "answer": 2, "tolerance": 0},
                    {"label": "Zahl der Chlorid-Ionen in der Verbindung mit Chlor", "answer": 2, "tolerance": 0}
                ],
                hints=["Hauptgruppe II → zwei Außenelektronen.",
                       "Beide werden abgegeben → X²⁺.",
                       "Chlorid ist einfach negativ; für den Ausgleich braucht es zwei."],
                solution="2 Außenelektronen → X²⁺.\nCl⁻ ist einfach negativ, also XCl₂. Es handelt sich um Calcium.",
                tags=["familien", "vorhersage", "msa"], spiral=["W-SYMB"]),
        aufgabe("PS08-C3-013", "C", 3, "choice",
                "Welche Vorhersage lässt sich aus dem Periodensystem NICHT ableiten?",
                options=["Wie schnell eine Reaktion abläuft.",
                         "Welche Ionenladung ein Hauptgruppenelement bildet.",
                         "Wie viele Außenelektronen ein Element hat."],
                answer=0,
                hints=["Was steht im PSE über Zeit?",
                       "Nichts.",
                       "Geschwindigkeit hängt von Temperatur, Zerteilung und Katalysator ab."],
                solution="Ionenladung und Außenelektronenzahl folgen unmittelbar aus der Stellung. Die Reaktionsgeschwindigkeit hängt dagegen von Temperatur, Zerteilungsgrad und Katalysator ab — dazu sagt das Periodensystem nichts.",
                tags=["familien", "bewerten", "msa"]),
        aufgabe("PS08-C4-014", "C", 4, "choice",
                "Ein Schüler behauptet: „Weil Kalium heftiger reagiert als Natrium, ist Kalium auch ein besseres Metall.“ Wie bewertest du diese Aussage?",
                options=["„Besser“ ist ohne Zweck keine sinnvolle Aussage — für einen Stromleiter zählt anderes als für eine Reaktion.",
                         "Richtig — heftigere Reaktion heißt besseres Metall.",
                         "Falsch — Natrium reagiert in Wirklichkeit heftiger."],
                answer=0,
                hints=["Wozu soll das Metall taugen?",
                       "Das steht nicht in der Aussage.",
                       "Ohne Zweck lässt sich „besser“ nicht beurteilen."],
                solution="Reaktionsfähigkeit ist eine Eigenschaft, keine Wertung. Für eine Batterie kann sie erwünscht sein, für ein Bauteil wäre sie ein Ausschlusskriterium. Bewertungen brauchen einen Zweck — das ist der Kern des Kompetenzbereichs Bewerten.",
                tags=["familien", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("ps", E, "Bereich PS · Einheiten 7 und 8")
