# -*- coding: utf-8 -*-
"""Bereich PS · Das Periodensystem — PS-05 bis PS-08."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "PS-05",
    "title": "Proton, Neutron, Elektron — die Ordnungszahl",
    "leitidee": "B1",
    "standards": ["K1", "K2.4", "K3.4"],
    "klasse": 7,
    "wortspeicher": ["das Proton", "das Neutron", "das Elektron", "die Ordnungszahl",
                     "die Massenzahl", "das Isotop", "die Kernladungszahl"],
    "worterklaerungen": {
        "Proton": "Ein positiv geladenes Teilchen im Kern.",
        "Neutron": "Ein ungeladenes Teilchen im Kern.",
        "Elektron": "Ein negativ geladenes Teilchen in der Hülle. Es ist sehr leicht.",
        "Massenzahl": "Protonen und Neutronen zusammengezählt.",
        "Isotop": "Atome desselben Elements mit verschiedener Neutronenzahl."
    },
    "can_do": {
        "A": "Ich lese die Ordnungszahl ab und nenne die Zahl der Protonen und Elektronen.",
        "B": "Ich berechne die Neutronenzahl aus Massenzahl und Ordnungszahl.",
        "C": "Ich erkläre Isotope und begründe, warum die Ordnungszahl das Element bestimmt."
    },
    "lernkarten": {
        "A": karte("Drei Teilchen",
                   "Ein Atom besteht aus drei Sorten Teilchen.",
                   ["Protonen sind positiv, Neutronen ungeladen. Beide sitzen im Kern.",
                    "Elektronen sind negativ. Sie sind in der Hülle."],
                   "Protonen + Neutronen im Kern, Elektronen in der Hülle.",
                   visual={"type": "atom", "z": 11, "symbol": "Na", "neutronen": 12,
                           "alt": "Schalenmodell von Natrium mit 11 Protonen und 12 Neutronen."},
                   beispiel={"titel": "Natrium", "aufgabe": "Natrium hat die Ordnungszahl 11.",
                             "schritte": ["Es hat 11 Protonen.", "Es hat 11 Elektronen."],
                             "ergebnis": "11 Protonen, 11 Elektronen.",
                             "luecke": {"schritt": 1, "wert": 11}}),
        "B": karte("Ordnungszahl und Massenzahl",
                   "Zwei Zahlen genügen, um ein Atom vollständig zu beschreiben — und sie stehen beide am Elementsymbol.",
                   ["Die Ordnungszahl Z zählt die Protonen. Im neutralen Atom sind es genauso viele Elektronen.",
                    "Die Massenzahl A zählt Protonen und Neutronen zusammen. Elektronen zählen nicht mit, sie sind rund 2000-mal leichter.",
                    "Daraus folgt: Neutronen = A − Z."],
                   "Z zählt Protonen. A zählt Kernteilchen. Neutronen = A − Z.",
                   visual={"type": "atom", "z": 17, "symbol": "Cl", "neutronen": 18,
                           "alt": "Schalenmodell von Chlor mit 17 Protonen und 18 Neutronen."}),
        "C": karte("Warum die Ordnungszahl das Element bestimmt",
                   "Die Neutronenzahl darf schwanken, ohne dass sich das Element ändert. Die Protonenzahl darf es nicht — und dafür gibt es einen guten Grund.",
                   ["Die Protonenzahl legt die Kernladung fest. Sie bestimmt, wie viele Elektronen ein neutrales Atom hat und wie sie verteilt sind.",
                    "Das chemische Verhalten hängt allein von den Elektronen ab. Deshalb bestimmt die Protonenzahl das Element.",
                    "Isotope unterscheiden sich nur in der Neutronenzahl. Chemisch verhalten sie sich gleich, physikalisch unterscheiden sie sich in der Masse.",
                    "Die im PSE angegebene Atommasse ist deshalb ein gewichteter Mittelwert über die natürlich vorkommenden Isotope — daher die krummen Werte wie 35,5 bei Chlor."],
                   "Protonen bestimmen das Element. Neutronen bestimmen nur die Masse.",
                   visual={"type": "pse", "markiert": ["Cl"], "perioden": 3,
                           "legende": "Chlor: mittlere Atommasse 35,5 — ein Mittelwert aus zwei Isotopen.",
                           "alt": "Periodensystem-Ausschnitt mit hervorgehobenem Chlor."})
    },
    "formelkarte": {"formeln": ["Protonen = Elektronen = Ordnungszahl Z",
                               "Neutronen = Massenzahl A − Ordnungszahl Z",
                               "Massenzahl A = Protonen + Neutronen"],
                    "saetze": ["Elektronen zählen bei der Massenzahl nicht mit.",
                               "Isotope: gleiche Protonenzahl, verschiedene Neutronenzahl.",
                               "Die Protonenzahl bestimmt das Element."]},
    "tasks": [
        aufgabe("PS05-A1-001", "A", 1, "numeric",
                "Wie viele Protonen hat ein Atom mit der Ordnungszahl 8?",
                answer=8, tolerance=0,
                hints=["Die Ordnungszahl zählt die Protonen.", "Sie ist 8.", "8 Protonen."],
                solution="Die Ordnungszahl gibt die Protonenzahl an: 8 Protonen.",
                tags=["atombau"], spiral=["K-ATOM"]),
        aufgabe("PS05-A2-002", "A", 2, "numeric",
                "Wie viele Elektronen hat ein neutrales Atom mit 12 Protonen?",
                answer=12, tolerance=0,
                hints=["Neutral heißt: gleich viele positive und negative Ladungen.",
                       "12 Protonen sind 12 positive Ladungen.",
                       "Also 12 Elektronen."],
                solution="Im neutralen Atom sind Protonen und Elektronen gleich viele: 12.",
                tags=["atombau"], spiral=["K-ATOM"]),
        aufgabe("PS05-A3-003", "A", 3, "assign",
                "Ordne jedem Teilchen seine Ladung zu.",
                slots=["Proton", "Neutron", "Elektron"],
                values=["positiv", "keine Ladung", "negativ"],
                answer=[0, 1, 2],
                hints=["Der Name des Neutrons verrät seine Ladung.",
                       "Neutron kommt von neutral.",
                       "Elektronen sind negativ."],
                solution="Proton → positiv.\nNeutron → keine Ladung.\nElektron → negativ.",
                tags=["atombau"], spiral=["K-ATOM"]),
        aufgabe("PS05-A4-004", "A", 4, "numeric",
                "Ein Atom hat 6 Protonen und 6 Neutronen. Wie groß ist die Massenzahl?",
                answer=12, tolerance=0,
                hints=["Massenzahl = Protonen + Neutronen.", "6 + 6.", "12."],
                solution="6 + 6 = 12. Elektronen zählen nicht mit, sie sind fast masselos.",
                misconceptions=[fv("elektronen_mitgezaehlt", 18,
                                   "Elektronen zählen bei der Massenzahl nicht mit — sie sind rund 2000-mal leichter als ein Proton.",
                                   "ion_und_atom_verwechselt")],
                tags=["atombau", "rechnen"], spiral=["K-ATOM"]),
        aufgabe("PS05-B1-005", "B", 1, "numeric",
                "Ein Atom hat die Massenzahl 23 und die Ordnungszahl 11. Wie viele Neutronen hat es?",
                answer=12, tolerance=0,
                hints=["Neutronen = Massenzahl − Ordnungszahl.", "23 − 11.", "12."],
                solution="23 − 11 = 12 Neutronen. Das Atom ist Natrium.",
                misconceptions=[fv("massenzahl_als_neutronen", 23,
                                   "Die Massenzahl zählt Protonen und Neutronen zusammen. Zieh die Ordnungszahl ab.",
                                   "ion_und_atom_verwechselt")],
                tags=["atombau", "rechnen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS05-B2-006", "B", 2, "multi",
                "Ein Atom hat die Ordnungszahl 17 und die Massenzahl 35.",
                fields=[
                    {"label": "Protonen", "answer": 17, "tolerance": 0},
                    {"label": "Neutronen", "answer": 18, "tolerance": 0,
                     "misconceptions": [fv("massenzahl_als_neutronen", 35,
                                           "Neutronen = Massenzahl − Ordnungszahl = 35 − 17.",
                                           "ion_und_atom_verwechselt")]},
                    {"label": "Elektronen im neutralen Atom", "answer": 17, "tolerance": 0}
                ],
                hints=["Ordnungszahl = Protonen = Elektronen.",
                       "Neutronen = 35 − 17.",
                       "Das Element ist Chlor."],
                solution="Protonen = 17, Elektronen = 17, Neutronen = 35 − 17 = 18. Es ist Chlor-35.",
                tags=["atombau", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS05-B2-007", "B", 2, "choice",
                "Zwei Atome haben beide 17 Protonen, aber 18 bzw. 20 Neutronen. Was sind sie?",
                options=["Isotope desselben Elements", "zwei verschiedene Elemente", "ein Atom und ein Ion"],
                answer=0,
                hints=["Was bestimmt das Element?", "Die Protonenzahl.", "Die ist bei beiden gleich."],
                solution="Gleiche Protonenzahl heißt gleiches Element. Unterschiedliche Neutronenzahl macht sie zu Isotopen — hier Chlor-35 und Chlor-37.",
                misconceptions=[fv("ordnungszahl_aendert_sich", 1,
                                   "Verschiedene Elemente hätten verschiedene Protonenzahlen. Hier ändert sich nur die Neutronenzahl.",
                                   "ion_und_atom_verwechselt")],
                tags=["atombau", "isotope", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS05-B3-008", "B", 3, "numeric",
                "Ein Teilchen hat 11 Protonen und 10 Elektronen. Welche Ladung hat es? (Gib die Zahl mit Vorzeichen an.)",
                answer=1, tolerance=0,
                hints=["Zähle positive und negative Ladungen.",
                       "11 positive, 10 negative.",
                       "Eine positive Ladung bleibt übrig."],
                solution="11 Protonen (+) und 10 Elektronen (−) ergeben eine überschüssige positive Ladung: Na⁺.",
                misconceptions=[fv("ladung_falsch_herum", -1,
                                   "Fehlt ein Elektron, ist das Teilchen <b>positiv</b> geladen.",
                                   "ladung_unvollstaendig")],
                tags=["atombau", "ionen", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS05-B3-009", "B", 3, "choice",
                "Warum wird die Elektronenmasse bei der Massenzahl vernachlässigt?",
                options=["Ein Elektron ist rund 2000-mal leichter als ein Proton.",
                         "Elektronen haben gar keine Masse.",
                         "Elektronen gehören nicht zum Atom."],
                answer=0,
                hints=["Vergleiche die Massen.",
                       "Elektronen sind sehr viel leichter.",
                       "Etwa 1/2000 eines Protons."],
                solution="Ein Elektron hat etwa 1/2000 der Masse eines Protons. Bei der Massenzahl fällt das nicht ins Gewicht — masselos ist es aber nicht.",
                misconceptions=[fv("elektron_masselos", 1,
                                   "Elektronen haben durchaus Masse, nur sehr wenig.")],
                tags=["atombau", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS05-B4-010", "B", 4, "choice",
                "Was ändert sich, wenn ein Atom ein Neutron aufnimmt?",
                options=["Nur die Masse — es bleibt dasselbe Element.",
                         "Es wird ein anderes Element.", "Es wird zu einem Ion."],
                answer=0,
                hints=["Was bestimmt das Element?",
                       "Die Protonenzahl.",
                       "Die bleibt unverändert."],
                solution="Ein zusätzliches Neutron erhöht die Massenzahl. Protonenzahl und Elektronenzahl bleiben gleich — es entsteht ein Isotop desselben Elements, kein Ion und kein anderes Element.",
                misconceptions=[fv("ordnungszahl_aendert_sich", 1,
                                   "Ein anderes Element entstünde nur bei einer anderen Protonenzahl.",
                                   "ion_und_atom_verwechselt")],
                tags=["atombau", "msa"], spiral=["K-ATOM"]),
        aufgabe("PS05-C2-011", "C", 2, "choice",
                "Warum steht bei Chlor im Periodensystem die Atommasse 35,5, obwohl kein Chloratom diese Masse hat?",
                options=["Es ist der gewichtete Mittelwert aus Chlor-35 und Chlor-37.",
                         "Es ist ein Messfehler.",
                         "Chloratome haben tatsächlich halbe Neutronen."],
                answer=0,
                hints=["Chlor kommt in zwei Isotopen vor.",
                       "Beide sind unterschiedlich häufig.",
                       "Der Tabellenwert mittelt beide."],
                solution="Natürliches Chlor besteht zu rund 75 % aus Chlor-35 und zu 25 % aus Chlor-37. Der gewichtete Mittelwert ergibt 35,5 — ein Wert, den kein einzelnes Atom besitzt.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 2,
                                   "Halbe Neutronen gibt es nicht. Der Wert ist ein Mittelwert über viele Atome.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["atombau", "isotope", "msa"], spiral=["K-ATOM"]),
        aufgabe("PS05-C3-012", "C", 3, "numeric",
                "Chlor besteht zu 75 % aus Chlor-35 und zu 25 % aus Chlor-37. Wie groß ist die mittlere Atommasse?",
                answer=35.5, tolerance=0.05,
                hints=["Gewichteter Mittelwert: jede Masse mit ihrem Anteil.",
                       "0,75 · 35 + 0,25 · 37.",
                       "26,25 + 9,25."],
                solution="0,75 · 35 + 0,25 · 37 = 26,25 + 9,25 = 35,5",
                misconceptions=[fv("ungewichteter_mittelwert", 36,
                                   "Du hast einfach gemittelt. Chlor-35 kommt dreimal so häufig vor — der Mittelwert muss gewichtet werden.")],
                tags=["atombau", "rechnen", "msa"], spiral=["K-ATOM", "K-QUANT"]),
        aufgabe("PS05-C3-013", "C", 3, "multi",
                "Ein Ion hat 16 Protonen, 16 Neutronen und 18 Elektronen.",
                fields=[
                    {"label": "Massenzahl", "answer": 32, "tolerance": 0},
                    {"label": "Ladung (mit Vorzeichen)", "answer": -2, "tolerance": 0,
                     "misconceptions": [fv("ladung_falsch_herum", 2,
                                           "Mehr Elektronen als Protonen heißt <b>negative</b> Ladung.",
                                           "ladung_unvollstaendig")]}
                ],
                hints=["Massenzahl = Protonen + Neutronen.",
                       "Ladung = Protonen − Elektronen.",
                       "16 − 18 = −2. Es ist ein Sulfid-Ion."],
                solution="A = 16 + 16 = 32\nLadung = 16 − 18 = −2 → S²⁻",
                tags=["atombau", "ionen", "msa"], spiral=["K-ATOM"]),
        aufgabe("PS05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Isotope sind verschiedene Elemente, weil sie verschiedene Massen haben.“ Wie bewertest du das?",
                options=["Falsch — das Element wird durch die Protonenzahl bestimmt, nicht durch die Masse.",
                         "Richtig — verschiedene Masse heißt verschiedenes Element.",
                         "Falsch — Isotope haben gar keine verschiedenen Massen."],
                answer=0,
                hints=["Wovon hängt das chemische Verhalten ab?",
                       "Von den Elektronen.",
                       "Und deren Zahl folgt aus der Protonenzahl."],
                solution="Chemisches Verhalten hängt an der Elektronenhülle, und deren Aufbau folgt aus der Protonenzahl. Isotope verhalten sich chemisch gleich und sind deshalb dasselbe Element — trotz verschiedener Masse.",
                tags=["atombau", "bewerten", "msa"], spiral=["K-ATOM"])
    ]
})

E.append({
    "unit": "PS-06",
    "title": "Atommasse und relative Atommasse",
    "leitidee": "B1",
    "standards": ["K1", "K2.4"],
    "klasse": 7,
    "wortspeicher": ["die Atommasse", "die relative Atommasse", "die atomare Masseneinheit",
                     "das Kohlenstoff-12", "die Molekülmasse"],
    "worterklaerungen": {
        "relative Atommasse": "Eine Verhältniszahl ohne Einheit. Sie vergleicht die Masse eines Atoms mit einer Vergleichsmasse.",
        "atomare Masseneinheit": "Ein Zwölftel der Masse eines Kohlenstoff-12-Atoms."
    },
    "can_do": {
        "A": "Ich lese die Atommasse aus dem Periodensystem ab.",
        "B": "Ich berechne die Masse eines Moleküls aus den Atommassen.",
        "C": "Ich erkläre, warum relative Atommassen ohne Einheit angegeben werden."
    },
    "lernkarten": {
        "A": karte("Zahlen im Periodensystem",
                   "Unter jedem Symbol steht eine Zahl.",
                   ["Sie sagt, wie schwer ein Atom ist.", "Man liest sie einfach ab."],
                   "Die Atommasse steht im Periodensystem.",
                   visual={"type": "pse", "markiert": ["O", "C"], "perioden": 3,
                           "alt": "Periodensystem-Ausschnitt mit Kohlenstoff und Sauerstoff."},
                   beispiel={"titel": "Wasser wiegen", "aufgabe": "Wie schwer ist ein Wassermolekül H₂O?",
                             "schritte": ["2 · 1 für die zwei H", "1 · 16 für das O", "2 + 16 = 18"],
                             "ergebnis": "18",
                             "luecke": {"schritt": 2, "wert": 18}}),
        "B": karte("Massen zusammenzählen",
                   "Die Masse eines Moleküls ist die Summe der Massen seiner Atome. Es geht keine Masse verloren, wenn Atome sich verbinden — das ist dieselbe Aussage wie die Massenerhaltung, nur auf ein Teilchen bezogen.",
                   ["Für jedes Elementsymbol die Atommasse aus dem PSE ablesen.",
                    "Mit dem Index multiplizieren: H₂ heißt 2 · 1.",
                    "Alles addieren. Das Ergebnis ist die Molekülmasse.",
                    "Für die Schule wird gerundet: H = 1, C = 12, N = 14, O = 16, S = 32."],
                   "Molekülmasse = Summe aller Atommassen, jede mit ihrem Index.",
                   visual={"type": "lewis", "molekuel": "h2o", "formel": "H2O",
                           "alt": "Lewis-Formel von Wasser."}),
        "C": karte("Warum ohne Einheit",
                   "Die Masse eines einzelnen Atoms ist unvorstellbar klein — ein Wasserstoffatom wiegt rund 0,0000000000000000000000017 g. Mit solchen Zahlen lässt sich nicht arbeiten.",
                   ["Deshalb wird verglichen statt gewogen: Als Bezug dient ein Zwölftel der Masse eines Kohlenstoff-12-Atoms.",
                    "Ein Sauerstoffatom ist 16-mal so schwer wie diese Einheit. Seine relative Atommasse ist 16 — eine Verhältniszahl ohne Einheit.",
                    "Dieselben Zahlen erscheinen später als molare Masse in g/mol wieder. Das ist kein Zufall, sondern der eigentliche Sinn des Mol-Begriffs."],
                   "Relative Atommasse: ein Verhältnis, keine Masse. Deshalb ohne Einheit.",
                   visual={"type": "pse", "markiert": ["C"], "perioden": 3,
                           "legende": "Kohlenstoff-12 ist der Bezugspunkt aller Atommassen.",
                           "alt": "Periodensystem-Ausschnitt mit hervorgehobenem Kohlenstoff."})
    },
    "formelkarte": {"formeln": ["Molekülmasse = Summe der Atommassen · Indizes"],
                    "saetze": ["H = 1 · C = 12 · N = 14 · O = 16 · S = 32 · Cl = 35,5",
                               "Na = 23 · Mg = 24 · Ca = 40 · Fe = 56 · Cu = 64",
                               "Relative Atommassen sind Verhältniszahlen — sie haben keine Einheit.",
                               "Bezug: ein Zwölftel der Masse eines Kohlenstoff-12-Atoms."]},
    "tasks": [
        aufgabe("PS06-A1-001", "A", 1, "numeric",
                "Wie groß ist die Atommasse von Sauerstoff?",
                answer=16, tolerance=0.5,
                hints=["Sieh im Periodensystem nach.", "Unter dem O steht die Zahl.", "16."],
                solution="Sauerstoff hat die (gerundete) Atommasse 16.",
                tags=["atommasse"], spiral=["K-QUANT"]),
        aufgabe("PS06-A2-002", "A", 2, "numeric",
                "Ein Wasserstoffmolekül besteht aus 2 H-Atomen (je 1). Wie groß ist seine Masse?",
                answer=2, tolerance=0,
                hints=["Zwei Atome, jedes mit der Masse 1.", "2 · 1.", "2."],
                solution="2 · 1 = 2",
                tags=["atommasse"], spiral=["K-BIND"]),
        aufgabe("PS06-A3-003", "A", 3, "numeric",
                "Wie groß ist die Masse eines Wassermoleküls H₂O? (H = 1, O = 16)",
                answer=18, tolerance=0,
                hints=["Zwei H und ein O.", "2 · 1 + 16.", "18."],
                solution="2 · 1 + 1 · 16 = 18",
                misconceptions=[fv("index_uebersehen", 17,
                                   "Der Index 2 gilt für den Wasserstoff: 2 · 1, nicht 1.",
                                   "summenformel_falsch_gelesen")],
                tags=["atommasse", "rechnen"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-A4-004", "A", 4, "numeric",
                "Wie groß ist die Masse von Kohlenstoffdioxid CO₂? (C = 12, O = 16)",
                answer=44, tolerance=0,
                hints=["Ein C und zwei O.", "12 + 2 · 16.", "12 + 32."],
                solution="12 + 2 · 16 = 12 + 32 = 44",
                misconceptions=[fv("index_uebersehen", 28,
                                   "Der Index 2 gilt für den Sauerstoff: 2 · 16 = 32.",
                                   "summenformel_falsch_gelesen")],
                tags=["atommasse", "rechnen"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-B1-005", "B", 1, "numeric",
                "Wie groß ist die Masse von Schwefelsäure H₂SO₄? (H = 1, S = 32, O = 16)",
                answer=98, tolerance=0,
                hints=["Zwei H, ein S, vier O.",
                       "2 · 1 + 32 + 4 · 16.",
                       "2 + 32 + 64."],
                solution="2 · 1 + 32 + 4 · 16 = 2 + 32 + 64 = 98",
                misconceptions=[fv("index_uebersehen", 50,
                                   "Der Index 4 gilt für den Sauerstoff: 4 · 16 = 64.",
                                   "summenformel_falsch_gelesen")],
                tags=["atommasse", "rechnen", "bbr"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-B2-006", "B", 2, "numeric",
                "Wie groß ist die Masse von Calciumcarbonat CaCO₃? (Ca = 40, C = 12, O = 16)",
                answer=100, tolerance=0,
                hints=["Ein Ca, ein C, drei O.",
                       "40 + 12 + 3 · 16.",
                       "40 + 12 + 48."],
                solution="40 + 12 + 3 · 16 = 100",
                tags=["atommasse", "rechnen", "bbr"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-B2-007", "B", 2, "numeric",
                "Wie groß ist die Masse von Ca(OH)₂? (Ca = 40, O = 16, H = 1)",
                answer=74, tolerance=0,
                hints=["Die 2 hinter der Klammer gilt für OH insgesamt.",
                       "40 + 2 · (16 + 1).",
                       "40 + 34."],
                solution="40 + 2 · (16 + 1) = 40 + 34 = 74",
                misconceptions=[fv("klammer_ignoriert", 57,
                                   "Die 2 hinter der Klammer verdoppelt <b>alles</b> in der Klammer, also O und H.",
                                   "summenformel_falsch_gelesen")],
                tags=["atommasse", "rechnen", "bbr"], spiral=["K-BIND"]),
        aufgabe("PS06-B3-008", "B", 3, "multi",
                "Berechne die Massen der folgenden Teilchen. (H = 1, N = 14, O = 16, S = 32)",
                fields=[
                    {"label": "NH₃", "answer": 17, "tolerance": 0},
                    {"label": "SO₂", "answer": 64, "tolerance": 0},
                    {"label": "HNO₃", "answer": 63, "tolerance": 0}
                ],
                hints=["Jeden Index einzeln beachten.",
                       "NH₃ = 14 + 3 · 1.",
                       "HNO₃ = 1 + 14 + 3 · 16."],
                solution="NH₃ = 14 + 3 = 17\nSO₂ = 32 + 2 · 16 = 64\nHNO₃ = 1 + 14 + 48 = 63",
                tags=["atommasse", "rechnen", "bbr"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-B3-009", "B", 3, "numeric",
                "Wie viel Prozent der Masse von Wasser H₂O entfallen auf den Sauerstoff?",
                answer=88.9, unit_label="%", tolerance=0.3,
                hints=["Masse des Sauerstoffs durch Gesamtmasse.",
                       "16 : 18.",
                       "Ergebnis mal 100."],
                solution="16 : 18 = 0,889 → 88,9 %",
                misconceptions=[fv("anteil_umgedreht", 11.1,
                                   "Das ist der Wasserstoffanteil. Gefragt war der Sauerstoff.")],
                tags=["atommasse", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("PS06-B4-010", "B", 4, "choice",
                "Warum hat die relative Atommasse keine Einheit?",
                options=["Sie ist ein Verhältnis zu einer Vergleichsmasse.",
                         "Weil man die Einheit weglassen darf.",
                         "Weil Atome keine Masse haben."],
                answer=0,
                hints=["Was wird verglichen?",
                       "Die Atommasse mit einer Bezugsmasse.",
                       "Ein Verhältnis hat keine Einheit."],
                solution="Verglichen wird mit einem Zwölftel der Masse eines Kohlenstoff-12-Atoms. Ein Verhältnis zweier Massen ist eine reine Zahl — deshalb ohne Einheit.",
                tags=["atommasse", "msa"], spiral=["K-QUANT"]),
        aufgabe("PS06-C2-011", "C", 2, "choice",
                "Warum wurde ausgerechnet Kohlenstoff-12 als Bezug gewählt?",
                options=["Es ist ein gut verfügbares, genau messbares Isotop — die Wahl ist eine Verabredung.",
                         "Kohlenstoff ist das häufigste Element.",
                         "Kohlenstoff hat die kleinste Atommasse."],
                answer=0,
                hints=["Gibt es einen physikalischen Zwang zu dieser Wahl?",
                       "Nein.",
                       "Es ist eine praktische Verabredung."],
                solution="Der Bezugspunkt ist eine Verabredung. Kohlenstoff-12 ist gut verfügbar und sehr genau messbar. Früher diente Wasserstoff als Bezug — die Zahlen verschoben sich dadurch leicht.",
                tags=["atommasse", "msa"]),
        aufgabe("PS06-C3-012", "C", 3, "multi",
                "Berechne für Ammoniumsulfat (NH₄)₂SO₄. (N = 14, H = 1, S = 32, O = 16)",
                fields=[
                    {"label": "Masse des Teilchens", "answer": 132, "tolerance": 0,
                     "misconceptions": [fv("klammer_ignoriert", 114,
                                           "Die 2 hinter der Klammer verdoppelt NH₄ vollständig: 2 · 18 = 36.",
                                           "summenformel_falsch_gelesen")]},
                    {"label": "Zahl der Wasserstoffatome", "answer": 8, "tolerance": 0},
                    {"label": "Massenanteil des Stickstoffs in Prozent", "answer": 21.2, "unit_label": "%", "tolerance": 0.3}
                ],
                hints=["(NH₄)₂ heißt 2 · (14 + 4) = 36.",
                       "Dazu SO₄ = 32 + 64 = 96.",
                       "Stickstoff: 2 · 14 = 28; 28 : 132."],
                solution="(NH₄)₂ = 2 · 18 = 36\nSO₄ = 32 + 4 · 16 = 96\ngesamt = 132\nH-Atome: 2 · 4 = 8\nw(N) = 28 : 132 = 21,2 %",
                tags=["atommasse", "rechnen", "msa"], spiral=["K-BIND", "K-QUANT"]),
        aufgabe("PS06-C3-013", "C", 3, "choice",
                "Warum entsprechen die Zahlen der relativen Atommasse später genau der molaren Masse in g/mol?",
                options=["Das Mol ist genau so definiert, dass diese Zahlen übereinstimmen.",
                         "Es ist ein Zufall.",
                         "Weil Gramm und atomare Masseneinheit dasselbe sind."],
                answer=0,
                hints=["Warum wurde das Mol so festgelegt?",
                       "Damit man die Zahlen direkt übernehmen kann.",
                       "Das ist der Sinn der Definition."],
                solution="Die Stoffmenge Mol ist genau so definiert, dass die relative Atommasse zahlengleich zur molaren Masse in g/mol ist. Damit lässt sich vom Periodensystem direkt in eine Wägung übersetzen — der eigentliche Nutzen des Mol-Begriffs.",
                tags=["atommasse", "msa"], spiral=["K-QUANT"]),
        aufgabe("PS06-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt: „Die Atommasse von Sauerstoff ist 16 g.“ Was ist daran falsch?",
                options=["Die relative Atommasse hat keine Einheit; 16 g/mol wäre die molare Masse.",
                         "Nichts, die Angabe ist richtig.",
                         "Sauerstoff hat die Atommasse 32."],
                answer=0,
                hints=["Welche Einheit gehört zur relativen Atommasse?",
                       "Gar keine.",
                       "16 g/mol wäre etwas anderes."],
                solution="Die relative Atommasse ist eine Verhältniszahl ohne Einheit: 16. Die molare Masse beträgt 16 g/mol — ein einzelnes Sauerstoffatom wiegt dagegen rund 2,7 · 10⁻²³ g. Die 32 gehört zum Molekül O₂.",
                misconceptions=[fv("groesse_und_einheit_verwechselt", 2,
                                   "32 ist die Masse des Moleküls O₂, nicht des Atoms.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["atommasse", "bewerten", "msa"], spiral=["K-QUANT"])
    ]
})

if __name__ == "__main__":
    schreiben("ps", E, "Bereich PS · Einheiten 5 und 6")
