# -*- coding: utf-8 -*-
"""Bereich SL · Säuren und Laugen — SL-03 bis SL-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "SL-03",
    "title": "Saure Lösungen: Protolyse",
    "leitidee": "B3",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 9,
    "wortspeicher": ["die Protolyse", "das Proton", "das Oxonium-Ion", "der Protonendonator",
                     "der Protonenakzeptor", "die saure Lösung"],
    "worterklaerungen": {
        "Protolyse": "Die Übertragung eines Protons von einem Teilchen auf ein anderes.",
        "Oxonium-Ion": "H₃O⁺. Es entsteht, wenn ein Wassermolekül ein Proton aufnimmt.",
        "Protonendonator": "Der Stoff, der ein Proton abgibt — die Säure."
    },
    "can_do": {
        "A": "Ich weiß, dass in sauren Lösungen Oxonium-Ionen vorliegen.",
        "B": "Ich beschreibe die Protolyse und benenne Donator und Akzeptor.",
        "C": "Ich erkläre den Unterschied zwischen Säure und saurer Lösung und die Rolle des Wassers."
    },
    "lernkarten": {
        "A": karte("Was eine Lösung sauer macht",
                   "Eine Säure gibt im Wasser etwas ab.",
                   ["Sie gibt ein Proton ab.", "Das Wasser nimmt es auf."],
                   "Oxonium-Ionen H₃O⁺ machen eine Lösung sauer.",
                   visual=anim("protolyse", "A"),
                   beispiel={"titel": "Chlorwasserstoff im Wasser",
                             "aufgabe": "HCl wird in Wasser gegeben.",
                             "schritte": ["HCl gibt ein Proton ab.",
                                          "Wasser nimmt es auf und wird zu H₃O⁺.",
                                          "Zurück bleibt Cl⁻."],
                             "ergebnis": "HCl + H₂O → H₃O⁺ + Cl⁻"}),
        "B": karte("Donator und Akzeptor",
                   "Eine Protolyse braucht immer zwei Partner: einen, der ein Proton abgibt, und einen, der es aufnimmt. Allein geht es nicht.",
                   ["Die Säure ist der Protonendonator — sie gibt ab.",
                    "Das Wasser ist hier der Protonenakzeptor — es nimmt auf und wird zum Oxonium-Ion H₃O⁺.",
                    "Zurück bleibt das Säurerest-Ion, etwa Cl⁻ oder SO₄²⁻.",
                    "Mehrprotonige Säuren wie H₂SO₄ können mehrere Protonen abgeben — schrittweise."],
                   "Säure gibt ab, Wasser nimmt auf. Ohne Akzeptor keine Protolyse.",
                   visual=anim("protolyse", "B")),
        "C": karte("Säure und saure Lösung",
                   "Zwei Begriffe, die im Alltag zusammenfallen und in der Chemie streng zu trennen sind.",
                   ["Eine Säure ist ein Stoff, der Protonen abgeben kann — etwa Chlorwasserstoff, ein Gas.",
                    "Eine saure Lösung entsteht erst, wenn dieser Stoff in Wasser gelöst wird und Oxonium-Ionen entstehen.",
                    "Der Beleg: Trockenes Chlorwasserstoffgas färbt trockenes Indikatorpapier nicht. Erst ein Tropfen Wasser löst die Farbreaktion aus.",
                    "Starke Säuren geben ihre Protonen nahezu vollständig ab, schwache nur teilweise. Deshalb ist eine verdünnte starke Säure saurer als eine konzentrierte schwache — Stärke und Konzentration sind zwei verschiedene Dinge."],
                   "Die Säure ist der Stoff. Die saure Lösung entsteht erst mit dem Wasser.",
                   visual=anim("protolyse", "C"))
    },
    "formelkarte": {"formeln": ["HCl + H₂O → H₃O⁺ + Cl⁻",
                               "H₂SO₄ + 2 H₂O → 2 H₃O⁺ + SO₄²⁻",
                               "CH₃COOH + H₂O ⇌ H₃O⁺ + CH₃COO⁻"],
                    "saetze": ["Protolyse: Übertragung eines Protons.",
                               "Säure = Protonendonator, Wasser = Protonenakzeptor.",
                               "H₃O⁺ macht die Lösung sauer.",
                               "Stärke und Konzentration sind zwei verschiedene Dinge."]},
    "tasks": [
        aufgabe("SL03-A1-001", "A", 1, "choice",
                "Was gibt eine Säure im Wasser ab?",
                options=["ein Proton", "ein Elektron", "ein Neutron"], answer=0,
                visual=anim("protolyse", "A"),
                hints=["Es ist ein Wasserstoff-Ion.", "Ein H⁺ ist ein Proton.", "Ein Proton."],
                solution="Eine Säure gibt ein Proton — ein H⁺-Ion — ab.",
                misconceptions=[fv("oxidation_reduktion_vertauscht", 1,
                                   "Elektronen werden bei Redoxreaktionen übertragen. Bei Säuren sind es Protonen.",
                                   "oxidation_reduktion_vertauscht")],
                tags=["protolyse"], spiral=["K-BIND"]),
        aufgabe("SL03-A2-002", "A", 2, "choice",
                "Welches Teilchen macht eine Lösung sauer?",
                options=["H₃O⁺", "OH⁻", "H₂O"], answer=0,
                hints=["Es entsteht, wenn Wasser ein Proton aufnimmt.",
                       "Es heißt Oxonium-Ion.",
                       "H₃O⁺."],
                solution="Das Oxonium-Ion H₃O⁺ macht eine Lösung sauer. OH⁻ macht sie alkalisch.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "OH⁻ ist das Hydroxid-Ion — es macht eine Lösung alkalisch.",
                                   "saeure_lauge_vertauscht")],
                tags=["protolyse"], spiral=["K-BIND"]),
        aufgabe("SL03-A3-003", "A", 3, "choice",
                "HCl + H₂O → H₃O⁺ + Cl⁻. Was ist aus dem Wasser geworden?",
                options=["ein Oxonium-Ion", "ein Hydroxid-Ion", "nichts"], answer=0,
                hints=["Es hat ein Proton aufgenommen.", "Aus H₂O wird H₃O⁺.", "Ein Oxonium-Ion."],
                solution="Das Wassermolekül hat ein Proton aufgenommen und ist zum Oxonium-Ion H₃O⁺ geworden.",
                tags=["protolyse"], spiral=["K-BIND"]),
        aufgabe("SL03-A4-004", "A", 4, "choice",
                "Warum färbt trockenes Chlorwasserstoffgas trockenes Indikatorpapier nicht?",
                options=["Ohne Wasser entstehen keine Oxonium-Ionen.", "Das Gas ist zu kalt.", "Das Papier ist zu dick."],
                answer=0,
                hints=["Was braucht die Protolyse?", "Einen Partner, der das Proton aufnimmt.", "Das Wasser."],
                solution="Ohne Wasser gibt es keinen Protonenakzeptor und damit keine Oxonium-Ionen. Erst ein Tropfen Wasser lässt den Indikator umschlagen.",
                tags=["protolyse", "msa"], spiral=["K-SL"]),
        aufgabe("SL03-B1-005", "B", 1, "choice",
                "Wer ist in HCl + H₂O → H₃O⁺ + Cl⁻ der Protonendonator?",
                options=["HCl", "H₂O", "Cl⁻"], answer=0,
                hints=["Wer gibt das Proton ab?", "Das HCl.", "Es ist der Donator."],
                solution="HCl gibt das Proton ab und ist damit der Protonendonator. Wasser nimmt es auf und ist der Akzeptor.",
                misconceptions=[fv("edukt_produkt_vertauscht", 1,
                                   "Wasser nimmt auf — es ist der Akzeptor.",
                                   "edukt_produkt_vertauscht")],
                tags=["protolyse", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL03-B2-006", "B", 2, "numeric",
                "Wie viele Protonen kann ein Molekül Schwefelsäure H₂SO₄ abgeben?",
                answer=2, tolerance=0,
                hints=["Sieh dir die Formel an.", "Wie viele H-Atome stehen vorn?", "Zwei."],
                solution="H₂SO₄ kann zwei Protonen abgeben — sie ist eine zweiprotonige Säure. Die Abgabe erfolgt schrittweise.",
                misconceptions=[fv("index_uebersehen", 1,
                                   "Der Index 2 am Wasserstoff sagt: zwei abgebbare Protonen.",
                                   "summenformel_falsch_gelesen")],
                tags=["protolyse", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL03-B2-007", "B", 2, "choice",
                "Was bleibt zurück, wenn Salpetersäure HNO₃ ein Proton abgibt?",
                options=["NO₃⁻", "NO₃", "HNO₂"], answer=0,
                hints=["Das H wird abgegeben.", "Zurück bleibt der Rest mit einer negativen Ladung.", "NO₃⁻."],
                solution="Gibt HNO₃ ein Proton ab, bleibt das Nitrat-Ion NO₃⁻ zurück. Die negative Ladung stammt vom zurückbleibenden Elektron.",
                misconceptions=[fv("ladung_unvollstaendig", 1,
                                   "Das Proton nimmt sein Elektron nicht mit — der Rest bleibt negativ geladen.",
                                   "ladung_unvollstaendig")],
                tags=["protolyse", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL03-B3-008", "B", 3, "assign",
                "Ordne jeder Säure ihr Säurerest-Ion zu.",
                slots=["HCl", "H₂SO₄", "HNO₃"],
                values=["Cl⁻ (Chlorid)", "SO₄²⁻ (Sulfat)", "NO₃⁻ (Nitrat)"], answer=[0, 1, 2],
                hints=["Jedes H wird abgegeben.",
                       "Die Zahl der abgegebenen Protonen ist die Ladung.",
                       "H₂SO₄ gibt zwei ab."],
                solution="HCl → Cl⁻, H₂SO₄ → SO₄²⁻, HNO₃ → NO₃⁻.",
                tags=["protolyse", "bbr"], spiral=["K-BIND"]),
        aufgabe("SL03-B3-009", "B", 3, "choice",
                "Warum ist Essigsäure eine schwache Säure?",
                options=["Sie gibt nur einen Teil ihrer Protonen ab; die Reaktion ist unvollständig.",
                         "Sie enthält weniger Wasserstoff.",
                         "Sie ist stark verdünnt."],
                answer=0,
                hints=["Was unterscheidet stark und schwach?",
                       "Wie vollständig die Protonen abgegeben werden.",
                       "Bei Essigsäure nur teilweise."],
                solution="Bei einer starken Säure werden praktisch alle Protonen abgegeben, bei einer schwachen nur ein kleiner Teil. Deshalb steht in der Gleichung der Essigsäure ein Gleichgewichtspfeil. Mit der Konzentration hat das nichts zu tun.",
                misconceptions=[fv("staerke_und_konzentration", 2,
                                   "Stärke und Konzentration sind zwei verschiedene Dinge. Auch konzentrierte Essigsäure bleibt eine schwache Säure.")],
                tags=["protolyse", "msa"], spiral=["K-SL"]),
        aufgabe("SL03-B4-010", "B", 4, "choice",
                "Was ist der Unterschied zwischen einer Säure und einer sauren Lösung?",
                options=["Die Säure ist der Stoff; die saure Lösung entsteht erst durch Protolyse im Wasser.",
                         "Es ist dasselbe.",
                         "Eine saure Lösung ist verdünnter."],
                answer=0,
                hints=["Ist reines HCl-Gas eine saure Lösung?",
                       "Nein — es ist ein Gas.",
                       "Erst im Wasser entstehen die Ionen."],
                solution="Chlorwasserstoff ist ein Gas und eine Säure. Erst gelöst in Wasser entstehen Oxonium-Ionen — dann liegt eine saure Lösung vor. Die Unterscheidung ist keine Spitzfindigkeit, sondern erklärt den Indikatorversuch.",
                tags=["protolyse", "msa"], spiral=["K-SL"]),
        aufgabe("SL03-C2-011", "C", 2, "choice",
                "Warum ist verdünnte Salzsäure saurer als konzentrierte Essigsäure gleicher Stoffmengenkonzentration?",
                options=["Salzsäure ist eine starke Säure und gibt ihre Protonen praktisch vollständig ab.",
                         "Salzsäure enthält mehr Wasserstoffatome.",
                         "Essigsäure ist gar keine Säure."],
                answer=0,
                hints=["Was bedeutet stark und schwach?",
                       "Wie vollständig die Protonen abgegeben werden.",
                       "Salzsäure gibt fast alle ab."],
                solution="Salzsäure gibt bei gleicher Stoffmengenkonzentration nahezu alle Protonen ab, Essigsäure nur wenige Prozent. Die Zahl der Oxonium-Ionen ist deshalb deutlich höher — Stärke schlägt Konzentration.",
                tags=["protolyse", "msa"], spiral=["K-SL"]),
        aufgabe("SL03-C3-012", "C", 3, "choice",
                "Warum steht in der Gleichung der Essigsäure ein Doppelpfeil, bei Salzsäure aber nicht?",
                options=["Bei der schwachen Säure stellt sich ein Gleichgewicht ein; die Reaktion läuft nicht vollständig ab.",
                         "Der Doppelpfeil ist Geschmackssache.",
                         "Essigsäure reagiert in beide Richtungen gleich schnell wie Salzsäure."],
                answer=0,
                hints=["Was bedeutet ein Doppelpfeil?",
                       "Beide Richtungen laufen ab.",
                       "Bei starker Säure ist die Rückreaktion vernachlässigbar."],
                solution="Der Doppelpfeil zeigt ein Gleichgewicht an: Nur ein Teil der Essigsäuremoleküle hat ein Proton abgegeben. Bei Salzsäure ist die Rückreaktion vernachlässigbar — deshalb der einfache Pfeil.",
                tags=["protolyse", "msa"], spiral=["K-REAK"]),
        aufgabe("SL03-C3-013", "C", 3, "multi",
                "0,1 mol Salzsäure werden in 1 L Wasser gelöst und geben ihre Protonen vollständig ab.",
                fields=[
                    {"label": "Stoffmenge der Oxonium-Ionen", "answer": 0.1, "unit_label": "mol", "tolerance": 0.005},
                    {"label": "Konzentration in mol/L", "answer": 0.1, "unit_label": "mol/L", "tolerance": 0.005},
                    {"label": "pH-Wert", "answer": 1, "tolerance": 0.1}
                ],
                hints=["Jedes HCl liefert ein H₃O⁺.",
                       "c = n : V = 0,1 : 1.",
                       "0,1 mol/L entspricht pH 1."],
                solution="n(H₃O⁺) = 0,1 mol\nc = 0,1 mol/L\n0,1 = 10⁻¹ → pH 1",
                tags=["protolyse", "msa"], spiral=["K-QUANT", "K-SL"]),
        aufgabe("SL03-C4-014", "C", 4, "choice",
                "Ein Schüler schreibt: „HCl → H⁺ + Cl⁻“. Was fehlt in dieser Darstellung?",
                options=["Das Wasser als Protonenakzeptor — ein freies Proton existiert in Lösung nicht.",
                         "Nichts, die Gleichung ist vollständig.",
                         "Die Ladungen stimmen nicht."],
                answer=0,
                hints=["Kann ein Proton allein in Lösung sein?",
                       "Nein — es wird sofort gebunden.",
                       "Vom Wasser."],
                solution="Ein freies Proton ist in wässriger Lösung nicht existent — es wird sofort von einem Wassermolekül gebunden. Die vollständige Gleichung lautet HCl + H₂O → H₃O⁺ + Cl⁻. Die Kurzform ist eine zulässige Vereinfachung, verdeckt aber die Rolle des Wassers.",
                tags=["protolyse", "bewerten", "msa"], spiral=["K-REAK"])
    ]
})

E.append({
    "unit": "SL-04",
    "title": "Laugen: Hydroxid-Ionen und Basen",
    "leitidee": "B3",
    "standards": ["K1", "K2.2", "K3.4"],
    "klasse": 9,
    "sicherheit": [
        "Natronlauge ist stark ätzend und greift besonders die Augen an. Schutzbrille ist Pflicht.",
        "Laugenreste gehören in den Sammelbehälter, nicht in den Ausguss."
    ],
    "wortspeicher": ["die Lauge", "die Base", "das Hydroxid-Ion", "die Natronlauge",
                     "alkalisch", "der Protonenakzeptor"],
    "worterklaerungen": {
        "Lauge": "Eine alkalische wässrige Lösung. Sie enthält Hydroxid-Ionen.",
        "Base": "Ein Stoff, der Protonen aufnehmen kann.",
        "Hydroxid-Ion": "OH⁻. Es macht eine Lösung alkalisch."
    },
    "can_do": {
        "A": "Ich weiß, dass Laugen Hydroxid-Ionen enthalten, und kenne Beispiele.",
        "B": "Ich beschreibe die Bildung einer Lauge und ihre Eigenschaften.",
        "C": "Ich erkläre den Basenbegriff über die Protonenaufnahme und vergleiche Base und Lauge."
    },
    "lernkarten": {
        "A": karte("Das Gegenstück zur Säure",
                   "Laugen fühlen sich seifig an und färben den Indikator blau.",
                   ["Sie enthalten Hydroxid-Ionen OH⁻.", "Seifenlauge und Rohrreiniger sind Laugen."],
                   "OH⁻ macht eine Lösung alkalisch.",
                   visual={"type": "phskala", "marken": [{"wert": 10, "stoff": "Seifenlauge"},
                                                         {"wert": 13, "stoff": "Rohrreiniger"}],
                           "alt": "pH-Skala mit alkalischen Marken."},
                   beispiel={"titel": "Natronlauge", "aufgabe": "Natriumhydroxid wird in Wasser gelöst.",
                             "schritte": ["Es zerfällt in Na⁺ und OH⁻.",
                                          "Die OH⁻-Ionen machen die Lösung alkalisch."],
                             "ergebnis": "Eine Lauge ist entstanden."}),
        "B": karte("Wie Laugen entstehen",
                   "Es gibt zwei Wege zu einer Lauge, und beide enden bei denselben Teilchen.",
                   ["Ein Metallhydroxid wie NaOH löst sich und liefert direkt Na⁺ und OH⁻.",
                    "Ein Metalloxid wie CaO reagiert mit Wasser: CaO + H₂O → Ca(OH)₂. Auch hier entstehen Hydroxid-Ionen.",
                    "Ammoniak nimmt dagegen ein Proton aus dem Wasser auf: NH₃ + H₂O ⇌ NH₄⁺ + OH⁻. Auch dabei entsteht OH⁻.",
                    "Laugen fühlen sich seifig an, weil sie Fett der Haut in Seife umwandeln. Genau das macht sie gefährlich für die Augen."],
                   "Ob gelöst, aus Oxid gebildet oder durch Protonenaufnahme — entscheidend ist das entstehende OH⁻.",
                   visual=anim("phwert", "B")),
        "C": karte("Base ist mehr als Lauge",
                   "Wie bei den Säuren gibt es auch hier zwei Begriffe, die getrennt gehören.",
                   ["Eine Base ist ein Stoff, der Protonen aufnehmen kann — der Protonenakzeptor.",
                    "Eine Lauge ist die wässrige, alkalische Lösung einer Base.",
                    "Ammoniak ist ein Gas und eine Base. Erst in Wasser entsteht daraus eine Lauge.",
                    "Auch Wasser kann als Base wirken: Gegenüber HCl nimmt es ein Proton auf. Gegenüber Ammoniak gibt es eines ab — dann wirkt es als Säure. Ob ein Stoff Säure oder Base ist, hängt vom Partner ab."],
                   "Base = Protonenakzeptor. Lauge = ihre wässrige Lösung.",
                   visual=anim("protolyse", "C"))
    },
    "formelkarte": {"formeln": ["NaOH → Na⁺ + OH⁻",
                               "CaO + H₂O → Ca(OH)₂",
                               "NH₃ + H₂O ⇌ NH₄⁺ + OH⁻"],
                    "saetze": ["OH⁻ macht eine Lösung alkalisch.",
                               "Base = Protonenakzeptor, Lauge = wässrige Lösung einer Base.",
                               "Metalloxid + Wasser → Lauge.",
                               "Laugen greifen besonders die Augen an."]},
    "tasks": [
        aufgabe("SL04-A1-001", "A", 1, "choice",
                "Welches Teilchen macht eine Lösung alkalisch?",
                options=["OH⁻", "H₃O⁺", "H₂O"], answer=0,
                hints=["Es ist das Gegenstück zum Oxonium-Ion.", "Es heißt Hydroxid-Ion.", "OH⁻."],
                solution="Das Hydroxid-Ion OH⁻ macht eine Lösung alkalisch.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "H₃O⁺ macht eine Lösung sauer, nicht alkalisch.",
                                   "saeure_lauge_vertauscht")],
                tags=["laugen"], spiral=["K-BIND"]),
        aufgabe("SL04-A2-002", "A", 2, "choice",
                "Wie färbt sich Universalindikator in einer Lauge?",
                options=["blau", "rot", "gelb"], answer=0,
                hints=["Alkalisch liegt rechts auf der Skala.", "Dort ist die Farbe blau.", "Blau."],
                solution="In alkalischen Lösungen färbt sich der Indikator blau.",
                tags=["laugen"], spiral=["K-SL"]),
        aufgabe("SL04-A3-003", "A", 3, "choice",
                "Was entsteht, wenn Natriumhydroxid NaOH in Wasser gelöst wird?",
                options=["Na⁺ und OH⁻", "Na und OH", "H₃O⁺ und Cl⁻"], answer=0,
                hints=["Es ist ein Salz aus zwei Ionen.", "Beim Lösen werden sie frei.", "Na⁺ und OH⁻."],
                solution="NaOH zerfällt beim Lösen in Na⁺ und OH⁻. Die Hydroxid-Ionen machen die Lösung alkalisch.",
                tags=["laugen"], spiral=["K-BIND"]),
        aufgabe("SL04-A4-004", "A", 4, "choice",
                "Warum ist Natronlauge besonders für die Augen gefährlich?",
                options=["Sie wandelt Fett in Seife um und zerstört so das Gewebe.",
                         "Sie ist sehr kalt.", "Sie leuchtet."],
                answer=0,
                hints=["Warum fühlen sich Laugen seifig an?",
                       "Sie verseifen Fett.",
                       "Das Auge besteht aus empfindlichem Gewebe."],
                solution="Laugen verseifen Fett — deshalb das seifige Gefühl auf der Haut. Im Auge zerstört das binnen Sekunden Gewebe. Deshalb ist die Schutzbrille bei Laugen besonders wichtig.",
                tags=["laugen", "sicherheit"]),
        aufgabe("SL04-B1-005", "B", 1, "choice",
                "Was entsteht, wenn Calciumoxid CaO in Wasser gegeben wird?",
                options=["Calciumhydroxid — eine Lauge", "eine Säure", "nichts"], answer=0,
                hints=["Calcium ist ein Metall.", "Metalloxid + Wasser → Lauge.", "Es entsteht Ca(OH)₂."],
                solution="CaO + H₂O → Ca(OH)₂. Metalloxide bilden mit Wasser Laugen — der Indikator wird blau.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "Säuren entstehen aus Nichtmetalloxiden. Calcium ist ein Metall.",
                                   "saeure_lauge_vertauscht")],
                tags=["laugen", "bbr"], spiral=["K-REAK"]),
        aufgabe("SL04-B2-006", "B", 2, "choice",
                "Ammoniak NH₃ ist ein Gas. Warum reagiert seine wässrige Lösung alkalisch?",
                options=["Ammoniak nimmt dem Wasser ein Proton ab; dabei entstehen OH⁻-Ionen.",
                         "Ammoniak enthält selbst OH⁻.",
                         "Ammoniak ist ein Metallhydroxid."],
                answer=0,
                hints=["Ammoniak enthält kein OH.",
                       "Woher kommen die Hydroxid-Ionen dann?",
                       "Aus dem Wasser."],
                solution="NH₃ + H₂O ⇌ NH₄⁺ + OH⁻. Ammoniak nimmt ein Proton auf, das Wasser bleibt als OH⁻ zurück. Deshalb ist es eine Base, obwohl es kein OH enthält.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "In NH₃ steckt kein OH. Es stammt aus dem Wasser.",
                                   "summenformel_falsch_gelesen")],
                tags=["laugen", "msa"], spiral=["K-REAK"]),
        aufgabe("SL04-B2-007", "B", 2, "assign",
                "Ordne jedem Stoff die entstehende Lösung zu.",
                slots=["Natriumoxid Na₂O", "Schwefeldioxid SO₂", "Natriumhydroxid NaOH"],
                values=["Lauge", "Säure", "Lauge (zweites)"],
                answer=[0, 1, 2],
                hints=["Metalloxid + Wasser → Lauge.",
                       "Nichtmetalloxid + Wasser → Säure.",
                       "Schwefel ist ein Nichtmetall."],
                solution="Na₂O → Lauge (Metalloxid).\nSO₂ → Säure (Nichtmetalloxid).\nNaOH → Lauge (Hydroxid).",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "Merke: Metalloxide bilden Laugen, Nichtmetalloxide bilden Säuren.",
                                   "saeure_lauge_vertauscht")],
                tags=["laugen", "bbr"], spiral=["K-REAK"]),
        aufgabe("SL04-B3-008", "B", 3, "choice",
                "Was ist der Unterschied zwischen einer Base und einer Lauge?",
                options=["Die Base ist der Stoff, die Lauge ihre wässrige Lösung.",
                         "Es ist dasselbe.",
                         "Eine Lauge ist stärker."],
                answer=0,
                hints=["Ist Ammoniakgas eine Lauge?",
                       "Nein, es ist ein Gas.",
                       "Erst gelöst ergibt es eine Lauge."],
                solution="Ammoniak ist ein Gas und eine Base. Gelöst in Wasser entsteht daraus eine Lauge. Die Unterscheidung entspricht genau der zwischen Säure und saurer Lösung.",
                tags=["laugen", "msa"], spiral=["K-SL"]),
        aufgabe("SL04-B3-009", "B", 3, "numeric",
                "Eine Natronlauge enthält 4 g NaOH (M = 40 g/mol) in 1 L. Wie groß ist die Stoffmengenkonzentration?",
                answer=0.1, unit_label="mol/L", tolerance=0.005,
                hints=["Erst n = m : M.", "4 : 40 = 0,1 mol.", "c = n : V."],
                solution="n = 4 g : 40 g/mol = 0,1 mol\nc = 0,1 mol : 1 L = 0,1 mol/L",
                tags=["laugen", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("SL04-B4-010", "B", 4, "choice",
                "Warum reagiert eine Lösung von Seife leicht alkalisch?",
                options=["Seifen sind Salze schwacher Säuren; ihre Anionen nehmen Protonen aus dem Wasser auf.",
                         "Seife enthält Natronlauge.",
                         "Seife ist ein Metalloxid."],
                answer=0,
                hints=["Woraus besteht Seife?",
                       "Aus dem Natriumsalz einer Fettsäure.",
                       "Das Anion einer schwachen Säure ist eine Base."],
                solution="Seifen sind Natriumsalze schwacher Fettsäuren. Ihre Anionen nehmen im Wasser Protonen auf, dabei entstehen OH⁻-Ionen. Deshalb reagiert Seifenlösung alkalisch.",
                tags=["laugen", "msa"], spiral=["K-SL"]),
        aufgabe("SL04-C2-011", "C", 2, "choice",
                "Wasser reagiert mit HCl als Base, mit Ammoniak als Säure. Wie ist das möglich?",
                options=["Ob ein Stoff als Säure oder Base wirkt, hängt vom Reaktionspartner ab.",
                         "Wasser ist immer neutral.",
                         "Eine der beiden Reaktionen läuft nicht ab."],
                answer=0,
                hints=["Gegenüber HCl nimmt Wasser ein Proton auf.",
                       "Gegenüber Ammoniak gibt es eines ab.",
                       "Also kommt es auf den Partner an."],
                solution="Gegenüber HCl nimmt Wasser ein Proton auf und wirkt als Base. Gegenüber Ammoniak gibt es eines ab und wirkt als Säure. Säure und Base sind Rollen in einer Reaktion, keine festen Eigenschaften.",
                tags=["laugen", "msa"], spiral=["K-REAK"]),
        aufgabe("SL04-C3-012", "C", 3, "multi",
                "56 g Calciumoxid CaO (M = 56 g/mol) reagieren vollständig mit Wasser zu Ca(OH)₂ (M = 74 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Calciumoxids", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse des entstehenden Calciumhydroxids", "answer": 74, "unit_label": "g", "tolerance": 1},
                    {"label": "Stoffmenge der Hydroxid-Ionen", "answer": 2, "unit_label": "mol", "tolerance": 0.05}
                ],
                hints=["n = 56 : 56 = 1 mol.",
                       "1 : 1 zu Ca(OH)₂.",
                       "Jedes Ca(OH)₂ liefert zwei OH⁻."],
                solution="n(CaO) = 1 mol → n(Ca(OH)₂) = 1 mol → m = 74 g\nJede Formeleinheit liefert 2 OH⁻ → n(OH⁻) = 2 mol",
                tags=["laugen", "rechnen", "msa"], spiral=["K-QUANT", "K-BIND"]),
        aufgabe("SL04-C3-013", "C", 3, "choice",
                "Warum ist gelöschter Kalk Ca(OH)₂ eine schwächere Lauge als Natronlauge gleicher Konzentration?",
                options=["Calciumhydroxid ist schwer löslich; es gelangen weniger OH⁻-Ionen in Lösung.",
                         "Es enthält weniger OH-Gruppen.",
                         "Calcium ist edler als Natrium."],
                answer=0,
                hints=["Ca(OH)₂ hat sogar zwei OH-Gruppen.",
                       "Aber wie viel davon löst sich?",
                       "Nur wenig."],
                solution="Calciumhydroxid enthält zwar zwei OH-Gruppen je Formeleinheit, ist aber schwer löslich. In Lösung gelangen deshalb weniger Hydroxid-Ionen als bei gut löslichem NaOH — Kalkwasser hat nur etwa pH 12.",
                tags=["laugen", "msa"], spiral=["K-SL"]),
        aufgabe("SL04-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Basen enthalten immer OH-Gruppen.“ Wie bewertest du das?",
                options=["Falsch — Ammoniak enthält keine OH-Gruppe und ist trotzdem eine Base, weil es Protonen aufnimmt.",
                         "Richtig — ohne OH keine Base.",
                         "Falsch — Basen enthalten nie OH-Gruppen."],
                answer=0,
                hints=["Kennst du ein Gegenbeispiel?",
                       "Ammoniak NH₃.",
                       "Es nimmt ein Proton auf."],
                solution="Der Basenbegriff ist über die Protonenaufnahme definiert, nicht über das Vorhandensein von OH. Ammoniak ist das Standardgegenbeispiel: NH₃ + H₂O ⇌ NH₄⁺ + OH⁻ — das OH stammt aus dem Wasser.",
                misconceptions=[fv("summenformel_falsch_gelesen", 1,
                                   "Ammoniak ist eine Base ohne OH-Gruppe. Entscheidend ist die Protonenaufnahme.",
                                   "summenformel_falsch_gelesen")],
                tags=["laugen", "bewerten", "msa"], spiral=["K-BIND"])
    ]
})

if __name__ == "__main__":
    schreiben("sl", E, "Bereich SL · Einheiten 3 und 4")
