# -*- coding: utf-8 -*-
"""Bereich SL · Säuren und Laugen (Klasse 9, Themenfeld 3.8) — SL-01 bis SL-03."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "SL-01",
    "title": "Säuren im Alltag — Eigenschaften und Sicherheit",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.2"],
    "klasse": 9,
    "sicherheit": [
        "Konzentrierte Säuren sind ätzend. Schutzbrille und Handschuhe sind Pflicht.",
        "Beim Verdünnen gilt: erst das Wasser, dann die Säure.",
        "Bei Hautkontakt mindestens 10 Minuten mit fließendem Wasser spülen."
    ],
    "wortspeicher": ["die Säure", "ätzend", "die Verdünnungsregel", "der Kalk",
                     "die Salzsäure", "die Schwefelsäure", "die Kohlensäure"],
    "worterklaerungen": {
        "Säure": "Ein Stoff, dessen wässrige Lösung sauer schmeckt und Indikatoren rot färbt.",
        "Verdünnungsregel": "Erst das Wasser, dann die Säure — sonst spritzt es."
    },
    "can_do": {
        "A": "Ich nenne Säuren aus dem Alltag und weiß, wie man sicher mit ihnen umgeht.",
        "B": "Ich beschreibe die Wirkung von Säuren auf unedle Metalle und Kalk.",
        "C": "Ich begründe Sicherheitsregeln im Umgang mit Säuren fachlich."
    },
    "lernkarten": {
        "A": karte("Säuren kennst du schon",
                   "Säuren gibt es in jedem Haushalt.",
                   ["Zitronensaft und Essig sind Säuren.", "Sie schmecken sauer."],
                   "Säuren im Labor werden nie geschmeckt.",
                   visual={"type": "phskala", "marken": [{"wert": 2, "stoff": "Zitronensaft"},
                                                         {"wert": 3, "stoff": "Essig"}],
                           "alt": "pH-Skala mit Zitronensaft bei pH 2 und Essig bei pH 3."},
                   beispiel={"titel": "Kalk und Essig", "aufgabe": "Essig auf einen Kalkfleck.",
                             "schritte": ["Es schäumt.", "Ein Gas entsteht.", "Der Kalk verschwindet."],
                             "ergebnis": "Säuren lösen Kalk."}),
        "B": karte("Woran man Säuren erkennt",
                   "Säuren haben mehrere gemeinsame Wirkungen. Zusammen ergeben sie ein verlässliches Bild.",
                   ["Sie färben Indikatoren: Lackmus und Universalindikator werden rot.",
                    "Sie reagieren mit unedlen Metallen unter Bildung von Wasserstoff. Edle Metalle greifen sie nicht an.",
                    "Sie lösen Kalk unter Bildung von Kohlenstoffdioxid — daher der Kalkentferner im Bad.",
                    "Wichtige Säuren: Salzsäure HCl, Schwefelsäure H₂SO₄, Salpetersäure HNO₃, Kohlensäure H₂CO₃, Essigsäure."],
                   "Indikator rot, Wasserstoff mit unedlen Metallen, Kohlenstoffdioxid mit Kalk.",
                   visual=anim("phwert", "B")),
        "C": karte("Warum die Regeln so lauten",
                   "Die Sicherheitsregeln im Umgang mit Säuren sind keine Willkür — jede hat eine chemische Begründung.",
                   ["„Erst das Wasser, dann die Säure“: Beim Verdünnen wird viel Wärme frei. Gibt man Wasser in konzentrierte Säure, erhitzt sich der kleine Tropfen schlagartig und spritzt Säure heraus.",
                    "Mindestens 10 Minuten spülen: Eine ätzende Wirkung hält an, solange Reste auf der Haut sind. Kurzes Abspülen verdünnt nur.",
                    "Nicht neutralisieren, sondern spülen: Eine Neutralisation auf der Haut setzt zusätzlich Wärme frei.",
                    "Konzentrierte Schwefelsäure entzieht organischem Material das Wasser — deshalb schwärzt sie Papier und Haut."],
                   "Jede Regel hat einen Grund. Wer ihn kennt, wendet sie richtig an.",
                   visual={"type": "energie", "verlauf": "exotherm",
                           "alt": "Energiediagramm des exothermen Verdünnungsvorgangs."})
    },
    "formelkarte": {"formeln": ["Säure + unedles Metall → Salz + Wasserstoff",
                               "Säure + Kalk → Salz + Wasser + Kohlenstoffdioxid"],
                    "saetze": ["Erst das Wasser, dann die Säure.",
                               "Indikator wird rot: die Lösung ist sauer.",
                               "Salzsäure HCl · Schwefelsäure H₂SO₄ · Salpetersäure HNO₃ · Kohlensäure H₂CO₃",
                               "Bei Hautkontakt mindestens 10 Minuten spülen."]},
    "tasks": [
        aufgabe("SL01-A1-001", "A", 1, "choice",
                "Welcher Stoff aus dem Haushalt ist eine Säure?",
                options=["Essig", "Speisesalz", "Zucker"], answer=0,
                hints=["Er schmeckt sauer.", "Man nimmt ihn für Salat.", "Essig."],
                solution="Essig ist eine Säure. Salz und Zucker sind es nicht.",
                tags=["saeuren"], spiral=["W-LOES"]),
        aufgabe("SL01-A2-002", "A", 2, "choice",
                "Wie färbt sich Universalindikator in einer Säure?",
                options=["rot", "blau", "grün"], answer=0,
                visual=anim("phwert", "A"),
                hints=["Sauer ist links auf der Skala.", "Dort ist die Farbe rot.", "Rot."],
                solution="In sauren Lösungen färbt sich der Universalindikator rot.",
                misconceptions=[fv("indikator_vertauscht", 1,
                                   "Blau zeigt eine alkalische Lösung an. Sauer ist rot.",
                                   "saeure_lauge_vertauscht")],
                tags=["saeuren"], spiral=["W-LOES"]),
        aufgabe("SL01-A3-003", "A", 3, "choice",
                "Was gilt beim Verdünnen von Säure?",
                options=["Erst das Wasser, dann die Säure.", "Erst die Säure, dann das Wasser.", "Die Reihenfolge ist egal."],
                answer=0,
                hints=["Es gibt einen Merkspruch dazu.", "„… sonst geschieht das Ungeheure.“", "Erst das Wasser."],
                solution="Erst das Wasser, dann die Säure — sonst geschieht das Ungeheure. Beim Verdünnen wird viel Wärme frei.",
                misconceptions=[fv("reihenfolge_vertauscht", 1,
                                   "Umgekehrt spritzt die Säure. Erst das Wasser vorlegen.",
                                   "sicherheitsregel_missachtet")],
                tags=["saeuren", "sicherheit"]),
        aufgabe("SL01-A4-004", "A", 4, "choice",
                "Was passiert, wenn Essig auf Kalk trifft?",
                options=["Es schäumt, ein Gas entsteht.", "Nichts.", "Der Kalk wird härter."],
                answer=0,
                hints=["Beobachte einen Kalkentferner.", "Es sprudelt.", "Ein Gas entweicht."],
                solution="Säuren lösen Kalk. Dabei entsteht Kohlenstoffdioxid — das Schäumen. Genau darauf beruhen Kalkentferner.",
                tags=["saeuren"], spiral=["W-GLEI"]),
        aufgabe("SL01-B1-005", "B", 1, "choice",
                "Was entsteht, wenn eine Säure auf ein unedles Metall trifft?",
                options=["ein Salz und Wasserstoff", "ein Salz und Sauerstoff", "nur Wärme"],
                answer=0,
                hints=["Ein Gas entsteht.", "Es lässt sich mit der Knallgasprobe nachweisen.", "Wasserstoff."],
                solution="Säure + unedles Metall → Salz + Wasserstoff. Der Wasserstoff lässt sich mit der Knallgasprobe nachweisen.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Sauerstoff entsteht dabei nicht. Es ist Wasserstoff.",
                                   "nachweis_verwechselt")],
                tags=["saeuren", "bbr"], spiral=["W-GLEI"]),
        aufgabe("SL01-B2-006", "B", 2, "choice",
                "Warum greift Salzsäure Kupfer nicht an, Zink aber schon?",
                options=["Kupfer ist edler als Wasserstoff, Zink unedler.",
                         "Kupfer ist härter.", "Zink löst sich in jedem Wasser."],
                answer=0,
                hints=["Denk an die Redoxreihe.",
                       "Nur unedle Metalle reagieren mit Säuren.",
                       "Kupfer steht rechts vom Wasserstoff."],
                solution="Nur Metalle, die unedler sind als Wasserstoff, verdrängen ihn aus der Säure. Zink ist unedler, Kupfer edler — deshalb reagiert nur das Zink.",
                tags=["saeuren", "bbr"], spiral=["W-GLEI"]),
        aufgabe("SL01-B2-007", "B", 2, "choice",
                "Warum wird beim Verdünnen die Säure ins Wasser gegeben und nicht umgekehrt?",
                options=["Die frei werdende Wärme verteilt sich in der großen Wassermenge.",
                         "Die Säure ist schwerer.", "Damit man besser rühren kann."],
                answer=0,
                hints=["Was wird beim Verdünnen frei?",
                       "Wärme, und zwar viel.",
                       "Wenig Wasser kann sie nicht aufnehmen."],
                solution="Beim Verdünnen wird viel Wärme frei. In einer großen Wassermenge verteilt sie sich. Gibt man dagegen Wasser in konzentrierte Säure, erhitzt sich der Tropfen schlagartig und spritzt Säure heraus.",
                misconceptions=[fv("dichte_als_grund", 1,
                                   "Mit der Dichte hat die Regel nichts zu tun. Entscheidend ist die Wärme.",
                                   "sicherheitsregel_missachtet")],
                tags=["saeuren", "sicherheit", "bbr"]),
        aufgabe("SL01-B3-008", "B", 3, "assign",
                "Ordne jeder Säure ihre Formel zu.",
                slots=["Salzsäure", "Schwefelsäure", "Salpetersäure"],
                values=["HCl", "H₂SO₄", "HNO₃"], answer=[0, 1, 2],
                hints=["Salzsäure ist die einfachste.",
                       "Schwefelsäure enthält Schwefel.",
                       "Salpetersäure enthält Stickstoff."],
                solution="Salzsäure HCl, Schwefelsäure H₂SO₄, Salpetersäure HNO₃.",
                tags=["saeuren", "formeln", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SL01-B3-009", "B", 3, "choice",
                "Warum schwärzt konzentrierte Schwefelsäure Papier?",
                options=["Sie entzieht dem Papier das Wasser; zurück bleibt Kohlenstoff.",
                         "Sie verbrennt das Papier.",
                         "Sie färbt das Papier ein."],
                answer=0,
                hints=["Papier besteht aus Kohlenstoff, Wasserstoff und Sauerstoff.",
                       "Was passiert, wenn H und O als Wasser entfernt werden?",
                       "Kohlenstoff bleibt übrig."],
                solution="Konzentrierte Schwefelsäure wirkt stark wasserentziehend. Aus dem Papier wird Wasser herausgezogen, zurück bleibt schwarzer Kohlenstoff. Auf der Haut wirkt sie ebenso — daher die Gefährlichkeit.",
                tags=["saeuren", "sicherheit", "msa"]),
        aufgabe("SL01-B4-010", "B", 4, "numeric",
                "Ein Entkalker enthält 8 % Zitronensäure. Wie viel Säure stecken in 250 g?",
                answer=20, unit_label="g", tolerance=0.5,
                hints=["8 % von 250 g.", "1 % sind 2,5 g.", "8 · 2,5 g."],
                solution="250 g · 0,08 = 20 g Zitronensäure",
                tags=["saeuren", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL01-C2-011", "C", 2, "choice",
                "Warum soll man Säure auf der Haut spülen und nicht mit Lauge neutralisieren?",
                options=["Die Neutralisation setzt zusätzlich Wärme frei und kann die Haut weiter schädigen.",
                         "Lauge ist nicht verfügbar.",
                         "Die Neutralisation dauert zu lange."],
                answer=0,
                hints=["Ist die Neutralisation exotherm oder endotherm?",
                       "Exotherm.",
                       "Wärme auf verletzter Haut ist keine gute Idee."],
                solution="Die Neutralisation ist stark exotherm. Auf der Haut käme zur Verätzung eine Verbrennung hinzu. Reichlich Wasser verdünnt und kühlt zugleich — das ist die sichere Maßnahme.",
                tags=["saeuren", "sicherheit", "msa"]),
        aufgabe("SL01-C3-012", "C", 3, "choice",
                "Warum reagiert Kalk mit Säure unter Gasentwicklung?",
                options=["Es entsteht Kohlensäure, die sofort in Wasser und Kohlenstoffdioxid zerfällt.",
                         "Der Kalk verbrennt.",
                         "Die Säure verdampft."],
                answer=0,
                hints=["Kalk ist Calciumcarbonat.",
                       "Aus dem Carbonat wird zunächst Kohlensäure.",
                       "Die ist nicht stabil."],
                solution="Die Säure setzt aus dem Carbonat Kohlensäure frei. Diese ist instabil und zerfällt sofort in Wasser und Kohlenstoffdioxid — das aufsteigende Gas.",
                tags=["saeuren", "erklaeren", "msa"], spiral=["W-GLEI"]),
        aufgabe("SL01-C3-013", "C", 3, "multi",
                "Ein Kalkentferner enthält 10 % Essigsäure. Für eine Anwendung werden 400 g der Lösung gebraucht.",
                fields=[
                    {"label": "Masse der Essigsäure", "answer": 40, "unit_label": "g", "tolerance": 1},
                    {"label": "Masse des Wassers", "answer": 360, "unit_label": "g", "tolerance": 2},
                    {"label": "Säuremasse bei Verdünnung auf 4 %", "answer": 40, "unit_label": "g", "tolerance": 1}
                ],
                hints=["10 % von 400 g.",
                       "Der Rest ist Wasser.",
                       "Beim Verdünnen ändert sich die Säuremasse nicht."],
                solution="Säure: 400 · 0,10 = 40 g\nWasser: 360 g\nBeim Verdünnen bleibt die Säuremasse gleich — nur die Gesamtmasse wächst.",
                tags=["saeuren", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("SL01-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Verdünnte Säure ist harmlos.“ Wie bewertest du das?",
                options=["Zu pauschal — die Wirkung hängt von Konzentration, Säurestärke und Einwirkzeit ab.",
                         "Richtig — verdünnt ist immer harmlos.",
                         "Falsch — verdünnte Säure ist genauso gefährlich."],
                answer=0,
                hints=["Ist jede verdünnte Säure gleich schwach?",
                       "Nein — Konzentration und Stärke unterscheiden sich.",
                       "Und die Einwirkzeit zählt auch."],
                solution="Verdünnen senkt die Gefährdung, hebt sie aber nicht auf. Entscheidend sind Konzentration, Säurestärke und wie lange die Säure einwirkt. Eine pauschale Entwarnung ist im Labor nie angebracht.",
                tags=["saeuren", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "SL-02",
    "title": "Indikatoren und die pH-Skala",
    "leitidee": "B2",
    "standards": ["K1", "K2.2", "K2.4"],
    "klasse": 9,
    "wortspeicher": ["der Indikator", "die pH-Skala", "sauer", "neutral", "alkalisch",
                     "das Universalindikatorpapier", "der Rotkohlsaft"],
    "worterklaerungen": {
        "Indikator": "Ein Stoff, der je nach pH-Wert die Farbe wechselt.",
        "pH-Skala": "Eine Skala von 0 bis 14. Sie gibt an, wie sauer oder alkalisch eine Lösung ist."
    },
    "can_do": {
        "A": "Ich ordne pH-Werte den Bereichen sauer, neutral und alkalisch zu.",
        "B": "Ich lese pH-Werte ab und ordne Alltagsstoffe ein.",
        "C": "Ich erkläre, dass eine pH-Stufe dem Faktor 10 entspricht, und wende das auf Verdünnungen an."
    },
    "lernkarten": {
        "A": karte("Die Farbskala",
                   "Ein Indikator zeigt mit seiner Farbe an, wie sauer eine Lösung ist.",
                   ["Rot heißt sauer.", "Grün heißt neutral.", "Blau heißt alkalisch."],
                   "Unter 7 sauer, genau 7 neutral, über 7 alkalisch.",
                   visual=anim("phwert", "A"),
                   beispiel={"titel": "Zitronensaft", "aufgabe": "Der Indikator wird rot.",
                             "schritte": ["Rot heißt sauer.", "Der pH-Wert liegt unter 7."],
                             "ergebnis": "Zitronensaft ist sauer, pH etwa 2."}),
        "B": karte("Werte einordnen",
                   "Die pH-Skala macht aus einem Eindruck eine Zahl. Damit lassen sich Lösungen vergleichen, die beide „sauer“ schmecken.",
                   ["Magensäure liegt bei pH 1, Zitronensaft bei 2, Regenwasser bei 5,6, reines Wasser bei 7.",
                    "Seifenlauge liegt bei etwa 10, Rohrreiniger bei 13.",
                    "Universalindikatorpapier gibt einen groben Wert, ein pH-Meter einen genauen.",
                    "Rotkohlsaft ist ein natürlicher Indikator und durchläuft die ganze Farbskala von rot über violett bis grün."],
                   "Der pH-Wert macht „sauer“ vergleichbar.",
                   visual=anim("phwert", "B")),
        "C": karte("Eine Stufe ist der Faktor 10",
                   "Die pH-Skala ist keine gewöhnliche Skala: Zwischen zwei benachbarten Werten liegt nicht ein Schritt, sondern ein Faktor.",
                   ["Eine Lösung mit pH 3 enthält zehnmal mehr Oxonium-Ionen als eine mit pH 4 — und hundertmal mehr als eine mit pH 5.",
                    "Zehnfaches Verdünnen erhöht den pH-Wert um genau eine Stufe.",
                    "Über pH 7 hinaus geht das Verdünnen nicht: Aus einer Säure wird durch Wasserzugabe nie eine Lauge.",
                    "Deshalb ist der Unterschied zwischen pH 1 und pH 3 nicht „zwei Stufen“, sondern der Faktor 100 — das erklärt, warum Magensäure so viel aggressiver ist als Essig."],
                   "Eine Stufe = Faktor 10. Zwei Stufen = Faktor 100.",
                   visual=anim("phwert", "C"))
    },
    "formelkarte": {"formeln": ["pH < 7 sauer · pH = 7 neutral · pH > 7 alkalisch"],
                    "saetze": ["Eine pH-Stufe entspricht dem Faktor 10 bei der Konzentration.",
                               "Zehnfaches Verdünnen verschiebt den pH um 1 Richtung 7 — nie darüber hinaus.",
                               "Magensäure pH 1 · Zitrone 2 · Regen 5,6 · Wasser 7 · Seifenlauge 10.",
                               "Indikator: rot sauer, grün neutral, blau alkalisch."]},
    "tasks": [
        aufgabe("SL02-A1-001", "A", 1, "choice",
                "Eine Lösung hat pH 3. Ist sie sauer, neutral oder alkalisch?",
                options=["sauer", "neutral", "alkalisch"], answer=0,
                visual=anim("phwert", "A"),
                hints=["Neutral ist 7.", "3 liegt darunter.", "Also sauer."],
                solution="pH 3 liegt unter 7 — die Lösung ist sauer.",
                misconceptions=[fv("ph_skala_falschrum", 2,
                                   "Über 7 wäre alkalisch. pH 3 liegt darunter.",
                                   "ph_skala_falschrum")],
                tags=["ph"], spiral=["W-LOES"]),
        aufgabe("SL02-A2-002", "A", 2, "numeric",
                "Welchen pH-Wert hat eine neutrale Lösung?",
                answer=7, tolerance=0,
                hints=["Genau in der Mitte der Skala.", "Die Skala geht von 0 bis 14.", "7."],
                solution="Eine neutrale Lösung hat pH 7 — genau in der Mitte der Skala.",
                tags=["ph"], spiral=["W-LOES"]),
        aufgabe("SL02-A3-003", "A", 3, "assign",
                "Ordne jedem Stoff seinen Bereich zu.",
                slots=["Zitronensaft (pH 2)", "reines Wasser (pH 7)", "Seifenlauge (pH 10)"],
                values=["sauer", "neutral", "alkalisch"], answer=[0, 1, 2],
                hints=["Unter 7 sauer.", "Genau 7 neutral.", "Über 7 alkalisch."],
                solution="Zitronensaft sauer, Wasser neutral, Seifenlauge alkalisch.",
                tags=["ph"], spiral=["W-LOES"]),
        aufgabe("SL02-A4-004", "A", 4, "choice",
                "Welche Farbe zeigt Universalindikator bei pH 10?",
                options=["blau", "rot", "grün"], answer=0,
                visual=anim("phwert", "A"),
                hints=["pH 10 ist alkalisch.", "Alkalisch ist rechts auf der Skala.", "Dort ist es blau."],
                solution="pH 10 ist alkalisch — der Indikator färbt sich blau.",
                misconceptions=[fv("indikator_vertauscht", 1,
                                   "Rot zeigt eine saure Lösung an.",
                                   "saeure_lauge_vertauscht")],
                tags=["ph"], spiral=["W-LOES"]),
        aufgabe("SL02-B1-005", "B", 1, "choice",
                "Welche Lösung ist stärker sauer: pH 2 oder pH 5?",
                options=["pH 2", "pH 5", "beide gleich"], answer=0,
                hints=["Je kleiner der Wert, desto saurer.",
                       "2 ist kleiner als 5.",
                       "pH 2."],
                solution="Je kleiner der pH-Wert, desto saurer die Lösung. pH 2 ist deutlich saurer als pH 5 — genau um den Faktor 1000.",
                misconceptions=[fv("ph_skala_falschrum", 1,
                                   "Kleinere Werte bedeuten stärker sauer, nicht schwächer.",
                                   "ph_skala_falschrum")],
                tags=["ph", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL02-B2-006", "B", 2, "numeric",
                "Eine Säure mit pH 2 wird zehnfach verdünnt. Welchen pH-Wert hat sie danach?",
                answer=3, tolerance=0,
                visual=anim("phwert", "C"),
                hints=["Zehnfaches Verdünnen verschiebt um eine Stufe.",
                       "Richtung 7.",
                       "2 + 1 = 3."],
                solution="Zehnfaches Verdünnen verschiebt den pH-Wert um eine Stufe Richtung 7: von 2 auf 3.",
                misconceptions=[fv("ph_skala_falschrum", 1,
                                   "Verdünnen macht die Lösung <b>weniger</b> sauer — der pH-Wert steigt.",
                                   "ph_skala_falschrum")],
                tags=["ph", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL02-B2-007", "B", 2, "numeric",
                "Um welchen Faktor unterscheidet sich die Konzentration der Oxonium-Ionen bei pH 3 und pH 5?",
                answer=100, tolerance=0,
                hints=["Eine Stufe ist der Faktor 10.",
                       "Von 3 auf 5 sind es zwei Stufen.",
                       "10 · 10 = 100."],
                solution="Zwei Stufen bedeuten den Faktor 10 · 10 = 100. Eine Lösung mit pH 3 enthält hundertmal mehr Oxonium-Ionen.",
                misconceptions=[fv("ph_skala_falschrum", 2,
                                   "Die pH-Skala ist keine gewöhnliche Zahlenskala. Jede Stufe ist ein Faktor 10.",
                                   "ph_skala_falschrum")],
                tags=["ph", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL02-B3-008", "B", 3, "numeric",
                "Eine Säure mit pH 1 wird dreimal hintereinander zehnfach verdünnt. Welchen pH-Wert hat sie?",
                answer=4, tolerance=0,
                hints=["Jede Verdünnung eine Stufe.", "1 + 3.", "4."],
                solution="1 + 3 = 4. Drei zehnfache Verdünnungen entsprechen dem Faktor 1000.",
                tags=["ph", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL02-B3-009", "B", 3, "choice",
                "Warum wird eine Säure durch Verdünnen nie alkalisch?",
                options=["Verdünnen nähert den pH-Wert nur dem Wert von Wasser an — pH 7 wird nicht überschritten.",
                         "Weil Wasser selbst leicht sauer ist.",
                         "Weil Säure sich nicht verdünnen lässt."],
                answer=0,
                hints=["Was ist der Grenzwert beim Verdünnen?",
                       "Der pH-Wert von reinem Wasser.",
                       "Also 7."],
                solution="Beim Verdünnen nähert sich der pH-Wert dem von reinem Wasser an, also 7. Er überschreitet diesen Wert nicht — dafür bräuchte es eine Lauge.",
                tags=["ph", "msa"], spiral=["W-LOES"]),
        aufgabe("SL02-B4-010", "B", 4, "choice",
                "Warum eignet sich Rotkohlsaft als Indikator?",
                options=["Sein Farbstoff wechselt über den ganzen pH-Bereich mehrfach die Farbe.",
                         "Er ist besonders sauer.",
                         "Er ist billig."],
                answer=0,
                hints=["Was macht einen guten Indikator aus?",
                       "Er muss die Farbe wechseln.",
                       "Rotkohl tut das mehrfach."],
                solution="Der Farbstoff im Rotkohl durchläuft von sauer bis alkalisch mehrere Farben — von rot über violett und blau bis grün. Damit lässt sich der pH-Bereich grob ablesen.",
                tags=["ph", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL02-C2-011", "C", 2, "choice",
                "Magensäure hat pH 1, Essig pH 3. Wie viel saurer ist die Magensäure?",
                options=["hundertmal", "zweimal", "dreimal"], answer=0,
                hints=["Zwei Stufen Unterschied.",
                       "Jede Stufe ist der Faktor 10.",
                       "10 · 10."],
                solution="Zwei Stufen bedeuten den Faktor 100. Die Magensäure enthält hundertmal mehr Oxonium-Ionen — deshalb wirkt sie so viel aggressiver.",
                misconceptions=[fv("ph_skala_falschrum", 1,
                                   "Der Unterschied ist kein Faktor 2. Jede pH-Stufe entspricht dem Faktor 10.",
                                   "ph_skala_falschrum")],
                tags=["ph", "msa"], spiral=["W-LOES"]),
        aufgabe("SL02-C3-012", "C", 3, "multi",
                "Eine Salzsäure hat pH 1. Sie wird schrittweise zehnfach verdünnt.",
                fields=[
                    {"label": "pH nach der ersten Verdünnung", "answer": 2, "tolerance": 0},
                    {"label": "pH nach der vierten Verdünnung", "answer": 5, "tolerance": 0},
                    {"label": "pH nach der zehnten Verdünnung", "answer": 7, "tolerance": 0}
                ],
                hints=["Jede Verdünnung eine Stufe.",
                       "1 + 4 = 5.",
                       "Ab pH 7 geht es nicht weiter."],
                solution="1 → 2 → 3 → 4 → 5 …\nAb pH 7 hört die Verschiebung auf: Weiter als bis zum Wert von reinem Wasser kommt man durch Verdünnen nicht.",
                tags=["ph", "msa"], spiral=["W-LOES"]),
        aufgabe("SL02-C3-013", "C", 3, "choice",
                "Warum reicht Universalindikatorpapier für eine genaue Messung nicht aus?",
                options=["Es liefert nur einen groben Farbvergleich; für genaue Werte braucht es ein pH-Meter.",
                         "Es funktioniert nur bei Säuren.",
                         "Es ist zu teuer."],
                answer=0,
                hints=["Wie genau lässt sich eine Farbe ablesen?",
                       "Auf etwa eine halbe Stufe.",
                       "Das reicht für viele Fragen nicht."],
                solution="Der Farbvergleich erlaubt eine Genauigkeit von etwa einer halben pH-Stufe. Weil eine Stufe dem Faktor 10 entspricht, ist das für genaue Aussagen zu ungenau — dafür braucht es ein pH-Meter.",
                tags=["ph", "bewerten", "msa"]),
        aufgabe("SL02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „pH 6 und pH 8 sind fast gleich, beide liegen nahe bei 7.“ Wie bewertest du das?",
                options=["Die Werte liegen zahlenmäßig nahe, unterscheiden sich in der Konzentration aber um den Faktor 100.",
                         "Richtig, beide sind praktisch neutral.",
                         "Falsch, pH 6 ist alkalisch."],
                answer=0,
                hints=["Wie viele Stufen liegen zwischen 6 und 8?",
                       "Zwei.",
                       "Also der Faktor 100."],
                solution="Zwei Stufen bedeuten den Faktor 100. Die eine Lösung ist sauer, die andere alkalisch. Die scheinbare Nähe auf der Skala täuscht — genau das ist die Eigenart einer logarithmischen Skala.",
                tags=["ph", "bewerten", "msa"], spiral=["W-LOES"])
    ]
})

if __name__ == "__main__":
    schreiben("sl", E, "Bereich SL · Einheiten 1 und 2")
