# -*- coding: utf-8 -*-
"""Bereich ES · Ester und Makromoleküle — ES-02 bis ES-04."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "ES-02",
    "title": "Ester im Alltag: Aromen und Lösungsmittel",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["der Aromastoff", "das Lösungsmittel", "das Fruchtaroma",
                     "die Acetylsalicylsäure", "der Nagellackentferner"],
    "worterklaerungen": {
        "Aromastoff": "Ein Stoff, der Geruch und Geschmack erzeugt.",
        "Acetylsalicylsäure": "Der Wirkstoff in Aspirin. Chemisch ein Ester."
    },
    "can_do": {
        "A": "Ich nenne Verwendungen von Estern aus dem Alltag.",
        "B": "Ich erkläre, warum Ester als Aromen und Lösungsmittel geeignet sind.",
        "C": "Ich bewerte den Einsatz natürlicher und naturidentischer Aromastoffe."
    },
    "lernkarten": {
        "A": karte("Ester riechen gut",
                   "Viele Ester riechen nach Früchten.",
                   ["Sie werden als Aromastoffe verwendet.",
                    "Andere sind gute Lösungsmittel."],
                   "Ester: Aromastoffe und Lösungsmittel.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "ester", "name": "ein Ester",
                           "alt": "Strukturformel eines Esters."},
                   beispiel={"titel": "Fruchtaromen", "aufgabe": "Wonach riechen Ester?",
                             "schritte": ["Einer nach Birne.", "Einer nach Banane.",
                                          "Einer nach Rum."],
                             "ergebnis": "Verschiedene Ester, verschiedene Gerüche."}),
        "B": karte("Warum Ester so vielseitig sind",
                   "Ester haben keine freie OH-Gruppe mehr — und genau das erklärt ihre beiden wichtigsten Verwendungen.",
                   ["Ohne freie OH-Gruppe bilden Ester untereinander keine Wasserstoffbrücken. Sie sind deshalb flüchtiger als die Säuren, aus denen sie stammen.",
                    "Flüchtig bedeutet: Die Moleküle gelangen leicht in die Luft und an die Riechzellen. Deshalb sind viele Ester Aromastoffe.",
                    "Zugleich lösen sie sowohl unpolare als auch mäßig polare Stoffe — deshalb Ethylacetat in Nagellackentferner und Klebstoffen.",
                    "Fruchtaromen sind fast immer Ester: Pentylacetat riecht nach Banane, Ethylbutanoat nach Ananas.",
                    "Auch Acetylsalicylsäure, der Wirkstoff in Aspirin, ist ein Ester."],
                   "Keine freie OH-Gruppe heißt: flüchtig, riechend, gut lösend.",
                   visual=anim("veresterung", "B")),
        "C": karte("Natürlich, naturidentisch, künstlich",
                   "Aromastoffe werden auf Zutatenlisten unterschiedlich bezeichnet. Der Unterschied ist rechtlich geregelt und chemisch oft bedeutungslos.",
                   ["Natürliches Aroma: aus pflanzlichem oder tierischem Material gewonnen — nicht notwendigerweise aus der genannten Frucht.",
                    "Naturidentisch: im Labor hergestellt, aber molekular identisch mit dem natürlichen Stoff. Chemisch ist kein Unterschied feststellbar.",
                    "Künstliches Aroma: ein Stoff, der in der Natur nicht vorkommt.",
                    "Zu bedenken: Ein natürliches Aroma kann aufwendiger, teurer und mit größerem Flächenverbrauch verbunden sein als ein naturidentisches.",
                    "Fachlich gilt: Sind die Moleküle identisch, ist auch die Wirkung identisch. Die Herkunft ist ein wirtschaftliches und rechtliches, kein chemisches Kriterium."],
                   "Identische Moleküle wirken identisch — die Herkunft ändert daran nichts.",
                   visual={"type": "struktur", "kette": 4, "gruppe": "ester",
                           "alt": "Strukturformel eines Fruchtesters."})
    },
    "formelkarte": {"formeln": ["R–COO–R'"],
                    "saetze": ["Ester haben keine freie OH-Gruppe und sind deshalb flüchtig.",
                               "Viele Fruchtaromen sind Ester.",
                               "Ethylacetat ist ein verbreitetes Lösungsmittel.",
                               "Naturidentisch heißt: molekular identisch mit dem natürlichen Stoff."]},
    "tasks": [
        aufgabe("ES02-A1-001", "A", 1, "choice",
                "Wofür werden viele Ester verwendet?",
                options=["als Aromastoffe", "als Metalle", "als Säuren"], answer=0,
                hints=["Sie riechen nach Früchten.", "Deshalb kommen sie in Lebensmittel.", "Als Aromastoffe."],
                solution="Viele Ester riechen fruchtig und werden als Aromastoffe eingesetzt.",
                tags=["ester"], spiral=["W-ORG"]),
        aufgabe("ES02-A2-002", "A", 2, "choice",
                "Welcher Ester steckt im Nagellackentferner?",
                options=["Ethylacetat", "Essigsäure", "Ethanol"], answer=0,
                hints=["Es ist ein Ester.", "Aus Essigsäure und Ethanol.", "Ethylacetat."],
                solution="Ethylacetat — der Essigsäureethylester — ist ein verbreitetes Lösungsmittel in Nagellackentfernern.",
                tags=["ester"], spiral=["W-ORG"]),
        aufgabe("ES02-A3-003", "A", 3, "choice",
                "Warum riechen Ester so gut wahrnehmbar?",
                options=["Sie sind flüchtig und gelangen leicht in die Luft.",
                         "Sie sind sehr schwer.", "Sie sind fest."],
                answer=0,
                hints=["Was muss ein Stoff können, damit man ihn riecht?",
                       "Er muss in die Luft gelangen.",
                       "Also flüchtig sein."],
                solution="Nur flüchtige Stoffe erreichen die Riechzellen. Ester bilden keine Wasserstoffbrücken untereinander und verdunsten deshalb leicht.",
                tags=["ester"], spiral=["W-STOF"]),
        aufgabe("ES02-A4-004", "A", 4, "choice",
                "Ist der Wirkstoff in Aspirin ein Ester?",
                options=["Ja — Acetylsalicylsäure ist ein Ester.", "Nein, es ist ein Alkohol.", "Nein, es ist ein Salz."],
                answer=0,
                hints=["Der Name enthält „Acetyl“.", "Das deutet auf Essigsäure hin.", "Ja, ein Ester."],
                solution="Acetylsalicylsäure entsteht aus Salicylsäure und Essigsäure — sie ist ein Ester.",
                tags=["ester"], spiral=["W-ORG"]),
        aufgabe("ES02-B1-005", "B", 1, "choice",
                "Warum sind Ester flüchtiger als die Säuren, aus denen sie entstehen?",
                options=["Ihnen fehlt die freie OH-Gruppe für Wasserstoffbrücken.",
                         "Sie sind leichter.",
                         "Sie sind unpolar."],
                answer=0,
                hints=["Was macht die Carboxygruppe der Säure?",
                       "Sie bildet Wasserstoffbrücken.",
                       "Im Ester ist sie verändert."],
                solution="Bei der Veresterung wird die OH-Gruppe der Säure verbraucht. Ohne sie können die Estermoleküle untereinander keine Wasserstoffbrücken bilden — sie verdunsten leichter.",
                tags=["ester", "bbr"], spiral=["W-ORG"]),
        aufgabe("ES02-B2-006", "B", 2, "choice",
                "Warum ist Ethylacetat ein gutes Lösungsmittel für Lacke?",
                options=["Es löst unpolare und mäßig polare Stoffe und verdunstet rückstandsfrei.",
                         "Es ist besonders billig.",
                         "Es reagiert mit dem Lack."],
                answer=0,
                hints=["Ein Lösungsmittel darf nicht reagieren.",
                       "Es muss lösen und wieder verschwinden.",
                       "Ethylacetat tut beides."],
                solution="Ethylacetat löst ein breites Spektrum an Stoffen und verdunstet bei 77 °C rückstandsfrei. Es reagiert dabei nicht mit dem Gelösten — genau das macht ein gutes Lösungsmittel aus.",
                tags=["ester", "bbr"], spiral=["W-LOES"]),
        aufgabe("ES02-B2-007", "B", 2, "assign",
                "Ordne jedem Ester seinen Geruch zu.",
                slots=["Pentylacetat", "Ethylbutanoat", "Ethylmethanoat"],
                values=["Banane", "Ananas", "Rum"], answer=[0, 1, 2],
                hints=["Alle drei sind Fruchtester.",
                       "Pentylacetat riecht nach Banane.",
                       "Ethylbutanoat nach Ananas."],
                solution="Pentylacetat → Banane, Ethylbutanoat → Ananas, Ethylmethanoat → Rum.",
                tags=["ester", "bbr"], spiral=["W-ORG"]),
        aufgabe("ES02-B3-008", "B", 3, "choice",
                "Was bedeutet „naturidentisches Aroma“?",
                options=["Der Stoff ist im Labor hergestellt, aber molekular identisch mit dem natürlichen.",
                         "Der Stoff kommt in der Natur nicht vor.",
                         "Der Stoff wurde aus der genannten Frucht gewonnen."],
                answer=0,
                hints=["Identisch heißt: gleich aufgebaut.",
                       "Nur die Herkunft unterscheidet sich.",
                       "Im Labor hergestellt."],
                solution="Naturidentische Aromastoffe sind molekular identisch mit den natürlich vorkommenden — nur die Herstellung erfolgt synthetisch. Chemisch lassen sie sich nicht unterscheiden.",
                tags=["ester", "bewerten", "bbr"]),
        aufgabe("ES02-B3-009", "B", 3, "numeric",
                "Wie groß ist die molare Masse von Methylmethanoat HCOOCH₃? (C = 12, H = 1, O = 16 g/mol)",
                answer=60, unit_label="g/mol", tolerance=1,
                hints=["2 C, 4 H, 2 O.",
                       "24 + 4 + 32.",
                       "60 g/mol."],
                solution="M = 2 · 12 + 4 · 1 + 2 · 16 = 60 g/mol",
                tags=["ester", "rechnen", "bbr"], spiral=["W-RECH"]),
        aufgabe("ES02-B4-010", "B", 4, "choice",
                "Warum riecht Essigsäure stechend, ihr Ethylester aber fruchtig?",
                options=["Der Ester hat keine freie Carboxygruppe mehr — es ist ein anderer Stoff.",
                         "Der Ester ist verdünnt.",
                         "Der Ester ist wärmer."],
                answer=0,
                hints=["Was ist bei der Veresterung passiert?",
                       "Die Carboxygruppe wurde verändert.",
                       "Es ist ein anderer Stoff entstanden."],
                solution="Bei der Veresterung entsteht ein neuer Stoff mit anderer funktioneller Gruppe. Geruch und Eigenschaften folgen der Struktur — nicht der Herkunft.",
                tags=["ester", "msa"], spiral=["W-ORG"]),
        aufgabe("ES02-C2-011", "C", 2, "choice",
                "Warum sind Ester nur mäßig wasserlöslich, obwohl sie Sauerstoffatome enthalten?",
                options=["Ihnen fehlt die freie OH-Gruppe; sie können keine Wasserstoffbrücken als Donator bilden.",
                         "Sie sind vollständig unpolar.",
                         "Sie reagieren mit Wasser."],
                answer=0,
                hints=["Wozu braucht es eine OH-Gruppe?",
                       "Um selbst eine Brücke anzubieten.",
                       "Der Ester kann nur aufnehmen, nicht anbieten."],
                solution="Die Sauerstoffatome können Wasserstoffbrücken vom Wasser aufnehmen, aber der Ester besitzt selbst kein Wasserstoffatom an einem Sauerstoff. Die Wechselwirkung ist deshalb schwächer als bei Alkoholen oder Säuren.",
                tags=["ester", "msa"], spiral=["W-LOES"]),
        aufgabe("ES02-C3-012", "C", 3, "choice",
                "Wie bewertest du die Aussage „Natürliches Aroma ist immer besser als naturidentisches“?",
                options=["Chemisch ist bei identischen Molekülen kein Unterschied feststellbar; „besser“ braucht ein Kriterium.",
                         "Richtig, natürlich ist immer besser.",
                         "Falsch, naturidentisch ist immer besser."],
                answer=0,
                hints=["Sind die Moleküle unterscheidbar?",
                       "Bei naturidentischen nicht.",
                       "Also muss das Kriterium ein anderes sein."],
                solution="Sind die Moleküle identisch, sind Wirkung und Geruch identisch. Unterschiede liegen in Kosten, Flächenverbrauch und Verfügbarkeit — das sind wirtschaftliche und ökologische Kriterien, keine chemischen.",
                tags=["ester", "bewerten", "msa"]),
        aufgabe("ES02-C3-013", "C", 3, "choice",
                "Warum wird ein Fruchtaroma oft synthetisch hergestellt statt aus der Frucht gewonnen?",
                options=["Der Gehalt in der Frucht ist winzig; die Gewinnung wäre aufwendig und flächenintensiv.",
                         "Der natürliche Stoff wirkt schlechter.",
                         "Der natürliche Stoff ist giftig."],
                answer=0,
                hints=["Wie viel Aromastoff steckt in einer Erdbeere?",
                       "Sehr wenig.",
                       "Für ein Kilogramm bräuchte es Tonnen an Früchten."],
                solution="Aromastoffe kommen in Früchten in winzigen Mengen vor. Für ein Kilogramm bräuchte es viele Tonnen Obst und entsprechende Anbaufläche. Die synthetische Herstellung liefert dasselbe Molekül mit weit geringerem Aufwand.",
                tags=["ester", "bewerten", "msa"]),
        aufgabe("ES02-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Ester sind ungefährlich, sie riechen ja nach Obst.“ Wie bewertest du das?",
                options=["Falsch — vom Geruch lässt sich nicht auf die Wirkung schließen; viele Ester sind leicht entzündbar und reizend.",
                         "Richtig.",
                         "Falsch — alle Ester sind giftig."],
                answer=0,
                hints=["Sagt der Geruch etwas über die Gefährdung?",
                       "Nein.",
                       "Ethylacetat ist leicht entzündbar."],
                solution="Ein angenehmer Geruch sagt nichts über die Gefährdung. Ethylacetat ist leicht entzündbar und reizt die Atemwege — deshalb tragen auch Nagellackentferner Gefahrensymbole.",
                misconceptions=[fv("sicherheitsregel_missachtet", 1,
                                   "Der Geruch ist kein Maßstab für die Gefährdung.",
                                   "sicherheitsregel_missachtet")],
                tags=["ester", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "ES-03",
    "title": "Fette als Glyceride",
    "leitidee": "B2",
    "standards": ["K1", "K2.1", "K4.1"],
    "klasse": 10,
    "wortspeicher": ["das Fett", "das Glycerid", "die Fettsäure", "das Glycerin",
                     "gesättigt", "ungesättigt", "die Härtung"],
    "worterklaerungen": {
        "Glycerid": "Ein Ester aus Glycerin und Fettsäuren.",
        "Fettsäure": "Eine langkettige Carbonsäure.",
        "Härtung": "Das Umwandeln ungesättigter in gesättigte Fettsäuren durch Wasserstoff."
    },
    "can_do": {
        "A": "Ich weiß, dass Fette aus Glycerin und Fettsäuren bestehen.",
        "B": "Ich erkläre den Unterschied zwischen Ölen und festen Fetten.",
        "C": "Ich begründe die Fetthärtung und bewerte ihre Folgen."
    },
    "lernkarten": {
        "A": karte("Fette sind Ester",
                   "Ein Fett besteht aus zwei Bausteinen.",
                   ["Aus Glycerin mit drei OH-Gruppen.",
                    "Und aus drei Fettsäuren."],
                   "Fett = Glycerin + drei Fettsäuren.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "ester", "name": "Glycerid",
                           "alt": "Strukturformel eines Fettmoleküls."},
                   beispiel={"titel": "Der Aufbau", "aufgabe": "Wie viele Esterbindungen hat ein Fett?",
                             "schritte": ["Glycerin hat drei OH-Gruppen.",
                                          "Jede reagiert mit einer Fettsäure."],
                             "ergebnis": "Drei Esterbindungen.",
                             "luecke": {"schritt": 1, "wert": 3}}),
        "B": karte("Öl oder fest",
                   "Ob ein Fett bei Zimmertemperatur flüssig oder fest ist, entscheidet der Bau der enthaltenen Fettsäuren.",
                   ["Gesättigte Fettsäuren haben gerade Ketten. Sie liegen dicht beieinander, die van-der-Waals-Kräfte sind stark — das Fett ist fest.",
                    "Ungesättigte Fettsäuren haben an der Doppelbindung einen Knick. Die Moleküle liegen weniger dicht, die Anziehung ist schwächer — das Fett ist flüssig.",
                    "Deshalb sind tierische Fette meist fest und pflanzliche Öle meist flüssig.",
                    "Mehrfach ungesättigte Fettsäuren gelten ernährungsphysiologisch als günstig.",
                    "Alle Fette sind unpolar und deshalb wasserunlöslich, aber in Benzin löslich."],
                   "Gerade Ketten packen dicht — fest. Geknickte Ketten packen locker — flüssig.",
                   visual=anim("seife", "B")),
        "C": karte("Fetthärtung",
                   "Aus flüssigem Öl lässt sich festes Fett machen, indem die Doppelbindungen entfernt werden. Das Verfahren ist technisch bedeutsam und ernährungsphysiologisch umstritten.",
                   ["Bei der Härtung wird Wasserstoff an die Doppelbindungen angelagert. Aus ungesättigten werden gesättigte Fettsäuren.",
                    "Die Ketten sind danach gerade, packen dichter und das Fett wird streichfähig oder fest — so entsteht Margarine.",
                    "Als Nebenprodukt können bei unvollständiger Härtung Fettsäuren mit veränderter räumlicher Anordnung entstehen, die als gesundheitlich ungünstig gelten.",
                    "Moderne Verfahren vermeiden das weitgehend, etwa durch vollständige Härtung mit anschließender Mischung.",
                    "Bewertung braucht ein Kriterium: Haltbarkeit und Streichfähigkeit sprechen für die Härtung, ernährungsphysiologische Gründe dagegen."],
                   "Härten heißt: Wasserstoff an die Doppelbindungen — aus flüssig wird fest.",
                   visual=anim("seife", "C"))
    },
    "formelkarte": {"formeln": ["Fett = Glycerin + 3 Fettsäuren (3 Esterbindungen)"],
                    "saetze": ["Gesättigte Fettsäuren: gerade Ketten, festes Fett.",
                               "Ungesättigte Fettsäuren: geknickte Ketten, flüssiges Öl.",
                               "Härtung: Anlagerung von Wasserstoff an Doppelbindungen.",
                               "Alle Fette sind unpolar und wasserunlöslich."]},
    "tasks": [
        aufgabe("ES03-A1-001", "A", 1, "choice",
                "Woraus besteht ein Fett?",
                options=["aus Glycerin und drei Fettsäuren", "aus Zucker", "aus Eiweiß"], answer=0,
                hints=["Es ist ein Ester.", "Der Alkohol ist Glycerin.", "Dazu drei Fettsäuren."],
                solution="Ein Fett ist ein Ester aus Glycerin und drei Fettsäuren.",
                tags=["fette"], spiral=["W-ORG"]),
        aufgabe("ES03-A2-002", "A", 2, "numeric",
                "Wie viele Esterbindungen hat ein Fettmolekül?",
                answer=3, tolerance=0,
                hints=["Glycerin hat drei OH-Gruppen.", "Jede bildet eine Bindung.", "3."],
                solution="Glycerin hat drei OH-Gruppen, also entstehen drei Esterbindungen.",
                tags=["fette"], spiral=["W-ORG"]),
        aufgabe("ES03-A3-003", "A", 3, "choice",
                "Warum sind Pflanzenöle bei Zimmertemperatur flüssig?",
                options=["Sie enthalten ungesättigte Fettsäuren mit geknickten Ketten.",
                         "Sie sind wärmer.", "Sie enthalten Wasser."],
                answer=0,
                hints=["Ungesättigt heißt: mit Doppelbindung.",
                       "Dort ist die Kette geknickt.",
                       "Geknickte Ketten packen locker."],
                solution="Ungesättigte Fettsäuren haben an der Doppelbindung einen Knick. Die Moleküle liegen weniger dicht beieinander — das Fett bleibt flüssig.",
                tags=["fette"], spiral=["W-ORG"]),
        aufgabe("ES03-A4-004", "A", 4, "choice",
                "Löst sich Fett in Wasser?",
                options=["Nein, Fett ist unpolar.", "Ja, gut.", "Nur bei Wärme."], answer=0,
                hints=["Gleiches löst sich in Gleichem.",
                       "Wasser ist polar.",
                       "Fett nicht."],
                solution="Fette bestehen aus langen unpolaren Ketten und lösen sich nicht in polarem Wasser — wohl aber in Benzin.",
                tags=["fette"], spiral=["W-LOES"]),
        aufgabe("ES03-B1-005", "B", 1, "choice",
                "Warum sind tierische Fette meist fest?",
                options=["Sie enthalten überwiegend gesättigte Fettsäuren mit geraden Ketten.",
                         "Sie enthalten mehr Wasser.",
                         "Sie sind schwerer."],
                answer=0,
                hints=["Gerade Ketten packen dicht.",
                       "Dann sind die Anziehungskräfte stark.",
                       "Das Fett ist fest."],
                solution="Gesättigte Fettsäuren haben gerade Ketten, die dicht beieinander liegen. Die van-der-Waals-Kräfte sind stark — das Fett ist fest.",
                tags=["fette", "bbr"], spiral=["W-ORG"]),
        aufgabe("ES03-B2-006", "B", 2, "choice",
                "Was geschieht bei der Fetthärtung?",
                options=["Wasserstoff wird an die Doppelbindungen angelagert.",
                         "Wasser wird entzogen.",
                         "Das Fett wird gekühlt."],
                answer=0,
                hints=["Aus ungesättigt wird gesättigt.",
                       "Die Doppelbindungen verschwinden.",
                       "Wasserstoff wird angelagert."],
                solution="Bei der Härtung wird Wasserstoff an die Doppelbindungen angelagert. Aus ungesättigten Fettsäuren werden gesättigte — das Öl wird streichfähig oder fest.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 2,
                                   "Kühlen wäre eine Zustandsänderung. Die Härtung ist eine chemische Reaktion.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["fette", "bbr"], spiral=["W-GLEI"]),
        aufgabe("ES03-B2-007", "B", 2, "choice",
                "Warum wird Öl durch Härtung fest?",
                options=["Ohne Doppelbindungen sind die Ketten gerade und packen dichter.",
                         "Weil Wasserstoff schwer ist.",
                         "Weil das Öl dabei abkühlt."],
                answer=0,
                hints=["Was verursacht den Knick?",
                       "Die Doppelbindung.",
                       "Ohne sie ist die Kette gerade."],
                solution="Die Doppelbindung erzeugt einen Knick. Wird sie durch Wasserstoffanlagerung beseitigt, sind die Ketten gerade und liegen dichter — die Anziehung wächst, das Fett wird fest.",
                tags=["fette", "msa"], spiral=["W-ORG"]),
        aufgabe("ES03-B3-008", "B", 3, "choice",
                "Wie weist du eine Doppelbindung in einem Öl nach?",
                options=["Mit Bromwasser — es wird entfärbt.",
                         "Mit Kalkwasser.", "Mit einem Glimmspan."],
                answer=0,
                hints=["Brom lagert sich an Doppelbindungen an.",
                       "Dabei verschwindet die Farbe.",
                       "Bromwasser."],
                solution="Brom lagert sich an Doppelbindungen an, dabei entfärbt sich das braune Bromwasser. Bei gesättigten Fetten bleibt die Farbe.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Kalkwasser weist Kohlenstoffdioxid nach.",
                                   "nachweis_verwechselt")],
                tags=["fette", "nachweise", "msa"], spiral=["W-GLEI"]),
        aufgabe("ES03-B3-009", "B", 3, "choice",
                "Warum verdirbt Öl mit vielen Doppelbindungen schneller?",
                options=["Die Doppelbindungen reagieren leicht mit Luftsauerstoff.",
                         "Es enthält mehr Wasser.",
                         "Es ist wärmer."],
                answer=0,
                hints=["Was macht eine Doppelbindung reaktionsfreudig?",
                       "Sie ist ein Angriffspunkt.",
                       "Sauerstoff greift dort an."],
                solution="Doppelbindungen sind reaktionsfreudige Stellen. Luftsauerstoff greift dort an, es entstehen ranzig riechende Abbauprodukte. Deshalb sind mehrfach ungesättigte Öle weniger lange haltbar.",
                tags=["fette", "bbr"], spiral=["W-GLEI"]),
        aufgabe("ES03-B4-010", "B", 4, "choice",
                "Warum lässt sich Fett mit Benzin, aber nicht mit Wasser vom Geschirr lösen?",
                options=["Benzin ist wie Fett unpolar, Wasser dagegen polar.",
                         "Benzin ist wärmer.",
                         "Benzin reagiert mit dem Fett."],
                answer=0,
                hints=["Gleiches löst sich in Gleichem.",
                       "Fett ist unpolar.",
                       "Benzin auch."],
                solution="Fett und Benzin sind beide unpolar und mischen sich vollständig. Wasser ist polar — deshalb braucht es dort Seife als Vermittler.",
                tags=["fette", "bbr"], spiral=["W-LOES"]),
        aufgabe("ES03-C2-011", "C", 2, "choice",
                "Warum gelten mehrfach ungesättigte Fettsäuren ernährungsphysiologisch als günstig?",
                options=["Der Körper kann einige davon nicht selbst herstellen und braucht sie für Zellmembranen.",
                         "Sie enthalten weniger Energie.",
                         "Sie sind leichter verdaulich."],
                answer=0,
                hints=["Manche Fettsäuren sind essenziell.",
                       "Der Körper kann sie nicht selbst bilden.",
                       "Sie müssen über die Nahrung kommen."],
                solution="Einige mehrfach ungesättigte Fettsäuren sind essenziell — der Körper kann sie nicht selbst herstellen und braucht sie unter anderem für den Aufbau von Zellmembranen. Der Energiegehalt ist praktisch gleich.",
                tags=["fette", "bewerten", "msa"]),
        aufgabe("ES03-C3-012", "C", 3, "choice",
                "Warum wird bei der Fetthärtung heute meist vollständig gehärtet und anschließend gemischt?",
                options=["Bei unvollständiger Härtung entstehen Fettsäuren mit ungünstiger räumlicher Anordnung.",
                         "Weil es billiger ist.",
                         "Weil vollständig gehärtetes Fett besser schmeckt."],
                answer=0,
                hints=["Was passiert bei teilweiser Härtung?",
                       "Nicht alle Doppelbindungen verschwinden.",
                       "Manche ändern nur ihre räumliche Anordnung."],
                solution="Bei teilweiser Härtung bleiben Doppelbindungen erhalten, ändern aber ihre räumliche Anordnung — die entstehenden Fettsäuren gelten als gesundheitlich ungünstig. Vollständige Härtung mit anschließender Mischung vermeidet das.",
                tags=["fette", "bewerten", "msa"]),
        aufgabe("ES03-C3-013", "C", 3, "multi",
                "Ein Fettmolekül besteht aus Glycerin (M = 92 g/mol) und drei Palmitinsäuremolekülen (M = 256 g/mol). Bei der Bildung werden drei Wassermoleküle abgespalten (M = 18 g/mol).",
                fields=[
                    {"label": "Summe der Edukte", "answer": 860, "unit_label": "g/mol", "tolerance": 5},
                    {"label": "Masse des abgespaltenen Wassers", "answer": 54, "unit_label": "g/mol", "tolerance": 2},
                    {"label": "molare Masse des Fettes", "answer": 806, "unit_label": "g/mol", "tolerance": 5}
                ],
                hints=["92 + 3 · 256.",
                       "3 · 18 = 54.",
                       "860 − 54."],
                solution="Edukte: 92 + 768 = 860 g/mol\nWasser: 3 · 18 = 54 g/mol\nFett: 860 − 54 = 806 g/mol",
                tags=["fette", "rechnen", "msa"], spiral=["W-RECH", "W-GLEI"]),
        aufgabe("ES03-C4-014", "C", 4, "choice",
                "Bewerte: „Pflanzliche Fette sind immer gesünder als tierische.“",
                options=["Zu pauschal — entscheidend ist der Anteil gesättigter Fettsäuren, und auch Kokosfett ist pflanzlich und stark gesättigt.",
                         "Richtig.",
                         "Falsch, tierische Fette sind immer besser."],
                answer=0,
                hints=["Gibt es pflanzliche Fette mit vielen gesättigten Fettsäuren?",
                       "Ja — Kokosfett und Palmfett.",
                       "Also entscheidet nicht die Herkunft."],
                solution="Kokos- und Palmfett sind pflanzlich und enthalten überwiegend gesättigte Fettsäuren. Fischöl ist tierisch und reich an ungesättigten. Nicht die Herkunft entscheidet, sondern die Zusammensetzung.",
                tags=["fette", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("es", E, "Bereich ES · Einheiten 2 und 3")
