# -*- coding: utf-8 -*-
"""Bereich WA · Wasser — WA-04 bis WA-06."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "WA-04",
    "title": "Elektronegativität, polare Bindung, Dipol",
    "leitidee": "B2",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 8,
    "wortspeicher": ["die Elektronegativität", "die polare Elektronenpaarbindung", "die Teilladung",
                     "der Dipol", "unpolar", "die Wasserstoffbrücke"],
    "worterklaerungen": {
        "Elektronegativität": "Wie stark ein Atom die bindenden Elektronen zu sich zieht.",
        "Teilladung": "Eine kleine Ladung an einem Atom, geschrieben als δ+ oder δ−.",
        "Dipol": "Ein Molekül mit einem positiven und einem negativen Ende."
    },
    "can_do": {
        "A": "Ich weiß, dass Wasser zwei geladene Enden hat, und erkenne das im Ablenkversuch.",
        "B": "Ich erkläre die polare Bindung über die Elektronegativität und kennzeichne Teilladungen.",
        "C": "Ich begründe, warum der gewinkelte Bau für den Dipolcharakter entscheidend ist."
    },
    "lernkarten": {
        "A": karte("Wasser hat zwei Enden",
                   "Ein Wasserstrahl wird von einem geriebenen Stab abgelenkt.",
                   ["Das Wassermolekül hat ein positives und ein negatives Ende.",
                    "Deshalb reagiert es auf Ladung."],
                   "Wasser ist ein Dipol: zwei verschieden geladene Enden.",
                   visual=anim("dipol", "A"),
                   beispiel={"titel": "Der Ablenkversuch", "aufgabe": "Was passiert mit dem Strahl?",
                             "schritte": ["Der Stab wird gerieben und geladen.",
                                          "Er wird an den Strahl gehalten.",
                                          "Der Strahl biegt sich zum Stab."],
                             "ergebnis": "Der Strahl wird abgelenkt."}),
        "B": karte("Ungleich verteilte Elektronen",
                   "In einer Bindung zwischen verschiedenen Atomen liegen die gemeinsamen Elektronen nicht in der Mitte. Wie stark sie zu einer Seite gezogen werden, gibt die Elektronegativität an.",
                   ["Sauerstoff hat eine höhere Elektronegativität als Wasserstoff. Er zieht das bindende Elektronenpaar zu sich.",
                    "Dadurch trägt der Sauerstoff eine negative Teilladung δ−, jedes Wasserstoffatom eine positive δ+.",
                    "Eine solche Bindung heißt polare Elektronenpaarbindung. Sind beide Atome gleich, etwa in H₂ oder O₂, ist die Bindung unpolar.",
                    "Zwischen den Teilladungen benachbarter Wassermoleküle wirken Anziehungskräfte — die Wasserstoffbrücken."],
                   "Verschiedene Elektronegativität → verschobene Elektronen → Teilladungen.",
                   visual=anim("dipol", "B")),
        "C": karte("Warum der Winkel entscheidet",
                   "Polare Bindungen allein machen noch keinen Dipol. Entscheidend ist, ob sich die Teilladungen im Molekül aufheben oder nicht — und das hängt am Bau.",
                   ["Im Wassermolekül stehen die beiden O–H-Bindungen im Winkel von etwa 105°. Die beiden positiven Enden liegen auf derselben Seite, das negative gegenüber. Die Wirkungen addieren sich zu einem Gesamtdipol.",
                    "Kohlenstoffdioxid hat ebenfalls polare Bindungen, ist aber gestreckt: O=C=O. Die beiden Wirkungen zeigen in entgegengesetzte Richtungen und heben sich auf. CO₂ ist deshalb kein Dipol.",
                    "Daraus folgt unmittelbar das Löseverhalten: Polare Stoffe lösen sich in polaren Lösungsmitteln, unpolare in unpolaren.",
                    "Auch Siedetemperatur und Oberflächenspannung des Wassers folgen aus den Wasserstoffbrücken zwischen den Dipolen."],
                   "Polare Bindungen plus unsymmetrischer Bau ergeben einen Dipol.",
                   visual={"type": "lewis", "molekuel": "co2", "formel": "CO2",
                           "alt": "Lewis-Formel von Kohlenstoffdioxid — gestreckt gebaut."})
    },
    "formelkarte": {"formeln": ["ΔEN(O–H) ≈ 1,4 → polare Bindung"],
                    "saetze": ["Höhere Elektronegativität zieht die bindenden Elektronen zu sich.",
                               "Gleiche Atome → unpolare Bindung. Verschiedene Atome → polare Bindung.",
                               "Wasser ist gewinkelt (105°) und damit ein Dipol.",
                               "CO₂ hat polare Bindungen, ist aber gestreckt — kein Dipol.",
                               "Zwischen Wasserdipolen wirken Wasserstoffbrücken."]},
    "tasks": [
        aufgabe("WA04-A1-001", "A", 1, "choice",
                "Was passiert, wenn ein geriebener Stab an einen dünnen Wasserstrahl gehalten wird?",
                options=["Der Strahl wird abgelenkt.", "Der Strahl reißt ab.", "Nichts passiert."],
                answer=0, visual=anim("dipol", "A"),
                hints=["Wasser hat geladene Enden.", "Der Stab ist geladen.", "Ladungen wirken aufeinander."],
                solution="Der Strahl wird zum geladenen Stab hin abgelenkt, weil die Wassermoleküle geladene Enden haben.",
                tags=["dipol"], spiral=["W-TEIL"]),
        aufgabe("WA04-A2-002", "A", 2, "choice",
                "Welches Atom im Wassermolekül trägt die negative Teilladung?",
                options=["der Sauerstoff", "die Wasserstoffatome", "keines"], answer=0,
                visual={"type": "lewis", "molekuel": "h2o", "alt": "Lewis-Formel von Wasser."},
                hints=["Welches Atom zieht die Elektronen stärker an?",
                       "Der Sauerstoff.",
                       "Wo Elektronen sind, ist es negativ."],
                solution="Der Sauerstoff zieht die bindenden Elektronen zu sich und trägt deshalb die negative Teilladung δ−.",
                misconceptions=[fv("teilladung_vertauscht", 1,
                                   "Die Wasserstoffatome tragen die positive Teilladung δ+.",
                                   "polar_unpolar_vertauscht")],
                tags=["dipol"], spiral=["W-TEIL"]),
        aufgabe("WA04-A3-003", "A", 3, "choice",
                "Was bedeutet „Dipol“?",
                options=["Ein Molekül mit einem positiven und einem negativen Ende.",
                         "Ein Molekül aus zwei Atomen.", "Ein Molekül mit zwei Bindungen."],
                answer=0,
                hints=["Das Wort enthält „di“ für zwei und „pol“ für Pol.", "Es geht um Ladungen.", "Zwei geladene Enden."],
                solution="Ein Dipol hat zwei entgegengesetzt geladene Enden — ein positives und ein negatives.",
                tags=["dipol"], spiral=["W-TEIL"]),
        aufgabe("WA04-A4-004", "A", 4, "choice",
                "Warum wird ein Benzinstrahl nicht abgelenkt?",
                options=["Benzinmoleküle sind keine Dipole.", "Benzin ist zu leicht.", "Benzin ist brennbar."],
                answer=0,
                hints=["Wovon hängt die Ablenkung ab?", "Von geladenen Enden.", "Benzin hat keine."],
                solution="Benzin besteht aus unpolaren Molekülen ohne geladene Enden. Ein geladener Stab wirkt deshalb nicht auf sie.",
                tags=["dipol"], spiral=["W-STOF"]),
        aufgabe("WA04-B1-005", "B", 1, "choice",
                "Was gibt die Elektronegativität an?",
                options=["Wie stark ein Atom die bindenden Elektronen zu sich zieht.",
                         "Wie viele Elektronen ein Atom hat.",
                         "Wie negativ ein Ion geladen ist."],
                answer=0,
                hints=["Es geht um die Bindung.", "Wer zieht stärker?", "Das ist die Elektronegativität."],
                solution="Die Elektronegativität beschreibt, wie stark ein Atom die gemeinsamen Elektronen einer Bindung zu sich zieht. Sie steigt im Periodensystem nach rechts und nach oben.",
                misconceptions=[fv("ion_und_atom_verwechselt", 2,
                                   "Die Elektronegativität beschreibt die Bindung, nicht die Ionenladung.",
                                   "ion_und_atom_verwechselt")],
                tags=["dipol", "bbr"], spiral=["W-TEIL"]),
        aufgabe("WA04-B2-006", "B", 2, "assign",
                "Ordne jede Bindung richtig ein.",
                slots=["H–H in H₂", "O–H in H₂O", "Cl–Cl in Cl₂"],
                values=["unpolar", "polar", "unpolar (zweites)"],
                answer=[0, 1, 2],
                hints=["Sind die Atome gleich oder verschieden?",
                       "Gleiche Atome ziehen gleich stark.",
                       "Nur bei O–H sind die Atome verschieden."],
                solution="H–H und Cl–Cl verbinden gleiche Atome — die Elektronen liegen mittig, die Bindung ist unpolar. Bei O–H sind die Atome verschieden, die Bindung ist polar.",
                tags=["dipol", "bbr"], spiral=["W-SYMB"]),
        aufgabe("WA04-B2-007", "B", 2, "choice",
                "Warum ziehen sich Wassermoleküle gegenseitig an?",
                options=["Das positive Ende des einen zieht das negative Ende des anderen an.",
                         "Sie haben dieselbe Masse.",
                         "Sie bilden gemeinsame Elektronenpaare."],
                answer=0,
                hints=["Was haben Wassermoleküle für Enden?",
                       "Ein positives und ein negatives.",
                       "Ungleiche Ladungen ziehen sich an."],
                solution="Das δ+ des einen Moleküls und das δ− eines anderen ziehen sich an. Diese Anziehung heißt Wasserstoffbrücke und erklärt die hohe Siedetemperatur des Wassers.",
                misconceptions=[fv("bindungsart_verwechselt", 2,
                                   "Zwischen den Molekülen entstehen keine gemeinsamen Elektronenpaare — das wäre eine Bindung innerhalb eines Moleküls.",
                                   "bindungsart_verwechselt")],
                tags=["dipol", "bbr"], spiral=["W-TEIL"]),
        aufgabe("WA04-B3-008", "B", 3, "choice",
                "Kohlenstoffdioxid hat polare Bindungen, ist aber kein Dipol. Warum?",
                options=["Das Molekül ist gestreckt; die beiden Wirkungen heben sich auf.",
                         "Die Bindungen sind doch unpolar.",
                         "Kohlenstoffdioxid ist ein Gas."],
                answer=0,
                visual={"type": "lewis", "molekuel": "co2", "alt": "Lewis-Formel von Kohlenstoffdioxid."},
                hints=["Wie ist CO₂ gebaut?",
                       "Gestreckt: O=C=O.",
                       "Beide Wirkungen zeigen in entgegengesetzte Richtungen."],
                solution="In O=C=O zeigen beide polaren Bindungen in entgegengesetzte Richtungen und heben sich auf. Wäre CO₂ gewinkelt wie Wasser, wäre es ein Dipol. Der Bau entscheidet.",
                misconceptions=[fv("polar_unpolar_vertauscht", 1,
                                   "Die Bindungen sind sehr wohl polar. Es ist der gestreckte Bau, der den Dipol verhindert.",
                                   "polar_unpolar_vertauscht")],
                tags=["dipol", "msa"], spiral=["W-SYMB"]),
        aufgabe("WA04-B3-009", "B", 3, "choice",
                "Warum siedet Wasser trotz kleiner Moleküle erst bei 100 °C?",
                options=["Die Wasserstoffbrücken zwischen den Molekülen müssen erst überwunden werden.",
                         "Wassermoleküle sind besonders schwer.",
                         "Wasser enthält gelöste Luft."],
                answer=0,
                hints=["Was hält die Moleküle zusammen?",
                       "Die Anziehung zwischen den Dipolen.",
                       "Zum Sieden müssen sie getrennt werden."],
                solution="Beim Sieden müssen die Moleküle voneinander getrennt werden. Die starken Wasserstoffbrücken machen dafür viel Energie nötig — deshalb 100 °C statt der erwarteten −80 °C.",
                tags=["dipol", "bbr"], spiral=["W-STOF"]),
        aufgabe("WA04-B4-010", "B", 4, "choice",
                "Warum lösen sich Salze gut in Wasser, aber nicht in Benzin?",
                options=["Die Wasserdipole umlagern die Ionen; unpolares Benzin kann das nicht.",
                         "Benzin ist zu dünnflüssig.",
                         "Salze sind schwerer als Benzin."],
                answer=0,
                hints=["Was brauchen Ionen, um in Lösung zu gehen?",
                       "Geladene Partner.",
                       "Nur polare Moleküle bieten die."],
                solution="Wassermoleküle sind Dipole und lagern sich mit ihren Teilladungen um die Ionen. Benzinmoleküle sind unpolar und können die Ionen nicht aus dem Gitter lösen.",
                tags=["dipol", "loesen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA04-C2-011", "C", 2, "choice",
                "Ammoniak NH₃ ist pyramidal gebaut und hat polare N–H-Bindungen. Ist es ein Dipol?",
                options=["Ja — die Wirkungen heben sich wegen des unsymmetrischen Baus nicht auf.",
                         "Nein — es hat drei gleiche Bindungen.",
                         "Nein — Stickstoff ist nicht elektronegativ."],
                answer=0, visual={"type": "lewis", "molekuel": "nh3", "alt": "Lewis-Formel von Ammoniak."},
                hints=["Ist das Molekül symmetrisch gebaut?",
                       "Nein — das freie Elektronenpaar steht auf einer Seite.",
                       "Dann heben sich die Wirkungen nicht auf."],
                solution="Drei gleiche Bindungen genügen nicht für ein Aufheben — entscheidend ist die räumliche Anordnung. Durch das freie Elektronenpaar ist NH₃ pyramidal und damit unsymmetrisch. Es ist ein Dipol; deshalb löst es sich sehr gut in Wasser.",
                tags=["dipol", "msa"], spiral=["W-SYMB"]),
        aufgabe("WA04-C3-012", "C", 3, "choice",
                "Welche Aussage über Wasserstoffbrücken ist richtig?",
                options=["Sie wirken zwischen Molekülen und sind schwächer als eine Elektronenpaarbindung.",
                         "Sie wirken innerhalb eines Moleküls und sind stärker als eine Bindung.",
                         "Sie sind dasselbe wie eine Elektronenpaarbindung."],
                answer=0,
                hints=["Wo wirken sie?",
                       "Zwischen Molekülen.",
                       "Und sie sind deutlich schwächer als eine echte Bindung."],
                solution="Wasserstoffbrücken wirken zwischen Molekülen und sind rund zehnmal schwächer als eine Elektronenpaarbindung. Beim Sieden werden sie gelöst — die Moleküle selbst bleiben unversehrt.",
                misconceptions=[fv("bindungsart_verwechselt", 2,
                                   "Wasserstoffbrücken sind zwischenmolekulare Kräfte, keine Bindungen innerhalb des Moleküls.",
                                   "bindungsart_verwechselt")],
                tags=["dipol", "msa"], spiral=["W-TEIL"]),
        aufgabe("WA04-C3-013", "C", 3, "choice",
                "Warum verdampft Alkohol schneller als Wasser, obwohl seine Moleküle schwerer sind?",
                options=["Alkohol bildet weniger Wasserstoffbrücken je Molekül als Wasser.",
                         "Alkohol ist unpolar.",
                         "Alkoholmoleküle sind kleiner."],
                answer=0,
                hints=["Wie viele OH-Gruppen hat ein Alkoholmolekül?",
                       "Eine — Wasser hat zwei H-Atome am Sauerstoff.",
                       "Weniger Brücken heißt leichteres Verdampfen."],
                solution="Ein Ethanolmolekül hat nur eine OH-Gruppe und bildet dadurch weniger Wasserstoffbrücken als ein Wassermolekül. Die Moleküle lassen sich leichter voneinander trennen — trotz größerer Masse verdampft Alkohol schneller.",
                tags=["dipol", "msa"], spiral=["W-ORG"]),
        aufgabe("WA04-C4-014", "C", 4, "choice",
                "Ein Schüler folgert: „Ein Molekül mit polaren Bindungen ist immer ein Dipol.“ Wie bewertest du das?",
                options=["Falsch — CO₂ und CH₄ haben polare Bindungen und sind trotzdem keine Dipole, weil sie symmetrisch gebaut sind.",
                         "Richtig — polare Bindungen ergeben immer einen Dipol.",
                         "Falsch — polare Bindungen gibt es gar nicht."],
                answer=0,
                hints=["Nenne ein Gegenbeispiel.",
                       "Kohlenstoffdioxid.",
                       "Der Bau entscheidet mit."],
                solution="Polare Bindungen sind notwendig, aber nicht hinreichend. Erst ein unsymmetrischer Bau lässt die Wirkungen sich addieren. CO₂ und CH₄ sind Gegenbeispiele — beide haben polare Bindungen und sind keine Dipole.",
                misconceptions=[fv("polar_unpolar_vertauscht", 1,
                                   "Ein Gegenbeispiel genügt zur Widerlegung: CO₂ hat polare Bindungen und ist kein Dipol.",
                                   "polar_unpolar_vertauscht")],
                tags=["dipol", "bewerten", "msa"], spiral=["W-SYMB"])
    ]
})

E.append({
    "unit": "WA-05",
    "title": "Wasser als Lösungsmittel",
    "leitidee": "B2",
    "standards": ["K1", "K2.2", "K3.3"],
    "klasse": 8,
    "wortspeicher": ["das Lösungsmittel", "die Hydrathülle", "polar", "unpolar",
                     "die Löslichkeit", "die Emulsion"],
    "worterklaerungen": {
        "Hydrathülle": "Eine Schicht aus Wassermolekülen, die ein Ion umgibt.",
        "unpolar": "Ohne geladene Enden. Fette und Öle sind unpolar.",
        "Emulsion": "Feine Tröpfchen einer Flüssigkeit in einer anderen."
    },
    "can_do": {
        "A": "Ich weiß, dass sich Salz und Zucker in Wasser lösen, Öl aber nicht.",
        "B": "Ich erkläre das Lösen mit der Hydrathülle und wende die Regel „Gleiches löst Gleiches“ an.",
        "C": "Ich sage anhand des Molekülbaus voraus, ob ein Stoff wasserlöslich ist."
    },
    "lernkarten": {
        "A": karte("Was sich in Wasser löst",
                   "Nicht alles löst sich in Wasser.",
                   ["Salz und Zucker lösen sich.", "Öl und Fett lösen sich nicht."],
                   "Gleiches löst sich in Gleichem.",
                   visual=anim("loesen", "A"),
                   beispiel={"titel": "Öl und Wasser", "aufgabe": "Öl wird in Wasser gegeben.",
                             "schritte": ["Es bilden sich Tropfen.", "Die Tropfen schwimmen oben.",
                                          "Sie lösen sich nicht."],
                             "ergebnis": "Öl ist unpolar, Wasser polar."}),
        "B": karte("Wie das Lösen abläuft",
                   "Beim Lösen eines Salzes geschieht mehr, als es aussieht: Ein festes Gitter wird auseinandergenommen und jedes einzelne Ion neu umgeben.",
                   ["Die Wasserdipole lagern sich mit ihrem negativen Ende an die positiven Ionen und mit dem positiven Ende an die negativen.",
                    "Dadurch werden die Ionen aus dem Gitter gelöst und einzeln von Wassermolekülen umhüllt — das ist die Hydrathülle.",
                    "Weil die Ionen nun frei beweglich sind, leitet die Lösung den elektrischen Strom.",
                    "Regel: Polare Stoffe lösen sich in polaren Lösungsmitteln, unpolare in unpolaren."],
                   "Gleiches löst sich in Gleichem — polar zu polar, unpolar zu unpolar.",
                   visual=anim("loesen", "B")),
        "C": karte("Löslichkeit vorhersagen",
                   "Ob ein Stoff wasserlöslich ist, lässt sich am Molekülbau ablesen — und das gilt bis in die organische Chemie hinein.",
                   ["Geladene Teilchen und stark polare Gruppen wie –OH oder –COOH machen wasserlöslich.",
                    "Lange Kohlenwasserstoffketten machen unlöslich. Bei den Alkoholen kippt es zwischen Propanol und Butanol: Der unpolare Rest wird zu groß.",
                    "Seifen tragen beides — einen geladenen Kopf und einen langen unpolaren Schwanz. Deshalb vermitteln sie zwischen Fett und Wasser.",
                    "Löslich heißt nicht unbegrenzt: Jede Lösung erreicht eine Sättigungsgrenze, und die hängt von der Temperatur ab."],
                   "Polare Gruppen machen löslich, lange unpolare Ketten unlöslich.",
                   visual=anim("loesen", "C"))
    },
    "formelkarte": {"formeln": ["w = m(Stoff) : m(Lösung) · 100 %"],
                    "saetze": ["Gleiches löst sich in Gleichem.",
                               "Wasser ist polar, Öl und Benzin sind unpolar.",
                               "Gelöste Ionen tragen eine Hydrathülle und leiten den Strom.",
                               "Polare Gruppen (–OH, –COOH) machen wasserlöslich."]},
    "tasks": [
        aufgabe("WA05-A1-001", "A", 1, "choice",
                "Welcher Stoff löst sich in Wasser?",
                options=["Kochsalz", "Speiseöl", "Sand"], answer=0,
                hints=["Zwei der drei lösen sich nicht.", "Öl schwimmt oben, Sand sinkt.", "Kochsalz löst sich."],
                solution="Kochsalz löst sich in Wasser. Öl und Sand nicht.",
                tags=["loesen"], spiral=["W-LOES"]),
        aufgabe("WA05-A2-002", "A", 2, "choice",
                "Warum löst sich Öl nicht in Wasser?",
                options=["Öl ist unpolar, Wasser polar.", "Öl ist zu schwer.", "Öl ist zu warm."],
                answer=0, visual=anim("loesen", "A"),
                hints=["Gleiches löst sich in Gleichem.", "Wasser ist polar.", "Öl nicht."],
                solution="Wasser ist polar, Öl unpolar. Nach der Regel „Gleiches löst sich in Gleichem“ mischen sie sich nicht.",
                tags=["loesen"], spiral=["W-LOES"]),
        aufgabe("WA05-A3-003", "A", 3, "choice",
                "Was passiert mit den Ionen, wenn sich Salz in Wasser löst?",
                options=["Sie werden von Wassermolekülen umhüllt.", "Sie verschwinden.", "Sie werden zu Atomen."],
                answer=0,
                hints=["Die Ionen sind noch da — das Wasser schmeckt salzig.",
                       "Was passiert um sie herum?",
                       "Wassermoleküle legen sich um sie."],
                solution="Die Ionen werden aus dem Gitter gelöst und einzeln von Wassermolekülen umhüllt. Sie verschwinden nicht — beim Eindampfen kommen sie zurück.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Gelöst heißt nicht verschwunden. Beim Eindampfen erhältst du das Salz zurück.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["loesen"], spiral=["W-LOES"]),
        aufgabe("WA05-A4-004", "A", 4, "numeric",
                "In 200 g Wasser werden 20 g Zucker gelöst. Wie viel Prozent Zucker enthält die Lösung?",
                answer=9.09, unit_label="%", tolerance=0.2,
                hints=["Das Ganze ist Zucker plus Wasser.", "20 + 200 = 220 g.", "20 : 220."],
                solution="20 g : 220 g = 0,0909 → 9,09 %",
                misconceptions=[fv("loesungsmittel_als_ganzes", 10,
                                   "Du hast nur durch das Wasser geteilt. Der Zucker gehört auch zur Lösung.")],
                tags=["loesen", "rechnen"], spiral=["W-LOES"]),
        aufgabe("WA05-B1-005", "B", 1, "choice",
                "Was ist eine Hydrathülle?",
                options=["Die Schicht aus Wassermolekülen um ein gelöstes Ion.",
                         "Eine dünne Wasserhaut auf der Oberfläche.",
                         "Der Wasserdampf über einer Lösung."],
                answer=0, visual=anim("loesen", "B"),
                hints=["Es geht um gelöste Ionen.", "Was legt sich um sie herum?", "Wassermoleküle."],
                solution="Die Wasserdipole lagern sich mit ihren Teilladungen um jedes gelöste Ion. Diese Schicht heißt Hydrathülle.",
                tags=["loesen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA05-B2-006", "B", 2, "choice",
                "Warum leitet eine Kochsalzlösung den Strom, festes Kochsalz aber nicht?",
                options=["Erst in Lösung sind die Ionen frei beweglich.",
                         "Erst in Lösung entstehen Ionen.",
                         "Wasser leitet den Strom allein."],
                answer=0,
                hints=["Sind im Kristall schon Ionen vorhanden?",
                       "Ja — aber auf festen Plätzen.",
                       "Beweglich werden sie erst in Lösung."],
                solution="Auch im Kristall liegen Ionen vor, aber auf festen Gitterplätzen. Erst in Lösung sind sie beweglich und können Ladung transportieren. Reines Wasser leitet praktisch nicht.",
                misconceptions=[fv("ion_und_atom_verwechselt", 1,
                                   "Ionen entstehen nicht erst beim Lösen — sie sind bereits im Gitter vorhanden, nur unbeweglich.",
                                   "ion_und_atom_verwechselt")],
                tags=["loesen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA05-B2-007", "B", 2, "choice",
                "Warum löst sich Fett gut in Benzin?",
                options=["Beide sind unpolar.", "Beide sind polar.", "Benzin ist wärmer als Wasser."],
                answer=0,
                hints=["Gleiches löst sich in Gleichem.", "Fett ist unpolar.", "Benzin auch."],
                solution="Fett und Benzin sind beide unpolar. Nach der Regel „Gleiches löst sich in Gleichem“ mischen sie sich vollständig — deshalb wirken Benzin und ähnliche Lösungsmittel als Fettlöser.",
                tags=["loesen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA05-B3-008", "B", 3, "numeric",
                "Bei 20 °C lösen sich 36 g Kochsalz in 100 g Wasser. Wie viel löst sich in 250 g Wasser?",
                answer=90, unit_label="g", tolerance=1,
                hints=["Dreisatz: erst auf 1 g Wasser.", "36 : 100 = 0,36 g je Gramm.", "0,36 · 250."],
                solution="36 g je 100 g → 250 g : 100 · 36 g = 90 g",
                misconceptions=[fv("anteil_umgedreht", 14.4,
                                   "Du hast geteilt statt zu vervielfachen. Mehr Wasser löst mehr Salz.")],
                tags=["loesen", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA05-B3-009", "B", 3, "choice",
                "Warum löst sich Zucker in warmem Wasser schneller und mehr?",
                options=["Die Teilchen bewegen sich schneller und die Löslichkeit steigt mit der Temperatur.",
                         "Warmes Wasser ist polarer.",
                         "Zucker schmilzt im warmen Wasser."],
                answer=0,
                hints=["Was ändert sich bei höherer Temperatur?",
                       "Die Teilchenbewegung.",
                       "Und bei Feststoffen meist auch die Löslichkeit."],
                solution="Bei höherer Temperatur bewegen sich die Teilchen schneller — der Kristall wird rascher abgebaut. Zusätzlich steigt bei den meisten Feststoffen die Löslichkeit mit der Temperatur.",
                misconceptions=[fv("reaktion_und_zustandsaenderung_verwechselt", 2,
                                   "Zucker schmilzt erst bei rund 185 °C. Im Wasser löst er sich, er schmilzt nicht.",
                                   "reaktion_und_zustandsaenderung_verwechselt")],
                tags=["loesen", "bbr"], spiral=["W-LOES"]),
        aufgabe("WA05-B4-010", "B", 4, "choice",
                "Warum lässt sich fettige Kleidung mit Wasser allein nicht reinigen?",
                options=["Fett ist unpolar und wird von Wasser nicht gelöst — es braucht Seife als Vermittler.",
                         "Wasser ist zu kalt.",
                         "Fett ist schwerer als Wasser."],
                answer=0,
                hints=["Löst Wasser Fett?", "Nein — beide sind zu verschieden.", "Seife vermittelt zwischen beiden."],
                solution="Wasser ist polar, Fett unpolar — sie lösen einander nicht. Seifenmoleküle haben einen unpolaren und einen polaren Teil und vermitteln deshalb zwischen beiden.",
                tags=["loesen", "anwenden", "msa"], spiral=["W-LOES"]),
        aufgabe("WA05-C2-011", "C", 2, "choice",
                "Methanol und Ethanol mischen sich vollständig mit Wasser, Hexanol kaum. Warum?",
                options=["Mit wachsender Kettenlänge überwiegt der unpolare Teil des Moleküls.",
                         "Hexanol hat keine OH-Gruppe.",
                         "Hexanol ist schwerer."],
                answer=0,
                hints=["Alle drei haben eine OH-Gruppe.",
                       "Was unterscheidet sie?",
                       "Die Länge der Kohlenwasserstoffkette."],
                solution="Alle drei besitzen eine polare OH-Gruppe. Bei Methanol dominiert sie das Molekül, bei Hexanol überwiegt die lange unpolare Kette. Zwischen Propanol und Butanol kippt das Verhalten.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Auch Hexanol hat eine OH-Gruppe. Entscheidend ist das Verhältnis zum unpolaren Rest.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["loesen", "msa"], spiral=["W-ORG"]),
        aufgabe("WA05-C3-012", "C", 3, "multi",
                "300 g einer Lösung enthalten 4 % Salz. Sie wird auf 120 g eingedampft.",
                fields=[
                    {"label": "Salzmasse in der Lösung", "answer": 12, "unit_label": "g", "tolerance": 0.1},
                    {"label": "Salzanteil nach dem Eindampfen", "answer": 10, "unit_label": "%", "tolerance": 0.2}
                ],
                hints=["4 % von 300 g.",
                       "Die Salzmasse bleibt beim Eindampfen gleich.",
                       "12 g : 120 g · 100 %."],
                solution="Salz: 300 g · 0,04 = 12 g\nnach dem Eindampfen: 12 g : 120 g = 10 %\nNur Wasser verdampft — das Salz bleibt vollständig.",
                tags=["loesen", "rechnen", "msa"], spiral=["W-LOES"]),
        aufgabe("WA05-C3-013", "C", 3, "choice",
                "Warum steigt die Löslichkeit von Gasen mit sinkender Temperatur, die von Feststoffen aber meist mit steigender?",
                options=["Gase entweichen bei Wärme leichter aus der Lösung; bei Feststoffen hilft die Wärme, das Gitter zu lösen.",
                         "Gase sind leichter als Feststoffe.",
                         "Es ist bei beiden gleich."],
                answer=0,
                hints=["Was passiert mit Gasteilchen bei Wärme?",
                       "Sie werden schneller und entweichen.",
                       "Beim Feststoff muss dagegen ein Gitter aufgebrochen werden."],
                solution="Gelöste Gasteilchen entweichen bei Wärme leichter — deshalb perlt warmes Mineralwasser aus. Bei Feststoffen muss Gitterenergie überwunden werden; Wärme hilft dabei. Beide Trends folgen aus dem, was beim Lösen jeweils geschehen muss.",
                tags=["loesen", "msa"], spiral=["W-LOES"]),
        aufgabe("WA05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Alles löst sich irgendwann, man muss nur genug rühren.“ Wie bewertest du das?",
                options=["Falsch — jede Lösung hat eine Sättigungsgrenze, und unpolare Stoffe lösen sich in Wasser praktisch gar nicht.",
                         "Richtig — Rühren löst alles.",
                         "Falsch — Rühren hat gar keine Wirkung."],
                answer=0,
                hints=["Was passiert, wenn du immer mehr Salz zugibst?",
                       "Irgendwann bleibt es liegen.",
                       "Und Öl löst sich auch mit Rühren nicht."],
                solution="Rühren beschleunigt das Lösen, verschiebt aber die Sättigungsgrenze nicht. Über der Grenze bleibt Bodensatz liegen. Unpolare Stoffe lösen sich in Wasser ohnehin praktisch nicht — dagegen hilft kein Rühren.",
                tags=["loesen", "bewerten", "msa"], spiral=["W-LOES"])
    ]
})

if __name__ == "__main__":
    schreiben("wa", E, "Bereich WA · Einheiten 4 und 5")
