# -*- coding: utf-8 -*-
"""Bereich AL · Alkohole — AL-05 bis AL-07."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "AL-05",
    "title": "Primär, sekundär, tertiär — Oxidationsprodukte",
    "leitidee": "B3",
    "standards": ["K1", "K2.3", "K3.4"],
    "klasse": 10,
    "wortspeicher": ["primär", "sekundär", "tertiär", "das Alkanal", "das Alkanon",
                     "die Oxidation", "die Aldehydgruppe", "die Carbonylgruppe"],
    "worterklaerungen": {
        "primärer Alkohol": "Das C-Atom mit der OH-Gruppe hat nur einen C-Nachbarn.",
        "sekundärer Alkohol": "Das C-Atom mit der OH-Gruppe hat zwei C-Nachbarn.",
        "tertiärer Alkohol": "Das C-Atom mit der OH-Gruppe hat drei C-Nachbarn.",
        "Alkanal": "Ein Aldehyd. Entsteht aus einem primären Alkohol.",
        "Alkanon": "Ein Keton. Entsteht aus einem sekundären Alkohol."
    },
    "can_do": {
        "A": "Ich weiß, dass aus Alkoholen durch Oxidation neue Stoffe entstehen.",
        "B": "Ich unterscheide primäre, sekundäre und tertiäre Alkohole und nenne ihre Oxidationsprodukte.",
        "C": "Ich begründe, warum tertiäre Alkohole nicht oxidierbar sind."
    },
    "lernkarten": {
        "A": karte("Aus Alkohol wird etwas Neues",
                   "Ein Alkohol kann oxidiert werden.",
                   ["Dabei entsteht ein neuer Stoff.", "Er hat eine andere funktionelle Gruppe."],
                   "Oxidation ändert die funktionelle Gruppe.",
                   visual=anim("funktionellegruppe", "A"),
                   beispiel={"titel": "Ethanol wird oxidiert",
                             "aufgabe": "Was entsteht?",
                             "schritte": ["Zuerst ein Alkanal.", "Dann eine Säure."],
                             "ergebnis": "Ethanol → Ethanal → Essigsäure"}),
        "B": karte("Drei Sorten Alkohole",
                   "Wie ein Alkohol reagiert, entscheidet sich daran, wie viele Kohlenstoffnachbarn das Atom mit der OH-Gruppe hat.",
                   ["Primär: ein C-Nachbar. Die Oxidation ergibt ein Alkanal, weiter oxidiert eine Alkansäure.",
                    "Sekundär: zwei C-Nachbarn. Die Oxidation ergibt ein Alkanon — und hört dort auf.",
                    "Tertiär: drei C-Nachbarn. Es findet keine Oxidation statt.",
                    "Nachweis: Kupferoxid oder eine Kupferspirale in der Flamme. Bei primären und sekundären Alkoholen wird das schwarze Kupferoxid zu rotem Kupfer reduziert.",
                    "Ethanol → Ethanal → Essigsäure ist der Weg, der auch im Körper abläuft."],
                   "Primär → Alkanal → Säure. Sekundär → Alkanon. Tertiär → gar nichts.",
                   visual=anim("funktionellegruppe", "B")),
        "C": karte("Warum tertiär nicht geht",
                   "Dass tertiäre Alkohole sich nicht oxidieren lassen, folgt unmittelbar aus dem Bau — und ist ein gutes Beispiel dafür, wie Struktur Reaktionsverhalten bestimmt.",
                   ["Bei der Oxidation wird dem C-Atom mit der OH-Gruppe ein Wasserstoffatom entzogen; die entstehende Doppelbindung zum Sauerstoff bildet die Carbonylgruppe.",
                    "Ein primäres C-Atom trägt zwei H-Atome, ein sekundäres eines — beide können abgegeben werden.",
                    "Ein tertiäres C-Atom trägt kein Wasserstoffatom mehr: Alle drei übrigen Bindungen gehen an Kohlenstoff. Es gibt nichts zu entziehen.",
                    "Deshalb bleibt die Kupferspirale beim tertiären Alkohol schwarz — der Nachweis fällt negativ aus.",
                    "Auch der Abbau im Körper folgt diesem Weg: Ethanol ist primär, wird zu Ethanal und weiter zu Essigsäure oxidiert."],
                   "Kein Wasserstoff am C-Atom der OH-Gruppe — keine Oxidation.",
                   visual=anim("funktionellegruppe", "C"))
    },
    "formelkarte": {"formeln": ["primär: R–CH₂–OH → R–CHO → R–COOH",
                               "sekundär: R₂CH–OH → R₂C=O",
                               "tertiär: keine Oxidation"],
                    "saetze": ["Primär: ein C-Nachbar · sekundär: zwei · tertiär: drei.",
                               "Primäre Alkohole ergeben Alkanale, dann Alkansäuren.",
                               "Sekundäre Alkohole ergeben Alkanone.",
                               "Tertiäre Alkohole lassen sich nicht oxidieren.",
                               "Nachweis mit Kupferoxid: schwarz wird rot."]},
    "tasks": [
        aufgabe("AL05-A1-001", "A", 1, "choice",
                "Was entsteht, wenn ein primärer Alkohol oxidiert wird?",
                options=["zuerst ein Alkanal", "sofort eine Säure", "ein Alkan"], answer=0,
                visual=anim("funktionellegruppe", "A"),
                hints=["Es gibt zwei Schritte.", "Der erste führt zum Alkanal.", "Alkanal."],
                solution="Ein primärer Alkohol wird zuerst zum Alkanal oxidiert, dann weiter zur Alkansäure.",
                tags=["oxidation"], spiral=["K-ORG"]),
        aufgabe("AL05-A2-002", "A", 2, "choice",
                "Was entsteht aus Ethanol beim vollständigen Oxidieren?",
                options=["Essigsäure", "Methanol", "Ethan"], answer=0,
                hints=["Ethanol → Ethanal → ?", "Die Säure mit zwei C-Atomen.", "Essigsäure."],
                solution="Ethanol wird über Ethanal zu Essigsäure oxidiert. Denselben Weg geht der Abbau im Körper.",
                tags=["oxidation"], spiral=["K-ORG"]),
        aufgabe("AL05-A3-003", "A", 3, "choice",
                "Was zeigt eine Kupferspirale, die von schwarz zu rot wird?",
                options=["Der Alkohol lässt sich oxidieren.", "Der Alkohol ist tertiär.", "Es ist kein Alkohol."],
                answer=0,
                hints=["Schwarzes Kupferoxid wird zu rotem Kupfer.",
                       "Es wurde also reduziert.",
                       "Der Alkohol hat dafür Elektronen geliefert."],
                solution="Das schwarze Kupferoxid wird zu rotem Kupfer reduziert. Der Alkohol wurde dabei oxidiert — er ist also primär oder sekundär.",
                tags=["oxidation", "nachweise"], spiral=["K-REAK"]),
        aufgabe("AL05-A4-004", "A", 4, "choice",
                "Welcher Alkohol lässt sich nicht oxidieren?",
                options=["ein tertiärer", "ein primärer", "ein sekundärer"], answer=0,
                hints=["Bei einem fehlt das nötige Wasserstoffatom.",
                       "Beim tertiären.",
                       "Tertiär."],
                solution="Ein tertiärer Alkohol trägt am C-Atom der OH-Gruppe kein Wasserstoffatom mehr — er lässt sich nicht oxidieren.",
                tags=["oxidation"], spiral=["K-ORG"]),
        aufgabe("AL05-B1-005", "B", 1, "choice",
                "Wie erkennst du einen sekundären Alkohol?",
                options=["Das C-Atom mit der OH-Gruppe hat zwei C-Nachbarn.",
                         "Das Molekül hat zwei OH-Gruppen.",
                         "Es hat zwei C-Atome."],
                answer=0,
                visual={"type": "struktur", "kette": 3, "gruppe": "oh", "position": 2,
                        "alt": "Strukturformel eines sekundären Alkohols."},
                hints=["Es geht um die Nachbarn des C-Atoms mit der OH-Gruppe.",
                       "Zwei C-Nachbarn.",
                       "Nicht um die Zahl der OH-Gruppen."],
                solution="Entscheidend ist, wie viele Kohlenstoffnachbarn das C-Atom mit der OH-Gruppe hat: zwei bedeutet sekundär.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Die Zahl der OH-Gruppen bestimmt die Wertigkeit, nicht primär/sekundär/tertiär.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["oxidation", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL05-B2-006", "B", 2, "choice",
                "Was entsteht bei der Oxidation eines sekundären Alkohols?",
                options=["ein Alkanon", "ein Alkanal", "eine Säure"], answer=0,
                visual=anim("funktionellegruppe", "B"),
                hints=["Alkanale entstehen aus primären Alkoholen.",
                       "Aus sekundären entsteht etwas anderes.",
                       "Ein Alkanon, auch Keton genannt."],
                solution="Ein sekundärer Alkohol wird zum Alkanon oxidiert — und dort endet die Reihe. Propan-2-ol ergibt Propanon, das Aceton.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 1,
                                   "Alkanale entstehen aus primären Alkoholen.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["oxidation", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL05-B2-007", "B", 2, "assign",
                "Ordne jedem Alkoholtyp sein Oxidationsprodukt zu.",
                slots=["primär", "sekundär", "tertiär"],
                values=["Alkanal, dann Alkansäure", "Alkanon", "keine Oxidation"],
                answer=[0, 1, 2],
                hints=["Primär geht zwei Schritte.",
                       "Sekundär endet nach einem.",
                       "Tertiär gar nicht."],
                solution="primär → Alkanal → Alkansäure\nsekundär → Alkanon\ntertiär → keine Oxidation",
                tags=["oxidation", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL05-B3-008", "B", 3, "choice",
                "Warum lässt sich ein tertiärer Alkohol nicht oxidieren?",
                options=["Am C-Atom der OH-Gruppe sitzt kein Wasserstoffatom mehr.",
                         "Er ist zu groß.",
                         "Er hat keine OH-Gruppe."],
                answer=0,
                visual=anim("funktionellegruppe", "C"),
                hints=["Was wird bei der Oxidation entzogen?",
                       "Ein Wasserstoffatom vom C-Atom der OH-Gruppe.",
                       "Beim tertiären ist dort keines."],
                solution="Bei der Oxidation wird dem C-Atom der OH-Gruppe ein H-Atom entzogen. Beim tertiären Alkohol gehen alle drei übrigen Bindungen an Kohlenstoff — es gibt kein H-Atom zu entziehen.",
                tags=["oxidation", "msa"], spiral=["K-ORG"]),
        aufgabe("AL05-B3-009", "B", 3, "choice",
                "Was entsteht aus Propan-2-ol bei der Oxidation?",
                options=["Propanon (Aceton)", "Propansäure", "Propanal"], answer=0,
                hints=["Wo sitzt die OH-Gruppe?",
                       "Am mittleren C-Atom — also sekundär.",
                       "Sekundär ergibt ein Alkanon."],
                solution="Propan-2-ol ist ein sekundärer Alkohol. Die Oxidation ergibt Propanon — bekannt als Aceton.",
                misconceptions=[fv("funktionelle_gruppe_verwechselt", 2,
                                   "Propanal entstünde aus Propan-1-ol, einem primären Alkohol.",
                                   "funktionelle_gruppe_verwechselt")],
                tags=["oxidation", "bbr"], spiral=["K-ORG"]),
        aufgabe("AL05-B4-010", "B", 4, "choice",
                "Warum wird beim Alkoholabbau im Körper zuerst Ethanal gebildet?",
                options=["Ethanol ist ein primärer Alkohol; die Oxidation führt zunächst zum Alkanal.",
                         "Weil Ethanal ungiftig ist.",
                         "Weil der Körper keine Säuren bilden kann."],
                answer=0,
                hints=["Welcher Typ ist Ethanol?",
                       "Primär.",
                       "Primär ergibt zuerst ein Alkanal."],
                solution="Ethanol ist ein primärer Alkohol. Der erste Oxidationsschritt führt zum Ethanal, das für einen Teil der Katerbeschwerden verantwortlich ist. Erst der zweite Schritt liefert Essigsäure.",
                tags=["oxidation", "msa"], spiral=["K-ORG"]),
        aufgabe("AL05-C2-011", "C", 2, "choice",
                "Wie unterscheidest du experimentell einen sekundären von einem tertiären Alkohol?",
                options=["Mit einer glühenden Kupferspirale: Beim sekundären wird sie rot, beim tertiären bleibt sie schwarz.",
                         "Am Geruch.",
                         "An der Löslichkeit."],
                answer=0,
                hints=["Welcher Nachweis zeigt Oxidierbarkeit?",
                       "Die Kupferoxid-Probe.",
                       "Nur oxidierbare Alkohole reduzieren das Kupferoxid."],
                solution="Nur ein oxidierbarer Alkohol reduziert das schwarze Kupferoxid zu rotem Kupfer. Der tertiäre Alkohol kann das nicht — die Spirale bleibt schwarz.",
                tags=["oxidation", "nachweise", "msa"], spiral=["K-REAK"]),
        aufgabe("AL05-C3-012", "C", 3, "choice",
                "Warum endet die Oxidation eines sekundären Alkohols beim Alkanon?",
                options=["Am Carbonyl-C-Atom sitzt kein Wasserstoff mehr, der weiter entzogen werden könnte.",
                         "Alkanone sind besonders stabil gegen Wärme.",
                         "Sekundäre Alkohole reagieren nur einmal."],
                answer=0,
                hints=["Beim Alkanal sitzt am Carbonyl-C noch ein H-Atom.",
                       "Beim Alkanon nicht.",
                       "Ohne H keine weitere Oxidation."],
                solution="Beim Alkanal trägt das Carbonyl-C-Atom noch ein Wasserstoffatom — deshalb kann es weiter zur Säure oxidiert werden. Beim Alkanon sind beide Nachbarplätze von Kohlenstoff besetzt; die Reihe endet.",
                tags=["oxidation", "msa"], spiral=["K-ORG"]),
        aufgabe("AL05-C3-013", "C", 3, "assign",
                "Ordne jeden Alkohol seinem Typ zu.",
                slots=["Ethanol CH₃–CH₂–OH", "Propan-2-ol", "2-Methylpropan-2-ol"],
                values=["primär", "sekundär", "tertiär"], answer=[0, 1, 2],
                hints=["Zähle die C-Nachbarn des C-Atoms mit der OH-Gruppe.",
                       "Ethanol: einer.",
                       "2-Methylpropan-2-ol: drei."],
                solution="Ethanol: ein C-Nachbar → primär.\nPropan-2-ol: zwei → sekundär.\n2-Methylpropan-2-ol: drei → tertiär.",
                tags=["oxidation", "msa"], spiral=["K-ORG"]),
        aufgabe("AL05-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Alle Alkohole werden zu Säuren oxidiert.“ Wie bewertest du das?",
                options=["Falsch — nur primäre; sekundäre enden beim Alkanon, tertiäre reagieren gar nicht.",
                         "Richtig.",
                         "Falsch — kein Alkohol wird zu einer Säure."],
                answer=0,
                hints=["Was passiert bei sekundären Alkoholen?",
                       "Sie enden beim Alkanon.",
                       "Und tertiäre reagieren nicht."],
                solution="Nur primäre Alkohole durchlaufen die vollständige Reihe bis zur Säure. Sekundäre enden beim Alkanon, tertiäre lassen sich gar nicht oxidieren. Der Bau entscheidet über den Reaktionsweg.",
                misconceptions=[fv("verallgemeinert", 1,
                                   "Der Weg zur Säure gilt nur für primäre Alkohole.")],
                tags=["oxidation", "bewerten", "msa"], spiral=["K-ORG"])
    ]
})

E.append({
    "unit": "AL-06",
    "title": "Gärung, Destillation und Promillerechnung",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K4.2", "K4.3"],
    "klasse": 10,
    "wortspeicher": ["die alkoholische Gärung", "die Hefe", "das Enzym", "die Destillation",
                     "der Volumenanteil", "der Promillewert", "die Blutalkoholkonzentration"],
    "worterklaerungen": {
        "alkoholische Gärung": "Hefe wandelt Zucker in Ethanol und Kohlenstoffdioxid um.",
        "Enzym": "Ein biologischer Katalysator.",
        "Promille": "Ein Tausendstel. 1 ‰ sind 0,1 %."
    },
    "can_do": {
        "A": "Ich weiß, dass bei der Gärung Alkohol und Kohlenstoffdioxid entstehen.",
        "B": "Ich beschreibe Gärung und Destillation und rechne mit Volumenanteilen.",
        "C": "Ich berechne Blutalkoholwerte und bewerte die Folgen."
    },
    "lernkarten": {
        "A": karte("Aus Zucker wird Alkohol",
                   "Hefe wandelt Zucker um.",
                   ["Es entstehen Alkohol und Kohlenstoffdioxid.", "Das nennt man Gärung."],
                   "Zucker → Alkohol + Kohlenstoffdioxid.",
                   visual={"type": "apparatur", "aufbau": "destillation",
                           "alt": "Destillationsapparatur zur Alkoholgewinnung."},
                   beispiel={"titel": "Traubensaft", "aufgabe": "Was passiert bei der Gärung?",
                             "schritte": ["Hefe wird zugegeben.", "Es blubbert.",
                                          "Das Gas ist Kohlenstoffdioxid."],
                             "ergebnis": "Es entsteht Wein."}),
        "B": karte("Gärung und Destillation",
                   "Zwei Verfahren, die aufeinander aufbauen: Die Gärung erzeugt den Alkohol, die Destillation konzentriert ihn.",
                   ["Gärung: C₆H₁₂O₆ → 2 C₂H₅OH + 2 CO₂. Hefeenzyme wirken als Katalysator.",
                    "Die Gärung endet bei etwa 15 Volumenprozent — höhere Konzentrationen töten die Hefe ab.",
                    "Destillation: Ethanol siedet bei 78 °C, Wasser bei 100 °C. Der Dampf ist deshalb alkoholreicher als die Flüssigkeit.",
                    "Durch mehrfache Destillation lassen sich rund 96 Volumenprozent erreichen. Reines Ethanol geht so nicht — Wasser und Ethanol bilden bei dieser Zusammensetzung ein Gemisch mit gemeinsamem Siedepunkt.",
                    "Volumenprozent geben an, wie viel Milliliter reiner Alkohol in 100 mL Getränk stecken."],
                   "Gärung erzeugt bis 15 %, Destillation konzentriert auf bis zu 96 %.",
                   visual={"type": "anteil", "titel": "Alkoholgehalt einiger Getränke",
                           "segmente": [{"anteil": 5, "label": "Bier"}, {"anteil": 12, "label": "Wein"},
                                        {"anteil": 40, "label": "Schnaps"}],
                           "einheit": "Vol.-%",
                           "alt": "Alkoholgehalt von Bier, Wein und Schnaps im Vergleich."}),
        "C": karte("Blutalkohol berechnen",
                   "Aus der getrunkenen Menge lässt sich der Blutalkoholwert abschätzen. Die Rechnung ist einfach — die Folgerungen daraus sind es nicht.",
                   ["Zuerst die Masse des reinen Alkohols: Volumen des Getränks · Volumenanteil · Dichte (0,8 g/mL).",
                    "Dann die Widmark-Formel: c = m(Alkohol) : (Körpermasse · r). Der Faktor r beträgt rund 0,7 bei Männern und 0,6 bei Frauen.",
                    "Das Ergebnis ist die Blutalkoholkonzentration in Promille.",
                    "Der Abbau beträgt rund 0,1 bis 0,15 ‰ je Stunde und lässt sich durch nichts beschleunigen — weder durch Kaffee noch durch Bewegung.",
                    "Ab 0,3 ‰ ist die Reaktionsfähigkeit messbar eingeschränkt; ab 0,5 ‰ gilt im Straßenverkehr ein Bußgeld, für Fahranfänger gilt 0,0 ‰."],
                   "Erst die Alkoholmasse, dann teilen durch Körpermasse mal r.",
                   visual={"type": "diagramm", "titel": "Abbau des Blutalkohols",
                           "xtitel": "Zeit in Stunden", "ytitel": "Promille",
                           "punkte": [[0, 1.0], [2, 0.8], [4, 0.6], [6, 0.4], [8, 0.2], [10, 0.0]],
                           "ymin": 0, "ymax": 1.2,
                           "alt": "Der Blutalkohol sinkt gleichmäßig um rund 0,1 Promille je Stunde."})
    },
    "formelkarte": {"formeln": ["C₆H₁₂O₆ → 2 C₂H₅OH + 2 CO₂",
                               "m(Alkohol) = V(Getränk) · Vol.-% : 100 · 0,8 g/mL",
                               "c in ‰ = m(Alkohol) in g : (Körpermasse in kg · r)",
                               "r ≈ 0,7 (Mann) bzw. 0,6 (Frau)"],
                    "saetze": ["Gärung endet bei etwa 15 Volumenprozent.",
                               "Ethanol siedet bei 78 °C, Wasser bei 100 °C.",
                               "Abbau: rund 0,1 bis 0,15 ‰ je Stunde — nicht beschleunigbar.",
                               "Dichte von Ethanol: 0,8 g/mL."]},
    "tasks": [
        aufgabe("AL06-A1-001", "A", 1, "choice",
                "Was entsteht bei der alkoholischen Gärung?",
                options=["Alkohol und Kohlenstoffdioxid", "nur Alkohol", "Alkohol und Sauerstoff"],
                answer=0,
                hints=["Es blubbert bei der Gärung.", "Ein Gas entweicht.", "Kohlenstoffdioxid."],
                solution="Aus Zucker entstehen Ethanol und Kohlenstoffdioxid — das Blubbern zeigt das Gas an.",
                tags=["gaerung"], spiral=["K-REAK"]),
        aufgabe("AL06-A2-002", "A", 2, "choice",
                "Was bewirkt die Hefe bei der Gärung?",
                options=["Ihre Enzyme wirken als Katalysator.", "Sie liefert den Zucker.", "Sie liefert den Alkohol."],
                answer=0,
                hints=["Die Hefe wird nicht verbraucht.", "Sie beschleunigt nur.", "Als Katalysator."],
                solution="Die Enzyme der Hefe wirken als biologische Katalysatoren. Der Alkohol entsteht aus dem Zucker, nicht aus der Hefe.",
                tags=["gaerung"], spiral=["K-REAK"]),
        aufgabe("AL06-A3-003", "A", 3, "numeric",
                "Ein Bier hat 5 Volumenprozent. Wie viele Milliliter reiner Alkohol sind in 500 mL?",
                answer=25, unit_label="mL", tolerance=1,
                hints=["5 % von 500 mL.", "1 % sind 5 mL.", "5 · 5 mL."],
                solution="500 mL · 0,05 = 25 mL reiner Alkohol.",
                tags=["gaerung", "rechnen"], spiral=["K-SL"]),
        aufgabe("AL06-A4-004", "A", 4, "choice",
                "Warum lässt sich Alkohol durch Destillation von Wasser trennen?",
                options=["Ethanol siedet bei 78 °C, Wasser erst bei 100 °C.",
                         "Alkohol ist leichter.", "Alkohol löst sich nicht in Wasser."],
                answer=0,
                hints=["Die Destillation nutzt einen Unterschied.",
                       "Es ist die Siedetemperatur.",
                       "78 gegen 100 °C."],
                solution="Ethanol siedet bei niedrigerer Temperatur und geht deshalb zuerst in den Dampf über. Im Kühler wird es wieder flüssig.",
                misconceptions=[fv("trennverfahren_verwechselt", 1,
                                   "Die Dichte spielt bei der Destillation keine Rolle — beide mischen sich vollständig.",
                                   "trennverfahren_verwechselt")],
                tags=["gaerung"], spiral=["K-STOF"]),
        aufgabe("AL06-B1-005", "B", 1, "numeric",
                "Warum endet die Gärung bei etwa 15 Volumenprozent? Gib den Wert in Prozent an.",
                answer=15, unit_label="%", tolerance=1,
                hints=["Höhere Konzentrationen wirken auf die Hefe.",
                       "Sie stirbt ab.",
                       "Bei etwa 15 %."],
                solution="Ab etwa 15 Volumenprozent wirkt der Alkohol auf die Hefezellen als Zellgift — sie sterben ab und die Gärung endet. Höhere Gehalte erfordern eine Destillation.",
                tags=["gaerung", "bbr"], spiral=["K-SL"]),
        aufgabe("AL06-B2-006", "B", 2, "numeric",
                "Wie viel Gramm reiner Alkohol stecken in 200 mL Wein mit 12 Volumenprozent? (Dichte 0,8 g/mL)",
                answer=19.2, unit_label="g", tolerance=0.5,
                hints=["Erst das Volumen: 200 · 0,12 = 24 mL.",
                       "Dann mal die Dichte.",
                       "24 · 0,8."],
                solution="V = 200 mL · 0,12 = 24 mL\nm = 24 mL · 0,8 g/mL = 19,2 g",
                misconceptions=[fv("dichte_geteilt_statt_mal", 30,
                                   "Aus Volumen und Dichte wird die Masse durch Multiplizieren.")],
                tags=["gaerung", "rechnen", "bbr"], spiral=["K-SL", "K-STOF"]),
        aufgabe("AL06-B2-007", "B", 2, "choice",
                "Warum lässt sich durch Destillation kein reines Ethanol gewinnen?",
                options=["Bei rund 96 % bilden Wasser und Ethanol ein Gemisch mit gemeinsamem Siedepunkt.",
                         "Weil der Kühler zu klein ist.",
                         "Weil Ethanol zu schnell verdampft."],
                answer=0,
                hints=["Bis zu welchem Gehalt kommt man?",
                       "Etwa 96 %.",
                       "Dann sieden beide gemeinsam."],
                solution="Bei etwa 96 Volumenprozent verhalten sich Wasser und Ethanol wie ein einheitlicher Stoff und sieden gemeinsam. Weiter kommt man durch Destillation nicht — dafür braucht es andere Verfahren.",
                tags=["gaerung", "msa"], spiral=["K-STOF"]),
        aufgabe("AL06-B3-008", "B", 3, "numeric",
                "Ein Mann (80 kg, r = 0,7) trinkt 19,2 g reinen Alkohol. Welchen Promillewert erreicht er?",
                answer=0.34, unit_label="‰", tolerance=0.03,
                hints=["c = m : (Körpermasse · r).",
                       "19,2 : (80 · 0,7).",
                       "19,2 : 56."],
                solution="c = 19,2 g : (80 kg · 0,7) = 19,2 : 56 = 0,34 ‰",
                misconceptions=[fv("mol_geteilt_statt_mal", 1075,
                                   "Die Körpermasse mal r steht im Nenner — hier wird geteilt.")],
                tags=["gaerung", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("AL06-B3-009", "B", 3, "numeric",
                "Wie lange dauert der Abbau von 1,0 ‰ bei 0,1 ‰ je Stunde?",
                answer=10, unit_label="h", tolerance=0.5,
                hints=["1,0 geteilt durch 0,1.", "10.", "10 Stunden."],
                solution="1,0 ‰ : 0,1 ‰/h = 10 Stunden. Der Abbau lässt sich durch nichts beschleunigen.",
                tags=["gaerung", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("AL06-B4-010", "B", 4, "choice",
                "Was beschleunigt den Abbau von Alkohol im Blut?",
                options=["Nichts — der Abbau läuft mit konstanter Geschwindigkeit.",
                         "Kaffee", "Bewegung an der frischen Luft"],
                answer=0,
                hints=["Der Abbau erfolgt durch Enzyme.",
                       "Ihre Arbeitsgeschwindigkeit ist begrenzt.",
                       "Nichts beschleunigt sie."],
                solution="Der Abbau erfolgt enzymatisch in der Leber mit nahezu konstanter Geschwindigkeit von 0,1 bis 0,15 ‰ je Stunde. Kaffee macht wacher, senkt aber den Blutalkohol nicht.",
                misconceptions=[fv("sicherheitsregel_missachtet", 1,
                                   "Kaffee wirkt auf die Müdigkeit, nicht auf den Blutalkohol.",
                                   "sicherheitsregel_missachtet")],
                tags=["gaerung", "bewerten", "msa"]),
        aufgabe("AL06-C2-011", "C", 2, "multi",
                "Eine Frau (60 kg, r = 0,6) trinkt 0,5 L Bier mit 5 Volumenprozent. (Dichte Ethanol 0,8 g/mL)",
                fields=[
                    {"label": "Volumen des reinen Alkohols", "answer": 25, "unit_label": "mL", "tolerance": 1},
                    {"label": "Masse des Alkohols", "answer": 20, "unit_label": "g", "tolerance": 1},
                    {"label": "Blutalkoholkonzentration", "answer": 0.56, "unit_label": "‰", "tolerance": 0.05}
                ],
                hints=["500 mL · 0,05 = 25 mL.",
                       "25 · 0,8 = 20 g.",
                       "20 : (60 · 0,6) = 20 : 36."],
                solution="V = 25 mL · m = 20 g\nc = 20 : (60 · 0,6) = 20 : 36 = 0,56 ‰\nDamit läge sie bereits über der Grenze von 0,5 ‰.",
                tags=["gaerung", "rechnen", "msa"], spiral=["K-QUANT", "K-SL"]),
        aufgabe("AL06-C3-012", "C", 3, "multi",
                "Aus 180 g Traubenzucker C₆H₁₂O₆ (M = 180 g/mol) entsteht bei vollständiger Gärung Ethanol (M = 46 g/mol).",
                fields=[
                    {"label": "Stoffmenge des Zuckers", "answer": 1, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Stoffmenge des Ethanols", "answer": 2, "unit_label": "mol", "tolerance": 0.05},
                    {"label": "Masse des Ethanols", "answer": 92, "unit_label": "g", "tolerance": 2}
                ],
                hints=["n = 180 : 180 = 1 mol.",
                       "C₆H₁₂O₆ → 2 C₂H₅OH + 2 CO₂.",
                       "m = 2 · 46 = 92 g."],
                solution="n(Zucker) = 1 mol\nn(Ethanol) = 2 mol\nm(Ethanol) = 92 g — der Rest der Masse entweicht als CO₂.",
                tags=["gaerung", "rechnen", "msa"], spiral=["K-QUANT", "K-REAK"]),
        aufgabe("AL06-C3-013", "C", 3, "choice",
                "Warum gilt für Fahranfänger die Grenze 0,0 ‰?",
                options=["Bereits geringe Mengen schränken die Reaktionsfähigkeit ein, und die Fahrpraxis fehlt noch.",
                         "Weil junge Menschen Alkohol schneller abbauen.",
                         "Aus rein steuerlichen Gründen."],
                answer=0,
                hints=["Ab wann ist die Reaktionsfähigkeit messbar eingeschränkt?",
                       "Ab etwa 0,3 ‰.",
                       "Und Fahranfängern fehlt zusätzlich die Routine."],
                solution="Schon ab etwa 0,3 ‰ sind Reaktionszeit und Einschätzungsvermögen messbar eingeschränkt. Bei Fahranfängern kommt fehlende Routine hinzu — beides zusammen begründet die Nullgrenze.",
                tags=["gaerung", "bewerten", "msa"]),
        aufgabe("AL06-C4-014", "C", 4, "choice",
                "Ein Schüler rechnet: „Ich habe 1,0 ‰, in zwei Stunden bin ich wieder bei null.“ Wie bewertest du das?",
                options=["Falsch — bei 0,1 bis 0,15 ‰ je Stunde dauert es rund 7 bis 10 Stunden.",
                         "Richtig.",
                         "Falsch — der Abbau dauert nur eine Stunde."],
                answer=0,
                hints=["Wie schnell ist der Abbau?",
                       "0,1 bis 0,15 ‰ je Stunde.",
                       "1,0 geteilt durch 0,15 ist schon fast 7."],
                solution="Bei 0,15 ‰ je Stunde dauert der Abbau von 1,0 ‰ rund 7 Stunden, bei 0,1 ‰ sogar 10. Diese Fehleinschätzung ist eine der häufigsten Ursachen für Fahrten am Morgen danach.",
                misconceptions=[fv("sicherheitsregel_missachtet", 1,
                                   "Der Abbau dauert Stunden, nicht Minuten — und lässt sich nicht beschleunigen.",
                                   "sicherheitsregel_missachtet")],
                tags=["gaerung", "bewerten", "msa"], spiral=["K-QUANT"])
    ]
})

if __name__ == "__main__":
    schreiben("al", E, "Bereich AL · Einheiten 5 und 6")
