# -*- coding: utf-8 -*-
"""SL-07 (Abschluss Säuren) sowie KW-01 und KW-02 (Kohlenwasserstoffe)."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

SL = []
KW = []

SL.append({
    "unit": "SL-07",
    "title": "Anwenden & Prüfungstraining Säuren",
    "leitidee": "B3",
    "standards": ["K1", "K2.4", "K3.3", "K4.1"],
    "klasse": 9,
    "wortspeicher": ["die Protolyse", "die pH-Skala", "die Neutralisation", "die Titration",
                     "das Salz", "der Indikator"],
    "worterklaerungen": {
        "Titration": "Ein Messverfahren zur Bestimmung einer unbekannten Konzentration."
    },
    "can_do": {
        "A": "Ich ordne pH-Werte, Indikatorfarben und Stoffe sicher zu.",
        "B": "Ich stelle Neutralisationsgleichungen auf und rechne mit Konzentrationen.",
        "C": "Ich begründe Säure-Base-Reaktionen über die Protonenübertragung und bewerte Aussagen."
    },
    "lernkarten": {
        "A": karte("Säuren und Laugen im Überblick",
                   "In dieser Stunde kommt alles zusammen.",
                   ["H₃O⁺ macht sauer, OH⁻ macht alkalisch.", "Zusammen ergeben sie Wasser."],
                   "Erst lesen, was gefragt ist. Dann antworten.",
                   visual=anim("signalwoerter", "A")),
        "B": karte("Die drei roten Fäden",
                   "Der ganze Bereich hängt an drei Zusammenhängen.",
                   ["Protolyse: Säuren geben Protonen ab, Basen nehmen sie auf. Das Wasser ist immer beteiligt.",
                    "pH-Skala: Sie misst die Konzentration der Oxonium-Ionen. Eine Stufe ist der Faktor 10.",
                    "Neutralisation: H₃O⁺ + OH⁻ → 2 H₂O. Die übrigen Ionen bilden das Salz."],
                   "Protonenübertragung erklärt alles — von der Indikatorfarbe bis zur Titration.",
                   visual=anim("protolyse", "B")),
        "C": karte("Typische Prüfungsfehler",
                   "Vier Fehler kommen in Prüfungen immer wieder vor. Wer sie kennt, vermeidet sie.",
                   ["Stärke und Konzentration verwechseln: Eine verdünnte starke Säure ist saurer als eine konzentrierte schwache.",
                    "Die pH-Skala linear lesen: Zwischen pH 3 und pH 5 liegt der Faktor 100, nicht 2.",
                    "Säure und saure Lösung gleichsetzen: Ohne Wasser keine Oxonium-Ionen.",
                    "Bei der Titration die Protonenzahl vergessen: Eine zweiprotonige Säure verbraucht doppelt so viel Lauge."],
                   "Stärke ist nicht Konzentration. Eine pH-Stufe ist ein Faktor 10.",
                   visual=anim("signalwoerter", "C"))
    },
    "formelkarte": {"formeln": ["HCl + H₂O → H₃O⁺ + Cl⁻",
                               "H₃O⁺ + OH⁻ → 2 H₂O",
                               "Säure + Lauge → Salz + Wasser",
                               "c₁ · V₁ = c₂ · V₂"],
                    "saetze": ["pH < 7 sauer · = 7 neutral · > 7 alkalisch.",
                               "Eine pH-Stufe entspricht dem Faktor 10.",
                               "Metalloxid + Wasser → Lauge · Nichtmetalloxid + Wasser → Säure.",
                               "Am Äquivalenzpunkt sind die Stoffmengen gleich."]},
    "tasks": [
        aufgabe("SL07-A1-001", "A", 1, "choice",
                "Welches Teilchen macht eine Lösung sauer?",
                options=["H₃O⁺", "OH⁻", "Na⁺"], answer=0,
                hints=["Es entsteht durch Protonenaufnahme des Wassers.", "Es heißt Oxonium-Ion.", "H₃O⁺."],
                solution="Das Oxonium-Ion H₃O⁺ macht eine Lösung sauer.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "OH⁻ macht eine Lösung alkalisch.",
                                   "saeure_lauge_vertauscht")],
                tags=["pruefung"], spiral=["W-SYMB"]),
        aufgabe("SL07-A2-002", "A", 2, "choice",
                "Eine Lösung hat pH 12. Wie ist sie einzuordnen?",
                options=["alkalisch", "sauer", "neutral"], answer=0,
                hints=["Neutral ist 7.", "12 liegt darüber.", "Alkalisch."],
                solution="pH 12 liegt deutlich über 7 — die Lösung ist alkalisch.",
                tags=["pruefung"], spiral=["W-LOES"]),
        aufgabe("SL07-A3-003", "A", 3, "choice",
                "Was entsteht bei der Neutralisation immer?",
                options=["Wasser und ein Salz", "ein Gas", "ein Metall"], answer=0,
                hints=["H₃O⁺ und OH⁻ ergeben Wasser.", "Die übrigen Ionen bilden das Salz.", "Beides."],
                solution="Bei jeder Neutralisation entstehen Wasser und ein Salz.",
                tags=["pruefung"], spiral=["W-GLEI"]),
        aufgabe("SL07-A4-004", "A", 4, "numeric",
                "Eine Säure mit pH 2 wird zehnfach verdünnt. Welchen pH-Wert hat sie danach?",
                answer=3, tolerance=0,
                hints=["Eine Stufe Richtung 7.", "2 + 1.", "3."],
                solution="Zehnfaches Verdünnen verschiebt den pH-Wert um eine Stufe: von 2 auf 3.",
                misconceptions=[fv("ph_skala_falschrum", 1,
                                   "Verdünnen macht weniger sauer — der pH-Wert steigt.",
                                   "ph_skala_falschrum")],
                tags=["pruefung"], spiral=["W-LOES"]),
        aufgabe("SL07-B1-005", "B", 1, "choice",
                "Welches Salz entsteht aus Salpetersäure und Natronlauge?",
                options=["Natriumnitrat", "Natriumsulfat", "Natriumchlorid"], answer=0,
                hints=["Der Säurerest der Salpetersäure ist Nitrat.",
                       "Das Metall stammt aus der Lauge.",
                       "Natriumnitrat."],
                solution="HNO₃ + NaOH → NaNO₃ + H₂O. Das Salz ist Natriumnitrat.",
                tags=["pruefung", "bbr"], spiral=["W-SYMB"]),
        aufgabe("SL07-B2-006", "B", 2, "numeric",
                "30 mL Säure werden mit 24 mL Natronlauge (0,1 mol/L) neutralisiert. Wie groß ist die Säurekonzentration? (einprotonige Säure)",
                answer=0.08, unit_label="mol/L", tolerance=0.005,
                hints=["c₁ · V₁ = c₂ · V₂.",
                       "c₁ = 0,1 · 24 : 30.",
                       "0,08 mol/L."],
                solution="c(Säure) = 0,1 mol/L · 24 mL : 30 mL = 0,08 mol/L",
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL07-B2-007", "B", 2, "choice",
                "Welche Lösung entsteht, wenn Schwefeldioxid in Wasser geleitet wird?",
                options=["eine saure Lösung", "eine alkalische Lösung", "eine neutrale Lösung"],
                answer=0,
                hints=["Schwefel ist ein Nichtmetall.",
                       "Nichtmetalloxid + Wasser → Säure.",
                       "Sauer."],
                solution="SO₂ ist ein Nichtmetalloxid und bildet mit Wasser schweflige Säure — die Lösung ist sauer.",
                misconceptions=[fv("saeure_lauge_vertauscht", 1,
                                   "Alkalisch würde ein Metalloxid ergeben.",
                                   "saeure_lauge_vertauscht")],
                tags=["pruefung", "bbr"], spiral=["W-GLEI"]),
        aufgabe("SL07-B3-008", "B", 3, "choice",
                "Warum ist verdünnte Salzsäure saurer als konzentrierte Essigsäure gleicher Konzentration?",
                options=["Salzsäure gibt ihre Protonen praktisch vollständig ab, Essigsäure nur teilweise.",
                         "Salzsäure ist konzentrierter.",
                         "Essigsäure ist keine Säure."],
                answer=0,
                hints=["Was unterscheidet starke und schwache Säuren?",
                       "Wie vollständig sie Protonen abgeben.",
                       "Salzsäure ist stark."],
                solution="Bei gleicher Konzentration entstehen aus der starken Säure fast alle möglichen Oxonium-Ionen, aus der schwachen nur wenige Prozent. Stärke und Konzentration sind zwei verschiedene Größen.",
                misconceptions=[fv("staerke_und_konzentration", 1,
                                   "Die Konzentration ist laut Aufgabe gleich. Verschieden ist die Stärke.")],
                tags=["pruefung", "msa"], spiral=["W-LOES"]),
        aufgabe("SL07-B3-009", "B", 3, "numeric",
                "Um welchen Faktor unterscheidet sich die Oxonium-Konzentration bei pH 2 und pH 6?",
                answer=10000, tolerance=0,
                hints=["Vier Stufen Unterschied.", "Jede Stufe Faktor 10.", "10⁴."],
                solution="Vier Stufen bedeuten 10 · 10 · 10 · 10 = 10 000.",
                misconceptions=[fv("ph_skala_falschrum", 4,
                                   "Die Skala ist logarithmisch. Vier Stufen sind der Faktor 10 000, nicht 4.",
                                   "ph_skala_falschrum")],
                tags=["pruefung", "rechnen", "bbr"], spiral=["W-LOES"]),
        aufgabe("SL07-B4-010", "B", 4, "choice",
                "Warum verbraucht Schwefelsäure bei der Titration doppelt so viel Lauge wie Salzsäure gleicher Konzentration?",
                options=["Sie kann zwei Protonen abgeben.",
                         "Sie ist stärker.", "Sie ist dickflüssiger."],
                answer=0,
                hints=["Sieh dir die Formel an: H₂SO₄.",
                       "Zwei H-Atome.",
                       "Also zwei Protonen."],
                solution="H₂SO₄ gibt zwei Protonen ab. Jedes braucht ein OH⁻ zur Neutralisation — deshalb der doppelte Laugenverbrauch.",
                misconceptions=[fv("index_uebersehen", 1,
                                   "Nicht die Stärke, sondern die Zahl der abgebbaren Protonen entscheidet.",
                                   "summenformel_falsch_gelesen")],
                tags=["pruefung", "msa"], spiral=["W-SYMB"]),
        aufgabe("SL07-C2-011", "C", 2, "choice",
                "Welche Aussage über Wasser ist richtig?",
                options=["Wasser kann sowohl Protonen aufnehmen als auch abgeben — je nach Partner.",
                         "Wasser ist immer eine Säure.",
                         "Wasser nimmt an Säure-Base-Reaktionen nicht teil."],
                answer=0,
                hints=["Gegenüber HCl nimmt Wasser auf.",
                       "Gegenüber Ammoniak gibt es ab.",
                       "Es kommt auf den Partner an."],
                solution="Wasser wirkt gegenüber HCl als Base und gegenüber Ammoniak als Säure. Säure und Base sind Rollen in einer Reaktion, keine festen Eigenschaften.",
                tags=["pruefung", "msa"], spiral=["W-GLEI"]),
        aufgabe("SL07-C3-012", "C", 3, "multi",
                "25 mL Schwefelsäure werden mit 40 mL Natronlauge (0,2 mol/L) neutralisiert.",
                fields=[
                    {"label": "Stoffmenge der Natronlauge in mmol", "answer": 8, "unit_label": "mmol", "tolerance": 0.3},
                    {"label": "Stoffmenge der Schwefelsäure in mmol", "answer": 4, "unit_label": "mmol", "tolerance": 0.2},
                    {"label": "Konzentration der Schwefelsäure", "answer": 0.16, "unit_label": "mol/L", "tolerance": 0.01}
                ],
                hints=["n(NaOH) = 0,2 · 0,040 L.",
                       "H₂SO₄ ist zweiprotonig — halbe Stoffmenge.",
                       "c = 4 mmol : 25 mL."],
                solution="n(NaOH) = 8 mmol\nn(H₂SO₄) = 4 mmol\nc = 4 mmol : 0,025 L = 0,16 mol/L",
                tags=["pruefung", "rechnen", "msa"], spiral=["W-RECH", "W-LOES"]),
        aufgabe("SL07-C3-013", "C", 3, "choice",
                "Warum ist die Aussage „Neutralisation heißt, dass sich alles auflöst“ falsch?",
                options=["Die Ionen bleiben vollständig erhalten; beim Eindampfen bleibt das Salz zurück.",
                         "Sie ist richtig.",
                         "Bei der Neutralisation entsteht ein Gas."],
                answer=0,
                hints=["Was bleibt beim Eindampfen zurück?",
                       "Ein Salz.",
                       "Also war es vorhanden."],
                solution="Neutralisiert wird nur der pH-Wert. Die Ionen bleiben vollständig erhalten und lassen sich als Salz gewinnen — Masse geht nicht verloren.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Beim Eindampfen bleibt das Salz zurück.",
                                   "masse_verschwindet")],
                tags=["pruefung", "bewerten", "msa"], spiral=["W-GLEI"]),
        aufgabe("SL07-C4-014", "C", 4, "choice",
                "Welche Antwort auf „Erkläre, warum Salzsäure Indikatorpapier rot färbt“ ist vollständig?",
                options=["HCl gibt im Wasser ein Proton ab; die entstehenden Oxonium-Ionen bewirken den Farbumschlag.",
                         "Weil Salzsäure eine Säure ist.",
                         "Weil Indikatorpapier bei Säuren rot wird."],
                answer=0,
                hints=["„Erkläre“ verlangt eine Ursache.",
                       "Welche Teilchen bewirken den Umschlag?",
                       "Die Oxonium-Ionen."],
                solution="Antwort 2 und 3 wiederholen die Frage. Nur Antwort 1 nennt die Ursache: die Protolyse und die dabei entstehenden Oxonium-Ionen.",
                tags=["pruefung", "operatoren", "msa"])
    ]
})

# ============================================================
# KW-01 · Organisch oder anorganisch?
# ============================================================
KW.append({
    "unit": "KW-01",
    "title": "Organisch oder anorganisch?",
    "leitidee": "B1",
    "standards": ["K1", "K2.1", "K3.1"],
    "klasse": 9,
    "wortspeicher": ["organisch", "anorganisch", "der Kohlenstoff", "die Verkohlung",
                     "die Vierbindigkeit", "das Kohlenstoffgerüst"],
    "worterklaerungen": {
        "organisch": "Kohlenstoffverbindungen, meist aus lebenden Systemen oder aus Erdöl.",
        "Verkohlung": "Beim Erhitzen bleibt schwarzer Kohlenstoff zurück.",
        "Vierbindigkeit": "Ein Kohlenstoffatom bildet immer vier Bindungen."
    },
    "can_do": {
        "A": "Ich unterscheide organische und anorganische Stoffe an Beispielen.",
        "B": "Ich erkläre die Verkohlungsprobe und nenne die Besonderheiten des Kohlenstoffs.",
        "C": "Ich begründe die Vielfalt organischer Verbindungen mit der Vierbindigkeit."
    },
    "lernkarten": {
        "A": karte("Zwei Gruppen von Stoffen",
                   "Chemiker teilen Stoffe in zwei große Gruppen ein.",
                   ["Organische Stoffe enthalten Kohlenstoff.", "Zucker, Fett und Kunststoff sind organisch."],
                   "Organisch heißt: mit Kohlenstoffgerüst.",
                   visual={"type": "struktur", "kette": 3, "gruppe": "keine",
                           "alt": "Strukturformel von Propan mit drei Kohlenstoffatomen."},
                   beispiel={"titel": "Die Probe", "aufgabe": "Zucker wird erhitzt.",
                             "schritte": ["Er wird braun.", "Dann schwarz.",
                                          "Zurück bleibt Kohlenstoff."],
                             "ergebnis": "Zucker ist organisch."}),
        "B": karte("Woran man organische Stoffe erkennt",
                   "Ein einfacher Versuch trennt die beiden Gruppen zuverlässig — und zeigt zugleich, was organische Stoffe ausmacht.",
                   ["Verkohlungsprobe: Beim Erhitzen unter Luftabschluss bleibt schwarzer Kohlenstoff zurück. Kochsalz oder Sand tun das nicht.",
                    "Organische Stoffe verbrennen meist zu Kohlenstoffdioxid und Wasser — beides lässt sich nachweisen.",
                    "Sie schmelzen und sieden meist bei niedrigen Temperaturen und lösen sich schlecht in Wasser.",
                    "Ausnahmen gibt es: Kohlenstoffdioxid, Carbonate und Kohlensäure enthalten Kohlenstoff, werden aber zur anorganischen Chemie gezählt. Die Einteilung ist historisch gewachsen."],
                   "Verkohlung, Verbrennung zu CO₂ und H₂O, niedrige Schmelzpunkte — das sind die Kennzeichen.",
                   visual={"type": "apparatur", "aufbau": "reagenzglas",
                           "alt": "Ein Reagenzglas mit einer Probe zum Erhitzen."}),
        "C": karte("Warum ausgerechnet Kohlenstoff",
                   "Von rund 20 Millionen bekannten Verbindungen sind über 90 % Kohlenstoffverbindungen. Dafür gibt es drei Gründe, die alle im Bau des Kohlenstoffatoms liegen.",
                   ["Vierbindigkeit: Kohlenstoff hat vier Außenelektronen und bildet genau vier Bindungen — mehr Verknüpfungsmöglichkeiten als jedes andere Element seiner Gruppe.",
                    "Kohlenstoff bindet an sich selbst, und zwar in beliebig langen Ketten, Verzweigungen und Ringen. Silicium kann das nur über wenige Atome.",
                    "Die C–C-Bindung ist stabil genug, um Ketten zu tragen, aber nicht so fest, dass keine Reaktionen mehr möglich wären.",
                    "Hinzu kommen Doppel- und Dreifachbindungen und die Einbindung anderer Elemente — daraus folgt die Isomerie und damit die enorme Vielfalt."],
                   "Vier Bindungen plus Bindung an sich selbst — das ergibt Millionen Verbindungen.",
                   visual={"type": "lewis", "molekuel": "ch4", "formel": "CH4",
                           "alt": "Lewis-Formel von Methan mit vier Bindungen am Kohlenstoff."})
    },
    "formelkarte": {"formeln": ["Kohlenstoff bildet immer 4 Bindungen"],
                    "saetze": ["Organisch = Kohlenstoffverbindung (mit historischen Ausnahmen).",
                               "Verkohlungsprobe: schwarzer Rückstand beim Erhitzen.",
                               "Organische Stoffe verbrennen zu CO₂ und H₂O.",
                               "Ausnahmen: CO₂, Carbonate und Kohlensäure gelten als anorganisch."]},
    "tasks": [
        aufgabe("KW01-A1-001", "A", 1, "choice",
                "Welcher Stoff ist organisch?",
                options=["Zucker", "Kochsalz", "Sand"], answer=0,
                hints=["Organische Stoffe enthalten Kohlenstoff.",
                       "Kochsalz und Sand nicht.",
                       "Zucker."],
                solution="Zucker enthält Kohlenstoff und ist organisch. Kochsalz und Sand sind anorganisch.",
                tags=["organik"], spiral=["W-ORG"]),
        aufgabe("KW01-A2-002", "A", 2, "choice",
                "Was passiert, wenn Zucker stark erhitzt wird?",
                options=["Er wird braun und dann schwarz.", "Er verdampft rückstandslos.", "Nichts."],
                answer=0,
                hints=["Was bleibt in der Pfanne zurück?",
                       "Ein schwarzer Rest.",
                       "Das ist Kohlenstoff."],
                solution="Zucker verkohlt: Zurück bleibt schwarzer Kohlenstoff. Das ist der Nachweis für einen organischen Stoff.",
                tags=["organik"], spiral=["W-ORG"]),
        aufgabe("KW01-A3-003", "A", 3, "numeric",
                "Wie viele Bindungen bildet ein Kohlenstoffatom?",
                answer=4, tolerance=0,
                visual={"type": "lewis", "molekuel": "ch4", "alt": "Lewis-Formel von Methan."},
                hints=["Kohlenstoff hat vier Außenelektronen.", "8 − 4 = 4.", "Vier."],
                solution="Kohlenstoff bildet immer genau vier Bindungen.",
                misconceptions=[fv("formel_ohne_plus_zwei", 2,
                                   "Kohlenstoff hat vier Außenelektronen und bildet vier Bindungen.",
                                   "summenformel_falsch_gelesen")],
                tags=["organik"], spiral=["W-SYMB"]),
        aufgabe("KW01-A4-004", "A", 4, "choice",
                "Was entsteht bei der vollständigen Verbrennung eines organischen Stoffes?",
                options=["Kohlenstoffdioxid und Wasser", "nur Wasser", "nur Ruß"], answer=0,
                hints=["Der Stoff enthält C und H.",
                       "Beide verbinden sich mit Sauerstoff.",
                       "CO₂ und H₂O."],
                solution="Bei vollständiger Verbrennung entstehen Kohlenstoffdioxid aus dem Kohlenstoff und Wasser aus dem Wasserstoff.",
                tags=["organik"], spiral=["W-GLEI"]),
        aufgabe("KW01-B1-005", "B", 1, "choice",
                "Wie weist du nach, dass bei einer Verbrennung Kohlenstoffdioxid entstanden ist?",
                options=["Mit Kalkwasser — es wird trüb.",
                         "Mit einem Glimmspan.", "Mit der Knallgasprobe."],
                answer=0,
                hints=["Welcher Nachweis gehört zu CO₂?",
                       "Die Kalkwasserprobe.",
                       "Es wird milchig trüb."],
                solution="Kohlenstoffdioxid trübt Kalkwasser. Der Glimmspan weist Sauerstoff nach, die Knallgasprobe Wasserstoff.",
                misconceptions=[fv("nachweis_verwechselt", 1,
                                   "Der Glimmspan weist Sauerstoff nach.",
                                   "nachweis_verwechselt")],
                tags=["organik", "nachweise", "bbr"], spiral=["W-GLEI"]),
        aufgabe("KW01-B2-006", "B", 2, "choice",
                "Warum bildet Kohlenstoff so viele verschiedene Verbindungen?",
                options=["Er bildet vier Bindungen und kann sich in langen Ketten mit sich selbst verbinden.",
                         "Er ist das häufigste Element.",
                         "Er ist besonders leicht."],
                answer=0,
                hints=["Wie viele Bindungen bildet er?",
                       "Vier.",
                       "Und er bindet an sich selbst."],
                solution="Vier Bindungen und die Fähigkeit, beliebig lange Ketten, Verzweigungen und Ringe mit sich selbst zu bilden — das ergibt die Vielfalt. Kohlenstoff ist nicht das häufigste Element.",
                tags=["organik", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW01-B2-007", "B", 2, "choice",
                "Kohlenstoffdioxid enthält Kohlenstoff. Warum wird es trotzdem der anorganischen Chemie zugerechnet?",
                options=["Die Einteilung ist historisch gewachsen; einige einfache C-Verbindungen zählen zur anorganischen Chemie.",
                         "CO₂ enthält gar keinen Kohlenstoff.",
                         "CO₂ ist ein Gas."],
                answer=0,
                hints=["Ist die Einteilung streng logisch?",
                       "Nein, sie hat historische Gründe.",
                       "CO₂, Carbonate und Kohlensäure sind Ausnahmen."],
                solution="Die Trennung stammt aus der Zeit, als man organische Stoffe nur aus Lebewesen kannte. Einige einfache Kohlenstoffverbindungen — CO₂, Carbonate, Kohlensäure — blieben bei der anorganischen Chemie. Eine sachliche Notwendigkeit ist das nicht.",
                tags=["organik", "msa"], spiral=["W-ORG"]),
        aufgabe("KW01-B3-008", "B", 3, "assign",
                "Ordne jeden Stoff richtig ein.",
                slots=["Speiseöl", "Kochsalz", "Kunststoff"],
                values=["organisch", "anorganisch", "organisch (zweites)"],
                answer=[0, 1, 2],
                hints=["Was verkohlt beim Erhitzen?",
                       "Öl und Kunststoff.",
                       "Kochsalz nicht."],
                solution="Speiseöl und Kunststoff sind organisch — sie verkohlen. Kochsalz ist anorganisch.",
                tags=["organik", "bbr"], spiral=["W-ORG"]),
        aufgabe("KW01-B3-009", "B", 3, "choice",
                "Warum schmelzen organische Stoffe meist bei niedrigeren Temperaturen als Salze?",
                options=["Zwischen Molekülen wirken schwächere Kräfte als zwischen Ionen im Gitter.",
                         "Organische Stoffe sind leichter.",
                         "Organische Stoffe enthalten Wasser."],
                answer=0,
                hints=["Was muss beim Schmelzen überwunden werden?",
                       "Die Anziehung zwischen den Teilchen.",
                       "Zwischen Molekülen ist sie schwächer."],
                solution="Organische Stoffe bestehen aus Molekülen; zwischen ihnen wirken schwache zwischenmolekulare Kräfte. Im Salz muss dagegen ein Gitter aus stark angezogenen Ionen aufgebrochen werden.",
                tags=["organik", "msa"], spiral=["W-STOF"]),
        aufgabe("KW01-B4-010", "B", 4, "choice",
                "Warum kann Silicium trotz Vierbindigkeit keine so langen Ketten bilden wie Kohlenstoff?",
                options=["Die Si–Si-Bindung ist deutlich schwächer und zerfällt leicht.",
                         "Silicium hat nur drei Außenelektronen.",
                         "Silicium ist ein Metall."],
                answer=0,
                hints=["Silicium steht unter Kohlenstoff und hat auch vier Außenelektronen.",
                       "Der Unterschied liegt in der Bindungsstärke.",
                       "Si–Si ist schwächer als C–C."],
                solution="Silicium hat ebenfalls vier Außenelektronen, aber die Si–Si-Bindung ist deutlich schwächer als die C–C-Bindung. Lange Ketten zerfallen deshalb. Das ist einer der Gründe, warum das Leben auf Kohlenstoff beruht.",
                tags=["organik", "msa"], spiral=["W-TEIL"]),
        aufgabe("KW01-C2-011", "C", 2, "choice",
                "Wie lässt sich zeigen, dass bei der Verbrennung einer Kerze sowohl Kohlenstoff als auch Wasserstoff enthalten waren?",
                options=["Kalkwasser weist CO₂ nach, beschlagenes Glas oder Watesmopapier das Wasser.",
                         "Nur die Flamme beobachten.",
                         "Die Kerze wiegen."],
                answer=0,
                hints=["Zwei Produkte, zwei Nachweise.",
                       "CO₂ mit Kalkwasser.",
                       "Wasser durch Kondensation."],
                solution="Beide Produkte werden einzeln nachgewiesen: das Kohlenstoffdioxid mit Kalkwasser, das Wasser als Beschlag an einem kalten Glas. Daraus folgt, dass die Kerze C und H enthielt.",
                tags=["organik", "nachweise", "msa"], spiral=["W-GLEI"]),
        aufgabe("KW01-C3-012", "C", 3, "choice",
                "Wodurch wurde die alte Vorstellung widerlegt, organische Stoffe könnten nur von Lebewesen gebildet werden?",
                options=["Wöhler stellte 1828 Harnstoff aus anorganischen Ausgangsstoffen her.",
                         "Durch die Entdeckung des Kohlenstoffs.",
                         "Durch die Erfindung des Mikroskops."],
                answer=0,
                hints=["Es war ein einzelnes Experiment.",
                       "Ein organischer Stoff wurde im Labor hergestellt.",
                       "Es war Harnstoff."],
                solution="Friedrich Wöhler stellte 1828 Harnstoff — einen typisch organischen Stoff — aus anorganischen Ausgangsstoffen her. Damit war die Annahme einer besonderen „Lebenskraft“ widerlegt. Die Begriffe blieben, ihre ursprüngliche Begründung nicht.",
                tags=["organik", "msa"]),
        aufgabe("KW01-C3-013", "C", 3, "choice",
                "Warum ist die Verkohlungsprobe ein brauchbarer, aber kein vollständiger Nachweis?",
                options=["Sie zeigt Kohlenstoff an, unterscheidet aber nicht zwischen verschiedenen organischen Stoffen.",
                         "Sie funktioniert nur bei Zucker.",
                         "Sie ist zu gefährlich."],
                answer=0,
                hints=["Was genau zeigt die Probe?",
                       "Dass Kohlenstoff enthalten ist.",
                       "Mehr nicht."],
                solution="Die Probe belegt, dass der Stoff Kohlenstoff enthält — mehr nicht. Zucker, Fett und Kunststoff verkohlen alle. Für eine Identifizierung braucht es weitere Untersuchungen.",
                tags=["organik", "bewerten", "msa"]),
        aufgabe("KW01-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Organische Stoffe sind natürlich, anorganische künstlich.“ Wie bewertest du das?",
                options=["Falsch — Kunststoffe sind organisch und künstlich, Quarz ist anorganisch und natürlich.",
                         "Richtig.",
                         "Falsch — es ist genau umgekehrt."],
                answer=0,
                hints=["Denk an Kunststoffe.",
                       "Sie sind organisch und künstlich.",
                       "Und Sand ist anorganisch und natürlich."],
                solution="Die Einteilung sagt nichts über die Herkunft. Kunststoffe sind organisch und synthetisch, Quarz ist anorganisch und natürlich. Entscheidend ist allein das Kohlenstoffgerüst.",
                tags=["organik", "bewerten", "msa"])
    ]
})

if __name__ == "__main__":
    schreiben("sl", SL, "Bereich SL · Einheit 7")
    schreiben("kw", KW, "Bereich KW · Einheit 1")
