# -*- coding: utf-8 -*-
"""Bereich PS · Das Periodensystem — PS-03 bis PS-05."""
from einheiten_basis import karte, fv, aufgabe, anim, schreiben

E = []

E.append({
    "unit": "PS-03",
    "title": "Von Demokrit zu Dalton",
    "leitidee": "B1",
    "standards": ["K1", "K2.3", "K3.1"],
    "klasse": 7,
    "wortspeicher": ["das Atom", "unteilbar", "das Atommodell", "die Verbindung",
                     "das Massenverhältnis", "die Hypothese"],
    "worterklaerungen": {
        "Atom": "Das kleinste Teilchen eines Elements.",
        "unteilbar": "Man kann es nicht weiter zerlegen. Das dachte man früher vom Atom.",
        "Hypothese": "Eine begründete Vermutung. Sie muss noch geprüft werden."
    },
    "can_do": {
        "A": "Ich nenne die Grundidee von Demokrit und Dalton.",
        "B": "Ich erkläre die Aussagen des Daltonschen Modells und wende sie auf Reaktionen an.",
        "C": "Ich benenne die Grenzen des Daltonschen Modells und begründe, warum es dennoch trägt."
    },
    "lernkarten": {
        "A": karte("Die Idee vom kleinsten Teilchen",
                   "Demokrit dachte vor 2400 Jahren: Alles besteht aus kleinsten Teilchen.",
                   ["Er nannte sie Atome — das heißt „unteilbar“.", "Beweisen konnte er es nicht."],
                   "Atom heißt „unteilbar“.",
                   beispiel={"titel": "Dalton 1808", "aufgabe": "Dalton machte aus der Idee eine Theorie.",
                             "schritte": ["Jedes Element hat eigene Atome.",
                                          "Atome eines Elements sind gleich schwer.",
                                          "Bei Reaktionen werden Atome nur neu geordnet."],
                             "ergebnis": "Damit ließen sich Massenverhältnisse erklären."}),
        "B": karte("Was Dalton behauptete",
                   "Dalton machte aus einer philosophischen Idee eine prüfbare Theorie — und das ist der entscheidende Schritt.",
                   ["Alle Stoffe bestehen aus Atomen. Atome sind unteilbar und unzerstörbar.",
                    "Atome eines Elements sind untereinander gleich, Atome verschiedener Elemente verschieden schwer.",
                    "Bei einer chemischen Reaktion werden Atome umgeordnet, nicht erzeugt oder vernichtet — daraus folgt die Erhaltung der Masse.",
                    "Verbindungen entstehen in festen Zahlenverhältnissen. Deshalb sind auch die Massenverhältnisse fest."],
                   "Atome werden umgeordnet, nicht verbraucht. Das erklärt konstante Massenverhältnisse.",
                   visual={"type": "teilchen", "zustand": "fest", "art": "verbindung",
                           "alt": "Teilchenmodell einer Verbindung aus zwei Atomsorten."}),
        "C": karte("Wo Dalton endet",
                   "Daltons Modell erklärt die Stöchiometrie vollständig — und schweigt zu allem, was in einem Atom vorgeht. Beides gehört zusammen.",
                   ["Unteilbar stimmt nicht: Atome bestehen aus Protonen, Neutronen und Elektronen.",
                    "Gleich schwer stimmt nicht: Isotope desselben Elements haben verschiedene Massen.",
                    "Zur elektrischen Ladung, zu Ionen und zur Bindung sagt das Modell nichts.",
                    "Für Massenberechnungen in Reaktionsgleichungen genügt es bis heute — dort ist es nach wie vor das benutzte Modell."],
                   "Ein überholtes Modell bleibt brauchbar, solange man seine Grenze kennt.",
                   visual={"type": "atom", "z": 6, "symbol": "C", "neutronen": 6,
                           "alt": "Schalenmodell eines Kohlenstoffatoms."})
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Atom heißt „unteilbar“ — das war Demokrits Idee.",
                               "Dalton: Atome werden bei Reaktionen umgeordnet, nicht verbraucht.",
                               "Daraus folgt die Erhaltung der Masse.",
                               "Grenzen: Atome sind teilbar, Isotope sind verschieden schwer."]},
    "tasks": [
        aufgabe("PS03-A1-001", "A", 1, "choice",
                "Was bedeutet das Wort „Atom“?",
                options=["unteilbar", "sehr klein", "unsichtbar"], answer=0,
                hints=["Das Wort kommt aus dem Griechischen.", "Es beschreibt, was man nicht kann.", "Man kann es nicht teilen."],
                solution="„Atom“ kommt aus dem Griechischen und heißt „unteilbar“.",
                tags=["modelle", "geschichte"], spiral=["K-ATOM"]),
        aufgabe("PS03-A2-002", "A", 2, "choice",
                "Was sagte Dalton über die Atome eines Elements?",
                options=["Sie sind alle gleich.", "Sie sind alle verschieden.", "Es gibt nur eines davon."],
                answer=0,
                hints=["Dalton unterschied Elemente an ihren Atomen.",
                       "Innerhalb eines Elements sah er keine Unterschiede.",
                       "Sie sind alle gleich."],
                solution="Dalton nahm an, alle Atome eines Elements seien gleich — insbesondere gleich schwer. Heute wissen wir: Isotope widerlegen das.",
                tags=["modelle"], spiral=["K-ATOM"]),
        aufgabe("PS03-A3-003", "A", 3, "choice",
                "Was passiert nach Dalton mit den Atomen bei einer chemischen Reaktion?",
                options=["Sie werden neu zusammengesetzt.", "Sie werden zerstört.", "Es entstehen neue Atome."],
                answer=0,
                hints=["Geht bei einer Reaktion Masse verloren?", "Nein.", "Also bleiben die Atome erhalten."],
                solution="Die Atome werden nur neu angeordnet. Keines geht verloren, keines kommt hinzu — daraus folgt die Erhaltung der Masse.",
                misconceptions=[fv("masse_verschwindet", 1,
                                   "Würden Atome zerstört, ginge Masse verloren. Das widerspricht jeder Messung.",
                                   "masse_verschwindet")],
                tags=["modelle"], spiral=["K-REAK"]),
        aufgabe("PS03-A4-004", "A", 4, "choice",
                "Warum konnte Demokrit seine Idee nicht beweisen?",
                options=["Es gab keine Versuche und keine Messgeräte dafür.", "Er hat sich nicht getraut.", "Seine Idee war falsch."],
                answer=0,
                hints=["Wie prüft man eine Idee in der Naturwissenschaft?",
                       "Mit Versuchen.",
                       "Die gab es damals nicht."],
                solution="Demokrits Idee war eine philosophische Überlegung. Erst 2200 Jahre später gab es Messungen, mit denen sie prüfbar wurde.",
                tags=["modelle", "geschichte"]),
        aufgabe("PS03-B1-005", "B", 1, "choice",
                "Welche Aussage gehört zu Daltons Atommodell?",
                options=["Atome verschiedener Elemente sind verschieden schwer.",
                         "Atome bestehen aus Kern und Hülle.",
                         "Atome können Elektronen abgeben."],
                answer=0,
                hints=["Dalton wusste nichts vom Atomaufbau.",
                       "Kern und Hülle kamen erst 100 Jahre später.",
                       "Dalton sprach über Massen."],
                solution="Dalton unterschied Elemente über die Masse ihrer Atome. Von Kern, Hülle und Elektronen wusste er nichts — das kam erst um 1910.",
                misconceptions=[fv("modelle_vermischt", 1,
                                   "Kern und Hülle stammen von Rutherford, rund hundert Jahre nach Dalton.")],
                tags=["modelle", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS03-B2-006", "B", 2, "choice",
                "Kupfer und Sauerstoff verbinden sich immer im Massenverhältnis 4 : 1. Wie erklärt Dalton das?",
                options=["Die Atome verbinden sich in einem festen Zahlenverhältnis.",
                         "Zufällig ist immer gleich viel Sauerstoff da.",
                         "Das Verhältnis hängt von der Temperatur ab."],
                answer=0,
                hints=["Warum ist das Verhältnis immer gleich?",
                       "Weil sich immer gleich viele Atome verbinden.",
                       "Feste Atomzahl → feste Masse."],
                solution="Verbinden sich immer gleich viele Atome miteinander und haben Atome fester Sorten feste Massen, dann ist auch das Massenverhältnis fest. Genau das erklärt Daltons Modell.",
                tags=["modelle", "bbr"], spiral=["K-REAK"]),
        aufgabe("PS03-B2-007", "B", 2, "numeric",
                "Kupfer und Sauerstoff reagieren im Massenverhältnis 4 : 1. Wie viel Gramm Sauerstoff werden für 20 g Kupfer gebraucht?",
                answer=5, unit_label="g", tolerance=0.01,
                hints=["Auf 4 Teile Kupfer kommt 1 Teil Sauerstoff.",
                       "20 : 4.",
                       "5 g."],
                solution="20 g : 4 = 5 g Sauerstoff.",
                misconceptions=[fv("verhaeltnis_umgedreht", 80,
                                   "Verhältnis umgedreht: Vom Sauerstoff wird <b>weniger</b> gebraucht als vom Kupfer.")],
                tags=["modelle", "rechnen", "bbr"], spiral=["K-REAK"]),
        aufgabe("PS03-B3-008", "B", 3, "choice",
                "Welche Beobachtung widerlegt Daltons Annahme, Atome seien unteilbar?",
                options=["Atome bestehen aus Protonen, Neutronen und Elektronen.",
                         "Atome sind sehr klein.", "Atome bewegen sich."],
                answer=0,
                hints=["Was fand man später im Atom?",
                       "Kleinere Teilchen.",
                       "Damit ist es teilbar."],
                solution="Die Entdeckung von Elektron, Proton und Neutron zeigte, dass Atome aus kleineren Teilchen bestehen. Daltons Annahme der Unteilbarkeit war damit widerlegt.",
                tags=["modelle", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS03-B3-009", "B", 3, "numeric",
                "Aus 8 g Kupfer und 2 g Sauerstoff entsteht Kupferoxid. Wie viel Gramm Kupferoxid sind das?",
                answer=10, unit_label="g", tolerance=0,
                hints=["Nach Dalton geht kein Atom verloren.", "8 + 2.", "10 g."],
                solution="8 g + 2 g = 10 g. Weil Atome nur umgeordnet werden, bleibt die Masse erhalten.",
                misconceptions=[fv("masse_verschwindet", 6,
                                   "Du hast subtrahiert. Beide Edukte gehen vollständig ins Produkt ein.",
                                   "masse_verschwindet")],
                tags=["modelle", "rechnen"], spiral=["K-REAK"]),
        aufgabe("PS03-B4-010", "B", 4, "choice",
                "Warum wird Daltons Modell im Unterricht noch benutzt, obwohl es überholt ist?",
                options=["Für Massenberechnungen bei Reaktionen reicht es vollkommen aus.",
                         "Weil neuere Modelle zu teuer sind.",
                         "Aus Tradition."],
                answer=0,
                hints=["Wofür genau braucht man es?",
                       "Für Massen und Verhältnisse.",
                       "Dafür ist es ausreichend."],
                solution="Wer Massen in einer Reaktionsgleichung berechnet, braucht nur „Atome bleiben erhalten und haben feste Massen“. Genau das leistet Daltons Modell — für diese Frage ist es weiterhin das passende.",
                tags=["modelle", "bewerten", "msa"]),
        aufgabe("PS03-C2-011", "C", 2, "choice",
                "Welche Aussage Daltons wird durch Isotope widerlegt?",
                options=["Alle Atome eines Elements sind gleich schwer.",
                         "Atome werden bei Reaktionen umgeordnet.",
                         "Verbindungen haben feste Zahlenverhältnisse."],
                answer=0,
                hints=["Worin unterscheiden sich Isotope?",
                       "In der Neutronenzahl und damit in der Masse.",
                       "Also in der Masse."],
                solution="Isotope desselben Elements haben gleich viele Protonen, aber verschieden viele Neutronen — und damit verschiedene Massen. Daltons Annahme gleicher Masse ist damit widerlegt; die anderen beiden Aussagen gelten weiter.",
                tags=["modelle", "msa"], spiral=["K-ATOM"]),
        aufgabe("PS03-C3-012", "C", 3, "choice",
                "Kupfer bildet zwei Oxide: eines mit 4 : 1, eines mit 8 : 1 Massenverhältnis. Was folgt daraus für die Atomzahlen?",
                options=["Im zweiten Oxid kommen doppelt so viele Kupferatome auf ein Sauerstoffatom.",
                         "Die Sauerstoffatome sind im zweiten Oxid doppelt so schwer.",
                         "Eines der beiden Verhältnisse muss falsch gemessen sein."],
                answer=0,
                hints=["Die Atommassen ändern sich nicht.",
                       "Also muss sich die Anzahl ändern.",
                       "Doppelte Kupfermasse je Sauerstoff = doppelt so viele Kupferatome."],
                solution="Atommassen sind fest. Verdoppelt sich die Kupfermasse je Sauerstoffanteil, müssen doppelt so viele Kupferatome beteiligt sein: CuO und Cu₂O. Solche einfachen Zahlenverhältnisse waren Daltons stärkstes Argument.",
                misconceptions=[fv("teilchen_traegt_stoffeigenschaft", 1,
                                   "Die Masse eines Sauerstoffatoms ist immer gleich. Ändern kann sich nur die Anzahl.",
                                   "teilchen_traegt_stoffeigenschaft")],
                tags=["modelle", "msa"], spiral=["K-REAK"]),
        aufgabe("PS03-C3-013", "C", 3, "multi",
                "Ein Oxid enthält Kupfer und Sauerstoff im Massenverhältnis 4 : 1.",
                fields=[
                    {"label": "Kupfermasse in 25 g Oxid", "answer": 20, "unit_label": "g", "tolerance": 0.01},
                    {"label": "Sauerstoffmasse in 25 g Oxid", "answer": 5, "unit_label": "g", "tolerance": 0.01},
                    {"label": "Massenanteil des Sauerstoffs in Prozent", "answer": 20, "unit_label": "%", "tolerance": 0.1}
                ],
                hints=["Das Oxid besteht aus 4 + 1 = 5 Teilen.",
                       "1 Teil = 25 g : 5 = 5 g.",
                       "Kupfer sind 4 Teile."],
                solution="1 Teil = 25 g : 5 = 5 g\nKupfer = 4 · 5 g = 20 g, Sauerstoff = 5 g\nAnteil O = 5 : 25 = 20 %",
                tags=["modelle", "rechnen", "msa"], spiral=["K-REAK"]),
        aufgabe("PS03-C4-014", "C", 4, "choice",
                "Ein Schüler sagt: „Daltons Modell ist widerlegt, also darf man damit nicht mehr rechnen.“ Wie bewertest du das?",
                options=["Falsch — widerlegt ist nur die Unteilbarkeit; die Massenerhaltung gilt unverändert.",
                         "Richtig — ein widerlegtes Modell darf nicht verwendet werden.",
                         "Falsch — das Modell ist gar nicht widerlegt."],
                answer=0,
                hints=["Welche Aussagen des Modells sind widerlegt?",
                       "Unteilbarkeit und gleiche Masse.",
                       "Die Massenerhaltung nicht."],
                solution="Widerlegt sind zwei Einzelaussagen: Unteilbarkeit und gleiche Masse aller Atome eines Elements. Die Umordnung der Atome und damit die Massenerhaltung gelten unverändert — und genau darauf beruht jede stöchiometrische Rechnung.",
                tags=["modelle", "bewerten", "msa"])
    ]
})

E.append({
    "unit": "PS-04",
    "title": "Kern-Hülle-Modell und Streuversuch",
    "leitidee": "B1",
    "standards": ["K1", "K2.3", "K3.3"],
    "klasse": 7,
    "wortspeicher": ["der Atomkern", "die Atomhülle", "der Streuversuch", "die Goldfolie",
                     "positiv geladen", "die Kernladung"],
    "worterklaerungen": {
        "Atomkern": "Der winzige, schwere Bereich in der Mitte des Atoms. Er ist positiv geladen.",
        "Atomhülle": "Der Bereich um den Kern. Dort sind die Elektronen.",
        "Streuversuch": "Ein Versuch, bei dem kleine Teilchen auf eine dünne Folie geschossen werden."
    },
    "can_do": {
        "A": "Ich benenne Kern und Hülle des Atoms und weiß, dass das Atom fast leer ist.",
        "B": "Ich beschreibe den Streuversuch und die Beobachtungen.",
        "C": "Ich leite aus den Beobachtungen des Streuversuchs die Aussagen des Kern-Hülle-Modells ab."
    },
    "lernkarten": {
        "A": karte("Kern und Hülle",
                   "Ein Atom hat zwei Bereiche.",
                   ["In der Mitte ist der Kern. Er ist sehr klein und sehr schwer.",
                    "Um ihn herum ist die Hülle mit den Elektronen."],
                   "Kleiner Kern, große Hülle. Dazwischen ist fast nichts.",
                   visual=anim("streuversuch", "A"),
                   beispiel={"titel": "Wie leer ein Atom ist",
                             "aufgabe": "Wäre das Atom so groß wie ein Fußballstadion …",
                             "schritte": ["… läge der Kern als Erbse im Anstoßkreis.",
                                          "Der Rest wäre leer."],
                             "ergebnis": "Fast das ganze Atom ist leerer Raum."}),
        "B": karte("Der Versuch von Rutherford",
                   "1911 schoss Rutherford kleine, positiv geladene Teilchen auf eine hauchdünne Goldfolie und zählte, wo sie ankamen. Die Beobachtungen waren so unerwartet, dass sie das damalige Atommodell umwarfen.",
                   ["Fast alle Teilchen flogen geradeaus hindurch, als wäre die Folie gar nicht da.",
                    "Wenige wurden abgelenkt.",
                    "Ganz wenige — etwa eines von 8000 — kamen zurück.",
                    "Rutherford verglich das mit einer Granate, die an einem Blatt Papier abprallt."],
                   "Drei Beobachtungen, drei Schlüsse — das ist der Kern des Versuchs.",
                   visual=anim("streuversuch", "B")),
        "C": karte("Vom Befund zum Modell",
                   "Der Streuversuch ist das Musterbeispiel dafür, wie aus Beobachtungen ein Modell wird. Jede der drei Beobachtungen erzwingt eine Aussage.",
                   ["„Fast alle fliegen durch“ → Das Atom besteht fast vollständig aus leerem Raum.",
                    "„Wenige werden abgelenkt“ → Es gibt etwas Geladenes, das die positiven Teilchen abstößt.",
                    "„Ganz wenige kommen zurück“ → Dieses Etwas ist sehr klein und sehr massereich: der Kern.",
                    "Was das Modell nicht sagt: wie die Elektronen in der Hülle angeordnet sind. Dafür brauchte es Bohrs Erweiterung."],
                   "Ein Modell wird nicht erfunden, sondern aus Beobachtungen erzwungen.",
                   visual=anim("streuversuch", "C"))
    },
    "formelkarte": {"formeln": [],
                    "saetze": ["Atomkern: winzig, schwer, positiv geladen.",
                               "Atomhülle: groß, fast masselos, enthält die Elektronen.",
                               "Der Kern ist rund 10 000-mal kleiner als das Atom.",
                               "Fast das gesamte Atomvolumen ist leerer Raum."]},
    "tasks": [
        aufgabe("PS04-A1-001", "A", 1, "choice",
                "Wo sitzt die Masse eines Atoms fast vollständig?",
                options=["im Kern", "in der Hülle", "gleichmäßig verteilt"], answer=0,
                visual=anim("streuversuch", "A"),
                hints=["Der Kern ist klein, aber schwer.", "Die Elektronen sind fast masselos.", "Also im Kern."],
                solution="Fast die gesamte Masse steckt im winzigen Kern. Die Elektronen der Hülle sind fast masselos.",
                misconceptions=[fv("masse_in_huelle", 1,
                                   "Elektronen sind rund 2000-mal leichter als Protonen. Die Masse steckt im Kern.")],
                tags=["atombau"], spiral=["K-ATOM"]),
        aufgabe("PS04-A2-002", "A", 2, "choice",
                "Wie ist der Atomkern geladen?",
                options=["positiv", "negativ", "gar nicht"], answer=0,
                hints=["Im Kern sitzen Protonen.", "Protonen sind positiv.", "Also ist der Kern positiv."],
                solution="Im Kern sitzen die positiv geladenen Protonen. Der Kern ist deshalb positiv geladen.",
                tags=["atombau"], spiral=["K-ATOM"]),
        aufgabe("PS04-A3-003", "A", 3, "choice",
                "Was beobachtete Rutherford bei den meisten Teilchen?",
                options=["Sie flogen geradeaus durch die Folie.", "Sie prallten zurück.", "Sie blieben stecken."],
                answer=0, visual=anim("streuversuch", "A"),
                hints=["Sieh dir die Animation an.", "Die meisten Bahnen sind gerade.", "Sie fliegen durch."],
                solution="Fast alle Teilchen flogen geradeaus hindurch. Nur ganz wenige wurden abgelenkt oder kamen zurück.",
                tags=["atombau", "streuversuch"]),
        aufgabe("PS04-A4-004", "A", 4, "choice",
                "Was folgt daraus, dass fast alle Teilchen geradeaus durchfliegen?",
                options=["Das Atom ist fast leer.", "Gold ist sehr weich.", "Die Teilchen sind sehr schnell."],
                answer=0,
                hints=["Was müsste passieren, wenn das Atom voll wäre?",
                       "Dann würden viele abgelenkt.",
                       "Also ist es fast leer."],
                solution="Wäre das Atom mit Materie gefüllt, würden viele Teilchen abgelenkt. Dass fast alle durchfliegen, zeigt: Das Atom besteht fast nur aus leerem Raum.",
                tags=["atombau", "streuversuch"]),
        aufgabe("PS04-B1-005", "B", 1, "assign",
                "Ordne jeder Beobachtung im Streuversuch den passenden Schluss zu.",
                slots=["fast alle fliegen durch", "wenige werden abgelenkt", "ganz wenige kommen zurück"],
                values=["Das Atom ist fast leer.", "Es gibt geladene Bereiche.", "Der Kern ist klein und sehr schwer."],
                answer=[0, 1, 2],
                visual=anim("streuversuch", "B"),
                hints=["Jede Beobachtung erzwingt eine Aussage.",
                       "Durchfliegen heißt: nichts im Weg.",
                       "Zurückprallen heißt: etwas sehr Schweres im Weg."],
                solution="Durchfliegen → leerer Raum.\nAblenkung → Ladung.\nZurückprallen → kleiner, schwerer Kern.",
                tags=["atombau", "streuversuch", "bbr"]),
        aufgabe("PS04-B2-006", "B", 2, "choice",
                "Warum wurden einige Teilchen abgelenkt, ohne zurückzukommen?",
                options=["Sie flogen nahe am positiven Kern vorbei und wurden abgestoßen.",
                         "Sie trafen ein Elektron.", "Sie wurden von der Folie gebremst."],
                answer=0,
                hints=["Die Teilchen sind selbst positiv geladen.",
                       "Gleiche Ladungen stoßen sich ab.",
                       "Je näher am Kern, desto stärker die Ablenkung."],
                solution="Die Teilchen sind positiv geladen wie der Kern. Fliegen sie nah vorbei, stoßen sich beide ab und die Bahn krümmt sich. Nur bei einem fast direkten Treffer kommt das Teilchen zurück.",
                misconceptions=[fv("elektron_als_ursache", 1,
                                   "Elektronen sind viel zu leicht, um ein schweres Teilchen abzulenken.")],
                tags=["atombau", "bbr"], spiral=["K-ATOM"]),
        aufgabe("PS04-B2-007", "B", 2, "numeric",
                "Von 8000 Teilchen kommt etwa eines zurück. Wie viele wären das bei 40 000 Teilchen?",
                answer=5, tolerance=0,
                hints=["40 000 : 8 000.", "Das sind 5.", "5 Teilchen."],
                solution="40 000 : 8 000 = 5 Teilchen. Die Zahl zeigt, wie winzig der Kern im Vergleich zum Atom ist.",
                tags=["atombau", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("PS04-B3-008", "B", 3, "choice",
                "Warum musste eine sehr dünne Goldfolie verwendet werden?",
                options=["Bei dickerer Folie würden die Teilchen mehrfach abgelenkt und der Befund wäre nicht mehr auswertbar.",
                         "Dickere Folie wäre zu teuer gewesen.",
                         "Dickere Folie hätte die Teilchen erwärmt."],
                answer=0,
                hints=["Was passiert bei vielen Atomlagen hintereinander?",
                       "Mehrfachablenkung.",
                       "Dann lässt sich kein Einzelvorgang mehr erkennen."],
                solution="Nur bei wenigen Atomlagen entspricht eine Ablenkung einem einzelnen Vorgang. Bei dicker Folie überlagern sich viele Ablenkungen und der Schluss auf den Kern wäre nicht möglich.",
                tags=["atombau", "planen", "msa"]),
        aufgabe("PS04-B3-009", "B", 3, "choice",
                "Welches Atommodell wurde durch den Streuversuch abgelöst?",
                options=["Das Modell einer gleichmäßig verteilten Masse mit eingelagerten Elektronen.",
                         "Das Schalenmodell von Bohr.", "Das Orbitalmodell."],
                answer=0,
                hints=["Welches Modell galt vor 1911?",
                       "Man dachte an eine gleichmäßig gefüllte Kugel.",
                       "Der Versuch zeigte: Das Atom ist fast leer."],
                solution="Vor dem Streuversuch stellte man sich das Atom als gleichmäßig gefüllte Kugel vor. Diese Vorstellung ist mit den Beobachtungen nicht vereinbar. Bohrs Schalenmodell kam erst danach.",
                tags=["atombau", "modelle", "bbr"]),
        aufgabe("PS04-B4-010", "B", 4, "numeric",
                "Ein Atom hat einen Durchmesser von 0,1 nm, der Kern 0,00001 nm. Um welchen Faktor ist das Atom größer?",
                answer=10000, tolerance=1,
                hints=["0,1 : 0,00001.",
                       "Verschiebe das Komma.",
                       "10 000."],
                solution="0,1 nm : 0,00001 nm = 10 000. Das Atom ist zehntausendmal größer als sein Kern.",
                misconceptions=[fv("faktor_falsch", 1000,
                                   "Zähle die Stellen genau: 0,1 : 0,00001 = 10 000.",
                                   "groesse_und_einheit_verwechselt")],
                tags=["atombau", "rechnen", "bbr"], spiral=["K-QUANT"]),
        aufgabe("PS04-C2-011", "C", 2, "choice",
                "Warum ist der Vergleich „Granate prallt an Papier ab“ so treffend?",
                options=["Er zeigt, wie unerwartet der Befund war — etwas sehr Leichtes wirft etwas sehr Schweres zurück.",
                         "Er beschreibt die Geschwindigkeit der Teilchen.",
                         "Er beschreibt die Dicke der Goldfolie."],
                answer=0,
                hints=["Warum war Rutherford überrascht?",
                       "Weil niemand mit Rückwärtsflug rechnete.",
                       "Es muss also etwas sehr Massereiches geben."],
                solution="Nach dem damaligen Modell konnte nichts ein schnelles, schweres Teilchen zurückwerfen. Dass es geschah, erzwang die Annahme eines winzigen, sehr massereichen Kerns.",
                tags=["atombau", "msa"]),
        aufgabe("PS04-C3-012", "C", 3, "choice",
                "Was sagt das Kern-Hülle-Modell über die Anordnung der Elektronen?",
                options=["Nichts — dazu brauchte es Bohrs Erweiterung.",
                         "Dass sie auf festen Kreisbahnen laufen.",
                         "Dass sie im Kern sitzen."],
                answer=0,
                hints=["Was konnte der Streuversuch zeigen?",
                       "Nur, dass es einen Kern gibt und die Hülle leer ist.",
                       "Über die Anordnung sagt er nichts."],
                solution="Der Streuversuch belegt Kern und weitgehend leere Hülle. Wie die Elektronen darin angeordnet sind, lässt sich daraus nicht ableiten — das leistet erst das Schalenmodell.",
                misconceptions=[fv("modelle_vermischt", 1,
                                   "Die Kreisbahnen stammen von Bohr, nicht aus dem Streuversuch.")],
                tags=["atombau", "modelle", "msa"]),
        aufgabe("PS04-C3-013", "C", 3, "multi",
                "Ein Modellversuch: Ein Atom wird auf 100 m Durchmesser vergrößert.",
                fields=[
                    {"label": "Kerndurchmesser im Modell in Zentimetern", "answer": 1, "unit_label": "cm", "tolerance": 0.1},
                    {"label": "Um welchen Faktor wurde vergrößert (Atom real 0,1 nm)?", "answer": 1000000000000, "tolerance": 1e10}
                ],
                hints=["Der Kern ist 10 000-mal kleiner als das Atom.",
                       "100 m : 10 000 = 0,01 m = 1 cm.",
                       "Faktor: 100 m : 0,1 nm = 100 : 1·10⁻¹⁰ m."],
                solution="Kern im Modell: 100 m : 10 000 = 0,01 m = 1 cm\nVergrößerungsfaktor: 100 m : 10⁻¹⁰ m = 10¹² — also eine Billion.",
                tags=["atombau", "rechnen", "msa"], spiral=["K-QUANT"]),
        aufgabe("PS04-C4-014", "C", 4, "choice",
                "Ein Schüler fragt: „Wenn das Atom fast leer ist, warum falle ich dann nicht durch den Stuhl?“ Welche Antwort ist fachlich richtig?",
                options=["Die Elektronenhüllen stoßen sich gegenseitig elektrisch ab — Berührung ist eine Abstoßung, kein Aufeinandertreffen von Materie.",
                         "Weil die Atome des Stuhls dicht gepackt sind.",
                         "Weil der Stuhl aus Holz und nicht aus Gold besteht."],
                answer=0,
                hints=["Was berührt sich, wenn zwei Körper sich berühren?",
                       "Die Elektronenhüllen.",
                       "Und gleiche Ladungen stoßen sich ab."],
                solution="Beim Berühren nähern sich die negativ geladenen Elektronenhüllen und stoßen sich ab. Man spürt diese Abstoßung als Festigkeit. Dass die Atome selbst fast leer sind, widerspricht dem nicht.",
                tags=["atombau", "transfer", "msa"], spiral=["K-ATOM"])
    ]
})

if __name__ == "__main__":
    schreiben("ps", E, "Bereich PS · Einheiten 3 und 4")
